/* AMS — Custom, AMS & Memory IP Development. Sixteen activities.
   Stage w18–60 (42w), 296 M/M — the largest enablement stage. */
module.exports = {

'AMS-01': {
  stage:'amsIp', window:[0,6], criticalPath:false,
  purpose:[
    'Turn each custom block from a name on the make list into <b>a specification with budgets</b>—jitter, BER, PSRR, area, power—that a circuit designer can start against and a reviewer can hold them to.',
    'Analog specifications are budgets before they are targets. Total jitter is divided between the PLL, the distribution network and the PHY; each owner gets a share, and a share nobody allocated becomes an argument at integration when the eye closes and no one can say whose fault it is.',
  ],
  steps:[
    {n:1, text:'Custom block list confirmation from the make decisions', tat:0.5, lane:'main'},
    {n:2, text:'System-level budget decomposition — jitter, noise, BER', tat:1.5, lane:'main'},
    {n:3, text:'Per-block specification authoring', tat:2, lane:'main'},
    {n:4, text:'Area and power allocation per block', tat:1, lane:'par'},
    {n:5, text:'PSRR and supply sensitivity requirements', tat:1, lane:'par'},
    {n:6, text:'Specification review and owner acceptance', tat:2, lane:'main'},
  ],
  flowNote:'Step 2 is the one that prevents the integration argument. A jitter budget divided explicitly between PLL, distribution and PHY gives each owner a number; an unallocated total gives each owner a reason to believe the problem is somewhere else.',
  consumes:[
    'Make decisions from IPR-03',
    'Custom memory scope from PDK-06',
    'Interface specifications from ARCH-04',
    'Power and clock architecture from ARCH-05',
    'Block PPA budgets from ARCH-06',
  ],
  produces:[
    'Custom block list with owners',
    'System-level budget decomposition',
    'Per-block specifications with jitter, BER, PSRR and area budgets',
    'Per-block AMS specifications',
    'Area and power allocation per block',
    'PSRR and supply sensitivity requirements',
    'Specification review and acceptance record',
  ],
  producedBy:[1,2,2,3,4,5,6],
  rel:[
    {id:'AMS-D1', rel:'produces', text:'<b>AMS IP specifications and design review packages.</b> This activity is the deliverable—the specifications every other AMS activity is executed and reviewed against.'},
    {id:'AMS-D8', rel:'feeds', text:'<b>Integration guide.</b> The specification is what the integration guide\'s limitations are stated relative to.'},
  ],
  risks:[
    '<b>Budgets stated as totals rather than allocations.</b> An unallocated jitter budget produces three designers each assuming the others left them room.',
    '<b>Specifications written without the PHY vendor.</b> Where a PHY is bought, its jitter tolerance bounds what the PLL must deliver, and the two have to be written together.',
    '<b>Area allocated before the architecture is understood.</b> Analog area is set by matching, isolation and routing, and an allocation made from a digital estimate is not usable.',
    '<b>PSRR requirements omitted.</b> Supply sensitivity is what turns a working block into a failing one once the digital neighbors switch, and it is rarely specified up front.',
    '<b>No owner acceptance.</b> A specification the designer has not accepted is one they will design around rather than to.',
  ],
  roles:[
    {r:'AMS architect', d:'Owns the budgets and the specification set'},
    {r:'Block circuit owners', d:'Accept or contest their specification'},
    {r:'Interface architect', d:'Interface-side requirements and PHY interaction'},
    {r:'Power architect', d:'Supply, PSRR and rail assumptions'},
    {r:'AMS lead', d:'Review chair and arbitration'},
  ],
  effort:[['Per-block specification authoring',3], ['Budget decomposition',2], ['Area and power allocation',1.5], ['Review and acceptance',1.5]],
  entry:[
    'Make decisions available from IPR-03',
    'Custom memory scope handed over by PDK-06',
    'Interface and clock architecture defined by ARCH-04 and ARCH-05',
  ],
  exit:[
    'Every system budget decomposed into per-block allocations',
    'Each specification accepted by its named owner',
    'Area and power allocations reconciled against ARCH-06',
  ],
  dependsOn:['IPR-03','PDK-06','ARCH-04','ARCH-05','ARCH-06'],
  dependsNote:null,
  feedsInto:['AMS-02','AMS-03','AMS-04','AMS-05','AMS-11'],
  measuredBy:[
    'Blocks with an accepted specification',
    'System budgets fully allocated',
    'Specification changes after design start',
  ],
},

'AMS-02': {
  stage:'amsIp', window:[4,30], criticalPath:true,
  purpose:[
    'Design the <b>clock generation</b> the whole chip runs on—PLLs, their loop dynamics, their supply immunity and their jitter—and close them across process, voltage and temperature.',
    'A PLL is small, slow to build and impossible to work around. Twenty-six weeks for a block of a few hundred microns square looks disproportionate until the first silicon that will not lock over temperature, at which point the entire program is waiting on a circuit nobody can patch.',
  ],
  steps:[
    {n:1, text:'Architecture selection — integer, fractional, ring or LC', tat:2, lane:'main'},
    {n:2, text:'Loop dynamics and phase noise budget', tat:2, lane:'main'},
    {n:3, text:'VCO design and tuning range definition', tat:4, lane:'main'},
    {n:4, text:'Charge pump, loop filter and divider design', tat:4, lane:'main'},
    {n:5, text:'Supply regulation and PSRR strategy', tat:3, lane:'par'},
    {n:6, text:'Lock detection, calibration and startup sequencing', tat:3, lane:'par'},
    {n:7, text:'Layout with matching, shielding and isolation', tat:6, lane:'main'},
    {n:8, text:'Post-layout jitter closure across PVT', tat:5, lane:'main'},
    {n:9, text:'Clock distribution interface definition with physical design', tat:3, lane:'par'},
    {n:10, text:'Characterization and macro release', tat:3, lane:'main'},
  ],
  flowNote:'Step 8 is where the schedule risk lives. Post-layout jitter is routinely worse than pre-layout by more than the margin, and the fix is a layout change that takes the six weeks of step 7 again.',
  consumes:[
    'Jitter and PSRR budgets from AMS-01',
    'Clock architecture and DVFS points from ARCH-05',
    'Reference clock specification from the system requirements',
    'Node device models and PDK from PDK-01',
    'Supply and rail topology from ARCH-05',
  ],
  produces:[
    'PLL architecture selection record',
    'Loop dynamics and phase noise budget',
    'VCO design with its tuning range',
    'PLL architecture selection and loop design',
    'VCO and loop component designs',
    'Supply regulation and calibration scheme',
    'Lock detection, calibration and startup sequencing design',
    'PLL layout with matching and shielding',
    'Post-layout jitter results across PVT',
    'Clock distribution interface definition',
    'Characterized PLL macro with views',
  ],
  producedBy:[1,2,3,4,4,5,6,7,8,9,10],
  rel:[
    {id:'AMS-D1', rel:'feeds', text:'<b>AMS IP specifications and design review packages.</b> The PLL review package is the largest single item in the set.'},
    {id:'AMS-D2', rel:'feeds', text:'<b>Characterization reports across PVT and Monte Carlo.</b> Jitter across PVT is the headline number in the report.'},
    {id:'AMS-D5', rel:'feeds', text:'<b>Hard macro GDS with abstract views.</b> The PLL is one of the macros <code>AMS-15</code> abstracts and hands to physical design.'},
  ],
  risks:[
    '<b>Post-layout jitter worse than budget.</b> The commonest analog schedule failure, and the fix is a layout iteration measured in weeks, not days.',
    '<b>PSRR ignored until integration.</b> A PLL that meets jitter on a clean supply and fails beside switching digital logic has met a specification nobody can use.',
    '<b>Tuning range too narrow across corners.</b> A VCO that cannot cover the DVFS range at the slow corner is a DVFS policy that has to be reduced in silicon.',
    '<b>Lock time and startup unspecified.</b> Boot sequencing depends on lock time, and discovering it at bring-up delays every subsequent test.',
    '<b>One PLL designed for several very different uses.</b> Sharing one design across HBM, SerDes and core clocking usually means it is optimal for none.',
  ],
  roles:[
    {r:'PLL circuit designer', d:'Owns the architecture, the loop and the closure'},
    {r:'Analog layout engineer', d:'Matching, shielding and isolation'},
    {r:'Verification engineer, AMS', d:'Behavioural model and co-simulation'},
    {r:'Clocking architect', d:'Distribution interface and jitter budget'},
    {r:'AMS lead', d:'Review gates and schedule'},
  ],
  effort:[['VCO and loop design',9], ['Layout',7], ['Post-layout jitter closure',6], ['Supply regulation and calibration',5], ['Characterization and release',3], ['Distribution interface',2]],
  entry:[
    'Jitter and PSRR budgets accepted in AMS-01',
    'Clock architecture and DVFS points fixed by ARCH-05',
    'Device models available from the tracked PDK',
  ],
  exit:[
    'Jitter closed post-layout across PVT, not pre-layout',
    'Lock time and startup sequence characterized and documented',
    'Macro released with views and a behavioural model',
  ],
  dependsOn:['AMS-01','ARCH-05','PDK-01'],
  dependsNote:null,
  feedsInto:['AMS-11','AMS-12','AMS-13','AMS-15','PD-05','BU-03'],
  measuredBy:[
    'Post-layout jitter against budget',
    'Tuning range coverage at the slow corner',
    'Layout iterations after first post-layout simulation',
  ],
},

'AMS-03': {
  stage:'amsIp', window:[4,38], criticalPath:true,
  purpose:[
    'Deliver the <b>high-speed interfaces</b>—PCIe or CXL, die-to-die, HBM PHY—either designed from scratch or hardened from a vendor\'s deliverable onto this node and this flavor sheet.',
    'At thirty-four weeks and sixty man-months this is the largest single activity in the entire template, and it is the one most likely to decide the tapeout date. Even a bought PHY is not free: hardening, integration, and closing its analog margins on this process option is a project, and the vendor\'s schedule for it is not the program\'s.',
  ],
  steps:[
    {n:1, text:'PHY strategy per interface — build, buy hardened, or buy soft', tat:2, lane:'main'},
    {n:2, text:'Vendor deliverable ingestion and gap assessment', tat:3, lane:'main'},
    {n:3, text:'Equalization and link training architecture', tat:4, lane:'par'},
    {n:4, text:'TX and RX front-end design or adaptation', tat:7, lane:'main'},
    {n:5, text:'Clock recovery and per-lane timing', tat:5, lane:'par'},
    {n:6, text:'HBM PHY integration and training sequence', tat:6, lane:'main'},
    {n:7, text:'Layout, matching and lane pitch closure', tat:8, lane:'main'},
    {n:8, text:'Post-layout BER and eye closure across PVT', tat:6, lane:'main'},
    {n:9, text:'Compliance simulation against the interface specification', tat:4, lane:'par'},
    {n:10, text:'Macro release and integration support', tat:2, lane:'main'},
  ],
  flowNote:'Step 7 is eight weeks of layout because lane pitch is a floorplan constraint as much as a circuit one—the PHY has to fit the bump pitch <code>ARCH-08</code> defined, and a pitch mismatch found here forces a change at the die edge.',
  consumes:[
    'Interface selections and revisions from ARCH-04',
    'Vendor deliverables and licences from IPR-07',
    'Bump pitch and PHY placement from ARCH-08',
    'Channel budgets from SIPI-08',
    'Jitter budget from AMS-01',
  ],
  produces:[
    'PHY strategy per interface',
    'Vendor deliverable gap assessment',
    'Equalization and link training architecture',
    'TX/RX front-end and clock recovery designs',
    'Clock recovery and per-lane timing design',
    'HBM PHY integration and training sequence',
    'SerDes layout with lane pitch closure',
    'Post-layout BER and eye results across PVT',
    'Compliance simulation results',
    'Released PHY macros with integration support',
  ],
  producedBy:[1,2,3,4,5,6,7,8,9,10],
  rel:[
    {id:'AMS-D2', rel:'produces', text:'<b>Characterization reports across PVT and Monte Carlo.</b> The PHY\'s eye and BER characterization is the report\'s most consequential section.'},
    {id:'AMS-D5', rel:'feeds', text:'<b>Hard macro GDS with abstract views.</b> The PHY macros are the largest and most constrained of the set.'},
    {id:'AMS-D8', rel:'feeds', text:'<b>Integration guide with known limitations and errata.</b> PHY limitations—training corner cases, unsupported modes—are what integration most needs stated.'},
  ],
  risks:[
    '<b>Bought PHY assumed to need no work.</b> Hardening, integration and margin closure on this flavor sheet is a multi-quarter project regardless of who designed the circuit.',
    '<b>Lane pitch incompatible with the bump map.</b> Discovered at layout, it forces a change at the die edge where there is least room to make one.',
    '<b>Compliance simulated late.</b> A PHY that closes its own eye and fails the interface specification\'s compliance mask has to be reworked with no schedule left.',
    '<b>Channel budget not shared with SI.</b> The PHY closes against an assumed channel; if <code>SIPI-07</code> extracts a worse one, the margin was never real.',
    '<b>Vendor support model untested until integration.</b> The first hard question is when a support relationship is discovered to be a ticketing system.',
  ],
  roles:[
    {r:'SerDes and PHY lead', d:'Owns the strategy, the design and the closure'},
    {r:'Analog circuit designers', d:'TX/RX front end and clock recovery'},
    {r:'Analog layout engineers', d:'Lane pitch, matching and shielding'},
    {r:'SI liaison', d:'Channel budget and compliance conditions'},
    {r:'Vendor technical contact', d:'Hardening support and deliverable gaps'},
  ],
  effort:[['TX and RX front-end design',14], ['Layout and pitch closure',13], ['Post-layout BER and eye closure',11], ['HBM PHY integration',8], ['Clock recovery and per-lane timing',7], ['Compliance simulation',5], ['Macro release and support',2]],
  entry:[
    'Interface selections pinned by ARCH-04',
    'Vendor licences executed where PHYs are bought',
    'Bump pitch and PHY placement known from ARCH-08',
  ],
  exit:[
    'BER and eye closed post-layout across PVT at the specified channel',
    'Compliance simulated against the interface specification, not only internally',
    'Macros released with a stated limitation list',
  ],
  dependsOn:['AMS-01','ARCH-04','ARCH-08','IPR-07'],
  dependsNote:null,
  feedsInto:['AMS-12','AMS-13','AMS-15','SIPI-07','SIPI-08','PD-04','BU-05'],
  measuredBy:[
    'Eye margin against the compliance mask',
    'Lane pitch against the bump map constraint',
    'Weeks of vendor-side schedule the program cannot influence',
  ],
},

'AMS-04': {
  stage:'amsIp', window:[6,26], criticalPath:false,
  purpose:[
    'Build the <b>power management cells</b> everything else depends on—LDOs, bandgap references, bias generation—quietly and correctly, because every other block\'s specification assumes them.',
    'These blocks are small, unglamorous and load-bearing. A bandgap that drifts moves every analog threshold on the die; an LDO with insufficient PSRR at the switching frequency turns the PLL\'s careful jitter budget into noise. They are specified against by everyone and reviewed by almost nobody.',
  ],
  steps:[
    {n:1, text:'Supply topology and regulation requirement per domain', tat:1.5, lane:'main'},
    {n:2, text:'Bandgap reference design and trim strategy', tat:3.5, lane:'main'},
    {n:3, text:'LDO design — load range, stability, PSRR', tat:5, lane:'main'},
    {n:4, text:'Bias generation and distribution', tat:3, lane:'par'},
    {n:5, text:'Startup, sequencing and brown-out behavior', tat:2.5, lane:'par'},
    {n:6, text:'Layout with matching and supply isolation', tat:4, lane:'main'},
    {n:7, text:'Post-layout stability and PSRR verification across PVT', tat:4, lane:'main'},
    {n:8, text:'Trim and calibration procedure definition for test', tat:2, lane:'main'},
  ],
  flowNote:'Step 8 is easy to leave until later and expensive to. A trim procedure that test engineering only sees at <code>TEST-05</code> becomes a test-time cost, and a bandgap with no defined trim is a part with a distribution nobody can tighten.',
  consumes:[
    'Supply and rail topology from ARCH-05',
    'PSRR requirements from AMS-01',
    'Load profiles from the digital power estimate',
    'Node device models and precision element availability',
    'Test and trim capability from TEST-01',
  ],
  produces:[
    'Supply topology and regulation plan',
    'Bandgap reference design with trim strategy',
    'LDO designs with stability and PSRR results',
    'Bias generation and distribution scheme',
    'Startup, sequencing and brown-out behavior definition',
    'Regulator layout with supply isolation',
    'Post-layout stability and PSRR results across PVT',
    'Trim and calibration procedure for production test',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'AMS-D2', rel:'feeds', text:'<b>Characterization reports across PVT and Monte Carlo.</b> Bandgap drift and LDO PSRR across corners belong in the same report as the PLL and PHY results.'},
    {id:'AMS-D5', rel:'feeds', text:'<b>Hard macro GDS with abstract views.</b> Power management cells are delivered as macros like any other analog block.'},
    {id:'AMS-D7', rel:'feeds', text:'<b>Reliability report.</b> LDO pass devices and bandgaps carry EM and aging exposure that belongs in the reliability assessment.'},
  ],
  risks:[
    '<b>PSRR specified at DC.</b> The frequency that matters is where the digital load switches, and a regulator flat at DC can be transparent at that frequency.',
    '<b>Stability verified only at nominal load.</b> LDO compensation has to hold across the full load range including the transitions, which is where it usually does not.',
    '<b>Bandgap trim undefined.</b> An untrimmed reference has a distribution wide enough to move every analog threshold, and there is no way to tighten it in production.',
    '<b>Brown-out and startup behavior unspecified.</b> The part\'s behavior at supply ramp is discovered at bring-up, on silicon that cannot be changed.',
    '<b>Reviewed by nobody.</b> Blocks everyone assumes and nobody reviews are the ones that fail in a way that looks like someone else\'s problem.',
  ],
  roles:[
    {r:'Power management circuit designer', d:'Owns LDOs, bandgap and bias'},
    {r:'Analog layout engineer', d:'Matching, isolation and supply routing'},
    {r:'Power architect', d:'Topology, domains and load profiles'},
    {r:'Test engineering liaison', d:'Trim and calibration procedure'},
    {r:'Reliability engineer', d:'EM and aging on pass devices'},
  ],
  effort:[['LDO design',6], ['Bandgap and trim strategy',4.5], ['Layout',4], ['Post-layout verification',3.5], ['Bias generation',2.5], ['Trim procedure for test',1.5]],
  entry:[
    'Supply topology defined by ARCH-05',
    'PSRR and load requirements available from AMS-01',
    'Node precision element characterization available',
  ],
  exit:[
    'PSRR verified at the digital switching frequency, not only at DC',
    'Stability held across the full load range post-layout',
    'Trim procedure agreed with test engineering',
  ],
  dependsOn:['AMS-01','ARCH-05'],
  dependsNote:null,
  feedsInto:['AMS-12','AMS-13','AMS-14','AMS-15','SIPI-05','TEST-05'],
  measuredBy:[
    'PSRR at the switching frequency against requirement',
    'Load range over which stability is proven',
    'Reference distribution before and after trim',
  ],
},

'AMS-05': {
  stage:'amsIp', window:[2,12], criticalPath:true,
  purpose:[
    'Architect the <b>custom SRAM instance</b> the compiler could not deliver—bitcell choice, array organization, sense amplifier topology and replica timing—against the density and Vmin the block budget demands.',
    'This activity exists only because <code>PDK-06</code> opened it. That decision came with a quantified gap and a fixed window, and the architecture chosen here determines whether the rest of the custom memory chain can close inside it. A conservative architecture will not recover the density; an aggressive one may not close Vmin.',
  ],
  steps:[
    {n:1, text:'Scope confirmation against the PDK-06 decision and gap', tat:0.75, lane:'main'},
    {n:2, text:'Bitcell selection — foundry cell, pushed rules, or custom', tat:1.75, lane:'main'},
    {n:3, text:'Array organization — banking, segmentation, aspect ratio', tat:2, lane:'main'},
    {n:4, text:'Sense amplifier topology and offset budget', tat:2, lane:'main'},
    {n:5, text:'Replica timing and self-timed path design', tat:1.75, lane:'par'},
    {n:6, text:'Peripheral circuit architecture — decoders, drivers, IO', tat:1.5, lane:'par'},
    {n:7, text:'Density projection against the block budget', tat:3.5, lane:'main'},
    {n:8, text:'Architecture review and freeze', tat:1.5, lane:'par'},
  ],
  flowNote:'Step 7 closes the loop with <code>PDK-05</code>. If the projected density still misses the budget, the answer is to reopen the architecture now rather than to discover it after sixteen weeks of layout in <code>AMS-07</code>.',
  consumes:[
    'Custom instance decision and gap from PDK-06',
    'Density and Vmin measurements from PDK-05',
    'Memory hierarchy requirements from ARCH-03',
    'Block memory budget from ARCH-06',
    'Foundry bitcell options and pushed-rule policy',
  ],
  produces:[
    'Confirmed custom array scope',
    'Bitcell selection with rule implications',
    'Array organization and banking scheme',
    'Sense amplifier topology and offset budget',
    'Replica timing scheme',
    'Peripheral circuit architecture',
    'Density projection against budget',
    'Architecture freeze record',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'AMS-D3', rel:'produces', text:'<b>Custom SRAM instance specification with Vmin and sigma-yield report.</b> The specification half of the deliverable; <code>AMS-08</code> supplies the yield half.'},
    {id:'AMS-D1', rel:'feeds', text:'<b>AMS IP specifications and design review packages.</b> The array\'s architecture review is one of the stage\'s formal gates.'},
  ],
  risks:[
    '<b>Architecture that does not recover the gap.</b> A conservative organization produces a custom array with the compiler\'s density and none of the compiler\'s maintenance advantages.',
    '<b>Bitcell pushed beyond foundry appetite.</b> A cell the foundry will not approve is a layout that cannot tape out, and the approval path runs through <code>PDK-06</code>.',
    '<b>Sense amplifier offset budget optimistic.</b> Offset drives Vmin more than any other single choice, and an optimistic budget is discovered in <code>AMS-08</code> when it is far too late to change topology.',
    '<b>Replica timing not proven across corners.</b> Self-timed paths that track at nominal and diverge at the corner produce read failures that look random.',
    '<b>Architecture frozen without the density projection.</b> Freezing before step 7 means committing sixteen weeks of layout to an organization that may not close the gap.',
  ],
  roles:[
    {r:'Memory circuit architect', d:'Owns the array architecture and its freeze'},
    {r:'Bitcell and device engineer', d:'Cell selection and rule implications'},
    {r:'Sense amplifier designer', d:'Topology and offset budget'},
    {r:'Memory layout lead', d:'Density projection and floorplan feasibility'},
    {r:'PDK owner', d:'Foundry pushed-rule approval path'},
  ],
  effort:[['Array organization',4], ['Sense amplifier and offset budget',3.5], ['Bitcell selection',2.5], ['Replica timing',2], ['Density projection and review',2]],
  entry:[
    'Custom instance decision taken by PDK-06 with a quantified gap',
    'Compiler measurements available from PDK-05',
    'Foundry pushed-rule appetite known',
  ],
  exit:[
    'Projected density closes the gap the decision was taken on',
    'Bitcell choice within the foundry\'s stated approval appetite',
    'Architecture frozen with an offset and Vmin budget attached',
  ],
  dependsOn:['PDK-05','PDK-06','ARCH-03','ARCH-06'],
  dependsNote:null,
  feedsInto:['AMS-06','AMS-07','AMS-08','AMS-09','AMS-10'],
  measuredBy:[
    'Projected density against the PDK-05 gap',
    'Offset budget against what the topology can deliver',
    'Architecture reopened after freeze',
  ],
},

'AMS-06': {
  stage:'amsIp', window:[10,20], criticalPath:false,
  purpose:[
    'Design the <b>assist circuits that buy Vmin</b>—wordline boost, negative bitline, VDD collapse—and decide how much of each the array actually needs.',
    'Assist is what makes an aggressive array workable, and it is not free: each technique costs area, power and complexity, and some of them interact badly. The design question is not which assist is best but which combination reaches the Vmin target at the least cost, verified statistically rather than at nominal.',
  ],
  steps:[
    {n:1, text:'Vmin gap analysis against the AMS-05 architecture', tat:1, lane:'main'},
    {n:2, text:'Assist technique selection and interaction study', tat:2, lane:'main'},
    {n:3, text:'Wordline boost circuit design', tat:2, lane:'par'},
    {n:4, text:'Negative bitline circuit design', tat:2, lane:'par'},
    {n:5, text:'VDD collapse and read-assist timing', tat:2, lane:'main'},
    {n:6, text:'Assist control, timing and calibration', tat:2, lane:'main'},
    {n:7, text:'Vmin verification with assist enabled, across corners', tat:3, lane:'main'},
  ],
  flowNote:'Steps 3 and 4 run in parallel and step 2 decides whether both are needed. Write assist and read assist pull in opposite directions on the cell, and enabling both without studying the interaction can leave Vmin worse than either alone.',
  consumes:[
    'Array architecture and Vmin budget from AMS-05',
    'Vmin requirements from ARCH-05 operating points',
    'Bitcell characterization data',
    'Node assist circuit precedents from the foundry',
    'Power budget for the array from ARCH-06',
  ],
  produces:[
    'Vmin gap analysis with assist requirement',
    'Assist technique selection and interaction findings',
    'Wordline boost circuit design',
    'Wordline boost, negative bitline and collapse circuits',
    'VDD collapse and read-assist timing design',
    'Assist control and calibration scheme',
    'Vmin verification results with assist enabled',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'AMS-D3', rel:'feeds', text:'<b>Custom SRAM instance specification with Vmin and sigma-yield report.</b> The Vmin the instance is specified at is the Vmin with assist enabled, and this activity produces it.'},
    {id:'AMS-D2', rel:'feeds', text:'<b>Characterization reports.</b> Assist-enabled Vmin across corners is one of the report\'s core tables.'},
  ],
  risks:[
    '<b>Assist techniques combined without an interaction study.</b> Read and write assist push the cell in opposite directions; enabling both blindly can make Vmin worse.',
    '<b>Assist verified at nominal.</b> Vmin is a statistical quantity; verification at nominal proves nothing about the tail that decides yield.',
    '<b>Boost levels beyond reliability limits.</b> Wordline boost stresses the cell, and a level chosen for Vmin alone shortens life in a way <code>AMS-14</code> will find late.',
    '<b>Assist timing not calibrated.</b> Fixed assist timing that works at one corner and misfires at another produces intermittent failures indistinguishable from a marginal cell.',
    '<b>Area cost of assist unbudgeted.</b> Assist circuits sit in the periphery and can consume the density the custom array was built to recover.',
  ],
  roles:[
    {r:'Memory circuit designer', d:'Owns the assist circuits and their verification'},
    {r:'Bitcell and device engineer', d:'Cell response to assist and reliability limits'},
    {r:'Statistical analysis engineer', d:'Vmin verification across the distribution'},
    {r:'Reliability engineer', d:'Boost stress and aging implications'},
    {r:'Memory architect', d:'Area and power cost against the recovered density'},
  ],
  effort:[['Assist circuit design',4.5], ['Vmin verification',3], ['Assist control and calibration',2.5], ['Interaction study',2]],
  entry:[
    'Array architecture frozen by AMS-05',
    'Vmin target set from the operating points in ARCH-05',
    'Bitcell characterization data available',
  ],
  exit:[
    'Vmin target met statistically, not at nominal',
    'Assist interactions studied rather than assumed',
    'Boost levels within the reliability limits AMS-14 will check',
  ],
  dependsOn:['AMS-05','ARCH-05'],
  dependsNote:null,
  feedsInto:['AMS-07','AMS-08','AMS-10','AMS-14'],
  measuredBy:[
    'Vmin with assist against the target',
    'Area cost of assist against the recovered density',
    'Assist-related failures found in silicon',
  ],
},

'AMS-07': {
  stage:'amsIp', window:[18,34], criticalPath:true,
  purpose:[
    'Lay out the custom array at <b>pushed rules, and get the foundry to approve it</b>—because a layout the foundry will not sign is a layout that cannot tape out.',
    'Sixteen weeks of layout is what the density recovery actually costs. Pushed rules are the mechanism, and they carry an approval process with its own duration and its own possibility of refusal. Running layout and approval in sequence would not fit the window, so they run together, which means designing against rules that are not yet certain.',
  ],
  steps:[
    {n:1, text:'Pushed-rule set proposal and foundry pre-alignment', tat:2, lane:'main'},
    {n:2, text:'Bitcell array layout at pushed rules', tat:4, lane:'main'},
    {n:3, text:'Peripheral and assist circuit layout', tat:3.5, lane:'main'},
    {n:4, text:'Dummy, fill and density compliance', tat:2, lane:'par'},
    {n:5, text:'Foundry approval submission and iteration', tat:5, lane:'par'},
    {n:6, text:'DRC closure including pushed-rule waivers', tat:3, lane:'main'},
    {n:7, text:'LVS and antenna closure', tat:2, lane:'main'},
    {n:8, text:'Layout freeze and extraction handoff', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 5 runs in parallel out of necessity rather than choice. Waiting for approval before laying out would not fit the window, so the array is laid out against rules that may still be refused—which is why step 1\'s pre-alignment matters more than its two weeks suggest.',
  consumes:[
    'Array architecture from AMS-05',
    'Assist circuits from AMS-06',
    'Pushed-rule policy and approval path from PDK-06',
    'Design rule manual and exceptions from PDK-02',
    'Density target from the block budget',
  ],
  produces:[
    'Pushed-rule set with foundry pre-alignment',
    'Bitcell array and peripheral layout',
    'Peripheral and assist circuit layout',
    'Density and fill compliance record',
    'Foundry approval record and waivers',
    'DRC closure record with pushed-rule waivers',
    'DRC, LVS and antenna clean layout',
    'Frozen layout with extraction handoff',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'AMS-D6', rel:'produces', text:'<b>Per-macro DRC / LVS clean signoff, pushed rules approved by foundry.</b> This activity is the deliverable, and the approval is the half that cannot be produced internally.'},
    {id:'AMS-D3', rel:'feeds', text:'<b>Custom SRAM instance specification.</b> The achieved density is a layout result, and it is what the specification finally states.'},
  ],
  risks:[
    '<b>Foundry refuses a pushed rule after layout is built on it.</b> The mitigation is pre-alignment in step 1, and it is the single most valuable two weeks in the activity.',
    '<b>Density target missed despite the pushed rules.</b> The array then costs sixteen weeks and delivers the compiler\'s density, which is the worst available outcome.',
    '<b>Approval iterations underestimated.</b> Each foundry round trip runs to weeks, and the five-week allowance assumes no more than two.',
    '<b>Fill and density compliance left to the end.</b> Fill interacts with the array\'s matching and can undo careful layout if applied late.',
    '<b>Layout frozen before extraction is proven.</b> An array that extracts badly has to be re-laid out, and the extraction handoff is where that is found.',
  ],
  roles:[
    {r:'Memory layout lead', d:'Owns the layout and the density result'},
    {r:'Layout engineers', d:'Array, periphery and assist layout'},
    {r:'PDK owner', d:'Foundry approval submission and iteration'},
    {r:'Physical verification engineer', d:'DRC, LVS and antenna closure'},
    {r:'Foundry technical contact', d:'Pushed-rule review and approval'},
  ],
  effort:[['Array layout',7], ['Peripheral and assist layout',5.5], ['Foundry approval iteration',3.5], ['DRC and LVS closure',4], ['Fill and density compliance',2]],
  entry:[
    'Array architecture frozen by AMS-05',
    'Assist circuits available from AMS-06',
    'Foundry pushed-rule approval path agreed in PDK-06',
  ],
  exit:[
    'Every pushed rule approved by the foundry in writing',
    'Achieved density meets the target the decision was taken on',
    'Layout DRC, LVS and antenna clean, and extractable',
  ],
  dependsOn:['AMS-05','AMS-06','PDK-02','PDK-06'],
  dependsNote:null,
  feedsInto:['AMS-08','AMS-10','AMS-12','AMS-15','SO-02'],
  measuredBy:[
    'Pushed rules approved against those proposed',
    'Achieved density against the target',
    'Foundry approval iterations against the allowance',
  ],
},

'AMS-08': {
  stage:'amsIp', window:[20,30], criticalPath:false,
  purpose:[
    'Prove the array works <b>at the tail of the distribution rather than at nominal</b>—sigma-Vmin, bitcell variation, sense amplifier offset—using importance sampling because brute-force Monte Carlo cannot reach six sigma.',
    'A memory array of this size fails at the tail by definition: with hundreds of millions of cells, the six-sigma cell is not a hypothetical, it is present in every part. Nominal simulation says nothing about it, and the yield the cost model assumed depends entirely on where that tail sits.',
  ],
  steps:[
    {n:1, text:'Statistical methodology selection — importance sampling, scaled sigma', tat:1.5, lane:'main'},
    {n:2, text:'Bitcell variation model validation against silicon data', tat:2, lane:'main'},
    {n:3, text:'Sigma-Vmin analysis for read, write and retention', tat:3, lane:'main'},
    {n:4, text:'Sense amplifier offset distribution analysis', tat:2, lane:'par'},
    {n:5, text:'Peripheral and timing variation contribution', tat:1.5, lane:'par'},
    {n:6, text:'Array-level yield projection with redundancy applied', tat:2, lane:'main'},
    {n:7, text:'Statistical margin report and signoff', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 2 is the step that makes the rest meaningful. A variation model that has not been validated against silicon produces a six-sigma number with an unknown error, and the number is then used to justify a yield assumption in the cost model.',
  consumes:[
    'Array architecture from AMS-05',
    'Assist circuits and Vmin results from AMS-06',
    'Layout parasitics from AMS-07',
    'Foundry variation models and silicon data',
    'Redundancy scheme from AMS-09',
  ],
  produces:[
    'Statistical methodology and its validation',
    'Bitcell variation model validation record',
    'Sigma-Vmin results for read, write and retention',
    'Sense amplifier offset distribution analysis',
    'Offset and peripheral variation contributions',
    'Array yield projection with redundancy',
    'Statistical margin report',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'AMS-D3', rel:'produces', text:'<b>Custom SRAM instance specification with Vmin and sigma-yield report.</b> The yield half of the deliverable, and the half the cost model depends on.'},
    {id:'AMS-D2', rel:'feeds', text:'<b>Characterization reports across PVT and Monte Carlo.</b> The statistical results sit alongside the corner results, and the two say different things.'},
  ],
  risks:[
    '<b>Brute-force Monte Carlo used at the tail.</b> Reaching six sigma by direct sampling is computationally impossible; a run that terminates has not reached the tail it claims.',
    '<b>Variation model unvalidated.</b> The six-sigma answer inherits the model\'s error, and nobody knows its size.',
    '<b>Redundancy assumed to cover the tail.</b> Repair fixes a bounded number of failing bits; a distribution problem produces more than the repair scheme can absorb.',
    '<b>Retention overlooked.</b> Read and write Vmin get the attention; retention failures at low voltage and high temperature are found in qualification.',
    '<b>Result reported without the methodology.</b> A sigma number quoted without stating how it was obtained cannot be compared or challenged.',
  ],
  roles:[
    {r:'Statistical analysis engineer', d:'Owns the methodology and the sigma results'},
    {r:'Memory circuit designer', d:'Interprets results back into circuit changes'},
    {r:'Device and bitcell engineer', d:'Variation model validation against silicon'},
    {r:'Yield engineer', d:'Array yield projection and cost model input'},
    {r:'AMS lead', d:'Signs the statistical margin report'},
  ],
  effort:[['Sigma-Vmin analysis',4], ['Variation model validation',2.5], ['Offset and peripheral analysis',2.5], ['Yield projection',2], ['Report and signoff',1]],
  entry:[
    'Array architecture and assist circuits complete',
    'Layout parasitics available from AMS-07',
    'Foundry variation models and silicon data accessible',
  ],
  exit:[
    'Sigma targets met for read, write and retention',
    'Variation model validated against silicon, not assumed',
    'Yield projection handed to the cost model with its methodology',
  ],
  dependsOn:['AMS-05','AMS-06','AMS-07','AMS-09','PDK-05'],
  dependsNote:null,
  feedsInto:['AMS-10','AMS-14','DEF-04','MP-05'],
  measuredBy:[
    'Sigma achieved against target for each failure mode',
    'Variation model error against silicon',
    'Array yield projection against the cost model assumption',
  ],
},

'AMS-09': {
  stage:'amsIp', window:[16,22], criticalPath:false,
  purpose:[
    'Build <b>redundancy and repair into the array</b> and make it match the BISR architecture DFT is designing—spare rows and columns, fuse allocation, repair algorithm, and the interface between them.',
    'Redundancy is worth several points of yield and only if the two halves agree. The array provides spares and a repair interface; <code>DFT-03</code> provides the BIST engine and the repair analysis. A mismatch between them is found at pattern generation, when both are effectively frozen.',
  ],
  steps:[
    {n:1, text:'Redundancy scheme selection — row, column, or both', tat:1, lane:'main'},
    {n:2, text:'Spare allocation against the projected defect distribution', tat:1.5, lane:'main'},
    {n:3, text:'Repair interface definition with the BISR architecture', tat:1.25, lane:'main'},
    {n:4, text:'Fuse and repair storage allocation', tat:1, lane:'par'},
    {n:5, text:'Repair algorithm agreement with DFT', tat:1, lane:'par'},
    {n:6, text:'Redundancy verification and yield contribution analysis', tat:2.25, lane:'main'},
  ],
  flowNote:'Steps 3 and 5 are joint work with <code>DFT-03</code> rather than handoffs. Both sides can specify a repair scheme that is internally consistent and mutually incompatible, and only writing them together prevents it.',
  consumes:[
    'Array architecture from AMS-05',
    'BISR architecture intent from DFT-03',
    'Defect density projection from TECH-07',
    'Fuse map and lifecycle model from ARCH-07',
    'Yield target from the cost model',
  ],
  produces:[
    'Redundancy scheme selection record',
    'Redundancy scheme with spare allocation',
    'Repair interface definition',
    'Fuse and repair storage allocation',
    'Repair interface specification, agreed with DFT',
    'Repair algorithm agreement',
    'Redundancy yield contribution analysis',
  ],
  producedBy:[1,2,3,4,5,5,6],
  rel:[
    {id:'AMS-D3', rel:'feeds', text:'<b>Custom SRAM instance specification.</b> Repairable and unrepairable yield are different numbers, and the specification has to state which it quotes.'},
    {id:'AMS-D8', rel:'feeds', text:'<b>Integration guide.</b> The repair interface is one of the integration points most likely to be misunderstood, and it belongs in the guide.'},
  ],
  risks:[
    '<b>Repair interface specified independently by both sides.</b> Two consistent specifications that disagree with each other, discovered at ATPG when both are frozen.',
    '<b>Spare allocation not matched to the defect distribution.</b> Row spares against a column-clustered defect mode repair nothing.',
    '<b>Fuse capacity insufficient.</b> Repair data has to be stored; an allocation made without counting the worst-case repair set produces parts that cannot be repaired.',
    '<b>Redundancy credited twice.</b> Yield projections that apply repair in both the array analysis and the product model double-count the benefit.',
    '<b>Repair algorithm assumed rather than agreed.</b> The BIST engine implements one algorithm; the array assumes another, and the mismatch is silent until silicon.',
  ],
  roles:[
    {r:'Memory circuit designer', d:'Owns the redundancy scheme and the array side'},
    {r:'DFT engineer', d:'BISR architecture and the repair algorithm'},
    {r:'Yield engineer', d:'Defect distribution and repair effectiveness'},
    {r:'Fuse and lifecycle engineer', d:'Repair storage allocation'},
    {r:'Memory architect', d:'Area cost of spares against yield gain'},
  ],
  effort:[['Redundancy scheme and spare allocation',2], ['Repair interface with DFT',1.5], ['Yield contribution analysis',1.5], ['Fuse allocation and algorithm agreement',1]],
  entry:[
    'Array architecture available from AMS-05',
    'BISR architecture intent available from DFT-03',
    'Defect density projection from TECH-07',
  ],
  exit:[
    'Repair interface written jointly with DFT, not in parallel',
    'Spare allocation matched to the projected defect modes',
    'Fuse capacity sized against the worst-case repair set',
  ],
  dependsOn:['AMS-05','DFT-03','TECH-07'],
  dependsNote:null,
  feedsInto:['AMS-08','AMS-10','DFT-03','DFT-10','TEST-05'],
  measuredBy:[
    'Repair interface mismatches found at pattern generation',
    'Yield gain from repair against projection',
    'Fuse capacity against worst-case repair need',
  ],
},

'AMS-10': {
  stage:'amsIp', window:[28,38], criticalPath:true,
  purpose:[
    'Generate the <b>views the custom array needs to behave like a compiler instance</b>—timing, power, physical, functional—characterized across the same corners, so nothing downstream has to treat it as a special case.',
    'A custom array that cannot be dropped into the flow like a compiler macro has not finished. Synthesis, place-and-route, timing signoff and verification all expect a standard view set; anything missing becomes a manual exception that has to be remembered at every iteration by everyone.',
  ],
  steps:[
    {n:1, text:'View requirement definition against the tool matrix', tat:1, lane:'main'},
    {n:2, text:'Timing characterization across the signoff corners', tat:3, lane:'main'},
    {n:3, text:'Power and leakage characterization', tat:2, lane:'par'},
    {n:4, text:'Physical abstract, blockage and pin view generation', tat:1.5, lane:'par'},
    {n:5, text:'Functional and behavioural model generation', tat:1.5, lane:'par'},
    {n:6, text:'Compiler-equivalence check against a reference instance', tat:2, lane:'main'},
    {n:7, text:'View release and integration verification', tat:4, lane:'main'},
  ],
  flowNote:'Step 6 is the test that matters. Dropping the custom instance into the flow in place of a compiler instance and confirming the tools behave identically is what proves the view set is complete—reading the file list does not.',
  consumes:[
    'Layout and extraction from AMS-07',
    'Vmin and assist results from AMS-06',
    'Statistical results from AMS-08',
    'Signoff corner definition from PDK-11',
    'Tool view requirements from PDK-08',
  ],
  produces:[
    'View requirement definition against the tool matrix',
    'Timing views across the signoff corners',
    'Power and leakage views',
    'Physical abstract and blockage views',
    'Functional and behavioural models',
    'Compiler-equivalence check results',
    'Released view set',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'AMS-D4', rel:'produces', text:'<b>Custom memory views characterized to compiler equivalence.</b> This activity is the deliverable, and equivalence is the standard it is measured against.'},
    {id:'AMS-D5', rel:'feeds', text:'<b>Hard macro GDS with abstract views.</b> The custom array is delivered into the macro set on the same terms as the analog blocks.'},
  ],
  risks:[
    '<b>Characterized at fewer corners than signoff runs.</b> A missing corner turns into an extrapolation at <code>SO-02</code>, which the foundry will not accept.',
    '<b>Equivalence assumed from the file list.</b> A complete-looking view set can still behave differently in the tools, and only a substitution test finds it.',
    '<b>Behavioural model diverging from the circuit.</b> Verification passes against a model that does not match the array, and the mismatch reaches silicon.',
    '<b>Abstract blockages wrong.</b> Over-blocking wastes routing resource; under-blocking produces shorts found at <code>SO-02</code>.',
    '<b>Views released before the layout freezes.</b> Characterizing against a layout that then changes means doing the whole activity twice.',
  ],
  roles:[
    {r:'Memory characterization engineer', d:'Owns the view set and its characterization'},
    {r:'CAD methodology engineer', d:'View requirements and equivalence testing'},
    {r:'Memory circuit designer', d:'Behavioural model fidelity'},
    {r:'Physical design liaison', d:'Abstract and blockage correctness'},
    {r:'Signoff methodology engineer', d:'Corner coverage against the signoff set'},
  ],
  effort:[['Timing characterization',4], ['Power and leakage characterization',2.5], ['Equivalence checking',2], ['Physical and functional views',2], ['Release and integration verification',1.5]],
  entry:[
    'Layout frozen and extractable from AMS-07',
    'Signoff corners defined by PDK-11',
    'Tool view requirements known from PDK-08',
  ],
  exit:[
    'Characterized at every corner signoff will run',
    'Equivalence proven by substitution, not by inspection',
    'Views released only after the layout freeze',
  ],
  dependsOn:['AMS-06','AMS-07','AMS-08','AMS-09','PDK-11'],
  dependsNote:null,
  feedsInto:['AMS-15','SYN-02','PD-02','SO-02','DV-11'],
  measuredBy:[
    'Corners characterized against signoff corners',
    'Equivalence test results against a reference instance',
    'View defects found downstream',
  ],
},

'AMS-11': {
  stage:'amsIp', window:[6,22], criticalPath:false,
  purpose:[
    'Run the <b>schematic-level design and pre-layout simulation</b> that every analog block passes through—the common engineering discipline underneath the PLL, the PHY, the regulators and the array periphery.',
    'This is the shared substrate rather than a block: topology exploration, device sizing, pre-layout corner simulation and the design reviews that gate a block into layout. Separating it makes the schedule honest—a block that has not passed pre-layout review is not ready for the sixteen weeks of layout that follow.',
  ],
  steps:[
    {n:1, text:'Design environment and testbench framework setup', tat:1.5, lane:'main'},
    {n:2, text:'Topology exploration per block', tat:3, lane:'main'},
    {n:3, text:'Device sizing and operating point definition', tat:3.5, lane:'main'},
    {n:4, text:'Pre-layout corner simulation', tat:3, lane:'main'},
    {n:5, text:'Pre-layout Monte Carlo and mismatch analysis', tat:2.5, lane:'par'},
    {n:6, text:'Testbench and regression suite per block', tat:2.5, lane:'par'},
    {n:7, text:'Pre-layout design review and layout entry gate', tat:5, lane:'main'},
  ],
  flowNote:'Step 7 is a gate rather than a meeting. Layout is the longest and least reversible part of an analog block, and letting a schematic that has not closed at the corners enter layout guarantees that the corner failure is found after the layout is built.',
  consumes:[
    'Block specifications from AMS-01',
    'Node device models from the tracked PDK',
    'Design environment and simulator versions from PDK-08',
    'Reference designs from previous programs',
    'Reliability rules and limits from the DRM',
  ],
  produces:[
    'Design environment and testbench framework',
    'Topology selection per block',
    'Sized schematics with operating points',
    'Pre-layout corner simulation results',
    'Pre-layout corner and Monte Carlo results',
    'Per-block regression suites',
    'Layout entry gate records',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'AMS-D1', rel:'feeds', text:'<b>AMS IP specifications and design review packages.</b> The pre-layout review package is the formal record that a block was fit to enter layout.'},
    {id:'AMS-D2', rel:'feeds', text:'<b>Characterization reports.</b> Pre-layout corner results are the baseline post-layout results are compared against.'},
  ],
  risks:[
    '<b>Blocks entering layout without passing the gate.</b> Sixteen weeks of layout on a schematic that fails at the corner is the most expensive way to discover a topology problem.',
    '<b>Corner simulation run at typical mismatch.</b> Mismatch dominates analog corner behavior, and a corner run without it is a nominal run in disguise.',
    '<b>Testbenches written per block by different people.</b> Inconsistent testbenches make results incomparable across blocks and unusable as a regression.',
    '<b>Device models used from an unfrozen PDK.</b> Analog is far more model-sensitive than digital, and a model update mid-design can invalidate the sizing.',
    '<b>No regression suite.</b> Every subsequent change is then verified by hand, and the coverage of that verification degrades under schedule pressure.',
  ],
  roles:[
    {r:'Analog design leads', d:'Topology, sizing and pre-layout closure per block'},
    {r:'AMS methodology engineer', d:'Environment, testbench framework and regressions'},
    {r:'Design reviewers', d:'Layout entry gate'},
    {r:'AMS architect', d:'Confirms designs meet their allocated budgets'},
    {r:'PDK owner', d:'Model version control for analog design'},
  ],
  effort:[['Device sizing and operating points',5.5], ['Topology exploration',4.5], ['Pre-layout corner simulation',4], ['Testbench and regression suites',3], ['Monte Carlo and mismatch',2], ['Design reviews',1]],
  entry:[
    'Block specifications accepted in AMS-01',
    'Device models available from a tracked PDK version',
    'Simulator versions qualified by PDK-08',
  ],
  exit:[
    'Every block passes a pre-layout gate before entering layout',
    'Corner simulation includes mismatch, not only process corners',
    'Regression suite exists per block and runs automatically',
  ],
  dependsOn:['AMS-01','PDK-01','PDK-08'],
  dependsNote:null,
  feedsInto:['AMS-12','AMS-13','AMS-14','AMS-16'],
  measuredBy:[
    'Blocks passing the layout entry gate first time',
    'Corner failures found pre-layout against post-layout',
    'Regression coverage per block',
  ],
},

'AMS-12': {
  stage:'amsIp', window:[20,38], criticalPath:true,
  purpose:[
    'Lay out every analog and custom block to <b>DRC, LVS and antenna clean</b>, with the matching, shielding and fill discipline analog requires—and get the layouts extractable.',
    'Eighteen weeks is the largest single block of time in the stage after the PHY, and it is largely irreducible. Analog layout is where matching, isolation and parasitic control are actually implemented, and none of it can be automated or parallelized the way digital place-and-route can.',
  ],
  steps:[
    {n:1, text:'Floorplan and pin placement per macro', tat:2, lane:'main'},
    {n:2, text:'Matching-critical device layout', tat:4, lane:'main'},
    {n:3, text:'Shielding, guarding and isolation structures', tat:3, lane:'main'},
    {n:4, text:'Supply and bias routing with EM compliance', tat:3, lane:'par'},
    {n:5, text:'Fill and density compliance without disturbing matching', tat:2.5, lane:'par'},
    {n:6, text:'DRC closure per macro', tat:4, lane:'main'},
    {n:7, text:'LVS and antenna closure', tat:3, lane:'main'},
    {n:8, text:'Extraction setup and layout freeze', tat:2, lane:'main'},
  ],
  flowNote:'Step 5 is where careful layout is most often undone. Fill applied without regard to matching structures changes the parasitics the whole design was tuned against, and the effect is only seen in post-layout simulation.',
  consumes:[
    'Sized schematics from AMS-11',
    'PLL, PHY and regulator designs from AMS-02 to AMS-04',
    'Design rules and exceptions from PDK-02',
    'Macro placement intent from ARCH-08 and PD-01',
    'Golden environment and decks from PDK-13',
  ],
  produces:[
    'Macro floorplans and pin placement',
    'Matching-critical device layouts',
    'Shielding and isolation structures',
    'EM-compliant supply and bias routing',
    'Fill and density compliance record',
    'Per-macro DRC closure',
    'DRC, LVS and antenna clean layouts',
    'Extraction-ready frozen layouts',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'AMS-D6', rel:'produces', text:'<b>Per-macro DRC / LVS clean signoff.</b> Every analog macro\'s physical signoff, alongside the pushed-rule approvals from <code>AMS-07</code>.'},
    {id:'AMS-D5', rel:'feeds', text:'<b>Hard macro GDS with abstract views.</b> The layout is the GDS half of every macro delivery.'},
  ],
  risks:[
    '<b>Fill applied late and without care.</b> It disturbs the parasitics the design was tuned against, and the damage appears only in post-layout results.',
    '<b>Matching implemented by intent rather than by construction.</b> Common-centroid and dummy structures are a layout discipline; describing them in a review is not implementing them.',
    '<b>EM checked only at signoff.</b> Analog supply routing carries high current density in small geometries, and an EM failure found at <code>SO-03</code> is a layout rebuild.',
    '<b>Pin placement not agreed with physical design.</b> A macro whose pins face the wrong way costs routing resource at the top level for the life of the design.',
    '<b>Layout frozen without an extraction check.</b> A macro that extracts slowly or badly stalls every post-layout simulation that follows.',
  ],
  roles:[
    {r:'Analog layout lead', d:'Owns layout quality and the freeze'},
    {r:'Layout engineers', d:'Per-macro implementation'},
    {r:'Analog designers', d:'Matching intent and parasitic sensitivity'},
    {r:'Physical verification engineer', d:'DRC, LVS and antenna closure'},
    {r:'Physical design liaison', d:'Pin placement and top-level integration'},
  ],
  effort:[['Matching-critical layout',7], ['DRC closure',5], ['Shielding and isolation',4.5], ['LVS and antenna closure',4], ['Supply and bias routing',3.5], ['Fill and extraction setup',2]],
  entry:[
    'Schematics passed the AMS-11 layout entry gate',
    'Design rules and exceptions available from PDK-02',
    'Macro placement intent known from ARCH-08',
  ],
  exit:[
    'Every macro DRC, LVS and antenna clean',
    'Fill applied without disturbing matching structures',
    'Pin placement agreed with physical design before freeze',
  ],
  dependsOn:['AMS-02','AMS-03','AMS-04','AMS-11','PDK-02','PDK-13'],
  dependsNote:null,
  feedsInto:['AMS-13','AMS-14','AMS-15','PD-02','SO-02'],
  measuredBy:[
    'Macros clean at first physical verification run',
    'Post-layout degradation against pre-layout results',
    'EM violations found at signoff',
  ],
},

'AMS-13': {
  stage:'amsIp', window:[22,38], criticalPath:true,
  purpose:[
    'Simulate every block <b>with its layout parasitics extracted</b>, across process, voltage and temperature and across the Monte Carlo distribution—and close whatever the layout took away.',
    'Post-layout is where analog designs are actually judged. Parasitics reduce bandwidth, add mismatch, degrade PSRR and move every margin in the wrong direction. The gap between pre- and post-layout is the real measure of layout quality, and closing it is what the sixteen weeks are for.',
  ],
  steps:[
    {n:1, text:'Extraction flow setup and parasitic model selection', tat:1.5, lane:'main'},
    {n:2, text:'Post-layout functional simulation per block', tat:3, lane:'main'},
    {n:3, text:'PVT corner closure post-layout', tat:4, lane:'main'},
    {n:4, text:'Monte Carlo and mismatch analysis post-layout', tat:3, lane:'par'},
    {n:5, text:'Pre- to post-layout degradation analysis', tat:2, lane:'par'},
    {n:6, text:'Layout iteration requests and re-simulation', tat:4.5, lane:'main'},
    {n:7, text:'Characterization data assembly', tat:3, lane:'main'},
  ],
  flowNote:'Step 6 is planned iteration rather than contingency. Analog blocks essentially always need at least one layout turn after post-layout simulation, and a schedule with no allowance for it is a schedule that will slip on the first block.',
  consumes:[
    'Frozen layouts and extraction from AMS-12',
    'Pre-layout baselines from AMS-11',
    'Signoff corner definition from PDK-11',
    'Extraction decks from PDK-10',
    'Block specifications and budgets from AMS-01',
  ],
  produces:[
    'Extraction flow and parasitic model selection',
    'Post-layout functional and corner results per block',
    'Post-layout PVT corner closure results',
    'Monte Carlo and mismatch results',
    'Degradation analysis pre- to post-layout',
    'Layout iteration requests',
    'Assembled characterization data',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'AMS-D2', rel:'produces', text:'<b>Characterization reports across PVT and Monte Carlo.</b> This activity is the deliverable—the numbers every downstream consumer of these macros relies on.'},
    {id:'AMS-D1', rel:'feeds', text:'<b>AMS IP specifications and design review packages.</b> Post-layout results are what each block\'s final review is held against.'},
  ],
  risks:[
    '<b>No layout iteration in the plan.</b> At least one turn per block is normal; a schedule with none slips on the first block and never recovers.',
    '<b>Corner closure on a subset of blocks.</b> The block skipped for time is the one that fails in silicon, and it is usually skipped because it looked simple.',
    '<b>Parasitic model too coarse.</b> A model that misses coupling produces post-layout results that are optimistic in exactly the cases that matter.',
    '<b>Degradation not analyzed.</b> Knowing a block passed post-layout is less useful than knowing how much margin the layout consumed, which is what predicts the next block.',
    '<b>Monte Carlo run at reduced sample count.</b> Cutting samples to save runtime narrows the distribution and flatters the tail.',
  ],
  roles:[
    {r:'Analog design leads', d:'Own post-layout closure per block'},
    {r:'Extraction engineer', d:'Flow setup and parasitic model selection'},
    {r:'Characterization engineer', d:'Corner and Monte Carlo data assembly'},
    {r:'Analog layout lead', d:'Executes iteration requests'},
    {r:'AMS lead', d:'Schedules iterations and arbitrates margin trades'},
  ],
  effort:[['PVT corner closure',5.5], ['Layout iteration and re-simulation',4.5], ['Post-layout functional simulation',3.5], ['Monte Carlo and mismatch',3], ['Characterization assembly',2.5], ['Extraction setup',1]],
  entry:[
    'Layouts frozen and extractable from AMS-12',
    'Pre-layout baselines available from AMS-11',
    'Extraction decks validated by PDK-10',
  ],
  exit:[
    'Every block closed post-layout at every signoff corner',
    'Degradation from pre-layout quantified per block',
    'Characterization data complete enough to release the macros',
  ],
  dependsOn:['AMS-11','AMS-12','PDK-10','PDK-11'],
  dependsNote:null,
  feedsInto:['AMS-14','AMS-15','SO-02','BU-07'],
  measuredBy:[
    'Blocks closed post-layout at all corners',
    'Margin lost from pre- to post-layout',
    'Layout iterations per block against the allowance',
  ],
},

'AMS-14': {
  stage:'amsIp', window:[28,38], criticalPath:false,
  purpose:[
    'Check every analog macro for the failure modes that <b>appear over time rather than at test</b>—electromigration, IR, aging, ESD and latch-up—because none of them show up in a functional simulation.',
    'Analog blocks carry high current densities in small geometries and run continuously for the product\'s life. A design that passes every corner and fails EM has passed everything the design flow checks and none of what qualification will.',
  ],
  steps:[
    {n:1, text:'Reliability requirement definition per macro', tat:1, lane:'main'},
    {n:2, text:'Electromigration analysis on supply and signal routing', tat:2.5, lane:'main'},
    {n:3, text:'IR drop analysis within macros', tat:1.5, lane:'par'},
    {n:4, text:'Aging and lifetime simulation at the rated conditions', tat:2.5, lane:'main'},
    {n:5, text:'ESD path verification through the macro', tat:2, lane:'par'},
    {n:6, text:'Latch-up and guard structure review', tat:1.5, lane:'par'},
    {n:7, text:'Reliability report and waiver disposition', tat:4, lane:'main'},
  ],
  flowNote:'Step 4 is the one that needs the product\'s actual mission profile. Aging simulated at nominal conditions for a nominal lifetime says nothing about a part that runs at the top of its DVFS range continuously, which is exactly how an accelerator is used.',
  consumes:[
    'Post-layout results and parasitics from AMS-13',
    'Reliability rules from PDK-02 and the DRM',
    'ESD strategy from PDK-07',
    'Mission profile and lifetime requirements from the qualification plan',
    'Assist boost levels from AMS-06',
  ],
  produces:[
    'Reliability requirements per macro',
    'EM analysis results on supply and signal routing',
    'In-macro IR drop results',
    'Aging and lifetime simulation results',
    'ESD path verification and latch-up review',
    'Latch-up and guard structure review findings',
    'Reliability report with waiver dispositions',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'AMS-D7', rel:'produces', text:'<b>Reliability report—EM/IR, ESD, latch-up, aging.</b> This activity is the deliverable, and it is what qualification will be checked against.'},
    {id:'AMS-D8', rel:'feeds', text:'<b>Integration guide.</b> Reliability limits—maximum current, boost duty cycle, operating conditions—are integration constraints and belong in the guide.'},
  ],
  risks:[
    '<b>Aging simulated at nominal conditions.</b> An accelerator runs near its limit continuously; a nominal mission profile understates the stress by a wide margin.',
    '<b>EM checked on supplies only.</b> High-speed signal routing in a PHY carries current densities that matter, and signal EM is routinely omitted.',
    '<b>ESD path assumed from the strategy.</b> The strategy defines the intent; only tracing the path through the actual layout confirms it exists.',
    '<b>Assist boost stress not fed back.</b> The boost levels <code>AMS-06</code> chose for Vmin have an aging cost, and the two activities have to reconcile.',
    '<b>Waivers granted without a lifetime calculation.</b> A reliability waiver without a quantified life impact is a decision nobody can defend at qualification.',
  ],
  roles:[
    {r:'Reliability engineer', d:'Owns the analysis and the report'},
    {r:'Analog designers', d:'Interpret findings back into design changes'},
    {r:'ESD engineer', d:'Path verification and clamp effectiveness'},
    {r:'Layout engineers', d:'Implement routing and guard structure fixes'},
    {r:'Quality liaison', d:'Waiver disposition against qualification requirements'},
  ],
  effort:[['Aging and lifetime simulation',2.5], ['Electromigration analysis',2.5], ['ESD path verification',2], ['IR and latch-up review',1.5], ['Report and waiver disposition',1.5]],
  entry:[
    'Post-layout results available from AMS-13',
    'Mission profile and lifetime requirements defined',
    'ESD strategy fixed by PDK-07',
  ],
  exit:[
    'Aging simulated against the product\'s real mission profile',
    'EM checked on signal routing as well as supplies',
    'Every waiver carries a quantified lifetime impact',
  ],
  dependsOn:['AMS-06','AMS-12','AMS-13','PDK-07'],
  dependsNote:null,
  feedsInto:['AMS-15','SO-07','MP-03','MP-02'],
  measuredBy:[
    'Macros passing EM and aging at rated conditions',
    'Waivers with a quantified lifetime impact',
    'Reliability findings at qualification traceable to a missed check',
  ],
},

'AMS-15': {
  stage:'amsIp', window:[32,40], criticalPath:true,
  purpose:[
    'Wrap every finished block into a <b>hard macro physical design can place and verification can simulate</b>—GDS, abstract, timing views, netlist, power intent and a behavioural model.',
    'This is the handoff the whole stage exists to make. The macro set has to arrive before <code>PD-02</code> places it, and the abstracts specifically have to arrive well before the models do, because floorplan needs the shape long before signoff needs the timing.',
  ],
  steps:[
    {n:1, text:'View requirement confirmation with physical design and verification', tat:1, lane:'main'},
    {n:2, text:'GDS finalization and macro boundary definition', tat:1.5, lane:'main'},
    {n:3, text:'Abstract generation — blockages, pins, routing layers', tat:1.5, lane:'main'},
    {n:4, text:'Timing view generation from characterization data', tat:2, lane:'par'},
    {n:5, text:'CDL netlist and UPF power intent generation', tat:1.5, lane:'par'},
    {n:6, text:'Behavioural and wreal model release', tat:1.5, lane:'par'},
    {n:7, text:'Integration verification on a trial placement', tat:2, lane:'main'},
    {n:8, text:'Macro release and version control', tat:2, lane:'main'},
  ],
  flowNote:'Step 7 is worth the two weeks. Placing every macro in a trial floorplan and running the flow over it finds abstract errors, pin conflicts and missing views before the whole physical design team is depending on them.',
  consumes:[
    'Frozen layouts from AMS-12',
    'Characterization data from AMS-13',
    'Custom memory views from AMS-10',
    'Reliability constraints from AMS-14',
    'View and tool requirements from PDK-08 and PD-01',
  ],
  produces:[
    'Confirmed view requirement list',
    'Finalized GDS per macro',
    'Physical abstracts with blockages and pins',
    'Timing and power views',
    'CDL netlists and UPF power intent',
    'Behavioural and wreal models',
    'Trial placement integration verification results',
    'Released, version-controlled macro set',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'AMS-D5', rel:'produces', text:'<b>Hard macro GDS with abstract views.</b> This activity is the deliverable, and it is the stage\'s milestone—AMS Macro Handoff.'},
    {id:'AMS-D4', rel:'feeds', text:'<b>Custom memory views characterized to compiler equivalence.</b> The custom array joins the macro set here on the same terms as the analog blocks.'},
    {id:'AMS-D2', rel:'feeds', text:'<b>Characterization reports.</b> The views are generated from the characterization data and have to stay consistent with it.'},
  ],
  risks:[
    '<b>Abstracts delivered with the models.</b> Floorplan needs the shape months before signoff needs the timing; a single delivery date serves the later need and misses the earlier one.',
    '<b>Trial placement skipped.</b> Abstract and pin errors are then found by the physical design team, at the point where the whole floorplan depends on them.',
    '<b>Views inconsistent with the characterization.</b> A timing view generated from stale data produces a design closed against numbers the silicon does not have.',
    '<b>Macro released without version control.</b> Two teams on different macro revisions produce a mismatch that is diagnosed as a tool problem.',
    '<b>Power intent omitted.</b> A macro with no UPF view breaks low-power verification and forces a manual exception at every run.',
  ],
  roles:[
    {r:'AMS integration lead', d:'Owns the macro set and its release'},
    {r:'Characterization engineer', d:'Timing and power view generation'},
    {r:'Layout engineer', d:'GDS finalization and abstract generation'},
    {r:'Physical design liaison', d:'Trial placement and abstract validation'},
    {r:'Verification liaison', d:'Behavioural model fidelity and release'},
  ],
  effort:[['Timing and power view generation',2.5], ['Abstract generation',1.5], ['Trial placement verification',1.5], ['GDS finalization',1], ['Netlist, UPF and models',1], ['Release and version control',0.5]],
  entry:[
    'Layouts frozen by AMS-12',
    'Characterization complete from AMS-13',
    'View requirements confirmed with PD and DV',
  ],
  exit:[
    'Abstracts released ahead of models, on the schedule PD needs',
    'Trial placement run and clean before general release',
    'Every macro version-controlled and its views mutually consistent',
  ],
  dependsOn:['AMS-10','AMS-12','AMS-13','AMS-14'],
  dependsNote:null,
  feedsInto:['PD-01','PD-02','SYN-02','DV-07','SO-02'],
  measuredBy:[
    'Macros released against the PD need date',
    'Abstract and view defects found at trial placement',
    'Macro revisions issued after release',
  ],
},

'AMS-16': {
  stage:'amsIp', window:[26,42], criticalPath:false,
  purpose:[
    'Keep the analog and digital halves talking—<b>co-simulation, integration support and the errata that come out of it</b>—through the whole period when the macros are being integrated.',
    'Analog blocks fail at their boundaries: a reset that arrives before a rail is stable, a calibration sequence nobody scheduled, a control interface each side interpreted differently. Co-simulation is where those are found, and the integration guide is where they stop being rediscovered.',
  ],
  steps:[
    {n:1, text:'AMS co-simulation environment setup', tat:2, lane:'main'},
    {n:2, text:'Behavioural model correlation against circuit simulation', tat:2.5, lane:'main'},
    {n:3, text:'Boundary and control interface co-verification', tat:3, lane:'main'},
    {n:4, text:'Startup, calibration and sequencing co-simulation', tat:2.5, lane:'par'},
    {n:5, text:'Integration support to RTL and physical design', tat:5, lane:'par'},
    {n:6, text:'Errata capture and integration guide authoring', tat:3, lane:'main'},
    {n:7, text:'Bring-up support material and debug hooks', tat:5.5, lane:'main'},
  ],
  flowNote:'Step 5 runs across the whole window and is the reason this activity is marked continuous. Integration questions do not arrive in a block; they arrive one at a time for four months, and the engineer who can answer them has to still be assigned.',
  consumes:[
    'Behavioural models from AMS-15',
    'Circuit simulation results from AMS-13',
    'RTL integration environment from RTL-03',
    'Verification methodology from DV-07',
    'Startup and sequencing requirements from ARCH-05',
  ],
  produces:[
    'AMS co-simulation environment',
    'Model correlation results',
    'Boundary and control interface verification results',
    'Startup and calibration co-simulation results',
    'Integration support record for RTL and physical design',
    'Integration guide with known limitations',
    'Errata list and bring-up debug material',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'AMS-D8', rel:'produces', text:'<b>Integration guide with known limitations and errata.</b> This activity is the deliverable, and it is what stops the same integration question being asked four times.'},
    {id:'AMS-D1', rel:'feeds', text:'<b>AMS IP specifications and design review packages.</b> Where co-simulation contradicts a specification, the specification is what gets corrected.'},
  ],
  risks:[
    '<b>Behavioural models never correlated.</b> Digital verification then passes against a model that does not match the circuit, and the mismatch reaches silicon undetected.',
    '<b>Boundary conditions unverified.</b> Reset ordering, rail sequencing and enable timing are where analog blocks actually fail, and none of them are internal to the block.',
    '<b>Support engineer unassigned.</b> Integration questions arrive for months; without a named engineer they are answered by guesswork or not at all.',
    '<b>Errata captured in email.</b> A limitation known to one integrator and nobody else is rediscovered by every other integrator in turn.',
    '<b>Calibration sequence not co-simulated.</b> A calibration that works in the circuit and is never exercised from the digital side is first tried at bring-up.',
  ],
  roles:[
    {r:'AMS verification engineer', d:'Owns co-simulation and model correlation'},
    {r:'AMS integration engineer', d:'Integration support and errata capture'},
    {r:'Analog designers', d:'Answer boundary and behavior questions'},
    {r:'RTL integration lead', d:'Digital-side boundary definition'},
    {r:'Validation liaison', d:'Bring-up debug hooks and support material'},
  ],
  effort:[['Integration support',4], ['Boundary and interface co-verification',2.5], ['Model correlation',2], ['Integration guide and errata',1.5], ['Bring-up support material',1], ['Environment setup',1]],
  entry:[
    'Behavioural models released by AMS-15',
    'RTL integration environment available from RTL-03',
    'Co-simulation tools qualified by PDK-08',
  ],
  exit:[
    'Every behavioural model correlated against circuit simulation',
    'Boundary and sequencing verified, not assumed',
    'Integration guide published and maintained, not held in email',
  ],
  dependsOn:['AMS-11','AMS-13','AMS-15','RTL-03'],
  dependsNote:null,
  feedsInto:['RTL-03','DV-07','PD-02','BU-03','BU-05'],
  measuredBy:[
    'Models correlated against those released',
    'Integration questions answered within a working day',
    'Errata found at bring-up that co-simulation could have caught',
  ],
},

};
