/* ARCH — Architecture. Ten activities, full depth. Stage window w6–24 (18w). */
module.exports = {

'ARCH-01': {
  stage:'architecture', window:[0,14], criticalPath:true,
  purpose:[
    'Build the model the architecture is <b>argued with</b>. Every partitioning, sizing and interface decision in this stage is settled by simulation against the DEF-02 workload suite rather than by opinion.',
    'Fourteen weeks and 28 M/M make this the largest activity in the stage by a wide margin, and that is the right shape. Being wrong in a model costs a re-run; being wrong in RTL costs a quarter; being wrong in silicon costs a respin. The model\'s credibility is the stage\'s credibility—the moment nobody trusts it, every decision reverts to seniority.',
  ],
  steps:[
    {n:1, text:'Model scope and fidelity decision — analytical, trace-driven or cycle-approximate', tat:1, lane:'main'},
    {n:2, text:'Baseline model construction — compute, memory, interconnect', tat:2.5, lane:'main'},
    {n:3, text:'Workload suite integration from DEF-02', tat:1, lane:'par'},
    {n:4, text:'Correlation against previous-generation silicon', tat:1.5, lane:'main'},
    {n:5, text:'Design-space exploration sweeps — cluster count, SRAM capacity, HBM channels', tat:3, lane:'main'},
    {n:6, text:'Interconnect and NoC topology studies', tat:2, lane:'par'},
    {n:7, text:'Power model overlay and TOPS/W projection', tat:2, lane:'main'},
    {n:8, text:'Bottleneck analysis and roofline characterization', tat:1.5, lane:'par'},
    {n:9, text:'Sensitivity analysis and a stated confidence interval', tat:3, lane:'main'},
    {n:10, text:'Model handoff and regression harness for later stages', tat:1, lane:'main'},
  ],
  flowNote:'Correlation sits early on purpose. A model that has never been checked against silicon produces numbers, not answers, and every sweep run before correlation has to be re-run afterwards.',
  consumes:[
    'Workload suite and KPI table from DEF-02',
    'PPA targets from DEF-03',
    'Bandwidth requirements from DEF-05',
    'Previous-generation silicon and its measured performance',
    'Node library characterization from PDK-03',
  ],
  produces:[
    'Model scope and fidelity decision record',
    'Baseline performance model',
    'Workload suite integrated into the model',
    'Correlation report against previous-generation silicon',
    'Design-space exploration results, per sweep',
    'Interconnect and NoC topology study results',
    'Power and TOPS/W projection',
    'Bottleneck and roofline analysis',
    'Sensitivity analysis with a confidence statement',
    'Performance model and its source',
    'Regression harness for downstream re-runs',
  ],
  producedBy:[1,2,3,4,5,6,7,8,9,10,10],
  rel:[
    {id:'ARCH-D2', rel:'produces', text:'<b>Performance model and workload analysis report.</b> The model, its correlation and its confidence statement are the deliverable—the report without the model is an assertion.'},
    {id:'ARCH-D1', rel:'feeds', text:'<b>Architecture specification.</b> Every quantitative claim in the specification traces back to a sweep in this model, or it does not belong in the specification.'},
    {id:'ARCH-D3', rel:'feeds', text:'<b>Block partitioning and PPA budget table.</b> The sweeps are what decide cluster count and SRAM capacity before <code>ARCH-02</code> draws the boundaries.'},
  ],
  risks:[
    '<b>Model never correlated against silicon.</b> An uncorrelated model has an unknown error bar, and every decision taken on it inherits that error silently.',
    '<b>Fidelity chosen for comfort.</b> An analytical model that runs in seconds will answer the wrong question quickly; a cycle-accurate model that takes a week per sweep will answer nothing in time to matter.',
    '<b>Sweeps run on an unrepresentative workload.</b> The model inherits whatever bias DEF-02 built into the suite, and amplifies it across every architectural decision.',
    '<b>Power model bolted on at the end.</b> TOPS/W is a KPI; a performance model with no power overlay cannot answer the question the product is sold on.',
    '<b>No confidence statement.</b> A projection quoted as a single number invites the organization to plan against a precision the model does not have.',
  ],
  roles:[
    {r:'Performance architect', d:'Owns the model, its fidelity and its confidence statement'},
    {r:'Modeling engineers', d:'Model construction, sweeps and the regression harness'},
    {r:'Workload analyst', d:'Suite integration and result interpretation'},
    {r:'Power modeling engineer', d:'Power overlay and TOPS/W projection'},
    {r:'Silicon correlation engineer', d:'Previous-generation measurement and correlation'},
  ],
  effort:[['Model construction',7], ['Design-space exploration',6], ['Power model overlay',4], ['NoC and interconnect studies',3.5], ['Bottleneck and sensitivity analysis',3.5], ['Silicon correlation',3], ['Handoff and regression harness',1]],
  entry:[
    'Workload suite delivered and runnable from DEF-02',
    'PPA targets published by DEF-03',
    'Previous-generation platform available for correlation',
  ],
  exit:[
    'Model correlated against silicon with a stated error band',
    'Every architectural decision in the stage traced to a sweep',
    'Regression harness handed over so later stages can re-run it',
  ],
  dependsOn:['DEF-02','DEF-03','DEF-05'],
  dependsNote:null,
  feedsInto:['ARCH-02','ARCH-03','ARCH-06','ARCH-09','DV-09'],
  measuredBy:[
    'Correlation error against previous-generation silicon',
    'Architectural decisions supported by a sweep',
    'Model re-run turnaround once a parameter changes',
  ],
},

'ARCH-02': {
  stage:'architecture', window:[2,10], criticalPath:true,
  purpose:[
    'Decide what sits on which die and where the block boundaries fall—including <b>whether this is one die or several</b>.',
    'The monolithic-versus-chiplet call is the most expensive decision in the stage. It sets the package, the die-to-die interface, the test strategy, the yield model and the cost model at once, and after Architecture Freeze it is effectively irreversible: unwinding it means redoing the floorplan, the package design and the test hardware together.',
  ],
  steps:[
    {n:1, text:'Block decomposition from the functional requirements', tat:1, lane:'main'},
    {n:2, text:'Reticle limit and die size feasibility check', tat:0.5, lane:'main'},
    {n:3, text:'Monolithic and chiplet options built as costed candidates', tat:2, lane:'main'},
    {n:4, text:'Yield and cost comparison per candidate, with the DEF-04 model', tat:1.5, lane:'par'},
    {n:5, text:'Die-to-die interface implication study', tat:1, lane:'par'},
    {n:6, text:'Partition boundary definition — what crosses, at what bandwidth', tat:3, lane:'main'},
    {n:7, text:'Known-good-die and test implication review', tat:1, lane:'par'},
    {n:8, text:'Partitioning decision and record', tat:1.5, lane:'main'},
  ],
  flowNote:'Boundary definition takes three of the eight weeks because it is the part that gets skipped. Deciding "two dies" is quick; deciding exactly which signals cross at what bandwidth and latency is the work that makes the decision real.',
  consumes:[
    'Design-space exploration results from ARCH-01',
    'Cost and yield model from DEF-04',
    'Reticle limit and node constraints from TECH-02',
    'Package architecture options from the requirement register',
    'Test strategy assumptions from DFT-01',
  ],
  produces:[
    'Block decomposition and hierarchy',
    'Reticle limit and die size feasibility finding',
    'Costed partitioning candidates',
    'Yield and cost comparison per candidate',
    'Die-to-die interface implication study',
    'Partition boundary specification — signals, bandwidth, latency',
    'Known-good-die and test implication assessment',
    'Partitioning decision record with dissent',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'ARCH-D3', rel:'produces', text:'<b>Block partitioning and PPA budget table.</b> The partitioning half of the deliverable; <code>ARCH-06</code> supplies the budget half against these blocks.'},
    {id:'ARCH-D1', rel:'feeds', text:'<b>Architecture specification.</b> The partition and its boundaries are the specification\'s structural spine—every other section is written against them.'},
    {id:'ARCH-D6', rel:'feeds', text:'<b>Chip-level block diagram with pin and bump budget.</b> <code>ARCH-08</code> draws what this activity decides.'},
  ],
  risks:[
    '<b>Chiplet chosen for the roadmap rather than for this product.</b> A die-to-die interface costs area, power and a test strategy; taking it on to be ready for the next program charges this one.',
    '<b>Boundaries drawn without bandwidth.</b> A partition that names blocks but not the traffic between them is redrawn at <code>PD-02</code> when the floorplan cannot carry it.',
    '<b>Reticle limit checked against the estimate, not the growth.</b> Die area grows through implementation; a partition that fits at architecture and not at signoff is a partition that fails late.',
    '<b>Test implications deferred.</b> Known-good-die coverage on a chiplet part is a DFT and test-hardware program of its own, and it is priced after the decision is taken.',
    '<b>Decision recorded without the dissent.</b> The objection nobody minuted resurfaces at first silicon with nothing to point at.',
  ],
  roles:[
    {r:'Chief architect', d:'Owns the partitioning decision and its record'},
    {r:'Physical architect', d:'Reticle, floorplan and boundary feasibility'},
    {r:'Cost and yield analyst', d:'Candidate comparison against the DEF-04 model'},
    {r:'Interconnect architect', d:'Boundary traffic, bandwidth and latency'},
    {r:'DFT liaison', d:'Known-good-die and test strategy implications'},
  ],
  effort:[['Candidate construction',4], ['Boundary definition',3.5], ['Yield and cost comparison',2.5], ['Die-to-die interface study',2], ['Test implication review',1], ['Decision record',1]],
  entry:[
    'First design-space results available from ARCH-01',
    'Cost model usable for candidate comparison',
    'Reticle and node constraints confirmed by TECH',
  ],
  exit:[
    'Partitioning decided and recorded with the alternatives it beat',
    'Every boundary carries a bandwidth and latency budget',
    'Test and yield implications priced, not deferred',
  ],
  dependsOn:['ARCH-01','DEF-04','TECH-02'],
  dependsNote:null,
  feedsInto:['ARCH-03','ARCH-06','ARCH-08','ARCH-10','PKGD-01','DFT-01'],
  measuredBy:[
    'Candidates evaluated against the one chosen',
    'Boundaries carrying an agreed bandwidth budget',
    'Partition changes raised after Architecture Freeze',
  ],
},

'ARCH-03': {
  stage:'architecture', window:[4,12], criticalPath:true,
  purpose:[
    'Define how data moves and where it lives—<b>dataflow, on-die SRAM capacity and organization, HBM channel count</b>—for each workload class the product serves.',
    'An inference accelerator is a memory system with arithmetic attached. A hierarchy that does not match the reuse pattern of the workload shows up as a utilization number nobody can lift afterwards: not by clock speed, not by more compute, and not by any amount of software.',
  ],
  steps:[
    {n:1, text:'Dataflow selection per workload class — weight-stationary, output-stationary, hybrid', tat:1.5, lane:'main'},
    {n:2, text:'On-die SRAM capacity sizing against measured reuse distance', tat:2, lane:'main'},
    {n:3, text:'SRAM banking, port and bandwidth organization', tat:1.5, lane:'par'},
    {n:4, text:'HBM channel count and address interleaving scheme', tat:1.5, lane:'main'},
    {n:5, text:'Cache and scratchpad policy', tat:1, lane:'par'},
    {n:6, text:'Prefetch and data-movement engine requirement', tat:1, lane:'par'},
    {n:7, text:'Hierarchy simulation against the ARCH-01 model', tat:2, lane:'main'},
    {n:8, text:'Hierarchy specification and handoff', tat:1, lane:'main'},
  ],
  flowNote:'Sizing precedes simulation and simulation revises sizing—the two weeks in step 7 include at least one full turn back through step 2. A hierarchy accepted on its first simulation has almost certainly not been swept.',
  consumes:[
    'Workload traces and reuse analysis from DEF-02',
    'Bandwidth requirements from DEF-05',
    'Design-space results from ARCH-01',
    'Partition boundaries from ARCH-02',
    'Memory compiler capability from PDK-04',
  ],
  produces:[
    'Dataflow specification per workload class',
    'SRAM capacity sizing with reuse-distance evidence',
    'SRAM capacity, banking and port organization',
    'HBM channel count and interleaving scheme',
    'Cache and scratchpad policy note',
    'Prefetch and data-movement engine requirement',
    'Hierarchy simulation results',
    'Memory hierarchy specification chapter',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'ARCH-D1', rel:'produces', text:'<b>Architecture specification.</b> The memory hierarchy chapter is authored here and lands in the specification whole; <code>ARCH-09</code> assembles rather than rewrites it.'},
    {id:'ARCH-D3', rel:'feeds', text:'<b>Block partitioning and PPA budget table.</b> SRAM capacity is the largest single area line in the budget, and it is decided here.'},
    {id:'ARCH-D2', rel:'feeds', text:'<b>Performance model and workload analysis report.</b> The hierarchy sweeps are run in the ARCH-01 model and reported with it.'},
  ],
  risks:[
    '<b>SRAM sized on average reuse.</b> Reuse distance has a tail; a capacity chosen at the median misses the workloads that define the product\'s worst case.',
    '<b>Banking decided after capacity.</b> Capacity and bandwidth are separate constraints, and a bank organization that cannot feed the compute wastes the area it took.',
    '<b>Memory compiler capability assumed.</b> The instance the hierarchy needs may not exist on the node—<code>PDK-05</code> is where that is found, and it is found after this decision unless someone asks early.',
    '<b>Dataflow chosen once for all workloads.</b> A single dataflow optimized for one class starves another, and the deployment mix decides which mistake is cheaper.',
    '<b>Interleaving left to implementation.</b> Address interleaving decides whether HBM channels are actually parallel; deferred, it becomes a bandwidth shortfall nobody predicted.',
  ],
  roles:[
    {r:'Memory systems architect', d:'Owns the hierarchy and its specification'},
    {r:'Dataflow architect', d:'Dataflow selection and compute-memory matching'},
    {r:'Performance modeling engineer', d:'Hierarchy sweeps in the ARCH-01 model'},
    {r:'Memory IP liaison', d:'Compiler capability and instance feasibility'},
    {r:'Workload analyst', d:'Reuse distance and access-pattern analysis'},
  ],
  effort:[['SRAM capacity and organization',3], ['Dataflow selection',2.5], ['Hierarchy simulation',2.5], ['HBM channels and interleaving',1.5], ['Cache, scratchpad and prefetch policy',1.5], ['Specification and handoff',1]],
  entry:[
    'Reuse analysis available from the DEF-02 traces',
    'Partition boundaries stable from ARCH-02',
    'Memory compiler capability indicated by PDK-04',
  ],
  exit:[
    'Capacity and bandwidth justified by simulation, not by precedent',
    'Dataflow chosen per workload class with the trade recorded',
    'Memory instance requirements handed to PDK and AMS',
  ],
  dependsOn:['DEF-02','DEF-05','ARCH-01','ARCH-02'],
  dependsNote:null,
  feedsInto:['ARCH-06','ARCH-08','ARCH-10','PDK-05','AMS-05','RTL-01'],
  measuredBy:[
    'Utilization achieved in simulation against the roofline',
    'SRAM area against the ARCH-06 allocation',
    'Hierarchy changes raised after RTL freeze',
  ],
},

'ARCH-04': {
  stage:'architecture', window:[3,9], criticalPath:false,
  purpose:[
    'Choose the external interfaces and <b>pin their revisions</b>—PCIe generation, CXL profile, HBM generation, die-to-die if the part is a chiplet—and turn each into a controller and PHY requirement IPR can go and buy.',
    'Interfaces are where the program touches standards bodies and IP vendors, neither of which runs on the program\'s calendar. A generation selected before its specification is ratified imports someone else\'s schedule into this one, and the import is silent until the PHY is late.',
  ],
  steps:[
    {n:1, text:'Interface requirement extraction from DEF-05', tat:0.5, lane:'main'},
    {n:2, text:'Standard revision status and ratification timing review', tat:1, lane:'main'},
    {n:3, text:'Host interface selection — PCIe generation and CXL profile', tat:1.5, lane:'main'},
    {n:4, text:'HBM generation selection and controller requirement', tat:1, lane:'par'},
    {n:5, text:'Die-to-die interface selection, if a chiplet split survives ARCH-02', tat:1, lane:'par'},
    {n:6, text:'Compliance and interoperability requirement definition', tat:1, lane:'par'},
    {n:7, text:'Controller and PHY requirement handoff to IP strategy', tat:1, lane:'main'},
    {n:8, text:'Interface definition document and review', tat:2, lane:'main'},
  ],
  flowNote:'The handoff in step 7 is what makes this activity urgent rather than merely important. <code>IPR-04</code> cannot evaluate a PHY vendor against a generation nobody has chosen, and PHY license lead times run to a quarter.',
  consumes:[
    'Bandwidth and interface sizing from DEF-05',
    'Partitioning decision from ARCH-02',
    'Standards body revision status and ratification schedules',
    'Vendor PHY roadmaps under NDA',
    'Node PHY availability from TECH-03',
  ],
  produces:[
    'Consolidated interface requirement list',
    'Standard revision and ratification status record',
    'Host interface selection with generation and profile',
    'HBM generation selection and controller requirement',
    'Interface selection record with the revision pinned',
    'Die-to-die interface requirement, where applicable',
    'Compliance and interoperability requirement list',
    'Controller and PHY requirement specification',
    'Interface definition document',
  ],
  producedBy:[1,2,3,4,5,5,6,7,8],
  rel:[
    {id:'ARCH-D4', rel:'produces', text:'<b>Interface and protocol definition document.</b> This activity is the deliverable—the selections, their revisions and the requirements derived from them.'},
    {id:'ARCH-D1', rel:'feeds', text:'<b>Architecture specification.</b> The interface chapter is imported from the definition document rather than restated, so the two cannot drift.'},
    {id:'ARCH-D6', rel:'feeds', text:'<b>Chip-level block diagram with pin and bump budget.</b> Lane counts and PHY footprints are what <code>ARCH-08</code> allocates bumps against.'},
  ],
  risks:[
    '<b>Specification not ratified at selection.</b> Designing to a draft revision transfers a standards-body schedule into the program, and the transfer is invisible until compliance testing.',
    '<b>PHY assumed available on the node.</b> A PHY proven on the previous node is not a PHY on this one; <code>IPR-05</code> is where that is confirmed, and it is confirmed after this choice.',
    '<b>Compliance requirements written late.</b> Interoperability testing needs hardware, test suites and lab time booked against dates set here.',
    '<b>Lane count set by bandwidth alone.</b> Lanes cost bumps, area and power; a count chosen without <code>ARCH-08</code> in the room is a count the floorplan will renegotiate.',
    '<b>Die-to-die selection deferred past ARCH-02.</b> The interface is a large architectural commitment, and deferring it forces the conservative default.',
  ],
  roles:[
    {r:'Interface architect', d:'Owns the selections and the definition document'},
    {r:'Standards liaison', d:'Revision status, ratification timing and compliance'},
    {r:'IP strategist', d:'Turns requirements into vendor evaluation criteria'},
    {r:'SerDes and PHY specialist', d:'PHY feasibility on the selected node'},
    {r:'Physical architect', d:'Bump and area cost of the lane count'},
  ],
  effort:[['Interface selection studies',2], ['Standards and ratification review',1], ['Compliance requirement definition',1], ['IP requirement handoff',1], ['Definition document and review',1]],
  entry:[
    'Interface sizing available from DEF-05',
    'Partitioning decided by ARCH-02',
    'Vendor PHY roadmaps accessible under NDA',
  ],
  exit:[
    'Every interface pinned to a named, ratified revision',
    'Controller and PHY requirements handed to IPR',
    'Compliance obligations listed with the hardware they need',
  ],
  dependsOn:['DEF-05','ARCH-02','TECH-03'],
  dependsNote:null,
  feedsInto:['ARCH-08','IPR-01','IPR-04','AMS-03','SIPI-07','TEST-01'],
  measuredBy:[
    'Interfaces pinned to a ratified revision',
    'Days from selection to IPR vendor engagement',
    'Interface changes raised after Architecture Freeze',
  ],
},

'ARCH-05': {
  stage:'architecture', window:[7,14], criticalPath:false,
  purpose:[
    'Define the power and clock structure the whole implementation inherits—<b>domains, rails, DVFS operating points, clock crossings, reset topology</b>—and write the first UPF intent.',
    'Power intent is one of the few architectural artifacts consumed literally by tools. A domain boundary drawn here becomes isolation and level-shifter cells at <code>SYN-06</code> and a verification obligation at <code>DV-06</code>. Drawn late, or drawn differently by two teams, it forces both to be redone.',
  ],
  steps:[
    {n:1, text:'Power domain partitioning against the block list', tat:1.5, lane:'main'},
    {n:2, text:'Voltage rail and regulator topology', tat:1, lane:'main'},
    {n:3, text:'DVFS operating point definition and switching policy', tat:1.5, lane:'par'},
    {n:4, text:'Clock domain architecture and crossing inventory', tat:1.5, lane:'main'},
    {n:5, text:'Reset topology and sequencing', tat:1, lane:'par'},
    {n:6, text:'Power management controller requirement', tat:1, lane:'par'},
    {n:7, text:'UPF intent draft', tat:2, lane:'main'},
    {n:8, text:'Review with physical design and verification', tat:1, lane:'main'},
  ],
  flowNote:'The crossing inventory in step 4 is the artifact <code>RTL-06</code> closes CDC against. An inventory that is incomplete at Architecture Freeze becomes a CDC finding in week 40, when the fix is an RTL change under change control.',
  consumes:[
    'Power envelope and per-domain budget from DEF-03',
    'Block list and partitioning from ARCH-02',
    'DVFS requirements from the workload analysis',
    'Library and IO capability from PDK-03',
    'Package power delivery constraints from PKGD-06',
  ],
  produces:[
    'Power domain definition and boundary map',
    'Voltage rail and regulator topology',
    'DVFS operating point table and policy',
    'Clock domain architecture with a crossing inventory',
    'Reset topology and sequence specification',
    'Power management controller requirement',
    'UPF intent file, first draft',
    'Review record from physical design and verification',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'ARCH-D5', rel:'produces', text:'<b>Power / clock / reset architecture and UPF intent.</b> This activity is the deliverable, and the UPF file is the part of it tools consume directly.'},
    {id:'ARCH-D1', rel:'feeds', text:'<b>Architecture specification.</b> The power and clock chapter, and the constraint every block owner designs against.'},
    {id:'ARCH-D3', rel:'feeds', text:'<b>Block partitioning and PPA budget table.</b> Power domains are the unit the power budget is allocated in.'},
  ],
  risks:[
    '<b>Domains drawn for elegance rather than for control.</b> Every domain boundary costs isolation cells, level shifters and verification states; a domain that is never independently gated is pure overhead.',
    '<b>Crossing inventory incomplete.</b> A clock crossing missing from the inventory is a crossing nobody constrains and nobody verifies, and it fails intermittently in silicon.',
    '<b>DVFS policy without measured operating points.</b> Operating points chosen from the library rather than from silicon leave either performance or margin on the table.',
    '<b>UPF drafted after RTL starts.</b> Power intent that arrives mid-RTL forces retrofitting into blocks already written, and the retrofit is never as clean as the design.',
    '<b>Reset sequencing left to bring-up.</b> A reset order discovered in the lab is discovered on silicon that cannot be changed.',
  ],
  roles:[
    {r:'Power architect', d:'Owns the domains, the rails and the UPF intent'},
    {r:'Clocking architect', d:'Clock domain architecture and crossing inventory'},
    {r:'Low-power methodology engineer', d:'UPF authoring and tool consumption'},
    {r:'Physical design liaison', d:'Rail feasibility and PDN implication'},
    {r:'Verification liaison', d:'Confirms the intent is verifiable as written'},
  ],
  effort:[['Power domain partitioning',2], ['UPF intent draft',2], ['Clock domain architecture',1.5], ['DVFS definition',1.5], ['Reset and power management controller',1.5], ['Review',0.5]],
  entry:[
    'Power budget per domain available from DEF-03',
    'Block list stable from ARCH-02',
    'Library and IO low-power capability confirmed by PDK-03',
  ],
  exit:[
    'Every clock crossing on the inventory with a named synchroniser strategy',
    'UPF intent parses in the target tools, not only on paper',
    'Physical design and verification have accepted the architecture',
  ],
  dependsOn:['DEF-03','ARCH-02'],
  dependsNote:null,
  feedsInto:['ARCH-06','ARCH-09','RTL-05','SYN-06','DV-06','PD-03'],
  measuredBy:[
    'Clock crossings inventoried against those later found by CDC',
    'Power domains that are actually independently gated',
    'UPF revisions after RTL freeze',
  ],
},

'ARCH-06': {
  stage:'architecture', window:[12,16], criticalPath:true,
  purpose:[
    'Divide the stage\'s PPA targets across the real block list, so <b>every block owner starts implementation with a number rather than an aspiration</b>.',
    'This is DEF-03\'s allocation done again, and done properly. DEF-03 allocated against an estimated block list; this allocates against the partitioning <code>ARCH-02</code> settled and the hierarchy <code>ARCH-03</code> sized. It is the version RTL, synthesis and physical design are actually held to, and the version an overrun is measured against.',
  ],
  steps:[
    {n:1, text:'Reconcile the DEF-03 targets against the ARCH-02 block list', tat:0.75, lane:'main'},
    {n:2, text:'Area allocation per block, from the floorplan intent', tat:1, lane:'main'},
    {n:3, text:'Power allocation per block and per domain', tat:1, lane:'main'},
    {n:4, text:'Frequency and timing budget per clock domain', tat:0.75, lane:'par'},
    {n:5, text:'Margin reservation for ECO and late growth', tat:0.5, lane:'par'},
    {n:6, text:'Owner assignment and explicit acceptance per block', tat:0.75, lane:'main'},
    {n:7, text:'Budget publication and change-control rule', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 6 is acceptance, not notification. A budget a block owner has not agreed to is a budget that will be exceeded and disputed, and the dispute happens at <code>PD-09</code> when there is no time for it.',
  consumes:[
    'PPA targets from DEF-03',
    'Block list and partitioning from ARCH-02',
    'Memory hierarchy sizing from ARCH-03',
    'Power domain definition from ARCH-05',
    'Floorplan intent from ARCH-08',
  ],
  produces:[
    'Reconciliation note against the DEF-03 targets',
    'Per-block area allocation',
    'Per-block and per-domain power allocation',
    'Per-block area, power and timing budget',
    'Margin reservation record',
    'Owner acceptance sheet per block',
    'Change-control rule for budget movement',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'ARCH-D3', rel:'produces', text:'<b>Block partitioning and PPA budget table.</b> The budget half of the deliverable, published against the blocks <code>ARCH-02</code> defined.'},
    {id:'ARCH-D1', rel:'feeds', text:'<b>Architecture specification.</b> The budget table is referenced by the specification rather than copied, so a budget change does not need a specification revision.'},
    {id:'ARCH-D7', rel:'gates', text:'<b>Architecture Freeze review package.</b> A block without an accepted budget is an open item at the freeze gate.'},
  ],
  risks:[
    '<b>Budgets allocated to 100%.</b> A budget with no margin has nothing left for the ECO storm at physical design, where power and area always grow.',
    '<b>Allocation without acceptance.</b> An unaccepted budget is defended by nobody and consumed by whoever moves first.',
    '<b>No change-control rule.</b> Budgets that can be moved quietly stop being budgets; movement has to cost a conversation.',
    '<b>Reconciliation against DEF-03 skipped.</b> If the architecture\'s total quietly exceeds the definition target, the cost model is wrong and nobody has been told.',
    '<b>Timing budget by clock domain only.</b> Domains contain blocks with very different closure difficulty, and a flat budget hides which one is impossible.',
  ],
  roles:[
    {r:'PPA lead', d:'Owns the allocation, the margin and the change-control rule'},
    {r:'Chief architect', d:'Arbitrates when blocks contest the same budget'},
    {r:'Block owners', d:'Accept or contest their allocation'},
    {r:'Physical architect', d:'Confirms the area allocation against the floorplan intent'},
    {r:'Program manager', d:'Records acceptance and carries gaps into the gate'},
  ],
  effort:[['Area and power allocation',2], ['Reconciliation against DEF-03',0.75], ['Timing budget',0.5], ['Owner acceptance',0.5], ['Publication and change control',0.25]],
  entry:[
    'Block list final from ARCH-02',
    'Memory hierarchy sized by ARCH-03',
    'Floorplan intent available from ARCH-08',
  ],
  exit:[
    'Every block carries an accepted area, power and timing budget',
    'Margin reserved and stated, not assumed',
    'Change-control rule published and agreed',
  ],
  dependsOn:['DEF-03','ARCH-02','ARCH-03','ARCH-05','ARCH-08'],
  dependsNote:null,
  feedsInto:['ARCH-09','ARCH-10','RTL-01','SYN-07','PD-02'],
  measuredBy:[
    'Blocks with an accepted budget against the block count',
    'Margin held back as a share of each budget',
    'Architecture total against the DEF-03 target',
  ],
},

'ARCH-07': {
  stage:'architecture', window:[6,12], criticalPath:false,
  purpose:[
    'Define how the part <b>boots trustworthily, protects its assets and identifies itself</b>—secure boot chain, root of trust, key storage, fuse map and lifecycle states—and the debug lockdown that goes with them.',
    'Security is architectural or it is absent. A root of trust cannot be retrofitted onto a design with no immutable boot path and no fuse plan. The tension worth naming early is that the debug access DFT and bring-up want is the same access an attacker wants, and only an architecture can resolve it.',
  ],
  steps:[
    {n:1, text:'Threat model and asset inventory', tat:1, lane:'main'},
    {n:2, text:'Secure boot chain and immutable ROM definition', tat:1.5, lane:'main'},
    {n:3, text:'Root of trust and key storage selection', tat:1, lane:'par'},
    {n:4, text:'Fuse map, chip identity and lifecycle state definition', tat:1, lane:'main'},
    {n:5, text:'Debug and test access lockdown policy, with DFT', tat:1, lane:'par'},
    {n:6, text:'Cryptographic accelerator requirement', tat:0.75, lane:'par'},
    {n:7, text:'Security architecture note and review', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 5 is a negotiation, not a decision taken alone. <code>DFT-04</code> needs JTAG and trace access for silicon debug, and every path it opens is a path this activity has to close in production lifecycle states.',
  consumes:[
    'Security requirements from the requirement register',
    'Customer and regulatory obligations',
    'Block list and boot architecture from ARCH-02',
    'eFuse and OTP capability from PDK-02',
    'DFT access architecture intent from DFT-04',
  ],
  produces:[
    'Threat model and asset inventory',
    'Secure boot chain specification',
    'Root of trust and key storage architecture',
    'Fuse map and lifecycle state definition',
    'Debug lockdown policy',
    'Cryptographic accelerator requirement',
    'Security architecture note and review record',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'ARCH-D1', rel:'produces', text:'<b>Architecture specification.</b> The security chapter is authored here in full—boot chain, lifecycle states and lockdown policy—and lands in the specification whole.'},
    {id:'ARCH-D5', rel:'feeds', text:'<b>Power / clock / reset architecture.</b> Secure boot constrains the reset sequence: the root of trust must run before anything else is released from reset.'},
  ],
  risks:[
    '<b>Security started after the block list is fixed.</b> A root of trust needs its own reset domain, its own ROM and its own fuse path; adding them later disturbs three architectures at once.',
    '<b>Debug access left open in production.</b> The lifecycle state that locks JTAG is the one nobody tests, because testing it makes the part undebuggable.',
    '<b>Fuse map without a lifecycle model.</b> Fuses are one-time; a map with no defined state transitions produces parts that cannot be returned to a testable state.',
    '<b>Key storage decided by IP availability.</b> Choosing the root of trust because a block was available is choosing a threat model by accident.',
    '<b>No named security owner past architecture.</b> Security decisions get eroded one waiver at a time through implementation unless someone owns them all the way to qualification.',
  ],
  roles:[
    {r:'Security architect', d:'Owns the threat model, the boot chain and the lockdown policy'},
    {r:'Boot and firmware architect', d:'Boot sequence and immutable ROM content'},
    {r:'DFT liaison', d:'Negotiates debug access against lockdown'},
    {r:'Fuse and lifecycle engineer', d:'Fuse map, chip identity, state transitions'},
    {r:'Compliance liaison', d:'Customer and regulatory obligations'},
  ],
  effort:[['Boot chain and root of trust',2.5], ['Threat model and asset inventory',1.5], ['Fuse map and lifecycle states',1], ['Debug lockdown negotiation',1], ['Cryptographic accelerator requirement',0.5], ['Review',0.5]],
  entry:[
    'Security requirements present in the requirement register',
    'Block list available from ARCH-02',
    'eFuse and OTP capability confirmed by PDK-02',
  ],
  exit:[
    'Threat model reviewed and every asset mapped to a control',
    'Lifecycle states defined with their transitions and their tests',
    'Debug lockdown agreed with DFT rather than imposed on it',
  ],
  dependsOn:['DEF-01','ARCH-02'],
  dependsNote:null,
  feedsInto:['ARCH-09','ARCH-10','DFT-04','DFT-10','RTL-04','MP-11'],
  measuredBy:[
    'Assets in the inventory mapped to an implemented control',
    'Lifecycle state transitions with a defined test',
    'Security waivers accepted after Architecture Freeze',
  ],
},

'ARCH-08': {
  stage:'architecture', window:[10,15], criticalPath:false,
  purpose:[
    'Draw the chip as a <b>physical object</b> for the first time—block placement intent, IO ring, bump field—and publish the pin and bump budget the package will be designed against.',
    'The bump map is the first artifact the die and the package share, and the first hard constraint on bandwidth. An interface needing more bumps than the field can supply is an interface that has to shrink, and having that argument here costs a meeting. Having it at <code>PD-04</code>, with the substrate already ordered, costs the substrate.',
  ],
  steps:[
    {n:1, text:'Block placement intent from the partitioning and the hierarchy', tat:1, lane:'main'},
    {n:2, text:'IO ring and PHY placement plan', tat:1, lane:'main'},
    {n:3, text:'Bump field definition — pitch, count, power-to-signal ratio', tat:1.5, lane:'main'},
    {n:4, text:'Signal bump allocation per interface', tat:0.75, lane:'par'},
    {n:5, text:'Power delivery bump budget against the power envelope', tat:1, lane:'par'},
    {n:6, text:'Package feasibility check with package design', tat:0.75, lane:'par'},
    {n:7, text:'Block diagram and bump budget publication', tat:1.5, lane:'main'},
  ],
  flowNote:'The power-to-signal ratio in step 3 is the number that decides the argument. On a part at this power envelope most of the bump field is power delivery, and the signal budget is what is left over rather than what was asked for.',
  consumes:[
    'Partitioning and boundaries from ARCH-02',
    'Memory hierarchy and HBM channel count from ARCH-03',
    'Interface lane counts from ARCH-04',
    'Power envelope from DEF-03',
    'Package architecture options from PKGD-01',
  ],
  produces:[
    'Chip-level block diagram with placement intent',
    'IO ring and PHY placement plan',
    'Bump field definition and map',
    'Signal and power bump allocation',
    'Power delivery bump budget',
    'Package feasibility finding',
    'Published block diagram and bump budget',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'ARCH-D6', rel:'produces', text:'<b>Chip-level block diagram with pin and bump budget.</b> This activity is the deliverable, and the bump map is the half of it the package team consumes directly.'},
    {id:'ARCH-D1', rel:'feeds', text:'<b>Architecture specification.</b> The physical view chapter—the first place the specification stops being a block diagram and becomes a die.'},
    {id:'ARCH-D3', rel:'feeds', text:'<b>Block partitioning and PPA budget table.</b> Placement intent is what <code>ARCH-06</code> allocates die area against.'},
  ],
  risks:[
    '<b>Bump budget derived after interfaces are fixed.</b> Lane counts set without a bump budget produce a floorplan that cannot be built and an interface that has to be cut late.',
    '<b>Power delivery bumps underestimated.</b> Too few power bumps is an IR-drop problem discovered at <code>SIPI-04</code>, when the bump map is already in the package design.',
    '<b>Placement intent treated as decoration.</b> Physical design inherits this drawing; an intent that ignores routing feasibility is redrawn at <code>PD-01</code> and the schedule pays for both.',
    '<b>Package feasibility checked against a generic assumption.</b> Bump pitch and field size depend on the actual interposer and substrate technology, which <code>PKGD-01</code> may not have settled yet.',
    '<b>HBM PHY placement left open.</b> HBM PHYs must sit against the interposer edge facing their stacks; deciding this late constrains everything else on the die.',
  ],
  roles:[
    {r:'Physical architect', d:'Owns the placement intent and the bump field'},
    {r:'IO and PHY architect', d:'Ring organization and PHY placement'},
    {r:'Power delivery engineer', d:'Power bump budget against the envelope'},
    {r:'Package design liaison', d:'Feasibility against the interposer and substrate'},
    {r:'Chief architect', d:'Arbitrates bandwidth against bump budget'},
  ],
  effort:[['Bump field definition and allocation',2], ['Placement intent',1.25], ['Power bump budget',0.75], ['Package feasibility check',0.5], ['Publication',0.5]],
  entry:[
    'Partitioning decided by ARCH-02',
    'Interface lane counts available from ARCH-04',
    'Package architecture candidates known from PKGD-01',
  ],
  exit:[
    'Bump field defined with an explicit power-to-signal ratio',
    'Every interface has an allocated bump count package has accepted',
    'Placement intent reviewed by physical design as buildable',
  ],
  dependsOn:['ARCH-02','ARCH-03','ARCH-04','DEF-03'],
  dependsNote:null,
  feedsInto:['ARCH-06','ARCH-09','PKGD-02','PD-01','PD-04','SIPI-02'],
  measuredBy:[
    'Signal bumps allocated against those requested',
    'Power-to-signal ratio against the envelope requirement',
    'Bump map revisions after Architecture Freeze',
  ],
},

'ARCH-09': {
  stage:'architecture', window:[9,18], criticalPath:true,
  purpose:[
    'Write the document the rest of the program builds against, and run it through the review that ends in <b>Architecture Freeze</b>.',
    'The specification is not a record of decisions already taken; writing it is what exposes the decisions nobody took. Every downstream stage reads this document, and every ambiguity left in it becomes an argument in RTL, a bug in verification, or a waiver at signoff. The consistency pass matters as much as the authoring.',
  ],
  steps:[
    {n:1, text:'Specification structure and section ownership assignment', tat:0.5, lane:'main'},
    {n:2, text:'Section authoring across the architecture team', tat:3.5, lane:'main'},
    {n:3, text:'Consistency pass — every number traced to its source activity', tat:1.5, lane:'par'},
    {n:4, text:'Open-issue register and disposition', tat:1, lane:'par'},
    {n:5, text:'Internal technical review, two rounds', tat:2, lane:'main'},
    {n:6, text:'Downstream readiness review with RTL, DV, DFT and physical design', tat:1.5, lane:'main'},
    {n:7, text:'Freeze package assembly', tat:1, lane:'par'},
    {n:8, text:'Architecture Freeze gate', tat:1.5, lane:'main'},
  ],
  flowNote:'The downstream readiness review in step 6 is the one that predicts the program. Architecture reviewing its own specification confirms it is coherent; RTL, DV and DFT reviewing it confirms it is implementable, and those are different questions.',
  consumes:[
    'Every other ARCH activity\'s output',
    'Performance model results from ARCH-01',
    'PPA budget table from ARCH-06',
    'Feasibility concessions from DEF-07',
    'Open issues carried from the architecture risk register',
  ],
  produces:[
    'Specification structure with section owners',
    'Architecture specification',
    'Consistency and traceability record',
    'Open-issue register with disposition per item',
    'Internal technical review findings, two rounds',
    'Downstream readiness review findings',
    'Architecture Freeze package and decision record',
    'Architecture Freeze gate decision',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'ARCH-D1', rel:'produces', text:'<b>Architecture specification.</b> This activity assembles and closes it. Chapters authored in <code>ARCH-03</code>, <code>ARCH-05</code> and <code>ARCH-07</code> arrive whole; the work here is coherence, not rewriting.'},
    {id:'ARCH-D7', rel:'produces', text:'<b>Architecture Freeze review package.</b> The specification, the open-issue disposition and the downstream readiness findings, assembled for the gate.'},
    {id:'ARCH-D2', rel:'feeds', text:'<b>Performance model and workload analysis report.</b> Published alongside the specification, because the specification\'s numbers are only defensible with it.'},
  ],
  risks:[
    '<b>Freeze declared with open issues undispositioned.</b> An open issue carried past freeze is a decision deferred to whoever hits it first in RTL.',
    '<b>Consistency pass skipped under schedule pressure.</b> The same number appearing differently in two chapters is the defect that costs the most and is found the latest.',
    '<b>Downstream teams reviewing after freeze.</b> A readiness review that happens after the gate cannot change anything, and becomes a complaint rather than a review.',
    '<b>Specification written as a narrative.</b> Implementable specifications are tables, interfaces and constraints; prose is where ambiguity survives review.',
    '<b>Freeze treated as a date rather than a condition.</b> A gate that passes because it was scheduled to teaches the organization that gates do not mean anything.',
  ],
  roles:[
    {r:'Chief architect', d:'Owns the specification and the freeze recommendation'},
    {r:'Section authors', d:'Architecture leads writing their own chapters'},
    {r:'Technical editor', d:'Consistency, traceability and structure'},
    {r:'Downstream leads', d:'RTL, DV, DFT and PD readiness review'},
    {r:'Program manager', d:'Open-issue disposition and the gate record'},
  ],
  effort:[['Section authoring',6], ['Technical and readiness reviews',3.5], ['Consistency and traceability pass',2], ['Open-issue disposition',1.5], ['Freeze package and gate',1]],
  entry:[
    'All architectural decisions taken, or explicitly listed as open',
    'PPA budget accepted by block owners in ARCH-06',
    'Downstream leads available to review before the gate',
  ],
  exit:[
    'Every open issue dispositioned — closed, deferred with an owner, or accepted as risk',
    'Downstream readiness review completed before the gate, not after',
    'Freeze decision recorded with conditions and dissent',
  ],
  dependsOn:['ARCH-01','ARCH-02','ARCH-03','ARCH-04','ARCH-05','ARCH-06','ARCH-07','ARCH-08'],
  dependsNote:null,
  feedsInto:['ARCH-10','RTL-01','DV-01','DFT-01','SYN-01','PD-01'],
  measuredBy:[
    'Open issues dispositioned at the gate against those raised',
    'Specification numbers traceable to a source activity',
    'Specification revisions issued after freeze',
  ],
},

'ARCH-10': {
  stage:'architecture', window:[12,18], criticalPath:true,
  purpose:[
    'Turn each architectural block into a <b>microarchitecture specification its RTL owner can implement from</b>—pipeline structure, interfaces, control, register map and the verification hooks.',
    'The architecture specification says what each block does; this says how. Starting it inside the architecture stage rather than at RTL kickoff is what lets <code>RTL-02</code> begin with something to write against instead of a paragraph—and it is the cheapest place to find out that two blocks disagree about the interface between them.',
  ],
  steps:[
    {n:1, text:'Block specification template and review cadence', tat:0.5, lane:'main'},
    {n:2, text:'Block owner assignment and kickoff', tat:0.5, lane:'main'},
    {n:3, text:'Pipeline and datapath definition per block', tat:2, lane:'main'},
    {n:4, text:'Block interface and protocol definition against the NoC', tat:1.5, lane:'par'},
    {n:5, text:'Control, configuration and register map, first pass', tat:1.5, lane:'par'},
    {n:6, text:'Verification hook and observability requirement, with DV', tat:1, lane:'par'},
    {n:7, text:'Microarchitecture review, first round', tat:1.5, lane:'main'},
    {n:8, text:'Handoff to RTL implementation', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 4 runs in parallel and is where the interesting failures live. Two block owners each writing their side of a shared interface will disagree, and finding that here costs a meeting rather than an integration debug at <code>RTL-04</code>.',
  consumes:[
    'Architecture specification chapters from ARCH-09',
    'Partitioning and boundaries from ARCH-02',
    'Memory hierarchy specification from ARCH-03',
    'PPA budget per block from ARCH-06',
    'Verification strategy intent from DV-01',
  ],
  produces:[
    'Microarchitecture specification per block',
    'Block owner assignment and kickoff record',
    'Per-block pipeline and datapath definition',
    'Block interface and protocol definitions',
    'Register map first pass, per block',
    'Verification hook and observability requirements',
    'First-round microarchitecture review findings',
    'RTL implementation handoff package',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'ARCH-D1', rel:'feeds', text:'<b>Architecture specification.</b> Block specifications are children of it—they refine rather than restate, and any conflict is resolved in favor of the architecture specification.'},
    {id:'ARCH-D3', rel:'feeds', text:'<b>Block partitioning and PPA budget table.</b> Microarchitecture is where a block owner first tests whether the allocated budget is achievable.'},
    {id:'ARCH-D7', rel:'gates', text:'<b>Architecture Freeze review package.</b> A block with no microarchitecture owner is an open item at the gate—the specification cannot be implemented by nobody.'},
  ],
  risks:[
    '<b>Block owners not assigned.</b> A block whose specification has no author is a block whose RTL starts by inventing one, usually in week three of implementation.',
    '<b>Interfaces written from one side.</b> Each owner specifying their own side of a shared interface produces two consistent documents that disagree with each other.',
    '<b>Register map deferred to RTL.</b> The register map is the software contract; defining it late means firmware development starts late and the two never converge.',
    '<b>Verification hooks added after the design.</b> Observability designed in is cheap; observability retrofitted costs area, timing and an RTL change under control.',
    '<b>Microarchitecture that ignores the budget.</b> A pipeline designed without reference to <code>ARCH-06</code>\'s allocation is a budget overrun scheduled for synthesis.',
  ],
  roles:[
    {r:'Block architects', d:'Author their block\'s microarchitecture specification'},
    {r:'Interconnect architect', d:'Arbitrates shared interface definitions'},
    {r:'RTL leads', d:'Receive the handoff and confirm it is implementable'},
    {r:'Verification liaison', d:'Observability and verification hook requirements'},
    {r:'Chief architect', d:'Resolves conflicts against the architecture specification'},
  ],
  effort:[['Pipeline and datapath definition',4], ['Interface definition',2.5], ['Register map first pass',2], ['Microarchitecture reviews',2], ['Verification hooks',1], ['Handoff',0.5]],
  entry:[
    'Architecture specification chapters stable enough to refine',
    'Block owners assigned and available',
    'PPA budget accepted per block in ARCH-06',
  ],
  exit:[
    'Every block has a specification and a named owner',
    'Shared interfaces agreed by both sides, not by each',
    'RTL leads have accepted the handoff as implementable',
  ],
  dependsOn:['ARCH-02','ARCH-03','ARCH-06','ARCH-09'],
  dependsNote:null,
  feedsInto:['RTL-01','RTL-02','RTL-07','DV-01','DFT-01'],
  measuredBy:[
    'Blocks with a specification and an owner at freeze',
    'Shared interfaces signed by both sides',
    'Interface defects found at RTL integration',
  ],
},

};
