/* ASSY — Assembly & Package Build. Eleven activities. Stage w76–107 (31w), 50 M/M.
   Opens on the package design freeze: ASSY-10 and ASSY-11 build the production
   interposer and substrate, which take longer than the die does. */
module.exports = {

'ASSY-01': {
  stage:'packaging', window:[23,26], criticalPath:true,
  purpose:[
    'Sort the wafers and pick the <b>known-good die</b> that will go into packages—because on a 2.5D part a bad die does not fail alone, it takes an interposer, two HBM stacks and an assembly with it.',
    'Known-good-die screening is what makes multi-die packaging economically viable. The coverage achieved at sort determines how many assembled units fail for reasons that were detectable on the wafer, and each of those is a package\'s worth of material lost.',
  ],
  steps:[
    {n:1, text:'Wafer receipt and sort setup on the probe station', tat:0.5, lane:'main'},
    {n:2, text:'Wafer sort execution against the KGD criteria', tat:1, lane:'main'},
    {n:3, text:'Marginal die disposition', tat:0.75, lane:'par'},
    {n:4, text:'Known-good-die selection and wafer mapping', tat:1, lane:'main'},
    {n:5, text:'Die release to assembly with traceability', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 3 is where the economics live. A marginal die is cheap to scrap and expensive to assemble; the criteria for rejecting one have to be set against the assembled unit\'s cost rather than against the die\'s.',
  consumes:[
    'Accepted wafers from FAB-08 and FAB-10',
    'Wafer sort program from TEST-05',
    'Probe card from TEST-03',
    'KGD criteria from PKGD-10',
    'Assembly quantity requirement from ASSY-09',
  ],
  produces:[
    'Wafers received with sort setup complete',
    'Sort execution results',
    'Marginal die disposition record',
    'Known-good-die map per wafer',
    'Die released to assembly with traceability',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'ASSY-D1', rel:'feeds', text:'<b>Assembled units.</b> Everything assembled starts from a die this activity selected.'},
    {id:'ASSY-D3', rel:'feeds', text:'<b>Assembly yield report and failure pareto.</b> Assembly failures traceable to die quality belong against the sort coverage that let them through.'},
  ],
  risks:[
    '<b>KGD coverage below what the package economics need.</b> Every escaped die costs an assembled unit, and the coverage target follows from that cost rather than from a test convention.',
    '<b>Marginal criteria set against die cost.</b> On a 2.5D part the assembled unit is worth many times the die, and the reject threshold should reflect that.',
    '<b>Traceability lost between wafer and package.</b> An assembly failure that cannot be traced back to a die and its wafer position cannot be attributed.',
    '<b>Sort program not ready.</b> The probe card and program come from <code>TEST</code>, and a delay there stops assembly rather than delaying test.',
    '<b>Sorting only for function.</b> Parametric marginality—leakage, Vmin—predicts field failure and is worth screening even when the die functions.',
  ],
  roles:[
    {r:'Product engineering', d:'Owns sort criteria and die disposition'},
    {r:'Test engineering', d:'Sort program and probe card execution'},
    {r:'Yield engineer', d:'Wafer map analysis and marginal criteria'},
    {r:'Assembly liaison', d:'Die release, quantity and traceability'},
    {r:'Quality engineer', d:'KGD criteria against assembled unit cost'},
  ],
  effort:[['Sort execution',2], ['KGD selection and mapping',1.25], ['Sort setup',0.75], ['Marginal disposition',0.5], ['Release and traceability',0.5]],
  entry:[
    'Wafers delivered from FAB-10',
    'Sort program and probe card ready from TEST-03 and TEST-05',
    'KGD criteria agreed with the OSAT',
  ],
  exit:[
    'Coverage sufficient for the assembled unit\'s economics',
    'Marginal criteria set against package cost, not die cost',
    'Every released die traceable to wafer and position',
  ],
  dependsOn:['FAB-08','FAB-10','TEST-03','TEST-05','PKGD-10'],
  dependsNote:null,
  feedsInto:['ASSY-03','ASSY-07','ASSY-09'],
  measuredBy:[
    'KGD coverage achieved',
    'Assembly failures attributable to escaped die',
    'Die traceability to wafer position',
  ],
},

'ASSY-02': {
  stage:'packaging', window:[23,26], criticalPath:false,
  purpose:[
    'Procure and inspect the <b>HBM stacks</b>—bought components that go into the package alongside the program\'s own die, and that fail in ways the program does not control.',
    'HBM is a purchased part with its own supply constraints and its own quality distribution. Incoming inspection matters because an HBM stack that fails after assembly costs the whole unit, and the supplier\'s outgoing quality is not the program\'s to verify after the fact.',
  ],
  steps:[
    {n:1, text:'HBM procurement confirmation and delivery', tat:0.5, lane:'main'},
    {n:2, text:'Incoming inspection against specification', tat:1, lane:'main'},
    {n:3, text:'Supplier test data review', tat:0.75, lane:'par'},
    {n:4, text:'Stack qualification and release to assembly', tat:1, lane:'main'},
    {n:5, text:'Inventory and lot traceability', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 3 costs almost nothing and catches a class of problem inspection cannot. Supplier test data shows the distribution the delivered lot came from, and a lot at the edge of specification is worth knowing about before it is bonded in.',
  consumes:[
    'HBM purchase orders from MP-10 and procurement',
    'Supplier test data and certificates',
    'HBM specification and requirements from ARCH-03',
    'Incoming inspection capability',
    'Assembly quantity requirement',
  ],
  produces:[
    'Delivered HBM stacks',
    'Incoming inspection results',
    'Supplier test data review',
    'Qualified stacks released to assembly',
    'Inventory and lot traceability record',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'ASSY-D1', rel:'feeds', text:'<b>Assembled units.</b> HBM is part of every assembled unit, and its quality is part of the unit\'s.'},
    {id:'ASSY-D4', rel:'feeds', text:'<b>Package-level inspection and test data.</b> Incoming HBM data belongs with the assembly\'s own inspection record.'},
  ],
  risks:[
    '<b>HBM supply constrained.</b> It is a scarce component with long lead times, and a shortage stops assembly regardless of how many die are ready.',
    '<b>Incoming inspection skipped.</b> A marginal stack bonded into a unit costs the whole unit, and the fault is only visible afterwards.',
    '<b>Supplier data not reviewed.</b> The distribution the lot came from predicts its behavior, and the data is provided at no cost.',
    '<b>Lot traceability not maintained.</b> An HBM-related failure that cannot be traced to a supplier lot cannot be escalated usefully.',
    '<b>Specification mismatch discovered at assembly.</b> Stack height, bump pitch and thermal characteristics all have to match the package design.',
  ],
  roles:[
    {r:'Procurement', d:'HBM supply and delivery'},
    {r:'Quality engineer', d:'Incoming inspection and supplier data'},
    {r:'Package engineer', d:'Specification compliance'},
    {r:'Operations planner', d:'Inventory and traceability'},
    {r:'Supplier liaison', d:'Escalation on quality or supply'},
  ],
  effort:[['Incoming inspection',0.75], ['Stack qualification',0.5], ['Procurement coordination',0.4], ['Traceability',0.35]],
  entry:[
    'HBM ordered with committed delivery',
    'Specification and inspection criteria defined',
    'Inspection capability available',
  ],
  exit:[
    'Every lot inspected and its supplier data reviewed',
    'Stacks confirmed against the package specification',
    'Lot traceability maintained into assembly',
  ],
  dependsOn:['ARCH-03','TECH-09','PKGD-10'],
  dependsNote:null,
  feedsInto:['ASSY-03','ASSY-07','MP-10'],
  measuredBy:[
    'Stacks rejected at incoming inspection',
    'Supply delivered against the assembly schedule',
    'HBM-attributed failures after assembly',
  ],
},

'ASSY-03': {
  stage:'packaging', window:[25,28], criticalPath:true,
  purpose:[
    'Bond the die and HBM stacks to the interposer—<b>micro-bump preparation and thermo-compression bonding</b>—inside the process window the vehicles established.',
    'This is the step the whole PTV program existed to de-risk. Bond force, temperature and time were characterized on vehicles; here they are applied to real die, and the process window is either followed or the vehicle work was wasted.',
  ],
  steps:[
    {n:1, text:'Process setup to the frozen window', tat:0.5, lane:'main'},
    {n:2, text:'Micro-bump preparation and flux application', tat:1, lane:'main'},
    {n:3, text:'Bond parameter monitoring during the run', tat:0.75, lane:'par'},
    {n:4, text:'Thermo-compression bonding of die and stacks', tat:1, lane:'main'},
    {n:5, text:'Post-bond inspection', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 3 records what actually happened. The frozen window says what the parameters should be; monitoring says what they were, and a unit that failed can only be attributed if its actual bond conditions were captured.',
  consumes:[
    'Known-good die from ASSY-01',
    'Qualified HBM stacks from ASSY-02',
    'Interposers from PKGD-09 supply',
    'Frozen process window from PTV-12',
    'Assembly process flow from PKGD-10',
  ],
  produces:[
    'Process setup to the frozen window',
    'Prepared micro-bumps',
    'Bond parameter monitoring data',
    'Bonded die and stack assemblies',
    'Post-bond inspection results',
    'Assembly travelers with actual conditions',
  ],
  producedBy:[1,2,3,4,5,5],
  rel:[
    {id:'ASSY-D2', rel:'produces', text:'<b>Assembly travelers and process data.</b> This activity is where the traveler starts and where the actual bond conditions are recorded.'},
    {id:'ASSY-D1', rel:'feeds', text:'<b>Assembled units.</b> Bonding is the step that makes a set of components into a package.'},
  ],
  risks:[
    '<b>Running outside the frozen window.</b> The PTV program established boundaries; operating outside them discards the evidence it produced.',
    '<b>Bond parameters not recorded per unit.</b> A failed unit cannot be attributed to its conditions, and the yield analysis loses its most useful variable.',
    '<b>Bump preparation inconsistent.</b> Flux and surface condition affect joint formation, and variability here shows up as scattered yield.',
    '<b>Post-bond inspection sampled too thinly.</b> Bonding defects are localized, and a sample that misses them lets them through to underfill where they are unfixable.',
    '<b>Process drift across the run.</b> Long runs drift, and without monitoring the drift is only visible in the yield trend afterwards.',
  ],
  roles:[
    {r:'OSAT process engineer', d:'Executes bonding to the window'},
    {r:'Assembly process engineer', d:'Window compliance and monitoring'},
    {r:'Quality engineer', d:'Post-bond inspection and traveler discipline'},
    {r:'Package engineer', d:'Process deviation decisions'},
    {r:'Yield engineer', d:'Parameter-to-yield attribution'},
  ],
  effort:[['Thermo-compression bonding',2.5], ['Bump preparation',1.5], ['Process setup',1], ['Post-bond inspection',0.5], ['Parameter monitoring',0.5]],
  entry:[
    'Known-good die released from ASSY-01',
    'HBM stacks qualified in ASSY-02',
    'Process window frozen by PTV-12',
  ],
  exit:[
    'Every unit bonded inside the frozen window',
    'Actual bond parameters recorded per unit',
    'Post-bond inspection coverage sufficient to catch localized defects',
  ],
  dependsOn:['ASSY-01','ASSY-02','PTV-12','PKGD-10'],
  dependsNote:null,
  feedsInto:['ASSY-04','ASSY-06','ASSY-07'],
  measuredBy:[
    'Units bonded within the window',
    'Bond parameter capture rate',
    'Post-bond defects found against escaped',
  ],
},

'ASSY-04': {
  stage:'packaging', window:[26,29], criticalPath:true,
  purpose:[
    'Attach the interposer to the substrate and <b>underfill and mold</b> the assembly—the steps that make it mechanically robust and that lock in whatever went before.',
    'Underfill is irreversible. Once it has flowed and cured, a bonding defect underneath is permanent and invisible to everything except acoustic imaging. The step\'s quality—void-free flow, complete fillet, correct cure—determines whether the mechanical stress the package will see is distributed or concentrated.',
  ],
  steps:[
    {n:1, text:'Interposer to substrate attach', tat:0.5, lane:'main'},
    {n:2, text:'Underfill dispense and flow', tat:1, lane:'main'},
    {n:3, text:'Void and fillet inspection', tat:0.75, lane:'par'},
    {n:4, text:'Underfill cure and molding', tat:1, lane:'main'},
    {n:5, text:'Post-mold inspection', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 3 is the last chance to catch a bonding problem. Acoustic imaging before cure can still identify a void or an incomplete fill; after cure the unit is what it is, and the defect surfaces during thermal cycling months later.',
  consumes:[
    'Bonded assemblies from ASSY-03',
    'Substrates from PKGD-09 supply',
    'Underfill and mold compound specifications',
    'Frozen process window from PTV-12',
    'Warpage data from PTV-07',
  ],
  produces:[
    'Interposer-to-substrate attached assemblies',
    'Dispensed and flowed underfill',
    'Void and fillet inspection results',
    'Underfilled assemblies',
    'Cured and molded units',
    'Post-mold inspection results',
  ],
  producedBy:[1,2,3,4,5,5],
  rel:[
    {id:'ASSY-D1', rel:'feeds', text:'<b>Assembled units.</b> After molding the unit is mechanically complete.'},
    {id:'ASSY-D4', rel:'feeds', text:'<b>Package-level inspection and test data.</b> Void and fillet inspection results are part of the unit\'s quality record.'},
  ],
  risks:[
    '<b>Underfill voids.</b> They concentrate stress and are the mechanism behind delayed CPI failures, and they are invisible after cure without acoustic imaging.',
    '<b>Incomplete fillet.</b> The fillet distributes stress at the die edge, and an incomplete one puts that stress into the die corner instead.',
    '<b>Cure profile deviation.</b> Under-cured underfill has different mechanical properties, and the difference appears as reliability rather than as a visible defect.',
    '<b>Warpage during cure exceeding the window.</b> The vehicle program measured it; running outside that window reintroduces the risk that was retired.',
    '<b>Inspection only after molding.</b> Once molded the assembly cannot be examined usefully, and the inspection has to happen before.',
  ],
  roles:[
    {r:'OSAT process engineer', d:'Underfill, cure and molding execution'},
    {r:'Assembly process engineer', d:'Window compliance and profile control'},
    {r:'Quality engineer', d:'Void and fillet inspection'},
    {r:'Materials engineer', d:'Underfill and mold compound behavior'},
    {r:'Reliability liaison', d:'Defect implications for qualification'},
  ],
  effort:[['Underfill dispense and cure',2], ['Interposer attach',1.25], ['Molding',1], ['Inspection',0.75]],
  entry:[
    'Bonded assemblies from ASSY-03',
    'Substrates delivered against the PKGD-09 order',
    'Process window and materials specified',
  ],
  exit:[
    'Void and fillet inspected before cure, not after',
    'Cure profile within the frozen window',
    'Warpage during the process inside the validated range',
  ],
  dependsOn:['ASSY-03','PKGD-09','PTV-12'],
  dependsNote:null,
  feedsInto:['ASSY-05','ASSY-06','ASSY-07'],
  measuredBy:[
    'Void rate at inspection',
    'Fillet completeness',
    'Cure profile deviation from the window',
  ],
},

'ASSY-05': {
  stage:'packaging', window:[28,30], criticalPath:true,
  purpose:[
    'Finish the package—<b>TIM, lid and ball attach</b>—and produce units that can be mounted, cooled and tested.',
    'These are the last steps and they determine two things the product is judged on: the thermal interface that decides the achievable power envelope, and the ball array that decides whether the package mounts reliably. Both were characterized on vehicles and both are executed here.',
  ],
  steps:[
    {n:1, text:'TIM application and lid attach', tat:0.5, lane:'main'},
    {n:2, text:'Ball attach and reflow', tat:0.75, lane:'main'},
    {n:3, text:'Lid flatness and co-planarity check', tat:0.5, lane:'par'},
    {n:4, text:'Final visual and dimensional inspection', tat:0.75, lane:'main'},
  ],
  flowNote:'Step 1 sets the thermal performance the product will actually have. Bond line thickness under the lid is a process parameter, and the difference between the characterized value and the achieved one is watts of headroom.',
  consumes:[
    'Molded assemblies from ASSY-04',
    'TIM material and lid components',
    'Ball attach process from the frozen window',
    'TIM characterization from PTV-09',
    'Dimensional specification from PKGD-11',
  ],
  produces:[
    'Lidded units with applied TIM',
    'Ball-attached packages',
    'Lid flatness and co-planarity results',
    'Final inspection results',
    'Completed assembled units',
  ],
  producedBy:[1,2,3,4,4],
  rel:[
    {id:'ASSY-D1', rel:'produces', text:'<b>Assembled units—bring-up, qualification and sample lots.</b> This activity is where a unit becomes a finished package.'},
    {id:'ASSY-D4', rel:'feeds', text:'<b>Package-level inspection and test data.</b> Dimensional and flatness data belongs with the unit\'s record.'},
  ],
  risks:[
    '<b>TIM bond line thicker than characterized.</b> Thermal resistance rises, and the power envelope the product was sold on shrinks.',
    '<b>Lid flatness out of specification.</b> The cooling solution then contacts unevenly, which produces hotspots the thermal design did not predict.',
    '<b>Ball co-planarity outside the mounting window.</b> The package does not mount reliably, and the customer discovers it during their assembly.',
    '<b>Dimensional drift from the specification.</b> The package has to fit sockets, heatsinks and board footprints that were designed to the drawing.',
    '<b>Final inspection sampled rather than complete.</b> On an engineering build every unit is precious, and a defect shipped to bring-up costs lab days.',
  ],
  roles:[
    {r:'OSAT process engineer', d:'Lid, TIM and ball attach execution'},
    {r:'Thermal engineer', d:'TIM bond line and thermal implications'},
    {r:'Quality engineer', d:'Flatness, co-planarity and dimensional inspection'},
    {r:'Package engineer', d:'Specification compliance'},
    {r:'Product engineering', d:'Unit acceptance for downstream use'},
  ],
  effort:[['Lid and TIM attach',1.25], ['Ball attach',1], ['Inspection',0.75]],
  entry:[
    'Molded assemblies from ASSY-04',
    'TIM and lid components available',
    'Dimensional specification from PKGD-11',
  ],
  exit:[
    'TIM bond line within the characterized range',
    'Lid flatness and ball co-planarity inside specification',
    'Every unit inspected, not a sample',
  ],
  dependsOn:['ASSY-04','PTV-09','PKGD-11'],
  dependsNote:null,
  feedsInto:['ASSY-06','ASSY-08','ASSY-09'],
  measuredBy:[
    'TIM bond line against the characterized value',
    'Flatness and co-planarity yield',
    'Dimensional conformance',
  ],
},

'ASSY-06': {
  stage:'packaging', window:[26,28], criticalPath:false,
  purpose:[
    'Inspect the assemblies <b>without taking them apart</b>—X-ray for joints, acoustic imaging for delamination and voids, metrology for warpage—because most assembly defects are invisible from outside.',
    'A 2.5D package hides everything that matters. The joints are under the die, the underfill is under the interposer, and the only way to see any of it non-destructively is through imaging. What this activity catches is what does not reach bring-up as an unexplained failure.',
  ],
  steps:[
    {n:1, text:'Inspection plan and sampling strategy', tat:0.5, lane:'main'},
    {n:2, text:'X-ray inspection of joints and voids', tat:0.75, lane:'main'},
    {n:3, text:'Defect classification and disposition', tat:0.5, lane:'par'},
    {n:4, text:'Acoustic imaging and warpage metrology', tat:0.75, lane:'main'},
  ],
  flowNote:'Step 1\'s sampling strategy is a real decision on a small build. Full inspection is affordable at engineering-lot quantities and not at production volume, and starting with full coverage is what tells you what sampling would have missed.',
  consumes:[
    'Assemblies at each process stage from ASSY-03 to ASSY-05',
    'Inspection criteria from PTV vehicle results',
    'X-ray and CSAM capability at the OSAT',
    'Warpage limits from PTV-07',
    'Defect classification scheme',
  ],
  produces:[
    'Inspection plan and sampling strategy',
    'X-ray inspection results',
    'Defect classification and disposition',
    'Acoustic imaging and warpage results',
  ],
  producedBy:[1,2,3,4],
  rel:[
    {id:'ASSY-D4', rel:'produces', text:'<b>Package-level inspection and test data.</b> This activity is the deliverable—the non-destructive record of what is inside each unit.'},
    {id:'ASSY-D3', rel:'feeds', text:'<b>Assembly yield report and failure pareto.</b> Inspection findings are the physical evidence behind the yield numbers.'},
  ],
  risks:[
    '<b>Sampling too thin on an engineering build.</b> Full inspection is affordable at these quantities, and a defect reaching bring-up costs far more than the inspection would have.',
    '<b>Defects classified inconsistently.</b> Without a scheme the same feature is a defect on Monday and acceptable on Tuesday, and the yield data becomes noise.',
    '<b>Inspection only at the end.</b> Defects are cheapest to catch at the step that created them, and end-of-line inspection cannot attribute them.',
    '<b>Warpage limits not applied.</b> The vehicle program set them; a unit outside them is a reliability risk regardless of whether it functions.',
    '<b>Findings not fed back to process.</b> Inspection that produces a pass/fail and no process signal wastes most of its value.',
  ],
  roles:[
    {r:'Quality engineer', d:'Owns inspection and classification'},
    {r:'OSAT metrology', d:'X-ray, CSAM and warpage measurement'},
    {r:'Assembly process engineer', d:'Process feedback from findings'},
    {r:'Failure analysis engineer', d:'Ambiguous defect interpretation'},
    {r:'Package engineer', d:'Acceptance criteria against vehicle data'},
  ],
  effort:[['X-ray and acoustic imaging',1.25], ['Warpage metrology',0.75], ['Defect classification',0.5], ['Inspection plan',0.5]],
  entry:[
    'Assemblies available at each process stage',
    'Inspection criteria derived from PTV results',
    'Imaging capability available at the OSAT',
  ],
  exit:[
    'Inspection at each process step, not only at the end',
    'Defects classified against a consistent scheme',
    'Findings fed back to the process that created them',
  ],
  dependsOn:['ASSY-03','ASSY-04','ASSY-05','PTV-07'],
  dependsNote:null,
  feedsInto:['ASSY-07','ASSY-08','MP-04'],
  measuredBy:[
    'Coverage of inspection against build quantity',
    'Defects caught at the creating step',
    'Classification consistency',
  ],
},

'ASSY-07': {
  stage:'packaging', window:[26,31], criticalPath:false,
  purpose:[
    'Analyze the <b>assembly yield</b>, build the failure pareto, find the root causes with the OSAT and tune the process inside the window the vehicles defined.',
    'First-build assembly yield on a 2.5D part is rarely what the cost model assumed. This activity turns the gap into a set of attributed causes and process adjustments—and compares the result against what the vehicle program predicted, which is how the vehicle work gets validated in turn.',
  ],
  steps:[
    {n:1, text:'Yield data collection across process steps', tat:0.75, lane:'main'},
    {n:2, text:'Failure pareto by mode and process step', tat:1.25, lane:'main'},
    {n:3, text:'Comparison against the PTV yield prediction', tat:1, lane:'par'},
    {n:4, text:'Root cause analysis with the OSAT', tat:1.5, lane:'main'},
    {n:5, text:'Corrective action tracking', tat:1, lane:'par'},
    {n:6, text:'Process tuning inside the frozen window', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 6 stays inside the window deliberately. Tuning beyond the validated boundaries would abandon the evidence the vehicle program produced, and a yield improvement bought that way carries an unquantified reliability risk.',
  consumes:[
    'Yield data from every assembly step',
    'Inspection results from ASSY-06',
    'Continuity results from ASSY-08',
    'PTV yield prediction from PTV-11',
    'Frozen process window from PTV-12',
  ],
  produces:[
    'Yield data by process step',
    'Failure pareto by mode',
    'Comparison against vehicle prediction',
    'Root cause findings',
    'Corrective actions and their tracking',
    'Process tuning record',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'ASSY-D3', rel:'produces', text:'<b>Assembly yield report and failure pareto.</b> This activity is the deliverable, and the pareto is what the OSAT acts on.'},
    {id:'ASSY-D2', rel:'feeds', text:'<b>Assembly travelers and process data.</b> Yield attribution depends on the traveler data, and the analysis feeds back into what travelers should capture.'},
  ],
  risks:[
    '<b>Yield reported without attribution.</b> A number tells the program it has a problem; a pareto by process step tells the OSAT what to change.',
    '<b>Tuning outside the validated window.</b> It may improve yield and it discards the reliability evidence the vehicles produced.',
    '<b>Vehicle prediction not compared.</b> The comparison is what validates or invalidates the whole PTV program, and it is cheap to make.',
    '<b>Root cause pursued without the OSAT.</b> Process knowledge sits with the assembler, and analysis without them produces hypotheses rather than causes.',
    '<b>Corrective actions untracked.</b> An agreed action that nobody follows up is an action that did not happen.',
  ],
  roles:[
    {r:'Yield engineer', d:'Owns yield analysis and the pareto'},
    {r:'OSAT process engineer', d:'Root cause and process adjustment'},
    {r:'Quality engineer', d:'Failure classification and corrective action tracking'},
    {r:'Package engineer', d:'Window compliance for any tuning'},
    {r:'Product cost analyst', d:'Yield against the cost model assumption'},
  ],
  effort:[['Root cause analysis',2], ['Failure pareto',1.5], ['Process tuning',1.25], ['Data collection',0.75], ['Vehicle comparison',0.5]],
  entry:[
    'Assembly running with data collection in place',
    'Inspection and continuity results available',
    'Vehicle yield prediction available from PTV-11',
  ],
  exit:[
    'Failures attributed to process steps, not only counted',
    'Tuning kept inside the validated window',
    'Yield compared against the vehicle prediction',
  ],
  dependsOn:['ASSY-03','ASSY-04','ASSY-06','ASSY-08','PTV-11','PTV-12'],
  dependsNote:null,
  feedsInto:['MP-05','MP-10','PTV-12'],
  measuredBy:[
    'Assembly yield against the cost model',
    'Failures attributed to a process step',
    'Corrective actions completed',
  ],
},

'ASSY-08': {
  stage:'packaging', window:[29,31], criticalPath:false,
  purpose:[
    'Test the assembled packages <b>electrically for opens, shorts and marginal joints</b> before they go anywhere—the cheapest possible screen on the most expensive units the program has.',
    'A package-level continuity test costs minutes and catches assembly failures that would otherwise consume lab days at bring-up. On units this expensive, screening before shipping is not optional economics.',
  ],
  steps:[
    {n:1, text:'Test setup and continuity criteria', tat:0.5, lane:'main'},
    {n:2, text:'Open and short test execution', tat:0.75, lane:'main'},
    {n:3, text:'Marginal resistance screening', tat:0.5, lane:'par'},
    {n:4, text:'Failure disposition and unit release', tat:0.75, lane:'main'},
  ],
  flowNote:'Step 3 separates working from reliably working. A joint that conducts with elevated resistance passes a continuity test and fails in the field, and screening for it here is far cheaper than a field return.',
  consumes:[
    'Completed units from ASSY-05',
    'Continuity criteria from PTV-11',
    'Test hardware and fixtures',
    'Package pin map from PKGD-04',
    'Failure disposition process',
  ],
  produces:[
    'Test setup and criteria',
    'Open and short results per unit',
    'Marginal resistance screening results',
    'Failure disposition and released units',
  ],
  producedBy:[1,2,3,4],
  rel:[
    {id:'ASSY-D4', rel:'produces', text:'<b>Package-level inspection and test data.</b> The electrical half of the deliverable, alongside the imaging from <code>ASSY-06</code>.'},
    {id:'ASSY-D1', rel:'gates', text:'<b>Assembled units.</b> A unit that fails continuity is not released to bring-up, however scarce units are.'},
  ],
  risks:[
    '<b>Screening skipped because units are scarce.</b> A failed unit consumed at bring-up costs more lab time than the whole screen would have.',
    '<b>Continuity only, no resistance.</b> Marginal joints conduct and fail later, and only a resistance measurement distinguishes them.',
    '<b>Criteria not derived from vehicle data.</b> <code>PTV-11</code> measured what good and marginal look like, and the criteria should come from there.',
    '<b>Failures not fed to yield analysis.</b> An electrical failure is yield data and belongs in the pareto.',
    '<b>Test fixture damaging units.</b> On packages this expensive the fixture itself has to be qualified.',
  ],
  roles:[
    {r:'Package test engineer', d:'Owns the screen and its criteria'},
    {r:'Quality engineer', d:'Disposition and release decisions'},
    {r:'Yield engineer', d:'Failure data into the pareto'},
    {r:'OSAT test', d:'Execution and fixturing'},
    {r:'Product engineering', d:'Release decisions on marginal units'},
  ],
  effort:[['Test execution',1.25], ['Failure disposition',0.75], ['Test setup',0.5], ['Marginal screening',0.5]],
  entry:[
    'Completed units from ASSY-05',
    'Continuity criteria derived from PTV-11',
    'Test fixture available and qualified',
  ],
  exit:[
    'Every unit screened before release',
    'Marginal joints identified by resistance, not only continuity',
    'Failures fed into the yield pareto',
  ],
  dependsOn:['ASSY-05','PTV-11','PKGD-04'],
  dependsNote:null,
  feedsInto:['ASSY-07','ASSY-09','BU-01'],
  measuredBy:[
    'Units screened against units built',
    'Marginal units identified',
    'Fixture-induced damage',
  ],
},

'ASSY-09': {
  stage:'packaging', window:[28,31], criticalPath:true,
  purpose:[
    'Allocate the finished units—<b>bring-up, qualification, customer samples</b>—and build to that allocation, because the first build never has enough for everyone.',
    'Three groups need units simultaneously and all of them are on the critical path of something. Bring-up needs them to start debugging, qualification needs them to start a months-long stress campaign, and customers were promised samples. The allocation is a program decision, not an assembly one.',
  ],
  steps:[
    {n:1, text:'Allocation requirement collection from each consumer', tat:0.5, lane:'main'},
    {n:2, text:'Unit allocation and reservation', tat:1, lane:'main'},
    {n:3, text:'Contention resolution and escalation', tat:0.5, lane:'par'},
    {n:4, text:'Build to allocation across lots', tat:1, lane:'main'},
    {n:5, text:'Release and traceability per allocation', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 3 is a program decision escalated deliberately. Qualification starting late delays mass production; bring-up starting late delays everything; and customer samples are often contractual. Resolving that trade below the program level puts it in the wrong hands.',
  consumes:[
    'Screened units from ASSY-08',
    'Bring-up requirement from BU-01',
    'Qualification vehicle requirement from MP-01',
    'Customer sample commitments from DEF-01',
    'Build quantity from the assembly run',
  ],
  produces:[
    'Allocation requirements per consumer',
    'Unit allocation and reservation record',
    'Contention resolution decisions',
    'Units built to allocation',
    'Release and traceability per allocation',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'ASSY-D5', rel:'produces', text:'<b>Unit allocation record across bring-up, qual and customers.</b> This activity is the deliverable, and it settles a contention that would otherwise be settled by whoever asks loudest.'},
    {id:'ASSY-D1', rel:'produces', text:'<b>Assembled units—bring-up, qualification and sample lots.</b> The units as allocated lots rather than as an undifferentiated build.'},
  ],
  risks:[
    '<b>Allocation decided by whoever asks first.</b> The three consumers have different downstream consequences, and the trade belongs to the program.',
    '<b>Qualification starved.</b> Reliability stress runs for months; starting it late moves mass production directly.',
    '<b>Customer samples cut.</b> They are frequently contractual, and missing them has commercial consequences the program may not see.',
    '<b>Build quantity below the sum of needs.</b> Which is normal, and it means the shortfall has to be decided rather than discovered.',
    '<b>Traceability lost per allocation.</b> A qualification failure has to be traceable to its lot and its assembly conditions.',
  ],
  roles:[
    {r:'Program manager', d:'Owns the allocation and its contention'},
    {r:'Validation lead', d:'Bring-up requirement'},
    {r:'Quality lead', d:'Qualification vehicle requirement'},
    {r:'Product marketing', d:'Customer sample commitments'},
    {r:'Operations planner', d:'Build execution and traceability'},
  ],
  effort:[['Allocation and reservation',1], ['Build to allocation',0.75], ['Requirement collection',0.5], ['Contention resolution',0.5], ['Release and traceability',0.25]],
  entry:[
    'Units screened and released from ASSY-08',
    'Requirements collected from all three consumers',
    'Build quantity known',
  ],
  exit:[
    'Allocation decided at program level, not by request order',
    'Qualification quantity sufficient to start its campaign',
    'Every allocated unit traceable to its lot and conditions',
  ],
  dependsOn:['ASSY-01','ASSY-05','ASSY-08'],
  dependsNote:null,
  feedsInto:['BU-01','MP-02','MP-04','BU-12'],
  measuredBy:[
    'Units allocated against requested per consumer',
    'Qualification start date against the plan',
    'Traceability maintained per allocation',
  ],
},

'ASSY-10': {
  stage:'packaging', window:[0,20], criticalPath:true,
  purpose:[
    'Build the <b>production interposer</b> the assembly consumes—a silicon wafer run of its own, with its own mask set, started the week the package design freezes and finished before a single die is attached.',
    'On a 2.5D part the interposer is not a purchased commodity; it is a second silicon product on a second schedule. Nothing in the assembly window can begin without it, and its lead time is measured in months rather than weeks, so it is started against the frozen database rather than against the wafers coming out of <code>FAB</code>.',
  ],
  steps:[
    {n:1, text:'Release the frozen interposer database and mask tooling to the foundry', tat:1.5, lane:'main'},
    {n:2, text:'Interposer mask set fabrication and inspection', tat:4, lane:'main'},
    {n:3, text:'Interposer wafer start and through-silicon via formation', tat:3, lane:'main'},
    {n:4, text:'Redistribution layer and top-metal build on the interposer', tat:4, lane:'main'},
    {n:5, text:'Inline metrology and defect monitoring across the interposer run', tat:6, lane:'par'},
    {n:6, text:'Micro-bump and under-bump metallization', tat:2.5, lane:'main'},
    {n:7, text:'Interposer wafer acceptance test and warpage screening', tat:2.5, lane:'main'},
    {n:8, text:'Known-good interposer release and inventory handover to the OSAT', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 2 is the one that cannot be compressed. The interposer needs a mask set like any other silicon, and ordering it is gated on the same design freeze as the substrate—which is why both start in the same week and why that week, not the tapeout, is the real commitment point for the package.',
  consumes:[
    'Frozen interposer and RDL database from PKGD-11',
    'Interposer routing design from PKGD-03',
    'Foundry interposer capacity booked at PKGD-09',
    'Bump map and pitch from PKGD-02',
    'Assembly process window frozen at PTV-12',
  ],
  produces:[
    'Interposer database and mask tooling released to the foundry',
    'Interposer mask set, inspected and qualified',
    'Interposer wafers started with TSV formation complete',
    'Interposer RDL and top-metal build complete',
    'Inline metrology and defect record for the run',
    'Micro-bump and UBM formation complete',
    'Interposer wafer acceptance and warpage data',
    'Known-good interposer inventory released to assembly',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'ASSY-D1', rel:'feeds', text:'<b>Assembled units.</b> No interposer, no unit—this is the part the whole 2.5D stack is built on.'},
    {id:'ASSY-D2', rel:'feeds', text:'<b>Assembly travelers and process data.</b> Interposer lot and wafer identity is what makes an assembled unit traceable back to its base.'},
  ],
  risks:[
    '<b>Started against wafer-out rather than against the design freeze.</b> The interposer takes months, and a program that orders it when the die is ready has already lost the assembly slot.',
    '<b>Mask tooling treated as part of the die tapeout.</b> It is a separate mask set on a separate release, and it is gated on <code>PKGD-11</code> rather than on <code>TO-11</code>.',
    '<b>Warpage screened only at assembly.</b> An interposer that warps outside the window fails at bonding, where the die it takes with it is already expensive.',
    '<b>Capacity booked but not converted to a wafer start.</b> A reservation is not a lot; the start date is what has to be tracked.',
    '<b>No known-good screening before handover.</b> An unscreened interposer moves the yield loss into the assembly, which is the most expensive place to find it.',
  ],
  roles:[
    {r:'Package engineer', d:'Owns the interposer build and its acceptance criteria'},
    {r:'Foundry interface', d:'Wafer starts, capacity and lot tracking'},
    {r:'Mask operations', d:'Interposer tooling release and mask set completion'},
    {r:'Quality engineer', d:'Wafer acceptance and warpage screening'},
    {r:'Supply chain', d:'Inventory position and handover to the OSAT'},
  ],
  effort:[
    ['Interposer wafer processing', 3],
    ['Mask set and tooling', 2],
    ['Acceptance and screening', 1.5],
    ['Lot tracking and handover', 1.5],
  ],
  entry:[
    'Interposer database frozen and DRC clean at PKGD-11',
    'Foundry interposer capacity confirmed against PKGD-09',
    'Bump map and pitch final',
  ],
  exit:[
    'Mask set complete and inspected',
    'Wafer acceptance and warpage inside the assembly window',
    'Known-good interposer inventory released with traceability',
  ],
  dependsOn:['PKGD-11','PKGD-03','PKGD-09'],
  dependsNote:null,
  feedsInto:['ASSY-03','ASSY-04'],
  measuredBy:[
    'Weeks from design freeze to interposer availability',
    'Interposer wafer acceptance rate',
    'Warpage distribution against the assembly window',
  ],
  terms:['TSV','RDL','OSAT','CoWoS'],
},

'ASSY-11': {
  stage:'packaging', window:[0,16], criticalPath:true,
  purpose:[
    'Build the <b>production package substrate</b>—the organic carrier the interposer sits on—at the supplier, against the stack-up frozen at <code>PKGD-11</code>.',
    'Substrate lead time is the longest single external commitment in the back end and the one least under the program\'s control. It is ordered off the design freeze, not off the wafers, and in a tight advanced-packaging market it is the item that decides whether assembly starts on time.',
  ],
  steps:[
    {n:1, text:'Release the frozen substrate stack-up and tooling to the supplier', tat:1.5, lane:'main'},
    {n:2, text:'Laminate material allocation and lot commitment', tat:3, lane:'main'},
    {n:3, text:'Substrate core, build-up layers and fine-line escape routing', tat:5, lane:'main'},
    {n:4, text:'Supplier line monitoring and lot-to-lot variability review', tat:7, lane:'par'},
    {n:5, text:'Surface finish, solder resist and stiffener processing', tat:2.5, lane:'main'},
    {n:6, text:'Substrate electrical test, coplanarity and warpage screening', tat:2, lane:'main'},
    {n:7, text:'Incoming inspection and release of substrate lots to the OSAT', tat:2, lane:'main'},
  ],
  flowNote:'Step 2 is where the schedule is actually won or lost. Laminate allocation is a queue position at the supplier, and the programs that hold one booked it at <code>PKGD-09</code>, twenty weeks before this activity opens.',
  consumes:[
    'Frozen substrate stack-up and tooling from PKGD-11',
    'Escape routing and package DRC from PKGD-04',
    'Substrate supplier capacity booked at PKGD-09',
    'Warpage and co-planarity limits from PKGD-07',
    'Board-level reliability results from PTV-10',
  ],
  produces:[
    'Substrate stack-up and tooling released to the supplier',
    'Laminate allocation and material lot commitment',
    'Substrate build complete through escape routing',
    'Supplier line monitoring and variability record',
    'Surface finish and stiffener processing complete',
    'Substrate electrical test, coplanarity and warpage data',
    'Substrate lots released to assembly with traceability',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'ASSY-D1', rel:'feeds', text:'<b>Assembled units.</b> The substrate is the carrier every unit is built onto; it gates <code>ASSY-04</code> outright.'},
    {id:'ASSY-D2', rel:'feeds', text:'<b>Assembly travelers and process data.</b> Substrate lot identity travels with the unit and is what a warpage failure is attributed against.'},
  ],
  risks:[
    '<b>Lead time assumed rather than confirmed.</b> Twelve to sixteen weeks is the quiet-market figure; it has run to thirty, and the plan carries one buffer for both this and the interposer.',
    '<b>Laminate allocation not held.</b> Capacity booked at <code>PKGD-09</code> has to be converted to a material commitment, or the queue position is somebody else\'s.',
    '<b>Coplanarity screened at the OSAT instead of the supplier.</b> A substrate rejected at incoming has already consumed its whole lead time.',
    '<b>Single-sourced with no second supplier qualified.</b> The substrate is the longest external item and the one with the fewest alternatives.',
    '<b>Stiffener and surface finish changed after the freeze.</b> A late change here restarts the build rather than adjusting it.',
  ],
  roles:[
    {r:'Package engineer', d:'Owns the substrate build and acceptance'},
    {r:'Supply chain', d:'Laminate allocation, lead time and supplier escalation'},
    {r:'Supplier quality', d:'Line monitoring and lot disposition'},
    {r:'Quality engineer', d:'Coplanarity and warpage screening at incoming'},
    {r:'Program management', d:'Lead-time risk against the assembly start'},
  ],
  effort:[
    ['Substrate build oversight', 2],
    ['Material allocation and expediting', 1.5],
    ['Incoming screening', 1.5],
    ['Supplier quality', 1],
  ],
  entry:[
    'Substrate stack-up frozen and package DRC clean at PKGD-11',
    'Supplier capacity and laminate allocation confirmed',
    'Warpage and coplanarity limits agreed',
  ],
  exit:[
    'Electrical test and coplanarity inside the agreed limits',
    'Warpage screened at the supplier, not only at incoming',
    'Substrate lots released to the OSAT with lot traceability',
  ],
  dependsOn:['PKGD-11','PKGD-04','PKGD-09'],
  dependsNote:null,
  feedsInto:['ASSY-04','ASSY-05'],
  measuredBy:[
    'Weeks from design freeze to substrate availability',
    'Incoming acceptance rate by lot',
    'Coplanarity and warpage distribution against limits',
  ],
  terms:['OSAT','CPI'],
},

};
