/* BU — Silicon Bring-up. Twelve activities. Stage w102–120 (18w), 153 M/M. */
module.exports = {

'BU-01': {
  stage:'bringup', window:[0,1.5], criticalPath:true,
  purpose:[
    'Receive the first units, <b>check them and mount them</b>—a short activity whose only job is to make sure the most valuable objects the program has ever produced are not damaged before they are powered.',
    'There are very few first-silicon units and each represents the whole program\'s schedule. A unit destroyed by a mounting error or an unnoticed shipping defect is not replaceable inside any useful timeframe.',
  ],
  steps:[
    {n:1, text:'Sample receipt and incoming inspection', tat:0.5, lane:'main'},
    {n:2, text:'Board mounting and mechanical fit', tat:0.5, lane:'main'},
    {n:3, text:'Unit tracking register and allocation record', tat:0.5, lane:'par'},
    {n:4, text:'Pre-power checklist against the board\'s known issues', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 4 is the reason board bring-up happened first. The checklist is only meaningful because <code>EVB-07</code> already established which board behaviors are normal and which are faults.',
  consumes:[
    'Allocated units from ASSY-09',
    'Screened unit record from ASSY-08',
    'Brought-up boards from EVB-07',
    'Board known-issue list from EVB-07',
    'ESD and handling procedures',
  ],
  produces:[
    'Incoming inspection record',
    'Units mounted on boards',
    'Unit tracking and allocation register',
    'Pre-power checklist completion',
  ],
  producedBy:[1,2,3,4],
  rel:[
    {id:'BU-D1', rel:'feeds', text:'<b>Bring-up report with per-milestone health status.</b> Receipt and mounting are the report\'s first entries.'},
    {id:'BU-D5', rel:'informs', text:'<b>Failure analysis reports.</b> A unit\'s history starts here, and an FA needs to know how it was handled.'},
  ],
  risks:[
    '<b>Handling damage on an irreplaceable unit.</b> ESD or mechanical damage at mounting costs a unit the program cannot replace.',
    '<b>Mounting onto an unvalidated board.</b> A board fault then destroys the part, and <code>EVB-07</code> exists to prevent exactly this.',
    '<b>No unit tracking.</b> Every subsequent result has to be attributable to a specific unit and its history.',
    '<b>Incoming inspection skipped in the rush.</b> Shipping damage is real and is much cheaper to find before power than after.',
    '<b>All units mounted at once.</b> A systematic board or handling fault then takes the whole fleet rather than one unit.',
  ],
  roles:[
    {r:'Bring-up lead', d:'Owns the sequence and the unit register'},
    {r:'Hardware engineer', d:'Mounting and mechanical fit'},
    {r:'Quality engineer', d:'Incoming inspection'},
    {r:'Lab technician', d:'ESD-controlled handling'},
    {r:'Program manager', d:'Unit allocation and risk spreading'},
  ],
  effort:[['Board mounting',0.75], ['Incoming inspection',0.5], ['Pre-power checklist',0.5], ['Unit tracking',0.25]],
  entry:[
    'Units allocated and screened from ASSY-08 and ASSY-09',
    'Boards brought up and accepted from EVB-07',
    'ESD-controlled bench available',
  ],
  exit:[
    'Every unit inspected before mounting',
    'Units mounted only on validated boards',
    'Unit register started and maintained',
  ],
  dependsOn:['ASSY-08','ASSY-09','EVB-07'],
  dependsNote:null,
  feedsInto:['BU-02'],
  measuredBy:[
    'Units damaged during receipt and mounting',
    'Units traceable in the register',
    'Boards validated before mounting',
  ],
},

'BU-02': {
  stage:'bringup', window:[1,4], criticalPath:true,
  purpose:[
    'Apply power for the first time—<b>sequenced, current-limited and instrumented</b>—and establish that the part is alive.',
    'First power-on is the moment the whole design becomes physical. It is also the moment a shorted rail or a sequencing error can destroy a unit in milliseconds, which is why it is done with limits, with measurement, and with the ability to stop.',
  ],
  steps:[
    {n:1, text:'Power sequencing verification against the specification', tat:0.5, lane:'main'},
    {n:2, text:'First power application with current limits', tat:1, lane:'main'},
    {n:3, text:'Anomaly triage on the first application', tat:0.75, lane:'par'},
    {n:4, text:'Rail voltage and current profiling', tat:1, lane:'main'},
    {n:5, text:'Health check and go/no-go for the next step', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 2\'s current limits are what turn a fatal event into a diagnostic one. A rail that draws far more than expected trips the limit and the part survives to be investigated; without the limit it is destroyed and the information goes with it.',
  consumes:[
    'Mounted units from BU-01',
    'Power subsystem and protection from EVB-05',
    'Power sequencing specification from ARCH-08',
    'Expected rail currents from PD-08',
    'Telemetry from EVB-05',
  ],
  produces:[
    'Power sequencing verification',
    'First power application record',
    'Anomaly triage findings',
    'Rail voltage and current profiles',
    'Health check and go/no-go decision',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'BU-D1', rel:'feeds', text:'<b>Bring-up report with per-milestone health status.</b> Power-on is the first milestone and its result sets the program\'s tone.'},
    {id:'BU-D2', rel:'feeds', text:'<b>Characterization data set.</b> The first rail current measurements are the earliest real power data the program has.'},
  ],
  risks:[
    '<b>Power applied without current limits.</b> A short then destroys the unit instead of revealing itself.',
    '<b>Sequencing not verified against the specification.</b> A wrong power-up order damages the part and the fault is the platform\'s, not the silicon\'s.',
    '<b>Rail currents not profiled.</b> The first real power data is available at exactly this moment and is easy to not capture.',
    '<b>Multiple units powered before the first is understood.</b> A systematic fault then takes several units instead of one.',
    '<b>Anomalies pushed past to reach the next milestone.</b> Something unexplained at power-on rarely stays harmless.',
  ],
  roles:[
    {r:'Bring-up lead', d:'Owns the sequence and the go/no-go'},
    {r:'Power engineer', d:'Sequencing, limits and rail measurement'},
    {r:'Design engineer', d:'Expected currents and anomaly interpretation'},
    {r:'Validation engineer', d:'Instrumentation and data capture'},
    {r:'Program manager', d:'Unit risk exposure'},
  ],
  effort:[['First power application',2.5], ['Rail profiling',2], ['Sequencing verification',1.5], ['Anomaly triage',1.25], ['Health check',0.75]],
  entry:[
    'Units mounted from BU-01',
    'Power subsystem validated in EVB-05',
    'Expected rail currents from PD-08',
  ],
  exit:[
    'Current limits in place before first application',
    'Rail currents profiled against expectation',
    'No unexplained anomaly carried into the next milestone',
  ],
  dependsOn:['BU-01','EVB-05','ARCH-08','PD-08'],
  dependsNote:null,
  feedsInto:['BU-03','BU-09','MP-05'],
  measuredBy:[
    'Units surviving first power-on',
    'Rail currents against prediction',
    'Anomalies resolved before proceeding',
  ],
},

'BU-03': {
  stage:'bringup', window:[2,5], criticalPath:false,
  purpose:[
    'Validate <b>reset, clocking and PLL lock</b>—the infrastructure everything else depends on, and the layer where a fault masquerades as a fault somewhere else.',
    'A PLL that locks unreliably or a reset domain released in the wrong order produces symptoms all over the chip: boot failures, interface training failures, sporadic functional errors. Clearing this layer first means the failures found later are real.',
  ],
  steps:[
    {n:1, text:'Reference clock and input validation', tat:0.5, lane:'main'},
    {n:2, text:'PLL lock across the frequency range', tat:1, lane:'main'},
    {n:3, text:'Reset sequence and domain release verification', tat:0.75, lane:'par'},
    {n:4, text:'Clock tree and domain verification', tat:1, lane:'main'},
    {n:5, text:'Jitter and stability measurement', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 5\'s jitter measurement is easy to skip because the part appears to work without it. It matters because interface training margin depends on clock quality, and a jitter problem found here explains a class of failures that would otherwise be chased in the SerDes.',
  consumes:[
    'Powered units from BU-02',
    'PLL specifications from AMS-04',
    'Clock architecture from ARCH-05',
    'Reset architecture from RTL-04',
    'Clock instrumentation from EVB-09',
  ],
  produces:[
    'Reference clock validation',
    'PLL lock results across the range',
    'Reset sequence and domain release verification',
    'Clock tree and domain verification',
    'Jitter and stability measurements',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'BU-D1', rel:'feeds', text:'<b>Bring-up report with per-milestone health status.</b> Clocking and reset form the second milestone.'},
    {id:'BU-D2', rel:'feeds', text:'<b>Characterization data set.</b> PLL lock range and jitter are datasheet-relevant measurements.'},
  ],
  risks:[
    '<b>PLL lock validated only at nominal.</b> The lock range matters because shmoo and characterization will operate outside nominal.',
    '<b>Reset domain release order not verified.</b> The resulting failures appear anywhere on the chip and are attributed to the wrong block.',
    '<b>Jitter unmeasured.</b> Interface training margin depends on it, and a jitter problem is then debugged inside the SerDes.',
    '<b>Clock tree assumed correct because the part boots.</b> A misconfigured divider is compatible with booting and incompatible with performance.',
    '<b>Clock quality measured through the board without accounting for it.</b> The board contributes jitter and its contribution has to be separated.',
  ],
  roles:[
    {r:'Bring-up engineer', d:'Owns clocking and reset validation'},
    {r:'AMS engineer', d:'PLL behavior and lock characteristics'},
    {r:'Design engineer', d:'Clock tree and reset architecture'},
    {r:'Characterization engineer', d:'Jitter measurement'},
    {r:'Validation engineer', d:'Instrumentation and data capture'},
  ],
  effort:[['PLL lock validation',2.5], ['Clock tree verification',2], ['Reset sequence verification',1.5], ['Jitter measurement',1.25], ['Reference validation',0.75]],
  entry:[
    'Units powered and healthy from BU-02',
    'PLL specification from AMS-04',
    'Clock instrumentation available from EVB-09',
  ],
  exit:[
    'PLL lock verified across the full operating range',
    'Reset domain release order confirmed against the architecture',
    'Jitter measured with the board\'s contribution separated',
  ],
  dependsOn:['BU-02','AMS-04','ARCH-05','RTL-04'],
  dependsNote:null,
  feedsInto:['BU-04','BU-05','BU-09'],
  measuredBy:[
    'PLL lock range achieved against specification',
    'Jitter against the interface budget',
    'Reset-related failures found later',
  ],
},

'BU-04': {
  stage:'bringup', window:[4,8], criticalPath:true,
  purpose:[
    '<b>Boot the part</b>—ROM, firmware load, register access, first functional response—and confirm that the design does what it was written to do.',
    'First boot is the milestone that turns a powered die into a working processor. It is also the point at which the design, the firmware, the board and the host software are all exercised together for the first time, which is why it is the milestone most likely to expose an integration assumption nobody wrote down.',
  ],
  steps:[
    {n:1, text:'Boot ROM and initialization sequence execution', tat:0.75, lane:'main'},
    {n:2, text:'Firmware load and handoff', tat:1.25, lane:'main'},
    {n:3, text:'Boot failure triage', tat:1, lane:'par'},
    {n:4, text:'Register access and device identity read', tat:1.25, lane:'main'},
    {n:5, text:'First bring-up report and status broadcast', tat:1, lane:'par'},
    {n:6, text:'Functional smoke test', tat:0.75, lane:'main'},
  ],
  flowNote:'Step 4\'s first successful register read is the moment the program knows the silicon is fundamentally sound. Everything before it is infrastructure and everything after it is degrees of correctness.',
  consumes:[
    'Clocking-validated units from BU-03',
    'Host enablement from EVB-10',
    'Boot ROM and firmware from the firmware team',
    'Register map from RTL-06',
    'Debug access from EVB-06',
  ],
  produces:[
    'Boot ROM execution record',
    'Firmware load and handoff results',
    'Boot failure triage findings',
    'Register access and identity read',
    'First bring-up report',
    'Functional smoke test results',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'BU-D1', rel:'produces', text:'<b>Bring-up report with per-milestone health status.</b> First boot is the report\'s central milestone and where it starts being published widely.'},
    {id:'BU-D4', rel:'feeds', text:'<b>Errata list with workarounds.</b> Boot-time deviations are the earliest errata the program records.'},
  ],
  risks:[
    '<b>Boot failure with no state visible.</b> Without debug access the failure is a symptom with no information, and debug access comes from <code>EVB-06</code>.',
    '<b>Firmware and hardware assumptions differing.</b> The handoff is where two teams\' expectations meet, and nobody wrote them down.',
    '<b>Register map drift.</b> The tool reads addresses the silicon does not implement and reports plausible garbage.',
    '<b>Smoke test too shallow.</b> A part that boots and does nothing else has passed a milestone without demonstrating much.',
    '<b>Status not broadcast.</b> First boot is the news the whole program is waiting for, and silence is read as failure.',
  ],
  roles:[
    {r:'Bring-up lead', d:'Owns the boot milestone'},
    {r:'Firmware engineer', d:'Boot ROM, firmware load and handoff'},
    {r:'Design engineer', d:'Register map and failure interpretation'},
    {r:'Validation software engineer', d:'Host tooling and register access'},
    {r:'Program manager', d:'Status broadcast and expectation management'},
  ],
  effort:[['Firmware load and handoff',3.5], ['Register access',3], ['Boot sequence execution',2.5], ['Failure triage',1.75], ['Smoke test',1.25]],
  entry:[
    'Clocking and reset validated in BU-03',
    'Host enablement validated in EVB-10',
    'Firmware and boot ROM available',
  ],
  exit:[
    'Successful register read and device identity confirmed',
    'Boot-time deviations captured as errata candidates',
    'Status broadcast to the program',
  ],
  dependsOn:['BU-03','EVB-06','EVB-10','RTL-06'],
  dependsNote:null,
  feedsInto:['BU-05','BU-06','BU-09','BU-10'],
  measuredBy:[
    'Time from power-on to first register read',
    'Boot failures with usable state captured',
    'Smoke test coverage at first boot',
  ],
},

'BU-05': {
  stage:'bringup', window:[6,14], criticalPath:true,
  purpose:[
    'Bring up the <b>interfaces</b>—PCIe/CXL link training, HBM training, die-to-die—which on this part is the largest single body of bring-up work and the most likely to produce a respin decision.',
    'Interfaces are where design, package, board and protocol all meet. Training failures are notoriously hard to attribute because every layer can cause them, and the margin measurements taken here are what tell the program whether the part is comfortable or on the edge.',
  ],
  steps:[
    {n:1, text:'Interface bring-up order and plan', tat:1, lane:'main'},
    {n:2, text:'PCIe/CXL link training', tat:2, lane:'main'},
    {n:3, text:'Link margin and eye measurement', tat:2, lane:'par'},
    {n:4, text:'HBM interface training', tat:2.5, lane:'main'},
    {n:5, text:'Training failure debug', tat:2, lane:'par'},
    {n:6, text:'Die-to-die interface bring-up', tat:1.5, lane:'main'},
    {n:7, text:'Interoperability against host platforms', tat:1.5, lane:'par'},
    {n:8, text:'Interface stability and compliance run', tat:1, lane:'main'},
  ],
  flowNote:'Step 3 is not optional even when training succeeds. A link that trains with no margin trains today and fails at temperature or on a different host, and only the eye measurement distinguishes the two.',
  consumes:[
    'Booted units from BU-04',
    'SIPI channel budget and predictions from SIPI-04 and SIPI-05',
    'Debug and trace access from EVB-06',
    'Lab instrumentation from EVB-09',
    'Interface specifications from ARCH-03',
  ],
  produces:[
    'Interface bring-up order and plan',
    'PCIe/CXL link training results',
    'Link margin and eye measurements',
    'HBM training results',
    'Training failure debug findings',
    'Interface bring-up plan',
    'Die-to-die interface results',
    'Interoperability results',
    'Interface stability and compliance data',
  ],
  producedBy:[1,2,3,4,5,6,6,7,8],
  rel:[
    {id:'BU-D3', rel:'produces', text:'<b>Interface compliance results with training margins.</b> This activity is the deliverable, and the margins are what say whether the part is comfortable.'},
    {id:'BU-D1', rel:'feeds', text:'<b>Bring-up report with per-milestone health status.</b> Interface training is the milestone that decides whether the product works as designed.'},
  ],
  risks:[
    '<b>Training success accepted without margin measurement.</b> A zero-margin link works on the bench and fails in the field.',
    '<b>Failures not attributable across layers.</b> Design, package, board and protocol can all cause the same symptom, and the SIPI predictions are what separate them.',
    '<b>HBM training treated as a vendor problem.</b> The interface is the program\'s, and its training parameters have to be understood locally.',
    '<b>Interoperability tested against one host.</b> Customers use many, and a link that only works with the lab\'s host is not compliant.',
    '<b>Compliance run deferred.</b> Formal compliance is a gate for certification and takes lab time that has to be booked.',
  ],
  roles:[
    {r:'Interface engineer', d:'Owns link and memory training'},
    {r:'SI/PI engineer', d:'Margin attribution against the channel budget'},
    {r:'Design engineer', d:'SerDes and controller behavior'},
    {r:'Validation engineer', d:'Compliance and interoperability'},
    {r:'Bring-up lead', d:'Prioritization and escalation'},
  ],
  effort:[['HBM training',7], ['PCIe/CXL training',6], ['Margin and eye measurement',4.5], ['Training failure debug',4], ['Die-to-die bring-up',2.5], ['Compliance and interoperability',2]],
  entry:[
    'Units booted from BU-04',
    'SIPI predictions available from SIPI-04 and SIPI-05',
    'High-speed instrumentation available from EVB-09',
  ],
  exit:[
    'Every interface\'s margin measured, not only its training result',
    'Failures attributed to a layer against the SIPI prediction',
    'Interoperability confirmed on more than the lab\'s host',
  ],
  dependsOn:['BU-04','SIPI-04','SIPI-05','EVB-06','EVB-09'],
  dependsNote:null,
  feedsInto:['BU-06','BU-08','BU-10','TEST-10','MP-11'],
  measuredBy:[
    'Training margin against the SIPI prediction',
    'Interfaces trained against interfaces designed',
    'Interoperability across host platforms',
  ],
},

'BU-06': {
  stage:'bringup', window:[8,14], criticalPath:false,
  purpose:[
    'Validate the <b>memory subsystem</b>—controller, address map, bandwidth, latency, ECC—because on an AI accelerator the memory system is most of the performance.',
    'HBM training establishes that the links work; this establishes that the memory system delivers. Bandwidth and latency against the architecture model is the measurement the product\'s performance claims rest on, and it is where architectural assumptions meet a real memory controller.',
  ],
  steps:[
    {n:1, text:'Memory controller initialization and configuration', tat:1, lane:'main'},
    {n:2, text:'Address map and pattern validation', tat:1.5, lane:'main'},
    {n:3, text:'ECC and error handling validation', tat:1.5, lane:'par'},
    {n:4, text:'Bandwidth measurement against the model', tat:1.5, lane:'main'},
    {n:5, text:'Refresh and thermal behavior', tat:1.5, lane:'par'},
    {n:6, text:'Latency and efficiency characterization', tat:2, lane:'main'},
  ],
  flowNote:'Step 3 has to be done deliberately by injecting errors. ECC that has never corrected anything is ECC that has never been shown to work, and a broken correction path is silent until it matters.',
  consumes:[
    'Trained HBM interfaces from BU-05',
    'Memory subsystem model from ARCH-04',
    'Address map from RTL-05',
    'Memory test content from TEST-06',
    'Thermal capability from EVB-08',
  ],
  produces:[
    'Controller initialization and configuration',
    'Address map and pattern validation',
    'ECC and error handling validation',
    'Bandwidth measurements against the model',
    'Refresh and thermal behavior data',
    'Latency and efficiency characterization',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'BU-D2', rel:'feeds', text:'<b>Characterization data set.</b> Memory bandwidth, latency and efficiency are core characterization results.'},
    {id:'BU-D3', rel:'feeds', text:'<b>Interface compliance results with training margins.</b> Sustained memory operation is what proves the trained interfaces hold.'},
  ],
  risks:[
    '<b>ECC never exercised.</b> A correction path that has never corrected an injected error has not been validated.',
    '<b>Bandwidth measured without the model to compare against.</b> A number without a target says nothing about whether the design met its intent.',
    '<b>Refresh behavior at temperature not checked.</b> HBM refresh scales with temperature and the effect on bandwidth is real.',
    '<b>Address map validated only at the boundaries.</b> Aliasing errors sit in the middle of the map and pass boundary tests.',
    '<b>Efficiency ignored in favor of peak.</b> Peak bandwidth is a datasheet number; achieved efficiency is what workloads see.',
  ],
  roles:[
    {r:'Memory engineer', d:'Owns memory subsystem validation'},
    {r:'Architect', d:'Model comparison and efficiency expectation'},
    {r:'Design engineer', d:'Controller behavior and address map'},
    {r:'Validation engineer', d:'ECC injection and error handling'},
    {r:'Thermal engineer', d:'Refresh and temperature interaction'},
  ],
  effort:[['Bandwidth measurement',4.5], ['Latency characterization',3.5], ['Address map validation',3], ['ECC validation',2.5], ['Controller initialization',1.5], ['Refresh behavior',1]],
  entry:[
    'HBM interfaces trained in BU-05',
    'Architecture memory model available from ARCH-04',
    'Thermal control available from EVB-08',
  ],
  exit:[
    'ECC validated by injected errors, not by absence of failures',
    'Bandwidth and latency compared against the architecture model',
    'Efficiency characterized, not only peak',
  ],
  dependsOn:['BU-05','ARCH-04','RTL-05','EVB-08'],
  dependsNote:null,
  feedsInto:['BU-08','BU-10','MP-12'],
  measuredBy:[
    'Achieved bandwidth against the model',
    'Latency against the architectural target',
    'ECC correction verified by injection',
  ],
},

'BU-07': {
  stage:'bringup', window:[9,16], criticalPath:false,
  purpose:[
    '<b>Shmoo the part</b> across voltage, frequency and temperature—the measurement that establishes how much margin the design actually has.',
    'Every operating condition the product will be specified at comes out of this. The shmoo shows where the part stops working, and the distance between that boundary and the nominal operating point is the margin the datasheet, the guard bands and the qualification plan all depend on.',
  ],
  steps:[
    {n:1, text:'Shmoo plan and automation setup', tat:1, lane:'main'},
    {n:2, text:'Voltage-frequency shmoo at room temperature', tat:1.5, lane:'main'},
    {n:3, text:'Power measurement across the sweep', tat:1.5, lane:'par'},
    {n:4, text:'Temperature-extended shmoo', tat:1.5, lane:'main'},
    {n:5, text:'Unit-to-unit variation across the fleet', tat:1.5, lane:'par'},
    {n:6, text:'Shmoo analysis and margin extraction', tat:3, lane:'main'},
  ],
  flowNote:'Step 5 is what separates a characteristic from an anecdote. One unit\'s shmoo is that unit; the fleet\'s spread is what the population looks like, and the specification has to be set against the population.',
  consumes:[
    'Booted and interface-trained units from BU-04 and BU-05',
    'Sweep automation from EVB-09',
    'Thermal control from EVB-08',
    'Rail sweep capability from EVB-05',
    'Characterization content from TEST-07',
  ],
  produces:[
    'Shmoo plan and automation',
    'Voltage-frequency shmoo at room',
    'Power measurements across the sweep',
    'Temperature-extended shmoo',
    'Unit-to-unit variation data',
    'Margin extraction and analysis',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'BU-D2', rel:'produces', text:'<b>Characterization data set—V/F/T shmoo and power measurements.</b> This activity is the deliverable.'},
    {id:'BU-D1', rel:'feeds', text:'<b>Bring-up report with per-milestone health status.</b> Margin is the strongest single indicator of whether the silicon is healthy.'},
  ],
  risks:[
    '<b>Shmoo on a single unit.</b> The result describes that unit and is used as if it described the population.',
    '<b>Room temperature only.</b> The hot and cold corners are where the margin is smallest and where qualification will operate.',
    '<b>Manual sweeps.</b> The corner count then gets reduced to fit the available engineer time, silently.',
    '<b>Thermal throttling inside the sweep.</b> The shmoo then maps the cooling solution rather than the silicon.',
    '<b>Margin measured but not fed into guard bands.</b> The data exists and production test still uses convention.',
  ],
  roles:[
    {r:'Characterization engineer', d:'Owns the shmoo campaign'},
    {r:'Validation engineer', d:'Automation and data capture'},
    {r:'Product engineering', d:'Margin interpretation and guard bands'},
    {r:'Thermal engineer', d:'Temperature control and throttling checks'},
    {r:'Design engineer', d:'Failure mode interpretation at the boundaries'},
  ],
  effort:[['Temperature-extended shmoo',4], ['Voltage-frequency shmoo',3.5], ['Margin extraction',3], ['Power measurement',2.5], ['Unit-to-unit variation',2], ['Automation setup',1]],
  entry:[
    'Units functional from BU-04 and BU-05',
    'Sweep automation working from EVB-09',
    'Thermal control available from EVB-08',
  ],
  exit:[
    'Shmoo across a fleet, not a single unit',
    'Temperature corners included, not only room',
    'No throttling inside the measured region',
  ],
  dependsOn:['BU-04','BU-05','EVB-05','EVB-08','EVB-09','TEST-07'],
  dependsNote:null,
  feedsInto:['BU-08','BU-11','MP-06','MP-08','TEST-10'],
  measuredBy:[
    'Margin at the worst corner',
    'Units in the shmoo sample',
    'Corners measured against planned',
  ],
},

'BU-08': {
  stage:'bringup', window:[11,17], criticalPath:false,
  purpose:[
    'Measure <b>real performance against the architecture model</b>—the check on whether the product does what it was sold as doing.',
    'The whole program was justified by a performance projection. This is where that projection meets a physical part running real workloads, and any gap has to be attributed: to the model, to the design, to the memory system, or to the software driving it.',
  ],
  steps:[
    {n:1, text:'Benchmark and workload setup', tat:1, lane:'main'},
    {n:2, text:'Performance measurement across workloads', tat:1.5, lane:'main'},
    {n:3, text:'Power efficiency measurement', tat:1.5, lane:'par'},
    {n:4, text:'Comparison against the architecture model', tat:1.5, lane:'main'},
    {n:5, text:'Bottleneck profiling', tat:1.5, lane:'par'},
    {n:6, text:'Gap analysis and attribution', tat:2, lane:'main'},
  ],
  flowNote:'Step 6 is where the program learns something durable. A gap attributed to the model improves the next program\'s projections; a gap attributed to the design becomes an errata or a respin input; an unattributed gap teaches nothing.',
  consumes:[
    'Functional units from BU-04 through BU-06',
    'Architecture performance model from ARCH-02',
    'Workload definitions from DEF-03',
    'Power measurement from BU-07',
    'Lab instrumentation from EVB-09',
  ],
  produces:[
    'Benchmark and workload setup',
    'Performance measurements across workloads',
    'Power efficiency measurements',
    'Comparison against the architecture model',
    'Bottleneck profiling results',
    'Gap analysis and attribution',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'BU-D2', rel:'feeds', text:'<b>Characterization data set.</b> Performance and efficiency measurements are part of the product\'s characterization.'},
    {id:'BU-D1', rel:'feeds', text:'<b>Bring-up report with per-milestone health status.</b> Performance against target is the milestone the business cares about most.'},
  ],
  risks:[
    '<b>Performance measured on unrepresentative workloads.</b> A benchmark that is not what customers run produces a number that does not predict their experience.',
    '<b>Gap reported without attribution.</b> Nobody can act on it, and the next program repeats the modeling error.',
    '<b>Software limiting the measurement.</b> An immature stack understates the silicon, and the difference has to be established rather than assumed.',
    '<b>Efficiency ignored.</b> Performance per watt is the metric this product class is bought on, and raw throughput alone misleads.',
    '<b>Measured at a single operating point.</b> Real deployment spans conditions, and performance at nominal is not the whole picture.',
  ],
  roles:[
    {r:'Performance engineer', d:'Owns measurement and attribution'},
    {r:'Architect', d:'Model comparison and gap interpretation'},
    {r:'Validation software engineer', d:'Workload execution and software effects'},
    {r:'Design engineer', d:'Bottleneck root cause'},
    {r:'Product marketing', d:'Workload representativeness'},
  ],
  effort:[['Performance measurement',4], ['Model comparison',3.5], ['Gap analysis',3], ['Bottleneck profiling',2.5], ['Efficiency measurement',2], ['Benchmark setup',1]],
  entry:[
    'Memory subsystem validated in BU-06',
    'Architecture model available from ARCH-02',
    'Workloads defined in DEF-03',
  ],
  exit:[
    'Every material gap attributed to a cause',
    'Efficiency measured alongside throughput',
    'Software\'s contribution to the measurement established',
  ],
  dependsOn:['BU-05','BU-06','BU-07','ARCH-02','DEF-03'],
  dependsNote:null,
  feedsInto:['BU-11','MP-12','TEST-10'],
  measuredBy:[
    'Performance against the architecture projection',
    'Efficiency against the target',
    'Gaps attributed against gaps found',
  ],
},

'BU-09': {
  stage:'bringup', window:[4,14], criticalPath:true,
  purpose:[
    '<b>Debug what is wrong</b>—reproduce it, isolate it, extract the internal state, find the root cause, and get failure analysis where physical evidence is needed.',
    'This is the activity the whole DFT and debug infrastructure investment exists to serve. It runs alongside every other bring-up activity because anomalies arrive from all of them, and its throughput largely determines how long bring-up takes.',
  ],
  steps:[
    {n:1, text:'Anomaly intake and triage process', tat:1, lane:'main'},
    {n:2, text:'Reproduction and isolation', tat:2, lane:'main'},
    {n:3, text:'Simulation and emulation cross-check', tat:2, lane:'par'},
    {n:4, text:'Internal state extraction via DFT and trace', tat:2.5, lane:'main'},
    {n:5, text:'Design-team escalation and analysis', tat:2, lane:'par'},
    {n:6, text:'Hypothesis test and root cause', tat:2.5, lane:'main'},
    {n:7, text:'Debug knowledge capture', tat:1.5, lane:'par'},
    {n:8, text:'Failure analysis request and disposition', tat:2, lane:'main'},
  ],
  flowNote:'Step 3 is the highest-leverage step in the activity. An anomaly reproduced in simulation can be examined with full visibility and unlimited retries, which is an environment no amount of silicon debug can match.',
  consumes:[
    'Anomalies from every bring-up activity',
    'DFT and trace access from DFT-08 and EVB-06',
    'Simulation and emulation environments from DV-08 and DV-11',
    'Design database and RTL from RTL-09',
    'FA laboratory capability',
  ],
  produces:[
    'Anomaly intake and triage records',
    'Reproduction and isolation results',
    'Simulation and emulation cross-check findings',
    'Extracted internal state',
    'Design-team analysis',
    'Root cause determinations',
    'Debug knowledge base',
    'Failure analysis reports and dispositions',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'BU-D5', rel:'produces', text:'<b>Failure analysis reports.</b> This activity is the deliverable, and physical FA is its most conclusive form.'},
    {id:'BU-D4', rel:'feeds', text:'<b>Errata list with workarounds.</b> Every root cause found here becomes an errata entry or a fix.'},
  ],
  risks:[
    '<b>Symptoms treated instead of causes.</b> A workaround without a root cause hides a mechanism that resurfaces in the field.',
    '<b>No path back to simulation.</b> Debug then happens only on silicon, with limited visibility and long turnaround per hypothesis.',
    '<b>Design team engaged late.</b> The people who wrote the logic can often recognize a symptom in minutes, and validation debugs alone for days first.',
    '<b>Units consumed by destructive FA too readily.</b> Physical analysis destroys the unit, and there are very few.',
    '<b>Findings not captured.</b> The same anomaly is then debugged twice by different engineers.',
  ],
  roles:[
    {r:'Silicon debug engineer', d:'Owns anomaly resolution'},
    {r:'Design engineer', d:'Logic analysis and hypothesis generation'},
    {r:'DFT engineer', d:'State extraction and trace'},
    {r:'DV engineer', d:'Simulation and emulation reproduction'},
    {r:'Failure analysis engineer', d:'Physical analysis and disposition'},
  ],
  effort:[['Root cause determination',7], ['Internal state extraction',6], ['Reproduction and isolation',5], ['Simulation cross-check',4], ['FA and disposition',3.5], ['Knowledge capture',2.5]],
  entry:[
    'Anomalies arriving from bring-up activities',
    'DFT and trace access working from EVB-06',
    'Simulation and emulation environments available',
  ],
  exit:[
    'Root cause established rather than symptom suppressed',
    'Anomalies reproduced in simulation where possible',
    'Findings captured so they are debugged once',
  ],
  dependsOn:['BU-02','BU-03','BU-04','BU-05','DFT-08','EVB-06','DV-08','DV-11'],
  dependsNote:'Anomalies arrive from every bring-up activity; the dependencies listed are the ones that supply the debug capability rather than the problems.',
  feedsInto:['BU-10','BU-11','MP-05'],
  measuredBy:[
    'Anomalies root-caused against opened',
    'Median time from anomaly to root cause',
    'Anomalies reproduced outside silicon',
  ],
},

'BU-10': {
  stage:'bringup', window:[10,17], criticalPath:false,
  purpose:[
    'Turn what is wrong into a <b>documented errata list with workarounds</b>—the honest account of the silicon\'s behavior that customers and the next revision both need.',
    'Every part ships with errata. What distinguishes a well-run program is that its errata are known, characterized, worked around and disclosed, rather than discovered by a customer. This activity is where debug findings become a product document.',
  ],
  steps:[
    {n:1, text:'Errata intake and classification', tat:1, lane:'main'},
    {n:2, text:'Impact and severity assessment', tat:1.5, lane:'main'},
    {n:3, text:'Customer-visibility determination', tat:1.5, lane:'par'},
    {n:4, text:'Workaround definition and validation', tat:1.5, lane:'main'},
    {n:5, text:'Fix-versus-document decision input', tat:1, lane:'par'},
    {n:6, text:'Errata documentation and release', tat:3, lane:'main'},
  ],
  flowNote:'Step 4\'s validation is the part that gets skipped. A workaround that has been described but never run is a hypothesis, and shipping it as a mitigation is how a known issue becomes a field failure anyway.',
  consumes:[
    'Root causes from BU-09',
    'Failure analysis results from BU-09',
    'Design impact assessment from RTL-09',
    'Customer use models from DEF-03',
    'Documentation standards from MP-12',
  ],
  produces:[
    'Errata intake and classification',
    'Impact and severity assessment',
    'Customer-visibility determination',
    'Validated workarounds',
    'Fix-versus-document input',
    'Released errata documentation',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'BU-D4', rel:'produces', text:'<b>Errata list with workarounds.</b> This activity is the deliverable, and it is what ships alongside the product.'},
    {id:'BU-D6', rel:'feeds', text:'<b>Respin versus metal-fix decision record.</b> Which errata are tolerable with a workaround is the decision\'s main input.'},
  ],
  risks:[
    '<b>Workarounds documented but never validated.</b> The mitigation then fails in the field and the errata gave false comfort.',
    '<b>Severity assessed by engineering alone.</b> Customer impact depends on use models, and the assessment needs that perspective.',
    '<b>Errata suppressed for commercial reasons.</b> Undisclosed known issues discovered by a customer damage far more than the disclosure would have.',
    '<b>Errata list not versioned against silicon revision.</b> Which errata apply to which stepping becomes ambiguous the moment a second stepping exists.',
    '<b>Documentation deferred to the end.</b> The context is freshest at root cause, and reconstructing it months later loses detail.',
  ],
  roles:[
    {r:'Product engineering', d:'Owns the errata list'},
    {r:'Design engineer', d:'Mechanism and workaround definition'},
    {r:'Validation engineer', d:'Workaround validation on silicon'},
    {r:'Product marketing', d:'Customer impact and disclosure'},
    {r:'Technical writer', d:'Errata documentation'},
  ],
  effort:[['Workaround definition and validation',3], ['Errata documentation',2.5], ['Impact assessment',2], ['Visibility determination',1.5], ['Fix decision input',1]],
  entry:[
    'Root causes available from BU-09',
    'Customer use models from DEF-03',
    'Documentation standard from MP-12',
  ],
  exit:[
    'Every workaround validated on silicon, not only described',
    'Severity assessed with customer use models in view',
    'Errata versioned against silicon revision',
  ],
  dependsOn:['BU-04','BU-05','BU-06','BU-09'],
  dependsNote:null,
  feedsInto:['BU-11','BU-12','MP-12'],
  measuredBy:[
    'Workarounds validated against documented',
    'Errata found by customers after release',
    'Time from root cause to documented errata',
  ],
},

'BU-11': {
  stage:'bringup', window:[13,17], criticalPath:true,
  purpose:[
    'Decide whether the silicon needs a <b>respin, a metal fix, or nothing</b>—the single most consequential decision the program makes after tapeout.',
    'A full-mask respin costs a mask set and roughly a quarter of schedule. A metal fix costs far less but can only reach defects in the routing layers. Shipping as-is with workarounds costs nothing now and possibly a great deal later. The decision has to weigh all three against evidence rather than optimism.',
  ],
  steps:[
    {n:1, text:'Defect list and fix scoping', tat:0.75, lane:'main'},
    {n:2, text:'Metal-fix feasibility assessment', tat:1, lane:'main'},
    {n:3, text:'Full-mask respin scoping', tat:0.75, lane:'par'},
    {n:4, text:'Cost, schedule and risk comparison', tat:1.25, lane:'main'},
    {n:5, text:'Customer and market impact input', tat:0.75, lane:'par'},
    {n:6, text:'Decision and its record', tat:1, lane:'main'},
  ],
  flowNote:'Step 2 is bounded by physics rather than by will. A metal fix can only change routing layers, and whether the required change fits inside them is a question with a factual answer that has to be established before the decision is framed.',
  consumes:[
    'Errata list and severity from BU-10',
    'Root causes from BU-09',
    'Margin data from BU-07',
    'Performance gaps from BU-08',
    'Mask and fab cost from TECH-08',
  ],
  produces:[
    'Defect list and fix scope',
    'Metal-fix feasibility assessment',
    'Full-mask respin scope',
    'Cost, schedule and risk comparison',
    'Customer and market impact assessment',
    'Recorded decision with its rationale',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'BU-D6', rel:'produces', text:'<b>Respin versus metal-fix decision record.</b> This activity is the deliverable, and the record is what the program is held to.'},
    {id:'BU-D4', rel:'feeds', text:'<b>Errata list with workarounds.</b> Errata not fixed by the decision become permanent, documented behavior.'},
  ],
  risks:[
    '<b>Decision made on schedule pressure alone.</b> Shipping a part with a real defect to protect a date routinely costs more than the delay would have.',
    '<b>Metal-fix feasibility assumed.</b> It is a physical question about which layers the fix touches, and it is often answered optimistically.',
    '<b>Margin data not weighed.</b> A part with adequate function and no margin fails in the field, and the shmoo already said so.',
    '<b>Decision unrecorded.</b> Six months later nobody can reconstruct what was known and what was accepted.',
    '<b>Customer input excluded.</b> Whether an errata is tolerable depends on what customers do with the part.',
  ],
  roles:[
    {r:'Program manager', d:'Owns the decision and its record'},
    {r:'Design lead', d:'Fix scope and metal-fix feasibility'},
    {r:'Product engineering', d:'Errata severity and margin evidence'},
    {r:'Product marketing', d:'Customer and market impact'},
    {r:'Executive sponsor', d:'Cost and schedule authority'},
  ],
  effort:[['Cost, schedule and risk comparison',1.5], ['Metal-fix feasibility',1.25], ['Respin scoping',1], ['Decision record',0.75], ['Market impact input',0.5]],
  entry:[
    'Errata list and severities available from BU-10',
    'Margin and performance data from BU-07 and BU-08',
    'Mask and fab costs available',
  ],
  exit:[
    'Metal-fix feasibility established physically, not assumed',
    'Margin evidence weighed alongside functional defects',
    'Decision recorded with what was known at the time',
  ],
  dependsOn:['BU-07','BU-08','BU-09','BU-10','TECH-08'],
  dependsNote:null,
  feedsInto:['BU-12','MP-09','MP-10'],
  measuredBy:[
    'Decision made against the planned date',
    'Feasibility claims that held',
    'Defects found later that the decision did not consider',
  ],
},

'BU-12': {
  stage:'bringup', window:[13,18], criticalPath:false,
  purpose:[
    'Get <b>samples to customers</b> with everything they need to use them—screened units, documentation, errata, and a channel to report back.',
    'Customer samples start the evaluation cycle that decides design wins, and they start it months before mass production. What ships with the unit determines whether the customer\'s first week is productive or spent rediscovering issues the program already knows about.',
  ],
  steps:[
    {n:1, text:'Sample readiness criteria', tat:0.75, lane:'main'},
    {n:2, text:'Unit selection and screening for samples', tat:1.25, lane:'main'},
    {n:3, text:'Customer documentation and errata pack', tat:1, lane:'par'},
    {n:4, text:'Release package assembly', tat:1.5, lane:'main'},
    {n:5, text:'Feedback channel establishment', tat:1, lane:'par'},
    {n:6, text:'Sample shipment and support setup', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 5 is the one that pays back most. A customer who finds something and has an obvious route to report it gives the program early field data; one who does not gives it a design loss with no explanation.',
  consumes:[
    'Allocated sample units from ASSY-09',
    'Errata list from BU-10',
    'Decision record from BU-11',
    'Preliminary datasheet from MP-12',
    'Customer commitments from DEF-01',
  ],
  produces:[
    'Sample readiness criteria',
    'Screened and selected sample units',
    'Customer documentation and errata pack',
    'Assembled release package',
    'Feedback channel',
    'Shipped samples with support in place',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'BU-D7', rel:'produces', text:'<b>Customer sample release package.</b> This activity is the deliverable—units plus everything needed to use them.'},
    {id:'BU-D4', rel:'feeds', text:'<b>Errata list with workarounds.</b> The errata pack that ships with samples is the errata list\'s first external use.'},
  ],
  risks:[
    '<b>Samples shipped without errata.</b> The customer spends their first week rediscovering known issues and loses confidence in the part.',
    '<b>Units not screened before shipping.</b> A marginal sample creates a customer-visible failure that the program cannot investigate remotely.',
    '<b>Documentation lagging the silicon.</b> A datasheet describing behavior the sample does not have generates support load and doubt.',
    '<b>No feedback channel.</b> Customer findings then arrive as rumor or not at all, and the program loses its earliest field data.',
    '<b>Samples shipped before the respin decision.</b> If a respin follows, customers are evaluating a stepping that will not ship.',
  ],
  roles:[
    {r:'Product marketing', d:'Owns customer sample release'},
    {r:'Product engineering', d:'Unit screening and readiness criteria'},
    {r:'Applications engineer', d:'Customer support and feedback channel'},
    {r:'Technical writer', d:'Documentation and errata pack'},
    {r:'Program manager', d:'Timing against the respin decision'},
  ],
  effort:[['Release package assembly',1.75], ['Unit selection and screening',1.25], ['Documentation pack',1.25], ['Shipment and support',1], ['Feedback channel',0.75]],
  entry:[
    'Sample units allocated from ASSY-09',
    'Errata list released from BU-10',
    'Respin decision recorded in BU-11',
  ],
  exit:[
    'Errata pack shipping with every sample',
    'Units screened before shipment',
    'Feedback channel established and staffed',
  ],
  dependsOn:['ASSY-09','BU-10','BU-11'],
  dependsNote:null,
  feedsInto:['MP-10','MP-12'],
  measuredBy:[
    'Samples shipped against commitment',
    'Customer issues that were already documented',
    'Feedback received through the channel',
  ],
},

};
