/* DFT — DFT Architecture. Eleven activities. Stage w18–58 (40w), 130 M/M. */
module.exports = {

'DFT-01': {
  stage:'dft', window:[0,8], criticalPath:true,
  purpose:[
    'Decide <b>how the chip will be tested</b> before it is built to be testable—scan style, compression ratio, hierarchical partitioning, and the test modes the design will support.',
    'Every one of these choices constrains the design rather than following it. Compression ratio decides pattern volume and therefore test cost; hierarchical DFT decides whether a block can be tested independently; and both have to be settled before <code>SYN-01</code> writes constraints against them.',
  ],
  steps:[
    {n:1, text:'Test strategy definition — what is tested where and how', tat:1.5, lane:'main'},
    {n:2, text:'Scan architecture and chain organization', tat:2, lane:'main'},
    {n:3, text:'Compression architecture and ratio selection', tat:1.5, lane:'main'},
    {n:4, text:'Hierarchical DFT partitioning against the design hierarchy', tat:1.5, lane:'par'},
    {n:5, text:'Test mode definition and mode control', tat:1.5, lane:'par'},
    {n:6, text:'Architecture specification and review', tat:3, lane:'main'},
  ],
  flowNote:'Step 3 is a cost decision disguised as an architecture one. Compression ratio sets pattern volume, pattern volume sets tester memory and test time, and test time is a per-unit cost for the life of the product.',
  consumes:[
    'Design hierarchy and partitioning from ARCH-02',
    'Coverage and test-time targets from DFT-02',
    'Memory list and BISR intent from ARCH-03',
    'Test platform constraints from TEST-02',
    'Debug access requirements from ARCH-07',
  ],
  produces:[
    'Test strategy statement',
    'Scan architecture and chain organization',
    'Compression architecture and ratio',
    'Hierarchical DFT partitioning',
    'Test mode definition',
    'DFT architecture specification',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'DFT-D1', rel:'produces', text:'<b>DFT architecture specification and coverage plan.</b> This activity is the deliverable, and everything else in the stage is executed against it.'},
    {id:'DFT-D7', rel:'gates', text:'<b>DFT signoff entry for the tapeout checklist.</b> An architecture that was never fixed cannot be signed off against.'},
  ],
  risks:[
    '<b>Architecture decided after synthesis starts.</b> Scan insertion and constraints depend on it; deciding late means re-running both.',
    '<b>Compression ratio chosen without the test cost model.</b> Ratio trades pattern volume against silicon area, and only <code>TEST-09</code>\'s cost model says which side to favor.',
    '<b>Hierarchical DFT ignored on a large die.</b> Flat scan on a design this size produces pattern volumes and runtimes that become their own schedule problem.',
    '<b>Test modes defined without the security architecture.</b> Every test mode is an access path, and <code>ARCH-07</code> has to lock the ones that should not exist in production.',
    '<b>Architecture written and not reviewed by test engineering.</b> A scheme that is elegant in design and unrunnable on the chosen ATE is discovered at <code>TEST-08</code>.',
  ],
  roles:[
    {r:'DFT architect', d:'Owns the architecture and its specification'},
    {r:'Test engineering liaison', d:'ATE feasibility and test-time implications'},
    {r:'Product engineering liaison', d:'Coverage and cost targets'},
    {r:'Security architect', d:'Test mode access and lockdown'},
    {r:'Physical design liaison', d:'Chain routing and compression feasibility'},
  ],
  effort:[['Scan and compression architecture',5], ['Architecture specification and review',3], ['Test strategy definition',2], ['Hierarchical partitioning',1], ['Test mode definition',1]],
  entry:[
    'Design hierarchy known from ARCH-02',
    'Coverage and test-time targets agreed in DFT-02',
    'Test platform direction available from TEST-02',
  ],
  exit:[
    'Architecture fixed before synthesis writes constraints against it',
    'Compression ratio chosen against a test cost model',
    'Specification reviewed by test and product engineering',
  ],
  dependsOn:['ARCH-02','ARCH-09','DFT-02'],
  dependsNote:null,
  feedsInto:['DFT-03','DFT-05','DFT-06','DFT-09','SYN-01','TEST-01'],
  measuredBy:[
    'Architecture decisions taken before synthesis starts',
    'Compression ratio against pattern volume budget',
    'Architecture changes after freeze',
  ],
},

'DFT-02': {
  stage:'dft', window:[2,7], criticalPath:false,
  purpose:[
    'Agree the <b>coverage and test-time targets</b> with the people who pay for them—product engineering, who own quality, and test engineering, who own the tester seconds.',
    'Coverage and test time pull against each other, and neither belongs to DFT alone. A defect-per-million target sets required coverage; a cost-per-unit target sets allowable test time; and the architecture in <code>DFT-01</code> is chosen to sit between them. Negotiating this first is what makes the architecture decidable.',
  ],
  steps:[
    {n:1, text:'Quality target translation — DPPM to required coverage', tat:1, lane:'main'},
    {n:2, text:'Test time budget from the product cost model', tat:1, lane:'main'},
    {n:3, text:'Fault model selection — stuck-at, transition, cell-aware', tat:1, lane:'par'},
    {n:4, text:'Coverage target per fault model and per block class', tat:1, lane:'par'},
    {n:5, text:'Target agreement and record', tat:3, lane:'main'},
  ],
  flowNote:'Step 3 has a large downstream cost. Cell-aware patterns catch defects the other models miss and multiply pattern count doing it, so the decision belongs here with the cost model in the room rather than at <code>DFT-07</code> when the patterns are being generated.',
  consumes:[
    'Quality and DPPM targets from the product requirements',
    'Test cost budget from DEF-04',
    'Defect density projection from TECH-07',
    'Test platform capability from TEST-02',
    'Previous-generation coverage and escape data',
  ],
  produces:[
    'Coverage target derived from the DPPM requirement',
    'Test time budget',
    'Fault model selection',
    'Per-block-class coverage targets',
    'Agreed target record',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'DFT-D1', rel:'feeds', text:'<b>DFT architecture specification and coverage plan.</b> The coverage plan half—the numbers <code>DFT-01</code>\'s architecture is chosen to reach.'},
    {id:'DFT-D4', rel:'feeds', text:'<b>ATPG pattern sets with coverage report.</b> The report is measured against the targets set here, not against what the tool happened to reach.'},
  ],
  risks:[
    '<b>Coverage target set by convention.</b> "99% stuck-at" carried from the last program may be far from what this product\'s DPPM requirement needs.',
    '<b>Test time budget not derived from cost.</b> A test time nobody costed becomes whatever the patterns need, and the per-unit cost is discovered at production.',
    '<b>Fault model chosen at pattern generation.</b> Adding cell-aware late multiplies pattern volume against a tester memory budget already fixed.',
    '<b>Targets agreed without product engineering.</b> The organization that owns field quality has to own the coverage number, or it will be renegotiated when patterns run long.',
    '<b>No per-block differentiation.</b> Memory-dominated blocks and control logic need different approaches, and a single flat target over-tests one and under-tests the other.',
  ],
  roles:[
    {r:'DFT architect', d:'Owns the target negotiation and record'},
    {r:'Product engineering', d:'DPPM and field quality requirements'},
    {r:'Test engineering', d:'Test time, tester memory and cost'},
    {r:'Yield engineer', d:'Defect density and fault model relevance'},
    {r:'Program manager', d:'Records the agreement and its cost implication'},
  ],
  effort:[['Quality target translation',1.5], ['Test time budget',1], ['Fault model selection',1], ['Target agreement',0.5]],
  entry:[
    'DPPM and quality requirements available',
    'Test cost budget from the DEF-04 model',
    'Defect density projection from TECH-07',
  ],
  exit:[
    'Coverage target derived from DPPM, not inherited',
    'Test time budget traced to a per-unit cost',
    'Targets signed by product and test engineering',
  ],
  dependsOn:['DEF-04','TECH-07'],
  dependsNote:null,
  feedsInto:['DFT-01','DFT-07','TEST-01','TEST-09'],
  measuredBy:[
    'Coverage target against DPPM requirement',
    'Test time budget against the cost model',
    'Targets renegotiated during pattern generation',
  ],
},

'DFT-03': {
  stage:'dft', window:[6,16], criticalPath:true,
  purpose:[
    'Architect <b>memory test and repair</b>—MBIST engines, BIRA analysis, BISR repair and the fuse path—for a design where memory is most of the die.',
    'On an accelerator the arrays dominate both area and defect exposure, and they cannot be tested by scan. MBIST is how they are tested and repair is how the yield is recovered; both have to be designed jointly with <code>AMS-09</code>, because the array provides the spares and this activity provides the engine that uses them.',
  ],
  steps:[
    {n:1, text:'Memory inventory and test requirement per instance', tat:1.5, lane:'main'},
    {n:2, text:'MBIST architecture and engine allocation', tat:2.5, lane:'main'},
    {n:3, text:'Algorithm selection per memory type', tat:1.5, lane:'par'},
    {n:4, text:'BIRA and repair analysis architecture', tat:2, lane:'main'},
    {n:5, text:'BISR and fuse path integration with ARCH-07', tat:2, lane:'par'},
    {n:6, text:'Repair interface agreement with the memory designers', tat:1.5, lane:'par'},
    {n:7, text:'MBIST insertion and integration', tat:2.5, lane:'main'},
    {n:8, text:'Architecture verification and specification', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 6 is the joint decision with <code>AMS-09</code>. Both sides can specify an internally consistent repair scheme that the other cannot implement, and writing the interface together is the only reliable way to avoid it.',
  consumes:[
    'Memory instances from PDK-04 and AMS-10',
    'Redundancy scheme from AMS-09',
    'Fuse map and lifecycle from ARCH-07',
    'Coverage targets from DFT-02',
    'Repair yield expectations from the yield model',
  ],
  produces:[
    'Memory inventory with test requirements',
    'MBIST architecture and engine allocation',
    'Algorithm selection per memory type',
    'BIRA and BISR architecture',
    'Fuse path integration',
    'Repair interface agreement with the memory designers',
    'MBIST insertion and verification results',
    'Verified MBIST architecture specification',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'DFT-D2', rel:'produces', text:'<b>MBIST / BISR insertion and test collateral.</b> This activity is the deliverable, including the repair collateral test engineering will run.'},
    {id:'DFT-D1', rel:'feeds', text:'<b>DFT architecture specification.</b> Memory test is a large part of the overall architecture, not a separate subject.'},
  ],
  risks:[
    '<b>Repair interface specified separately from the array.</b> Two consistent specifications that disagree, found at pattern generation when both are frozen.',
    '<b>Algorithms chosen without the failure modes.</b> March algorithms differ in what they catch; a default choice misses the defect modes this array actually exhibits.',
    '<b>Fuse capacity insufficient.</b> Repair data has to be stored, and an allocation made without counting the worst-case repair set produces unrepairable parts.',
    '<b>MBIST runtime unbudgeted.</b> Memory test on an array-dominated die can dominate test time, and it is often costed after the architecture is fixed.',
    '<b>Repair not verified end to end.</b> A repair path proven in pieces and never exercised from failure through analysis to fuse blow fails at production test.',
  ],
  roles:[
    {r:'DFT memory lead', d:'Owns MBIST, BIRA and BISR architecture'},
    {r:'Memory circuit designers', d:'Redundancy and repair interface'},
    {r:'Fuse and lifecycle engineer', d:'Fuse path and capacity'},
    {r:'Test engineering liaison', d:'MBIST runtime and repair flow at ATE'},
    {r:'Verification engineer', d:'Repair path end-to-end verification'},
  ],
  effort:[['MBIST architecture and insertion',5], ['BIRA and BISR architecture',3.5], ['Repair interface and fuse path',2.5], ['Algorithm selection',1.5], ['Architecture verification',1.5]],
  entry:[
    'Memory inventory available from PDK-04',
    'Redundancy scheme from AMS-09 in progress',
    'Fuse map and lifecycle model from ARCH-07',
  ],
  exit:[
    'Repair interface written jointly with the memory designers',
    'Repair path verified end to end, not in pieces',
    'MBIST runtime inside the test time budget',
  ],
  dependsOn:['DFT-01','PDK-04','AMS-09','ARCH-07'],
  dependsNote:null,
  feedsInto:['DFT-06','DFT-10','AMS-09','TEST-05','MP-05'],
  measuredBy:[
    'MBIST runtime against the test time budget',
    'Repair interface mismatches at pattern generation',
    'Repair yield recovered against projection',
  ],
},

'DFT-04': {
  stage:'dft', window:[4,12], criticalPath:false,
  purpose:[
    'Design the <b>access network</b>—boundary scan, IJTAG, TAP controller and the debug paths—that every test, every repair and every silicon debug session runs through.',
    'The TAP is the door into the chip. It is used at wafer sort, at package test, during bring-up and in the field, and it is also the door <code>ARCH-07</code> needs to lock in production. Designing it is a negotiation between access and security rather than a purely technical exercise.',
  ],
  steps:[
    {n:1, text:'Access architecture — TAP, IJTAG network topology', tat:1.5, lane:'main'},
    {n:2, text:'Boundary scan implementation per IEEE 1149.1', tat:1.5, lane:'main'},
    {n:3, text:'IJTAG instrument network and description files', tat:2, lane:'par'},
    {n:4, text:'Debug and trace access path definition', tat:1.5, lane:'par'},
    {n:5, text:'Security lockdown integration per lifecycle state', tat:1.5, lane:'main'},
    {n:6, text:'Access network verification and description file generation', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 5 is where the negotiation with <code>ARCH-07</code> lands. Every path this activity opens for debug is a path security has to close in production lifecycle states, and the lock has to be testable without making the part permanently undebuggable.',
  consumes:[
    'DFT architecture from DFT-01',
    'Security lockdown policy from ARCH-07',
    'Debug requirements from validation and BU-09',
    'Package pin availability from ARCH-08',
    'IJTAG tooling from PDK-08',
  ],
  produces:[
    'TAP and IJTAG network architecture',
    'Boundary scan implementation',
    'Instrument network with ICL and PDL descriptions',
    'BSDL and description files',
    'Debug and trace access paths',
    'Lifecycle-state lockdown integration',
    'Access network verification results and description files',
  ],
  producedBy:[1,2,3,3,4,5,6],
  rel:[
    {id:'DFT-D3', rel:'produces', text:'<b>JTAG / IJTAG description files (BSDL, ICL, PDL).</b> This activity is the deliverable, and these files are what board test and ATE consume.'},
    {id:'DFT-D1', rel:'feeds', text:'<b>DFT architecture specification.</b> The access network is how every other DFT feature is reached.'},
  ],
  risks:[
    '<b>Debug access designed out for security.</b> A part that cannot be debugged in the field is a part whose first field failure has no diagnostic path.',
    '<b>Lockdown untested.</b> The lifecycle transition that locks the TAP is the one nobody exercises, because exercising it makes the part undebuggable.',
    '<b>Description files generated late.</b> BSDL and ICL are consumed by board test and ATE; generating them near tapeout leaves no time to validate them.',
    '<b>Access network verified only in functional mode.</b> The network exists to work when the design does not, and that is the mode that needs proving.',
    '<b>Pin budget for debug not reserved.</b> Trace ports need pins, and a bump map fixed without them means debug through a narrow channel.',
  ],
  roles:[
    {r:'DFT access lead', d:'Owns the TAP, the network and the description files'},
    {r:'Security architect', d:'Lockdown policy per lifecycle state'},
    {r:'Validation liaison', d:'Debug and trace requirements for bring-up'},
    {r:'Verification engineer', d:'Access network verification'},
    {r:'Physical design liaison', d:'Pin and routing budget for the network'},
  ],
  effort:[['Access network verification and files',3], ['TAP and IJTAG architecture',2.5], ['Boundary scan implementation',1.5], ['Debug and trace paths',1.5], ['Security lockdown integration',1.5]],
  entry:[
    'DFT architecture available from DFT-01',
    'Security lockdown policy defined by ARCH-07',
    'Pin and bump budget known from ARCH-08',
  ],
  exit:[
    'Lockdown transitions tested, not only implemented',
    'Description files generated and validated before tapeout',
    'Debug access preserved for the lifecycle states that need it',
  ],
  dependsOn:['DFT-01','ARCH-07','ARCH-08'],
  dependsNote:null,
  feedsInto:['DFT-08','DFT-10','DFT-11','TEST-08','BU-03'],
  measuredBy:[
    'Lifecycle lockdown transitions tested',
    'Description files validated before tapeout',
    'Debug access available in the states validation needs',
  ],
},

'DFT-05': {
  stage:'dft', window:[8,15], criticalPath:false,
  purpose:[
    'Design the <b>on-chip clock controllers</b> that generate at-speed test clocks—because transition-fault testing needs clock pulses the tester cannot supply at frequency.',
    'Stuck-at testing runs slowly and catches static defects. The defects that matter for a high-frequency part are timing-related, and catching them needs launch-capture pulses at functional speed. The tester cannot produce them, so the chip has to produce them for itself.',
  ],
  steps:[
    {n:1, text:'At-speed test requirement per clock domain', tat:1, lane:'main'},
    {n:2, text:'OCC architecture and PLL interface', tat:1.5, lane:'main'},
    {n:3, text:'Launch-capture sequencing and pulse control', tat:1.5, lane:'main'},
    {n:4, text:'Multi-domain and cross-domain at-speed strategy', tat:1.5, lane:'par'},
    {n:5, text:'OCC insertion and integration', tat:1.5, lane:'par'},
    {n:6, text:'At-speed clocking verification', tat:3, lane:'main'},
  ],
  flowNote:'Step 4 is the difficult part. Single-domain at-speed test is well understood; testing paths that cross domains at speed requires the domains to have a defined phase relationship in test mode, which is a constraint on the clocking architecture rather than on DFT.',
  consumes:[
    'Clock architecture and domains from ARCH-05',
    'DFT architecture from DFT-01',
    'PLL interface from AMS-02',
    'Test platform clocking capability from TEST-02',
    'Transition fault coverage targets from DFT-02',
  ],
  produces:[
    'At-speed test requirements per domain',
    'OCC architecture and PLL interface',
    'Launch-capture sequencing control',
    'Cross-domain at-speed strategy',
    'Inserted and verified OCC logic',
    'At-speed clocking verification results',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'DFT-D1', rel:'feeds', text:'<b>DFT architecture specification.</b> At-speed clocking is what makes transition-fault coverage achievable, so it belongs in the architecture.'},
    {id:'DFT-D4', rel:'feeds', text:'<b>ATPG pattern sets with coverage report.</b> Transition patterns cannot be generated for domains the OCC cannot clock at speed.'},
  ],
  risks:[
    '<b>At-speed test not supported on every domain.</b> Coverage then has a hole exactly where the fastest logic is, which is where transition defects concentrate.',
    '<b>Cross-domain paths untested at speed.</b> These are among the most timing-marginal paths in the design and the hardest to cover.',
    '<b>OCC interaction with the PLL unverified.</b> A controller that cannot get a clean clock from the PLL in test mode produces patterns that fail on good silicon.',
    '<b>Power during at-speed test ignored.</b> Scan shift followed by at-speed capture creates switching activity far above functional, and the IR drop can cause failures on good parts.',
    '<b>OCC inserted late.</b> It sits in the clock path, so adding it after clock tree synthesis means redoing the tree.',
  ],
  roles:[
    {r:'DFT engineer, at-speed', d:'Owns OCC architecture and insertion'},
    {r:'Clocking architect', d:'Domain phase relationships in test mode'},
    {r:'PLL designer', d:'PLL behavior and interface in test mode'},
    {r:'Test engineering liaison', d:'Tester clocking capability and limits'},
    {r:'Physical design liaison', d:'Clock tree impact of OCC insertion'},
  ],
  effort:[['At-speed clocking verification',2.5], ['OCC architecture and interface',2], ['Launch-capture sequencing',1.5], ['Cross-domain strategy',1], ['Insertion and integration',1]],
  entry:[
    'Clock architecture and domains fixed by ARCH-05',
    'DFT architecture available from DFT-01',
    'PLL test-mode behavior known from AMS-02',
  ],
  exit:[
    'At-speed clocking available on every domain that needs coverage',
    'Cross-domain at-speed strategy defined and verified',
    'OCC inserted before clock tree synthesis, not after',
  ],
  dependsOn:['DFT-01','ARCH-05','AMS-02'],
  dependsNote:null,
  feedsInto:['DFT-06','DFT-07','SYN-02','PD-05'],
  measuredBy:[
    'Domains with at-speed capability against domains needing it',
    'Cross-domain paths covered at speed',
    'Test-mode IR drop against the functional case',
  ],
},

'DFT-06': {
  stage:'dft', window:[14,24], criticalPath:true,
  purpose:[
    'Insert the <b>scan chains, compression and test logic</b> into the design during synthesis, and drive DFT design-rule checking to clean.',
    'This is where the architecture becomes logic. DFT DRC violations—uncontrollable clocks, unresettable flops, blocked scan paths—reduce coverage silently, and each one is a set of faults ATPG will never be able to target.',
  ],
  steps:[
    {n:1, text:'Scan insertion setup and configuration', tat:1.5, lane:'main'},
    {n:2, text:'Scan chain insertion and stitching', tat:2, lane:'main'},
    {n:3, text:'Compression logic insertion', tat:1.5, lane:'par'},
    {n:4, text:'Test point insertion for coverage improvement', tat:1.5, lane:'par'},
    {n:5, text:'DFT DRC analysis and violation closure', tat:3, lane:'main'},
    {n:6, text:'Scan chain integrity verification', tat:1.5, lane:'par'},
    {n:7, text:'Insertion signoff and netlist handoff', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 5 is the substance. Every DFT DRC violation is a region of logic ATPG cannot control or observe, and the coverage loss is silent—the tool simply reports a lower number without saying which violation caused it.',
  consumes:[
    'DFT architecture from DFT-01',
    'MBIST insertion from DFT-03',
    'OCC logic from DFT-05',
    'Synthesis flow from SYN-01',
    'Netlist from SYN-02',
  ],
  produces:[
    'Scan insertion configuration',
    'Stitched scan chains',
    'Inserted compression logic',
    'Test points for coverage improvement',
    'DFT DRC clean results',
    'Scan chain integrity verification results',
    'Scan-inserted netlist',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'DFT-D5', rel:'produces', text:'<b>DFT DRC clean report.</b> This activity is the deliverable, and clean means every violation fixed or explicitly accepted with its coverage cost.'},
    {id:'DFT-D4', rel:'feeds', text:'<b>ATPG pattern sets with coverage report.</b> Coverage achievable at <code>DFT-07</code> is bounded by how clean this activity got.'},
  ],
  risks:[
    '<b>DRC violations accepted without measuring their coverage cost.</b> Each one silently removes faults from the targetable set, and the total is invisible until ATPG reports a low number.',
    '<b>Test points inserted without area budget.</b> They improve coverage and cost area and timing, and adding them late competes with closure.',
    '<b>Chain balance ignored.</b> Unbalanced chains set shift time by the longest one, and shift time is most of the test time.',
    '<b>Insertion done once and not re-run.</b> Netlist changes after insertion leave chains stale, and the mismatch appears at pattern validation.',
    '<b>Chain integrity unverified.</b> A broken chain makes everything behind it untestable, and finding that at ATE rather than in simulation costs a silicon turn.',
  ],
  roles:[
    {r:'DFT implementation engineer', d:'Owns insertion and DRC closure'},
    {r:'Synthesis engineer', d:'Flow integration and netlist handoff'},
    {r:'Block designers', d:'Fix DRC violations in their logic'},
    {r:'Physical design liaison', d:'Chain ordering and routing feasibility'},
    {r:'DFT architect', d:'Accepts violations with their coverage cost'},
  ],
  effort:[['DFT DRC closure',5], ['Scan insertion and stitching',3.5], ['Signoff and handoff',2.5], ['Compression insertion',1.5], ['Test point insertion',1], ['Chain integrity verification',0.5]],
  entry:[
    'DFT architecture fixed by DFT-01',
    'MBIST and OCC logic available',
    'Synthesis flow running from SYN-01',
  ],
  exit:[
    'Every DRC violation fixed or accepted with a measured coverage cost',
    'Chains balanced against the shift time budget',
    'Chain integrity verified in simulation before ATPG',
  ],
  dependsOn:['DFT-01','DFT-03','DFT-05','SYN-01','PDK-09'],
  dependsNote:null,
  feedsInto:['DFT-07','DFT-09','SYN-05','DV-11','PD-12'],
  measuredBy:[
    'DRC violations closed against accepted',
    'Coverage cost of accepted violations',
    'Chain length imbalance against budget',
  ],
},

'DFT-07': {
  stage:'dft', window:[22,38], criticalPath:true,
  purpose:[
    'Generate the <b>ATPG patterns</b>—stuck-at, transition and cell-aware—and drive coverage to the targets <code>DFT-02</code> agreed, inside the pattern volume the tester can hold.',
    'Two constraints pull against each other here: coverage has to reach the quality target and pattern volume has to fit tester memory and test time. Every technique that raises one raises the other, and closing both is the work.',
  ],
  steps:[
    {n:1, text:'ATPG setup, constraints and test mode configuration', tat:2, lane:'main'},
    {n:2, text:'Stuck-at pattern generation and coverage analysis', tat:3, lane:'main'},
    {n:3, text:'Transition and at-speed pattern generation', tat:3.5, lane:'main'},
    {n:4, text:'Cell-aware pattern generation', tat:2.5, lane:'par'},
    {n:5, text:'Untestable fault analysis and coverage justification', tat:2.5, lane:'par'},
    {n:6, text:'Pattern volume reduction and compaction', tat:3, lane:'main'},
    {n:7, text:'Coverage closure against the DFT-02 targets', tat:2, lane:'par'},
    {n:8, text:'Pattern set assembly and release', tat:4.5, lane:'main'},
  ],
  flowNote:'Step 5 is what makes a coverage number honest. Faults reported as untestable are either genuinely untestable—tied off, redundant—or untestable because of a DRC violation, and only analysis distinguishes a real limit from a fixable one.',
  consumes:[
    'Scan-inserted netlist from DFT-06',
    'Coverage targets and fault models from DFT-02',
    'Test time and memory budget from TEST-09',
    'Library fault models from PDK-03',
    'OCC and at-speed setup from DFT-05',
  ],
  produces:[
    'ATPG setup and constraints',
    'Stuck-at pattern set with coverage analysis',
    'Transition and at-speed pattern set',
    'Stuck-at, transition and cell-aware pattern sets',
    'Untestable fault analysis',
    'Compacted pattern volumes',
    'Coverage report against targets',
    'Released pattern sets',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'DFT-D4', rel:'produces', text:'<b>ATPG pattern sets with coverage report.</b> This activity is the deliverable, and the coverage report is what the quality target is measured against.'},
    {id:'DFT-D7', rel:'feeds', text:'<b>DFT signoff entry for the tapeout checklist.</b> Coverage against target is one of the checklist\'s quantitative entries.'},
  ],
  risks:[
    '<b>Coverage target missed and accepted late.</b> The remedies—test points, DRC fixes, architecture changes—all need an RTL or netlist change, and none are available near tapeout.',
    '<b>Pattern volume exceeding tester memory.</b> Patterns that do not fit have to be split across loads, which multiplies test time and cost.',
    '<b>Untestable faults accepted without analysis.</b> A fixable DRC violation reported as an untestable fault is coverage given away.',
    '<b>Cell-aware added late.</b> It multiplies pattern count against a budget already set, forcing a choice between coverage and test time with no room to negotiate.',
    '<b>Patterns generated on a netlist that then changes.</b> Any netlist change after generation invalidates the set, and regeneration takes weeks.',
  ],
  roles:[
    {r:'ATPG engineer', d:'Owns pattern generation and coverage closure'},
    {r:'DFT architect', d:'Untestable fault analysis and coverage decisions'},
    {r:'Test engineering liaison', d:'Pattern volume, memory and test time'},
    {r:'Block designers', d:'Fix DRC violations blocking coverage'},
    {r:'Product engineering', d:'Accepts final coverage against the quality target'},
  ],
  effort:[['Pattern generation',10], ['Pattern volume reduction',6], ['Untestable fault analysis',4.5], ['Pattern set assembly and release',4], ['Coverage closure',3.5]],
  entry:[
    'Scan-inserted netlist available and DRC clean from DFT-06',
    'Coverage targets set by DFT-02',
    'Tester memory and test time budget known from TEST-09',
  ],
  exit:[
    'Coverage meets the DFT-02 targets per fault model',
    'Pattern volume inside tester memory without splitting',
    'Untestable faults analyzed rather than accepted',
  ],
  dependsOn:['DFT-02','DFT-05','DFT-06','TEST-09'],
  dependsNote:null,
  feedsInto:['DFT-08','TEST-08','TO-03','MP-06'],
  measuredBy:[
    'Coverage achieved against target per fault model',
    'Pattern volume against tester memory',
    'Untestable faults analyzed against accepted',
  ],
},

'DFT-08': {
  stage:'dft', window:[28,38], criticalPath:true,
  purpose:[
    'Prove the patterns <b>actually run</b>—simulate them against the netlist with timing, convert them to tester format, and hand ATE a set that works.',
    'A pattern set that passes in ATPG and fails in gate-level simulation is a pattern set that would have failed on silicon. This activity is the last place a pattern problem is cheap, and it is also where the format conversion for the tester is proved rather than assumed.',
  ],
  steps:[
    {n:1, text:'Pattern simulation environment setup', tat:1.5, lane:'main'},
    {n:2, text:'Zero-delay pattern validation by gate-level simulation', tat:2, lane:'main'},
    {n:3, text:'Timing-annotated pattern simulation', tat:2, lane:'par'},
    {n:4, text:'Pattern failure debug and regeneration', tat:2.5, lane:'main'},
    {n:5, text:'STIL and WGL format conversion', tat:1.5, lane:'par'},
    {n:6, text:'Tester format and timing set validation', tat:1.5, lane:'par'},
    {n:7, text:'Pattern release and DFT tapeout signoff', tat:4, lane:'main'},
  ],
  flowNote:'Step 3 catches what zero-delay cannot: patterns that violate timing at the capture edge. On an at-speed pattern set this is not a formality—a launch-capture sequence that closes in ATPG and fails in timing simulation would have produced yield loss on good die.',
  consumes:[
    'Pattern sets from DFT-07',
    'Gate-level netlist and SDF from PD-09',
    'Simulation environment from DV-11',
    'Tester format requirements from TEST-08',
    'Timing sets and tester capability from TEST-02',
  ],
  produces:[
    'Pattern simulation environment',
    'Zero-delay and timing-annotated validation results',
    'Timing-annotated pattern simulation results',
    'Regenerated patterns for failures',
    'STIL and WGL format files',
    'Tester format validation results',
    'Released ATE-ready pattern set',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'DFT-D6', rel:'produces', text:'<b>Pattern validation (GLS) report and ATE-ready pattern files.</b> This activity is the deliverable—patterns proved to run rather than assumed to.'},
    {id:'DFT-D7', rel:'produces', text:'<b>DFT signoff entry for the tapeout checklist.</b> DFT signs the checklist on validated patterns, not on generated ones.'},
  ],
  risks:[
    '<b>Validation skipped for schedule.</b> A pattern failure then appears at ATE bring-up, where the diagnosis competes with everything else happening at first silicon.',
    '<b>Only zero-delay simulation run.</b> Timing-related pattern failures are exactly what at-speed patterns are meant to detect, and they are invisible without SDF.',
    '<b>Format conversion assumed.</b> STIL and WGL translation has tool-specific quirks, and a set that converts cleanly can still time incorrectly on the tester.',
    '<b>Regeneration cost underestimated.</b> A pattern failure requiring regeneration puts the whole set back through <code>DFT-07</code>, which takes weeks not days.',
    '<b>Timing sets not validated against the actual tester.</b> A pattern that assumes an edge placement the ATE cannot produce fails on hardware for a reason no simulation shows.',
  ],
  roles:[
    {r:'DFT validation engineer', d:'Owns pattern validation and release'},
    {r:'Gate-level simulation engineer', d:'Simulation environment and debug'},
    {r:'ATPG engineer', d:'Pattern regeneration where validation fails'},
    {r:'Test engineering', d:'Format conversion and tester timing sets'},
    {r:'DFT architect', d:'Signs the tapeout checklist entry'},
  ],
  effort:[['Pattern release and signoff',4], ['Failure debug and regeneration',3.5], ['Gate-level validation',2.5], ['Timing-annotated simulation',2], ['Format conversion and validation',2]],
  entry:[
    'Pattern sets released by DFT-07',
    'Netlist and SDF available from PD-09',
    'Simulation environment available from DV-11',
  ],
  exit:[
    'Patterns validated with timing, not only zero-delay',
    'Format conversion validated against the actual tester capability',
    'DFT tapeout checklist entry signed on validated patterns',
  ],
  dependsOn:['DFT-04','DFT-07','DV-11','PD-09'],
  dependsNote:null,
  feedsInto:['TO-03','TEST-08','MP-06','BU-02'],
  measuredBy:[
    'Patterns validated against patterns released',
    'Failures found in validation against at ATE bring-up',
    'Regeneration cycles required',
  ],
},

'DFT-09': {
  stage:'dft', window:[16,26], criticalPath:false,
  purpose:[
    'Work with physical design on whether the <b>scan chains and compression network can actually be routed</b>—and fix the plan before routing rather than after.',
    'Compression networks connect every chain to a shared decompressor and compactor, which produces long routes across the die competing with functional signals for the same resource. A compression ratio that is optimal on paper and unroutable in practice is discovered at <code>PD-06</code>, when the remedies are expensive.',
  ],
  steps:[
    {n:1, text:'Chain routing feasibility analysis with the floorplan', tat:1.5, lane:'main'},
    {n:2, text:'Compression network topology against physical partitioning', tat:2, lane:'main'},
    {n:3, text:'Chain ordering and reordering strategy', tat:1.5, lane:'par'},
    {n:4, text:'Congestion impact assessment', tat:1.5, lane:'par'},
    {n:5, text:'Test clock distribution feasibility', tat:1.5, lane:'par'},
    {n:6, text:'Physical DFT plan agreement with physical design', tat:6.5, lane:'main'},
  ],
  flowNote:'Step 3 is where the two disciplines usually collide. DFT wants chains ordered for balance and diagnosis; physical design wants them ordered for routing. Reordering after placement is the standard compromise, and agreeing it here avoids arguing about it during closure.',
  consumes:[
    'DFT architecture and compression from DFT-01',
    'Scan insertion from DFT-06',
    'Floorplan and partitioning from PD-01 and PD-02',
    'Routing resource from the metal stack in TECH-02',
    'Congestion analysis from PD-06',
  ],
  produces:[
    'Chain routing feasibility findings',
    'Compression topology aligned to physical partitions',
    'Chain ordering and reordering strategy',
    'Congestion impact assessment',
    'Test clock distribution plan',
    'Agreed physical DFT plan',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'DFT-D1', rel:'feeds', text:'<b>DFT architecture specification.</b> An architecture that cannot be routed is not an architecture, and this is where that is established.'},
    {id:'DFT-D5', rel:'feeds', text:'<b>DFT DRC clean report.</b> Physical feasibility findings often send work back into insertion, so the two are closed together.'},
  ],
  risks:[
    '<b>Compression ratio unroutable.</b> A ratio chosen for pattern volume alone produces a network that consumes routing resource the functional design needs.',
    '<b>Chain reordering breaking diagnosis.</b> Physical reordering improves routing and can destroy the chain-to-block mapping diagnosis depends on.',
    '<b>Test clock distribution treated as functional.</b> Scan shift clocks reach every flop and have their own skew and power requirements.',
    '<b>Feasibility assessed after routing starts.</b> The findings then arrive when the only remaining remedy is to reduce coverage.',
    '<b>Hierarchical partition boundaries ignored.</b> Chains crossing physical partitions carry a routing and timing cost that a logical view does not show.',
  ],
  roles:[
    {r:'DFT physical lead', d:'Owns the physical DFT plan'},
    {r:'Physical design engineers', d:'Routing feasibility and congestion'},
    {r:'DFT architect', d:'Trades compression ratio against routability'},
    {r:'Diagnosis engineer', d:'Chain-to-block mapping for failure analysis'},
    {r:'Clock architect', d:'Test clock distribution'},
  ],
  effort:[['Compression topology and feasibility',3.5], ['Physical DFT plan agreement',2.5], ['Chain ordering strategy',1.5], ['Congestion assessment',1.5], ['Test clock distribution',1]],
  entry:[
    'DFT architecture and compression defined by DFT-01',
    'Floorplan available from PD-01',
    'Scan insertion in progress in DFT-06',
  ],
  exit:[
    'Compression network confirmed routable at the chosen ratio',
    'Chain reordering strategy preserves diagnosis capability',
    'Physical DFT plan agreed before detailed routing starts',
  ],
  dependsOn:['DFT-01','DFT-06','PD-01'],
  dependsNote:null,
  feedsInto:['DFT-07','PD-06','PD-12'],
  measuredBy:[
    'Routing resource used by the compression network',
    'Chain reordering impact on diagnosis resolution',
    'Feasibility findings raised before routing starts',
  ],
},

'DFT-10': {
  stage:'dft', window:[12,18], criticalPath:false,
  purpose:[
    'Build the <b>fuse and identity infrastructure</b>—eFuse arrays, chip ID, repair storage, lifecycle state—that repair, traceability and security all depend on.',
    'Fuses are written once and read forever. They store memory repair, trim values, chip identity and lifecycle state, and every one of those consumers has its own requirements. Getting the capacity or the read path wrong produces parts that cannot be repaired, identified or secured.',
  ],
  steps:[
    {n:1, text:'Fuse consumer inventory — repair, trim, ID, lifecycle, security', tat:1, lane:'main'},
    {n:2, text:'Capacity allocation against worst-case need', tat:1, lane:'main'},
    {n:3, text:'eFuse array integration and programming path', tat:1.5, lane:'par'},
    {n:4, text:'Fuse read, shadow register and distribution design', tat:1.5, lane:'main'},
    {n:5, text:'Chip identity and traceability scheme', tat:1, lane:'par'},
    {n:6, text:'Lifecycle state encoding with ARCH-07', tat:1, lane:'par'},
    {n:7, text:'Fuse infrastructure verification', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 2 is the step that fails silently. Every consumer asks for a modest allocation, the total is set once, and the worst-case repair set—which is a distribution rather than an average—exceeds it on the parts that most needed repairing.',
  consumes:[
    'Repair storage requirement from DFT-03 and AMS-09',
    'Trim requirements from AMS-04',
    'Lifecycle and security states from ARCH-07',
    'Traceability requirements from MP-09',
    'eFuse capability from PDK-02',
  ],
  produces:[
    'Fuse consumer inventory',
    'Capacity allocation with worst-case margin',
    'eFuse array integration and programming path',
    'Fuse read and distribution logic',
    'Chip identity scheme',
    'Lifecycle state encoding agreed with the security architecture',
    'Verified fuse infrastructure',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'DFT-D2', rel:'feeds', text:'<b>MBIST / BISR insertion and test collateral.</b> Repair is only useful if the repair data can be stored and read back, which this activity provides.'},
    {id:'DFT-D3', rel:'feeds', text:'<b>JTAG / IJTAG description files.</b> Fuse programming and readback run through the access network, and the instrument descriptions cover them.'},
  ],
  risks:[
    '<b>Capacity sized to the average repair need.</b> Repair need is a distribution, and the parts needing most repair are exactly the ones the allocation fails.',
    '<b>Programming path untested.</b> Fuses are one-time; a programming path that does not work correctly produces parts that are permanently wrong.',
    '<b>Fuse read timing in the boot path unconsidered.</b> Repair and trim values have to be distributed before the logic that uses them is released from reset.',
    '<b>Traceability scheme designed late.</b> Chip identity is needed for yield analysis and field returns, and retrofitting it means parts that cannot be traced.',
    '<b>Lifecycle encoding without a test path.</b> A lifecycle transition that cannot be exercised in test is a transition whose correctness is unknown until the field.',
  ],
  roles:[
    {r:'Fuse and infrastructure engineer', d:'Owns the array, capacity and read path'},
    {r:'DFT memory lead', d:'Repair storage requirements'},
    {r:'Security architect', d:'Lifecycle state encoding and protection'},
    {r:'Product engineering', d:'Traceability and identity requirements'},
    {r:'Verification engineer', d:'Fuse infrastructure verification'},
  ],
  effort:[['Fuse infrastructure verification',2], ['Read and distribution design',1.5], ['Array integration and programming',1], ['Capacity allocation',0.75], ['Identity and lifecycle encoding',0.75]],
  entry:[
    'Repair storage requirements known from DFT-03',
    'Lifecycle states defined by ARCH-07',
    'eFuse capability confirmed by PDK-02',
  ],
  exit:[
    'Capacity sized against worst-case, not average, repair need',
    'Programming and read paths verified before tapeout',
    'Lifecycle transitions exercisable in test',
  ],
  dependsOn:['DFT-03','DFT-04','ARCH-07','PDK-02'],
  dependsNote:null,
  feedsInto:['TEST-05','MP-09','BU-02','MP-06'],
  measuredBy:[
    'Fuse capacity against worst-case repair need',
    'Programming path failures found pre-silicon',
    'Lifecycle transitions with a test path',
  ],
},

'DFT-11': {
  stage:'dft', window:[6,14], criticalPath:false,
  purpose:[
    'Design the <b>observability the lab will need</b>—trace, triggers, internal visibility, design-for-debug—because at bring-up the only view into the chip is the one designed in months earlier.',
    'Silicon debug is constrained entirely by what was built. A failure that cannot be observed cannot be diagnosed, and the difference between a two-day debug and a two-month one is usually whether someone put a trigger and a trace port where it was needed.',
  ],
  steps:[
    {n:1, text:'Debug requirement collection from validation and design', tat:1, lane:'main'},
    {n:2, text:'Observability architecture — trace, triggers, snapshot', tat:2, lane:'main'},
    {n:3, text:'Trace port and bandwidth budget', tat:1, lane:'par'},
    {n:4, text:'Trigger and cross-trigger network', tat:1.5, lane:'par'},
    {n:5, text:'Internal state snapshot and scan dump capability', tat:1.5, lane:'main'},
    {n:6, text:'Debug infrastructure verification and documentation', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 5 is the cheapest debug capability available. Scan chains already reach every flop; adding the ability to halt and dump their contents turns the test infrastructure into a full internal state view for almost no extra area.',
  consumes:[
    'Debug requirements from validation and BU-09',
    'Access network from DFT-04',
    'Scan infrastructure from DFT-06',
    'Pin and bump budget from ARCH-08',
    'Security lockdown policy from ARCH-07',
  ],
  produces:[
    'Debug requirement list',
    'Observability architecture',
    'Trace port and bandwidth budget',
    'Trigger and cross-trigger network',
    'Scan dump and snapshot capability',
    'Debug infrastructure documentation',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'DFT-D3', rel:'feeds', text:'<b>JTAG / IJTAG description files.</b> Debug instruments are part of the access network and are described alongside it.'},
    {id:'DFT-D1', rel:'feeds', text:'<b>DFT architecture specification.</b> Design-for-debug is part of the DFT architecture rather than a separate concern.'},
  ],
  risks:[
    '<b>Debug traded away for area.</b> The saving is small and the cost is paid at bring-up, in weeks, by a different team.',
    '<b>Requirements collected from design rather than validation.</b> The people who will debug the silicon know what they need to see; the people who built it usually assume it works.',
    '<b>Trace bandwidth inadequate.</b> A trace port too narrow to capture the event of interest produces a debug capability that cannot answer the question.',
    '<b>Debug infrastructure unverified.</b> It is used first when the chip is misbehaving, which is the worst moment to discover the debug path is broken.',
    '<b>No documentation.</b> A capability the lab does not know exists is a capability that was not built.',
  ],
  roles:[
    {r:'DFT debug lead', d:'Owns observability architecture and documentation'},
    {r:'Validation liaison', d:'States what the lab will need to see'},
    {r:'Design leads', d:'Identify internal state worth observing'},
    {r:'Security architect', d:'Debug access under lifecycle lockdown'},
    {r:'Verification engineer', d:'Debug infrastructure verification'},
  ],
  effort:[['Debug infrastructure verification and documentation',3.5], ['Observability architecture',2.5], ['Trigger network',1.5], ['Snapshot and scan dump',1.5], ['Trace port budget',1]],
  entry:[
    'Debug requirements collected from validation',
    'Access network architecture from DFT-04',
    'Pin budget known from ARCH-08',
  ],
  exit:[
    'Debug paths verified before tapeout, not first used at bring-up',
    'Trace bandwidth sufficient for the events validation named',
    'Capabilities documented for the people who will use them',
  ],
  dependsOn:['DFT-01','DFT-04','ARCH-07','ARCH-08'],
  dependsNote:null,
  feedsInto:['BU-09','BU-05','TEST-10','MP-05'],
  measuredBy:[
    'Debug requirements met against those collected',
    'Debug paths verified pre-silicon',
    'Bring-up issues diagnosed with built-in observability',
  ],
},

};
