/* DV — Verification. Twelve activities. Stage w26–66 (40w), 650 M/M — the largest stage. */
module.exports = {

'DV-01': {
  stage:'verification', window:[0,8], criticalPath:true,
  purpose:[
    'Write the plan that says <b>what will be verified, how, and how anyone will know it is done</b>—feature by feature, with a coverage model behind each claim.',
    'Verification is the largest line of effort in the program, and without a plan it is 650 man-months of activity with no definition of completion. The coverage model is what turns "we tested it" into a measurable statement, and the features nobody writes into the plan are the features nobody verifies.',
  ],
  steps:[
    {n:1, text:'Feature extraction from the architecture and block specifications', tat:1.5, lane:'main'},
    {n:2, text:'Verification strategy per feature — simulation, formal, emulation', tat:1.5, lane:'main'},
    {n:3, text:'Coverage model definition — functional, code, assertion', tat:2, lane:'main'},
    {n:4, text:'Closure criteria and signoff definition per block', tat:1, lane:'par'},
    {n:5, text:'Resource, compute and schedule modeling', tat:1, lane:'par'},
    {n:6, text:'Verification plan review with design and architecture', tat:3, lane:'main'},
  ],
  flowNote:'Step 6 is a review by the people who wrote the specification, and its purpose is to find features the plan missed. Verification reviewing its own plan confirms it is coherent; architecture reviewing it confirms it is complete, and incompleteness is the failure mode that matters.',
  consumes:[
    'Architecture specification from ARCH-09',
    'Block specifications from RTL-01',
    'Register map from RTL-07',
    'IP verification collateral requirements from IPR-06',
    'Compute capacity model from PDK-12',
  ],
  produces:[
    'Feature list extracted from the specifications',
    'Verification strategy per feature',
    'Coverage model — functional, code and assertion',
    'Closure criteria per block and at chip level',
    'Resource and schedule model',
    'Reviewed verification plan',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'DV-D1', rel:'produces', text:'<b>Verification plan (vPlan) and coverage model.</b> This activity is the deliverable, and the coverage model is what every later closure claim is measured against.'},
    {id:'DV-D8', rel:'gates', text:'<b>DV closure signoff package.</b> Closure is defined here; a signoff against criteria written later is a signoff against a moving target.'},
  ],
  risks:[
    '<b>Plan written from the RTL rather than the specification.</b> It then verifies what was built rather than what was specified, and the two differ exactly where the bugs are.',
    '<b>Coverage model that measures activity rather than intent.</b> Code coverage says lines were executed; functional coverage says features were exercised, and only the second answers the question.',
    '<b>Closure criteria left vague.</b> "High coverage" is not a criterion anyone can sign, and it becomes whatever the schedule allows.',
    '<b>Architecture not in the review.</b> The features the plan missed are exactly the ones only the specification\'s author would notice.',
    '<b>Resource model omitted.</b> A plan that needs more compute or more engineers than exist is a plan whose closure date is fiction.',
  ],
  roles:[
    {r:'Verification lead', d:'Owns the plan, the coverage model and the criteria'},
    {r:'Block verification owners', d:'Per-block strategy and closure criteria'},
    {r:'Chief architect', d:'Confirms feature completeness against the specification'},
    {r:'RTL lead', d:'Confirms the plan is verifiable as the design is built'},
    {r:'Program manager', d:'Resource and schedule feasibility'},
  ],
  effort:[['Coverage model definition',8], ['Feature extraction',5], ['Strategy per feature',5], ['Plan review',4], ['Closure criteria',2], ['Resource modeling',1]],
  entry:[
    'Architecture specification frozen by ARCH-09',
    'Block specifications available from RTL-01',
    'Compute capacity model available from PDK-12',
  ],
  exit:[
    'Every specified feature has a verification strategy and a coverage point',
    'Closure criteria written and agreed before verification starts',
    'Plan reviewed by architecture and design, not only by verification',
  ],
  dependsOn:['ARCH-09','RTL-01','RTL-07'],
  dependsNote:null,
  feedsInto:['DV-02','DV-03','DV-05','DV-10','IPR-06'],
  measuredBy:[
    'Features with a coverage point against features specified',
    'Closure criteria signed before verification starts',
    'Features added to the plan after it was reviewed',
  ],
},

'DV-02': {
  stage:'verification', window:[4,18], criticalPath:true,
  purpose:[
    'Build the <b>verification environment</b>—UVM agents, scoreboards, sequences, VIP integration—that every test in the program will run inside.',
    'The environment is infrastructure with a long lead time and no visible output until it works. Sixty man-months buys agents for every interface, scoreboards that actually check, and reusable sequences. Testbench bring-up running late is the single most common reason verification starts late, and it starts late invisibly.',
  ],
  steps:[
    {n:1, text:'Environment architecture and reuse strategy', tat:1.5, lane:'main'},
    {n:2, text:'Agent development per interface', tat:4, lane:'main'},
    {n:3, text:'Third-party VIP integration and configuration', tat:3, lane:'par'},
    {n:4, text:'Scoreboard and reference model development', tat:4, lane:'main'},
    {n:5, text:'Sequence library and stimulus infrastructure', tat:3, lane:'par'},
    {n:6, text:'Register model integration from the RDL source', tat:2, lane:'par'},
    {n:7, text:'Environment bring-up on the first block', tat:2.5, lane:'main'},
    {n:8, text:'Environment release and documentation', tat:2, lane:'main'},
  ],
  flowNote:'Step 4 is where verification quality is decided. A scoreboard that compares against a reference model finds bugs; one that only checks protocol legality confirms the design does something rather than the right thing.',
  consumes:[
    'Verification plan from DV-01',
    'Block and interface specifications from RTL-01',
    'Register description source from RTL-07',
    'VIP licences from IPR-07',
    'Methodology standards and reuse libraries',
  ],
  produces:[
    'Environment architecture and reuse strategy',
    'UVM agents per interface',
    'Integrated third-party VIP',
    'Scoreboards and reference models',
    'Sequence library',
    'Register model integration',
    'Environment bring-up results on the first block',
    'Released environment with documentation',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'DV-D2', rel:'produces', text:'<b>UVM testbenches and integrated VIP.</b> This activity is the deliverable—the environment every subsequent verification activity runs inside.'},
    {id:'DV-D1', rel:'feeds', text:'<b>Verification plan and coverage model.</b> Coverage is collected by the environment, so what it can measure bounds what the plan can claim.'},
  ],
  risks:[
    '<b>Bring-up slower than planned and invisible.</b> Environment work has no test-pass metric, so slippage is not visible until testing should have started.',
    '<b>Scoreboards that check protocol rather than function.</b> A legal transaction carrying wrong data passes, and the bug survives to chip level.',
    '<b>No reuse strategy.</b> Every block building its own environment multiplies effort and makes results incomparable across blocks.',
    '<b>Register model hand-written.</b> A model that diverges from the RDL source produces tests that pass against the wrong offsets.',
    '<b>VIP licences short.</b> Verification concurrency is capped by VIP seats, and the cap is discovered when regressions start queuing.',
  ],
  roles:[
    {r:'Verification architect', d:'Owns the environment architecture and reuse'},
    {r:'Agent and VIP engineers', d:'Interface agents and VIP integration'},
    {r:'Reference model engineers', d:'Scoreboards and functional models'},
    {r:'Methodology engineer', d:'Standards, reuse libraries and documentation'},
    {r:'Register map owner', d:'RDL-generated register model'},
  ],
  effort:[['Agent development',16], ['Scoreboard and reference models',16], ['VIP integration',10], ['Sequence library',8], ['Environment bring-up',5], ['Register model and documentation',5]],
  entry:[
    'Verification plan available from DV-01',
    'Interface specifications stable enough to build agents against',
    'VIP licences executed in IPR-07',
  ],
  exit:[
    'Environment running on a real block, not on a stub',
    'Scoreboards checking against reference models',
    'Environment documented and reused rather than rebuilt per block',
  ],
  dependsOn:['DV-01','RTL-01','RTL-07','IPR-07'],
  dependsNote:null,
  feedsInto:['DV-03','DV-04','DV-06','DV-07','DV-10'],
  measuredBy:[
    'Blocks running in the shared environment against total',
    'Bugs found by scoreboards against by manual inspection',
    'Environment bring-up against plan',
  ],
},

'DV-03': {
  stage:'verification', window:[8,38], criticalPath:true,
  purpose:[
    'Verify every block against its specification with <b>constrained-random and directed testing</b>, and drive each one to its coverage closure criteria.',
    'Two hundred man-months—the largest activity in the template—spread across thirty weeks and every block in the design. This is where most bugs are found and most verification time is spent, and its efficiency is set almost entirely by decisions taken in <code>DV-01</code> and <code>DV-02</code>.',
  ],
  steps:[
    {n:1, text:'Per-block testbench instantiation from the shared environment', tat:2.5, lane:'main'},
    {n:2, text:'Directed test development for specified behavior', tat:5, lane:'main'},
    {n:3, text:'Constrained-random stimulus and constraint development', tat:6, lane:'main'},
    {n:4, text:'Assertion development and binding', tat:4, lane:'par'},
    {n:5, text:'Corner-case and error-injection testing', tat:5, lane:'main'},
    {n:6, text:'Coverage analysis and hole closure per block', tat:6, lane:'main'},
    {n:7, text:'Debug and bug reporting loop with block owners', tat:8, lane:'par'},
    {n:8, text:'Block-level closure and signoff', tat:5.5, lane:'main'},
  ],
  flowNote:'Step 7 runs in parallel across the whole window because debugging is continuous rather than a phase. It is also where the largest single share of the effort goes—finding a bug is usually quicker than proving what caused it.',
  consumes:[
    'Verification environment from DV-02',
    'Block RTL releases from RTL-02',
    'Coverage model and closure criteria from DV-01',
    'Block specifications from RTL-01',
    'Regression capacity from DV-10',
  ],
  produces:[
    'Per-block testbenches and test suites',
    'Directed test suite for specified behavior',
    'Directed and constrained-random tests',
    'Bound assertion set',
    'Corner-case and error-injection results',
    'Coverage analysis and hole closure records',
    'Bug reports and debug log with block owners',
    'Assertions bound to block interfaces',
    'Block-level signoff records',
  ],
  producedBy:[1,2,3,4,5,6,7,8,8],
  rel:[
    {id:'DV-D2', rel:'feeds', text:'<b>UVM testbenches and integrated VIP.</b> Per-block testbenches extend the shared environment and are delivered with it.'},
    {id:'DV-D3', rel:'feeds', text:'<b>Regression and coverage dashboards.</b> Block coverage is the largest contributor to the dashboards <code>DV-10</code> maintains.'},
    {id:'DV-D8', rel:'feeds', text:'<b>DV closure signoff package.</b> Block signoff is the substance of chip-level closure; the package aggregates it.'},
  ],
  risks:[
    '<b>Coverage closed by adding coverage points rather than tests.</b> Redefining the model to match what was tested produces a closure number that measures nothing.',
    '<b>Constrained-random left unconstrained.</b> Random stimulus without well-designed constraints spends compute exploring illegal or uninteresting space.',
    '<b>Corner cases skipped because the specification is silent.</b> The gap belongs back in <code>RTL-01</code>, not quietly into the untested set.',
    '<b>Debug loop bottlenecked on block owners.</b> Verification finds faster than design fixes, and the queue is where the schedule quietly goes.',
    '<b>Blocks signed off against different standards.</b> Without enforced criteria from <code>DV-01</code>, each block closes to whatever its owner considered enough.',
  ],
  roles:[
    {r:'Block verification owners', d:'Own their block\'s testing and closure'},
    {r:'Verification engineers', d:'Test development, coverage and debug'},
    {r:'Block designers', d:'Bug fixing and specification clarification'},
    {r:'Verification lead', d:'Closure standard and signoff consistency'},
    {r:'Methodology engineer', d:'Constraint and assertion quality'},
  ],
  effort:[['Debug and bug reporting',55], ['Constrained-random development',40], ['Coverage analysis and closure',35], ['Directed test development',30], ['Corner-case and error injection',22], ['Assertions and signoff',18]],
  entry:[
    'Environment released by DV-02',
    'Block RTL available from RTL-02',
    'Coverage model and criteria set by DV-01',
  ],
  exit:[
    'Every block closed against the DV-01 criteria, not its own',
    'Coverage holes closed by tests, not by model changes',
    'Signoff records complete per block',
  ],
  dependsOn:['DV-01','DV-02','RTL-02'],
  dependsNote:null,
  feedsInto:['DV-04','DV-10','DV-12','RTL-02'],
  measuredBy:[
    'Blocks closed against plan',
    'Coverage achieved against the model',
    'Bug find and fix rates over time',
  ],
},

'DV-04': {
  stage:'verification', window:[14,36], criticalPath:true,
  purpose:[
    'Verify the chip as <b>one system running realistic scenarios</b>—boot, configuration, traffic, power transitions, error recovery—rather than as a collection of verified blocks.',
    'Blocks that each pass in isolation routinely fail together. Chip-level verification is where arbitration, ordering, deadlock, reset sequencing and end-to-end data integrity are actually tested, and none of those are visible from inside a block.',
  ],
  steps:[
    {n:1, text:'Chip-level environment assembly', tat:2.5, lane:'main'},
    {n:2, text:'Boot and configuration scenario development', tat:3, lane:'main'},
    {n:3, text:'End-to-end data path and integrity testing', tat:4, lane:'main'},
    {n:4, text:'Interconnect stress, arbitration and deadlock testing', tat:3.5, lane:'par'},
    {n:5, text:'Power state transition and DVFS scenario testing', tat:3, lane:'par'},
    {n:6, text:'Error injection and recovery at system level', tat:3.5, lane:'main'},
    {n:7, text:'Realistic workload scenarios from the DEF-02 suite', tat:3.5, lane:'par'},
    {n:8, text:'Chip-level coverage closure and signoff', tat:9, lane:'main'},
  ],
  flowNote:'Step 7 uses the same workloads <code>DEF-02</code> assembled and <code>ARCH-01</code> modelled. Running them in simulation is slow and worth it: it is the only place the design, the model and the product\'s actual intent are compared against each other before silicon.',
  consumes:[
    'Top-level RTL from RTL-04',
    'Block signoffs from DV-03',
    'Workload suite from DEF-02',
    'Power state definitions from ARCH-05',
    'Chip-level coverage model from DV-01',
  ],
  produces:[
    'Chip-level verification environment',
    'Boot and configuration scenarios',
    'End-to-end data integrity results',
    'Interconnect stress and deadlock findings',
    'Power transition scenario results',
    'System-level error injection and recovery results',
    'Realistic workload scenarios in the testbench',
    'Chip-level coverage closure and signoff',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'DV-D8', rel:'feeds', text:'<b>DV closure signoff package.</b> Chip-level closure is the part of the package that speaks to whether the system works, rather than the parts.'},
    {id:'DV-D3', rel:'feeds', text:'<b>Regression and coverage dashboards.</b> Chip-level scenarios are the slowest and most informative regressions on the dashboard.'},
  ],
  risks:[
    '<b>Started too late because blocks are not ready.</b> Chip-level defects take longest to find and fix, and compressing the window pushes them into silicon.',
    '<b>Scenarios written by verification alone.</b> Realistic use comes from the workload suite and from software; invented scenarios test what verification imagined.',
    '<b>Deadlock and arbitration untested.</b> These fail only under contention, which random block-level stimulus does not create.',
    '<b>Power transitions verified functionally only.</b> Retention, isolation and sequencing across a real power state change are where low-power designs actually fail.',
    '<b>Simulation too slow to run meaningful scenarios.</b> If a boot takes a day, the scenario set shrinks to what fits, and emulation in <code>DV-08</code> is the answer.',
  ],
  roles:[
    {r:'Chip verification lead', d:'Owns chip-level scenarios and closure'},
    {r:'System verification engineers', d:'Scenario development and debug'},
    {r:'Interconnect verification specialist', d:'Arbitration, ordering and deadlock'},
    {r:'Low-power verification engineer', d:'Power state transition scenarios'},
    {r:'Software liaison', d:'Boot and configuration realism'},
  ],
  effort:[['End-to-end and integrity testing',26], ['Chip-level coverage closure',20], ['Interconnect stress and deadlock',16], ['Boot and configuration scenarios',16], ['Error injection and recovery',16], ['Workload scenarios and environment',16]],
  entry:[
    'Top-level RTL boots in RTL-04',
    'Blocks largely closed in DV-03',
    'Workload suite available from DEF-02',
  ],
  exit:[
    'Realistic workload scenarios run, not only synthetic ones',
    'Deadlock and arbitration tested under contention',
    'Chip-level coverage closed against the DV-01 model',
  ],
  dependsOn:['DV-01','DV-02','DV-03','RTL-04'],
  dependsNote:null,
  feedsInto:['DV-08','DV-09','DV-10','DV-12','BU-04'],
  measuredBy:[
    'Scenarios run against scenarios planned',
    'Chip-level bugs found against block-level',
    'Simulation throughput on the boot scenario',
  ],
},

'DV-05': {
  stage:'verification', window:[10,26], criticalPath:false,
  purpose:[
    'Use <b>formal proof where simulation is weak</b>—connectivity, control logic, arbiters, security properties, register access—and prove exhaustively what testing can only sample.',
    'Formal answers a different question. Simulation shows that the cases tried worked; a proof shows that no case exists that does not. For arbiters, protocol state machines and security isolation, the space is too large to sample and the failure modes are exactly the ones random stimulus misses.',
  ],
  steps:[
    {n:1, text:'Target selection — where formal beats simulation', tat:1.5, lane:'main'},
    {n:2, text:'Property specification per target', tat:3, lane:'main'},
    {n:3, text:'Connectivity and structural proof at chip level', tat:2.5, lane:'par'},
    {n:4, text:'Control logic and arbiter proofs', tat:3.5, lane:'main'},
    {n:5, text:'Security and isolation property proofs', tat:2.5, lane:'par'},
    {n:6, text:'Assumption review and over-constraint checking', tat:2.5, lane:'main'},
    {n:7, text:'Proof closure, bounded results and reporting', tat:5.5, lane:'main'},
  ],
  flowNote:'Step 6 is what separates a proof from a false claim. A property that passes because assumptions excluded the failing case has proved nothing, and reviewing assumptions is the only way to know which of the two happened.',
  consumes:[
    'Verification plan target selection from DV-01',
    'Block RTL from RTL-02',
    'Security architecture properties from ARCH-07',
    'Interface protocol definitions from ARCH-04',
    'Formal tool setup from PDK-08',
  ],
  produces:[
    'Formal target list with rationale',
    'Property specifications per target',
    'Connectivity and structural proof results',
    'Control and arbiter proof results',
    'Security property proof results',
    'Assumption review and over-constraint findings',
    'Assumption list and proof closure report',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'DV-D4', rel:'produces', text:'<b>Formal proof reports with assumption list.</b> This activity is the deliverable, and the assumption list is what makes the proofs auditable.'},
    {id:'DV-D8', rel:'feeds', text:'<b>DV closure signoff package.</b> Formally proved properties are a different kind of evidence from coverage, and the package should distinguish them.'},
  ],
  risks:[
    '<b>Over-constrained proofs.</b> Assumptions that exclude the failing case produce a green result and no information, and only assumption review catches it.',
    '<b>Formal applied where simulation is better.</b> Datapath and workload behavior are poor formal targets; applying it there consumes specialist time for little return.',
    '<b>Bounded results reported as proofs.</b> A property proved to depth twenty is not proved; the bound has to be stated with the result.',
    '<b>Properties written from the RTL.</b> A property derived from the implementation proves the implementation matches itself.',
    '<b>Security properties omitted.</b> Isolation and access control are exactly the properties simulation samples poorly and formal proves well.',
  ],
  roles:[
    {r:'Formal verification lead', d:'Owns target selection and proof quality'},
    {r:'Formal engineers', d:'Property specification and proof closure'},
    {r:'Security architect', d:'Security and isolation properties'},
    {r:'Block designers', d:'Assumption review and counterexample interpretation'},
    {r:'Verification lead', d:'Integrates formal results into closure evidence'},
  ],
  effort:[['Property specification',10], ['Control and arbiter proofs',9], ['Proof closure and reporting',8], ['Assumption review',6], ['Security property proofs',4], ['Connectivity proofs',3]],
  entry:[
    'Formal targets selected in DV-01',
    'Block RTL stable enough to prove against',
    'Formal tools qualified by PDK-08',
  ],
  exit:[
    'Every proof reported with its assumptions and its bound',
    'Assumptions reviewed for over-constraint, not just listed',
    'Security properties proved rather than sampled',
  ],
  dependsOn:['DV-01','RTL-02','ARCH-07','PDK-08'],
  dependsNote:null,
  feedsInto:['DV-10','DV-12','SO-09'],
  measuredBy:[
    'Properties fully proved against bounded',
    'Assumptions reviewed against assumptions made',
    'Bugs found by formal that simulation had missed',
  ],
},

'DV-06': {
  stage:'verification', window:[18,28], criticalPath:false,
  purpose:[
    'Verify the design <b>against its power intent</b>—isolation, retention, level shifting, power sequencing—because none of it is visible in a normal functional simulation.',
    'A design that passes every functional test can still corrupt state on a power-down, drive an isolated domain, or fail to retain what it needed. Low-power verification simulates the domains actually powering down, and it is the only place these failures appear before silicon.',
  ],
  steps:[
    {n:1, text:'UPF-aware simulation environment setup', tat:1.5, lane:'main'},
    {n:2, text:'Static UPF structural checking', tat:1.5, lane:'main'},
    {n:3, text:'Isolation and level shifter verification', tat:2, lane:'main'},
    {n:4, text:'Retention and state restoration verification', tat:2, lane:'par'},
    {n:5, text:'Power sequencing and controller verification', tat:2, lane:'par'},
    {n:6, text:'Power-aware regression integration', tat:1.5, lane:'par'},
    {n:7, text:'Low-power coverage closure and reporting', tat:5, lane:'main'},
  ],
  flowNote:'Step 4 is the one that finds real bugs. Retention verification requires actually powering a domain down in simulation and checking what survives; a design that has never been simulated through a power cycle has never been tested for the failure mode.',
  consumes:[
    'UPF power intent from RTL-05',
    'Power state definitions from ARCH-05',
    'Verification environment from DV-02',
    'Power management controller RTL from RTL-05',
    'Low-power tool support from PDK-08',
  ],
  produces:[
    'UPF-aware simulation environment',
    'Static UPF structural check results',
    'Isolation and level shifter verification results',
    'Retention verification results',
    'Power sequencing verification results',
    'Power-aware regression integration',
    'Low-power coverage report',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'DV-D5', rel:'produces', text:'<b>Low-power verification report.</b> This activity is the deliverable, and it is the only evidence that the power architecture works as intended.'},
    {id:'DV-D3', rel:'feeds', text:'<b>Regression and coverage dashboards.</b> Power-aware regressions belong in the same dashboard as functional ones, not in a side report.'},
  ],
  risks:[
    '<b>Only static checking performed.</b> Structural UPF checks find missing cells; only simulation finds a design that corrupts state when the domain actually goes down.',
    '<b>Retention verified for the intended state only.</b> What is not retained matters as much as what is, and a design that retains too little fails on resume.',
    '<b>Power sequences tested in isolation.</b> The failure is usually a power transition during traffic, not a clean idle transition.',
    '<b>Power-aware simulation excluded from regression.</b> It is slow, so it gets run once; a later RTL change then breaks it silently.',
    '<b>UPF used for verification differing from synthesis.</b> Two versions of the intent means verifying one design and building another.',
  ],
  roles:[
    {r:'Low-power verification engineer', d:'Owns power-aware verification and closure'},
    {r:'Low-power implementation lead', d:'UPF correctness and intent alignment'},
    {r:'Verification methodology engineer', d:'Power-aware regression integration'},
    {r:'Power architect', d:'Confirms the verified states match the architecture'},
    {r:'Block designers', d:'Retention and isolation defect fixes'},
  ],
  effort:[['Isolation and retention verification',7], ['Power sequencing verification',4], ['Coverage closure and reporting',3.5], ['Environment setup',2.5], ['Static checking',1.5], ['Regression integration',1.5]],
  entry:[
    'UPF available and tool-accepted from RTL-05',
    'Power states defined by ARCH-05',
    'Environment available from DV-02',
  ],
  exit:[
    'Domains simulated powering down, not only statically checked',
    'Retention verified for both what is kept and what is not',
    'Power-aware tests running in the regular regression',
  ],
  dependsOn:['DV-02','RTL-05','ARCH-05'],
  dependsNote:null,
  feedsInto:['DV-10','DV-12','SO-09','BU-02'],
  measuredBy:[
    'Power states simulated against states defined',
    'Retention defects found pre-silicon',
    'Power-aware tests in the nightly regression',
  ],
},

'DV-07': {
  stage:'verification', window:[16,28], criticalPath:false,
  purpose:[
    'Verify the <b>boundary between the analog macros and the digital design</b>—control interfaces, calibration sequences, startup ordering—with the analog represented by models correlated to its circuits.',
    'Analog blocks fail where they meet digital. A PLL that locks perfectly and a controller that sequences perfectly can still disagree about when lock is valid. Co-simulation is where those disagreements appear, and the alternative is finding them at bring-up with an oscilloscope.',
  ],
  steps:[
    {n:1, text:'Co-simulation environment and model integration', tat:2, lane:'main'},
    {n:2, text:'Model fidelity review against AMS characterization', tat:2, lane:'main'},
    {n:3, text:'Control and configuration interface verification', tat:2.5, lane:'main'},
    {n:4, text:'Calibration and training sequence verification', tat:2.5, lane:'par'},
    {n:5, text:'Startup, lock and ready-signaling verification', tat:2, lane:'par'},
    {n:6, text:'Analog fault and degraded-mode behavior', tat:1.5, lane:'par'},
    {n:7, text:'Co-simulation closure and findings report', tat:5.5, lane:'main'},
  ],
  flowNote:'Step 2 decides whether any of this is meaningful. Verification against a behavioural model that does not match the circuit proves the digital side works with a fiction, and the correlation in <code>AMS-16</code> is what makes the model a proxy rather than a guess.',
  consumes:[
    'Behavioural models from AMS-15',
    'Correlation results from AMS-16',
    'Integrated AMS macros from RTL-03',
    'Startup and sequencing requirements from ARCH-05',
    'Verification environment from DV-02',
  ],
  produces:[
    'AMS co-simulation environment',
    'Model fidelity review findings',
    'Control and configuration interface results',
    'Calibration and training sequence results',
    'Startup and ready-signaling results',
    'Analog fault and degraded-mode results',
    'Co-simulation findings report',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'DV-D2', rel:'feeds', text:'<b>UVM testbenches and integrated VIP.</b> The co-simulation environment extends the shared testbench rather than standing beside it.'},
    {id:'DV-D8', rel:'feeds', text:'<b>DV closure signoff package.</b> Mixed-signal boundary closure is a distinct claim in the package, because it rests on models rather than on RTL alone.'},
  ],
  risks:[
    '<b>Models never correlated.</b> Digital passes against a fiction, and the mismatch reaches silicon as a bring-up failure nobody predicted.',
    '<b>Calibration sequences untested from the digital side.</b> A calibration that works when the analog engineer drives it manually is first exercised by firmware at bring-up.',
    '<b>Ready and lock signaling assumed.</b> When a lock signal becomes valid is a contract; each side assuming a different answer produces intermittent boot failures.',
    '<b>Degraded modes unverified.</b> What the digital side does when a PLL fails to lock is behavior that only matters in the field, where it matters a great deal.',
    '<b>Co-simulation too slow to regress.</b> Run once and never again, it cannot catch a later change on either side.',
  ],
  roles:[
    {r:'AMS verification engineer', d:'Owns co-simulation and model fidelity'},
    {r:'Analog designers', d:'Model accuracy and expected behavior'},
    {r:'Digital verification engineers', d:'Control and calibration sequence testing'},
    {r:'Firmware liaison', d:'Calibration sequences as software will drive them'},
    {r:'Verification lead', d:'Integrates findings into closure evidence'},
  ],
  effort:[['Control and calibration verification',7], ['Model fidelity review',4], ['Startup and signaling verification',3.5], ['Environment and model integration',3], ['Findings report',1.5], ['Degraded-mode testing',1]],
  entry:[
    'Behavioural models released by AMS-15',
    'AMS macros integrated in RTL-03',
    'Co-simulation tools available and qualified',
  ],
  exit:[
    'Every model correlated against its circuit before being relied on',
    'Calibration sequences exercised from the digital side',
    'Degraded and fault behavior verified, not assumed',
  ],
  dependsOn:['DV-02','RTL-03','AMS-15','AMS-16'],
  dependsNote:null,
  feedsInto:['DV-10','DV-12','BU-03','BU-05'],
  measuredBy:[
    'Models correlated against models used',
    'Boundary defects found here against at bring-up',
    'Calibration sequences verified against those implemented',
  ],
},

'DV-08': {
  stage:'verification', window:[6,26], criticalPath:false,
  purpose:[
    'Stand up <b>emulation and FPGA prototyping</b>—partitioning, capacity, speed, debug—so that scenarios too long for simulation can actually be run.',
    'A boot that takes a day in simulation takes minutes in emulation, and workload scenarios that are impossible in one are routine in the other. Emulation is also the platform firmware development runs on, which makes its availability date a dependency for a team outside this stage entirely.',
  ],
  steps:[
    {n:1, text:'Platform selection and capacity sizing', tat:2, lane:'main'},
    {n:2, text:'Design partitioning across the platform', tat:3.5, lane:'main'},
    {n:3, text:'Memory and interface modeling on the platform', tat:3, lane:'par'},
    {n:4, text:'Bring-up and first boot on emulation', tat:4, lane:'main'},
    {n:5, text:'Debug and visibility infrastructure', tat:3, lane:'par'},
    {n:6, text:'Performance and throughput tuning', tat:2.5, lane:'par'},
    {n:7, text:'Long-scenario and workload execution', tat:8, lane:'main'},
    {n:8, text:'Platform handover to firmware and validation', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 8 makes this activity a dependency for people outside verification. Firmware cannot start on real workloads until the platform runs, and the handover date belongs in the program schedule rather than in the verification plan alone.',
  consumes:[
    'Top-level RTL from RTL-04',
    'Emulator or FPGA capacity and licences',
    'Memory and interface models for the platform',
    'Workload suite from DEF-02',
    'Debug requirements from validation and firmware',
  ],
  produces:[
    'Platform selection and capacity plan',
    'Design partitioning for the platform',
    'Memory and interface models',
    'Working emulation platform with boot',
    'Debug and visibility infrastructure',
    'Performance and throughput tuning record',
    'Long-scenario and workload results',
    'Platform handover package to firmware and validation',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'DV-D6', rel:'produces', text:'<b>Emulation platform and system test suite.</b> This activity is the deliverable, and it serves firmware and validation as much as verification.'},
    {id:'DV-D3', rel:'feeds', text:'<b>Regression and coverage dashboards.</b> Emulation regressions cover scenarios simulation cannot reach, and belong in the same view.'},
  ],
  risks:[
    '<b>Partitioning consuming more time than expected.</b> Splitting a large design across emulator capacity is difficult and iterative, and it is routinely underestimated.',
    '<b>Capacity contended with another program.</b> Emulator capacity is expensive and shared; a program without a booked allocation runs when the other one is not.',
    '<b>Debug visibility inadequate.</b> A platform that runs fast and cannot be probed produces failures that cannot be diagnosed.',
    '<b>Handover date not in the program schedule.</b> Firmware plans against it, and treating it as an internal verification milestone means nobody outside knows when it slips.',
    '<b>Models diverging from the design.</b> Memory and interface models built for the platform can drift from the RTL, and results then reflect the model.',
  ],
  roles:[
    {r:'Emulation lead', d:'Owns the platform, partitioning and bring-up'},
    {r:'Emulation engineers', d:'Partitioning, modeling and tuning'},
    {r:'Debug infrastructure engineer', d:'Visibility and trace on the platform'},
    {r:'Firmware liaison', d:'Handover requirements and platform use'},
    {r:'Program manager', d:'Capacity booking and handover date'},
  ],
  effort:[['Design partitioning',14], ['Bring-up and first boot',12], ['Memory and interface modeling',10], ['Debug infrastructure',8], ['Long-scenario execution',7], ['Handover and tuning',4]],
  entry:[
    'Top-level RTL elaborating from RTL-04',
    'Emulator or FPGA capacity booked',
    'Workload suite available from DEF-02',
  ],
  exit:[
    'Design boots on the platform at usable speed',
    'Debug visibility sufficient to diagnose a failure',
    'Platform handed over to firmware on a scheduled date',
  ],
  dependsOn:['DV-02','RTL-04','DEF-02'],
  dependsNote:null,
  feedsInto:['DV-04','DV-09','DV-10','BU-04'],
  measuredBy:[
    'Emulation speed against target',
    'Weeks from RTL availability to first platform boot',
    'Scenarios run on emulation that simulation could not',
  ],
},

'DV-09': {
  stage:'verification', window:[22,34], criticalPath:false,
  purpose:[
    'Check that the design <b>actually delivers the performance the architecture promised</b>—bandwidth, latency, utilization—against the same workloads <code>ARCH-01</code> modelled.',
    'Functional correctness and performance are separate questions, and passing every test says nothing about the second. A design that computes correctly at 60% of modelled throughput is a product that misses its headline KPI, and finding that in silicon leaves no options.',
  ],
  steps:[
    {n:1, text:'Performance measurement infrastructure in the testbench', tat:1.5, lane:'main'},
    {n:2, text:'Workload execution on emulation and simulation', tat:3, lane:'main'},
    {n:3, text:'Bandwidth and utilization measurement against the model', tat:2.5, lane:'main'},
    {n:4, text:'Latency and queueing analysis', tat:2, lane:'par'},
    {n:5, text:'Bottleneck identification and root cause', tat:2.5, lane:'par'},
    {n:6, text:'Correlation against the ARCH-01 performance model', tat:2.5, lane:'main'},
    {n:7, text:'Findings, recommendations and model reconciliation', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 6 closes a loop opened at architecture. Where the RTL and the model disagree, one of them is wrong—and finding out which is what tells the program whether it has a design problem or a modeling problem.',
  consumes:[
    'Emulation platform from DV-08',
    'Workload suite from DEF-02',
    'Performance model and predictions from ARCH-01',
    'Chip-level environment from DV-04',
    'KPI targets from DEF-02',
  ],
  produces:[
    'Performance measurement infrastructure',
    'Workload execution results',
    'Bandwidth, utilization and latency measurements',
    'Latency and queueing analysis',
    'Bottleneck analysis with root causes',
    'Model correlation results',
    'Findings and recommendations',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'DV-D8', rel:'feeds', text:'<b>DV closure signoff package.</b> Performance evidence is part of tapeout readiness—functional closure alone does not say the product meets its KPIs.'},
    {id:'DV-D6', rel:'feeds', text:'<b>Emulation platform and system test suite.</b> The performance workloads become part of the standing suite the platform runs.'},
  ],
  risks:[
    '<b>Performance treated as a bring-up activity.</b> Discovered in silicon, a throughput shortfall has no remaining fix except software and marketing.',
    '<b>Measured only on synthetic traffic.</b> Synthetic patterns exercise the interconnect; real workloads exercise the design, and only the second predicts the product.',
    '<b>Model and RTL disagreement left unresolved.</b> Whichever is wrong, not knowing which means every downstream projection is unreliable.',
    '<b>Bottlenecks found without root cause.</b> Knowing throughput is low is not actionable; knowing which queue saturates is.',
    '<b>No time left to act.</b> Findings that arrive after RTL freeze can only be documented, not fixed.',
  ],
  roles:[
    {r:'Performance verification lead', d:'Owns measurement and correlation'},
    {r:'Performance architect', d:'Model comparison and reconciliation'},
    {r:'Emulation engineers', d:'Workload execution at usable speed'},
    {r:'Interconnect designers', d:'Bottleneck root cause'},
    {r:'Chief architect', d:'Decides between design change and model correction'},
  ],
  effort:[['Bandwidth and utilization measurement',8], ['Workload execution',6], ['Bottleneck analysis',5], ['Model correlation',5], ['Latency analysis',3], ['Findings and reconciliation',3]],
  entry:[
    'Emulation platform running from DV-08',
    'Chip-level environment available from DV-04',
    'Performance model predictions available from ARCH-01',
  ],
  exit:[
    'Real workloads measured, not only synthetic traffic',
    'Every model disagreement resolved as design or model error',
    'Findings delivered with time to act on them',
  ],
  dependsOn:['DV-04','DV-08','ARCH-01','DEF-02'],
  dependsNote:null,
  feedsInto:['DV-10','ARCH-01','BU-08'],
  measuredBy:[
    'Measured throughput against modelled',
    'Bottlenecks with an identified root cause',
    'Weeks between findings and RTL freeze',
  ],
},

'DV-10': {
  stage:'verification', window:[12,38], criticalPath:true,
  purpose:[
    'Keep the regressions running and the <b>coverage moving toward closure</b>—triage failures, manage capacity, publish where every block stands, and close the holes that remain.',
    'Coverage closure is not a phase at the end; it is a curve that either bends or does not. This activity owns the curve: which holes are real, which tests would close them, and whether the regression is stable enough for the numbers to mean anything.',
  ],
  steps:[
    {n:1, text:'Regression suite definition and tiering', tat:2, lane:'main'},
    {n:2, text:'Regression infrastructure and capacity management', tat:2.5, lane:'main'},
    {n:3, text:'Failure triage process and ownership', tat:2.5, lane:'par'},
    {n:4, text:'Coverage collection, merging and reporting', tat:3, lane:'main'},
    {n:5, text:'Coverage hole analysis and test targeting', tat:5, lane:'main'},
    {n:6, text:'Regression stability and flake elimination', tat:4, lane:'par'},
    {n:7, text:'Dashboard publication and closure tracking', tat:4, lane:'par'},
    {n:8, text:'Coverage closure and signoff assembly', tat:13.5, lane:'main'},
  ],
  flowNote:'Step 6 is unglamorous and load-bearing. A regression with intermittent failures trains everyone to ignore red results, and once that habit forms the regression has stopped being a signal.',
  consumes:[
    'Coverage model and criteria from DV-01',
    'Test suites from DV-03 through DV-09',
    'Regression capacity from PDK-12 and RTL-09',
    'Build and CI infrastructure from RTL-09',
    'Closure criteria per block',
  ],
  produces:[
    'Tiered regression suites',
    'Regression infrastructure and capacity plan',
    'Failure triage process with ownership',
    'Merged coverage reporting',
    'Hole analysis and targeted test list',
    'Regression stability and flake elimination record',
    'Published coverage dashboard',
    'Coverage dashboards and closure signoff',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'DV-D3', rel:'produces', text:'<b>Regression and coverage dashboards.</b> This activity is the deliverable, and its value is that the numbers are current and trusted.'},
    {id:'DV-D8', rel:'produces', text:'<b>DV closure signoff package.</b> Closure is assembled here from the evidence every other DV activity produced.'},
  ],
  risks:[
    '<b>Flaky regressions tolerated.</b> Once red results are routinely ignored, the regression has stopped providing information and nobody notices when it matters.',
    '<b>Coverage merged without stability.</b> Numbers from an unstable regression are noise presented as a trend.',
    '<b>Holes closed by waiving rather than testing.</b> A hole waived without analysis is untested behavior recorded as covered.',
    '<b>Capacity insufficient at peak.</b> Regression queues at the point of closure directly extend the closure date.',
    '<b>Closure signed with the curve still climbing.</b> Coverage still rising at signoff means the plan\'s completion criteria were not what stopped the work.',
  ],
  roles:[
    {r:'Regression owner', d:'Owns suites, stability and capacity'},
    {r:'Coverage lead', d:'Hole analysis, targeting and closure'},
    {r:'Verification lead', d:'Closure signoff and package assembly'},
    {r:'Block verification owners', d:'Triage and close their own failures'},
    {r:'CAD infrastructure', d:'Compute and license capacity'},
  ],
  effort:[['Coverage hole analysis and targeting',12], ['Closure and signoff assembly',10], ['Regression stability',8], ['Coverage collection and reporting',6], ['Triage process',5], ['Infrastructure and dashboards',4]],
  entry:[
    'Coverage model defined by DV-01',
    'Test suites producing coverage from DV-03',
    'Regression capacity allocated',
  ],
  exit:[
    'Regression stable enough that a red result is believed',
    'Every hole analyzed before it is closed or waived',
    'Coverage curve flat at signoff, not still climbing',
  ],
  dependsOn:['DV-01','DV-03','RTL-09','PDK-12'],
  dependsNote:null,
  feedsInto:['DV-12','SYN-05','TO-03','SO-09'],
  measuredBy:[
    'Regression flake rate',
    'Coverage against the model at signoff',
    'Holes analyzed against holes waived',
  ],
},

'DV-11': {
  stage:'verification', window:[28,38], criticalPath:true,
  purpose:[
    'Simulate the <b>gate-level netlist</b>, first functionally and then with real timing, to catch what RTL simulation structurally cannot—X-propagation, reset behavior, timing-dependent failures and synthesis or DFT-induced differences.',
    'RTL simulation is optimistic about X and blind to timing. Gate-level simulation is slow, painful and the last check before the design becomes masks—it is also where scan insertion, clock gating and synthesis transformations are proved not to have changed behavior.',
  ],
  steps:[
    {n:1, text:'Gate-level environment and netlist bring-up', tat:1.5, lane:'main'},
    {n:2, text:'Zero-delay functional gate-level simulation', tat:2, lane:'main'},
    {n:3, text:'X-propagation and reset initialization analysis', tat:2, lane:'main'},
    {n:4, text:'SDF back-annotated timing simulation', tat:2.5, lane:'par'},
    {n:5, text:'DFT and scan mode simulation', tat:2, lane:'par'},
    {n:6, text:'Power-aware gate-level simulation', tat:1.5, lane:'par'},
    {n:7, text:'Failure debug and closure', tat:4.5, lane:'main'},
  ],
  flowNote:'Step 3 finds the class of bug RTL simulation is structurally incapable of seeing. RTL X-optimism hides uninitialized state; at gate level the X propagates, and a design that boots in RTL can fail to come out of reset in gates.',
  consumes:[
    'Gate-level netlist from SYN-01',
    'SDF timing from PD-09',
    'Scan-inserted netlist from DFT-06',
    'Verification environment from DV-02',
    'Power intent from RTL-05',
  ],
  produces:[
    'Gate-level environment with the netlist brought up',
    'Functional gate-level results',
    'X-propagation and reset initialization findings',
    'SDF timing-annotated simulation results',
    'Scan and DFT mode simulation results',
    'Gate-level simulation environment',
    'Gate-level simulation report',
    'Failure debug and closure record',
  ],
  producedBy:[1,2,3,4,5,6,6,7],
  rel:[
    {id:'DV-D7', rel:'produces', text:'<b>Gate-level simulation report.</b> This activity is the deliverable, and it is a tapeout checklist item rather than an optional confirmation.'},
    {id:'DV-D8', rel:'feeds', text:'<b>DV closure signoff package.</b> Gate-level results close the gap between what was verified and what will be manufactured.'},
  ],
  risks:[
    '<b>Skipped because it is slow.</b> The failures it finds—X propagation, reset, timing-dependent behavior—have no other pre-silicon detector.',
    '<b>Run only in functional mode.</b> Scan and test modes are how the part is tested at ATE, and a scan mode that does not work makes the part untestable.',
    '<b>Started after netlist churn has settled.</b> Waiting for a stable netlist means starting too late; running early on an imperfect netlist finds environment problems while there is time.',
    '<b>X failures suppressed rather than fixed.</b> Forcing initial values to make the simulation run hides exactly the uninitialized state the check exists to find.',
    '<b>Timing simulation on a subset of corners.</b> Timing-dependent failures appear at specific corners, and the corner skipped is the one that fails.',
  ],
  roles:[
    {r:'Gate-level simulation lead', d:'Owns the runs and the closure'},
    {r:'Verification engineers', d:'Debug and failure analysis'},
    {r:'Synthesis liaison', d:'Netlist and transformation questions'},
    {r:'DFT engineer', d:'Scan and test mode simulation'},
    {r:'Physical design liaison', d:'SDF generation and timing questions'},
  ],
  effort:[['Failure debug and closure',7], ['Functional gate-level simulation',4], ['X-propagation analysis',3.5], ['SDF timing simulation',3], ['Scan and DFT mode simulation',1.5], ['Power-aware simulation',1]],
  entry:[
    'Gate-level netlist available from SYN-01',
    'Scan insertion complete in DFT-06',
    'SDF available from PD-09 for timing runs',
  ],
  exit:[
    'X-propagation issues fixed rather than suppressed',
    'Scan and test modes simulated, not only functional',
    'Timing simulation run at the corners that matter',
  ],
  dependsOn:['DV-02','SYN-01','DFT-06','RTL-05'],
  dependsNote:null,
  feedsInto:['DV-12','DFT-08','TO-02','SO-09'],
  measuredBy:[
    'Modes simulated against modes the part will use',
    'X failures fixed against suppressed',
    'Gate-level defects found that RTL simulation could not',
  ],
},

'DV-12': {
  stage:'verification', window:[6,40], criticalPath:true,
  purpose:[
    'Run the <b>bug disposition board</b>—triage every defect, decide what gets fixed, and make the risk of what does not explicit and owned.',
    'Every program reaches tapeout with open bugs. The question is whether they were assessed and accepted or simply ran out of time, and the difference is entirely this activity. Its output at the end is the errata list bring-up will work against and the risk statement the Go / No-Go decision reads.',
  ],
  steps:[
    {n:1, text:'Bug tracking, severity and triage process definition', tat:1.5, lane:'main'},
    {n:2, text:'Disposition board charter and membership', tat:1, lane:'main'},
    {n:3, text:'Continuous triage and disposition', tat:22, lane:'main'},
    {n:4, text:'Bug rate and closure trend analysis', tat:4, lane:'par'},
    {n:5, text:'Deferred bug risk assessment', tat:4, lane:'par'},
    {n:6, text:'Escape analysis on late-found defects', tat:3, lane:'par'},
    {n:7, text:'Open bug list and risk statement for tapeout', tat:5, lane:'main'},
    {n:8, text:'DV closure recommendation', tat:4.5, lane:'main'},
  ],
  flowNote:'Step 6 is the loop that improves the process rather than the design. Asking why a bug found in week 34 was not found in week 12 usually points at a missing coverage point or an untested mode, and fixing that finds the next one earlier.',
  consumes:[
    'Defects from every DV activity',
    'Coverage and closure status from DV-10',
    'Change control decisions from RTL-10',
    'Silicon debug capability from DFT-11',
    'Tapeout criteria from the program plan',
  ],
  produces:[
    'Bug tracking and triage process',
    'Disposition board decisions',
    'Triage and disposition log',
    'Bug rate and closure trend analysis',
    'Deferred bug risk assessments',
    'Escape analysis findings',
    'Open bug list and risk statement',
    'DV closure recommendation',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'DV-D8', rel:'feeds', text:'<b>DV closure signoff package.</b> The open bug list and its risk statement are the part of the package the Go / No-Go decision actually reads.'},
    {id:'DV-D3', rel:'feeds', text:'<b>Regression and coverage dashboards.</b> Bug find and closure rates sit alongside coverage as the two curves that say whether verification is converging.'},
  ],
  risks:[
    '<b>Bugs deferred without risk assessment.</b> An unassessed open bug at tapeout is a risk nobody quantified being accepted by nobody in particular.',
    '<b>Severity assigned by the finder.</b> Consistent severity requires a board; without one, the same defect is critical in one block and minor in another.',
    '<b>Bug rate still rising at closure.</b> A find rate that has not turned over means the design has more defects than have been found, whatever the coverage says.',
    '<b>No escape analysis.</b> The process that let a bug survive to week 34 will let the next one survive too.',
    '<b>Errata list assembled after tapeout.</b> Bring-up needs the known-issue list on day one, and assembling it later means debugging problems that were already known.',
  ],
  roles:[
    {r:'Verification lead', d:'Chairs the disposition board'},
    {r:'RTL lead', d:'Fix feasibility and design-side impact'},
    {r:'Chief architect', d:'Severity and product impact of deferred defects'},
    {r:'Program manager', d:'Risk acceptance and tapeout criteria'},
    {r:'Validation liaison', d:'Turns deferred bugs into bring-up watch items'},
  ],
  effort:[['Continuous triage and disposition',10], ['Open bug list and risk statement',4], ['Deferred bug risk assessment',4], ['Trend analysis',3], ['Escape analysis',2], ['Closure recommendation',2]],
  entry:[
    'Bug tracking system and severity scheme agreed',
    'Board membership named and meeting',
    'Tapeout criteria defined in the program plan',
  ],
  exit:[
    'Every deferred bug carries an assessed, owned risk',
    'Bug find rate turned over before closure is recommended',
    'Errata list ready for bring-up on day one',
  ],
  dependsOn:['DV-01','DV-10','RTL-10'],
  dependsNote:null,
  feedsInto:['TO-04','TO-05','BU-10','SO-09'],
  measuredBy:[
    'Deferred bugs with a risk assessment',
    'Bug find rate trend at closure',
    'Escapes analyzed against escapes found',
  ],
},

};
