/* /details/glossary.js — every abbreviation the template uses, expanded.
 * `full` is the expansion; `note` says what it is and why a program manager
 * would care. `group` orders the printed appendix. */
const G = {

/* ---------- program and commercial ---------- */
'TAT':   ['Turn-Around Time', 'program', 'Elapsed calendar time an activity occupies, in weeks. Not the same as effort — a 20-week activity may take one person or ten.'],
'M/M':   ['Man-Month', 'program', 'One person working for one month. The unit of effort in this template; summing it across a stage gives the headcount the stage consumes.'],
'FTE':   ['Full-Time Equivalent', 'program', 'One person working full time. Derived here as M/M ÷ TAT in months — the team size implied while the activity runs.'],
'PPA':   ['Power, Performance, Area', 'program', 'The three quantities every chip design trades against each other. A "PPA target" is the contract the architecture must meet.'],
'KPI':   ['Key Performance Indicator', 'program', 'A measurable target derived from a requirement. A requirement without a KPI cannot be tested at the end.'],
'NRE':   ['Non-Recurring Engineering', 'program', 'One-off cost — masks, tooling, IP licences — as opposed to per-unit cost. Dominates the business case for an advanced node.'],
'ASP':   ['Average Selling Price', 'program', 'What the part is expected to sell for. With yield and cost it decides whether the program has a margin.'],
'BOM':   ['Bill of Materials', 'program', 'The itemized list of what goes into the product. An IP BOM lists every IP block the die needs and where it comes from.'],
'PRD':   ['Product Requirements Document', 'program', 'The baselined statement of what the product must do. Everything downstream is an answer to it.'],
'NDA':   ['Non-Disclosure Agreement', 'program', 'The contract that has to exist before a foundry, IP vendor or customer will share anything useful. Routinely on the critical path early.'],
'RFI':   ['Request For Information', 'program', 'An early, non-binding enquiry to a supplier — used to scope options before quoting.'],
'RFQ':   ['Request For Quotation', 'program', 'A formal request for price and terms. Precedes a purchase order.'],
'PO':    ['Purchase Order', 'program', 'The binding commitment to buy. Long-lead items (masks, substrates, HBM) need one far earlier than intuition suggests.'],
'PCN':   ['Product Change Notification', 'program', 'The formal notice to customers that something about a shipping product has changed. Once in production, changes go through it.'],
'WIP':   ['Work In Progress', 'program', 'Material already started but not finished. In a fab it is weeks of committed capacity that cannot be redirected.'],
'CI':    ['Continuous Integration', 'program', 'Automated build-and-test on every change. In hardware it usually means nightly regressions rather than per-commit.'],
'DOE':   ['Design Of Experiments', 'program', 'A structured set of experimental splits chosen so each variable\'s effect can be separated. How process windows get characterized.'],
'SW/FW': ['Software / Firmware', 'program', 'Out of scope for this template, which covers design and silicon enablement only — but the handoff boundary still has to be agreed.'],

/* ---------- process, foundry and manufacturing ---------- */
'FEOL':  ['Front End Of Line', 'process', 'The transistor-forming steps of wafer fabrication. Taped out first in a split MTO, because it has the longest cycle time.'],
'BEOL':  ['Back End Of Line', 'process', 'The metal interconnect layers built above the transistors. Taped out about a month after FEOL to buy design-fix time.'],
'MTO':   ['Mask Tape-Out', 'process', 'The release of the design database to mask making. The irreversible commitment — masks cost millions and take weeks.'],
'PDK':   ['Process Design Kit', 'process', 'The foundry\'s package of models, rules and libraries that makes a process usable. Its version and maturity gate everything downstream.'],
'DK':    ['Design Kit', 'process', 'Used interchangeably with PDK; sometimes the assembly or package equivalent supplied by the OSAT.'],
'DRM':   ['Design Rule Manual', 'process', 'The foundry document defining what geometry is legal. Its version has to match the DRC deck actually being run.'],
'DTCO':  ['Design-Technology Co-Optimization', 'process', 'Tuning design style and process options together rather than treating the process as fixed. Where standard-cell track height gets decided.'],
'EUV':   ['Extreme Ultraviolet lithography', 'process', 'The lithography used at advanced nodes. Its layer count drives mask cost and cycle time.'],
'ULK':   ['Ultra Low-K dielectric', 'process', 'The fragile low-capacitance insulator in BEOL. Mechanically weak, which is why chip-package interaction stress matters.'],
'CMP':   ['Chemical Mechanical Planarization', 'process', 'The polishing step that keeps each layer flat. Drives metal-density fill rules in layout.'],
'OPC':   ['Optical Proximity Correction', 'process', 'Pre-distorting mask shapes so the printed result matches intent. Part of mask data prep, after tapeout.'],
'MDP':   ['Mask Data Preparation', 'process', 'Turning the design database into mask-writer input — fracturing, OPC, job deck. Weeks of work between tapeout and first wafer.'],
'WAT':   ['Wafer Acceptance Test', 'process', 'Parametric measurement on scribe-line structures. Tells you whether the process was in spec independently of whether the chip works.'],
'PCM':   ['Process Control Monitor', 'process', 'The test structures WAT measures. Their readings are the earliest signal that a lot drifted.'],
'MPW':   ['Multi-Project Wafer', 'process', 'A shared mask set carrying several designs. The cheap way to get a test chip fabricated.'],
'OSAT':  ['Outsourced Semiconductor Assembly and Test', 'process', 'The subcontractor that packages and tests the die. Owns the assembly process knowledge the program depends on.'],
'KGD':   ['Known Good Die', 'process', 'A die screened at wafer sort as worth packaging. On a 2.5D part an escaped bad die costs an entire assembled module.'],
'TSV':   ['Through-Silicon Via', 'process', 'A vertical connection through a die or interposer. What makes stacked and 2.5D construction possible.'],
'RDL':   ['Redistribution Layer', 'process', 'Fine wiring on the die or interposer surface that moves connections to where the bumps are.'],
'CoWoS':['Chip-on-Wafer-on-Substrate', 'process', 'A 2.5D packaging technology: die placed on a silicon interposer, which sits on the substrate. The construction assumed here.'],
'TV':    ['Test Vehicle', 'process', 'A structure built purely to learn about a process, not to sell. Retires risk before the real product commits.'],
'MTV':   ['Mechanical Test Vehicle', 'process', 'A test vehicle for warpage, stress and assembly mechanics rather than electrical behavior.'],
'TTV':   ['Thermal Test Vehicle', 'process', 'A test vehicle carrying heaters and sensors, used to characterize the package thermal path before real silicon exists.'],
'CPI':   ['Chip-Package Interaction', 'process', 'Mechanical stress where die and package meet, driven by their different thermal expansion. The main reliability risk in 2.5D construction.'],

/* ---------- IP and libraries ---------- */
'IP':    ['Intellectual Property block', 'ip', 'A pre-designed functional block — a PHY, a memory compiler, a controller — bought or reused rather than written.'],
'SRAM':  ['Static Random-Access Memory', 'ip', 'On-die memory. Usually generated by a compiler; when the compiler misses the PPA target, a custom instance has to be developed.'],
'ROM':   ['Read-Only Memory', 'ip', 'Fixed on-die memory, typically holding boot code.'],
'OTP':   ['One-Time Programmable memory', 'ip', 'Fuse-based memory written once after manufacture — used for trim values, keys and repair settings.'],
'PLL':   ['Phase-Locked Loop', 'ip', 'The circuit that multiplies a reference clock up to the operating frequency. Its lock range bounds the shmoo.'],
'VCO':   ['Voltage-Controlled Oscillator', 'ip', 'The tunable oscillator inside a PLL.'],
'LDO':   ['Low-Dropout regulator', 'ip', 'An on-die linear regulator giving a quiet local supply to sensitive analog blocks.'],
'SerDes':['Serialiser / Deserialiser', 'ip', 'The circuit that turns parallel data into a high-speed serial stream and back. The heart of every high-speed interface.'],
'PHY':   ['Physical layer', 'ip', 'The analog and mixed-signal circuitry that drives an interface\'s wires — as opposed to the digital controller above it.'],
'NoC':   ['Network on Chip', 'ip', 'The on-die interconnect fabric carrying traffic between blocks.'],
'AMS':   ['Analog / Mixed-Signal', 'ip', 'Circuitry that is not purely digital. Characterized by simulation rather than by static timing, and on a different schedule from the digital flow.'],
'RF':    ['Radio Frequency', 'ip', 'High-frequency analog circuitry.'],
'HV':    ['High Voltage', 'ip', 'Devices rated above the core supply — used in IO and power management.'],

/* ---------- design and implementation ---------- */
'RTL':   ['Register Transfer Level', 'design', 'The synthesisable hardware description — Verilog or SystemVerilog. "RTL freeze" means no further functional change.'],
'SDC':   ['Synopsys Design Constraints', 'design', 'The file describing clocks, exceptions and IO timing. Wrong constraints make timing closure meaningless in both directions.'],
'STA':   ['Static Timing Analysis', 'design', 'Exhaustive timing checking without simulation. The basis of timing signoff.'],
'MMMC':  ['Multi-Mode Multi-Corner', 'design', 'Analyzing every operating mode against every process/voltage/temperature corner at once. The standard implementation setup.'],
'MCMM':  ['Multi-Corner Multi-Mode', 'design', 'The same thing as MMMC; vendors differ on word order.'],
'DC':    ['Direct current', 'design', 'Zero frequency. A regulator specified only at DC says nothing about how it behaves where the digital load actually switches.'],
'PVT':   ['Process, Voltage, Temperature', 'design', 'The three axes of operating variation a design must survive. "Corners" are their extremes.'],
'OCV':   ['On-Chip Variation', 'design', 'Allowance for variation between devices on the same die. AOCV and POCV are its advanced and parametric refinements.'],
'AOCV':  ['Advanced On-Chip Variation', 'design', 'Depth- and distance-dependent OCV derating — less pessimistic than a flat margin.'],
'POCV':  ['Parametric On-Chip Variation', 'design', 'Statistical OCV using per-cell sigma rather than a derate table.'],
'CTS':   ['Clock Tree Synthesis', 'design', 'Building the buffer network that delivers the clock. Sets skew, and consumes a large share of dynamic power.'],
'ECO':   ['Engineering Change Order', 'design', 'A late, targeted change to a design that is otherwise frozen. A metal-only ECO touches routing layers alone.'],
'QoR':   ['Quality of Results', 'design', 'The bundle of timing, area, power and congestion numbers a tool run produces. What "the netlist got better" actually means.'],
'DRC':   ['Design Rule Check', 'design', 'Verifying that layout geometry obeys the foundry rules. A tapeout gate.'],
'LVS':   ['Layout Versus Schematic', 'design', 'Verifying that the layout implements the intended netlist. The other tapeout gate.'],
'DFM':   ['Design For Manufacturability', 'design', 'Changes that improve yield without changing function — via doubling, spacing, fill.'],
'EM':    ['Electromigration', 'design', 'Metal atoms drifting under sustained current, eventually opening a wire. Bounds how much current a given wire width may carry. In \u201c3D EM\u201d it means electromagnetic instead \u2014 field solving for package and board models.'],
'IR':    ['IR drop', 'design', 'Supply voltage lost across the resistance of the power grid (I × R). Too much and the logic misses timing that STA said was fine.'],
'PDN':   ['Power Delivery Network', 'design', 'Everything carrying current from the regulator to the transistors — board, package and on-die grid together.'],
'SSN':   ['Simultaneous Switching Noise', 'design', 'Supply disturbance when many outputs switch together. Couples into interfaces as jitter.'],
'IO':    ['Input / Output', 'design', 'The circuitry and pads connecting the die to the outside world.'],
'DVFS':  ['Dynamic Voltage and Frequency Scaling', 'design', 'Changing supply and clock at runtime to trade power against performance.'],
'UPF':   ['Unified Power Format', 'design', 'The machine-readable description of power domains, isolation and retention. Carries power intent through the whole flow.'],
'CPM':   ['Chip Power Model', 'design', 'A compact model of the die\'s current demand, handed to package and board teams so they can size the PDN.'],
'CPS':   ['Chip Power/Signal model', 'design', 'CPM extended with signal behavior, for combined power and signal co-analysis.'],
'CDC':   ['Clock Domain Crossing', 'design', 'A signal passing between unrelated clocks. Unsynchronized crossings fail intermittently and are invisible to simulation.'],
'RDC':   ['Reset Domain Crossing', 'design', 'The same hazard for signals passing between independently reset regions.'],
'LEC':   ['Logical Equivalence Checking', 'design', 'Proving two netlists implement the same function — used after every synthesis or ECO step.'],
'GLS':   ['Gate-Level Simulation', 'design', 'Simulating the actual netlist with real delays. Slow, but catches what RTL simulation and STA both miss.'],
'FFN':   ['Final Full Netlist', 'design', 'The netlist released for the last physical-design turn — RTL frozen, ECOs closed, no functional change beyond it.'],
'N0/N1/N2':['Netlist drop 0 / 1 / 2', 'design', 'The successive netlist releases from synthesis to physical design. N0 is flow-flush — structurally representative but functionally incomplete — and each drop raises quality.'],

/* ---------- verification and DFT ---------- */
'DV':    ['Design Verification', 'verif', 'Proving the RTL does what the specification says, before any silicon exists.'],
'UVM':   ['Universal Verification Methodology', 'verif', 'The standard SystemVerilog framework for building constrained-random testbenches.'],
'VIP':   ['Verification IP', 'verif', 'A bought testbench component that models a protocol — PCIe, CXL, HBM — so the design can be checked against it.'],
'DFT':   ['Design For Test', 'verif', 'Structure added to the design purely so it can be tested and debugged — scan, BIST, compression, trace.'],
'ATPG':  ['Automatic Test Pattern Generation', 'verif', 'Computing the input patterns that expose manufacturing defects, and the coverage they reach.'],
'BIST':  ['Built-In Self-Test', 'verif', 'On-die logic that tests a block without external equipment.'],
'MBIST': ['Memory Built-In Self-Test', 'verif', 'BIST for embedded memories — the only practical way to test thousands of SRAM instances.'],
'BIRA':  ['Built-In Redundancy Analysis', 'verif', 'On-die logic that works out which spare rows or columns would repair a failing memory.'],
'BISR':  ['Built-In Self-Repair', 'verif', 'Applying that repair automatically. Turns memory defects from scrap into yield.'],
'OCC':   ['On-Chip Clock Controller', 'verif', 'Generates the fast clock pulses needed for at-speed scan testing.'],
'JTAG':  ['Joint Test Action Group (IEEE 1149.1)', 'verif', 'The standard serial access port used for boundary scan, debug and configuration.'],
'IJTAG': ['Internal JTAG (IEEE 1687)', 'verif', 'A standard for reaching instruments inside the chip through the JTAG port.'],
'ICL':   ['Instrument Connectivity Language', 'verif', 'Describes how on-die instruments are wired to the IJTAG network.'],
'PDL':   ['Procedural Description Language', 'verif', 'Describes how to operate those instruments, alongside ICL.'],
'BSDL':  ['Boundary Scan Description Language', 'verif', 'The machine-readable description of a part\'s boundary-scan behavior, delivered to board makers.'],
'TAP':   ['Test Access Port', 'verif', 'The JTAG interface pins and controller.'],
'STIL':  ['Standard Test Interface Language', 'verif', 'A vendor-neutral test pattern format. Translated to tester-native format before use.'],
'WGL':   ['Waveform Generation Language', 'verif', 'An older pattern interchange format, still used by some testers.'],
'SDF':   ['Standard Delay Format', 'verif', 'Back-annotated delays from the physical design, used to make gate-level simulation realistic.'],
'DUT':   ['Device Under Test', 'verif', 'Whatever is currently being tested — a block in simulation or a packaged part on a tester.'],
'FPGA':  ['Field-Programmable Gate Array', 'verif', 'Reconfigurable hardware used to prototype the design far faster than simulation.'],
'IPC':   ['Instructions Per Cycle', 'design', 'How much work the design retires per clock. Performance is frequency \u00d7 IPC, so a max frequency target only means something alongside the IPC assumption behind it.'],

/* ---------- signal, power and package ---------- */
'SI':    ['Signal Integrity', 'pkg', 'Whether a high-speed signal still resembles itself at the far end — loss, reflection, crosstalk, jitter.'],
'PI':    ['Power Integrity', 'pkg', 'Whether the supply stays inside its window under real switching current.'],
'SI/PI': ['Signal and Power Integrity', 'pkg', 'The two treated together, because on a high-speed interface they interact.'],
'SIPI':  ['Signal Integrity / Power Integrity', 'pkg', 'The stage that owns electrical closure across die, package and board together.'],
'EM/IR': ['Electromigration and IR drop', 'pkg', 'The two current-related checks on the on-die power grid, usually run as one analysis.'],
'TIM':   ['Thermal Interface Material', 'pkg', 'The compound between die and lid or heatsink. Its bond line thickness directly sets how much power the part can dissipate.'],
'Rjc':   ['Thermal resistance, junction to case', 'pkg', 'How many degrees the die rises per watt, measured to the package case. The package\'s share of the thermal path.'],
'Rja':   ['Thermal resistance, junction to ambient', 'pkg', 'The same, measured to the surrounding air — so it includes the cooling solution.'],
'PTV':   ['Package Test Vehicle', 'pkg', 'The vehicle program that de-risks assembly and package construction before product silicon commits.'],
'PCB':   ['Printed Circuit Board', 'pkg', 'The board the packaged part is mounted on.'],
'EVB':   ['Evaluation Board', 'pkg', 'The lab platform built to bring up and characterize the silicon. Its capability bounds what can be measured.'],
'VRM':   ['Voltage Regulator Module', 'pkg', 'The board-level regulator supplying the part. Its transient response has to follow the die\'s current steps.'],
'BERT':  ['Bit Error Rate Tester', 'pkg', 'Instrument that drives a high-speed link and counts errors — how link margin is actually measured.'],
'CSAM':  ['C-mode Scanning Acoustic Microscopy', 'pkg', 'Ultrasonic imaging that finds voids and delamination inside a sealed package without destroying it.'],

/* ---------- test ---------- */
'ATE':   ['Automatic Test Equipment', 'test', 'The production tester. Its capability, pin count and cost per hour shape the whole test strategy.'],
'STDF':  ['Standard Test Data Format', 'test', 'The industry format for per-unit test results. The raw material of all yield analysis.'],
'DPPM':  ['Defective Parts Per Million', 'test', 'The escape rate the test flow is designed to achieve. Coverage without a DPPM target is an engineering preference, not a commitment.'],
'Vmin':  ['Minimum operating voltage', 'test', 'The lowest supply at which a part still works. Its distribution across units is a core characterization result.'],
'Fmax':  ['Maximum operating frequency', 'test', 'The highest clock a part sustains at a given voltage and temperature.'],
'Shmoo': ['Shmoo plot', 'test', 'A pass/fail map across two swept variables, usually voltage against frequency. Shows where the part stops working, and so how much margin it has.'],
'TOPS':  ['Tera-Operations Per Second', 'test', 'Throughput measure for an accelerator — 10¹² operations a second.'],
'TOPS/W':['Tera-Operations Per Second per Watt', 'test', 'Efficiency measure. The metric this product class is actually bought on.'],
'INT8':  ['8-bit integer', 'test', 'A low-precision numeric format used for inference. Throughput is quoted per format.'],
'FP8':   ['8-bit floating point', 'test', 'A low-precision format used for training and inference.'],
'MLPerf':['MLPerf benchmark suite', 'test', 'The industry-standard machine-learning benchmark set customers compare parts with.'],

/* ---------- reliability and compliance ---------- */
'HTOL':  ['High Temperature Operating Life', 'qual', 'A thousand hours of powered operation at elevated temperature. The core reliability stress, and the longest fixed item before mass production.'],
'HTS':   ['High Temperature Storage', 'qual', 'Unpowered bake, which exercises diffusion and interface degradation.'],
'THB':   ['Temperature Humidity Bias', 'qual', 'Powered stress in heat and humidity — finds corrosion and moisture-driven failure.'],
'uHAST': ['unbiased Highly Accelerated Stress Test', 'qual', 'Pressurized heat and humidity without bias. Accelerates moisture ingress into the package.'],
'MSL':   ['Moisture Sensitivity Level', 'qual', 'How long a package may sit in ambient air before it must be baked prior to soldering. A poor level forces handling procedures on every customer line.'],
'ESD':   ['Electrostatic Discharge', 'qual', 'A static discharge event the part must survive. Classified by model.'],
'HBM (ESD)':['Human Body Model', 'qual', 'The ESD model representing a person touching a pin. Distinct from HBM the memory — context decides which is meant.'],
'CDM':   ['Charged Device Model', 'qual', 'The ESD model where the package itself is charged and discharges through a pin. Scales with package size, so it usually binds on a large 2.5D part.'],
'JEDEC': ['Joint Electron Device Engineering Council', 'qual', 'The body whose standards define memory interfaces and reliability qualification methods.'],
'AEC':   ['Automotive Electronics Council', 'qual', 'The body defining automotive-grade qualification, stricter than commercial JEDEC.'],
'EMC':   ['Electromagnetic Compatibility', 'qual', 'Regulatory limits on emitted and tolerated interference. A market-access gate.'],
'RoHS':  ['Restriction of Hazardous Substances', 'qual', 'EU restriction on certain materials. Needs a declaration from every component supplier.'],
'REACH': ['Registration, Evaluation, Authorization and Restriction of Chemicals', 'qual', 'The broader EU chemicals regulation, with the same supplier-declaration burden.'],
'FIT':   ['Failures In Time', 'qual', 'Failures per billion device-hours. The unit reliability commitments are written in.'],
'FA':    ['Failure Analysis', 'qual', 'Physically finding out why a part failed. Usually destroys the unit, which matters when there are only a handful.'],

/* ---------- interfaces and memory ---------- */
'HBM':   ['High Bandwidth Memory', 'iface', 'Stacked DRAM placed beside the die on an interposer. Two stacks are assumed here. Also stands for Human Body Model in ESD contexts.'],
'HBM3':  ['High Bandwidth Memory generation 3', 'iface', 'The HBM generation assumed in this template; 3E is its extended-speed revision.'],
'PCIe':  ['Peripheral Component Interconnect Express', 'iface', 'The host interface standard. Compliance is obtained at scheduled plugfests, not on demand.'],
'CXL':   ['Compute Express Link', 'iface', 'A coherent protocol layered on the PCIe physical layer, used for memory and accelerator attachment.'],
'UCIe':  ['Universal Chiplet Interconnect Express', 'iface', 'The standard die-to-die interface for chiplet construction.'],
'D2D':   ['Die-to-Die', 'iface', 'The link between two dies inside one package.'],
'ECC':   ['Error Correcting Code', 'iface', 'Redundancy that detects and repairs memory errors. Untested correction logic is indistinguishable from working correction logic.'],
'GB/s':  ['Gigabytes per second', 'iface', 'Bandwidth unit used for memory and interface targets.'],
'TX/RX': ['Transmit / Receive', 'iface', 'The two directions of a serial link.'],
'BER':   ['Bit Error Rate', 'iface', 'How often a link corrupts a bit. The headline quality number for a high-speed interface.'],
'PSRR':  ['Power Supply Rejection Ratio', 'iface', 'How well an analog block ignores noise on its supply. Sets how much PDN noise a PHY tolerates.'],

/* ---------- data formats and tooling ---------- */
'GDS':   ['Graphic Data System (GDSII)', 'tool', 'The layout database format handed to mask making. OASIS is its modern, smaller replacement.'],
'OASIS': ['Open Artwork System Interchange Standard', 'tool', 'A compact layout format used instead of GDSII for large databases.'],
'LEF':   ['Library Exchange Format', 'tool', 'The abstract physical view of a cell or macro — outline, pins, blockages — used for placement and routing.'],
'.lib':  ['Liberty timing library', 'tool', 'Timing, power and noise characterization of a cell across corners. Missing corners silently limit signoff.'],
'CDL':   ['Circuit Description Language', 'tool', 'The transistor-level netlist used as the reference for LVS.'],
'QRC':   ['Parasitic extraction (Quantus RC)', 'tool', 'Extracting resistance and capacitance from layout so timing reflects real wires.'],
'RLC':   ['Resistance, Inductance, Capacitance', 'tool', 'The passive network form used for package and board models.'],
'CAD':   ['Computer-Aided Design (methodology team)', 'tool', 'The group that owns tool flows, scripts and infrastructure rather than the design itself.'],
'EDA':   ['Electronic Design Automation', 'tool', 'The design-tool industry and its licences — a real capacity constraint during peak implementation.'],
'ODB':   ['ODB++ board database', 'tool', 'A PCB manufacturing data format.'],
'ID':    ['Identifier', 'tool', 'The stable reference used to trace a requirement, activity or deliverable through the program.'],
'AI':    ['Artificial Intelligence', 'tool', 'The product\'s application domain in this template — a training and inference accelerator.'],
'LLM':   ['Large Language Model', 'tool', 'The workload class driving the memory bandwidth and capacity targets assumed here.'],
'ML':    ['Machine Learning', 'tool', 'The broader workload family the product serves.'],
'HPC':   ['High Performance Computing', 'tool', 'The other workload family such parts serve, with different bandwidth and precision needs.'],
/* ---------- remaining terms found in the corpus ---------- */
'GDSII': ['Graphic Data System II', 'tool', 'The full name of the GDS layout format handed to mask making.'],
'VDD':   ['Supply voltage', 'design', 'The positive rail powering a block. "VDD collapse" is a deliberate momentary droop used as an SRAM write assist.'],
'RTD':   ['Resistance Temperature Detector', 'pkg', 'A resistive on-die or in-package temperature sensor. Needs calibration before its reading is an absolute temperature rather than a relative one.'],
'TX':    ['Transmitter', 'iface', 'The driving end of a serial link.'],
'RX':    ['Receiver', 'iface', 'The receiving end of a serial link, including its equalization and clock recovery.'],
'SSO':   ['Simultaneous Switching Output', 'design', 'Many outputs switching at once; the current step they draw is what produces SSN.'],
'BSP':   ['Board Support Package', 'program', 'The minimum software that lets a host boot and talk to the board. Its boundary with the firmware team has to be agreed, not assumed.'],
'HD':    ['High Density', 'process', 'A standard-cell flavor optimized for area rather than speed; HPC is its high-performance counterpart. Process option menus offer both.'],
'HBM3E': ['High Bandwidth Memory 3 Extended', 'iface', 'The extended-speed revision of HBM3.'],
'PPM':   ['Parts Per Million', 'test', 'Rate unit; DPPM is its defective-parts form.'],
/* ---------- remaining terms found in the corpus ---------- */
'GDSII': ['Graphic Data System II', 'tool', 'The full name of the GDS layout format handed to mask making.'],
'VDD':   ['Supply voltage', 'design', 'The positive rail powering a block. "VDD collapse" is a deliberate momentary droop used as an SRAM write assist.'],
'RTD':   ['Resistance Temperature Detector', 'pkg', 'A resistive on-die or in-package temperature sensor. Needs calibration before its reading is an absolute temperature rather than a relative one.'],
'TX':    ['Transmitter', 'iface', 'The driving end of a serial link.'],
'RX':    ['Receiver', 'iface', 'The receiving end of a serial link, including its equalization and clock recovery.'],
'SSO':   ['Simultaneous Switching Output', 'design', 'Many outputs switching at once; the current step they draw is what produces SSN.'],
'BSP':   ['Board Support Package', 'program', 'The minimum software that lets a host boot and talk to the board. Its boundary with the firmware team has to be agreed, not assumed.'],
'HD':    ['High Density', 'process', 'A standard-cell flavor optimized for area rather than speed; HPC is its high-performance counterpart. Process option menus offer both.'],
'HBM3E': ['High Bandwidth Memory 3 Extended', 'iface', 'The extended-speed revision of HBM3.'],
'PPM':   ['Parts Per Million', 'test', 'Rate unit; DPPM is its defective-parts form.'],
};

module.exports = Object.fromEntries(Object.entries(G).map(([k, [full, group, note]]) => [k, { full, group, note }]));
