/* IPR — IP Strategy & Readiness. Ten activities. Stage w4–26 (22w), 47 M/M. */
module.exports = {

'IPR-01': {
  stage:'ipReadiness', window:[0,5], criticalPath:true,
  purpose:[
    'Decompose the product into <b>the IP it actually needs</b>—every block, with its specification, its interfaces and the requirement it traces back to—and publish it as a bill of materials the program can be held to.',
    'An IP-BOM derived from the last program\'s list is the most common way to arrive at the wrong one. What this product needs follows from its requirements and its architecture, and the blocks that differ from last time are exactly the ones with the longest lead times.',
  ],
  steps:[
    {n:1, text:'Requirement-to-IP decomposition against the requirement register', tat:1, lane:'main'},
    {n:2, text:'Block-level IP identification from the architecture sketch', tat:1.5, lane:'main'},
    {n:3, text:'Interface and protocol IP identification', tat:0.75, lane:'par'},
    {n:4, text:'Foundry IP identification — memory compilers, IO, standard cells', tat:0.75, lane:'par'},
    {n:5, text:'Per-IP specification stub — function, performance, interfaces', tat:1.5, lane:'main'},
    {n:6, text:'Bill of materials assembly and traceability check', tat:1, lane:'main'},
  ],
  flowNote:'Step 6\'s traceability check is what separates a list from a bill of materials. An IP that traces to no requirement is an IP nobody needs; a requirement that traces to no IP is a gap nobody has staffed.',
  consumes:[
    'Requirement register from DEF-01',
    'Architecture sketch and block list direction from ARCH-02',
    'Interface selections from ARCH-04',
    'Previous-program IP list as a starting reference',
    'Foundry IP catalogue for the selected node',
  ],
  produces:[
    'Requirement-to-IP decomposition',
    'Block-level IP list',
    'Interface and protocol IP list',
    'Interface and foundry IP identification',
    'Per-IP specification stubs',
    'Requirement-to-IP traceability matrix',
    'IP bill of materials, block by block',
    'Traceability gap list',
  ],
  producedBy:[1,2,3,4,5,6,6,6],
  rel:[
    {id:'IPR-D1', rel:'produces', text:'<b>IP bill of materials with make / buy / reuse decision per block.</b> The bill half of the deliverable; <code>IPR-03</code> adds the decision against each line.'},
    {id:'IPR-D3', rel:'feeds', text:'<b>IP readiness report.</b> Readiness is assessed per line of this bill, so the bill\'s completeness bounds the report\'s.'},
  ],
  risks:[
    '<b>Bill inherited from the previous program.</b> The blocks that differ are the ones with the longest lead times, and inheriting the list hides exactly those.',
    '<b>Foundry IP omitted.</b> Memory compilers, IO and standard cells are IP with licences and lead times, and a bill that lists only third-party blocks understates the procurement.',
    '<b>Specification stubs too thin to evaluate against.</b> A vendor cannot be assessed against "a PCIe PHY"; the stub has to carry performance, interface and process detail.',
    '<b>Traceability skipped.</b> Without it, blocks appear because someone assumed them and requirements go unserved because nobody noticed.',
    '<b>Bill frozen before architecture settles.</b> A bill written before <code>ARCH-02</code> partitions will miss the die-to-die interface entirely if the part turns out to be a chiplet.',
  ],
  roles:[
    {r:'IP strategist', d:'Owns the bill of materials and its traceability'},
    {r:'Chief architect', d:'Confirms the block list and its interfaces'},
    {r:'Interface architect', d:'Protocol and PHY IP identification'},
    {r:'CAD and library lead', d:'Foundry IP — compilers, IO, cells'},
    {r:'Program manager', d:'Carries the bill into procurement planning'},
  ],
  effort:[['Requirement decomposition',1.5], ['Block and interface identification',1.5], ['Specification stubs',1], ['Bill assembly and traceability',1]],
  entry:[
    'Requirement register available at v0.9 from DEF-01',
    'Architecture direction known well enough to name blocks',
    'Foundry IP catalogue accessible',
  ],
  exit:[
    'Every IP traces to a requirement, and every requirement to an IP or a gap',
    'Foundry IP included alongside third-party and internal blocks',
    'Specification stubs detailed enough to evaluate a vendor against',
  ],
  dependsOn:['DEF-01','ARCH-02','ARCH-04'],
  dependsNote:null,
  feedsInto:['IPR-02','IPR-03','IPR-04','TECH-08','PDK-04'],
  measuredBy:[
    'IP lines traceable to a requirement',
    'Requirements with no IP against them',
    'Bill changes after the architecture freeze',
  ],
},

'IPR-02': {
  stage:'ipReadiness', window:[1,5], criticalPath:false,
  purpose:[
    'Audit what the organization <b>already owns and can actually reuse on this node</b>—not what it owns in general, which is a different and much longer list.',
    'Reuse is where the schedule is won, and it is also where optimism concentrates. A block proven on the previous node is not available on this one until it has been ported, re-characterized and re-verified, and that work is a project with a duration. The audit\'s job is to separate genuine reuse from hopeful reuse.',
  ],
  steps:[
    {n:1, text:'Internal IP inventory against the bill of materials', tat:0.75, lane:'main'},
    {n:2, text:'Node availability check per internal block', tat:1.25, lane:'main'},
    {n:3, text:'Collateral completeness audit — views, testbenches, documentation', tat:1, lane:'par'},
    {n:4, text:'Maintenance and ownership status per block', tat:0.75, lane:'par'},
    {n:5, text:'Reuse classification — direct, port required, or rebuild', tat:2, lane:'main'},
  ],
  flowNote:'Step 4 asks who still maintains each block, and the answer is often nobody. An unmaintained block is technically reusable and practically a rebuild, because the first bug found has no owner.',
  consumes:[
    'IP bill of materials from IPR-01',
    'Internal IP catalogue and repositories',
    'Previous-program silicon results per block',
    'Node and flavor selection from TECH',
    'Team ownership records',
  ],
  produces:[
    'Internal IP inventory mapped to the bill',
    'Node availability finding per block',
    'Collateral completeness audit',
    'Ownership and maintenance status',
    'Reuse classification per block',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'IPR-D1', rel:'feeds', text:'<b>IP bill of materials.</b> Reuse classification is one of the three answers the make / buy / reuse column can take, and it is decided here.'},
    {id:'IPR-D3', rel:'feeds', text:'<b>IP readiness report.</b> An internal block on the wrong node is exactly as unready as an external one, and belongs in the same report.'},
  ],
  risks:[
    '<b>Reuse claimed on the previous node.</b> Availability is node-specific; a block not yet ported is a porting project, not a reuse.',
    '<b>Collateral assumed complete.</b> Missing multi-corner .lib files or an absent testbench turns reuse into re-characterization and re-verification.',
    '<b>Unmaintained blocks counted as reuse.</b> A block with no owner has no one to fix its first bug, and the fix lands on the integration team.',
    '<b>Audit run on the catalogue rather than the repository.</b> Catalogues describe intent; repositories contain what actually exists.',
    '<b>Silicon history ignored.</b> A block that shipped with an erratum is reusable with that erratum, and the erratum belongs in the audit.',
  ],
  roles:[
    {r:'IP strategist', d:'Owns the audit and the reuse classification'},
    {r:'IP librarian', d:'Inventory, repositories and collateral'},
    {r:'Design leads', d:'Ownership and maintenance status per block'},
    {r:'Verification liaison', d:'Testbench and DV collateral completeness'},
    {r:'Silicon validation liaison', d:'Errata and known issues from previous silicon'},
  ],
  effort:[['Node availability assessment',1], ['Inventory against the bill',0.75], ['Collateral audit',0.75], ['Reuse classification',0.5]],
  entry:[
    'Bill of materials available from IPR-01',
    'Access to internal IP repositories',
    'Node selected so availability can be assessed',
  ],
  exit:[
    'Every internal block classified as direct reuse, port, or rebuild',
    'Collateral gaps listed per block, not assumed away',
    'Blocks with no maintainer flagged as such',
  ],
  dependsOn:['IPR-01','TECH-01'],
  dependsNote:null,
  feedsInto:['IPR-03','IPR-08','ARCH-06'],
  measuredBy:[
    'Blocks classified as direct reuse against those later ported',
    'Collateral gaps found here against those found at integration',
    'Blocks with a named maintainer',
  ],
},

'IPR-03': {
  stage:'ipReadiness', window:[5,10], criticalPath:true,
  purpose:[
    'Take each line of the bill and decide, with a reason, whether it is <b>made, bought or reused</b>—and record what the rejected options would have cost.',
    'Make/buy is a schedule decision more than a cost one. Building a PHY internally is cheaper on paper and costs nine months in <code>AMS-03</code>; buying it costs a license and a vendor dependency. Neither is wrong, and the program only gets to argue about it once.',
  ],
  steps:[
    {n:1, text:'Decision criteria definition — cost, schedule, differentiation, risk', tat:0.75, lane:'main'},
    {n:2, text:'Differentiation screen — which blocks are the product\'s own value', tat:1, lane:'main'},
    {n:3, text:'Internal capacity check against the make candidates', tat:1, lane:'par'},
    {n:4, text:'Cost and schedule comparison per line', tat:1.5, lane:'main'},
    {n:5, text:'Foundry-specific versus portable IP consideration', tat:0.75, lane:'par'},
    {n:6, text:'Decision per line and record of rejected options', tat:1.75, lane:'main'},
  ],
  flowNote:'Step 3 is the check that changes answers. A make decision assumes engineers who are also assigned to the custom SRAM and the PLL; capacity, not capability, is what usually decides.',
  consumes:[
    'IP bill of materials from IPR-01',
    'Reuse classification from IPR-02',
    'AMS capacity and schedule from the program plan',
    'Sourcing strategy direction from TECH-08',
    'Cost model assumptions from DEF-04',
  ],
  produces:[
    'Decision criteria and their weighting',
    'Differentiation screen result',
    'Internal capacity commitment for make decisions',
    'Cost and schedule comparison per line',
    'Foundry-specific versus portable IP assessment',
    'Make / buy / reuse decision per line',
    'Rejected option record with cost and schedule',
  ],
  producedBy:[1,2,3,4,5,6,6],
  rel:[
    {id:'IPR-D1', rel:'produces', text:'<b>IP bill of materials with make / buy / reuse decision per block.</b> The decision half of the deliverable, with the rejected options priced rather than forgotten.'},
    {id:'IPR-D7', rel:'feeds', text:'<b>IP risk register.</b> Every buy decision creates a vendor dependency and every make decision creates a capacity dependency; both belong on the register.'},
  ],
  risks:[
    '<b>Make decided on capability rather than capacity.</b> The team can build it; whether it can build it alongside everything else it is already committed to is the real question.',
    '<b>Differentiating IP bought.</b> Buying the block that is the product\'s actual advantage buys a product the competitor can buy too.',
    '<b>Commodity IP built.</b> Building a standard interface consumes analog engineers who are the program\'s scarcest resource, for no differentiation.',
    '<b>Foundry-specific IP chosen without reference to sourcing strategy.</b> It forecloses the migration option <code>TECH-08</code> was pricing, and usually after that study concludes.',
    '<b>Decisions recorded without the alternatives.</b> Every setback reopens a decision whose reasoning nobody can reconstruct.',
  ],
  roles:[
    {r:'IP strategist', d:'Owns the decisions and their record'},
    {r:'Chief architect', d:'Differentiation screen — what is the product\'s own value'},
    {r:'AMS lead', d:'Internal capacity for make candidates'},
    {r:'Procurement lead', d:'Buy-side cost and vendor landscape'},
    {r:'Program manager', d:'Schedule impact and capacity commitment'},
  ],
  effort:[['Cost and schedule comparison',1.5], ['Differentiation screen',1], ['Capacity check',0.75], ['Decision record',0.75]],
  entry:[
    'Bill of materials complete from IPR-01',
    'Reuse classification available from IPR-02',
    'AMS capacity known from the program plan',
  ],
  exit:[
    'Every line decided with a criterion attached, not by default',
    'Make decisions backed by a named capacity commitment',
    'Rejected options priced and recorded',
  ],
  dependsOn:['IPR-01','IPR-02','TECH-08'],
  dependsNote:null,
  feedsInto:['IPR-04','IPR-07','IPR-08','AMS-01','AMS-03'],
  measuredBy:[
    'Lines decided against lines in the bill',
    'Make decisions with a capacity commitment behind them',
    'Decisions reopened after IP Plan Freeze',
  ],
},

'IPR-04': {
  stage:'ipReadiness', window:[6,15], criticalPath:true,
  purpose:[
    'Run a real evaluation of the vendors behind every buy decision—<b>technical capability, deliverable quality, support model and track record</b>—rather than choosing from a datasheet.',
    'A PHY vendor is a nine-month dependency. What matters is less the block\'s peak specification than whether the deliverables arrive complete, whether the support engineer answers, and whether the last three customers taped out on schedule. None of that is on the datasheet.',
  ],
  steps:[
    {n:1, text:'Vendor long-list per IP line', tat:0.75, lane:'main'},
    {n:2, text:'RFI issue and response collection', tat:2, lane:'main'},
    {n:3, text:'Technical evaluation against the specification stubs', tat:2.5, lane:'main'},
    {n:4, text:'Reference customer checks and tapeout track record', tat:1.5, lane:'par'},
    {n:5, text:'Support model and escalation path assessment', tat:1, lane:'par'},
    {n:6, text:'RFQ issue and commercial comparison', tat:1.75, lane:'par'},
    {n:7, text:'Evaluation matrix and vendor selection', tat:3.75, lane:'main'},
  ],
  flowNote:'Step 4 is the step most often skipped and the one that predicts the outcome best. A vendor\'s last three customers know whether the deliverables arrived complete and on time, and they will usually say.',
  consumes:[
    'Buy decisions from IPR-03',
    'Specification stubs from IPR-01',
    'Node and process option from TECH-02',
    'Interface requirements from ARCH-04',
    'Vendor landscape and previous-program experience',
  ],
  produces:[
    'Vendor long-list per IP line',
    'RFI responses per vendor',
    'Technical evaluation against the stubs',
    'Reference customer findings',
    'Support model and escalation path assessment',
    'RFI and RFQ responses',
    'Vendor evaluation matrix and selection record',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'IPR-D2', rel:'produces', text:'<b>Vendor evaluation matrix and selection record.</b> This activity is the deliverable, and the matrix is what a later dispute is settled against.'},
    {id:'IPR-D5', rel:'feeds', text:'<b>Executed licences and POs.</b> Selection precedes negotiation; <code>IPR-07</code> contracts with whoever this activity chose.'},
    {id:'IPR-D3', rel:'feeds', text:'<b>IP readiness report.</b> Vendor track record is part of an IP\'s maturity rating, not separate from it.'},
  ],
  risks:[
    '<b>Evaluation from the datasheet.</b> Peak specifications are marketing; deliverable completeness and support responsiveness are what the integration actually depends on.',
    '<b>Reference checks skipped.</b> The vendor\'s previous customers know what the program is about to find out, and asking costs an hour.',
    '<b>Single vendor evaluated.</b> An evaluation with one candidate is a justification, and the commercial position that follows is weak.',
    '<b>Support model unexamined.</b> A block with no named support engineer becomes the integration team\'s problem the first time it misbehaves.',
    '<b>Node-specific capability assumed from a different node.</b> A PHY proven at the previous node is not the same product; <code>IPR-05</code> is where that is confirmed.',
  ],
  roles:[
    {r:'IP strategist', d:'Owns the evaluation and the selection'},
    {r:'Technical evaluators', d:'Assessment against the specification stubs'},
    {r:'Procurement lead', d:'RFQ, commercial comparison and terms'},
    {r:'Integration lead', d:'Deliverable completeness and support expectations'},
    {r:'Program manager', d:'Reference checks on schedule performance'},
  ],
  effort:[['Technical evaluation',3.5], ['RFI and RFQ handling',2], ['Reference checks',1.5], ['Evaluation matrix and selection',2], ['Support model assessment',1]],
  entry:[
    'Buy decisions made in IPR-03',
    'Specification stubs detailed enough to evaluate against',
    'NDAs in place with candidate vendors',
  ],
  exit:[
    'At least two candidates evaluated per significant line',
    'Reference customers contacted for the critical blocks',
    'Selection recorded against the matrix, with support model assessed',
  ],
  dependsOn:['IPR-01','IPR-03','ARCH-04'],
  dependsNote:null,
  feedsInto:['IPR-05','IPR-06','IPR-07','AMS-03'],
  measuredBy:[
    'Candidates evaluated per line',
    'Reference checks completed on critical blocks',
    'Vendor changes after selection',
  ],
},

'IPR-05': {
  stage:'ipReadiness', window:[8,15], criticalPath:true,
  purpose:[
    'Establish, for each bought and reused block, <b>whether it has actually run in silicon on this node and this process option</b>—and if not, what it would take to get it there.',
    '"Silicon-proven" is the most abused phrase in IP procurement. It can mean proven on a different node, on a different process option, at a different speed grade, or in a test chip that was never characterized. This activity replaces the phrase with a fact, and the fact is what the integration schedule should be built on.',
  ],
  steps:[
    {n:1, text:'Proven-status definition — what the program will accept as evidence', tat:0.75, lane:'main'},
    {n:2, text:'Evidence request per block — test chip, production part, characterization data', tat:1.5, lane:'main'},
    {n:3, text:'Node and process option match verification', tat:1.5, lane:'main'},
    {n:4, text:'Speed grade and operating condition match check', tat:1, lane:'par'},
    {n:5, text:'Errata and known-issue review per block', tat:1, lane:'par'},
    {n:6, text:'Maturity level assignment per block', tat:1.25, lane:'main'},
    {n:7, text:'Readiness report and gap list', tat:2, lane:'main'},
  ],
  flowNote:'Step 1 is not bureaucracy. Without an agreed evidence standard, every vendor\'s claim is accepted at its own definition, and the readiness report becomes a collection of adjectives.',
  consumes:[
    'Vendor selections from IPR-04',
    'Reuse classification from IPR-02',
    'Node and process option from TECH-02',
    'Vendor silicon evidence and characterization data',
    'Errata from previous programs and vendor disclosures',
  ],
  produces:[
    'Evidence standard the program accepts',
    'Collected silicon evidence per block',
    'Silicon evidence per block, with node and option match',
    'Speed grade and condition match findings',
    'Errata and known-issue summary',
    'Maturity level per block and a gap list',
    'IP readiness report with its gap list',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'IPR-D3', rel:'produces', text:'<b>IP readiness report—silicon-proven status and maturity level per IP.</b> This activity is the deliverable, and it is the one that replaces a claim with a fact.'},
    {id:'IPR-D7', rel:'feeds', text:'<b>IP risk register.</b> Every block below the maturity bar is a risk with a name, an owner and a mitigation.'},
    {id:'IPR-D6', rel:'feeds', text:'<b>IP delivery schedule.</b> An unproven block needs a hardening window, and the window has to be in the schedule.'},
  ],
  risks:[
    '<b>Vendor claim accepted at the vendor\'s definition.</b> Without an evidence standard, "silicon-proven" means whatever is most convenient.',
    '<b>Node matched, process option not.</b> The same node with a different flavor sheet is a different library, different rules and often a different PHY.',
    '<b>Errata not requested.</b> Every silicon-proven block has errata; a block presented with none has either not been characterized or is not being fully disclosed.',
    '<b>Assessment done after the license is signed.</b> The finding has no commercial consequence once the PO is placed, and the leverage is gone.',
    '<b>Speed grade ignored.</b> A PHY proven at a lower rate on the same node is an engineering project, not a proven block.',
  ],
  roles:[
    {r:'IP strategist', d:'Owns the evidence standard and the readiness report'},
    {r:'Technical evaluators', d:'Evidence assessment per block'},
    {r:'AMS lead', d:'PHY and analog block evidence interpretation'},
    {r:'Silicon validation liaison', d:'Errata review and characterization data reading'},
    {r:'Procurement lead', d:'Uses findings as negotiating position before signature'},
  ],
  effort:[['Evidence assessment',2.5], ['Node and option verification',1.5], ['Errata review',1], ['Maturity assignment and report',1]],
  entry:[
    'Vendor selections available from IPR-04',
    'Node and process option fixed by TECH-02',
    'Vendor NDAs allow access to characterization data',
  ],
  exit:[
    'Every block carries a maturity level backed by evidence, not by claim',
    'Node and process option match verified per block',
    'Findings available before licences are signed in IPR-07',
  ],
  dependsOn:['IPR-02','IPR-04','TECH-02'],
  dependsNote:null,
  feedsInto:['IPR-06','IPR-07','IPR-08','IPR-10','TC-02','RTL-03'],
  measuredBy:[
    'Blocks with evidence against blocks with a claim',
    'Node and option mismatches found',
    'Errata disclosed against errata found later',
  ],
},

'IPR-06': {
  stage:'ipReadiness', window:[11,18], criticalPath:false,
  purpose:[
    'Define <b>exactly what a complete IP delivery contains</b>—every view, model, testbench and document—and get that list agreed before it becomes a contractual obligation.',
    'Most IP delivery disputes are not about whether the block works; they are about whether a delivery counted as a delivery. A block that arrives without multi-corner timing views or without its verification collateral has arrived in a form the program cannot integrate, and the argument that follows is unwinnable if the checklist was never agreed.',
  ],
  steps:[
    {n:1, text:'Deliverable checklist definition per IP class', tat:1, lane:'main'},
    {n:2, text:'View and model requirements against the tool matrix', tat:1.5, lane:'main'},
    {n:3, text:'Verification collateral requirements with DV', tat:1, lane:'par'},
    {n:4, text:'Documentation, errata and integration guide requirements', tat:1, lane:'par'},
    {n:5, text:'Acceptance criteria and incoming inspection procedure', tat:1.5, lane:'main'},
    {n:6, text:'Checklist agreement with each vendor', tat:2, lane:'par'},
    {n:7, text:'Checklist publication and handoff to procurement', tat:3, lane:'main'},
  ],
  flowNote:'Step 5 turns the checklist into something enforceable. A list of expected files is a wish; an acceptance procedure that says what is checked, by whom, and what happens when it fails is a term.',
  consumes:[
    'Vendor selections from IPR-04',
    'Tool matrix and view requirements from PDK-08',
    'Verification methodology needs from DV-01',
    'Integration requirements from RTL-03',
    'Previous-program IP delivery disputes',
  ],
  produces:[
    'Deliverable checklist per IP class',
    'View and model requirement list',
    'Verification collateral requirements',
    'Documentation, errata and integration guide requirements',
    'Acceptance criteria and incoming inspection procedure',
    'Vendor-agreed checklists',
    'Published checklist with procurement handoff',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'IPR-D4', rel:'produces', text:'<b>IP deliverable acceptance checklist.</b> This activity is the deliverable, and its value is entirely in being agreed before the PO rather than after the delivery.'},
    {id:'IPR-D5', rel:'feeds', text:'<b>Executed licences and POs.</b> The checklist becomes a contractual schedule, which is the only form in which it is enforceable.'},
  ],
  risks:[
    '<b>Checklist agreed after the PO.</b> Once the commercial terms are closed, a missing view is a favor rather than an obligation.',
    '<b>Views specified without the tool matrix.</b> A .lib set that does not cover the signoff corners in <code>PDK-11</code> is incomplete in a way nobody notices until closure.',
    '<b>Verification collateral omitted.</b> A block delivered without its testbench has to be verified from scratch, and that effort was never in the DV plan.',
    '<b>No incoming inspection.</b> Deliverables accepted without a check are found incomplete weeks later, when the vendor\'s engineer has moved on.',
    '<b>One checklist for all IP classes.</b> A memory compiler, a PHY and a controller have genuinely different deliverable sets, and a single list serves none of them.',
  ],
  roles:[
    {r:'IP integration lead', d:'Owns the checklist and the acceptance procedure'},
    {r:'CAD methodology engineer', d:'View and model requirements against the tools'},
    {r:'Verification lead', d:'Collateral requirements and what DV will need'},
    {r:'Procurement lead', d:'Makes the checklist a contractual schedule'},
    {r:'Vendor technical contacts', d:'Agree the list is deliverable as written'},
  ],
  effort:[['Checklist and view requirements',2], ['Acceptance criteria and inspection',1.5], ['Verification collateral requirements',1], ['Vendor agreement and publication',1.5]],
  entry:[
    'Vendor selections made in IPR-04',
    'Tool matrix available from PDK-08',
    'Signoff corner intent known from PDK-11',
  ],
  exit:[
    'Checklist agreed with each vendor before the PO is placed',
    'Acceptance procedure names who checks what, and when',
    'Views cover the signoff corners the program will actually run',
  ],
  dependsOn:['IPR-04','PDK-08','DV-01'],
  dependsNote:null,
  feedsInto:['IPR-07','IPR-09','RTL-03','PD-02'],
  measuredBy:[
    'Vendors with an agreed checklist before PO',
    'Deliveries rejected at incoming inspection',
    'Missing views discovered after acceptance',
  ],
},

'IPR-07': {
  stage:'ipReadiness', window:[10,22], criticalPath:true,
  purpose:[
    'Turn selections into <b>executed licences and purchase orders with committed delivery dates</b>, including the deliverable checklist as a contractual schedule.',
    'Twelve weeks for 5 M/M—this is the stage\'s longest activity and among its smallest in effort, because the elapsed time belongs to two legal departments and a procurement process. It is on the critical path regardless: nothing arrives until it executes, and <code>RTL-03</code> has integration windows that assume it did.',
  ],
  steps:[
    {n:1, text:'Commercial terms definition per IP line', tat:1.5, lane:'main'},
    {n:2, text:'Licence model negotiation — per-use, per-project, royalty', tat:2.5, lane:'main'},
    {n:3, text:'Delivery date commitment and milestone schedule', tat:2, lane:'main'},
    {n:4, text:'Deliverable checklist attached as a contractual schedule', tat:1, lane:'par'},
    {n:5, text:'Support, maintenance and escalation terms', tat:1.5, lane:'par'},
    {n:6, text:'Liability, indemnity and IP warranty terms', tat:1.5, lane:'par'},
    {n:7, text:'Legal redline cycles', tat:3.5, lane:'main'},
    {n:8, text:'Execution, PO issue and distribution', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 3 is the one the program cares about and the one commercial negotiation treats as secondary. A license with excellent terms and no committed delivery date has bought a block that arrives when the vendor is ready.',
  consumes:[
    'Vendor selections from IPR-04',
    'Readiness findings from IPR-05 as negotiating position',
    'Deliverable checklists from IPR-06',
    'Integration window requirements from the program schedule',
    'Corporate legal templates and positions',
  ],
  produces:[
    'Commercial terms per IP line',
    'Agreed licence model per block',
    'Executed licences with delivery commitments',
    'Deliverable checklist as a contractual schedule',
    'Support and escalation terms',
    'Agreed liability, indemnity and warranty terms',
    'Redline history with resolved positions',
    'Purchase orders issued',
    'Distribution record of what has been licensed to whom',
  ],
  producedBy:[1,2,3,4,5,6,7,8,8],
  rel:[
    {id:'IPR-D5', rel:'produces', text:'<b>Executed licences and POs with committed delivery dates.</b> This activity is the deliverable, and the committed date is the part the schedule depends on.'},
    {id:'IPR-D6', rel:'feeds', text:'<b>IP delivery schedule.</b> Committed dates are what <code>IPR-09</code> aligns against the integration windows.'},
    {id:'IPR-D4', rel:'gates', text:'<b>IP deliverable acceptance checklist.</b> The checklist only has force once it is attached to an executed agreement.'},
  ],
  risks:[
    '<b>Licence executed without a committed delivery date.</b> The block then arrives when the vendor is ready, and the integration window absorbs the difference.',
    '<b>Readiness findings not used in negotiation.</b> A block that is not proven on the node is a commercial position; signing before <code>IPR-05</code> reports discards it.',
    '<b>Checklist not attached.</b> An agreed checklist outside the contract is an understanding, and understandings do not survive a disputed delivery.',
    '<b>Redline duration underestimated.</b> Two legal departments take longer than either forecasts, and the program\'s plan should assume the longer figure.',
    '<b>Support terms omitted.</b> A block with no support commitment becomes unsupported precisely when integration needs help.',
  ],
  roles:[
    {r:'Procurement lead', d:'Owns the negotiation, the POs and the terms'},
    {r:'Legal counsel', d:'Licence structure, liability and redlines'},
    {r:'IP strategist', d:'Technical terms and the deliverable schedule'},
    {r:'Program manager', d:'Delivery dates against integration windows'},
    {r:'Finance partner', d:'Licence model, royalty exposure and budget'},
  ],
  effort:[['Negotiation support',2], ['Terms and license model',1.5], ['Delivery commitment',0.75], ['Execution and distribution',0.75]],
  entry:[
    'Vendor selections final from IPR-04',
    'Readiness findings available from IPR-05',
    'Deliverable checklists agreed in IPR-06',
  ],
  exit:[
    'Every license carries a committed delivery date, not an intention',
    'Deliverable checklist attached as a contractual schedule',
    'Access distributed and tracked to the teams that need it',
  ],
  dependsOn:['IPR-04','IPR-05','IPR-06','TECH-06'],
  dependsNote:null,
  feedsInto:['IPR-09','RTL-03','AMS-03','PD-02'],
  measuredBy:[
    'Licences with a committed delivery date',
    'Weeks from selection to execution',
    'Deliveries received against the committed date',
  ],
},

'IPR-08': {
  stage:'ipReadiness', window:[14,19], criticalPath:false,
  purpose:[
    'For every block that is <b>not proven on this node</b>, scope the work that gets it there—porting, hardening, re-characterization, re-verification—and put it in the schedule as a project with an owner.',
    'Unproven IP does not become proven by being licensed. Someone ports it, re-characterizes it at the program\'s corners and re-verifies it, and that someone is either the vendor on a schedule the program does not control, or the program\'s own engineers who are already committed elsewhere.',
  ],
  steps:[
    {n:1, text:'Unproven block list from the readiness report', tat:0.5, lane:'main'},
    {n:2, text:'Porting scope per block — layout, characterization, verification', tat:1.5, lane:'main'},
    {n:3, text:'Vendor versus internal execution decision per block', tat:1, lane:'par'},
    {n:4, text:'Effort and duration estimate per block', tat:1.25, lane:'main'},
    {n:5, text:'Dependency mapping against the integration windows', tat:0.75, lane:'par'},
    {n:6, text:'Hardening plan with owners and dates', tat:1.75, lane:'main'},
  ],
  flowNote:'Step 3 decides who absorbs the risk. Vendor-executed hardening is on a schedule the program cannot influence; internally executed hardening competes with <code>AMS-03</code> for the same analog engineers. Both are real answers and neither is free.',
  consumes:[
    'Readiness report and gap list from IPR-05',
    'Reuse classification from IPR-02',
    'Make / buy decisions from IPR-03',
    'AMS capacity from the program plan',
    'Integration window requirements from RTL and PD',
  ],
  produces:[
    'Unproven block list',
    'Unproven block list with porting scope',
    'Execution decision per block — vendor or internal',
    'Effort and duration estimates',
    'Dependency map against integration windows',
    'Hardening plan with owners and dates',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'IPR-D3', rel:'feeds', text:'<b>IP readiness report.</b> A block\'s maturity level is only actionable alongside the plan that raises it, and this activity supplies the plan.'},
    {id:'IPR-D6', rel:'feeds', text:'<b>IP delivery schedule.</b> A hardening window is part of the delivery date, and omitting it produces a schedule that cannot hold.'},
  ],
  risks:[
    '<b>Hardening treated as vendor overhead.</b> It is a project with a duration; leaving it off the plan means the block arrives on a date nobody derived.',
    '<b>Internal execution assumed available.</b> The engineers who would port a PHY are the engineers building the PLL and the custom array, and they cannot do all three.',
    '<b>Re-verification omitted from scope.</b> Porting changes the block; the verification collateral has to be re-run, and that effort belongs in the DV plan.',
    '<b>Characterization corners not matched to the program\'s.</b> A block re-characterized at the vendor\'s corners still cannot be signed off at the program\'s.',
    '<b>Plan without dates.</b> A hardening plan with owners and no dates does not integrate with the program schedule and is therefore not tracked.',
  ],
  roles:[
    {r:'IP strategist', d:'Owns the hardening plan'},
    {r:'AMS lead', d:'Internal capacity and analog porting scope'},
    {r:'Verification lead', d:'Re-verification scope and collateral'},
    {r:'Vendor technical contacts', d:'Vendor-executed hardening scope and schedule'},
    {r:'Program manager', d:'Dates, owners and integration window alignment'},
  ],
  effort:[['Porting scope definition',1.5], ['Effort and duration estimation',1], ['Execution decision',0.75], ['Hardening plan',0.75]],
  entry:[
    'Readiness report available from IPR-05',
    'AMS capacity known from the program plan',
    'Integration windows known from RTL and PD planning',
  ],
  exit:[
    'Every unproven block has a scoped plan with an owner and a date',
    'Internal execution decisions backed by a capacity commitment',
    'Re-verification scope included, not assumed',
  ],
  dependsOn:['IPR-02','IPR-03','IPR-05'],
  dependsNote:null,
  feedsInto:['IPR-09','IPR-10','AMS-03','DV-02'],
  measuredBy:[
    'Unproven blocks with a dated plan',
    'Internal hardening committed against AMS capacity',
    'Hardening completed against plan',
  ],
},

'IPR-09': {
  stage:'ipReadiness', window:[17,21], criticalPath:true,
  purpose:[
    'Line up <b>every IP delivery date against the window that actually needs it</b>—RTL integration, synthesis, floorplan—and surface the mismatches while they can still be fixed.',
    'An IP schedule is only meaningful against the design schedule. A PHY delivered in week 40 is early for RTL and late for the floorplan, because <code>PD-02</code> needs the abstract long before <code>RTL-03</code> needs the model. Alignment means matching each deliverable to the window that consumes it, not the block to a date.',
  ],
  steps:[
    {n:1, text:'Integration window extraction — what each stage needs and when', tat:0.75, lane:'main'},
    {n:2, text:'Committed delivery date collection per block and per deliverable', tat:1, lane:'main'},
    {n:3, text:'Deliverable-level alignment — abstracts before models before collateral', tat:1.25, lane:'main'},
    {n:4, text:'Hardening plan overlay from IPR-08', tat:0.75, lane:'par'},
    {n:5, text:'Mismatch identification and escalation list', tat:1, lane:'main'},
    {n:6, text:'Schedule integration into the program plan', tat:0.75, lane:'par'},
  ],
  flowNote:'Step 3 is where the useful detail lives. Vendors quote one date for a block; the design needs the LEF abstract for floorplan months before it needs the multi-corner .lib for signoff, and asking for the abstract early is often free.',
  consumes:[
    'Committed delivery dates from IPR-07',
    'Hardening plan from IPR-08',
    'RTL integration windows from the program schedule',
    'Floorplan and macro placement needs from PD planning',
    'Deliverable checklist from IPR-06',
  ],
  produces:[
    'Integration window map per consuming stage',
    'Committed delivery dates per block and deliverable',
    'Deliverable-level delivery schedule',
    'Hardening overlay',
    'Mismatch and escalation list',
    'IP schedule folded into the program plan',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'IPR-D6', rel:'produces', text:'<b>IP delivery schedule folded into the program plan.</b> This activity is the deliverable, and "folded in" is the operative part—a separate IP schedule is one nobody tracks.'},
    {id:'IPR-D7', rel:'feeds', text:'<b>IP risk register.</b> Every mismatch that cannot be closed becomes a tracked risk with a mitigation.'},
  ],
  risks:[
    '<b>Block-level dates instead of deliverable-level.</b> One date per block hides that the abstract is needed months before the model, and the earlier need is the binding one.',
    '<b>IP schedule maintained separately.</b> A schedule outside the program plan is not reviewed at program reviews and drifts unnoticed.',
    '<b>Mismatches recorded without escalation.</b> A known gap with no owner and no escalation is a gap that is discovered again at integration.',
    '<b>Hardening overlay omitted.</b> Delivery dates for unproven blocks are meaningless without the porting window that follows them.',
    '<b>Floorplan needs underestimated.</b> Physical design needs abstracts and blockages very early; planning against RTL\'s needs alone produces a late floorplan.',
  ],
  roles:[
    {r:'Program manager', d:'Owns the alignment and the escalation list'},
    {r:'IP strategist', d:'Deliverable-level requirements per block'},
    {r:'RTL integration lead', d:'Integration window requirements'},
    {r:'Physical design lead', d:'Abstract and macro availability needs'},
    {r:'Procurement lead', d:'Escalation with vendors on mismatches'},
  ],
  effort:[['Deliverable-level alignment',0.75], ['Window extraction and date collection',0.5], ['Mismatch identification',0.5], ['Schedule integration',0.25]],
  entry:[
    'Committed dates available from IPR-07',
    'Hardening plan available from IPR-08',
    'Integration windows known from the program schedule',
  ],
  exit:[
    'Alignment done per deliverable, not per block',
    'Every mismatch has an owner and an escalation path',
    'IP schedule visible inside the program plan, not beside it',
  ],
  dependsOn:['IPR-06','IPR-07','IPR-08','DEF-08'],
  dependsNote:null,
  feedsInto:['RTL-03','RTL-09','PD-02','PD-04'],
  measuredBy:[
    'Deliverables aligned to a consuming window',
    'Mismatches closed against those raised',
    'IP deliveries late against the window that needed them',
  ],
},

'IPR-10': {
  stage:'ipReadiness', window:[18,22], criticalPath:false,
  purpose:[
    'Rate every IP line for <b>maturity and supply risk</b>, and decide where a contingency is worth having—a second source, an internal fallback, or an accepted exposure with a trigger.',
    'Some risk here is unavoidable and pretending otherwise is what makes it dangerous. The point is not to eliminate single-vendor dependencies but to know which ones would stop the program, and to have decided in advance what would be done about each.',
  ],
  steps:[
    {n:1, text:'Risk rating per IP line — maturity, vendor, schedule, supply', tat:1, lane:'main'},
    {n:2, text:'Critical dependency identification — which failures stop the program', tat:1, lane:'main'},
    {n:3, text:'Second-source viability per critical block', tat:0.75, lane:'par'},
    {n:4, text:'Internal fallback option assessment', tat:0.75, lane:'par'},
    {n:5, text:'Contingency decision and trigger definition per critical block', tat:2, lane:'main'},
  ],
  flowNote:'Step 5 defines triggers, not intentions. "We would build it internally if the vendor slipped" is worthless without the date at which that decision has to be taken to still be executable.',
  consumes:[
    'Readiness report and maturity levels from IPR-05',
    'Hardening plan from IPR-08',
    'Delivery schedule and mismatches from IPR-09',
    'Vendor evaluation matrix from IPR-04',
    'Sourcing strategy from TECH-08',
  ],
  produces:[
    'Risk rating per IP line',
    'Critical dependency list',
    'Second-source viability findings',
    'Internal fallback assessment',
    'Contingency plan with triggers and decision dates',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'IPR-D7', rel:'produces', text:'<b>IP risk register and contingency plan.</b> This activity is the deliverable, and the triggers are what make it a plan rather than a list.'},
    {id:'IPR-D3', rel:'feeds', text:'<b>IP readiness report.</b> Maturity and risk are read together—a mature block from a fragile vendor is not a low-risk line.'},
  ],
  risks:[
    '<b>Register without triggers.</b> A contingency with no decision date cannot be executed, because by the time the need is obvious the option has expired.',
    '<b>Every line rated as critical.</b> A register where everything is critical directs attention nowhere; the point is to identify the few that stop the program.',
    '<b>Second source assessed on capability alone.</b> An alternative vendor without a license, an evaluation and a delivery date is not a contingency.',
    '<b>Internal fallback assumed.</b> A fallback that depends on engineers already committed to the critical path is not a fallback.',
    '<b>Register written and not reviewed.</b> IP risk changes as deliveries land; a register reviewed once at IP Plan Freeze is stale by RTL integration.',
  ],
  roles:[
    {r:'IP strategist', d:'Owns the register and the contingency plan'},
    {r:'Program manager', d:'Critical dependency identification and triggers'},
    {r:'Procurement lead', d:'Second-source viability and commercial options'},
    {r:'AMS lead', d:'Internal fallback feasibility and capacity'},
    {r:'Chief architect', d:'Confirms which failures actually stop the program'},
  ],
  effort:[['Risk rating',0.75], ['Critical dependency analysis',0.5], ['Contingency options',0.5], ['Trigger definition',0.25]],
  entry:[
    'Readiness levels assigned by IPR-05',
    'Delivery schedule aligned by IPR-09',
    'Sourcing strategy known from TECH-08',
  ],
  exit:[
    'Critical dependencies identified and separated from the rest',
    'Every critical block has a contingency with a trigger date',
    'Register has a review cadence, not just an author',
  ],
  dependsOn:['IPR-05','IPR-08','IPR-09','TECH-08'],
  dependsNote:null,
  feedsInto:['RTL-10','DEF-09','AMS-01'],
  measuredBy:[
    'Critical dependencies with a triggered contingency',
    'Register reviews held against those planned',
    'Contingencies executed against those defined',
  ],
},

};
