/* MP — Qualification & Mass Production. Twelve activities. Stage w106–132 (26w), 208 M/M. */
module.exports = {

'MP-01': {
  stage:'qualification', window:[0,6], criticalPath:true,
  purpose:[
    'Define <b>what qualification means for this product</b>—which standards apply, which stresses run, on how many units, and against what acceptance criteria.',
    'Qualification is the evidence that the part survives its intended life. The plan is where that evidence is designed: too little and a customer\'s own qualification finds what yours did not, too much and months of chamber time are spent on stresses nobody required.',
  ],
  steps:[
    {n:1, text:'Standard selection — JEDEC, AEC and customer applicability', tat:1, lane:'main'},
    {n:2, text:'Stress matrix and sample size definition', tat:1.5, lane:'main'},
    {n:3, text:'Qualification vehicle and lot definition', tat:1, lane:'par'},
    {n:4, text:'Lab and chamber capacity booking', tat:1.5, lane:'main'},
    {n:5, text:'Customer qualification requirement collection', tat:1, lane:'par'},
    {n:6, text:'Plan review and release', tat:2, lane:'main'},
  ],
  flowNote:'Step 4 is why this activity runs first. HTOL occupies a chamber for a thousand hours, and chambers are shared; a booking made late pushes the whole qualification campaign and therefore mass production.',
  consumes:[
    'Product requirements and quality target from DEF-04',
    'Application and use conditions from DEF-03',
    'Customer qualification requirements',
    'Package construction from PKGD-11',
    'Unit availability from ASSY-09',
  ],
  produces:[
    'Applicable standard selection',
    'Stress matrix with sample sizes',
    'Qualification vehicle and lot definition',
    'Chamber and lab bookings',
    'Customer requirement record',
    'Released qualification plan',
    'Reviewed and released qualification plan',
  ],
  producedBy:[1,2,3,4,5,5,6],
  rel:[
    {id:'MP-D1', rel:'produces', text:'<b>Qualification plan and JEDEC-compliant qualification report.</b> The plan half of the deliverable; the report follows from executing it.'},
    {id:'MP-D5', rel:'informs', text:'<b>Production readiness review signoff.</b> The plan defines what evidence the readiness review will be asked to accept.'},
  ],
  risks:[
    '<b>Chamber capacity booked late.</b> Stress duration is fixed and capacity is shared, so a late booking moves mass production directly.',
    '<b>Sample sizes below the confidence the claim needs.</b> A reliability claim from too few units does not support the specification.',
    '<b>Customer requirements collected after the plan.</b> A customer-specific stress discovered later restarts a months-long campaign.',
    '<b>Three lots not planned.</b> Standards generally require multiple production lots, and a single-lot qualification is not accepted.',
    '<b>Use conditions assumed rather than specified.</b> The acceleration factors depend on them, and wrong conditions make the whole campaign non-representative.',
  ],
  roles:[
    {r:'Reliability engineer', d:'Owns the qualification plan'},
    {r:'Quality manager', d:'Standard applicability and acceptance criteria'},
    {r:'Package engineer', d:'Package-specific stress requirements'},
    {r:'Product marketing', d:'Customer qualification requirements'},
    {r:'Operations planner', d:'Unit availability and chamber capacity'},
  ],
  effort:[['Stress matrix and sample sizes',2.5], ['Plan review and release',1.75], ['Standard selection',1.5], ['Lab and chamber booking',1], ['Vehicle definition',0.75], ['Customer requirements',0.5]],
  entry:[
    'Product use conditions defined in DEF-03',
    'Package construction known from PKGD-11',
    'Unit allocation agreed in ASSY-09',
  ],
  exit:[
    'Chamber capacity booked against the full stress duration',
    'Sample sizes supporting the reliability claim',
    'Customer-specific requirements included before release',
  ],
  dependsOn:['DEF-03','DEF-04','PKGD-11','ASSY-09'],
  dependsNote:null,
  feedsInto:['MP-02','MP-03','MP-04','MP-09','TEST-07'],
  measuredBy:[
    'Chamber capacity secured against the plan',
    'Sample size against the confidence claim',
    'Customer requirements captured before execution',
  ],
},

'MP-02': {
  stage:'qualification', window:[5,23], criticalPath:true,
  purpose:[
    'Run the <b>reliability stresses</b>—HTOL, high-temperature storage, temperature cycling, uHAST, THB—that demonstrate the silicon survives its specified life.',
    'This is eighteen weeks of mostly waiting, and it is the longest fixed-duration item between first silicon and mass production. HTOL alone is a thousand hours; it cannot be shortened, only started earlier or run in parallel.',
  ],
  steps:[
    {n:1, text:'Sample preparation and pre-stress characterization', tat:1.5, lane:'main'},
    {n:2, text:'Stress chamber loading and campaign start', tat:2, lane:'main'},
    {n:3, text:'uHAST and THB execution', tat:3, lane:'par'},
    {n:4, text:'HTOL execution', tat:6, lane:'main'},
    {n:5, text:'Interim readouts at defined intervals', tat:3, lane:'par'},
    {n:6, text:'Temperature cycle and HTS execution', tat:4.5, lane:'main'},
    {n:7, text:'Failure analysis on stress failures', tat:2.5, lane:'par'},
    {n:8, text:'Final readout, analysis and report', tat:4, lane:'main'},
  ],
  flowNote:'Step 5\'s interim readouts are what turn a pass/fail campaign into a learning one. A parameter drifting at 500 hours predicts a failure at 1000 that would otherwise arrive as a surprise at the end of a four-month run.',
  consumes:[
    'Qualification plan from MP-01',
    'Qualification units from ASSY-09',
    'Pre-stress characterization from TEST-07',
    'Chamber capacity from MP-01',
    'Failure analysis capability',
  ],
  produces:[
    'Pre-stress characterization baseline',
    'Loaded stress campaign',
    'uHAST and THB results',
    'HTOL results',
    'Interim readout data',
    'Temperature cycle and HTS results',
    'Stress failure analyses',
    'Reliability data package',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D2', rel:'produces', text:'<b>Reliability and package qualification data packages.</b> The silicon-reliability half of the deliverable.'},
    {id:'MP-D1', rel:'feeds', text:'<b>Qualification plan and JEDEC-compliant qualification report.</b> These are the results the report is written from.'},
  ],
  risks:[
    '<b>Campaign started late.</b> The duration is fixed, so every week of delay is a week of mass production delay, one for one.',
    '<b>No pre-stress characterization.</b> Drift cannot be measured without a baseline, and a failure cannot be distinguished from a part that was always marginal.',
    '<b>Interim readouts skipped.</b> Failures then arrive only at the end, with no time left to respond before the ramp.',
    '<b>Stress failures not analyzed.</b> A failure without a mechanism cannot be judged as systematic or as a one-off, and the distinction decides the ramp.',
    '<b>Units insufficient for the full matrix.</b> A stress dropped for lack of units is a gap in the qualification the customer will find.',
  ],
  roles:[
    {r:'Reliability engineer', d:'Owns the stress campaign'},
    {r:'Test engineer', d:'Pre-stress and readout measurement'},
    {r:'Failure analysis engineer', d:'Stress failure mechanisms'},
    {r:'Quality engineer', d:'Acceptance against the standard'},
    {r:'Lab technician', d:'Chamber operation and readout scheduling'},
  ],
  effort:[['HTOL execution',8], ['Temperature cycle and HTS',6], ['Readout and analysis',5], ['uHAST and THB',4.5], ['Interim readouts',3.5], ['Failure analysis',3]],
  entry:[
    'Qualification plan released from MP-01',
    'Units available from ASSY-09',
    'Chambers booked and available',
  ],
  exit:[
    'Pre-stress baseline recorded for every unit',
    'Interim readouts taken at the planned intervals',
    'Every stress failure analyzed to a mechanism',
  ],
  dependsOn:['MP-01','ASSY-09','TEST-07'],
  dependsNote:null,
  feedsInto:['MP-09','MP-12','MP-05'],
  measuredBy:[
    'Campaign start against plan',
    'Failures per stress against the acceptance criterion',
    'Failures analyzed to a mechanism',
  ],
},

'MP-03': {
  stage:'qualification', window:[6,12], criticalPath:false,
  purpose:[
    'Qualify the part\'s <b>ESD and latch-up robustness</b>—HBM and CDM discharge, and latch-up immunity—the handling-survival properties every downstream user depends on.',
    'ESD failures happen in assembly lines, in labs and in the field, and they are almost never traced back to the part that could not take them. The classification levels are what tell a customer\'s manufacturing engineer how to handle the device.',
  ],
  steps:[
    {n:1, text:'ESD and latch-up test plan and pin classification', tat:1, lane:'main'},
    {n:2, text:'HBM ESD characterization', tat:1.5, lane:'main'},
    {n:3, text:'Pin classification and protection review', tat:1, lane:'par'},
    {n:4, text:'CDM ESD characterization', tat:1.5, lane:'main'},
    {n:5, text:'Failure analysis on ESD failures', tat:1, lane:'par'},
    {n:6, text:'Latch-up test and report', tat:2, lane:'main'},
  ],
  flowNote:'Step 4 matters more than step 2 on a package this size. CDM stress scales with package capacitance, and a large 2.5D package charges to a far higher energy than a small one—the CDM level is usually the binding constraint.',
  consumes:[
    'ESD protection design from AMS-09 and PD-11',
    'Package construction from PKGD-11',
    'Qualification plan from MP-01',
    'Qualification units from ASSY-09',
    'ESD test laboratory capability',
  ],
  produces:[
    'ESD and latch-up test plan',
    'HBM ESD classification',
    'Pin classification and protection review',
    'CDM ESD classification',
    'ESD failure analyses',
    'Latch-up test results and report',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'MP-D2', rel:'feeds', text:'<b>Reliability and package qualification data packages.</b> ESD and latch-up classification are part of the qualification package.'},
    {id:'MP-D8', rel:'feeds', text:'<b>Datasheet and product documentation set.</b> ESD classification is a datasheet parameter every handler reads.'},
  ],
  risks:[
    '<b>CDM underestimated for the package size.</b> A large package stores far more charge, and the CDM level is usually the binding one.',
    '<b>ESD failures not analyzed.</b> Which pin and which protection element failed is what makes the result actionable for a fix.',
    '<b>Latch-up tested only at room temperature.</b> Latch-up susceptibility increases with temperature, and the hot corner is the real test.',
    '<b>Classification below what customer assembly requires.</b> A part that cannot survive a customer\'s line is a part they cannot buy.',
    '<b>Pin classification incomplete.</b> Untested pin combinations are unqualified pins, and there is no assumption to fall back on.',
  ],
  roles:[
    {r:'ESD engineer', d:'Owns ESD and latch-up qualification'},
    {r:'Circuit designer', d:'Protection design and failure interpretation'},
    {r:'Package engineer', d:'Package contribution to CDM'},
    {r:'Quality engineer', d:'Classification against customer requirements'},
    {r:'Failure analysis engineer', d:'ESD failure localization'},
  ],
  effort:[['HBM ESD characterization',2], ['CDM ESD characterization',2], ['Latch-up test',1.75], ['Pin classification',1], ['Test plan',0.75], ['Failure analysis',0.5]],
  entry:[
    'Qualification plan from MP-01',
    'Units available from ASSY-09',
    'ESD test laboratory booked',
  ],
  exit:[
    'CDM evaluated against the package\'s actual capacitance',
    'Latch-up tested at the hot corner',
    'Classification meeting customer assembly requirements',
  ],
  dependsOn:['MP-01','ASSY-09','AMS-09','PD-11','PKGD-11'],
  dependsNote:null,
  feedsInto:['MP-09','MP-12'],
  measuredBy:[
    'ESD classification achieved against target',
    'Latch-up immunity at maximum temperature',
    'Pin combinations tested against total',
  ],
},

'MP-04': {
  stage:'qualification', window:[8,20], criticalPath:false,
  purpose:[
    'Qualify the <b>package</b>—moisture sensitivity, board-level reliability, drop and bend—which on a 2.5D structure is where the reliability risk actually concentrates.',
    'The silicon\'s reliability is a well-understood function of process and use conditions. The package\'s is not: a large interposer on an organic substrate with two HBM stacks has thermal expansion mismatches on every interface, and this is where they are proven or found out.',
  ],
  steps:[
    {n:1, text:'MSL preconditioning and moisture classification', tat:1.5, lane:'main'},
    {n:2, text:'Board-level reliability — temperature cycling on board', tat:2.5, lane:'main'},
    {n:3, text:'Solder joint reliability modeling correlation', tat:2, lane:'par'},
    {n:4, text:'Drop and bend testing', tat:3, lane:'main'},
    {n:5, text:'Warpage and co-planarity tracked through stress', tat:2, lane:'par'},
    {n:6, text:'Package-level readout and acoustic imaging', tat:2.5, lane:'main'},
    {n:7, text:'Failure analysis on package failures', tat:1.5, lane:'par'},
    {n:8, text:'Analysis and qualification report', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 3 is what turns this campaign into a predictive model rather than a single data point. Correlating measured joint life against the model means the next package variant can be assessed without repeating twelve weeks of testing.',
  consumes:[
    'Qualification plan from MP-01',
    'Package units from ASSY-09',
    'PTV reliability results from PTV-10',
    'Package construction from PKGD-11',
    'Board-level test capability',
  ],
  produces:[
    'MSL classification',
    'Board-level reliability results',
    'Solder joint reliability model correlation',
    'Drop and bend results',
    'Warpage and co-planarity through stress',
    'Package readout and acoustic imaging',
    'Package failure analyses',
    'Package qualification report',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D2', rel:'produces', text:'<b>Reliability and package qualification data packages.</b> The package half of the deliverable.'},
    {id:'MP-D1', rel:'feeds', text:'<b>Qualification plan and JEDEC-compliant qualification report.</b> Package qualification is a required section of the report.'},
  ],
  risks:[
    '<b>MSL classification worse than the assembly process needs.</b> A high moisture sensitivity forces bake-and-handle procedures on every customer line.',
    '<b>Board-level reliability short of the application requirement.</b> The joints, not the die, then set the product\'s life.',
    '<b>PTV results not compared.</b> The vehicles predicted this behavior, and the comparison validates or invalidates the whole vehicle program.',
    '<b>Warpage measured only before stress.</b> The interesting change is what stress does to it, and that requires measurement through the campaign.',
    '<b>Failures attributed to the package without analysis.</b> A CPI failure and a solder joint failure need different fixes and look similar from outside.',
  ],
  roles:[
    {r:'Package reliability engineer', d:'Owns package qualification'},
    {r:'Package engineer', d:'Construction and failure mechanism'},
    {r:'Materials engineer', d:'Interface and joint behavior'},
    {r:'Quality engineer', d:'Standard compliance and acceptance'},
    {r:'Failure analysis engineer', d:'Package failure localization'},
  ],
  effort:[['Board-level reliability',4.5], ['Drop and bend testing',3.5], ['MSL preconditioning',3], ['Readout and acoustic imaging',2.5], ['Joint reliability correlation',2.5], ['Warpage tracking',2]],
  entry:[
    'Qualification plan from MP-01',
    'Package units available from ASSY-09',
    'PTV reliability data available from PTV-10',
  ],
  exit:[
    'MSL classification compatible with customer assembly',
    'Board-level life meeting the application requirement',
    'Results compared against the PTV prediction',
  ],
  dependsOn:['MP-01','ASSY-09','PTV-10','PKGD-11','ASSY-06'],
  dependsNote:null,
  feedsInto:['MP-09','MP-12','PTV-12'],
  measuredBy:[
    'MSL level achieved',
    'Board-level cycles to failure against requirement',
    'Correlation between measured and modelled joint life',
  ],
},

'MP-05': {
  stage:'qualification', window:[2,22], criticalPath:true,
  purpose:[
    'Run <b>yield learning</b> continuously through the ramp—pareto, defect analysis, corrective action, and a yield model checked against the cost target.',
    'Yield is the difference between a product that makes money and one that does not, and first-ramp yield is never where the cost model assumed. This activity runs for the whole stage because yield learning is a rate, not an event: what matters is how fast the pareto\'s top item is removed and replaced by the next.',
  ],
  steps:[
    {n:1, text:'Yield data pipeline and baseline establishment', tat:2, lane:'main'},
    {n:2, text:'Failure pareto by bin and failure mode', tat:3.5, lane:'main'},
    {n:3, text:'Wafer-level spatial signature analysis', tat:3, lane:'par'},
    {n:4, text:'Defect analysis and root cause', tat:4.5, lane:'main'},
    {n:5, text:'Assembly and test yield split', tat:3, lane:'par'},
    {n:6, text:'Corrective action and yield improvement', tat:5, lane:'main'},
    {n:7, text:'Excursion detection and response', tat:3, lane:'par'},
    {n:8, text:'Yield model against the cost target', tat:5, lane:'main'},
  ],
  flowNote:'Step 5 is the split that decides who acts. Die yield, assembly yield and test yield have different owners and different fixes, and a combined number tells none of them what to do.',
  consumes:[
    'Test data infrastructure from TEST-11',
    'Fab yield data from FAB-09',
    'Assembly yield from ASSY-07',
    'Bring-up failure analysis from BU-09',
    'Cost model from DEF-06',
  ],
  produces:[
    'Yield data pipeline and baseline',
    'Failure pareto by bin and mode',
    'Spatial signature analysis',
    'Defect root causes',
    'Assembly and test yield split',
    'Corrective actions and improvement record',
    'Excursion detection and responses',
    'Yield model against cost target',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D4', rel:'produces', text:'<b>Yield model versus cost target report.</b> This activity is the deliverable, and the model is what the business plan is checked against.'},
    {id:'MP-D5', rel:'feeds', text:'<b>Production readiness review signoff.</b> Yield at the readiness review is one of its principal acceptance criteria.'},
  ],
  risks:[
    '<b>Yield reported as one number.</b> Die, assembly and test yield have different owners, and a combined figure directs nobody.',
    '<b>Spatial signatures not analyzed.</b> Edge, center and radial patterns each point at a different process cause and are visible only on the wafer map.',
    '<b>Corrective actions not verified.</b> An action taken without confirming the pareto moved is an action that may have done nothing.',
    '<b>Excursions detected at the weekly review.</b> By then a week of material is affected, and detection has to be automatic.',
    '<b>Yield model not checked against the cost target.</b> The gap between achieved and assumed yield is the product\'s margin, and it can go unnoticed for months.',
  ],
  roles:[
    {r:'Yield engineer', d:'Owns yield learning and the pareto'},
    {r:'Process engineer', d:'Fab-side defect root cause'},
    {r:'Assembly engineer', d:'Assembly yield contribution'},
    {r:'Test engineer', d:'Test yield and bin analysis'},
    {r:'Cost analyst', d:'Yield model against the business case'},
  ],
  effort:[['Defect analysis and root cause',10], ['Corrective action and improvement',9], ['Failure pareto',7], ['Yield model',6], ['Spatial signature analysis',4.5], ['Excursion response',3.5]],
  entry:[
    'Test data infrastructure running from TEST-11',
    'Fab and assembly yield data flowing',
    'Cost model available from DEF-06',
  ],
  exit:[
    'Yield split by die, assembly and test',
    'Corrective actions verified against the pareto',
    'Yield model reconciled with the cost target',
  ],
  dependsOn:['TEST-11','FAB-09','ASSY-07','BU-09','DEF-06'],
  dependsNote:null,
  feedsInto:['MP-09','MP-10','MP-06'],
  measuredBy:[
    'Yield against the cost model assumption',
    'Pareto top-item removal rate',
    'Time from excursion to detection',
  ],
},

'MP-06': {
  stage:'qualification', window:[10,19], criticalPath:true,
  purpose:[
    'Release the <b>production test program</b>—frozen, guard-band-validated, qualified and version-controlled—for every unit the product will ever ship.',
    'After this release, a change to test content requires re-qualification. That makes the release a genuine freeze, and it makes the guard-band validation that precedes it the last chance to be sure the limits neither throw away good parts nor let bad ones through.',
  ],
  steps:[
    {n:1, text:'Release candidate program freeze', tat:1, lane:'main'},
    {n:2, text:'Guard-band validation against characterization', tat:2, lane:'main'},
    {n:3, text:'Test escape and over-kill analysis', tat:1.5, lane:'par'},
    {n:4, text:'Production flow validation on volume lots', tat:2, lane:'main'},
    {n:5, text:'Limit adjustment and re-validation', tat:1.5, lane:'par'},
    {n:6, text:'Program qualification and signoff', tat:2, lane:'main'},
    {n:7, text:'Production tester porting and correlation', tat:1.25, lane:'par'},
    {n:8, text:'Release and version control', tat:2, lane:'main'},
  ],
  flowNote:'Step 3 quantifies both directions of error. Escapes cost the customer\'s trust and over-kill costs yield, and a limit set without measuring both is optimizing one at the other\'s expense without knowing it.',
  consumes:[
    'Sort and final programs from TEST-05 and TEST-06',
    'Characterization data from TEST-07 and BU-07',
    'Correlation results from TEST-10',
    'Yield data from MP-05',
    'Production tester fleet from TEST-02',
  ],
  produces:[
    'Frozen release candidate',
    'Guard-band validation results',
    'Escape and over-kill analysis',
    'Production flow validation on volume lots',
    'Limit adjustments',
    'Program qualification and signoff',
    'Tester porting and correlation',
    'Released, version-controlled production programs',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D3', rel:'produces', text:'<b>Production test program release.</b> This activity is the deliverable, and after it the content is frozen.'},
    {id:'MP-D5', rel:'feeds', text:'<b>Production readiness review signoff.</b> A released and qualified test program is a precondition for the review.'},
  ],
  risks:[
    '<b>Guard bands not validated against characterization.</b> Limits then rest on convention rather than on what the silicon actually does.',
    '<b>Over-kill unmeasured.</b> Good parts are discarded on every lot and the loss is attributed to yield rather than to the limits.',
    '<b>Flow validated on one lot.</b> Lot-to-lot variation is the thing the flow has to tolerate, and one lot cannot show it.',
    '<b>Porting across the tester fleet without correlation.</b> Tester-to-tester differences then present as yield differences by machine.',
    '<b>Released without version control.</b> A yield excursion cannot be correlated with a program change nobody can identify.',
  ],
  roles:[
    {r:'Product engineering', d:'Owns the release and its guard bands'},
    {r:'Test engineer', d:'Program freeze, porting and correlation'},
    {r:'Quality engineer', d:'Qualification and signoff'},
    {r:'Yield engineer', d:'Escape and over-kill quantification'},
    {r:'Operations', d:'Fleet deployment and version control'},
  ],
  effort:[['Guard-band validation',5], ['Production flow validation',4], ['Program qualification',3.5], ['Escape and over-kill analysis',3], ['Release and version control',2.5], ['Tester porting',2]],
  entry:[
    'Programs debugged from TEST-05 and TEST-06',
    'Characterization and correlation data available',
    'Volume lots available for flow validation',
  ],
  exit:[
    'Guard bands derived from characterization, not convention',
    'Both escape and over-kill quantified',
    'Flow validated across multiple lots and testers',
  ],
  dependsOn:['TEST-05','TEST-06','TEST-09','TEST-10','BU-07','MP-05'],
  dependsNote:null,
  feedsInto:['MP-07','MP-09','MP-10'],
  measuredBy:[
    'Escape rate against the DPPM target',
    'Over-kill rate at the released limits',
    'Tester-to-tester yield spread after porting',
  ],
},

'MP-07': {
  stage:'qualification', window:[14,23], criticalPath:false,
  purpose:[
    'Convert production test to <b>multi-site</b> and cut test time—the change that makes the cost per unit sustainable at volume.',
    'Single-site testing is fine for a hundred units and ruinous for a million. Multi-site conversion multiplies throughput per tester and divides the capital needed for the ramp, and it is a real engineering exercise because parallel sites interfere with each other in ways single-site testing never reveals.',
  ],
  steps:[
    {n:1, text:'Multi-site feasibility on the production hardware', tat:1, lane:'main'},
    {n:2, text:'Multi-site load board and probe card conversion', tat:2, lane:'main'},
    {n:3, text:'Test time reduction on the released content', tat:1.5, lane:'par'},
    {n:4, text:'Parallel program adaptation', tat:2, lane:'main'},
    {n:5, text:'Site-to-site variation analysis', tat:1.5, lane:'par'},
    {n:6, text:'Multi-site correlation and validation', tat:2, lane:'main'},
    {n:7, text:'Throughput and capacity model update', tat:1.25, lane:'par'},
    {n:8, text:'Release of the converted flow', tat:2, lane:'main'},
  ],
  flowNote:'Step 5 is what makes the conversion trustworthy. Sites differ—in contact, in power delivery, in noise coupling—and a systematic site bias shows up as a yield difference that gets chased as a process problem for weeks.',
  consumes:[
    'Released production programs from MP-06',
    'Tester pin count and configuration from TEST-02',
    'Test time analysis from TEST-09',
    'Load board and probe card designs from TEST-03 and TEST-04',
    'Volume forecast from MP-10',
  ],
  produces:[
    'Multi-site feasibility assessment',
    'Converted multi-site hardware',
    'Converted multi-site load board and probe card',
    'Test time reduction on released content',
    'Adapted parallel programs',
    'Site-to-site variation analysis',
    'Multi-site correlation and validation',
    'Updated throughput and capacity model',
    'Released converted flow',
  ],
  producedBy:[1,1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D3', rel:'feeds', text:'<b>Production test program release.</b> The multi-site flow is a controlled revision of the released program.'},
    {id:'MP-D6', rel:'feeds', text:'<b>Ramp plan and supply commitment.</b> Throughput per tester is what the capacity commitment is built from.'},
  ],
  risks:[
    '<b>Site-to-site bias undetected.</b> It appears as a yield difference and is investigated as a process problem for weeks.',
    '<b>Pin count insufficient for the site count.</b> The tester configuration from <code>TEST-02</code> bounds this, and it cannot be changed now.',
    '<b>Parallel power delivery inadequate.</b> Four parts drawing full current through one load board droop in ways one part does not.',
    '<b>Conversion done after the ramp starts.</b> Capital is then committed at single-site throughput and cannot be recovered.',
    '<b>Time reduction changing coverage.</b> Any content change after MP-06 requires re-qualification, which is expensive at this point.',
  ],
  roles:[
    {r:'Test engineer', d:'Owns multi-site conversion'},
    {r:'Test hardware engineer', d:'Load board and probe card conversion'},
    {r:'Product engineering', d:'Site correlation and coverage preservation'},
    {r:'Operations planner', d:'Capacity and throughput model'},
    {r:'Yield engineer', d:'Site bias detection'},
  ],
  effort:[['Multi-site hardware conversion',4], ['Parallel program adaptation',3.5], ['Correlation and validation',3], ['Test time reduction',2.5], ['Site variation analysis',1.75], ['Capacity model',1.25]],
  entry:[
    'Production programs released from MP-06',
    'Tester configuration supporting the site count',
    'Test time analysis available from TEST-09',
  ],
  exit:[
    'Site-to-site bias measured and within tolerance',
    'Parallel power delivery adequate at full current',
    'Conversion complete before capital is committed to the ramp',
  ],
  dependsOn:['MP-06','TEST-02','TEST-03','TEST-04','TEST-09'],
  dependsNote:null,
  feedsInto:['MP-09','MP-10'],
  measuredBy:[
    'Throughput multiple achieved against site count',
    'Site-to-site yield spread',
    'Cost per tested unit after conversion',
  ],
},

'MP-08': {
  stage:'qualification', window:[8,17], criticalPath:false,
  purpose:[
    'Validate the design across <b>process corners</b> using split lots—material deliberately fabricated at the edges of the process window.',
    'Production silicon spans the process distribution, and the units bring-up characterized came from one lot near its center. Split lots produce the fast and slow corners on purpose, which is the only way to know whether the design\'s margin survives the population it will actually be built from.',
  ],
  steps:[
    {n:1, text:'Split-lot design across process corners', tat:1, lane:'main'},
    {n:2, text:'Split lot fabrication and tracking', tat:2, lane:'main'},
    {n:3, text:'Parametric spread and Cpk analysis', tat:1.5, lane:'par'},
    {n:4, text:'Corner characterization on split material', tat:2, lane:'main'},
    {n:5, text:'Design margin at the corners', tat:1.5, lane:'par'},
    {n:6, text:'Corner-to-model correlation', tat:2, lane:'main'},
    {n:7, text:'Process window recommendation', tat:1.25, lane:'par'},
    {n:8, text:'Corner signoff and report', tat:2, lane:'main'},
  ],
  flowNote:'Step 6 closes a loop opened right back at signoff. The design was timed against corner models; measuring real corner silicon says whether those models were pessimistic, accurate, or—the dangerous case—optimistic.',
  consumes:[
    'Split lot material from FAB-06',
    'Corner models from PDK-05',
    'Characterization content from TEST-07',
    'Shmoo baseline from BU-07',
    'Process window from TECH-05',
  ],
  produces:[
    'Split-lot design',
    'Fabricated and tracked split lots',
    'Parametric spread and Cpk analysis',
    'Corner characterization results',
    'Design margin at the corners',
    'Corner-to-model correlation',
    'Process window recommendation',
    'Corner signoff report',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D4', rel:'feeds', text:'<b>Yield model versus cost target report.</b> Corner yield is what the model has to predict across the real distribution.'},
    {id:'MP-D1', rel:'feeds', text:'<b>Qualification plan and JEDEC-compliant qualification report.</b> Corner validation is part of demonstrating the design is production-worthy.'},
  ],
  risks:[
    '<b>Corner models optimistic against real silicon.</b> The design was signed off against those models, and a gap here means the margin does not exist.',
    '<b>Split lots not actually at the corners.</b> Material that drifted back toward center proves nothing about the edges.',
    '<b>Cpk not computed.</b> Capability against the specification is what predicts production yield, and a pass/fail result does not.',
    '<b>Corner characterization skipped for schedule.</b> The population\'s edges are then only seen in production, as an unexplained yield tail.',
    '<b>Process window recommendation not fed back to the fab.</b> The data exists and the process keeps running at its original center point.',
  ],
  roles:[
    {r:'Product engineering', d:'Owns corner validation'},
    {r:'Process engineer', d:'Split lot design and execution'},
    {r:'Characterization engineer', d:'Corner measurement'},
    {r:'Design engineer', d:'Model correlation and margin assessment'},
    {r:'Yield engineer', d:'Cpk and distribution analysis'},
  ],
  effort:[['Corner characterization',3.5], ['Split lot execution',3], ['Corner-to-model correlation',2.5], ['Cpk analysis',2], ['Design margin assessment',1.75], ['Window recommendation',1.25]],
  entry:[
    'Split lot material available from FAB-06',
    'Corner models available from PDK-05',
    'Characterization content ready from TEST-07',
  ],
  exit:[
    'Split material verified to be at the intended corners',
    'Cpk computed against the specification',
    'Model-to-silicon correlation established at both corners',
  ],
  dependsOn:['FAB-06','PDK-05','TEST-07','BU-07','TECH-05'],
  dependsNote:null,
  feedsInto:['MP-06','MP-09','MP-05'],
  measuredBy:[
    'Corner spread achieved against intended',
    'Cpk against the specification',
    'Model-to-silicon gap at the corners',
  ],
},

'MP-09': {
  stage:'qualification', window:[18,24], criticalPath:true,
  purpose:[
    'Hold the <b>production readiness review</b>—the cross-functional gate where every function states whether it is ready—and stand up change control for everything that follows.',
    'This is the program\'s last formal decision point. After it, the product is in production and every change goes through customer notification. The review\'s value is that it forces each function to say ready or not ready on the record, which is a different act from being asked in a meeting whether there are any concerns.',
  ],
  steps:[
    {n:1, text:'Readiness criteria and evidence collection', tat:1, lane:'main'},
    {n:2, text:'Cross-functional readiness review', tat:1.5, lane:'main'},
    {n:3, text:'Change control and document baseline', tat:1, lane:'par'},
    {n:4, text:'Gap closure and conditional item tracking', tat:1.5, lane:'main'},
    {n:5, text:'Escalation of unresolved items', tat:1, lane:'par'},
    {n:6, text:'Signoff and PCN process establishment', tat:2, lane:'main'},
  ],
  flowNote:'Step 4\'s conditional items are where a review either works or becomes theatre. A conditional pass with an owner, a date and a consequence is a real mechanism; a conditional pass without them is an unconditional pass with a note attached.',
  consumes:[
    'Qualification results from MP-02, MP-03 and MP-04',
    'Test program release from MP-06',
    'Yield model from MP-05',
    'Supply commitment from MP-10',
    'Compliance certificates from MP-11',
  ],
  produces:[
    'Readiness criteria and collected evidence',
    'Cross-functional review record',
    'Change control and document baseline',
    'Gap closure and conditional item tracking',
    'Escalation record',
    'Signed-off readiness and established PCN process',
    'Mass production release record',
  ],
  producedBy:[1,2,3,4,5,6,6],
  rel:[
    {id:'MP-D5', rel:'produces', text:'<b>Production readiness review signoff.</b> This activity is the deliverable—the record of who declared ready and on what evidence.'},
    {id:'MP-D9', rel:'produces', text:'<b>Mass Production release record.</b> The formal statement that the product is in production, with its conditions.'},
  ],
  risks:[
    '<b>Review held without evidence.</b> Function-by-function assurances are not the same as qualification data, and a review that accepts them is not a gate.',
    '<b>Conditional items without owners or dates.</b> The condition is then never closed and the pass was unconditional in practice.',
    '<b>Change control not established.</b> Post-production changes then reach customers without notification, which is a contractual failure.',
    '<b>Dissent not recorded.</b> A function that said not-ready and was overruled is the program\'s most valuable record if something goes wrong.',
    '<b>Document baseline not frozen.</b> Which datasheet, which errata, which test program was released becomes ambiguous immediately.',
  ],
  roles:[
    {r:'Program manager', d:'Owns the review and its record'},
    {r:'Quality manager', d:'Readiness criteria and evidence standards'},
    {r:'Function leads', d:'Ready or not-ready declarations'},
    {r:'Document control', d:'Baseline freeze and change control'},
    {r:'Executive sponsor', d:'Signoff authority and escalation'},
  ],
  effort:[['Cross-functional review',2.25], ['Evidence collection',1.75], ['Gap closure and tracking',1.5], ['Signoff and PCN setup',1.25], ['Change control baseline',0.75], ['Escalation',0.5]],
  entry:[
    'Qualification results available from MP-02 through MP-04',
    'Test program released from MP-06',
    'Supply and compliance status available',
  ],
  exit:[
    'Every conditional item with an owner, a date and a consequence',
    'Change control and PCN process established before release',
    'Dissenting positions recorded, not resolved off the record',
  ],
  dependsOn:['MP-02','MP-03','MP-04','MP-05','MP-06','MP-07','MP-08','MP-10','MP-11','MP-12','BU-11'],
  dependsNote:'The review is the convergence point for the whole stage — it consumes the output of nearly every other MP activity.',
  feedsInto:[],
  measuredBy:[
    'Readiness criteria met against total',
    'Conditional items closed by their date',
    'Post-release issues that the review had evidence for',
  ],
},

'MP-10': {
  stage:'qualification', window:[10,22], criticalPath:true,
  purpose:[
    'Commit the <b>supply chain and the ramp</b>—wafers, substrates, HBM, assembly and test capacity—against a demand forecast, with the lead times and second sources that make the commitment real.',
    'A ramp is a chain of commitments made months before the volume they serve. Substrates have long lead times, HBM is allocated across the industry, and assembly capacity is booked. Any one of them short stops the ramp, and none of them can be fixed quickly.',
  ],
  steps:[
    {n:1, text:'Demand forecast and volume commitment', tat:1.5, lane:'main'},
    {n:2, text:'Wafer, substrate and HBM supply commitment', tat:2.5, lane:'main'},
    {n:3, text:'Lead time and buffer analysis', tat:2, lane:'par'},
    {n:4, text:'Assembly and test capacity commitment', tat:2.5, lane:'main'},
    {n:5, text:'Cost per unit at volume', tat:2, lane:'par'},
    {n:6, text:'Ramp plan and build schedule', tat:2.5, lane:'main'},
    {n:7, text:'Logistics and distribution setup', tat:1.5, lane:'par'},
    {n:8, text:'Supply chain risk and second-source plan', tat:3, lane:'main'},
  ],
  flowNote:'Step 8 runs last but covers everything before it. Each commitment made in steps 2 and 4 is a single point of failure, and the plan has to say what happens if any one of them fails—before it does.',
  consumes:[
    'Demand forecast from DEF-05 and product marketing',
    'Yield model from MP-05',
    'Test throughput from MP-07',
    'HBM supply position from ASSY-02',
    'Substrate and interposer supply from PKGD-09',
  ],
  produces:[
    'Demand forecast and volume commitment',
    'Wafer, substrate and HBM supply commitments',
    'Lead time and buffer analysis',
    'Assembly and test capacity commitments',
    'Cost per unit at volume',
    'Ramp plan and build schedule',
    'Logistics and distribution setup',
    'Supply chain risk and second-source plan',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D6', rel:'produces', text:'<b>Ramp plan and supply commitment.</b> This activity is the deliverable.'},
    {id:'MP-D4', rel:'feeds', text:'<b>Yield model versus cost target report.</b> Cost per unit at volume is where the yield model meets the actual supply cost.'},
  ],
  risks:[
    '<b>HBM allocation insufficient.</b> It is allocated across the industry and a shortfall stops the ramp regardless of everything else.',
    '<b>Substrate lead time underestimated.</b> Advanced substrates are long-lead and capacity-constrained, and the buffer has to reflect that.',
    '<b>Ramp planned against an optimistic yield.</b> Volume commitments then require more wafer starts than were booked.',
    '<b>No second source anywhere in the chain.</b> Every single-source node is a single point of failure for the whole product.',
    '<b>Capacity committed before the readiness review.</b> A conditional readiness outcome then meets an unconditional supply commitment.',
  ],
  roles:[
    {r:'Operations manager', d:'Owns the ramp and supply commitments'},
    {r:'Procurement', d:'Supplier commitments and second sources'},
    {r:'Product marketing', d:'Demand forecast'},
    {r:'Cost analyst', d:'Cost per unit at volume'},
    {r:'Program manager', d:'Ramp against readiness'},
  ],
  effort:[['Supply commitment',3], ['Capacity commitment',2.5], ['Ramp plan',2], ['Risk and second-source plan',1.75], ['Lead time analysis',1.5], ['Cost at volume',1.25]],
  entry:[
    'Demand forecast available',
    'Yield model available from MP-05',
    'Test throughput known from MP-07',
  ],
  exit:[
    'Every long-lead item committed with buffer',
    'Ramp built on the achieved yield, not the assumed one',
    'Single-source nodes identified with a contingency',
  ],
  dependsOn:['MP-05','MP-06','MP-07','ASSY-02','PKGD-09','DEF-05','BU-11','BU-12'],
  dependsNote:null,
  feedsInto:['MP-09'],
  measuredBy:[
    'Long-lead items committed against required',
    'Ramp achieved against plan',
    'Single-source nodes with a contingency',
  ],
},

'MP-11': {
  stage:'qualification', window:[10,22], criticalPath:false,
  purpose:[
    'Obtain the <b>compliance and certification</b> the product cannot ship without—interface compliance, EMC and safety, and materials declarations.',
    'These are gates rather than engineering activities: without a PCIe or CXL compliance listing, without EMC certification, without RoHS and REACH declarations, the product cannot be sold in most markets regardless of how well it works.',
  ],
  steps:[
    {n:1, text:'Applicable standards and certification scope', tat:1.5, lane:'main'},
    {n:2, text:'PCIe/CXL compliance testing at a plugfest', tat:2.5, lane:'main'},
    {n:3, text:'Compliance failure remediation', tat:2, lane:'par'},
    {n:4, text:'EMC and safety testing', tat:2.5, lane:'main'},
    {n:5, text:'Documentation and declaration preparation', tat:2, lane:'par'},
    {n:6, text:'Materials compliance — RoHS, REACH, conflict minerals', tat:2.5, lane:'main'},
    {n:7, text:'Export classification', tat:1.5, lane:'par'},
    {n:8, text:'Certificate issue and registration', tat:3, lane:'main'},
  ],
  flowNote:'Step 2 depends on an event calendar the program does not control. Plugfests happen on fixed dates a few times a year, and missing one costs a quarter rather than a week.',
  consumes:[
    'Interface compliance results from BU-05',
    'Materials declarations from the supply chain',
    'Package construction from PKGD-11',
    'Applicable regulatory requirements',
    'Certification body and plugfest schedules',
  ],
  produces:[
    'Applicable standards and scope',
    'PCIe/CXL compliance test results',
    'Remediation record',
    'EMC and safety test results',
    'Compliance documentation and declarations',
    'Materials compliance declarations',
    'Export classification',
    'Issued certificates and registrations',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D7', rel:'produces', text:'<b>Compliance certificates.</b> This activity is the deliverable, and without it the product cannot ship.'},
    {id:'MP-D8', rel:'feeds', text:'<b>Datasheet and product documentation set.</b> Compliance statements and classifications are part of the product documentation.'},
  ],
  risks:[
    '<b>Plugfest date missed.</b> They occur a few times a year on fixed dates, and missing one delays the listing by a quarter.',
    '<b>Materials declarations not collected from suppliers.</b> Every component in the package needs one, and collecting them takes months.',
    '<b>Compliance failure discovered at the plugfest.</b> Pre-compliance testing exists precisely so that formal testing is a confirmation.',
    '<b>Export classification left late.</b> A high-performance accelerator may be controlled, and the classification determines which markets exist.',
    '<b>Certification scope assessed for one region.</b> Requirements differ by market, and a missing certification closes a region entirely.',
  ],
  roles:[
    {r:'Compliance engineer', d:'Owns certification and declarations'},
    {r:'Interface engineer', d:'Compliance testing and remediation'},
    {r:'Regulatory affairs', d:'Standards applicability and export classification'},
    {r:'Supply chain', d:'Supplier materials declarations'},
    {r:'Product marketing', d:'Target markets and their requirements'},
  ],
  effort:[['PCIe/CXL compliance',4.5], ['EMC and safety testing',4], ['Materials compliance',3.5], ['Certificate issue and registration',2.5], ['Failure remediation',2], ['Documentation and export',1.5]],
  entry:[
    'Interface results available from BU-05',
    'Package construction and materials known from PKGD-11',
    'Target markets defined',
  ],
  exit:[
    'Compliance listing obtained, not just tested',
    'Materials declarations collected for every component',
    'Export classification completed before shipment',
  ],
  dependsOn:['BU-05','PKGD-11','ASSY-02','DEF-05'],
  dependsNote:null,
  feedsInto:['MP-09','MP-12'],
  measuredBy:[
    'Certifications obtained against required',
    'Plugfest attendance against schedule',
    'Markets open at launch',
  ],
},

'MP-12': {
  stage:'qualification', window:[14,24], criticalPath:false,
  purpose:[
    'Release the <b>product documentation</b>—datasheet, user guide, errata, application notes—the artefacts a customer actually receives alongside the silicon.',
    'The documentation is the product as far as most customers experience it. A datasheet parameter that cannot be traced to a measurement, a programming model that omits a required sequence, or an errata list that lags the silicon each cost far more support effort than the writing would have.',
  ],
  steps:[
    {n:1, text:'Documentation scope and ownership', tat:1.5, lane:'main'},
    {n:2, text:'Datasheet from characterization data', tat:2, lane:'main'},
    {n:3, text:'Parameter traceability to measurement', tat:1.5, lane:'par'},
    {n:4, text:'User guide and programming model', tat:2, lane:'main'},
    {n:5, text:'Localization and format production', tat:1.5, lane:'par'},
    {n:6, text:'Errata and application notes', tat:2, lane:'main'},
    {n:7, text:'Revision and distribution control', tat:1.5, lane:'par'},
    {n:8, text:'Technical review, approval and release', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 3 is what makes the datasheet defensible. Every number should point at a measurement, its conditions and its sample size, so that a customer\'s question about a parameter has an answer rather than a search.',
  consumes:[
    'Characterization data from TEST-07 and BU-07',
    'Errata list from BU-10',
    'Performance results from BU-08',
    'Compliance classifications from MP-11',
    'Programming model from RTL-06 and ARCH-06',
  ],
  produces:[
    'Documentation scope and ownership',
    'Reviewed and released documentation set',
    'Datasheet',
    'Parameter traceability record',
    'User guide and programming model documentation',
    'Localized and formatted documentation outputs',
    'Errata and application notes',
    'Revision and distribution control',
    'Localized and formatted outputs',
  ],
  producedBy:[1,1,2,3,4,5,6,7,8],
  rel:[
    {id:'MP-D8', rel:'produces', text:'<b>Datasheet and product documentation set.</b> This activity is the deliverable.'},
    {id:'MP-D9', rel:'feeds', text:'<b>Mass Production release record.</b> A released documentation set is part of what the release record attests to.'},
  ],
  risks:[
    '<b>Datasheet parameters without traceable measurements.</b> A customer question then has no answer, and the number cannot be defended.',
    '<b>Errata lagging the silicon.</b> The most useful document ships out of date, which is worse than shipping it late.',
    '<b>Programming model incomplete.</b> Required initialization sequences omitted from the guide become support cases, one per customer.',
    '<b>Documentation written from specifications rather than measurements.</b> It then describes the intended product rather than the one shipping.',
    '<b>No revision control on released documents.</b> Which datasheet revision a customer holds becomes unknowable.',
  ],
  roles:[
    {r:'Technical writer', d:'Owns the documentation set'},
    {r:'Product engineering', d:'Datasheet parameters and traceability'},
    {r:'Applications engineer', d:'User guide and application notes'},
    {r:'Design engineer', d:'Programming model accuracy'},
    {r:'Product marketing', d:'Approval and release'},
  ],
  effort:[['Datasheet',4.5], ['User guide',3.5], ['Errata and application notes',2.75], ['Review and release',2.5], ['Parameter traceability',1.75], ['Revision control',1]],
  entry:[
    'Characterization data available from TEST-07 and BU-07',
    'Errata list released from BU-10',
    'Compliance classifications from MP-11',
  ],
  exit:[
    'Every datasheet parameter traceable to a measurement',
    'Errata current with the shipping silicon',
    'Documentation under revision and distribution control',
  ],
  dependsOn:['TEST-07','TEST-10','BU-07','BU-08','BU-10','MP-11','MP-02'],
  dependsNote:null,
  feedsInto:['MP-09','BU-12'],
  measuredBy:[
    'Parameters with traceable measurements',
    'Errata currency against silicon revision',
    'Support cases attributable to documentation gaps',
  ],
},

};
