/* PD — Physical Design. Sixteen activities. Stage w46–76 (30w), 449 M/M. */
module.exports = {

'PD-01': {
  stage:'physicalDesign', window:[0,7], criticalPath:true,
  purpose:[
    'Build the flow—<b>scripts, MMMC environment, decks, runtimes, capacity</b>—and debug it on the N0 flow-flush netlist rather than on the netlist the schedule depends on.',
    'This is why <code>SYN-03</code> releases a netlist nobody expects to close. Every flow problem—a deck that does not load, a scenario that does not converge, a runtime that exceeds the night—is found here on a throwaway database, weeks before the same problem would have cost a turn.',
  ],
  steps:[
    {n:1, text:'Flow scope definition and script framework', tat:1.5, lane:'main'},
    {n:2, text:'MMMC environment build across corners and modes', tat:2, lane:'main'},
    {n:3, text:'Script, deck and library integration', tat:1.5, lane:'par'},
    {n:4, text:'N0 flow-flush run, end to end', tat:2, lane:'main'},
    {n:5, text:'Hierarchical and block-level flow definition', tat:1.5, lane:'par'},
    {n:6, text:'Runtime baseline and capacity assessment', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 6 is what makes the schedule credible. A flow that runs correctly and takes forty hours per iteration sets a closure cadence nobody planned for, and knowing that number now is what lets <code>PDK-12</code> buy capacity before it is needed.',
  consumes:[
    'N0 netlist from SYN-03',
    'Golden environment and flow from PDK-13',
    'Constraints from SYN-01',
    'Corner and mode definition from PDK-11',
    'Compute and license capacity from PDK-12',
  ],
  produces:[
    'Physical design script framework',
    'MMMC environment across corners and modes',
    'Integrated decks and libraries',
    'N0 end-to-end run results',
    'Hierarchical flow definition',
    'Runtime baseline and capacity assessment',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PD-D1', rel:'produces', text:'<b>Flow setup release—MMMC environment, scripts and runtime baseline.</b> This activity is the deliverable, and the runtime baseline is the part the schedule depends on.'},
    {id:'PD-D5', rel:'feeds', text:'<b>MCMM timing closure reports.</b> The scenario set built here is what every later closure report is generated from.'},
  ],
  risks:[
    '<b>Flow setup on the first real netlist.</b> Every flow problem then costs a turn, and the turns are the schedule.',
    '<b>MMMC scenarios incomplete.</b> A corner or mode missing from the setup is one the design is never closed at, and it is found at <code>SO-02</code>.',
    '<b>Runtime not measured.</b> A flow that works and takes two days per iteration produces a closure schedule nobody planned, discovered when closure starts.',
    '<b>Hierarchical flow deferred.</b> A design this size cannot be closed flat; deferring the block-level flow means building it under pressure.',
    '<b>Capacity assumed rather than booked.</b> The flow\'s peak concurrency is known here, and licences take weeks to procure.',
  ],
  roles:[
    {r:'Physical design flow lead', d:'Owns the flow, its scripts and its runtime'},
    {r:'CAD methodology engineer', d:'Deck, library and environment integration'},
    {r:'Timing methodology engineer', d:'MMMC scenario construction'},
    {r:'CAD infrastructure', d:'Runtime, capacity and license planning'},
    {r:'Synthesis liaison', d:'N0 content and flow feedback'},
  ],
  effort:[['MMMC environment build',6], ['N0 flow-flush run',5], ['Flow scope and scripts',4], ['Deck and library integration',3.5], ['Hierarchical flow definition',2], ['Runtime baseline',1.5]],
  entry:[
    'N0 netlist available from SYN-03',
    'Golden environment released by PDK-13',
    'Corner and mode definition final from PDK-11',
  ],
  exit:[
    'Flow runs end to end on N0, not on a fragment',
    'Runtime baseline measured and fed to capacity planning',
    'Hierarchical and block-level flows both defined',
  ],
  dependsOn:['SYN-03','PDK-11','PDK-12','PDK-13'],
  dependsNote:null,
  feedsInto:['PD-02','PD-05','SYN-05','PDK-12'],
  measuredBy:[
    'Flow steps running end to end on N0',
    'Runtime per iteration against the closure plan',
    'Flow problems found on N0 against on N1',
  ],
},

'PD-02': {
  stage:'physicalDesign', window:[5,14], criticalPath:true,
  purpose:[
    'Decide <b>where everything physically goes</b>—partitions, macros, block boundaries, pins, utilization—and freeze it, because everything downstream is built on it.',
    'The floorplan is the most consequential and least reversible decision in the stage. Macro placement sets routing congestion, block boundaries set what can be closed independently, and pin placement sets the top-level routing burden. A floorplan changed at turn 2 invalidates the clock trees, the power grid and the routing built on it.',
  ],
  steps:[
    {n:1, text:'Partition definition against the design hierarchy', tat:2, lane:'main'},
    {n:2, text:'Macro placement — memories, PHYs, analog', tat:2.5, lane:'main'},
    {n:3, text:'Standard cell area planning and utilization targets', tat:2, lane:'par'},
    {n:4, text:'Block boundary and pin planning', tat:2, lane:'main'},
    {n:5, text:'Keep-out, blockage and halo definition', tat:1.5, lane:'par'},
    {n:6, text:'Floorplan review and freeze', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 2 is where a memory-dominated die is won or lost. Hundreds of macro instances have to be placed so their access paths are short, their power can be delivered and the logic between them can be routed—and moving one late moves everything around it.',
  consumes:[
    'Floorplan intent and bump map from ARCH-08',
    'Macro abstracts from AMS-15 and PDK-04',
    'Partitioning from ARCH-02',
    'Netlist from SYN-05',
    'Area budgets from ARCH-06',
  ],
  produces:[
    'Partition definition',
    'Macro placement',
    'Area and utilization plan',
    'Block boundaries and pin placement',
    'Keep-out and blockage definition',
    'Frozen floorplan',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PD-D4', rel:'produces', text:'<b>Floorplan and PDN specification.</b> The floorplan half; <code>PD-03</code> supplies the power grid it is built against.'},
    {id:'PD-D2', rel:'feeds', text:'<b>Turn 1 and Turn 2 databases.</b> Every turn is placed and routed inside this floorplan; changing it invalidates the turns.'},
  ],
  risks:[
    '<b>Macro placement not congestion-aware.</b> Macros placed for access and not for the logic between them produce routing congestion that cannot be fixed at <code>PD-08</code>.',
    '<b>Floorplan changed after turn 1.</b> Clock trees, power grid and routing are all built on it, and all of them are invalidated.',
    '<b>Utilization set too high.</b> A dense floorplan closes area and cannot be routed or timing-closed, and the discovery comes after weeks of work.',
    '<b>Pin placement ignoring top-level routing.</b> Block pins facing the wrong way make top-level routing expensive for the whole rest of the program.',
    '<b>Partitions that do not match the design hierarchy.</b> Closing blocks that cut across logical boundaries makes timing budgets and equivalence checking harder for no gain.',
  ],
  roles:[
    {r:'Floorplan owner', d:'Owns partitions, macro placement and the freeze'},
    {r:'Physical design engineers', d:'Area planning, pins and blockages'},
    {r:'Architecture liaison', d:'Confirms the floorplan matches the intent'},
    {r:'Package liaison', d:'Bump map alignment with the floorplan'},
    {r:'Synthesis liaison', d:'Congestion feedback into physical-aware synthesis'},
  ],
  effort:[['Macro placement',9], ['Partition definition',7], ['Block boundary and pin planning',6], ['Area and utilization planning',5], ['Review and freeze',3], ['Blockages and halos',2]],
  entry:[
    'Floorplan intent and bump map from ARCH-08',
    'Macro abstracts available from AMS-15',
    'Flow running from PD-01',
  ],
  exit:[
    'Floorplan frozen before turn 1 starts',
    'Macro placement validated against congestion, not only access',
    'Pin placement reviewed for top-level routing cost',
  ],
  dependsOn:['PD-01','ARCH-08','AMS-15','PDK-04','SYN-05'],
  dependsNote:null,
  feedsInto:['PD-03','PD-04','PD-05','PD-16','SYN-04','DFT-09'],
  measuredBy:[
    'Floorplan changes after freeze',
    'Congestion at turn 1 against prediction',
    'Utilization achieved against target',
  ],
},

'PD-03': {
  stage:'physicalDesign', window:[6,14], criticalPath:false,
  purpose:[
    'Build the <b>power delivery network</b>—grid topology, straps, switches, decap—and prove by early IR analysis that it can actually feed the die at its power envelope.',
    'The PDN is built early because everything routes around it. Grid density trades directly against routing resource: too sparse and IR drop eats timing margin, too dense and there is nothing left to route with. Getting it wrong is discovered at <code>SO-04</code>, when the fix is a metal change across the whole die.',
  ],
  steps:[
    {n:1, text:'PDN topology and grid definition per domain', tat:1.5, lane:'main'},
    {n:2, text:'Grid implementation and strap insertion', tat:2, lane:'main'},
    {n:3, text:'Power switch and always-on region planning', tat:1.5, lane:'par'},
    {n:4, text:'Early static IR analysis', tat:2, lane:'main'},
    {n:5, text:'Decap planning and placement', tat:1.5, lane:'par'},
    {n:6, text:'PDN refinement and freeze', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 4 has to happen while the grid can still change. Static IR on a placed design with real power numbers tells you whether the grid works; running it after routing means any fix competes with a routed design for the same metal.',
  consumes:[
    'Power budget per domain from ARCH-06',
    'Power domain definition from ARCH-05 and SYN-07',
    'Floorplan from PD-02',
    'Bump and rail assignment from PD-04',
    'Power estimates from SYN-06',
  ],
  produces:[
    'PDN topology and grid definition',
    'Implemented grid and straps',
    'Power switch and always-on plan',
    'Early static IR analysis results',
    'Decap plan',
    'Frozen PDN specification',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PD-D4', rel:'produces', text:'<b>Floorplan and PDN specification.</b> The power grid half of the deliverable, frozen alongside the floorplan it sits in.'},
    {id:'PD-D5', rel:'feeds', text:'<b>MCMM timing closure reports.</b> IR drop consumes timing margin, so the PDN\'s quality shows up in closure.'},
  ],
  risks:[
    '<b>Grid density traded against routing without analysis.</b> Both constraints are real, and choosing by feel produces either IR problems or congestion.',
    '<b>IR analyzed only statically.</b> Dynamic IR under real switching is worse, and <code>SIPI-04</code> with the package model is worse again.',
    '<b>Decap placed where there is room.</b> Decoupling works where the current is drawn, not where the floorplan left space.',
    '<b>Power switches planned late.</b> They need area, always-on routing and their own control, and retrofitting them disturbs the floorplan.',
    '<b>PDN frozen before power numbers are real.</b> A grid designed against estimates and fed a design that draws more is a grid that fails at signoff.',
  ],
  roles:[
    {r:'Power delivery engineer', d:'Owns the PDN and its analysis'},
    {r:'Physical design engineers', d:'Grid implementation and decap placement'},
    {r:'Power architect', d:'Domain topology and switch strategy'},
    {r:'SI/PI liaison', d:'Hands the grid to chip-package co-analysis'},
    {r:'Floorplan owner', d:'Area for switches, straps and decap'},
  ],
  effort:[['Grid implementation',6], ['Early IR analysis',5], ['Topology definition',3.5], ['Decap planning',2.5], ['Power switch planning',2], ['Refinement and freeze',1]],
  entry:[
    'Floorplan available from PD-02',
    'Power budgets per domain from ARCH-06',
    'Bump and rail assignment progressing in PD-04',
  ],
  exit:[
    'Static IR analyzed on a placed design with real power numbers',
    'Grid density justified against routing resource',
    'PDN frozen with the floorplan, not after it',
  ],
  dependsOn:['PD-02','ARCH-05','ARCH-06','SYN-07'],
  dependsNote:null,
  feedsInto:['PD-08','PD-10','PD-11','SIPI-03','SO-04'],
  measuredBy:[
    'Static IR against budget',
    'Routing resource consumed by the grid',
    'PDN changes after freeze',
  ],
},

'PD-04': {
  stage:'physicalDesign', window:[6,14], criticalPath:false,
  purpose:[
    'Turn the architecture\'s bump budget into <b>an actual bump map and RDL</b>, iterating with package design until both sides can build what the other needs.',
    'The bump map is the contract between the die and the package, and it is negotiated rather than declared. Signal escape on the package constrains bump position; power delivery constrains bump count; and the die\'s floorplan constrains where either can go. All three have to close at once.',
  ],
  steps:[
    {n:1, text:'Bump map ingestion from the architecture budget', tat:1.5, lane:'main'},
    {n:2, text:'RDL and redistribution planning', tat:2, lane:'main'},
    {n:3, text:'Power bump and rail assignment', tat:1.5, lane:'par'},
    {n:4, text:'Package co-design iteration', tat:2, lane:'main'},
    {n:5, text:'Signal escape planning with the substrate', tat:1.5, lane:'par'},
    {n:6, text:'Bump map freeze and interface file release', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 6 is a hard date rather than a milestone. <code>PKGD-11</code> freezes package design against this map, and the substrate order that follows has a twenty-week lead time—a late bump map moves wafer-out by moving the substrate.',
  consumes:[
    'Bump budget and map intent from ARCH-08',
    'Package architecture from PKGD-01',
    'Floorplan and IO ring from PD-02',
    'Power delivery requirements from PD-03',
    'Substrate escape constraints from PKGD-04',
  ],
  produces:[
    'Ingested bump map',
    'RDL and redistribution plan',
    'Bump map with signal and power assignment',
    'Power bump and rail assignment',
    'Package co-design iteration record',
    'Signal escape plan with the substrate',
    'Frozen bump map and package interface files',
  ],
  producedBy:[1,2,3,3,4,5,6],
  rel:[
    {id:'PD-D7', rel:'produces', text:'<b>Bump map, RDL and package interface files.</b> This activity is the deliverable, and it is consumed directly by package design.'},
    {id:'PD-D4', rel:'feeds', text:'<b>Floorplan and PDN specification.</b> Bump position constrains where power can be delivered, so the two documents have to agree.'},
  ],
  risks:[
    '<b>Bump map frozen late.</b> Package design and the substrate order both wait on it, and the substrate lead time makes the delay a wafer-out delay.',
    '<b>Escape routing not checked on the package side.</b> A map that is optimal on the die and unroutable on the substrate has to be redone.',
    '<b>Power bump count reduced to fit signals.</b> The signals that fit are then fed by a PDN that cannot deliver, and <code>SIPI-04</code> finds it.',
    '<b>RDL treated as free.</b> Redistribution has its own rules and resistance, and a plan that ignores them produces IR and EM problems in the RDL itself.',
    '<b>Co-design conducted by file exchange.</b> Two teams iterating asynchronously on the same interface converge slowly or not at all.',
  ],
  roles:[
    {r:'Bump and RDL owner', d:'Owns the map and the interface files'},
    {r:'Package designer', d:'Escape routing and substrate constraints'},
    {r:'Power delivery engineer', d:'Power bump count and rail assignment'},
    {r:'Floorplan owner', d:'Die-side placement constraints'},
    {r:'SI liaison', d:'Signal assignment for channel quality'},
  ],
  effort:[['Package co-design iteration',4], ['RDL planning',3.5], ['Bump map ingestion and assignment',2.5], ['Power bump assignment',2], ['Escape planning',2]],
  entry:[
    'Bump budget available from ARCH-08',
    'Package architecture selected in PKGD-01',
    'Floorplan and IO ring available from PD-02',
  ],
  exit:[
    'Bump map frozen on the date package design needs it',
    'Escape routing confirmed feasible on the substrate',
    'Power bump count sufficient for the delivery requirement',
  ],
  dependsOn:['PD-02','PD-03','ARCH-08','PKGD-01'],
  dependsNote:null,
  feedsInto:['PKGD-02','PKGD-11','SIPI-02','SIPI-04','AMS-03'],
  measuredBy:[
    'Bump map freeze against the package design need date',
    'Escape feasibility confirmed before freeze',
    'Power bumps against the delivery requirement',
  ],
},

'PD-05': {
  stage:'physicalDesign', window:[8,16], criticalPath:true,
  purpose:[
    'Run the <b>first real turn on the N1 netlist</b>—place, build clocks, route—and establish the QoR baseline that says how far the design is from closing.',
    'Turn 1 is the first honest measurement of the design\'s physical difficulty. Everything before it was estimate; this produces real congestion, real timing and real power on a real floorplan, and the gap it reveals is what the next two turns exist to close.',
  ],
  steps:[
    {n:1, text:'N1 intake and turn setup', tat:1, lane:'main'},
    {n:2, text:'Placement and optimization', tat:2, lane:'main'},
    {n:3, text:'Congestion analysis and mitigation', tat:1.5, lane:'par'},
    {n:4, text:'Clock tree synthesis, first pass', tat:2, lane:'main'},
    {n:5, text:'Timing analysis and first ECO round', tat:1.5, lane:'par'},
    {n:6, text:'First full route', tat:2, lane:'main'},
    {n:7, text:'Power analysis on the placed and routed design', tat:1.5, lane:'par'},
    {n:8, text:'QoR baseline and feedback to synthesis', tat:1, lane:'main'},
  ],
  flowNote:'Step 8 is what makes turn 1 worth its cost. The turn\'s purpose is not to close—it will not—but to produce a measured baseline and a specific list of what synthesis and RTL must change before turn 2.',
  consumes:[
    'N1 netlist and handoff package from SYN-05 and SYN-12',
    'Frozen floorplan from PD-02',
    'PDN from PD-03',
    'Flow and MMMC from PD-01',
    'Constraints from SYN-01',
  ],
  produces:[
    'N1 intake and turn setup',
    'Placed and optimized N1 database',
    'Congestion analysis and mitigation results',
    'First-pass clock trees',
    'First-round timing analysis and ECOs',
    'First full route',
    'Turn 1 placed and routed database',
    'Timing and power analysis results',
    'QoR baseline',
    'Feedback list to synthesis and RTL',
  ],
  producedBy:[1,2,3,4,5,6,7,7,8,8],
  rel:[
    {id:'PD-D2', rel:'produces', text:'<b>Turn 1 and Turn 2 databases with QoR delta reports.</b> The first turn, and the baseline the second is measured against.'},
    {id:'PD-D5', rel:'feeds', text:'<b>MCMM timing closure reports.</b> The violation burn-down starts here, with turn 1\'s numbers as its origin.'},
  ],
  risks:[
    '<b>Turn 1 expected to close.</b> It will not, and treating the gap as a crisis rather than as data produces panic instead of a plan.',
    '<b>Feedback not specific.</b> "Congestion is high" changes nothing; "the compute cluster is over 90% utilization in three regions and needs restructuring" changes the next drop.',
    '<b>Turn run on an incomplete netlist.</b> A baseline missing blocks understates the difficulty and misleads the closure plan.',
    '<b>Congestion mitigated locally.</b> Fixing congestion by rip-up and reroute hides a structural problem that only synthesis or floorplan can solve.',
    '<b>Clock tree built before the floorplan is stable.</b> A CTS on a floorplan that then changes is work thrown away.',
  ],
  roles:[
    {r:'Physical design turn lead', d:'Owns the turn and its QoR baseline'},
    {r:'Placement and routing engineers', d:'Turn execution'},
    {r:'Clock tree engineer', d:'First-pass CTS'},
    {r:'Timing engineer', d:'Analysis and first ECO round'},
    {r:'Synthesis liaison', d:'Receives and acts on the feedback'},
  ],
  effort:[['Placement and optimization',11], ['First full route',10], ['Clock tree synthesis',8], ['Timing analysis and ECO',7], ['Congestion analysis',5], ['QoR baseline and feedback',4]],
  entry:[
    'N1 handoff accepted from SYN-12',
    'Floorplan frozen in PD-02',
    'PDN implemented in PD-03',
  ],
  exit:[
    'QoR baseline measured on a substantially complete netlist',
    'Feedback to synthesis specific enough to act on',
    'Congestion characterized as structural or local',
  ],
  dependsOn:['PD-01','PD-02','PD-03','SYN-05','SYN-12'],
  dependsNote:null,
  feedsInto:['PD-06','PD-07','PD-09','SYN-08'],
  measuredBy:[
    'QoR gap at turn 1 against budget',
    'Feedback items acted on in N2',
    'Netlist completeness at the baseline',
  ],
},

'PD-06': {
  stage:'physicalDesign', window:[14,22], criticalPath:true,
  purpose:[
    'Run the <b>second turn on N2 and converge</b>—congestion, timing and power—then quantify honestly how much closure risk remains for the final turn.',
    'Turn 2 is where the design either starts converging or reveals that it will not. Its output is a number: how many violations remain, in which blocks, and whether the trend from turn 1 projects to closure. That number is what the program uses to decide whether the tapeout date holds.',
  ],
  steps:[
    {n:1, text:'N2 intake and delta assessment against turn 1', tat:1, lane:'main'},
    {n:2, text:'Placement with congestion mitigation', tat:2, lane:'main'},
    {n:3, text:'Congestion hot-spot restructuring with synthesis', tat:1.5, lane:'par'},
    {n:4, text:'Clock tree refinement', tat:2, lane:'main'},
    {n:5, text:'Timing convergence and ECO rounds', tat:1.5, lane:'par'},
    {n:6, text:'Route convergence', tat:2, lane:'main'},
    {n:7, text:'Power and IR convergence', tat:1.5, lane:'par'},
    {n:8, text:'Closure risk quantification for the final turn', tat:1, lane:'main'},
  ],
  flowNote:'Step 3 is joint work with <code>SYN-04</code> rather than a physical design task. Congestion that survives placement optimization is structural, and the only remedies are logic restructuring or a floorplan change—both of which belong to someone else.',
  consumes:[
    'N2 netlist and handoff from SYN-08 and SYN-12',
    'Turn 1 database and QoR from PD-05',
    'Congestion feedback loop with SYN-04',
    'Clock trees from PD-07',
    'Timing closure status from PD-09',
  ],
  produces:[
    'N2 intake and delta assessment',
    'Placement with congestion mitigation',
    'Congestion mitigation and restructuring results',
    'Refined clock trees',
    'Timing convergence and ECO record',
    'Converged route',
    'Timing and power convergence results',
    'Turn 2 placed and routed database',
    'Closure risk quantification',
  ],
  producedBy:[1,2,3,4,5,6,7,8,8],
  rel:[
    {id:'PD-D2', rel:'produces', text:'<b>Turn 1 and Turn 2 databases with QoR delta reports.</b> The second turn, and the last one before the netlist is frozen.'},
    {id:'PD-D5', rel:'feeds', text:'<b>MCMM timing closure reports.</b> The burn-down trend across turns is what predicts whether the final turn closes.'},
  ],
  risks:[
    '<b>Closure risk understated at turn 2.</b> This is the last point at which a frequency or feature concession is cheap, and an optimistic number removes the option.',
    '<b>Congestion fixed locally rather than structurally.</b> Rip-up and reroute buys a turn and leaves the problem for the final one, when there is no time.',
    '<b>Turn 2 not compared against turn 1.</b> The absolute number matters less than the trend, and only the delta says whether the design is converging.',
    '<b>Power convergence deferred.</b> Power fixes change timing; leaving them to the final turn means re-closing timing after every one.',
    '<b>Late RTL changes absorbed into turn 2.</b> A functional change mid-turn invalidates the comparison the turn exists to produce.',
  ],
  roles:[
    {r:'Physical design turn lead', d:'Owns the turn and the closure risk statement'},
    {r:'Placement and routing engineers', d:'Convergence execution'},
    {r:'Synthesis liaison', d:'Structural restructuring in congested regions'},
    {r:'Timing engineer', d:'Timing convergence and ECO'},
    {r:'Program manager', d:'Consumes the risk quantification for the tapeout decision'},
  ],
  effort:[['Placement and congestion mitigation',11], ['Route convergence',10], ['Clock tree refinement',8], ['Timing convergence',8], ['Power and IR convergence',4], ['Risk quantification',4]],
  entry:[
    'N2 handoff accepted from SYN-12',
    'Turn 1 QoR baseline available from PD-05',
    'Congestion feedback loop running with SYN-04',
  ],
  exit:[
    'Convergence trend measured against turn 1, not only reported',
    'Structural congestion addressed structurally',
    'Closure risk stated with paths, blocks and options',
  ],
  dependsOn:['PD-05','SYN-08','SYN-12','PD-07'],
  dependsNote:null,
  feedsInto:['PD-13','PD-09','SYN-09','SO-01'],
  measuredBy:[
    'Violation count trend from turn 1',
    'Congestion resolved structurally against locally',
    'Closure risk at turn 2 against final-turn outcome',
  ],
},

'PD-07': {
  stage:'physicalDesign', window:[10,22], criticalPath:false,
  purpose:[
    'Build and refine the <b>clock trees</b> across turns—skew, insertion delay, jitter budget, power—for a design with dozens of domains and crossings between them.',
    'Clock tree synthesis is rebuilt every turn and improved each time. Skew directly buys or costs timing margin; insertion delay costs power and OCV; and cross-domain paths need a defined phase relationship that only a deliberately built tree provides. It is one of the few areas where a good result is worth several percent of frequency.',
  ],
  steps:[
    {n:1, text:'Clock architecture implementation plan', tat:1.5, lane:'main'},
    {n:2, text:'Clock tree synthesis per domain', tat:2.5, lane:'main'},
    {n:3, text:'Clock power optimization', tat:2, lane:'par'},
    {n:4, text:'Skew and insertion delay balancing', tat:2.5, lane:'main'},
    {n:5, text:'Jitter and OCV budget management', tat:2, lane:'par'},
    {n:6, text:'Cross-domain and useful skew handling', tat:2.5, lane:'main'},
    {n:7, text:'Clock DRC and quality checking', tat:2, lane:'par'},
    {n:8, text:'Continuous refinement across turns', tat:3, lane:'main'},
  ],
  flowNote:'Step 6 is the hardest part and the one that pays. Useful skew moves margin from paths that have it to paths that need it, and cross-domain handling decides whether those paths can be closed at all—but both make the tree harder to build and harder to verify.',
  consumes:[
    'Clock architecture from ARCH-05',
    'OCC insertion from DFT-05',
    'Floorplan from PD-02',
    'Placement from PD-05 and PD-06',
    'PLL characteristics from AMS-02',
  ],
  produces:[
    'Clock architecture implementation plan',
    'Clock tree implementation plan',
    'Synthesized clock trees per domain',
    'Clock power optimization results',
    'Skew and insertion delay results',
    'Jitter and OCV budget records',
    'Cross-domain and useful skew handling',
    'Clock DRC and quality reports',
    'Clock tree refinement record across turns',
  ],
  producedBy:[1,2,2,3,4,5,6,7,8],
  rel:[
    {id:'PD-D5', rel:'feeds', text:'<b>MCMM timing closure reports.</b> Clock skew and insertion delay are inputs to every timing number in the report.'},
    {id:'PD-D2', rel:'feeds', text:'<b>Turn 1 and Turn 2 databases.</b> Each turn contains its own clock tree, rebuilt and improved.'},
  ],
  risks:[
    '<b>Clock power ignored.</b> The clock network is a large fraction of dynamic power on a design this size, and a tree optimized only for skew is expensive to run.',
    '<b>Useful skew applied without a plan.</b> It buys margin and complicates every subsequent ECO, because moving one path\'s timing moves its neighbors\'.',
    '<b>Cross-domain phase relationship undefined.</b> Paths between domains cannot be closed reliably, and the failure appears as intermittent silicon behavior.',
    '<b>Insertion delay allowed to grow.</b> Deep trees increase OCV derate and jitter accumulation, consuming the margin the skew balancing bought.',
    '<b>Tree quality not checked.</b> Clock DRC violations—transition, capacitance, pulse width—degrade the tree in ways timing analysis reports as margin loss without explaining.',
  ],
  roles:[
    {r:'Clock tree engineer', d:'Owns CTS, skew and tree quality'},
    {r:'Clocking architect', d:'Domain relationships and jitter budget'},
    {r:'Timing engineer', d:'Useful skew planning and OCV'},
    {r:'Power engineer', d:'Clock power optimization'},
    {r:'DFT engineer', d:'OCC integration and test-mode clocking'},
  ],
  effort:[['Clock tree synthesis per domain',7], ['Skew and insertion delay balancing',6], ['Refinement across turns',5], ['Clock power optimization',3], ['Jitter and OCV budget',2.5], ['Clock DRC and quality',2.5]],
  entry:[
    'Clock architecture available from ARCH-05',
    'OCC logic inserted by DFT-05',
    'Placement available from the current turn',
  ],
  exit:[
    'Clock power inside the ARCH-06 budget',
    'Cross-domain relationships defined and closed',
    'Clock DRC clean, not only timing-clean',
  ],
  dependsOn:['PD-02','PD-05','ARCH-05','DFT-05','AMS-02'],
  dependsNote:null,
  feedsInto:['PD-06','PD-09','PD-13','SO-02'],
  measuredBy:[
    'Clock skew and insertion delay per domain',
    'Clock power against budget',
    'Clock DRC violations at each turn',
  ],
},

'PD-08': {
  stage:'physicalDesign', window:[12,28], criticalPath:true,
  purpose:[
    'Route the design and drive it to <b>DRC clean</b>—global, detailed, antenna, via optimization—across every turn, on a die where routing resource is the scarcest commodity.',
    'Routing is where the floorplan, the synthesis and the power grid are all judged. Sixteen weeks and forty man-months buys convergence on a design where congestion is structural rather than local, and where every metal layer is contested between signals, clocks and the power grid.',
  ],
  steps:[
    {n:1, text:'Routing strategy and layer planning', tat:1.5, lane:'main'},
    {n:2, text:'Global routing and congestion assessment', tat:3, lane:'main'},
    {n:3, text:'Congestion-driven rip-up and reroute', tat:2.5, lane:'par'},
    {n:4, text:'Detailed routing', tat:3.5, lane:'main'},
    {n:5, text:'Antenna and via optimization', tat:2.5, lane:'par'},
    {n:6, text:'DRC convergence', tat:4, lane:'main'},
    {n:7, text:'Routing quality and manufacturability', tat:2.5, lane:'par'},
    {n:8, text:'Continuous routing across turns', tat:4, lane:'main'},
  ],
  flowNote:'Step 6 takes four weeks because DRC convergence on an advanced node is iterative and asymptotic. The last few hundred violations take as long as the first hundred thousand, and they are the ones that need manual attention.',
  consumes:[
    'Placement and clock trees from PD-05, PD-06 and PD-07',
    'Metal stack and routing rules from TECH-02 and PDK-02',
    'PDN from PD-03',
    'Scan routing requirements from PD-12',
    'DFM rules from PDK-02',
  ],
  produces:[
    'Routing strategy and layer plan',
    'Global routing and congestion assessment',
    'Congestion resolution records',
    'Globally and detail-routed database',
    'Antenna and via optimization results',
    'DRC convergence results',
    'Routing quality and manufacturability findings',
    'Routing record across turns',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'PD-D6', rel:'produces', text:'<b>Interim physical DRC / LVS clean.</b> This activity is the deliverable at each turn, and clean here is what makes <code>SO-03</code> tractable.'},
    {id:'PD-D3', rel:'feeds', text:'<b>Final-turn routed database on the FFN.</b> The final route is this activity\'s last execution.'},
  ],
  risks:[
    '<b>Congestion treated as a routing problem.</b> Structural congestion cannot be routed around, and rip-up cycles spent on it consume time without converging.',
    '<b>Antenna violations left late.</b> Fixes need diodes or layer jumps, both of which need space that a fully routed design does not have.',
    '<b>DRC convergence assumed linear.</b> The last violations are the hardest, and planning as if the rate is constant produces a schedule that misses.',
    '<b>Manufacturability ignored until signoff.</b> DFM-clean routing is cheaper to produce than to retrofit, and <code>SO-08</code> finds what was not.',
    '<b>Layer plan not respecting the PDN.</b> Signals and the power grid contend for the same upper layers, and a plan that ignores the grid produces conflicts everywhere.',
  ],
  roles:[
    {r:'Routing lead', d:'Owns routing strategy and DRC convergence'},
    {r:'Routing engineers', d:'Global, detailed routing and violation fixing'},
    {r:'DFM engineer', d:'Manufacturability and litho-friendly routing'},
    {r:'Physical verification engineer', d:'DRC analysis and triage'},
    {r:'Floorplan owner', d:'Structural remedies for congestion'},
  ],
  effort:[['Detailed routing',11], ['DRC convergence',9], ['Global routing',7], ['Rip-up and reroute',6], ['Antenna and via optimization',4], ['Routing quality',3]],
  entry:[
    'Placement and clock trees available for the turn',
    'Metal stack and routing rules available from PDK-02',
    'PDN implemented in PD-03',
  ],
  exit:[
    'DRC clean at each turn, not only at the final one',
    'Congestion resolved structurally where it is structural',
    'Manufacturability addressed during routing, not after',
  ],
  dependsOn:['PD-03','PD-05','PD-07','PDK-02','PDK-10'],
  dependsNote:null,
  feedsInto:['PD-10','PD-13','PD-15','SO-03','SO-08'],
  measuredBy:[
    'DRC violations remaining per turn',
    'Rip-up cycles spent on structural congestion',
    'Antenna violations at first detailed route',
  ],
},

'PD-09': {
  stage:'physicalDesign', window:[8,30], criticalPath:true,
  purpose:[
    'Close <b>timing across every corner and every mode</b>—setup, hold, cross-corner, cross-mode—and drive the violation burn-down that decides the tapeout date.',
    'Twenty-two weeks and sixty man-months, the largest activity in the stage. Multi-corner multi-mode closure on a large die is a long grind of analysis, ECO and re-analysis, and its burn-down curve is the single best predictor the program has of whether it will tape out on time.',
  ],
  steps:[
    {n:1, text:'Timing setup and MMMC scenario definition', tat:1.5, lane:'main'},
    {n:2, text:'Setup timing closure', tat:3, lane:'main'},
    {n:3, text:'Violation burn-down tracking and reporting', tat:3, lane:'par'},
    {n:4, text:'Hold timing closure', tat:3, lane:'main'},
    {n:5, text:'Timing ECO generation and application', tat:3, lane:'par'},
    {n:6, text:'Cross-corner and cross-mode convergence', tat:3.5, lane:'main'},
    {n:7, text:'Signoff timing correlation with the SO flow', tat:3, lane:'par'},
    {n:8, text:'Continuous closure across turns', tat:11, lane:'main'},
  ],
  flowNote:'Step 7 prevents the worst surprise available. A design closed in the implementation tool and re-analyzed in the signoff tool will show differences; discovering their size early lets the team close with the right margin rather than re-closing after <code>SO-02</code> reports.',
  consumes:[
    'Placed and routed databases from each turn',
    'Constraints from SYN-01',
    'Corner and derate definition from PDK-11',
    'Clock trees from PD-07',
    'Signoff correlation from SO-12',
  ],
  produces:[
    'MMMC timing scenarios',
    'Setup timing closure results',
    'Violation burn-down tracking',
    'Setup and hold closure results',
    'Timing ECOs',
    'Cross-corner convergence results',
    'Signoff correlation findings',
    'Closure record across turns',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'PD-D5', rel:'produces', text:'<b>MCMM timing closure reports with violation burn-down across turns.</b> This activity is the deliverable, and the burn-down is the program\'s best schedule predictor.'},
    {id:'PD-D3', rel:'feeds', text:'<b>Final-turn routed database.</b> A database is only handed to signoff when this activity says it is closed.'},
  ],
  risks:[
    '<b>Closing at some corners and deferring others.</b> The deferred corner is the one that fails, and it fails when there is no time to fix it.',
    '<b>Implementation and signoff timing diverging.</b> A design closed in one tool and judged in another can be weeks from closure without anyone knowing.',
    '<b>Hold fixed after setup.</b> Hold fixes add buffers that change setup, and doing them sequentially means iterating both.',
    '<b>Burn-down not tracked.</b> Without a trend nobody can distinguish a design that is converging slowly from one that is not converging at all.',
    '<b>ECO volume exceeding what the database can absorb.</b> Thousands of ECOs degrade the physical result, and at some point a re-run is cheaper than another ECO round.',
  ],
  roles:[
    {r:'Timing closure lead', d:'Owns closure, burn-down and the tapeout prediction'},
    {r:'STA engineers', d:'Analysis, ECO generation and convergence'},
    {r:'Physical design engineers', d:'ECO application and re-route'},
    {r:'Signoff methodology engineer', d:'Correlation with the signoff flow'},
    {r:'Program manager', d:'Uses the burn-down for schedule decisions'},
  ],
  effort:[['Setup timing closure',15], ['Hold timing closure',12], ['Continuous closure across turns',12], ['Timing ECO generation',9], ['Cross-corner convergence',7], ['Signoff correlation',5]],
  entry:[
    'Routed database available from the current turn',
    'Corner and derate definition final from PDK-11',
    'Signoff flow available for correlation from SO-01',
  ],
  exit:[
    'Closed at every corner and mode, not a subset',
    'Implementation and signoff timing correlated within a stated tolerance',
    'Burn-down trend projecting closure before the tapeout date',
  ],
  dependsOn:['PD-05','PD-07','SYN-01','PDK-11'],
  dependsNote:null,
  feedsInto:['PD-13','PD-14','SO-02','SO-12','DV-11'],
  measuredBy:[
    'Violations remaining per corner and mode',
    'Implementation-to-signoff timing correlation',
    'Burn-down rate against the tapeout date',
  ],
},

'PD-10': {
  stage:'physicalDesign', window:[16,26], criticalPath:false,
  purpose:[
    'Fix what the routing did to the electricals—<b>crosstalk, noise, electromigration, dynamic IR</b>—before signoff has to reject the design for them.',
    'Signal and power integrity problems are created by routing and found by analysis. Crosstalk between adjacent nets, EM in high-current wires and dynamic IR under real switching are all consequences of physical decisions, and fixing them means changing routing that was closed for timing.',
  ],
  steps:[
    {n:1, text:'SI setup and crosstalk analysis', tat:1.5, lane:'main'},
    {n:2, text:'Crosstalk fixing — spacing, shielding, buffer sizing', tat:2.5, lane:'main'},
    {n:3, text:'Noise and glitch analysis', tat:2, lane:'par'},
    {n:4, text:'Electromigration analysis and fixing', tat:2.5, lane:'main'},
    {n:5, text:'Dynamic IR iteration with the PDN', tat:2, lane:'par'},
    {n:6, text:'SI and PI iteration and closure', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 6 is an iteration rather than a step, because every fix perturbs something else. Widening a wire for EM changes its coupling; adding shielding consumes routing resource; and both change timing, which sends the design back to <code>PD-09</code>.',
  consumes:[
    'Routed database from PD-08',
    'PDN from PD-03',
    'Switching activity from SYN-06 and DV-04',
    'Signoff SI/PI methodology from SO-05',
    'Package co-analysis findings from SIPI-04',
  ],
  produces:[
    'SI setup and crosstalk analysis',
    'Crosstalk fixes — spacing, shielding, sizing',
    'Noise and glitch analysis results',
    'Crosstalk analysis and fixes',
    'EM analysis and routing fixes',
    'Dynamic IR results and PDN adjustments',
    'SI and PI closure records',
  ],
  producedBy:[1,2,3,4,4,5,6],
  rel:[
    {id:'PD-D6', rel:'feeds', text:'<b>Interim physical DRC / LVS clean.</b> SI and EM fixes are routing changes, so they close together with DRC.'},
    {id:'PD-D5', rel:'feeds', text:'<b>MCMM timing closure reports.</b> Crosstalk-induced delay is part of timing, and SI fixes change timing in both directions.'},
  ],
  risks:[
    '<b>SI analyzed after timing closes.</b> Crosstalk delay is timing, and closing without it means closing against numbers that will move.',
    '<b>EM checked only on power.</b> High-toggle signal nets on advanced nodes carry EM exposure too, and they are usually the ones nobody checks.',
    '<b>Dynamic IR analyzed with uniform activity.</b> Real switching is bursty and localized, and uniform assumptions understate the worst case badly.',
    '<b>Fixes applied without re-timing.</b> Shielding and spacing change delay, and a fix that breaks timing has moved the problem rather than solved it.',
    '<b>Package effects excluded.</b> Die-only dynamic IR is optimistic; <code>SIPI-04</code> with package inductance is the number signoff will use.',
  ],
  roles:[
    {r:'SI/PI engineer', d:'Owns crosstalk, noise, EM and IR analysis'},
    {r:'Routing engineers', d:'Apply spacing, shielding and width fixes'},
    {r:'Power delivery engineer', d:'PDN adjustments for dynamic IR'},
    {r:'Timing engineer', d:'Re-timing after SI fixes'},
    {r:'SIPI liaison', d:'Package-aware IR and channel context'},
  ],
  effort:[['Crosstalk fixing',5], ['EM analysis and fixing',4.5], ['SI and PI iteration',3.5], ['Noise and glitch analysis',2.5], ['Dynamic IR iteration',2.5]],
  entry:[
    'Routed database available from PD-08',
    'Switching activity available from SYN-06',
    'Signoff SI/PI methodology agreed with SO-05',
  ],
  exit:[
    'Crosstalk included in timing closure, not analyzed after it',
    'EM checked on signal nets as well as power',
    'Dynamic IR analyzed with realistic, localized activity',
  ],
  dependsOn:['PD-03','PD-08','PD-09','SYN-06'],
  dependsNote:null,
  feedsInto:['PD-13','SO-04','SO-05','SIPI-04'],
  measuredBy:[
    'Crosstalk-induced delay against the timing budget',
    'EM violations at signoff',
    'Dynamic IR against budget with realistic activity',
  ],
},

'PD-11': {
  stage:'physicalDesign', window:[14,19], criticalPath:false,
  purpose:[
    'Extract the <b>chip power model</b> the package co-verification needs—per domain, per mode, with realistic switching—and hand it over as a versioned artifact.',
    '<code>SIPI-03</code> cannot analyze the die, package and board as one power delivery network without a model of the die\'s current draw. Producing that model is a small activity with an outsized dependency: without it the co-verification cannot start, and the co-verification gates mask release.',
  ],
  steps:[
    {n:1, text:'Power model requirement definition with SIPI', tat:1, lane:'main'},
    {n:2, text:'CPM extraction per domain and operating mode', tat:1.5, lane:'main'},
    {n:3, text:'Switching scenario selection for the extraction', tat:1, lane:'par'},
    {n:4, text:'Model validation against internal IR analysis', tat:1.5, lane:'main'},
    {n:5, text:'Handoff and version control', tat:1, lane:'main'},
  ],
  flowNote:'Step 3 determines whether the model is useful. A CPM extracted under average activity understates the transient the package has to supply; extracting under the worst realistic burst is what makes <code>SIPI-04</code>\'s answer meaningful.',
  consumes:[
    'Placed and routed database from PD-05 or PD-06',
    'PDN from PD-03',
    'Switching activity from DV-04 and SYN-06',
    'Model format requirements from SIPI-01',
    'Power domain definition from ARCH-05',
  ],
  produces:[
    'Power model requirement definition',
    'Chip power model per domain and mode',
    'Switching scenario selection record',
    'Model validation against internal IR',
    'Versioned model handoff',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'PD-D4', rel:'feeds', text:'<b>Floorplan and PDN specification.</b> The power model is the PDN\'s behavior expressed for external consumers.'},
    {id:'PD-D7', rel:'feeds', text:'<b>Bump map, RDL and package interface files.</b> The model is part of what the package side needs alongside the physical interface.'},
  ],
  risks:[
    '<b>Model extracted under average activity.</b> The package has to supply the transient, and an averaged model hides exactly the event that matters.',
    '<b>Delivered late.</b> Co-verification is on the critical path to mask release, and it cannot start without this model.',
    '<b>Model not validated.</b> A CPM that disagrees with the die\'s own IR analysis is wrong in one of the two places, and nobody knows which.',
    '<b>Single model for all modes.</b> Different DVFS points and workloads draw very differently, and one model cannot represent them.',
    '<b>No version control.</b> The package team analyzing against a stale model produces conclusions about a die that no longer exists.',
  ],
  roles:[
    {r:'Power modeling engineer', d:'Owns extraction and validation'},
    {r:'Power delivery engineer', d:'Internal IR correlation'},
    {r:'SIPI liaison', d:'Model format and scenario requirements'},
    {r:'Verification liaison', d:'Realistic switching scenarios'},
    {r:'Configuration manager', d:'Model versioning and handoff'},
  ],
  effort:[['CPM extraction',2.5], ['Model validation',1.5], ['Requirement definition',1], ['Handoff and version control',1]],
  entry:[
    'Placed and routed database available',
    'PDN implemented in PD-03',
    'Model format agreed with SIPI-01',
  ],
  exit:[
    'Model extracted under realistic worst-case switching',
    'Validated against the die\'s own IR analysis',
    'Delivered versioned, on the date SIPI needs it',
  ],
  dependsOn:['PD-03','PD-05','SIPI-01','DV-04'],
  dependsNote:null,
  feedsInto:['SIPI-01','SIPI-03','SIPI-04','SO-06'],
  measuredBy:[
    'Model delivery against the SIPI need date',
    'Validation agreement with internal IR',
    'Modes modelled against modes the product uses',
  ],
},

'PD-12': {
  stage:'physicalDesign', window:[16,22], criticalPath:false,
  purpose:[
    'Reorder and route the <b>scan chains physically</b>—shorter routes, less congestion—without destroying the chain-to-block mapping diagnosis depends on.',
    'Scan chains as stitched by synthesis follow logical order and route terribly. Physical reordering fixes the routing and can scramble the relationship between chain position and physical location, which is exactly what failure diagnosis uses. Both constraints are real.',
  ],
  steps:[
    {n:1, text:'Scan chain physical analysis and routing cost', tat:1, lane:'main'},
    {n:2, text:'Chain reordering for routing efficiency', tat:1.5, lane:'main'},
    {n:3, text:'Diagnosis mapping preservation', tat:1, lane:'par'},
    {n:4, text:'DFT-aware routing and shielding of test paths', tat:1.5, lane:'main'},
    {n:5, text:'Test clock routing and skew', tat:1, lane:'par'},
    {n:6, text:'Chain verification after reorder', tat:2, lane:'main'},
  ],
  flowNote:'Step 6 is not optional. Reordering rewrites the netlist\'s scan connectivity, and a chain broken by the reorder makes everything behind it untestable—a failure that would otherwise be discovered at ATE bring-up.',
  consumes:[
    'Scan-inserted netlist from DFT-06',
    'Physical DFT plan from DFT-09',
    'Placement from the current turn',
    'Routing resource from PD-08',
    'Test clock architecture from DFT-05',
  ],
  produces:[
    'Chain routing cost analysis',
    'Reordered scan chains',
    'Diagnosis mapping record',
    'DFT-aware routing and shielding',
    'Test clock routing',
    'Post-reorder chain verification results',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PD-D6', rel:'feeds', text:'<b>Interim physical DRC / LVS clean.</b> Scan routing is routing, and it closes with everything else.'},
    {id:'PD-D3', rel:'feeds', text:'<b>Final-turn routed database.</b> The chains in the final database are the ones ATPG patterns were generated against.'},
  ],
  risks:[
    '<b>Reordering breaking diagnosis.</b> Failure analysis relies on mapping a failing bit to a physical location, and a scrambled chain removes that.',
    '<b>Chains not verified after reorder.</b> A break makes everything behind it untestable, and ATE bring-up is a costly place to find that.',
    '<b>Patterns generated before the final reorder.</b> Any chain change after <code>DFT-07</code> invalidates the pattern set and costs weeks of regeneration.',
    '<b>Test clock skew ignored.</b> Scan shift reaches every flop, and skew on the shift clock produces shift failures that look like design bugs.',
    '<b>Chain imbalance after reorder.</b> Physical reordering can lengthen one chain and shorten another, and shift time follows the longest.',
  ],
  roles:[
    {r:'DFT physical engineer', d:'Owns reordering and post-reorder verification'},
    {r:'Routing engineers', d:'Scan routing and shielding'},
    {r:'Diagnosis engineer', d:'Mapping preservation requirements'},
    {r:'ATPG engineer', d:'Pattern regeneration if chains change'},
    {r:'Clock engineer', d:'Test clock routing and skew'},
  ],
  effort:[['Chain reordering',2.5], ['DFT-aware routing',2], ['Post-reorder verification',1.5], ['Diagnosis mapping',1], ['Test clock routing',1]],
  entry:[
    'Scan-inserted netlist available from DFT-06',
    'Physical DFT plan agreed in DFT-09',
    'Placement available for the turn',
  ],
  exit:[
    'Chains verified after every reorder',
    'Diagnosis mapping preserved or explicitly traded',
    'Chain order frozen before ATPG generates patterns',
  ],
  dependsOn:['DFT-06','DFT-09','PD-08'],
  dependsNote:null,
  feedsInto:['DFT-07','PD-13','SO-03'],
  measuredBy:[
    'Routing resource saved by reordering',
    'Chain integrity after reorder',
    'Chain order changes after pattern generation',
  ],
},

'PD-13': {
  stage:'physicalDesign', window:[19,30], criticalPath:true,
  purpose:[
    'Run the <b>final turn on the FFN and close it completely</b>—timing, power, DRC, LVS—with no functional change admitted and no next turn to fall back on.',
    'Everything the stage has done is preparation for this. Fifty-five man-months over eleven weeks, on a frozen netlist, closing every corner and every mode to signoff standard. The discipline that matters is refusing functional change: an ECO that alters behavior restarts verification, and there is no schedule for that.',
  ],
  steps:[
    {n:1, text:'FFN intake and delta assessment against N2', tat:1, lane:'main'},
    {n:2, text:'Placement on the final netlist', tat:2, lane:'main'},
    {n:3, text:'ECO-only change discipline and gatekeeping', tat:1.5, lane:'par'},
    {n:4, text:'Final clock tree synthesis', tat:2, lane:'main'},
    {n:5, text:'Power and IR final convergence', tat:2, lane:'par'},
    {n:6, text:'Final routing', tat:2.5, lane:'main'},
    {n:7, text:'DRC and LVS convergence', tat:2, lane:'par'},
    {n:8, text:'Final timing closure across all corners and modes', tat:2, lane:'main'},
    {n:9, text:'Closure reporting and remaining-violation disposition', tat:1.5, lane:'par'},
    {n:10, text:'Database freeze and signoff handoff', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 3 runs across the whole turn and is a gate rather than a task. Every change request during the final turn has to be classified—timing ECO, functional change, or bug fix—and only the first is admitted without escalation.',
  consumes:[
    'FFN and handoff package from SYN-09 and SYN-12',
    'Turn 2 database and risk from PD-06',
    'Clock trees from PD-07',
    'SI/PI fixes from PD-10',
    'ECO infrastructure from PD-14',
  ],
  produces:[
    'FFN intake and delta assessment',
    'Placement on the final netlist',
    'ECO discipline records',
    'Final clock tree',
    'Final power and IR convergence results',
    'Final placed, clocked and routed database',
    'DRC and LVS clean results',
    'Final timing closure across corners and modes',
    'Closure report with remaining-violation disposition',
    'Frozen signoff-ready database',
  ],
  producedBy:[1,2,3,4,5,6,7,8,9,10],
  rel:[
    {id:'PD-D3', rel:'produces', text:'<b>Final-turn routed database on the FFN, per block and top.</b> This activity is the deliverable, and it is what signoff and tapeout consume.'},
    {id:'PD-D5', rel:'feeds', text:'<b>MCMM timing closure reports.</b> The final turn\'s closure report is the one Design Freeze is granted against.'},
  ],
  risks:[
    '<b>Functional change admitted during the final turn.</b> It restarts verification and equivalence, and no schedule allows for that at this point.',
    '<b>Closure gap larger than turn 2 predicted.</b> If the prediction was optimistic, the discovery comes with no remaining turns and only concessions available.',
    '<b>ECO volume degrading the database.</b> Thousands of ECOs on a final database produce a physical result worse than a clean re-run, but a re-run costs weeks.',
    '<b>Remaining violations dispositioned informally.</b> Every violation that survives to signoff must be a named, accepted waiver rather than an oversight.',
    '<b>Database frozen before LVS is clean.</b> A handoff that fails LVS at <code>SO-03</code> sends everything back with no time to spare.',
  ],
  roles:[
    {r:'Physical design lead', d:'Owns the final turn and the freeze'},
    {r:'Placement, CTS and routing engineers', d:'Final turn execution'},
    {r:'Timing closure lead', d:'Final closure across corners and modes'},
    {r:'Program manager', d:'Gatekeeps functional change requests'},
    {r:'Signoff lead', d:'Accepts the database for signoff'},
  ],
  effort:[['Final timing closure',14], ['Final routing',11], ['Placement',9], ['Final clock tree synthesis',7], ['Power and IR convergence',6], ['DRC and LVS convergence',5], ['Freeze and handoff',3]],
  entry:[
    'FFN released by SYN-09 against frozen RTL',
    'Turn 2 closure risk understood from PD-06',
    'ECO infrastructure running from PD-14',
  ],
  exit:[
    'Closed at every corner and mode to signoff standard',
    'No functional change admitted, or each one escalated and recorded',
    'Database frozen LVS-clean and accepted by signoff',
  ],
  dependsOn:['PD-06','PD-07','PD-10','SYN-09','SYN-12'],
  dependsNote:null,
  feedsInto:['SO-02','SO-03','SO-09','TO-01','PD-16'],
  measuredBy:[
    'Functional changes admitted during the final turn',
    'Closure achieved against the turn-2 prediction',
    'Violations dispositioned as waivers against oversights',
  ],
},

'PD-14': {
  stage:'physicalDesign', window:[12,30], criticalPath:false,
  purpose:[
    'Run the <b>ECO machinery</b>—flow, spare cells, metal-only strategy, impact tracking—that every turn depends on and that the final turn depends on absolutely.',
    'ECOs are how a closed design absorbs change without a full re-run. The infrastructure matters more than any individual ECO: a spare cell strategy decided at floorplan time determines whether a late fix is metal-only or needs a base layer change, and that distinction is worth several weeks and a mask set.',
  ],
  steps:[
    {n:1, text:'ECO flow and methodology setup', tat:1.5, lane:'main'},
    {n:2, text:'Functional ECO implementation capability', tat:2.5, lane:'main'},
    {n:3, text:'ECO impact assessment and tracking', tat:2, lane:'par'},
    {n:4, text:'Timing ECO implementation', tat:2.5, lane:'main'},
    {n:5, text:'Spare cell and metal-only ECO strategy', tat:2, lane:'par'},
    {n:6, text:'Continuous ECO operation across turns', tat:11.5, lane:'main'},
  ],
  flowNote:'Step 5 is decided early and matters late. Spare cells distributed through the floorplan cost area now and make a metal-only fix possible at tapeout; without them, a late functional fix needs base layers and a full mask set.',
  consumes:[
    'Change requests from RTL-10, DV-12 and timing closure',
    'Placed and routed databases from each turn',
    'Spare cell placement from PD-02',
    'ECO flow support from PDK-09',
    'Timing ECOs from PD-09',
  ],
  produces:[
    'ECO flow and methodology',
    'Functional ECO implementation capability',
    'Impact assessment and tracking records',
    'Timing ECO implementation',
    'Spare cell and metal-only strategy',
    'ECO log across turns',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PD-D8', rel:'produces', text:'<b>ECO log and change control record.</b> This activity is the deliverable, and the log is what makes a late database traceable to the design that was verified.'},
    {id:'PD-D3', rel:'feeds', text:'<b>Final-turn routed database.</b> The final database is the FFN plus its ECO history, and the two are inseparable.'},
  ],
  risks:[
    '<b>No spare cell strategy.</b> A late functional fix then requires base layers and a full mask set rather than a metal-only change.',
    '<b>ECOs applied without impact tracking.</b> A database with untracked changes cannot be reconciled against the netlist that was verified.',
    '<b>ECO volume unbounded.</b> Beyond some number, the physical result degrades enough that a clean re-run would be better—and nobody notices the crossing point.',
    '<b>Functional and timing ECOs not distinguished.</b> They have completely different verification consequences, and conflating them lets functional change in unnoticed.',
    '<b>Spare cells consumed early.</b> Using them for convenience during turn 1 leaves none for the fix that actually needs them at tapeout.',
  ],
  roles:[
    {r:'ECO lead', d:'Owns the flow, the strategy and the log'},
    {r:'Physical design engineers', d:'ECO implementation'},
    {r:'Timing engineers', d:'Timing ECO generation'},
    {r:'Verification liaison', d:'Functional ECO verification requirements'},
    {r:'Configuration manager', d:'ECO log and database traceability'},
  ],
  effort:[['Continuous ECO operation',8], ['Timing ECO implementation',5], ['Functional ECO implementation',4], ['Impact assessment and tracking',3], ['Spare cell strategy',2]],
  entry:[
    'ECO flow available from PDK-09',
    'Spare cell placement decided in PD-02',
    'Change control process running in RTL-10',
  ],
  exit:[
    'Metal-only fix path available at tapeout',
    'Every ECO tracked and reconcilable against the netlist',
    'Functional and timing ECOs distinguished in the log',
  ],
  dependsOn:['PD-02','PD-09','PDK-09','RTL-10'],
  dependsNote:null,
  feedsInto:['PD-13','TO-08','SO-09','TO-03'],
  measuredBy:[
    'Spare cells remaining at tapeout',
    'ECOs tracked against ECOs applied',
    'Metal-only fixes possible against fixes needed',
  ],
},

'PD-15': {
  stage:'physicalDesign', window:[24,29], criticalPath:false,
  purpose:[
    'Finish the die as a <b>manufacturable object</b>—seal ring, metal fill, dummy, alignment marks, identification—and verify that none of it broke what was closed.',
    'Chip finishing is mechanical and it is not free. Metal fill changes coupling capacitance and therefore timing; the seal ring consumes die edge; and dummy fill interacts with the analog matching that <code>AMS-12</code> spent weeks building. Every one has to be applied and then re-verified.',
  ],
  steps:[
    {n:1, text:'Seal ring and die edge implementation', tat:1, lane:'main'},
    {n:2, text:'Metal fill and density compliance', tat:1, lane:'main'},
    {n:3, text:'Fill impact on timing and extraction', tat:1, lane:'par'},
    {n:4, text:'Alignment marks, logos and die identification', tat:1.5, lane:'main'},
    {n:5, text:'Dummy and CMP compliance', tat:1, lane:'par'},
    {n:6, text:'Finishing verification against the closed database', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 3 is why finishing is not a formality. Fill adds capacitance to every net near it, and a design closed before fill and taped out after it has been signed off against a database that no longer exists.',
  consumes:[
    'Routed database from PD-08 and PD-13',
    'Seal ring and frame rules from PDK-02',
    'Fill and density rules from the DRM',
    'Analog macro fill exclusions from AMS-12',
    'Die identification requirements from MP-09',
  ],
  produces:[
    'Seal ring and die edge implementation',
    'Metal fill meeting density rules',
    'Fill timing impact analysis',
    'Alignment marks and die identification',
    'Dummy and CMP compliance',
    'Finishing verification results',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PD-D3', rel:'feeds', text:'<b>Final-turn routed database.</b> The database handed to tapeout is the finished one, and the finishing is part of it.'},
    {id:'PD-D6', rel:'feeds', text:'<b>Interim physical DRC / LVS clean.</b> Density and fill rules are DRC rules, and finishing is where they are met.'},
  ],
  risks:[
    '<b>Timing signed off before fill.</b> The taped-out database has fill and the signed-off one did not, which is a signoff against a different design.',
    '<b>Fill applied over analog matching structures.</b> It disturbs the parasitics <code>AMS-12</code> tuned, and the damage is invisible until silicon characterization.',
    '<b>Seal ring area not reserved.</b> Discovered late, it forces the die edge inward and moves the bump map.',
    '<b>Die identification omitted.</b> Traceability at yield analysis and field return depends on being able to identify the die, and it cannot be added later.',
    '<b>Finishing treated as a checkbox.</b> Each step changes the physical database, and each needs verification against what was closed.',
  ],
  roles:[
    {r:'Chip finishing engineer', d:'Owns seal ring, fill and marks'},
    {r:'Physical verification engineer', d:'Density and DRC compliance'},
    {r:'Timing engineer', d:'Fill impact on extraction and timing'},
    {r:'Analog layout liaison', d:'Fill exclusions around matching structures'},
    {r:'Product engineering', d:'Die identification and traceability requirements'},
  ],
  effort:[['Metal fill and density',2], ['Seal ring and die edge',1.5], ['Finishing verification',1], ['Fill timing impact',0.75], ['Marks and identification',0.75]],
  entry:[
    'Routed database stable from PD-08',
    'Fill and seal ring rules available from PDK-02',
    'Analog fill exclusions defined by AMS-12',
  ],
  exit:[
    'Timing verified after fill, not before it',
    'Analog matching structures protected from fill',
    'Die identification present and readable',
  ],
  dependsOn:['PD-08','PD-13','PDK-02','AMS-12'],
  dependsNote:null,
  feedsInto:['TO-01','SO-03','SO-08','MP-09'],
  measuredBy:[
    'Timing delta introduced by fill',
    'Density compliance across the die',
    'Analog structures affected by fill',
  ],
},

'PD-16': {
  stage:'physicalDesign', window:[14,28], criticalPath:true,
  purpose:[
    'Close the <b>blocks independently and assemble them into a top level</b> that meets timing across their boundaries—the hierarchical discipline a die this size requires.',
    'A design of this size cannot be closed flat: runtime and capacity make it impossible. Hierarchical closure lets blocks converge in parallel, at the cost of interface budgets that have to be right. A block that closes internally and misses its boundary budget has not helped.',
  ],
  steps:[
    {n:1, text:'Block closure criteria and handoff definition', tat:1.5, lane:'main'},
    {n:2, text:'Block-level closure', tat:3, lane:'main'},
    {n:3, text:'Inter-block timing budget and interface closure', tat:2.5, lane:'par'},
    {n:4, text:'Block abstract and timing model generation', tat:3, lane:'main'},
    {n:5, text:'Top-level routing and feedthrough management', tat:2.5, lane:'par'},
    {n:6, text:'Top-level assembly', tat:3, lane:'main'},
    {n:7, text:'Hierarchical timing correlation, block model against flat', tat:2, lane:'par'},
    {n:8, text:'Top-level integration verification', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 7 is the check that keeps hierarchy honest. A block\'s timing model is an abstraction, and if it disagrees with a flat analysis of the same block then the top level has been closed against a fiction.',
  consumes:[
    'Partition definition from PD-02',
    'Block databases from each turn',
    'Interface budgets from ARCH-06',
    'Timing closure status from PD-09',
    'Final database from PD-13',
  ],
  produces:[
    'Block closure criteria',
    'Block-level closure results',
    'Inter-block timing budgets',
    'Block abstracts and timing models',
    'Top-level routing and feedthroughs',
    'Assembled top level',
    'Closed block databases',
    'Assembled and verified top level',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'PD-D9', rel:'produces', text:'<b>Signoff-ready database handoff.</b> This activity is the deliverable—the assembled top level signoff and tapeout actually consume.'},
    {id:'PD-D3', rel:'feeds', text:'<b>Final-turn routed database on the FFN, per block and top.</b> The per-block half of the deliverable comes from here.'},
  ],
  risks:[
    '<b>Block models disagreeing with flat analysis.</b> The top level is then closed against an abstraction that does not represent the block.',
    '<b>Interface budgets set late.</b> Blocks close internally and fail at their boundaries, and the fix requires reopening blocks that were declared done.',
    '<b>Feedthroughs not planned.</b> Signals crossing a block have to be routed through it, and a block closed without feedthrough provision blocks the top level.',
    '<b>Blocks closed to different criteria.</b> Without an enforced standard, each block closes to what its owner considered sufficient, and the top level inherits the weakest.',
    '<b>Top-level assembly left to the end.</b> Assembly finds interface problems, and finding them after the final turn leaves no time to fix them.',
  ],
  roles:[
    {r:'Hierarchical closure lead', d:'Owns block criteria, budgets and assembly'},
    {r:'Block physical owners', d:'Close their blocks to the criteria'},
    {r:'Top-level integration engineer', d:'Assembly, feedthroughs and top routing'},
    {r:'Timing engineer', d:'Hierarchical correlation against flat analysis'},
    {r:'Physical verification engineer', d:'Top-level integration verification'},
  ],
  effort:[['Block-level closure',8], ['Top-level assembly',6], ['Integration verification',5], ['Abstract and model generation',4], ['Interface budgets',4], ['Top-level routing',3]],
  entry:[
    'Partitions defined in PD-02',
    'Interface budgets available from ARCH-06',
    'Blocks converging in PD-09',
  ],
  exit:[
    'Block models correlated against flat analysis',
    'Every block closed to one shared criterion',
    'Top level assembled and verified before the final turn ends',
  ],
  dependsOn:['PD-02','PD-09','PD-13','ARCH-06'],
  dependsNote:null,
  feedsInto:['SO-02','SO-03','SO-09','TO-01'],
  measuredBy:[
    'Block model to flat analysis correlation',
    'Interface violations at assembly',
    'Blocks closed to the shared criterion',
  ],
},

};
