/* PDK — PDK & Design Enablement. Thirteen activities. Stage w8–44 (36w), 97 M/M. */
module.exports = {

'PDK-01': {
  stage:'pdk', window:[0,34], criticalPath:true,
  purpose:[
    'Track what the foundry actually ships, version by version, and turn each release into <b>a delta the program can act on</b>—what changed, what it costs, and whether anything already done has to be redone.',
    'A PDK is not a thing you receive; it is a sequence. Design starts on 0.5 because waiting for production would cost two quarters, and the 0.5-to-1.0 delta then arrives in the middle of physical design. Whether that delta is a two-week re-characterization or a reopened timing signoff depends entirely on whether anyone was watching.',
  ],
  steps:[
    {n:1, text:'Release calendar and version tracking framework', tat:1, lane:'main'},
    {n:2, text:'0.1 to 0.5 delta impact analysis', tat:4, lane:'main'},
    {n:3, text:'Gap list maintained against what the design actually needs', tat:3, lane:'par'},
    {n:4, text:'0.5 to 1.0 delta impact analysis', tat:5, lane:'main'},
    {n:5, text:'Library and deck re-qualification per version', tat:6, lane:'par'},
    {n:6, text:'Production PDK adoption and version freeze decision', tat:4, lane:'main'},
    {n:7, text:'Version freeze policy and exception handling', tat:3, lane:'par'},
    {n:8, text:'Readiness dashboard maintenance across the stage', tat:20, lane:'main'},
  ],
  flowNote:'Step 8 runs for twenty of the thirty-four weeks and is the activity most likely to be dropped when the team is busy. It is also the only artifact that tells the program which of its assumptions have quietly expired.',
  consumes:[
    'Foundry PDK release calendar and notes',
    'Selected node and flavor sheet from TECH-01 and TECH-02',
    'Design agreement access from TECH-06',
    'Library and deck versions in use across the teams',
    'Design status — what has been characterized against which version',
  ],
  produces:[
    'Release calendar and version tracking framework',
    '0.1-to-0.5 delta impact analysis',
    'Open gap list against the design\'s requirements',
    'Delta impact analysis per version transition',
    'Re-qualification record per library and deck',
    'Production PDK adoption and freeze decision',
    'Version freeze decision and exception log',
    'PDK readiness dashboard, maintained',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'PDK-D1', rel:'produces', text:'<b>PDK readiness dashboard.</b> This activity is the deliverable, and it is a living document rather than a report—its value is entirely in being current.'},
    {id:'PDK-D2', rel:'feeds', text:'<b>Qualified library list.</b> Every version transition potentially invalidates a qualification, and this activity is what says which ones.'},
    {id:'PDK-D8', rel:'gates', text:'<b>Golden environment release notes.</b> The environment cannot be released against a version that has not been assessed and frozen.'},
  ],
  risks:[
    '<b>Design starts on a version the foundry calls preliminary and nobody re-checks.</b> The gap between 0.5 and production has reopened timing signoff on more than one program.',
    '<b>Delta analysis done on the release notes alone.</b> Foundry notes describe what changed; only re-running the design\'s own characterization says what it costs here.',
    '<b>Teams on different versions.</b> Synthesis on one library revision and physical design on another produces a mismatch that looks like a tool bug for weeks.',
    '<b>Freeze declared without an exception path.</b> A hard freeze with no route for a critical fix gets broken quietly, which is worse than breaking it openly.',
    '<b>Dashboard maintained until the team gets busy.</b> A stale readiness dashboard is more dangerous than none, because it is still trusted.',
  ],
  roles:[
    {r:'PDK owner', d:'Owns the dashboard, the deltas and the freeze decision'},
    {r:'CAD methodology engineer', d:'Re-qualification and deck version alignment'},
    {r:'Library engineer', d:'Library re-characterization per version'},
    {r:'Foundry technical contact', d:'Release calendar, notes and interpretation'},
    {r:'Physical design liaison', d:'States what a delta costs in the flow'},
  ],
  effort:[['Dashboard maintenance',4], ['Delta impact analyses',5], ['Gap list against design needs',2], ['Re-qualification coordination',2], ['Freeze policy and exceptions',1]],
  entry:[
    'Design agreement executed so PDK access is legal',
    'Node and flavor selected',
    'Release calendar obtained from the foundry',
  ],
  exit:[
    'Every version transition assessed before adoption, not after',
    'All teams on one recorded version, with exceptions logged',
    'Production PDK adopted and frozen with an exception path defined',
  ],
  dependsOn:['TECH-01','TECH-02','TECH-06'],
  dependsNote:null,
  feedsInto:['PDK-03','PDK-10','PDK-13','SYN-01','PD-01','SO-10'],
  measuredBy:[
    'Days between a foundry release and its delta assessment',
    'Teams on the recorded version against the total',
    'Signoff reopened by a PDK change',
  ],
},

'PDK-02': {
  stage:'pdk', window:[1,7], criticalPath:false,
  purpose:[
    'Read the design rule manual as a <b>constraint on this design</b> rather than as a document—identify which restricted rules bite, dispose of every recommended rule, and get the exceptions requested early.',
    'Restricted and recommended rules are where a node\'s real density lives. A design that adopts every recommended rule is safe and large; one that ignores them is dense and fails DFM. The disposition is a series of deliberate trades, and making them here is far cheaper than discovering them as violations at physical verification.',
  ],
  steps:[
    {n:1, text:'DRM ingestion and change log against the previous node', tat:1, lane:'main'},
    {n:2, text:'Restricted rule identification and impact assessment', tat:1.5, lane:'main'},
    {n:3, text:'Recommended rule disposition — adopt, waive or defer', tat:1.5, lane:'main'},
    {n:4, text:'Density and spacing rule impact on the floorplan', tat:1, lane:'par'},
    {n:5, text:'Rule exception request preparation for the foundry', tat:1, lane:'par'},
    {n:6, text:'DRM review record and distribution to the design teams', tat:2, lane:'main'},
  ],
  flowNote:'Exception requests in step 5 run in parallel because the foundry\'s response time is measured in weeks. Submitting them at the end of the review rather than as each one is identified adds a month to the answer.',
  consumes:[
    'Design rule manual for the selected node and flavor',
    'Previous-node DRM for comparison',
    'Floorplan intent from ARCH-08',
    'Custom and analog design intent from AMS-01',
    'Foundry exception request process',
  ],
  produces:[
    'Rule change log against the previous node',
    'Restricted rule impact assessment',
    'Recommended rule disposition record',
    'Density and spacing rule impact on the floorplan',
    'Exception requests submitted to the foundry',
    'DRM review record for the design teams',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PDK-D1', rel:'feeds', text:'<b>PDK readiness dashboard.</b> An outstanding exception request is a readiness gap, and it belongs on the dashboard with a date.'},
    {id:'PDK-D5', rel:'feeds', text:'<b>Internal reference flow and methodology guide.</b> Rule dispositions become flow settings—what the tools are told to enforce and what they are told to allow.'},
  ],
  risks:[
    '<b>Recommended rules adopted wholesale.</b> Safe, and it costs density the product was sized against; the trade should be made per rule, not once.',
    '<b>Restricted rules discovered at physical verification.</b> A restricted rule that bites is a layout change, and finding it at <code>SO-02</code> means finding it after routing closed.',
    '<b>Exception requests batched to the end.</b> Foundry turnaround runs to weeks per request; batching them converts a parallel wait into a serial one.',
    '<b>Analog rules read only by the digital team.</b> Pushed-rule and analog-specific sections matter to <code>AMS-07</code>, and they are the sections a digital-led review skips.',
    '<b>Disposition never distributed.</b> A decision the layout engineers never saw is a decision that does not exist.',
  ],
  roles:[
    {r:'CAD methodology lead', d:'Owns the disposition and the review record'},
    {r:'Physical design representative', d:'Floorplan and routing impact of each rule'},
    {r:'Custom layout representative', d:'Analog and pushed-rule sections'},
    {r:'DFM engineer', d:'Density, spacing and manufacturability trades'},
    {r:'Foundry technical contact', d:'Exception requests and interpretation'},
  ],
  effort:[['Rule impact assessment',2], ['Disposition decisions',1.5], ['Exception preparation',0.75], ['Review record and distribution',0.75]],
  entry:[
    'DRM released for the selected node and flavor',
    'Floorplan intent available from ARCH-08',
    'Exception request process agreed with the foundry',
  ],
  exit:[
    'Every recommended rule dispositioned with a reason, not defaulted',
    'Exception requests submitted, with expected response dates',
    'Disposition distributed to digital and custom teams alike',
  ],
  dependsOn:['TECH-02','PDK-01'],
  dependsNote:null,
  feedsInto:['PDK-09','PDK-10','AMS-07','PD-06','SO-06'],
  measuredBy:[
    'Recommended rules dispositioned against those in the DRM',
    'Exception requests answered before physical design starts',
    'Rule violations at signoff traceable to a missed disposition',
  ],
},

'PDK-03': {
  stage:'pdk', window:[4,12], criticalPath:true,
  purpose:[
    'Choose the standard cell libraries the design will be built from and <b>qualify them rather than assume them</b>—track height, Vt menu, multi-bit flops, and the timing models every downstream tool will trust.',
    'Library selection is a PPA decision disguised as a procurement one. Track height sets density and drive strength; the Vt menu sets leakage; multi-bit flops set clock power. And a timing model that is wrong at one corner produces a design that closes in the tool and fails in silicon, which is the failure mode nobody catches until bring-up.',
  ],
  steps:[
    {n:1, text:'Track height and library family selection', tat:1, lane:'main'},
    {n:2, text:'Multi-Vt menu qualification against the flavor sheet', tat:1.5, lane:'main'},
    {n:3, text:'Multi-bit flop and special cell evaluation', tat:1.5, lane:'par'},
    {n:4, text:'Timing model quality check across corners', tat:2, lane:'main'},
    {n:5, text:'Physical view and abstract consistency check', tat:1.5, lane:'par'},
    {n:6, text:'Library re-characterization where the foundry data is thin', tat:2, lane:'par'},
    {n:7, text:'Qualification record and library freeze', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 4 is the step that earns the activity. Foundry timing models are qualified by the foundry against the foundry\'s test cases; checking them at this design\'s corners and slew ranges is what catches the model error before it becomes a silicon failure.',
  consumes:[
    'Flavor sheet from TECH-02',
    'DTCO findings from TECH-03',
    'PDK release under tracking from PDK-01',
    'PPA targets and clock power budget from ARCH-06',
    'Foundry library release notes and characterization data',
  ],
  produces:[
    'Library family and track height selection record',
    'Qualified Vt menu with leakage projections',
    'Multi-bit and special cell evaluation',
    'Timing model quality report across corners',
    'Physical view and abstract consistency findings',
    'Re-characterization results where foundry data was thin',
    'Library qualification record and freeze',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'PDK-D2', rel:'produces', text:'<b>Qualified library list with .lib / LEF / GDS views.</b> The standard cell half of the deliverable; <code>PDK-04</code> adds memory and <code>PDK-07</code> adds IO.'},
    {id:'PDK-D1', rel:'feeds', text:'<b>PDK readiness dashboard.</b> An unqualified library is a readiness gap that blocks synthesis, and it shows on the dashboard as one.'},
    {id:'PDK-D6', rel:'feeds', text:'<b>Signoff corner definition.</b> The corners a library is characterized at bound the corners signoff can be run at.'},
  ],
  risks:[
    '<b>Timing models trusted without a quality check.</b> A model error at one corner produces a design that closes in the tool and fails on silicon—the most expensive class of library defect.',
    '<b>Track height chosen from the previous program.</b> Density and drive strength trade differently at each node; inheriting the choice inherits an answer to a question nobody asked here.',
    '<b>Vt menu wider than the flow can maintain.</b> Every Vt is a characterization, a qualification and a maintenance burden across every version transition.',
    '<b>Multi-bit flops evaluated after synthesis starts.</b> Clock power is largely decided by flop banking, and retrofitting it means re-running synthesis and re-closing timing.',
    '<b>LEF and GDS inconsistency.</b> An abstract that disagrees with the layout produces DRC violations at the very end, after routing has been built on the abstract.',
  ],
  roles:[
    {r:'Library lead', d:'Owns the selection, the qualification and the freeze'},
    {r:'Characterization engineer', d:'Timing model checks and re-characterization'},
    {r:'Synthesis liaison', d:'Vt menu and multi-bit flop implications'},
    {r:'Physical design liaison', d:'Track height, abstracts and routing resource'},
    {r:'Foundry library contact', d:'Release data, known issues and fixes'},
  ],
  effort:[['Library re-characterization',3], ['Timing model quality checks',2], ['Vt menu qualification',1.5], ['Special cell evaluation',1], ['Qualification record and freeze',1.5]],
  entry:[
    'Flavor sheet agreed by TECH-02',
    'Library release available under the design agreement',
    'PPA and clock power budget available from ARCH-06',
  ],
  exit:[
    'Timing models checked at this design\'s corners, not only the foundry\'s',
    'Vt menu frozen with a maintenance owner per corner',
    'Abstract and layout views confirmed consistent',
  ],
  dependsOn:['TECH-02','TECH-03','PDK-01'],
  dependsNote:null,
  feedsInto:['PDK-11','PDK-13','ARCH-01','ARCH-05','SYN-02','PD-05'],
  measuredBy:[
    'Corners with a validated timing model',
    'Library defects found downstream against those found here',
    'Vt menu size against the flow\'s maintenance capacity',
  ],
},

'PDK-04': {
  stage:'pdk', window:[6,15], criticalPath:true,
  purpose:[
    'Get the memory compiler licensed, evaluate what it can actually produce, and <b>generate the instances the design asked for</b>—with every view a downstream tool needs.',
    'On an inference accelerator the memory array is a large fraction of the die, and the compiler decides most of it. What the compiler can generate is a hard boundary on the architecture: a configuration outside its range is not a compiler setting, it is a custom design program in <code>AMS-05</code> costing four months.',
  ],
  steps:[
    {n:1, text:'Memory requirement collection from the hierarchy definition', tat:0.5, lane:'main'},
    {n:2, text:'Compiler license and access setup', tat:1, lane:'main'},
    {n:3, text:'Compiler capability screen against the requirement list', tat:1.5, lane:'main'},
    {n:4, text:'Instance generation across the required configurations', tat:2.5, lane:'main'},
    {n:5, text:'Redundancy and repair option evaluation', tat:1.5, lane:'par'},
    {n:6, text:'Compiler view completeness check — .lib, LEF, GDS, CDL, models', tat:1.5, lane:'par'},
    {n:7, text:'Instance library assembly and release', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 3 is the one with a schedule consequence. A capability gap found here opens the <code>PDK-06</code> decision with fifteen weeks of runway; found at instance generation, it opens the same decision with three.',
  consumes:[
    'Memory hierarchy and capacity requirements from ARCH-03',
    'Compiler license terms from TECH-06',
    'PDK version under tracking from PDK-01',
    'BISR and repair architecture intent from DFT-03',
    'Block memory budgets from ARCH-06',
  ],
  produces:[
    'Memory requirement list per block',
    'Compiler license and access setup record',
    'Compiler capability screen and gap list',
    'Generated instances across required configurations',
    'Redundancy and repair option evaluation',
    'Compiler view completeness findings',
    'Instance library with complete views',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'PDK-D2', rel:'produces', text:'<b>Qualified library list.</b> The memory half of the deliverable—instances with every view a downstream tool consumes.'},
    {id:'PDK-D3', rel:'feeds', text:'<b>Memory PPA gap analysis and custom-instance decision record.</b> The capability screen is where the gap first appears; <code>PDK-05</code> quantifies it.'},
    {id:'PDK-D1', rel:'feeds', text:'<b>PDK readiness dashboard.</b> Compiler access and instance availability are tracked readiness items in their own right.'},
  ],
  risks:[
    '<b>Compiler license assumed to be covered by the PDK agreement.</b> Memory compilers are licensed separately, and discovering that here stops the activity for weeks.',
    '<b>Capability screened after generation starts.</b> The gap is the same size either way; what differs is how much runway the custom path has.',
    '<b>Views generated but never checked.</b> A missing or inconsistent view surfaces at <code>PD-02</code> when the macro cannot be placed, and the compiler run has to be repeated.',
    '<b>Redundancy chosen without DFT.</b> Repair schemes have to match the BISR architecture in <code>DFT-03</code>, and a mismatch is found at pattern generation.',
    '<b>Instance count explosion.</b> Generating every configuration a block owner asks for produces a library nobody can characterize or maintain; consolidation is cheaper here than later.',
  ],
  roles:[
    {r:'Memory library engineer', d:'Owns compiler access, generation and the instance library'},
    {r:'Memory architect liaison', d:'Requirement list and configuration consolidation'},
    {r:'DFT liaison', d:'Redundancy and repair option alignment'},
    {r:'CAD methodology engineer', d:'View completeness and tool consumption'},
    {r:'Foundry memory contact', d:'Compiler capability, known issues and updates'},
  ],
  effort:[['Instance generation',3.5], ['Capability screen',2], ['View completeness checks',1.5], ['Redundancy option evaluation',1.5], ['Library assembly and release',1.5]],
  entry:[
    'Memory requirements available from ARCH-03',
    'Compiler license executed under TECH-06',
    'PDK version stable enough to generate against',
  ],
  exit:[
    'Every required configuration either generated or recorded as a gap',
    'All views present and checked, not merely produced',
    'Redundancy scheme aligned with the DFT architecture',
  ],
  dependsOn:['ARCH-03','TECH-06','PDK-01'],
  dependsNote:null,
  feedsInto:['PDK-05','PDK-13','AMS-05','DFT-03','RTL-03','PD-02'],
  measuredBy:[
    'Configurations generated against those requested',
    'Views complete against the tool requirement list',
    'Instance count against what the flow can maintain',
  ],
},

'PDK-05': {
  stage:'pdk', window:[14,20], criticalPath:true,
  purpose:[
    'Measure what the generated instances actually deliver—<b>density, Vmin, access time, leakage</b>—and set it against the budget each block was allocated.',
    'This is the activity that decides whether the custom memory path opens. The compiler produces an instance that meets the specification; the question here is whether it meets the <em>budget</em>, and the answer is frequently no by a margin large enough to matter but small enough to be argued about.',
  ],
  steps:[
    {n:1, text:'Block memory budget extraction from ARCH-06', tat:0.5, lane:'main'},
    {n:2, text:'Density measurement per generated instance', tat:1.5, lane:'main'},
    {n:3, text:'Vmin and access time characterization', tat:1.5, lane:'main'},
    {n:4, text:'Leakage and dynamic power measurement', tat:1, lane:'par'},
    {n:5, text:'Area efficiency against the block budget', tat:1, lane:'par'},
    {n:6, text:'Gap analysis and shortfall quantification', tat:2.5, lane:'main'},
  ],
  flowNote:'The gap analysis is quantified rather than described on purpose. "The compiler misses the budget" starts an argument; "the L2 array misses its density budget by 14%, which is 3.1 mm² of die" starts a decision.',
  consumes:[
    'Generated instances from PDK-04',
    'Block memory budgets from ARCH-06',
    'Vmin and operating voltage requirements from ARCH-05',
    'Access time requirements from the hierarchy specification',
    'DTCO SRAM findings from TECH-03',
  ],
  produces:[
    'Per-block memory budget extract',
    'Density measurement per instance',
    'Vmin and access time characterization results',
    'Leakage and dynamic power measurements',
    'Area efficiency comparison against budget',
    'Quantified gap analysis per block',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PDK-D3', rel:'produces', text:'<b>Memory PPA gap analysis and custom-instance decision record.</b> The gap analysis half—<code>PDK-06</code> adds the decision that follows from it.'},
    {id:'PDK-D2', rel:'feeds', text:'<b>Qualified library list.</b> An instance that fails characterization does not belong on the qualified list, whatever the compiler says.'},
  ],
  risks:[
    '<b>Density measured on the datasheet rather than the instance.</b> Compiler datasheets quote best-case configurations; the instance the design needs is rarely one of them.',
    '<b>Vmin characterized at nominal only.</b> Vmin is a distribution, and the number that matters is at the corner and the sigma the product is sold at.',
    '<b>Gap described rather than quantified.</b> A shortfall without a number in square millimetres cannot be traded against schedule in <code>PDK-06</code>.',
    '<b>Measurement late enough to remove the option.</b> Characterization completing after the AMS window has closed makes the custom path unavailable regardless of the gap.',
    '<b>Access time measured without the wire load.</b> An instance that meets access time standalone and misses it in place has not been characterized usefully.',
  ],
  roles:[
    {r:'Memory characterization engineer', d:'Owns the measurements and the gap analysis'},
    {r:'Memory library engineer', d:'Instance generation and configuration control'},
    {r:'PPA lead', d:'Budget comparison and shortfall quantification'},
    {r:'Circuit design liaison', d:'Vmin interpretation and assist implications'},
    {r:'Block owners', d:'Confirm the budget and accept or contest the gap'},
  ],
  effort:[['Vmin and access time characterization',3], ['Density measurement',1.5], ['Gap analysis',1.5], ['Power measurement',1]],
  entry:[
    'Instances generated and released by PDK-04',
    'Block budgets published by ARCH-06',
    'Characterization environment available',
  ],
  exit:[
    'Every instance measured against its block\'s budget',
    'Gaps quantified in area, power and Vmin, not described',
    'Results delivered with enough runway for PDK-06 to act',
  ],
  dependsOn:['PDK-04','ARCH-06'],
  dependsNote:null,
  feedsInto:['PDK-06','AMS-05','AMS-08','ARCH-06','PD-02'],
  measuredBy:[
    'Instances characterized against those released',
    'Gap quantified in die area',
    'Weeks of runway left for the custom decision',
  ],
},

'PDK-06': {
  stage:'pdk', window:[19,23], criticalPath:true,
  purpose:[
    'Decide what to do about the memory shortfall—<b>push rules, build a custom array, or change the architecture</b>—and hand the chosen scope to AMS with a schedule attached.',
    'This is a gate, not a study. The compiler instance missed the budget; the options each cost something different and one of them has to be taken. Deferring the decision does not preserve the options—the custom array path needs its full window in <code>AMS-05</code> through <code>AMS-10</code>, and every week of deferral removes one from the end.',
  ],
  steps:[
    {n:1, text:'Shortfall review against the block budgets', tat:0.5, lane:'main'},
    {n:2, text:'Option definition — pushed rules, custom array, or architecture change', tat:1, lane:'main'},
    {n:3, text:'Schedule impact assessment against the AMS window', tat:1, lane:'main'},
    {n:4, text:'Foundry appetite for pushed rules and the approval path', tat:0.75, lane:'par'},
    {n:5, text:'Cost and risk comparison of the options', tat:0.75, lane:'par'},
    {n:6, text:'Decision and scope handoff to AMS', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 4 runs in parallel and can veto an option outright. A pushed-rule array the foundry will not approve is not an option, and finding that after the decision is taken costs the whole custom window.',
  consumes:[
    'Quantified gap analysis from PDK-05',
    'AMS capacity and window from the program schedule',
    'Foundry pushed-rule policy and approval process',
    'Architecture flexibility from ARCH-03',
    'Cost impact of the die area at stake from DEF-04',
  ],
  produces:[
    'Shortfall review against the block budgets',
    'Defined options — pushed rules, custom array, architecture change',
    'Schedule impact assessment against the AMS window',
    'Foundry pushed-rule appetite finding',
    'Option definition with cost, schedule and risk per path',
    'Decision record with the alternatives rejected',
    'Scope handoff package to AMS',
  ],
  producedBy:[1,2,3,4,5,6,6],
  rel:[
    {id:'PDK-D3', rel:'produces', text:'<b>Memory PPA gap analysis and custom-instance decision record.</b> The decision half of the deliverable, and the record downstream stages will point at.'},
    {id:'PDK-D1', rel:'gates', text:'<b>PDK readiness dashboard.</b> An undecided memory gap is the most consequential open item the dashboard can carry—it holds both library closure and the AMS plan.'},
  ],
  risks:[
    '<b>Decision deferred to preserve options.</b> Deferral removes the custom option rather than preserving it, because the window is fixed at the far end by physical design.',
    '<b>Pushed rules chosen without foundry commitment.</b> Approval is a process with its own duration, and an unapproved pushed-rule array is a layout nobody can tape out.',
    '<b>Architecture change dismissed too quickly.</b> Reducing the array is sometimes cheaper than building it; the option deserves the same costing as the other two.',
    '<b>Scope handed to AMS without a schedule.</b> A custom instance request with no date is a request that competes with the SerDes for the same engineers and loses.',
    '<b>Decision taken without the block owner.</b> The owner who accepted the budget in <code>ARCH-06</code> is the one who has to accept the concession here.',
  ],
  roles:[
    {r:'PDK owner', d:'Owns the decision and its record'},
    {r:'Memory circuit lead', d:'Custom array scope and feasibility'},
    {r:'Program manager', d:'Schedule impact and AMS capacity'},
    {r:'Foundry technical contact', d:'Pushed-rule appetite and approval path'},
    {r:'Chief architect', d:'Arbitrates when the option is an architecture change'},
  ],
  effort:[['Option definition',1], ['Schedule impact assessment',0.75], ['Foundry approval path',0.5], ['Decision record and handoff',0.75]],
  entry:[
    'Gap quantified by PDK-05',
    'AMS window and capacity known from the program plan',
    'Foundry pushed-rule policy understood',
  ],
  exit:[
    'Decision taken and recorded with the rejected options priced',
    'Foundry approval path confirmed if pushed rules are chosen',
    'Scope handed to AMS with a date, not only a requirement',
  ],
  dependsOn:['PDK-05','ARCH-03','DEF-04'],
  dependsNote:null,
  feedsInto:['AMS-05','AMS-06','AMS-07','ARCH-06','PD-02'],
  measuredBy:[
    'Weeks from gap quantification to decision',
    'Options costed against options considered',
    'AMS window remaining at handoff',
  ],
},

'PDK-07': {
  stage:'pdk', window:[8,14], criticalPath:false,
  purpose:[
    'Qualify the <b>IO, ESD and latch-up</b> collateral—the library that sits at the die edge and decides whether the part survives handling, and whether its interfaces meet their electrical specifications.',
    'IO qualification is unglamorous and it is where parts die. An ESD strategy chosen late constrains the pad ring after the bump map is fixed; a latch-up rule missed produces a part that fails qualification for reasons no functional test would ever find.',
  ],
  steps:[
    {n:1, text:'IO requirement collection from the interface and bump plans', tat:0.5, lane:'main'},
    {n:2, text:'IO library selection against the interface list', tat:1.5, lane:'main'},
    {n:3, text:'ESD strategy and clamp selection', tat:1.5, lane:'main'},
    {n:4, text:'Latch-up rule review and guard ring strategy', tat:1, lane:'par'},
    {n:5, text:'IO timing and signal integrity model quality check', tat:1, lane:'par'},
    {n:6, text:'Qualification record and release', tat:2.5, lane:'main'},
  ],
  flowNote:'The ESD strategy in step 3 has to precede pad ring layout, which in turn precedes the bump map freeze in <code>ARCH-08</code>. Late ESD is a pad ring change, and a pad ring change is a bump map change.',
  consumes:[
    'Interface list from ARCH-04',
    'Bump and pad ring plan from ARCH-08',
    'Foundry IO library and ESD rule set',
    'Latch-up and reliability requirements from the qualification plan',
    'Package and board ESD requirements',
  ],
  produces:[
    'Consolidated IO requirement list',
    'IO library selection per interface',
    'ESD strategy and clamp selection record',
    'Latch-up and guard ring strategy',
    'IO timing and SI model quality report',
    'IO qualification record',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PDK-D2', rel:'produces', text:'<b>Qualified library list.</b> The IO and ESD half of the deliverable—the cells at the die edge, qualified rather than assumed.'},
    {id:'PDK-D6', rel:'feeds', text:'<b>Signoff corner definition.</b> ESD and latch-up verification conditions are part of what signoff has to run, and they are defined here.'},
  ],
  risks:[
    '<b>ESD strategy chosen after the pad ring.</b> Clamp placement and rail topology constrain the ring; retrofitting means redoing the ring and the bump map with it.',
    '<b>IO models unchecked.</b> IO timing models feed both STA and the channel simulation in <code>SIPI-07</code>; an error propagates into two signoffs at once.',
    '<b>Latch-up rules read as a formality.</b> Guard ring strategy affects area at the die edge, and a late change competes with the interfaces for the same space.',
    '<b>Package and board ESD requirements ignored.</b> The part\'s ESD rating is a system property; qualifying only the die produces a rating the system cannot use.',
    '<b>Library selected per interface with no consolidation.</b> Several IO families in one ring multiplies the qualification and the pad ring complexity for little gain.',
  ],
  roles:[
    {r:'IO library engineer', d:'Owns the selection and the qualification record'},
    {r:'ESD engineer', d:'Strategy, clamps and rail topology'},
    {r:'Reliability engineer', d:'Latch-up and guard ring requirements'},
    {r:'Physical design liaison', d:'Pad ring and area implications'},
    {r:'SI liaison', d:'IO model quality for channel and timing use'},
  ],
  effort:[['IO library selection',1.5], ['ESD strategy',1.5], ['Model quality checks',1], ['Qualification record',1]],
  entry:[
    'Interface list available from ARCH-04',
    'Pad ring and bump plan drafted in ARCH-08',
    'Foundry IO library and ESD rules released',
  ],
  exit:[
    'ESD strategy fixed before the pad ring is committed',
    'IO models validated for both timing and channel use',
    'Latch-up strategy reviewed against the qualification plan',
  ],
  dependsOn:['ARCH-04','ARCH-08','PDK-01'],
  dependsNote:null,
  feedsInto:['PDK-11','PD-01','SIPI-06','SIPI-07','SO-07','MP-03'],
  measuredBy:[
    'IO families in the ring against those qualified',
    'Model errors found downstream',
    'ESD rating achieved against the system requirement',
  ],
},

'PDK-08': {
  stage:'pdk', window:[10,20], criticalPath:false,
  purpose:[
    'Decide which tool at which version each flow step runs on, <b>qualify that combination on the node</b>, and freeze it—so that a result from one team means the same thing as a result from another.',
    'Tool versions are a correctness question, not an IT one. A node this advanced needs certified versions for extraction, timing and physical verification, and mixing versions across teams produces disagreements that consume weeks before anyone suspects the tools rather than the design.',
  ],
  steps:[
    {n:1, text:'Tool and version matrix definition per flow step', tat:1, lane:'main'},
    {n:2, text:'Vendor node certification status review', tat:1, lane:'main'},
    {n:3, text:'Synthesis and place-and-route version qualification', tat:2.5, lane:'main'},
    {n:4, text:'STA and signoff tool qualification', tat:2, lane:'par'},
    {n:5, text:'Physical verification and EM/IR tool qualification', tat:2, lane:'par'},
    {n:6, text:'Interoperability and database version check across tools', tat:1.5, lane:'par'},
    {n:7, text:'Version freeze and upgrade exception policy', tat:4, lane:'main'},
    {n:8, text:'Tool matrix publication to every team', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 6 catches what per-tool qualification cannot. Each tool can be certified on the node and still disagree with the next one about a database format or a parasitic convention, and only a cross-tool check finds it.',
  consumes:[
    'Selected node and flavor from TECH',
    'Vendor certification matrices for the node',
    'Foundry reference flow tool requirements',
    'Existing internal tool estate and licences',
    'Flow step definitions from PDK-09',
  ],
  produces:[
    'Tool and version matrix per flow step',
    'Vendor certification status record',
    'Synthesis and place-and-route version qualification results',
    'STA and signoff tool qualification results',
    'Qualification results per tool',
    'Interoperability check findings',
    'Version freeze and upgrade exception policy',
    'Published tool matrix',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'PDK-D4', rel:'produces', text:'<b>EDA tool and version matrix (qualified and frozen).</b> This activity is the deliverable, and the freeze is the part that matters.'},
    {id:'PDK-D5', rel:'feeds', text:'<b>Internal reference flow and methodology guide.</b> The flow is written against specific tool versions; the guide and the matrix are read together.'},
    {id:'PDK-D7', rel:'feeds', text:'<b>Compute and license capacity plan.</b> Which tools and how many concurrent seats is what the license plan is built from.'},
  ],
  risks:[
    '<b>Teams on different versions.</b> Two teams with different STA versions will disagree about timing, and the disagreement is diagnosed as a design problem for weeks first.',
    '<b>Certification status assumed.</b> Vendor node certification lags node release; an uncertified version produces results the foundry will not accept at signoff.',
    '<b>Interoperability never checked.</b> Per-tool qualification passes and the handoff between them fails, usually on parasitic or database conventions.',
    '<b>Freeze with no upgrade path.</b> A critical tool fix will arrive mid-program, and a policy that has no route to accept it will be broken informally.',
    '<b>Matrix published once.</b> A matrix nobody re-reads after month three is a matrix that describes an estate nobody is running.',
  ],
  roles:[
    {r:'CAD tools lead', d:'Owns the matrix, the qualification and the freeze'},
    {r:'Flow engineers', d:'Per-tool qualification on the node'},
    {r:'Signoff methodology engineer', d:'STA and physical verification qualification'},
    {r:'EDA vendor account contacts', d:'Certification status and fixes'},
    {r:'IT infrastructure', d:'Deployment and version enforcement'},
  ],
  effort:[['Synthesis and P&R qualification',3], ['STA and signoff qualification',2.5], ['Physical verification and EM/IR qualification',2.5], ['Interoperability checks',2], ['Matrix and freeze policy',2]],
  entry:[
    'Node and flavor selected',
    'Vendor certification matrices available',
    'Foundry reference flow requirements known',
  ],
  exit:[
    'Every flow step has a qualified, named tool version',
    'Cross-tool interoperability checked, not assumed',
    'Freeze published with an exception route for critical fixes',
  ],
  dependsOn:['TECH-02','PDK-01'],
  dependsNote:null,
  feedsInto:['PDK-09','PDK-12','PDK-13','SYN-01','PD-01','SO-01'],
  measuredBy:[
    'Flow steps with a qualified version against the total',
    'Cross-tool defects found here against those found downstream',
    'Version exceptions granted against the policy',
  ],
},

'PDK-09': {
  stage:'pdk', window:[12,22], criticalPath:true,
  purpose:[
    'Take the foundry\'s reference flow, <b>adapt it into a methodology this design can actually run</b>, and prove it on a representative block before the whole team depends on it.',
    'A reference flow is a starting point written for a generic design. This one has hierarchical partitions, hard macros, multiple power domains and a memory subsystem the reference never contemplated. The pilot in the last step is what turns an adapted flow into a trusted one.',
  ],
  steps:[
    {n:1, text:'Foundry reference flow ingestion', tat:1, lane:'main'},
    {n:2, text:'Gap analysis against internal methodology and design needs', tat:1.5, lane:'main'},
    {n:3, text:'Synthesis and place-and-route flow adaptation', tat:2.5, lane:'main'},
    {n:4, text:'Signoff flow adaptation and deck integration', tat:2, lane:'par'},
    {n:5, text:'Low-power flow integration against the UPF intent', tat:1.5, lane:'par'},
    {n:6, text:'Hierarchical and block-level flow definition', tat:2, lane:'par'},
    {n:7, text:'Methodology deck authoring', tat:2, lane:'main'},
    {n:8, text:'Flow pilot on a representative block', tat:3, lane:'main'},
  ],
  flowNote:'Three of the ten weeks are the pilot, and it is the step under most pressure to be skipped. A flow that has never been run end to end on a real block is a flow whose first user is doing the debugging on the critical path.',
  consumes:[
    'Foundry reference flow and scripts',
    'Tool matrix from PDK-08',
    'Rule and extraction decks from PDK-10',
    'UPF intent from ARCH-05',
    'Hierarchical partitioning from ARCH-02',
  ],
  produces:[
    'Ingested foundry reference flow',
    'Gap analysis against internal methodology',
    'Adapted synthesis and place-and-route flow',
    'Adapted synthesis, P&R and signoff flows',
    'Low-power flow integration',
    'Hierarchical and block-level flow definition',
    'Internal methodology deck',
    'Pilot results on a representative block',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'PDK-D5', rel:'produces', text:'<b>Internal reference flow and methodology guide.</b> This activity is the deliverable, and the pilot is what makes it credible.'},
    {id:'PDK-D8', rel:'feeds', text:'<b>Golden environment release notes.</b> The environment in <code>PDK-13</code> packages this flow; the two are released together.'},
    {id:'PDK-D1', rel:'feeds', text:'<b>PDK readiness dashboard.</b> Flow readiness is tracked alongside library and deck readiness—a design cannot start on any one of them alone.'},
  ],
  risks:[
    '<b>Pilot skipped under schedule pressure.</b> The flow\'s first real user then debugs it while on the critical path, which is the most expensive place to do it.',
    '<b>Reference flow adopted rather than adapted.</b> A generic flow on a hierarchical design with hard macros produces results nobody can close.',
    '<b>Low-power flow bolted on late.</b> UPF handling touches synthesis, placement and verification; adding it after the flow is built means rebuilding it.',
    '<b>Methodology deck written after the flow changes.</b> A guide that lags the scripts teaches the wrong flow to every engineer who joins.',
    '<b>Pilot block unrepresentative.</b> A small clean block pilots nothing; the pilot has to include a macro, a domain crossing and real congestion.',
  ],
  roles:[
    {r:'Methodology lead', d:'Owns the flow, the deck and the pilot'},
    {r:'Flow engineers', d:'Synthesis, P&R and signoff adaptation'},
    {r:'Low-power methodology engineer', d:'UPF flow integration'},
    {r:'Physical design pilot engineer', d:'Runs the pilot on a real block'},
    {r:'Foundry flow contact', d:'Reference flow support and known issues'},
  ],
  effort:[['Flow adaptation',4], ['Pilot on a representative block',3], ['Signoff flow and deck integration',2], ['Methodology deck',1.5], ['Low-power flow integration',1.5]],
  entry:[
    'Tool matrix qualified by PDK-08',
    'Decks under version control from PDK-10',
    'UPF intent available from ARCH-05',
  ],
  exit:[
    'Flow run end to end on a representative block, not a toy one',
    'Methodology deck matches the scripts as released',
    'Hierarchical and block flows both defined, not only the top',
  ],
  dependsOn:['PDK-02','PDK-08','PDK-10','ARCH-05'],
  dependsNote:null,
  feedsInto:['PDK-13','SYN-01','PD-01','SO-01','DFT-06'],
  measuredBy:[
    'Pilot blocks run end to end',
    'Flow defects found in the pilot against those found in production use',
    'Deck and script version agreement',
  ],
},

'PDK-10': {
  stage:'pdk', window:[6,12], criticalPath:false,
  purpose:[
    'Put every rule deck, extraction file and verification runset <b>under version control</b>, validate them on known-good structures, and make deck changes a notified event rather than a surprise.',
    'Decks are the quiet dependency. A DRC runset revision that arrives without notice changes what passes verification, and if two teams are running different revisions the disagreement looks like a layout problem. Version control here is what makes a signoff result reproducible six months later.',
  ],
  steps:[
    {n:1, text:'Deck inventory and version baseline', tat:1, lane:'main'},
    {n:2, text:'Version control and release process definition', tat:1, lane:'main'},
    {n:3, text:'QRC tech file and extraction deck validation', tat:1.5, lane:'par'},
    {n:4, text:'DRC and LVS deck validation on known-good structures', tat:1.5, lane:'main'},
    {n:5, text:'Deck change notification and impact process', tat:1, lane:'par'},
    {n:6, text:'Continuous deck version tracking across the stage', tat:2.5, lane:'main'},
  ],
  flowNote:'Validation on known-good structures in step 4 is what makes a deck trustworthy. A runset that has never been tested against a layout with a known answer will report both false positives and, far worse, false negatives.',
  consumes:[
    'Foundry rule decks, runsets and tech files',
    'PDK version tracking from PDK-01',
    'Tool matrix from PDK-08',
    'Known-good test structures from previous programs',
    'Rule dispositions from PDK-02',
  ],
  produces:[
    'Deck inventory with version baseline',
    'Version control and release process',
    'Extraction deck validation results',
    'DRC and LVS validation results',
    'Change notification process and log',
    'Deck version tracking log',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PDK-D5', rel:'feeds', text:'<b>Internal reference flow and methodology guide.</b> A flow is only reproducible if the decks it calls are versioned; the guide names the versions.'},
    {id:'PDK-D8', rel:'feeds', text:'<b>Golden environment release notes.</b> The environment pins deck versions, and this activity is what makes pinning possible.'},
    {id:'PDK-D1', rel:'feeds', text:'<b>PDK readiness dashboard.</b> Deck currency and validation status are readiness items on the dashboard.'},
  ],
  risks:[
    '<b>Decks used from a shared directory.</b> An unversioned deck makes every result unreproducible, and the problem is invisible until two results disagree.',
    '<b>Extraction deck unvalidated.</b> Parasitic extraction errors move timing by amounts that look like design problems, and they are found after weeks of closure work.',
    '<b>Deck updates applied silently.</b> A runset revision mid-closure changes what passes, and nobody can explain why yesterday\'s clean run is dirty today.',
    '<b>No known-good structures.</b> Without a layout whose answer is known, deck validation is an assertion.',
    '<b>Tracking stops when the stage ends.</b> Decks keep moving through signoff; a process that stops at PDK 1.0 leaves the most critical period unmanaged.',
  ],
  roles:[
    {r:'CAD methodology engineer', d:'Owns deck version control and the release process'},
    {r:'Physical verification engineer', d:'DRC and LVS deck validation'},
    {r:'Extraction engineer', d:'QRC tech file and parasitic deck validation'},
    {r:'PDK owner', d:'Change notification against the version tracking'},
    {r:'Foundry deck contact', d:'Deck releases, fixes and known issues'},
  ],
  effort:[['Deck validation',1.5], ['Version control process',1], ['Continuous tracking',1], ['Change notification process',0.5]],
  entry:[
    'Foundry decks released under the design agreement',
    'PDK version tracking established by PDK-01',
    'Known-good test structures available',
  ],
  exit:[
    'Every deck versioned and pinned, none used from a shared path',
    'Extraction and verification decks validated against known answers',
    'Change notification process running, with a log',
  ],
  dependsOn:['PDK-01','PDK-02'],
  dependsNote:null,
  feedsInto:['PDK-09','PDK-13','SO-02','SO-10','PD-06'],
  measuredBy:[
    'Decks under version control against the inventory',
    'Deck-induced result changes explained on the first day',
    'Reproducibility of a signoff run six months later',
  ],
},

'PDK-11': {
  stage:'pdk', window:[20,26], criticalPath:false,
  purpose:[
    'Agree with the foundry <b>exactly which corners and derates signoff will be run at</b>—PVT combinations, modes, and the OCV, AOCV or POCV methodology—and write it down before anyone closes timing against it.',
    'A corner set is a contract. Sign off at corners the foundry does not recognize and the foundry will not accept the result; sign off at more corners than necessary and every closure iteration costs runtime and license capacity the program has not budgeted for.',
  ],
  steps:[
    {n:1, text:'Corner and mode enumeration from the operating conditions', tat:1, lane:'main'},
    {n:2, text:'PVT corner set proposal', tat:1.5, lane:'main'},
    {n:3, text:'OCV, AOCV or POCV derate methodology selection', tat:1.5, lane:'par'},
    {n:4, text:'Foundry alignment on the corner set and derates', tat:2, lane:'main'},
    {n:5, text:'Signoff condition documentation', tat:1.5, lane:'main'},
    {n:6, text:'Corner count against runtime and license cost', tat:1, lane:'par'},
  ],
  flowNote:'Step 6 exists because corner count multiplies. Nine corners across three modes is twenty-seven signoff runs per iteration, and the compute plan in <code>PDK-12</code> is sized against whatever number this activity settles on.',
  consumes:[
    'Operating conditions and DVFS points from ARCH-05',
    'Library characterization corners from PDK-03',
    'IO and ESD conditions from PDK-07',
    'Foundry signoff requirements and recommended derates',
    'Runtime and license capacity constraints',
  ],
  produces:[
    'Corner and mode enumeration',
    'Proposed PVT corner set',
    'Derate methodology selection and rationale',
    'PVT corner set, agreed with the foundry',
    'Signoff condition document',
    'Corner count impact on runtime and licences',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PDK-D6', rel:'produces', text:'<b>Signoff corner definition agreed with foundry.</b> This activity is the deliverable, and "agreed" is the operative word—an internal corner set has no standing.'},
    {id:'PDK-D7', rel:'feeds', text:'<b>Compute and license capacity plan.</b> Corner count multiplied by modes is the single largest driver of signoff compute demand.'},
  ],
  risks:[
    '<b>Corner set agreed after closure starts.</b> Adding a corner mid-closure invalidates the work done, and the addition usually comes from the foundry.',
    '<b>Derate methodology chosen for margin.</b> OCV is conservative and expensive in area and power; POCV is tighter and demands better data. Choosing without the data is choosing margin blindly.',
    '<b>Corner count unbounded.</b> Every corner is a full signoff run per iteration; a set nobody trimmed becomes a schedule problem at <code>SO-02</code>.',
    '<b>Modes forgotten.</b> Corners multiply by modes, and a mode discovered late—a test mode, a low-power mode—multiplies the whole set.',
    '<b>Library corners narrower than the signoff set.</b> Signing off at a corner the library was never characterized at is signing off against extrapolation.',
  ],
  roles:[
    {r:'Signoff methodology lead', d:'Owns the corner set and the derate methodology'},
    {r:'STA lead', d:'Corner and mode enumeration, runtime implications'},
    {r:'Library engineer', d:'Confirms characterization covers the proposed corners'},
    {r:'Foundry technical contact', d:'Agreement on corners and recommended derates'},
    {r:'CAD infrastructure', d:'Runtime and license capacity impact'},
  ],
  effort:[['Corner and mode definition',1.5], ['Foundry alignment',1.5], ['Derate methodology',1], ['Documentation',1]],
  entry:[
    'Operating conditions and DVFS points defined by ARCH-05',
    'Library characterization corners known from PDK-03',
    'Foundry signoff requirements available',
  ],
  exit:[
    'Corner set agreed with the foundry in writing',
    'Every signoff corner covered by library characterization',
    'Runtime and license impact quantified and accepted',
  ],
  dependsOn:['ARCH-05','PDK-03','PDK-07'],
  dependsNote:null,
  feedsInto:['PDK-12','SYN-01','PD-09','SO-02','SO-12'],
  measuredBy:[
    'Corners agreed against corners later added',
    'Signoff runs per closure iteration',
    'Corners covered by library characterization',
  ],
},

'PDK-12': {
  stage:'pdk', window:[16,22], criticalPath:false,
  purpose:[
    'Model what the program will actually need in <b>compute, EDA licences and storage</b> across its peak, and procure it against a lead time rather than discovering it during timing closure.',
    'Compute is a schedule input disguised as an IT line item. Timing closure at <code>PD-09</code> runs multi-corner across a 600 mm² die; if the farm or the license pool caps concurrency, every iteration takes longer and the closure burn-down flattens for reasons nobody attributes to infrastructure.',
  ],
  steps:[
    {n:1, text:'Compute demand model per stage and per flow step', tat:1.5, lane:'main'},
    {n:2, text:'EDA license demand model against peak concurrency', tat:1.5, lane:'main'},
    {n:3, text:'Storage and data retention requirement', tat:0.75, lane:'par'},
    {n:4, text:'Farm capacity plan against procurement lead time', tat:1.5, lane:'main'},
    {n:5, text:'Licence negotiation support and pooling strategy', tat:1, lane:'par'},
    {n:6, text:'Capacity plan publication and review', tat:1.5, lane:'main'},
  ],
  flowNote:'The demand model is built per flow step rather than per team because that is how contention actually happens: three teams running the same tool at the same point in the schedule contend for one license pool, whatever the org chart says.',
  consumes:[
    'Flow step definitions and runtimes from PDK-09',
    'Corner and mode count from PDK-11',
    'Tool matrix from PDK-08',
    'Program schedule and stage overlap from DEF-08',
    'Existing farm and license estate',
  ],
  produces:[
    'Compute demand model per stage and flow step',
    'EDA license demand model at peak concurrency',
    'Storage and retention requirement',
    'Farm capacity plan with procurement dates',
    'Licence pooling strategy',
    'Published capacity plan and review record',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PDK-D7', rel:'produces', text:'<b>Compute and license capacity plan.</b> This activity is the deliverable, and its value is that it is dated against lead times.'},
    {id:'PDK-D4', rel:'feeds', text:'<b>EDA tool and version matrix.</b> Which tools are pooled and at what seat count is decided against the matrix.'},
  ],
  risks:[
    '<b>Demand modelled per team rather than per flow step.</b> Contention happens when several teams hit the same tool at the same time, which an org-chart model cannot see.',
    '<b>Peak sized to the average.</b> Signoff and closure peaks are several times the steady state, and a farm sized to the average flattens the burn-down exactly when it matters.',
    '<b>Licences procured without lead time.</b> Additional seats are a commercial negotiation with a duration; needing them next week is needing them next quarter.',
    '<b>Storage forgotten.</b> Multi-corner signoff databases are large, and a farm that runs out of storage stops as hard as one that runs out of cores.',
    '<b>Plan never reviewed against actual usage.</b> A capacity plan is a forecast; without a comparison to actuals nobody learns that it was wrong until closure.',
  ],
  roles:[
    {r:'CAD infrastructure lead', d:'Owns the demand model and the capacity plan'},
    {r:'Flow engineers', d:'Runtime and concurrency data per flow step'},
    {r:'Procurement lead', d:'Licence negotiation and lead times'},
    {r:'Program manager', d:'Stage overlap and peak timing'},
    {r:'IT operations', d:'Farm, storage and deployment'},
  ],
  effort:[['Demand modeling',1.5], ['Capacity plan',0.75], ['Licence strategy',0.5], ['Publication and review',0.25]],
  entry:[
    'Flow steps and runtimes known from PDK-09',
    'Corner and mode count settled by PDK-11',
    'Program schedule available from DEF-08',
  ],
  exit:[
    'Peak demand modelled per flow step, not per team',
    'Procurement dated against lead time, not against need date',
    'Plan published with a review cadence against actual usage',
  ],
  dependsOn:['PDK-08','PDK-09','PDK-11','DEF-08'],
  dependsNote:null,
  feedsInto:['SYN-11','PD-09','SO-01','DV-10'],
  measuredBy:[
    'Peak concurrency modelled against peak observed',
    'Licence denials during closure',
    'Procurement lead time against the need date',
  ],
},

'PDK-13': {
  stage:'pdk', window:[24,32], criticalPath:true,
  purpose:[
    'Package everything this stage produced into <b>one environment every team runs from</b>—tools, decks, libraries, scripts—prove it with a regression, and release it with known issues stated.',
    'Enablement only becomes real when it is a single thing an engineer can load. Until then the program has a qualified library here, a validated deck there and a flow in someone\'s home directory, and every new engineer assembles a slightly different version of the design environment.',
  ],
  steps:[
    {n:1, text:'Environment scope definition — tools, decks, libraries, scripts', tat:1, lane:'main'},
    {n:2, text:'Golden environment assembly', tat:2, lane:'main'},
    {n:3, text:'Flow regression suite definition', tat:1.5, lane:'par'},
    {n:4, text:'Regression run on the reference block', tat:2, lane:'main'},
    {n:5, text:'Result comparison against the pilot baseline', tat:1.5, lane:'par'},
    {n:6, text:'Release notes and known-issue list', tat:1.5, lane:'par'},
    {n:7, text:'Environment release and team onboarding', tat:3, lane:'main'},
  ],
  flowNote:'Step 5 is what makes the release trustworthy. If the golden environment produces different results from the <code>PDK-09</code> pilot on the same block, something in the packaging changed the answer, and finding that after release means everyone\'s results are suspect.',
  consumes:[
    'Qualified libraries from PDK-03, PDK-04 and PDK-07',
    'Validated decks from PDK-10',
    'Tool matrix from PDK-08',
    'Adapted flow and methodology deck from PDK-09',
    'Frozen PDK version from PDK-01',
  ],
  produces:[
    'Environment scope definition',
    'Golden design environment, versioned',
    'Flow regression suite',
    'Reference block regression results',
    'Regression results against the pilot baseline',
    'Release notes and known-issue list',
    'Onboarding material and team access',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'PDK-D8', rel:'produces', text:'<b>Golden environment release notes.</b> This activity is the deliverable—the environment itself, with what is in it and what is known to be wrong with it.'},
    {id:'PDK-D1', rel:'gates', text:'<b>PDK readiness dashboard.</b> The dashboard closes when the environment releases; until then every readiness item is still individually tracked.'},
    {id:'PDK-D5', rel:'feeds', text:'<b>Internal reference flow and methodology guide.</b> The guide describes the flow; this environment is the flow, packaged and versioned.'},
  ],
  risks:[
    '<b>Environment released without a regression.</b> An untested package is a package whose first regression is run by whoever is closest to a deadline.',
    '<b>Results differ from the pilot and the difference is not chased.</b> A packaging change that moves results silently invalidates the pilot\'s credibility and everything built on it.',
    '<b>Known issues omitted.</b> An environment released as clean produces bug reports for problems the team already knew about, and the reports go to the wrong place.',
    '<b>No onboarding.</b> A golden environment nobody was shown how to use is a directory people copy from and modify, which is where divergence starts.',
    '<b>Released and then not maintained.</b> Decks and PDK versions keep moving; an environment frozen at release drifts away from what signoff will require.',
  ],
  roles:[
    {r:'Methodology lead', d:'Owns the environment, its release and its maintenance'},
    {r:'CAD engineers', d:'Assembly, versioning and deployment'},
    {r:'Regression owner', d:'Suite definition and baseline comparison'},
    {r:'Physical design representative', d:'Confirms the environment is usable for real work'},
    {r:'IT operations', d:'Deployment and access'},
  ],
  effort:[['Environment assembly',2.5], ['Regression suite and runs',2.5], ['Onboarding',1.5], ['Release notes',1], ['Baseline comparison',0.5]],
  entry:[
    'Libraries qualified and frozen',
    'Decks validated and under version control',
    'Flow piloted successfully by PDK-09',
  ],
  exit:[
    'Regression reproduces the pilot baseline, or the difference is explained',
    'Known issues published with the release, not after it',
    'Teams onboarded onto the environment rather than copying it',
  ],
  dependsOn:['PDK-01','PDK-03','PDK-04','PDK-07','PDK-08','PDK-09','PDK-10'],
  dependsNote:null,
  feedsInto:['SYN-01','PD-01','SO-01','DFT-06','AMS-12'],
  measuredBy:[
    'Regression deviation from the pilot baseline',
    'Teams on the golden environment against those running private copies',
    'Known issues published against those later reported as new',
  ],
},

};
