/* PKGD — Package & Substrate Design. Eleven activities. Stage w24–76 (52w), 110 M/M. */
module.exports = {

'PKGD-01': {
  stage:'packageDesign', window:[0,8], criticalPath:true,
  purpose:[
    'Choose the <b>package architecture</b>—interposer type, substrate construction, layer count, body size—and commit to it, because everything from bump pitch to assembly capacity follows.',
    'This decision has the same character as the monolithic-versus-chiplet call in <code>ARCH-02</code>: it looks like an engineering choice and it is a supply chain commitment. A 2.5D silicon interposer is a different supplier, a different capacity queue and a different cost structure from an organic bridge, and switching later is not practical.',
  ],
  steps:[
    {n:1, text:'Package requirement consolidation — die size, power, interfaces, thermal', tat:1.5, lane:'main'},
    {n:2, text:'Architecture option definition — interposer, bridge, organic', tat:2, lane:'main'},
    {n:3, text:'Capability and capacity screen per option', tat:1.5, lane:'par'},
    {n:4, text:'Substrate construction and layer count study', tat:2, lane:'main'},
    {n:5, text:'Cost comparison per option with the DEF-04 model', tat:1.5, lane:'par'},
    {n:6, text:'Architecture selection and specification', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 3 can eliminate an option outright. Advanced interposer capacity is allocated quarters ahead to a small number of customers, and an architecture the program cannot get capacity for is not an option however good it looks technically.',
  consumes:[
    'Package architecture assumption from DEF-01',
    'Partitioning and die count from ARCH-02',
    'Backend supply chain findings from TECH-09',
    'Bandwidth and HBM requirements from DEF-05',
    'Cost model from DEF-04',
  ],
  produces:[
    'Package requirement consolidation',
    'Defined package architecture options',
    'Architecture options with capability assessment',
    'Capacity screen per option',
    'Substrate construction study',
    'Cost comparison',
    'Package architecture specification',
  ],
  producedBy:[1,2,3,3,4,5,6],
  rel:[
    {id:'PKGD-D1', rel:'produces', text:'<b>Package architecture specification.</b> This activity is the deliverable, and it is a supply chain commitment as much as a technical one.'},
    {id:'PKGD-D7', rel:'feeds', text:'<b>Substrate and interposer PO with committed lead time.</b> The architecture decides which supplier queue the program is standing in.'},
  ],
  risks:[
    '<b>Architecture chosen without capacity.</b> Advanced packaging capacity is scarce and allocated far ahead; a technically ideal option with no allocation is not an option.',
    '<b>Decision taken after the bump map.</b> Package architecture constrains bump pitch and field, and deciding afterwards means renegotiating the die.',
    '<b>Cost compared on the package alone.</b> Interposer, substrate, assembly yield and test all differ per architecture, and comparing one line misleads.',
    '<b>Thermal requirement not in the selection.</b> Package thermal resistance is architecture-dependent and sets the achievable power envelope.',
    '<b>Single option evaluated.</b> Without an alternative the program has no negotiating position and no fallback if capacity is refused.',
  ],
  roles:[
    {r:'Package architect', d:'Owns the architecture selection and specification'},
    {r:'Backend supply chain lead', d:'Capability and capacity screening'},
    {r:'Thermal engineer', d:'Thermal resistance per option'},
    {r:'Product cost analyst', d:'Cost comparison across options'},
    {r:'Chief architect', d:'Die-side implications of the choice'},
  ],
  effort:[['Architecture option definition',2.5], ['Substrate construction study',2], ['Selection and specification',2], ['Capacity screen',1.5], ['Cost comparison',1], ['Requirement consolidation',1]],
  entry:[
    'Partitioning and die count known from ARCH-02',
    'Backend supply chain findings available from TECH-09',
    'Bandwidth and HBM requirements from DEF-05',
  ],
  exit:[
    'Architecture selected with capacity indicated, not assumed',
    'At least two options evaluated and costed end to end',
    'Specification issued before bump planning starts',
  ],
  dependsOn:['DEF-01','DEF-05','ARCH-02','TECH-09','DEF-04'],
  dependsNote:null,
  feedsInto:['PKGD-02','PKGD-04','PKGD-07','PKGD-09','PD-04','PTV-01'],
  measuredBy:[
    'Options evaluated against the one chosen',
    'Capacity indicated for the selected architecture',
    'Architecture changes after selection',
  ],
},

'PKGD-02': {
  stage:'packageDesign', window:[8,18], criticalPath:true,
  purpose:[
    'Negotiate the <b>bump map with physical design</b>—pitch, count, power-to-signal ratio, position—until both the die and the package can build what the other needs.',
    'The bump field is where two design teams share one constraint. The die wants bumps where its logic is; the package wants them where its escape routing can reach; and the power delivery requirement takes most of the field regardless. Convergence takes iteration, and the iteration has to finish before <code>PD-04</code> freezes.',
  ],
  steps:[
    {n:1, text:'Bump pitch and field definition against the architecture', tat:2, lane:'main'},
    {n:2, text:'Power-to-signal ratio derivation from the power envelope', tat:1.5, lane:'main'},
    {n:3, text:'Signal bump assignment per interface', tat:2, lane:'par'},
    {n:4, text:'Escape feasibility check against the substrate', tat:2, lane:'main'},
    {n:5, text:'Die-side placement iteration with physical design', tat:2, lane:'par'},
    {n:6, text:'Bump map convergence and handoff', tat:4.5, lane:'main'},
  ],
  flowNote:'Step 4 is the check that usually forces the iteration. A bump assignment that works on the die can require escape routing the substrate cannot provide at its layer count, and finding that early is what keeps the map from being redone after freeze.',
  consumes:[
    'Package architecture from PKGD-01',
    'Bump budget and intent from ARCH-08',
    'Power envelope and delivery requirement from PD-03',
    'Interface lane counts from ARCH-04',
    'Substrate layer count from PKGD-04',
  ],
  produces:[
    'Bump pitch and field definition',
    'Power-to-signal ratio',
    'Signal bump assignment per interface',
    'Escape feasibility findings',
    'Die-side placement iteration record',
    'Converged bump map',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PKGD-D2', rel:'produces', text:'<b>Bump map and interposer / RDL database.</b> The bump map half of the deliverable; <code>PKGD-03</code> supplies the interposer routing.'},
    {id:'PKGD-D4', rel:'feeds', text:'<b>Package electrical design intent.</b> Bump assignment determines channel quality before any routing is drawn.'},
  ],
  risks:[
    '<b>Bump map converged on the die side only.</b> A map that cannot escape on the substrate has to be redone, and by then the die may be placed around it.',
    '<b>Power bumps reduced to fit signals.</b> The interfaces then work and the die cannot be fed, which <code>SIPI-04</code> finds much later.',
    '<b>Pitch chosen from the previous program.</b> Pitch depends on the interposer technology and the assembly process, both of which may have changed.',
    '<b>Signal assignment ignoring channel quality.</b> Which bump a high-speed signal uses affects its escape path and its crosstalk exposure.',
    '<b>Iteration continuing past the freeze date.</b> <code>PD-04</code> and the substrate order both depend on this closing on time.',
  ],
  roles:[
    {r:'Package designer', d:'Owns the package-side bump map'},
    {r:'Physical design liaison', d:'Die-side placement and constraints'},
    {r:'Power delivery engineer', d:'Power bump count and distribution'},
    {r:'SI engineer', d:'Signal assignment for channel quality'},
    {r:'Package architect', d:'Arbitrates when the two sides cannot converge'},
  ],
  effort:[['Bump pitch and field definition',3], ['Signal assignment',2.5], ['Escape feasibility',2.5], ['Convergence and handoff',2], ['Power ratio derivation',1], ['Die-side iteration',1]],
  entry:[
    'Package architecture selected in PKGD-01',
    'Bump budget available from ARCH-08',
    'Power delivery requirement known from PD-03',
  ],
  exit:[
    'Escape feasibility confirmed on the substrate, not only on the die',
    'Power-to-signal ratio meets the delivery requirement',
    'Map converged before the PD-04 freeze date',
  ],
  dependsOn:['PKGD-01','ARCH-04','ARCH-08','PD-03'],
  dependsNote:null,
  feedsInto:['PKGD-03','PKGD-05','PD-04','SIPI-02'],
  measuredBy:[
    'Iterations to convergence',
    'Escape feasibility at first check',
    'Power bumps against the delivery requirement',
  ],
},

'PKGD-03': {
  stage:'packageDesign', window:[16,30], criticalPath:true,
  purpose:[
    'Route the <b>interposer and its redistribution layers</b>—the silicon layer that carries the die-to-HBM channels and everything else the substrate cannot.',
    'On a 2.5D part the interposer carries the highest-density and highest-performance connections in the package. HBM channels alone run to thousands of nets at fine pitch, and their routing quality decides whether the memory interface trains at speed.',
  ],
  steps:[
    {n:1, text:'Interposer layer stack and routing resource plan', tat:2, lane:'main'},
    {n:2, text:'HBM channel routing and length management', tat:4, lane:'main'},
    {n:3, text:'Die-to-die and remaining signal routing', tat:3, lane:'par'},
    {n:4, text:'Power and ground distribution on the interposer', tat:3, lane:'main'},
    {n:5, text:'RDL routing and via planning', tat:2.5, lane:'par'},
    {n:6, text:'Interposer DRC and manufacturability', tat:2.5, lane:'par'},
    {n:7, text:'Interposer database release', tat:5, lane:'main'},
  ],
  flowNote:'Step 2 dominates because HBM channels are numerous, fine-pitch and length-sensitive at once. Getting them routed with matched lengths and clean references is most of the interposer\'s difficulty and most of its schedule.',
  consumes:[
    'Bump map from PKGD-02',
    'HBM channel requirements from ARCH-03 and ARCH-04',
    'Interposer technology rules from the supplier',
    'Power delivery requirement from PD-03',
    'SI requirements from SIPI-07',
  ],
  produces:[
    'Interposer layer stack and routing plan',
    'Routed HBM channels with length management',
    'Die-to-die and signal routing',
    'Interposer power distribution',
    'RDL routing and via plan',
    'Interposer DRC and manufacturability results',
    'Released interposer database',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'PKGD-D2', rel:'produces', text:'<b>Bump map and interposer / RDL database.</b> The interposer half of the deliverable—the routed silicon layer itself.'},
    {id:'PKGD-D4', rel:'feeds', text:'<b>Package electrical design intent.</b> Interposer routing is the highest-performance part of the package\'s electrical behavior.'},
  ],
  risks:[
    '<b>HBM channel lengths unmatched.</b> Skew across a wide parallel interface eats the training margin, and the failure appears at bring-up as a memory that will not train at speed.',
    '<b>Reference plane discontinuities.</b> A channel crossing a plane split has an impedance discontinuity, and on HBM there are thousands of channels to get right.',
    '<b>Interposer power distribution underprovisioned.</b> Current for two HBM stacks and the die passes through the interposer, and its resistance is part of the IR budget.',
    '<b>Manufacturability checked late.</b> Interposer rules differ from die rules, and a design that violates them is a supplier rejection rather than a warning.',
    '<b>Routing started before the bump map converges.</b> Every bump change is an interposer rework, and the rework is expensive at this density.',
  ],
  roles:[
    {r:'Interposer designer', d:'Owns interposer routing and its release'},
    {r:'SI engineer', d:'Channel length, reference and impedance requirements'},
    {r:'Power delivery engineer', d:'Interposer power distribution'},
    {r:'Supplier liaison', d:'Interposer technology rules and manufacturability'},
    {r:'Package architect', d:'Layer stack and resource allocation'},
  ],
  effort:[['HBM channel routing',5], ['Power distribution',3.5], ['Signal and die-to-die routing',3], ['RDL and via planning',2.5], ['Database release',2], ['DRC and manufacturability',2]],
  entry:[
    'Bump map converged in PKGD-02',
    'Interposer technology rules available from the supplier',
    'Channel requirements known from SIPI-07',
  ],
  exit:[
    'HBM channel lengths matched within the training budget',
    'Reference planes continuous under high-speed channels',
    'Interposer DRC clean against supplier rules',
  ],
  dependsOn:['PKGD-02','ARCH-03','ARCH-04','PD-03'],
  dependsNote:null,
  feedsInto:['PKGD-05','PKGD-11','SIPI-02','SIPI-07','PTV-05'],
  measuredBy:[
    'Channel length skew against the training budget',
    'Reference plane violations',
    'Interposer DRC violations at supplier review',
  ],
},

'PKGD-04': {
  stage:'packageDesign', window:[18,32], criticalPath:true,
  purpose:[
    'Design the <b>substrate</b>—stack-up, escape routing, power planes, package DRC—the organic carrier that connects the interposer to the board.',
    'The substrate is the part with the longest lead time and the least flexibility once ordered. Its layer count is fixed by escape routing needs and its cost scales with it, so the design converges on the smallest stack-up that can carry the escape—a trade made once and lived with.',
  ],
  steps:[
    {n:1, text:'Stack-up definition and layer count decision', tat:2, lane:'main'},
    {n:2, text:'Escape routing from the interposer footprint', tat:4, lane:'main'},
    {n:3, text:'Power and ground plane design', tat:3, lane:'par'},
    {n:4, text:'Board-side ball assignment and breakout', tat:3, lane:'main'},
    {n:5, text:'Via structure and drill planning', tat:2.5, lane:'par'},
    {n:6, text:'Package DRC against supplier rules', tat:2.5, lane:'par'},
    {n:7, text:'Substrate database release', tat:5, lane:'main'},
  ],
  flowNote:'Step 1 is the cost decision. Every substrate layer adds cost across the product\'s lifetime, and the layer count is set by whether the escape routing fits—which is not known until step 2 is attempted. The two steps iterate.',
  consumes:[
    'Package architecture from PKGD-01',
    'Interposer footprint from PKGD-03',
    'Board requirements and ball map from EVB-02',
    'Supplier design rules from PKGD-09',
    'Power delivery requirement from SIPI-05',
  ],
  produces:[
    'Substrate stack-up and layer count',
    'Escape routing from the interposer',
    'Power and ground plane design',
    'Board-side ball assignment',
    'Via and drill plan',
    'Package DRC results against supplier rules',
    'Released substrate database',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'PKGD-D3', rel:'produces', text:'<b>Substrate design files (Gerber / ODB++) and stack-up.</b> This activity is the deliverable, and it is what the supplier manufactures from.'},
    {id:'PKGD-D7', rel:'feeds', text:'<b>Substrate and interposer PO with committed lead time.</b> The order cannot be placed against a design that is not finished.'},
  ],
  risks:[
    '<b>Layer count set before escape is attempted.</b> A stack-up chosen for cost that cannot carry the escape has to be increased, and the cost model was built on the smaller number.',
    '<b>Supplier rules obtained late.</b> Substrate rules vary by supplier and technology, and designing to generic rules produces a design one supplier can build.',
    '<b>Power planes fragmented by escape routing.</b> Escape vias perforate the planes, and the resulting current path is what <code>SIPI-03</code> will analyze.',
    '<b>Ball map not agreed with the board.</b> The substrate\'s board-side interface is the board\'s problem too, and changing it late affects both.',
    '<b>Design released before DRC closes.</b> A supplier rejection costs weeks against a twenty-week lead time.',
  ],
  roles:[
    {r:'Substrate designer', d:'Owns stack-up, routing and release'},
    {r:'Package architect', d:'Layer count and cost trade'},
    {r:'Supplier liaison', d:'Design rules and manufacturability'},
    {r:'Board designer', d:'Ball map and board-side interface'},
    {r:'Power integrity engineer', d:'Plane design and current paths'},
  ],
  effort:[['Escape routing',5], ['Ball assignment and breakout',3.5], ['Power and ground planes',3], ['Stack-up definition',2.5], ['Via and drill planning',2], ['DRC and release',2]],
  entry:[
    'Package architecture selected in PKGD-01',
    'Interposer footprint available from PKGD-03',
    'Supplier design rules obtained via PKGD-09',
  ],
  exit:[
    'Layer count justified by an attempted escape, not assumed',
    'Package DRC clean against the actual supplier\'s rules',
    'Ball map agreed with the board design',
  ],
  dependsOn:['PKGD-01','PKGD-03','PKGD-09'],
  dependsNote:null,
  feedsInto:['PKGD-05','PKGD-06','PKGD-11','SIPI-02','PTV-05'],
  measuredBy:[
    'Layer count against the cost model assumption',
    'DRC violations at supplier review',
    'Escape routing completed at the chosen layer count',
  ],
},

'PKGD-05': {
  stage:'packageDesign', window:[26,36], criticalPath:false,
  purpose:[
    'Route the package for <b>signal integrity</b>—length matching, reference continuity, via design, crosstalk separation—so the channels can carry what the interfaces need.',
    'Package routing is where high-speed channels are made or ruined. A via with a long stub, a trace crossing a plane split, or a differential pair routed without its partner all cost margin that the PHY then has to make up. <code>SIPI-07</code> will measure the result; this activity is what determines it.',
  ],
  steps:[
    {n:1, text:'Channel budget allocation to the package', tat:1.5, lane:'main'},
    {n:2, text:'Length matching and skew control per interface', tat:2.5, lane:'main'},
    {n:3, text:'Reference plane continuity and return path design', tat:2, lane:'par'},
    {n:4, text:'Via structure design and stub management', tat:2, lane:'main'},
    {n:5, text:'Crosstalk separation and shielding', tat:2, lane:'par'},
    {n:6, text:'Routing review against the SI requirements', tat:4, lane:'main'},
  ],
  flowNote:'Step 4 is the one most often underestimated. Via stubs resonate at frequencies that matter for the fastest interfaces, and back-drilling or blind via structures are decisions with cost implications that belong to the substrate design rather than to routing.',
  consumes:[
    'Interposer and substrate routing from PKGD-03 and PKGD-04',
    'Channel budgets from AMS-03 and ARCH-04',
    'SI requirements and targets from SIPI-07',
    'Interface compliance requirements',
    'Supplier via and drill capability',
  ],
  produces:[
    'Channel budget allocation to the package',
    'Length-matched routing per interface',
    'Reference plane continuity design',
    'Via structures with managed stubs',
    'Crosstalk separation plan',
    'SI routing review record',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PKGD-D4', rel:'produces', text:'<b>Package electrical design intent and model handoff to co-verification.</b> The signal half of the deliverable—the design intent <code>SIPI</code> then verifies.'},
    {id:'PKGD-D3', rel:'feeds', text:'<b>Substrate design files and stack-up.</b> SI-driven routing is part of what the substrate files contain.'},
  ],
  risks:[
    '<b>Via stubs unmanaged.</b> They resonate in band for the fastest interfaces, and the remedy—back-drilling or blind vias—is a substrate cost decision made too late.',
    '<b>Length matching without reference continuity.</b> Matched traces over a split plane have matched delay and mismatched impedance.',
    '<b>Channel budget not allocated.</b> Die, package and board each consume part of the loss budget, and without allocation each assumes the others left room.',
    '<b>Crosstalk managed by spacing alone.</b> On a dense substrate there is no spare space, and the answer is usually reference and via design instead.',
    '<b>Review after the substrate is released.</b> SI findings then have nowhere to go except into the PHY\'s margin.',
  ],
  roles:[
    {r:'SI engineer', d:'Owns channel budgets and routing requirements'},
    {r:'Package designer', d:'Implements length, reference and via design'},
    {r:'Interposer designer', d:'Interposer-side channel routing'},
    {r:'PHY liaison', d:'Channel budget from the die side'},
    {r:'Supplier liaison', d:'Via and drill capability'},
  ],
  effort:[['Length matching and skew',3], ['Via structure design',2.5], ['Reference and return path',2], ['Crosstalk separation',2], ['Budget allocation',1.5], ['Review',1]],
  entry:[
    'Interposer and substrate routing progressing',
    'Channel budgets available from AMS-03',
    'SI targets defined by SIPI-07',
  ],
  exit:[
    'Channel budget explicitly allocated between die, package and board',
    'Via stubs managed rather than accepted',
    'Routing reviewed against SI requirements before substrate release',
  ],
  dependsOn:['PKGD-03','PKGD-04','ARCH-04','AMS-03'],
  dependsNote:null,
  feedsInto:['PKGD-11','SIPI-07','SIPI-08','SO-06'],
  measuredBy:[
    'Channel loss against the package\'s allocated budget',
    'Via stub length on critical interfaces',
    'Length skew per interface',
  ],
},

'PKGD-06': {
  stage:'packageDesign', window:[28,37], criticalPath:false,
  purpose:[
    'Design the <b>package power delivery</b>—plane structure, via arrays, decoupling footprints—knowing that its electrical closure belongs to <code>SIPI</code> rather than to this activity.',
    'The package sits between the die\'s instantaneous current demand and the board\'s slower supply. Its planes, vias and decoupling determine the impedance in the mid-frequency band where neither the die\'s on-chip decap nor the board\'s bulk capacitors help. Designing it is here; proving it works is co-verification.',
  ],
  steps:[
    {n:1, text:'Package PDN topology and plane allocation', tat:2, lane:'main'},
    {n:2, text:'Power via array design and current capability', tat:2, lane:'main'},
    {n:3, text:'Decoupling capacitor footprint placement', tat:1.5, lane:'par'},
    {n:4, text:'Plane perforation and current path management', tat:2, lane:'main'},
    {n:5, text:'Interposer to substrate power transition', tat:1.5, lane:'par'},
    {n:6, text:'PDN design intent handoff to co-verification', tat:3, lane:'main'},
  ],
  flowNote:'Step 3 places footprints rather than choosing values. Which capacitors go where is decided by <code>SIPI-05</code> against the impedance target; the package\'s job is to provide mounting positions close enough to the current draw for those choices to be available.',
  consumes:[
    'Substrate stack-up from PKGD-04',
    'Power delivery requirement from PD-03',
    'Bump and ball power assignment from PKGD-02',
    'Impedance targets from SIPI-03',
    'Supplier capability for via arrays and mounting',
  ],
  produces:[
    'Package PDN topology and plane allocation',
    'Power via array design',
    'Decoupling footprint placement',
    'Plane perforation and current path analysis',
    'Interposer to substrate power transition design',
    'PDN design intent handoff',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PKGD-D4', rel:'produces', text:'<b>Package electrical design intent and model handoff to co-verification.</b> The power half of the deliverable, handed to <code>SIPI</code> for closure.'},
    {id:'PKGD-D3', rel:'feeds', text:'<b>Substrate design files and stack-up.</b> Plane allocation and via arrays are substrate content.'},
  ],
  risks:[
    '<b>Decoupling footprints too far from the current draw.</b> Mounting position determines the loop inductance, and a capacitor mounted far away is a capacitor that does not help.',
    '<b>Plane perforation ignored.</b> Escape vias perforate power planes, and the remaining current path can be far worse than the plane suggests.',
    '<b>Via array sized for DC only.</b> Transient current is what the package has to supply, and DC sizing understates the requirement.',
    '<b>Closure assumed to be someone else\'s problem.</b> If the design intent is not analysable, <code>SIPI</code> cannot close it and the iteration comes back here.',
    '<b>Interposer to substrate transition overlooked.</b> The power path crosses two interfaces, and the transition is where its resistance concentrates.',
  ],
  roles:[
    {r:'Package power integrity engineer', d:'Owns package PDN design'},
    {r:'Substrate designer', d:'Plane and via implementation'},
    {r:'SIPI liaison', d:'Impedance targets and closure feedback'},
    {r:'Die power delivery engineer', d:'Die-side current profile'},
    {r:'Supplier liaison', d:'Via array and mounting capability'},
  ],
  effort:[['PDN topology and planes',2.5], ['Power via arrays',2], ['Plane perforation management',2], ['Decoupling footprints',1.5], ['Power transition design',1], ['Handoff',1]],
  entry:[
    'Substrate stack-up defined in PKGD-04',
    'Power delivery requirement known from PD-03',
    'Impedance targets available from SIPI-03',
  ],
  exit:[
    'Decoupling footprints placed for loop inductance, not convenience',
    'Plane perforation analyzed rather than assumed away',
    'Design intent handed over in a form SIPI can analyze',
  ],
  dependsOn:['PKGD-02','PKGD-04','PD-03','SIPI-03'],
  dependsNote:null,
  feedsInto:['PKGD-11','SIPI-03','SIPI-05','SO-06'],
  measuredBy:[
    'Package PDN impedance against target',
    'Decoupling loop inductance',
    'Current path resistance through perforated planes',
  ],
},

'PKGD-07': {
  stage:'packageDesign', window:[20,32], criticalPath:false,
  purpose:[
    'Simulate the <b>thermal and mechanical behavior</b> of the package—heat path, warpage, co-planarity, TIM and lid—before any of it is built.',
    'A package at this power dissipates hundreds of watts through a stack of materials with different expansion coefficients. The thermal path decides the achievable power envelope; the mechanical behavior decides whether the assembly survives reflow. Both are simulated here and measured on real vehicles in <code>PTV</code>.',
  ],
  steps:[
    {n:1, text:'Thermal model construction — die, interposer, substrate, lid', tat:2, lane:'main'},
    {n:2, text:'Steady-state thermal simulation and Rjc estimation', tat:2.5, lane:'main'},
    {n:3, text:'Hotspot and transient thermal analysis', tat:2, lane:'par'},
    {n:4, text:'TIM selection and interface resistance study', tat:2, lane:'par'},
    {n:5, text:'Warpage simulation across the reflow profile', tat:3, lane:'main'},
    {n:6, text:'Mechanical stress and co-planarity analysis', tat:2, lane:'par'},
    {n:7, text:'Thermal and mechanical design recommendations', tat:4.5, lane:'main'},
  ],
  flowNote:'Step 5 predicts what <code>PTV-07</code> will measure. Warpage across the reflow profile is the mechanism behind most 2.5D assembly failures, and simulating it before the vehicles are built is what makes the vehicle results interpretable rather than merely surprising.',
  consumes:[
    'Package architecture from PKGD-01',
    'Power map and hotspot data from PD-03 and SYN-06',
    'Material properties from the supplier',
    'Assembly reflow profile from PKGD-10',
    'Thermal requirements from DEF-03',
  ],
  produces:[
    'Thermal model of the package stack',
    'Steady-state thermal results and Rjc estimate',
    'Hotspot and transient analysis',
    'TIM selection and interface study',
    'Warpage simulation across reflow',
    'Mechanical stress and co-planarity results',
    'Thermal and mechanical design recommendations',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'PKGD-D5', rel:'produces', text:'<b>Thermal and mechanical (warpage) simulation reports.</b> This activity is the deliverable, and <code>PTV</code> is what validates it.'},
    {id:'PKGD-D6', rel:'feeds', text:'<b>Test vehicle requirement specification for PTV.</b> The simulations decide which mechanical and thermal risks the vehicles must measure.'},
  ],
  risks:[
    '<b>Thermal simulated at uniform power.</b> An accelerator\'s power is concentrated in the compute clusters, and uniform assumptions understate the hotspot badly.',
    '<b>Warpage simulated at room temperature only.</b> The failure happens at reflow peak, and the room-temperature number says nothing about it.',
    '<b>TIM performance taken from the datasheet.</b> Interface resistance depends on bond line thickness and pressure, both of which are assembly properties.',
    '<b>Material properties assumed.</b> Substrate and underfill properties vary by supplier and lot, and simulation is only as good as the inputs.',
    '<b>Results not fed into the vehicle plan.</b> Simulation identifies which risks to measure, and a vehicle plan built independently measures the wrong things.',
  ],
  roles:[
    {r:'Thermal engineer', d:'Owns thermal modeling and TIM selection'},
    {r:'Mechanical engineer', d:'Warpage, stress and co-planarity'},
    {r:'Package architect', d:'Design recommendations from the findings'},
    {r:'Supplier liaison', d:'Material properties and reflow profile'},
    {r:'Die power liaison', d:'Power map and hotspot distribution'},
  ],
  effort:[['Warpage simulation',3], ['Steady-state thermal',2.5], ['TIM and interface study',2], ['Hotspot and transient analysis',1.5], ['Mechanical stress analysis',1.5], ['Recommendations',1.5]],
  entry:[
    'Package architecture selected in PKGD-01',
    'Power map available from PD-03',
    'Material properties obtained from suppliers',
  ],
  exit:[
    'Thermal simulated against the real power map, not uniform power',
    'Warpage simulated across the full reflow profile',
    'Findings handed to PTV as vehicle requirements',
  ],
  dependsOn:['PKGD-01','PD-03','DEF-03'],
  dependsNote:null,
  feedsInto:['PKGD-08','PKGD-10','PTV-03','PTV-07','SIPI-10'],
  measuredBy:[
    'Predicted Rjc against the PTV measurement',
    'Predicted warpage against measured',
    'Hotspot temperature against the thermal requirement',
  ],
},

'PKGD-08': {
  stage:'packageDesign', window:[10,14], criticalPath:false,
  purpose:[
    'Tell <b>PTV what the vehicles have to measure</b>—which risks, which structures, which conditions—early enough that the vehicles can be designed, built and stressed before wafer-out.',
    'The test vehicle program has a fifty-two week window and a hard gate at product wafer-out. Its requirements have to arrive while there is time to act on them, which is why this activity sits at week ten of a fifty-two week stage rather than after the package design is finished.',
  ],
  steps:[
    {n:1, text:'Package risk identification for vehicle coverage', tat:1, lane:'main'},
    {n:2, text:'Vehicle type requirements — mechanical, thermal, electrical', tat:1.5, lane:'par'},
    {n:3, text:'Measurement condition and structure specification', tat:1.5, lane:'main'},
    {n:4, text:'Requirement handoff and PTV plan review', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 1 has to be done on an incomplete package design, which is uncomfortable and necessary. The architecture is known, the materials are known and the assembly process is broadly known—enough to say what will be risky, which is all the vehicle plan needs.',
  consumes:[
    'Package architecture from PKGD-01',
    'Thermal and warpage predictions from PKGD-07',
    'Assembly process direction from PKGD-10',
    'CPI and ULK risk from TECH-03',
    'Previous-program package failures',
  ],
  produces:[
    'Package risk list for vehicle coverage',
    'Vehicle type requirements',
    'Measurement conditions and structure specification',
    'Requirement handoff to PTV',
  ],
  producedBy:[1,2,3,4],
  rel:[
    {id:'PKGD-D6', rel:'produces', text:'<b>Test vehicle requirement specification for PTV.</b> This activity is the deliverable, and its timing matters as much as its content.'},
    {id:'PKGD-D5', rel:'feeds', text:'<b>Thermal and mechanical simulation reports.</b> The vehicles measure what the simulations predicted, so the two are specified together.'},
  ],
  risks:[
    '<b>Requirements issued after the package design completes.</b> The vehicle program then cannot finish before wafer-out, and the gate is missed.',
    '<b>Risks identified from the design rather than from experience.</b> The failures that matter are the ones previous programs hit, and they are rarely visible in a design review.',
    '<b>Electrical vehicle omitted.</b> Daisy-chain continuity and assembly yield are as important as thermal and mechanical, and they need their own vehicle.',
    '<b>Conditions unspecified.</b> A vehicle measured at the wrong temperature or reflow profile answers a question nobody asked.',
    '<b>No feedback loop defined.</b> The vehicle results have to change something, and the mechanism for that has to be agreed up front.',
  ],
  roles:[
    {r:'Package architect', d:'Owns the risk list and the requirements'},
    {r:'Thermal and mechanical engineers', d:'Vehicle requirements from the simulations'},
    {r:'Reliability engineer', d:'Failure modes worth measuring'},
    {r:'PTV lead', d:'Receives the requirements and confirms feasibility'},
    {r:'OSAT liaison', d:'Assembly process realism in the vehicle plan'},
  ],
  effort:[['Risk identification',1], ['Measurement specification',0.75], ['Vehicle type requirements',0.75], ['Handoff and review',0.5]],
  entry:[
    'Package architecture selected in PKGD-01',
    'First thermal and warpage predictions available',
    'Assembly process direction known from PKGD-10',
  ],
  exit:[
    'Requirements issued with time for the vehicle program to finish before wafer-out',
    'Risks drawn from experience as well as from the design',
    'Feedback mechanism into package design agreed',
  ],
  dependsOn:['PKGD-01','PKGD-07','TECH-03'],
  dependsNote:null,
  feedsInto:['PTV-01','PTV-02','PTV-03','PTV-04'],
  measuredBy:[
    'Weeks between requirement issue and the wafer-out gate',
    'Risks covered by vehicles against risks identified',
    'Vehicle findings that changed the package design',
  ],
},

'PKGD-09': {
  stage:'packageDesign', window:[22,32], criticalPath:true,
  purpose:[
    'Select the <b>substrate and interposer suppliers and book their lead time</b>—a twenty-week commitment that sets the date the package can be built.',
    'Substrate lead time is the longest single external dependency in the back half of the program, and it is ordered against a design that is not finished. Selecting the supplier early, understanding their rules and booking capacity is what makes the order placeable the moment the design freezes.',
  ],
  steps:[
    {n:1, text:'Supplier long-list and capability screen', tat:1.5, lane:'main'},
    {n:2, text:'Design rule and technology fit assessment', tat:2, lane:'main'},
    {n:3, text:'Capacity and lead time confirmation', tat:2, lane:'par'},
    {n:4, text:'Commercial negotiation and pricing', tat:2, lane:'par'},
    {n:5, text:'Supplier selection and qualification plan', tat:2.5, lane:'main'},
    {n:6, text:'Purchase order and lead time booking', tat:4, lane:'main'},
  ],
  flowNote:'Step 6 takes four weeks because the order cannot be placed until the design is frozen, and the freeze is in <code>PKGD-11</code>. Everything before it exists so that the order can be placed the same week the design is released rather than a month later.',
  consumes:[
    'Package architecture from PKGD-01',
    'Substrate design requirements from PKGD-04',
    'Backend supply chain landscape from TECH-09',
    'Volume forecast and ramp from DEF-08',
    'Cost targets from DEF-04',
  ],
  produces:[
    'Supplier capability screen',
    'Design rule and technology fit assessment',
    'Capacity and lead time confirmation',
    'Commercial terms',
    'Supplier selection and qualification plan',
    'Purchase order with committed lead time',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PKGD-D7', rel:'produces', text:'<b>Substrate and interposer PO with committed lead time.</b> This activity is the deliverable, and the committed date is what wafer-out has to be planned against.'},
    {id:'PKGD-D3', rel:'feeds', text:'<b>Substrate design files and stack-up.</b> Supplier rules determine what the substrate design can contain.'},
  ],
  risks:[
    '<b>Order placed after wafer-out is committed.</b> A twenty-week substrate against a fixed wafer-out date means wafers waiting for a package.',
    '<b>Supplier rules obtained after design starts.</b> A substrate designed to generic rules may be unbuildable by the chosen supplier.',
    '<b>Capacity assumed.</b> Advanced substrate capacity is constrained, and a supplier who can build it may not be able to build it when needed.',
    '<b>Single supplier with no alternative.</b> A supply disruption then has no mitigation, and substrates are not quickly re-sourced.',
    '<b>Lead time quoted without a commitment.</b> An indicative lead time is not a date, and the difference appears when the schedule depends on it.',
  ],
  roles:[
    {r:'Backend supply chain lead', d:'Owns supplier selection and the order'},
    {r:'Substrate designer', d:'Technology fit and rule assessment'},
    {r:'Procurement', d:'Commercial terms and purchase order'},
    {r:'Quality liaison', d:'Supplier qualification plan'},
    {r:'Program manager', d:'Lead time against the wafer-out date'},
  ],
  effort:[['Supplier selection and qualification',1], ['Design rule assessment',0.75], ['Capacity and lead time',0.75], ['Purchase order',0.75], ['Commercial negotiation',0.5], ['Capability screen',0.25]],
  entry:[
    'Package architecture selected in PKGD-01',
    'Substrate requirements known from PKGD-04',
    'Volume and ramp forecast available',
  ],
  exit:[
    'Lead time committed in writing, not indicative',
    'Supplier rules available before substrate design completes',
    'Order placeable the week the design freezes',
  ],
  dependsOn:['PKGD-01','TECH-09','DEF-08'],
  dependsNote:null,
  feedsInto:['PKGD-04','PKGD-11','PTV-05','ASSY-04'],
  measuredBy:[
    'Committed lead time against the wafer-out date',
    'Weeks between design freeze and order placement',
    'Suppliers qualified against those screened',
  ],
},

'PKGD-10': {
  stage:'packageDesign', window:[24,33], criticalPath:false,
  purpose:[
    'Select the <b>OSAT and define the assembly process</b>—bonding, underfill, molding, lid attach—because the process determines what the package design has to accommodate.',
    'Assembly is not a service the package is handed to; it is a set of constraints the package is designed within. Bond force, reflow profile, underfill flow and lid attach all impose requirements, and choosing the OSAT late means designing a package that has to be adapted to whoever ends up building it.',
  ],
  steps:[
    {n:1, text:'OSAT capability screen for the package architecture', tat:1.5, lane:'main'},
    {n:2, text:'Assembly process flow definition', tat:2, lane:'main'},
    {n:3, text:'Bonding, underfill and molding process parameters', tat:2, lane:'par'},
    {n:4, text:'Known-good-die handoff and responsibility model', tat:1.5, lane:'par'},
    {n:5, text:'OSAT selection and capacity commitment', tat:2, lane:'main'},
    {n:6, text:'Assembly agreement and process freeze plan', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 4 settles a question that becomes expensive later. When an assembled unit fails, whether the die or the assembly is responsible determines who bears the cost, and agreeing it while nobody has lost money is far easier than afterwards.',
  consumes:[
    'Package architecture from PKGD-01',
    'Backend supply chain findings from TECH-09',
    'Thermal and mechanical requirements from PKGD-07',
    'Volume and ramp forecast from DEF-08',
    'Known-good-die strategy from TEST-01',
  ],
  produces:[
    'OSAT capability screen',
    'Assembly process flow definition',
    'Process parameter specification',
    'Known-good-die responsibility model',
    'OSAT selection and capacity commitment',
    'Assembly agreement',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PKGD-D8', rel:'produces', text:'<b>OSAT assembly process flow and agreement.</b> This activity is the deliverable, and the agreement includes the responsibility model.'},
    {id:'PKGD-D5', rel:'feeds', text:'<b>Thermal and mechanical simulation reports.</b> The reflow profile the simulations use comes from the assembly process defined here.'},
  ],
  risks:[
    '<b>OSAT selected after the package is designed.</b> The design then has to be adapted to the assembler\'s process rather than developed with it.',
    '<b>Advanced packaging capacity not committed.</b> The same constraint as the interposer, and it applies to assembly capacity independently.',
    '<b>Known-good-die responsibility undefined.</b> The first failed lot is the wrong moment to discover nobody agreed who owns the die.',
    '<b>Process parameters left to the OSAT.</b> Bond force and reflow profile affect warpage and CPI, and the package design has to know them.',
    '<b>Process frozen without vehicle data.</b> <code>PTV-12</code> freezes the process window on evidence; freezing earlier means freezing on assumption.',
  ],
  roles:[
    {r:'Backend supply chain lead', d:'Owns OSAT selection and the agreement'},
    {r:'Package architect', d:'Process requirements from the design'},
    {r:'Quality liaison', d:'Known-good-die responsibility and failure ownership'},
    {r:'Procurement', d:'Capacity commitment and commercial terms'},
    {r:'PTV lead', d:'Process window validation plan'},
  ],
  effort:[['Assembly process definition',1.5], ['OSAT selection',1], ['Process parameters',1], ['Agreement and freeze plan',0.75], ['Known-good-die model',0.75]],
  entry:[
    'Package architecture selected in PKGD-01',
    'Backend landscape known from TECH-09',
    'Volume and ramp forecast available',
  ],
  exit:[
    'OSAT selected with committed capacity',
    'Process parameters known to the package design, not assumed',
    'Known-good-die responsibility agreed in writing',
  ],
  dependsOn:['PKGD-01','PKGD-07','TECH-09'],
  dependsNote:null,
  feedsInto:['PKGD-07','PKGD-11','PTV-06','ASSY-01','ASSY-03'],
  measuredBy:[
    'Assembly capacity committed against the ramp requirement',
    'Process parameters specified against those assumed',
    'Responsibility model agreed before first build',
  ],
},

'PKGD-11': {
  stage:'packageDesign', window:[46,52], criticalPath:true,
  purpose:[
    'Freeze the <b>package design</b>, close its DRC, release the tooling—and start the twenty-week substrate lead time that everything downstream waits on.',
    'The freeze is a schedule event more than a design one. The substrate order cannot be placed against a moving design, and the lead time that follows is what sets when packages can be built. Every week of delay here is a week at the far end, after wafer-out, where it is most visible and least recoverable.',
  ],
  steps:[
    {n:1, text:'Design completeness review across interposer and substrate', tat:1, lane:'main'},
    {n:2, text:'Final package DRC and supplier rule compliance', tat:1.5, lane:'main'},
    {n:3, text:'Electrical intent confirmation against SIPI findings', tat:1, lane:'par'},
    {n:4, text:'Tooling and manufacturing data release', tat:1.5, lane:'main'},
    {n:5, text:'Supplier design review and acceptance', tat:1.5, lane:'par'},
    {n:6, text:'Design freeze declaration and order release', tat:2, lane:'main'},
  ],
  flowNote:'Step 5 runs in parallel and can send the design back. Suppliers review for manufacturability against their own process, and their acceptance is what makes the order placeable—a design frozen internally and rejected by the supplier has not frozen anything.',
  consumes:[
    'Interposer database from PKGD-03',
    'Substrate database from PKGD-04',
    'SI and PDN design from PKGD-05 and PKGD-06',
    'Co-verification findings from SIPI-11',
    'Supplier PO framework from PKGD-09',
  ],
  produces:[
    'Design completeness review record',
    'Final package DRC results',
    'Electrical intent confirmation',
    'Released tooling and manufacturing data',
    'Supplier acceptance record',
    'Package Design Freeze declaration',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PKGD-D9', rel:'produces', text:'<b>Package Design Freeze package.</b> This activity is the deliverable, and it carries the stage\'s milestone.'},
    {id:'PKGD-D7', rel:'gates', text:'<b>Substrate and interposer PO with committed lead time.</b> The order is released on this freeze; nothing before it starts the lead time.'},
  ],
  risks:[
    '<b>Freeze slipping.</b> Twenty weeks of substrate lead time follow it, and the delay lands after wafer-out where nothing can absorb it.',
    '<b>Frozen before co-verification completes.</b> A <code>SIPI</code> finding after freeze is a package change against an order already placed.',
    '<b>Supplier acceptance assumed.</b> A design frozen internally and rejected on manufacturability has not frozen anything except the schedule.',
    '<b>Tooling data incomplete.</b> Manufacturing data is more than the design files, and a missing item stalls the order after it is placed.',
    '<b>Late bump map change from the die side.</b> <code>PD-04</code> has to be frozen first, and a die-side change after this point is extremely expensive.',
  ],
  roles:[
    {r:'Package architect', d:'Owns the freeze and the release'},
    {r:'Package and substrate designers', d:'Completeness and DRC closure'},
    {r:'SIPI liaison', d:'Electrical intent confirmation'},
    {r:'Supplier liaison', d:'Design review and acceptance'},
    {r:'Procurement', d:'Order release on freeze'},
  ],
  effort:[['Tooling and data release',1.5], ['Final DRC',1.5], ['Freeze and order release',1], ['Completeness review',1], ['Supplier review',0.5], ['Electrical confirmation',0.5]],
  entry:[
    'Interposer and substrate designs complete',
    'Co-verification signed off in SIPI-11',
    'Bump map frozen in PD-04',
  ],
  exit:[
    'Supplier has accepted the design, not only received it',
    'Order released the same week as the freeze',
    'Co-verification findings incorporated before freeze, not after',
  ],
  dependsOn:['PKGD-03','PKGD-04','PKGD-05','PKGD-06','PKGD-09','PKGD-10','PD-04','SIPI-11'],
  dependsNote:null,
  feedsInto:['ASSY-04','PTV-12','MP-10'],
  measuredBy:[
    'Freeze date against the substrate lead time requirement',
    'Supplier acceptance at first review',
    'Package changes requested after freeze',
  ],
},

};
