/* PTV — Package Test Vehicle (CPI / TTV). Twelve activities. Stage w36–88 (52w), 96 M/M.
   Must close before product wafer-out at w98. */
module.exports = {

'PTV-01': {
  stage:'packageTestVehicle', window:[0,6], criticalPath:true,
  purpose:[
    'Decide <b>which package risks the vehicles will actually retire</b>—chip-package interaction, warpage, thermal, assembly yield—and what evidence would count as retiring them.',
    'The vehicle program has one shot and a hard gate at product wafer-out. Its value depends entirely on measuring the risks that would otherwise be discovered on real dies, and a vehicle plan built from what is easy to measure rather than from what is risky produces reassurance instead of information.',
  ],
  steps:[
    {n:1, text:'Risk intake from package design and previous programs', tat:1, lane:'main'},
    {n:2, text:'Risk prioritization against product impact', tat:1.5, lane:'main'},
    {n:3, text:'Evidence definition — what would retire each risk', tat:1.5, lane:'par'},
    {n:4, text:'Vehicle type allocation per risk', tat:1.5, lane:'main'},
    {n:5, text:'Schedule feasibility against the wafer-out gate', tat:1, lane:'par'},
    {n:6, text:'Vehicle plan and risk coverage matrix', tat:2, lane:'main'},
  ],
  flowNote:'Step 5 checks the whole program against one date. Fifty-two weeks of vehicle work has to finish before product wafers come out at week 98, and if the arithmetic does not close then the plan has to shrink rather than the gate move.',
  consumes:[
    'Vehicle requirements from PKGD-08',
    'Thermal and warpage predictions from PKGD-07',
    'CPI and ULK risk from TECH-03',
    'Assembly process direction from PKGD-10',
    'Wafer-out forecast from FAB-09',
  ],
  produces:[
    'Risk intake from package design and previous programs',
    'Package risk list with product impact',
    'Evidence definition per risk',
    'Vehicle type allocation',
    'Schedule feasibility finding',
    'Test vehicle plan and risk coverage matrix',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D1', rel:'produces', text:'<b>Test vehicle plan and risk coverage matrix.</b> This activity is the deliverable, and the matrix is what every later result is reported against.'},
    {id:'PTV-D9', rel:'feeds', text:'<b>Package validation complete record.</b> Validation is complete when the matrix\'s risks are retired, which is why the matrix has to be right.'},
  ],
  risks:[
    '<b>Plan built from what is measurable.</b> Easy measurements produce data; the risk list produces information, and the two are not the same set.',
    '<b>Schedule not checked against the gate.</b> A fifty-two week program that finishes after wafer-out has validated nothing in time to matter.',
    '<b>Evidence undefined.</b> Without agreeing in advance what would retire a risk, the results become an argument rather than a conclusion.',
    '<b>Previous-program failures not consulted.</b> The package failure modes that recur are known, and they are the ones worth measuring.',
    '<b>Vehicle count driven by budget rather than by risk.</b> Fewer vehicles means fewer risks retired, and the trade should be explicit.',
  ],
  roles:[
    {r:'PTV lead', d:'Owns the plan and the coverage matrix'},
    {r:'Package architect', d:'Risk intake from the design'},
    {r:'Reliability engineer', d:'Failure modes worth measuring'},
    {r:'Program manager', d:'Schedule feasibility against the gate'},
    {r:'OSAT liaison', d:'Vehicle build feasibility'},
  ],
  effort:[['Risk prioritization',1.5], ['Vehicle allocation',1], ['Plan and coverage matrix',1], ['Evidence definition',0.75], ['Risk intake',0.75]],
  entry:[
    'Vehicle requirements received from PKGD-08',
    'Thermal and warpage predictions available',
    'Wafer-out forecast available from FAB-09',
  ],
  exit:[
    'Every carried risk has defined retiring evidence',
    'Programme schedule closes before the wafer-out gate',
    'Plan reflects prioritized risk rather than measurement convenience',
  ],
  dependsOn:['PKGD-07','PKGD-08','TECH-03'],
  dependsNote:null,
  feedsInto:['PTV-02','PTV-03','PTV-04','PTV-12'],
  measuredBy:[
    'Risks with defined retiring evidence',
    'Schedule margin against the wafer-out gate',
    'Vehicle types allocated against risks identified',
  ],
},

'PTV-02': {
  stage:'packageTestVehicle', window:[5,14], criticalPath:false,
  purpose:[
    'Design the <b>mechanical test vehicle</b>—dummy die stack, representative bump array, substrate coupon—that carries the package\'s mechanical behavior without any of its electronics.',
    'The MTV exists to be stressed. Its die are blank, its interposer is representative and its purpose is to reproduce the mechanical stack faithfully enough that warpage, co-planarity and CPI measured on it predict what the product will do.',
  ],
  steps:[
    {n:1, text:'Mechanical representativeness requirements', tat:1.5, lane:'main'},
    {n:2, text:'Dummy die and die stack design', tat:2, lane:'main'},
    {n:3, text:'Bump array design representative of the product', tat:2, lane:'par'},
    {n:4, text:'Interposer and substrate coupon design', tat:2.5, lane:'main'},
    {n:5, text:'Measurement feature integration — strain, reference marks', tat:1.5, lane:'par'},
    {n:6, text:'MTV design release', tat:3, lane:'main'},
  ],
  flowNote:'Step 1 defines what "representative" means for mechanics, which is narrower than it sounds. Die thickness, bump metallurgy, underfill and substrate construction matter; the circuitry does not. Getting that distinction right is what makes the MTV cheap.',
  consumes:[
    'Vehicle plan from PTV-01',
    'Package architecture from PKGD-01',
    'Mechanical predictions from PKGD-07',
    'Die thickness and bump specification from PD-04',
    'Material specifications from suppliers',
  ],
  produces:[
    'Mechanical representativeness requirements',
    'Dummy die and stack design',
    'Representative bump array',
    'Interposer and substrate coupon design',
    'Measurement feature integration',
    'Released MTV design',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D2', rel:'produces', text:'<b>MTV, TTV and daisy-chain vehicle designs.</b> The mechanical vehicle of the three.'},
    {id:'PTV-D4', rel:'feeds', text:'<b>Warpage and co-planarity data across the reflow profile.</b> What the MTV measures is bounded by how it was designed.'},
  ],
  risks:[
    '<b>Vehicle not mechanically representative.</b> Different die thickness or underfill produces warpage that does not predict the product\'s.',
    '<b>Measurement features omitted.</b> A vehicle with no reference marks or strain features can be measured externally and not internally.',
    '<b>Bump array simplified.</b> Bump density and distribution drive local stress, and a uniform array does not reproduce the product\'s concentrations.',
    '<b>Design released before the product\'s stack is settled.</b> A vehicle built on an assumption that changes measures the wrong package.',
    '<b>Coupon size unrepresentative.</b> Warpage scales with body size, and a smaller coupon understates it.',
  ],
  roles:[
    {r:'Mechanical engineer', d:'Owns representativeness and the MTV design'},
    {r:'Package designer', d:'Coupon and substrate design'},
    {r:'Materials engineer', d:'Die, underfill and substrate material match'},
    {r:'Metrology engineer', d:'Measurement feature requirements'},
    {r:'OSAT liaison', d:'Build feasibility'},
  ],
  effort:[['Coupon and substrate design',2], ['Dummy die and stack',1.75], ['Bump array design',1.5], ['Design release',1.5], ['Measurement features',1.25]],
  entry:[
    'Vehicle plan available from PTV-01',
    'Package architecture and materials known',
    'Die thickness and bump specification available from PD-04',
  ],
  exit:[
    'Mechanically representative in the dimensions that drive warpage',
    'Measurement features integrated, not added externally',
    'Released against a settled product stack',
  ],
  dependsOn:['PTV-01','PKGD-01','PKGD-07'],
  dependsNote:null,
  feedsInto:['PTV-05','PTV-07','PTV-08'],
  measuredBy:[
    'Representativeness against the product stack',
    'Measurement features integrated against those required',
    'Design changes after release',
  ],
},

'PTV-03': {
  stage:'packageTestVehicle', window:[5,14], criticalPath:false,
  purpose:[
    'Design the <b>thermal test vehicle</b>—embedded heaters and temperature sensors laid out to match the product\'s power map—so the package\'s thermal path can be measured rather than simulated.',
    'A TTV is a die that only makes heat, in the pattern the real die will make it. Uniform heaters measure an average the product will never experience; heaters matched to the compute cluster distribution measure the hotspot that decides the achievable power envelope.',
  ],
  steps:[
    {n:1, text:'Power map translation into heater zones', tat:1.5, lane:'main'},
    {n:2, text:'Heater array design and drive requirements', tat:2, lane:'main'},
    {n:3, text:'RTD and temperature sensor placement', tat:2, lane:'par'},
    {n:4, text:'TTV die and interposer integration', tat:2.5, lane:'main'},
    {n:5, text:'Calibration approach for the sensors', tat:1.5, lane:'par'},
    {n:6, text:'TTV design release', tat:3, lane:'main'},
  ],
  flowNote:'Step 3 decides what the vehicle can see. Sensors placed only at the die center measure a number the datasheet can quote; sensors distributed across the zones measure the gradient that determines whether the hotspot is survivable.',
  consumes:[
    'Vehicle plan from PTV-01',
    'Power map and hotspot distribution from PD-03 and SYN-06',
    'Thermal predictions from PKGD-07',
    'Package architecture from PKGD-01',
    'Sensor and heater process capability',
  ],
  produces:[
    'Heater zone map from the power distribution',
    'Heater array design and drive requirements',
    'Sensor placement plan',
    'TTV die and interposer integration',
    'Sensor calibration approach',
    'Released TTV design',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D2', rel:'produces', text:'<b>MTV, TTV and daisy-chain vehicle designs.</b> The thermal vehicle of the three.'},
    {id:'PTV-D6', rel:'feeds', text:'<b>Thermal characterization report with model correlation.</b> What the TTV can measure bounds what the correlation can claim.'},
  ],
  risks:[
    '<b>Uniform heaters.</b> They measure an average power distribution the product will never have, and the hotspot goes unmeasured.',
    '<b>Sensors too few or badly placed.</b> Thermal gradients are what matter, and a single center sensor cannot see one.',
    '<b>Sensor calibration not planned.</b> An uncalibrated RTD gives a relative number, and thermal resistance needs an absolute one.',
    '<b>Heater drive capability underspecified.</b> Reproducing hundreds of watts through a test vehicle needs real power delivery, and the setup has to supply it.',
    '<b>Power map taken from an early estimate.</b> The distribution changes through implementation, and a TTV built on the architecture-era map measures the wrong hotspot.',
  ],
  roles:[
    {r:'Thermal engineer', d:'Owns heater zoning and sensor placement'},
    {r:'TTV designer', d:'Heater array and die integration'},
    {r:'Metrology engineer', d:'Sensor calibration approach'},
    {r:'Die power liaison', d:'Power map and hotspot distribution'},
    {r:'OSAT liaison', d:'Build feasibility'},
  ],
  effort:[['TTV die integration',2], ['Heater array design',1.75], ['Sensor placement',1.5], ['Design release',1.5], ['Power map translation',1.25]],
  entry:[
    'Vehicle plan available from PTV-01',
    'Power map available from PD-03',
    'Thermal predictions available from PKGD-07',
  ],
  exit:[
    'Heater zones match the product\'s real power distribution',
    'Sensors placed to see gradients, not only a peak',
    'Calibration approach defined before build',
  ],
  dependsOn:['PTV-01','PKGD-01','PKGD-07'],
  dependsNote:null,
  feedsInto:['PTV-05','PTV-09'],
  measuredBy:[
    'Heater zone match against the power map',
    'Sensors placed against gradients of interest',
    'Power delivered against the product\'s envelope',
  ],
},

'PTV-04': {
  stage:'packageTestVehicle', window:[6,14], criticalPath:false,
  purpose:[
    'Design the <b>daisy-chain electrical vehicle</b>—continuity structures through every interconnect level—so assembly yield and interconnect integrity can be measured electrically.',
    'Daisy chains turn assembly quality into a resistance measurement. Every bump, every via and every ball becomes part of a chain that either conducts or does not, which makes an otherwise invisible assembly process observable and quantifiable.',
  ],
  steps:[
    {n:1, text:'Interconnect level inventory — bump, TSV, via, ball', tat:1, lane:'main'},
    {n:2, text:'Daisy chain topology and segmentation design', tat:2, lane:'main'},
    {n:3, text:'Kelvin structures for resistance measurement', tat:1.5, lane:'par'},
    {n:4, text:'Chain-to-location mapping for defect localization', tat:1.5, lane:'main'},
    {n:5, text:'Probe and measurement access design', tat:1.5, lane:'par'},
    {n:6, text:'Daisy-chain vehicle design release', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 2\'s segmentation decides the diagnostic resolution. One long chain says whether the assembly worked; many short segments say where it failed, and the difference is what turns a yield number into a corrective action.',
  consumes:[
    'Vehicle plan from PTV-01',
    'Bump map and interconnect structure from PKGD-02 and PKGD-03',
    'Assembly process from PKGD-10',
    'Substrate ball map from PKGD-04',
    'Measurement capability at the OSAT',
  ],
  produces:[
    'Interconnect level inventory',
    'Daisy chain topology with segmentation',
    'Kelvin resistance structures',
    'Chain-to-location mapping',
    'Probe and measurement access design',
    'Released daisy-chain vehicle design',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D2', rel:'produces', text:'<b>MTV, TTV and daisy-chain vehicle designs.</b> The electrical vehicle of the three.'},
    {id:'PTV-D3', rel:'feeds', text:'<b>Built vehicle lots with assembly travelers.</b> The daisy-chain vehicle is what makes the build\'s quality measurable.'},
  ],
  risks:[
    '<b>Chains too long.</b> A single break makes the whole chain open, and the yield number carries no information about where or why.',
    '<b>No Kelvin structures.</b> Two-wire resistance includes the probe path, and marginal interconnects are exactly where the difference matters.',
    '<b>Chain-to-location mapping omitted.</b> A failing chain that cannot be located gives no basis for a process change.',
    '<b>Not all interconnect levels covered.</b> Bump, TSV, via and ball each fail differently, and a vehicle covering only bumps misses the rest.',
    '<b>Measurement access not planned.</b> A vehicle that can only be measured with equipment the OSAT does not have is a vehicle that is not measured.',
  ],
  roles:[
    {r:'Package test engineer', d:'Owns chain design and measurement'},
    {r:'Package designer', d:'Chain routing through the interconnect levels'},
    {r:'Failure analysis engineer', d:'Localization requirements'},
    {r:'OSAT liaison', d:'Measurement capability and access'},
    {r:'Yield engineer', d:'Segmentation for yield attribution'},
  ],
  effort:[['Chain topology and segmentation',1.5], ['Design release',1.25], ['Chain-to-location mapping',1.25], ['Kelvin structures',1], ['Measurement access',1]],
  entry:[
    'Vehicle plan available from PTV-01',
    'Interconnect structure known from PKGD-02 and PKGD-03',
    'OSAT measurement capability confirmed',
  ],
  exit:[
    'Chains segmented finely enough to localize a failure',
    'Every interconnect level covered by at least one structure',
    'Measurement possible with equipment the OSAT actually has',
  ],
  dependsOn:['PTV-01','PKGD-02','PKGD-03','PKGD-10'],
  dependsNote:null,
  feedsInto:['PTV-05','PTV-11'],
  measuredBy:[
    'Localization resolution of the chain design',
    'Interconnect levels covered',
    'Measurability at the OSAT',
  ],
},

'PTV-05': {
  stage:'packageTestVehicle', window:[14,30], criticalPath:true,
  purpose:[
    'Build the <b>vehicle hardware</b>—TV die, interposers, substrates—through the same suppliers and processes the product will use.',
    'Sixteen weeks and six man-months: mostly waiting, on the same supplier queues the product will stand in. Using the real suppliers and the real processes is the point—a vehicle built through a different route measures a package the product will never have.',
  ],
  steps:[
    {n:1, text:'Vehicle build planning and quantity definition', tat:1.5, lane:'main'},
    {n:2, text:'TV die fabrication — dummy, TTV and daisy-chain', tat:6, lane:'main'},
    {n:3, text:'Interposer vehicle build', tat:5, lane:'par'},
    {n:4, text:'Substrate vehicle build', tat:5.5, lane:'main'},
    {n:5, text:'Incoming inspection and material qualification', tat:2.5, lane:'par'},
    {n:6, text:'Material readiness for assembly', tat:3, lane:'main'},
  ],
  flowNote:'Step 4 sits on the same substrate queue as the product, which is why it needs planning rather than ordering. Vehicle substrates competing with product substrates for the same capacity is a scheduling problem the program creates for itself if nobody sequences them.',
  consumes:[
    'Vehicle designs from PTV-02, PTV-03 and PTV-04',
    'Supplier capacity from PKGD-09',
    'Substrate and interposer processes from PKGD-03 and PKGD-04',
    'Build quantity from the DOE plan in PTV-06',
    'Material specifications',
  ],
  produces:[
    'Vehicle build plan with quantities',
    'Fabricated TV die',
    'Interposer vehicles',
    'Vehicle build plan and quantities',
    'Substrate vehicles',
    'Incoming inspection records',
    'Materials ready for assembly',
  ],
  producedBy:[1,2,3,4,4,5,6],
  rel:[
    {id:'PTV-D3', rel:'produces', text:'<b>Built vehicle lots with assembly travelers.</b> The material half of the deliverable; <code>PTV-06</code> assembles them.'},
    {id:'PTV-D9', rel:'feeds', text:'<b>Package validation complete record.</b> Nothing can be validated before the vehicles exist.'},
  ],
  risks:[
    '<b>Vehicles built through a different process.</b> A package assembled from materials the product will not use measures a package that will not exist.',
    '<b>Vehicle builds competing with product builds.</b> Same suppliers, same queue; without sequencing one delays the other.',
    '<b>Quantity too small for the DOE.</b> The process window study needs enough units to vary conditions, and a build sized for a single condition cannot support it.',
    '<b>Incoming inspection skipped.</b> A vehicle built from out-of-specification material produces results that describe the material rather than the package.',
    '<b>Build schedule not tracked against the gate.</b> Sixteen weeks of build inside a fifty-two week program leaves limited room for a slip.',
  ],
  roles:[
    {r:'PTV lead', d:'Owns the build plan and schedule'},
    {r:'Supply chain lead', d:'Supplier sequencing against product builds'},
    {r:'Package designer', d:'Vehicle design support during build'},
    {r:'Quality engineer', d:'Incoming inspection and material qualification'},
    {r:'Program manager', d:'Schedule tracking against the wafer-out gate'},
  ],
  effort:[['Substrate and interposer builds',2], ['TV die fabrication',1.5], ['Incoming inspection',1], ['Build planning',0.75], ['Material readiness',0.75]],
  entry:[
    'Vehicle designs released from PTV-02, PTV-03 and PTV-04',
    'Supplier capacity booked through PKGD-09',
    'DOE quantity requirement known from PTV-06',
  ],
  exit:[
    'Vehicles built through the product\'s own suppliers and processes',
    'Quantity sufficient for the assembly DOE',
    'Materials inspected before assembly, not after',
  ],
  dependsOn:['PTV-02','PTV-03','PTV-04','PKGD-09'],
  dependsNote:null,
  feedsInto:['PTV-06','PTV-12'],
  measuredBy:[
    'Build completion against the gate schedule',
    'Units built against the DOE requirement',
    'Incoming inspection findings',
  ],
},

'PTV-06': {
  stage:'packageTestVehicle', window:[28,39], criticalPath:true,
  purpose:[
    'Assemble the vehicles at the OSAT across a <b>designed experiment</b>—bond force, reflow profile, underfill, cure—so the assembly process window is measured rather than assumed.',
    'The process window is what <code>ASSY</code> will run to. Establishing it needs deliberate variation: units assembled at the edges of each parameter, not just at nominal, so that the window\'s boundaries are known rather than the center being confirmed.',
  ],
  steps:[
    {n:1, text:'DOE design across the assembly parameters', tat:1.5, lane:'main'},
    {n:2, text:'Bonding and die attach across conditions', tat:2.5, lane:'main'},
    {n:3, text:'Underfill and cure across conditions', tat:2, lane:'par'},
    {n:4, text:'Molding, lid and TIM attach', tat:2, lane:'main'},
    {n:5, text:'Inline inspection during assembly — X-ray, CSAM', tat:2, lane:'par'},
    {n:6, text:'Assembly traveler and condition traceability', tat:2, lane:'par'},
    {n:7, text:'Assembled lot release to characterization', tat:5, lane:'main'},
  ],
  flowNote:'Step 6 is what makes the DOE usable. Every unit has to be traceable to the exact conditions it was assembled under, and an assembly traveler that records the lot but not the condition turns a designed experiment back into a single build.',
  consumes:[
    'Built vehicle materials from PTV-05',
    'Assembly process definition from PKGD-10',
    'Process parameter ranges from the OSAT',
    'Thermal and mechanical predictions from PKGD-07',
    'Inspection capability at the OSAT',
  ],
  produces:[
    'Assembly DOE design',
    'Bonded vehicles across conditions',
    'Underfilled and cured vehicles',
    'Molded and lidded vehicles',
    'Inline inspection results',
    'Assembly travelers with condition traceability',
    'Assembled units across conditions',
    'Assembled lots released to characterization',
  ],
  producedBy:[1,2,3,4,5,6,7,7],
  rel:[
    {id:'PTV-D3', rel:'produces', text:'<b>Built vehicle lots with assembly travelers.</b> The assembly half of the deliverable, with the condition traceability that makes it useful.'},
    {id:'PTV-D8', rel:'feeds', text:'<b>Frozen assembly process window definition.</b> The window is derived from this DOE, so its design determines what can be known.'},
  ],
  risks:[
    '<b>Assembly at nominal only.</b> That confirms the center and says nothing about the boundaries, which is where production will occasionally operate.',
    '<b>Condition traceability lost.</b> Units that cannot be attributed to their assembly conditions turn the DOE into an expensive single build.',
    '<b>DOE too large for the unit count.</b> Varying every parameter needs units the build did not produce, and an under-powered DOE gives ambiguous results.',
    '<b>Inline inspection omitted.</b> Assembly defects found only at final characterization cannot be attributed to a process step.',
    '<b>OSAT running its standard process.</b> The point is deliberate variation, and an assembler defaulting to its recipe produces no window information.',
  ],
  roles:[
    {r:'Assembly process engineer', d:'Owns the DOE and its execution'},
    {r:'OSAT process engineer', d:'Parameter ranges and assembly execution'},
    {r:'Quality engineer', d:'Traveler discipline and traceability'},
    {r:'Metrology engineer', d:'Inline inspection during assembly'},
    {r:'PTV lead', d:'DOE scope against unit count'},
  ],
  effort:[['Bonding and die attach',3], ['Lot release and handling',2.5], ['Underfill and cure',2], ['Inline inspection',2], ['Molding and lid attach',1.5], ['DOE design and travelers',1]],
  entry:[
    'Vehicle materials ready from PTV-05',
    'Assembly process defined in PKGD-10',
    'OSAT parameter ranges agreed',
  ],
  exit:[
    'Units assembled across the parameter ranges, not only at nominal',
    'Every unit traceable to its assembly conditions',
    'Inline inspection performed during assembly, not after',
  ],
  dependsOn:['PTV-05','PKGD-10'],
  dependsNote:null,
  feedsInto:['PTV-07','PTV-08','PTV-09','PTV-10','PTV-11','PTV-12'],
  measuredBy:[
    'Conditions covered against the DOE design',
    'Units traceable to conditions',
    'Assembly defects caught inline',
  ],
},

'PTV-07': {
  stage:'packageTestVehicle', window:[38,45], criticalPath:false,
  purpose:[
    'Measure <b>warpage and co-planarity across the reflow profile</b>—not at room temperature, but at every point in the thermal cycle where the package deforms.',
    'Warpage is the mechanism behind most 2.5D assembly failures. A package flat at room temperature can bow by more than a hundred microns at reflow peak, opening joints that then re-close as it cools—leaving a unit that looks fine and has intermittent connections.',
  ],
  steps:[
    {n:1, text:'Measurement setup — shadow moiré or equivalent', tat:1, lane:'main'},
    {n:2, text:'Room-temperature baseline across units', tat:1.5, lane:'main'},
    {n:3, text:'Warpage measurement across the reflow profile', tat:2, lane:'main'},
    {n:4, text:'Co-planarity and ball flatness measurement', tat:1.5, lane:'par'},
    {n:5, text:'Condition-to-warpage correlation from the DOE', tat:1.5, lane:'par'},
    {n:6, text:'Comparison against the PKGD-07 simulation', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 6 is what makes the measurement reusable. A warpage number is one package; a validated simulation model predicts the next one, and correlating the two is what turns a measurement into a capability.',
  consumes:[
    'Assembled units with condition traceability from PTV-06',
    'Warpage simulation from PKGD-07',
    'Reflow profile from PKGD-10',
    'Measurement equipment and capability',
    'Co-planarity specification from the assembly requirements',
  ],
  produces:[
    'Measurement setup and method',
    'Room-temperature warpage baseline',
    'Warpage across the reflow profile',
    'Co-planarity and ball flatness results',
    'Condition correlation from the DOE',
    'Simulation comparison',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D4', rel:'produces', text:'<b>Warpage and co-planarity data across the reflow profile.</b> This activity is the deliverable, and the reflow-profile part is what distinguishes it from a room-temperature check.'},
    {id:'PTV-D8', rel:'feeds', text:'<b>Frozen assembly process window definition.</b> Warpage against condition is one of the window\'s defining constraints.'},
  ],
  risks:[
    '<b>Measured only at room temperature.</b> The failure occurs at reflow peak, and the room-temperature number is not predictive of it.',
    '<b>Simulation comparison skipped.</b> Without correlation the model stays unvalidated, and the next package has to be measured from scratch.',
    '<b>Co-planarity ignored.</b> Ball flatness determines whether the package mounts to the board reliably, and it is a separate property from warpage.',
    '<b>Too few units to see condition effects.</b> Warpage varies unit to unit, and distinguishing a condition effect from noise needs population.',
    '<b>Results not linked to assembly conditions.</b> Knowing the warpage without knowing which condition produced it gives no basis for a window.',
  ],
  roles:[
    {r:'Mechanical engineer', d:'Owns warpage measurement and correlation'},
    {r:'Metrology engineer', d:'Measurement setup and execution'},
    {r:'Simulation engineer', d:'Model comparison and update'},
    {r:'Assembly process engineer', d:'Condition attribution'},
    {r:'Quality engineer', d:'Co-planarity against specification'},
  ],
  effort:[['Warpage across reflow',2], ['Simulation comparison',1.75], ['Room-temperature baseline',1.5], ['Co-planarity measurement',1.5], ['Condition correlation',1.25]],
  entry:[
    'Assembled units available from PTV-06',
    'Simulation predictions available from PKGD-07',
    'Measurement equipment available',
  ],
  exit:[
    'Warpage measured across the full reflow profile',
    'Simulation correlated against measurement',
    'Results attributed to assembly conditions',
  ],
  dependsOn:['PTV-02','PTV-06','PKGD-07'],
  dependsNote:null,
  feedsInto:['PTV-12','PKGD-07','ASSY-06'],
  measuredBy:[
    'Peak warpage against the limit',
    'Simulation error against measurement',
    'Condition effects distinguishable from noise',
  ],
},

'PTV-08': {
  stage:'packageTestVehicle', window:[37,48], criticalPath:true,
  purpose:[
    'Evaluate <b>chip-package interaction</b>—the stress the package puts into the die\'s low-k dielectric stack, and whether the bumps and back-end metal survive it.',
    'CPI is the failure mode that makes 2.5D packaging risky at advanced nodes. Ultra-low-k dielectrics are mechanically weak, the package expands differently from the silicon, and the resulting stress concentrates exactly where the bumps meet the top metal. It cracks or it does not, and simulation alone is not enough to know.',
  ],
  steps:[
    {n:1, text:'CPI stress evaluation plan and structure selection', tat:1.5, lane:'main'},
    {n:2, text:'Thermal cycling stress application', tat:3, lane:'main'},
    {n:3, text:'Bump and BEOL integrity inspection', tat:2.5, lane:'par'},
    {n:4, text:'Low-k and ULK crack detection', tat:2.5, lane:'main'},
    {n:5, text:'Cross-section and failure analysis on affected units', tat:2, lane:'par'},
    {n:6, text:'CPI assessment and design implications', tat:4, lane:'main'},
  ],
  flowNote:'Step 5 is destructive and necessary. Electrical and acoustic methods say something is wrong; only cross-sectioning shows what failed and where, and the design implication depends entirely on which layer cracked.',
  consumes:[
    'Assembled MTV units from PTV-06',
    'Die stack and ULK information from TECH-03',
    'Warpage results from PTV-07',
    'Thermal cycling capability',
    'Underfill and material properties',
  ],
  produces:[
    'CPI evaluation plan and structure selection',
    'Thermal cycling stress results',
    'Bump and BEOL integrity findings',
    'ULK crack detection results',
    'Cross-section and failure analysis',
    'CPI assessment with design implications',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D5', rel:'produces', text:'<b>CPI stress assessment report—ULK, bump and BEOL integrity.</b> This activity is the deliverable, and it is the most consequential result the vehicle program produces.'},
    {id:'PTV-D9', rel:'feeds', text:'<b>Package validation complete record.</b> CPI is usually the risk the gate most depends on.'},
  ],
  risks:[
    '<b>CPI evaluated by simulation alone.</b> Material behavior at these dimensions is not predictable to the accuracy the decision needs.',
    '<b>Insufficient thermal cycles.</b> CPI failures accumulate; a short cycle count shows nothing and reassures wrongly.',
    '<b>Cross-sectioning skipped.</b> Detection without localization gives no design implication, and the implication is the output that matters.',
    '<b>Only nominal units stressed.</b> The DOE\'s edge conditions are where CPI is most likely, and testing only the center misses it.',
    '<b>Findings arriving after package design freezes.</b> A CPI problem needs an underfill, bump or design change, none of which are available after <code>PKGD-11</code>.',
  ],
  roles:[
    {r:'Reliability engineer', d:'Owns CPI evaluation and assessment'},
    {r:'Failure analysis engineer', d:'Cross-section and crack detection'},
    {r:'Materials engineer', d:'Underfill and stress mitigation options'},
    {r:'Package architect', d:'Design implications from the findings'},
    {r:'Die liaison', d:'BEOL and ULK stack implications'},
  ],
  effort:[['CPI assessment and implications',3.5], ['Thermal cycling',3], ['Crack detection',2.5], ['Cross-section and FA',2.5], ['Bump and BEOL inspection',2.5]],
  entry:[
    'Assembled units available from PTV-06',
    'Die stack information available from TECH-03',
    'Thermal cycling and FA capability available',
  ],
  exit:[
    'Stress applied to a cycle count that would reveal accumulation',
    'Failures cross-sectioned and localized, not only detected',
    'Findings delivered before the package design freeze',
  ],
  dependsOn:['PTV-02','PTV-06','PTV-07','TECH-03'],
  dependsNote:null,
  feedsInto:['PTV-12','PKGD-11','MP-04'],
  measuredBy:[
    'Thermal cycles survived against the qualification requirement',
    'Failures localized against detected',
    'Weeks between findings and package design freeze',
  ],
},

'PTV-09': {
  stage:'packageTestVehicle', window:[38,47], criticalPath:false,
  purpose:[
    'Characterize the package\'s <b>thermal performance</b>—junction-to-case and junction-to-ambient resistance, TIM behavior, hotspot mapping—and correlate it against the simulation.',
    'The thermal path decides the achievable power envelope, and the product is sold on that envelope. Measuring it on a TTV that reproduces the real power distribution is what turns a simulated Rjc into a number the datasheet can carry.',
  ],
  steps:[
    {n:1, text:'Thermal measurement setup and sensor calibration', tat:1.5, lane:'main'},
    {n:2, text:'Steady-state Rjc and Rja measurement', tat:2, lane:'main'},
    {n:3, text:'Hotspot mapping across the heater zones', tat:2, lane:'par'},
    {n:4, text:'TIM performance and bond line study', tat:2, lane:'main'},
    {n:5, text:'Transient thermal response measurement', tat:1.5, lane:'par'},
    {n:6, text:'Correlation against the PKGD-07 thermal model', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 4 measures the interface nobody can simulate reliably. TIM performance depends on bond line thickness, pressure and pump-out over time, and the datasheet value is a starting point rather than an answer.',
  consumes:[
    'Assembled TTV units from PTV-06',
    'Thermal simulation from PKGD-07',
    'Sensor calibration approach from PTV-03',
    'Thermal measurement equipment',
    'TIM material options',
  ],
  produces:[
    'Thermal measurement setup and calibration',
    'Rjc and Rja measurements',
    'Hotspot maps across zones',
    'TIM performance and bond line results',
    'Transient thermal response',
    'Model correlation results',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D6', rel:'produces', text:'<b>Thermal characterization report with model correlation.</b> This activity is the deliverable, and the correlation is what makes the model reusable.'},
    {id:'PTV-D8', rel:'feeds', text:'<b>Frozen assembly process window definition.</b> TIM bond line is an assembly parameter, and its thermal effect is measured here.'},
  ],
  risks:[
    '<b>TIM performance taken from the datasheet.</b> Bond line thickness and pressure are assembly parameters, and the achieved performance differs from the specification.',
    '<b>Hotspot not measured.</b> The average junction temperature is not what limits the part; the hottest zone is.',
    '<b>Simulation not correlated.</b> The model then remains unvalidated, and every future thermal question needs another vehicle.',
    '<b>Transient response ignored.</b> An accelerator\'s power is bursty, and the transient behavior determines whether the package can absorb a workload spike.',
    '<b>Measured at a single ambient condition.</b> Rja depends on airflow and ambient, and one condition does not characterize the range the product will see.',
  ],
  roles:[
    {r:'Thermal engineer', d:'Owns characterization and model correlation'},
    {r:'Metrology engineer', d:'Measurement setup and calibration'},
    {r:'Materials engineer', d:'TIM options and bond line study'},
    {r:'Simulation engineer', d:'Model update from measurement'},
    {r:'Product engineering', d:'Envelope implications for the datasheet'},
  ],
  effort:[['Model correlation',2.5], ['Rjc and Rja measurement',2], ['TIM study',2], ['Hotspot mapping',1.75], ['Transient measurement',1.75]],
  entry:[
    'Assembled TTV units available from PTV-06',
    'Thermal simulation available from PKGD-07',
    'Sensors calibrated per the PTV-03 approach',
  ],
  exit:[
    'TIM performance measured as assembled, not as specified',
    'Hotspot mapped rather than averaged',
    'Thermal model correlated and updated',
  ],
  dependsOn:['PTV-03','PTV-06','PKGD-07'],
  dependsNote:null,
  feedsInto:['PTV-12','PKGD-07','SIPI-10','MP-02'],
  measuredBy:[
    'Measured Rjc against simulation',
    'Hotspot temperature against the envelope requirement',
    'TIM performance as assembled against specification',
  ],
},

'PTV-10': {
  stage:'packageTestVehicle', window:[36,50], criticalPath:true,
  purpose:[
    'Stress the vehicles through <b>board-level reliability</b>—temperature cycling, drop, bend—because the package has to survive being mounted in a system, not only being assembled.',
    'Board-level reliability is where the package meets the customer\'s manufacturing process. Solder joints crack under thermal cycling, boards flex during handling, and a package that passes component qualification and fails board-level testing is a package the customer cannot use.',
  ],
  steps:[
    {n:1, text:'Board-level test plan and coupon board design', tat:2, lane:'main'},
    {n:2, text:'Coupon board fabrication and vehicle mounting', tat:2.5, lane:'main'},
    {n:3, text:'Temperature cycling to failure', tat:4, lane:'main'},
    {n:4, text:'Drop and shock testing', tat:2.5, lane:'par'},
    {n:5, text:'Bend and flex testing', tat:2, lane:'par'},
    {n:6, text:'Failure mode analysis and characteristic life', tat:5.5, lane:'main'},
  ],
  flowNote:'Step 3 runs to failure rather than to a pass criterion. Characteristic life—the cycle count at which a defined fraction fails—is what a customer needs to assess the package in their system, and a pass at a fixed cycle count does not provide it.',
  consumes:[
    'Assembled units from PTV-06',
    'Board-level reliability standards (JEDEC)',
    'Customer board and mounting requirements',
    'Coupon board design capability',
    'Reliability chamber capacity',
  ],
  produces:[
    'Board-level test plan and coupon boards',
    'Mounted vehicle assemblies',
    'Temperature cycling results to failure',
    'Drop and shock results',
    'Bend and flex results',
    'Failure mode analysis and characteristic life',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D7', rel:'produces', text:'<b>Board-level reliability data on vehicles.</b> This activity is the deliverable, and characteristic life is what customers will ask for.'},
    {id:'PTV-D9', rel:'feeds', text:'<b>Package validation complete record.</b> Board-level survival is part of what "validated" has to mean.'},
  ],
  risks:[
    '<b>Testing to a pass criterion rather than to failure.</b> A pass tells the customer nothing about margin; characteristic life does.',
    '<b>Coupon board unrepresentative.</b> Board thickness and pad design affect solder joint stress, and a test board unlike the customer\'s predicts poorly.',
    '<b>Started too late to finish.</b> Temperature cycling to failure takes months, and it is the longest test in the vehicle program.',
    '<b>Failure modes not analyzed.</b> Knowing units failed at a cycle count without knowing how gives no route to improvement.',
    '<b>Only one mounting condition.</b> Different customers mount differently, and the package\'s sensitivity to that is worth knowing.',
  ],
  roles:[
    {r:'Reliability engineer', d:'Owns board-level testing and analysis'},
    {r:'Board engineer', d:'Coupon board design and mounting'},
    {r:'Failure analysis engineer', d:'Failure mode identification'},
    {r:'Quality liaison', d:'Standards compliance and customer requirements'},
    {r:'Package architect', d:'Design implications from failures'},
  ],
  effort:[['Failure analysis and characteristic life',2.5], ['Temperature cycling',2], ['Coupon board and mounting',1.5], ['Drop and shock',1], ['Bend and flex',1]],
  entry:[
    'Assembled units available from PTV-06',
    'Board-level standards and customer requirements known',
    'Reliability chamber capacity booked',
  ],
  exit:[
    'Testing run to failure, with characteristic life established',
    'Coupon boards representative of customer mounting',
    'Failure modes identified, not only counted',
  ],
  dependsOn:['PTV-06'],
  dependsNote:null,
  feedsInto:['PTV-12','MP-04','MP-11'],
  measuredBy:[
    'Characteristic life against the requirement',
    'Failure modes identified against failures observed',
    'Test completion against the wafer-out gate',
  ],
},

'PTV-11': {
  stage:'packageTestVehicle', window:[39,48], criticalPath:false,
  purpose:[
    'Measure <b>assembly yield electrically</b> through the daisy chains, localize what failed, and turn that into process learning before the product is assembled.',
    'Assembly yield on a 2.5D package with hundreds of thousands of interconnects is not guaranteed. The daisy chains make it measurable, and the segmentation makes it attributable—which is what lets the OSAT fix a process problem rather than accept a yield number.',
  ],
  steps:[
    {n:1, text:'Continuity test setup and measurement plan', tat:1, lane:'main'},
    {n:2, text:'Chain continuity measurement across units', tat:2, lane:'main'},
    {n:3, text:'Kelvin resistance measurement on interconnects', tat:1.5, lane:'par'},
    {n:4, text:'Failure localization from chain segmentation', tat:2, lane:'main'},
    {n:5, text:'Condition-to-yield correlation from the DOE', tat:1.5, lane:'par'},
    {n:6, text:'Assembly yield learning and process feedback', tat:4, lane:'main'},
  ],
  flowNote:'Step 5 is why the DOE was run. Yield varying with bond force or reflow profile identifies the parameter that matters, and that is the parameter the process window in <code>PTV-12</code> will be built around.',
  consumes:[
    'Assembled daisy-chain units from PTV-06',
    'Chain-to-location mapping from PTV-04',
    'Assembly conditions from the travelers',
    'Measurement capability at the OSAT',
    'Yield expectations from the cost model',
  ],
  produces:[
    'Continuity test setup and plan',
    'Chain continuity results across units',
    'Kelvin resistance measurements',
    'Failure localization findings',
    'Condition-to-yield correlation',
    'Assembly yield learning and process feedback',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D3', rel:'feeds', text:'<b>Built vehicle lots with assembly travelers.</b> The travelers\' condition data is what makes this analysis possible.'},
    {id:'PTV-D8', rel:'feeds', text:'<b>Frozen assembly process window definition.</b> Yield against condition is the window\'s most direct evidence.'},
  ],
  risks:[
    '<b>Yield measured without localization.</b> A number with no location gives the OSAT nothing to act on.',
    '<b>Marginal interconnects passing continuity.</b> A high-resistance joint conducts and will fail in the field; Kelvin measurement is what distinguishes it.',
    '<b>Condition correlation not performed.</b> The DOE\'s whole purpose is to link yield to parameters, and skipping the analysis wastes the build.',
    '<b>Feedback arriving after the process freezes.</b> Learning that cannot change the process window is learning with no consequence.',
    '<b>Sample size too small for yield estimation.</b> Assembly yield is a rate, and estimating it needs enough units for the rate to be meaningful.',
  ],
  roles:[
    {r:'Package test engineer', d:'Owns continuity measurement and localization'},
    {r:'Yield engineer', d:'Yield estimation and condition correlation'},
    {r:'OSAT process engineer', d:'Process feedback and corrective action'},
    {r:'Failure analysis engineer', d:'Physical confirmation of localized failures'},
    {r:'Quality engineer', d:'Marginal interconnect criteria'},
  ],
  effort:[['Yield learning and feedback',1.5], ['Continuity measurement',1.25], ['Failure localization',1.25], ['Kelvin measurement',1], ['Condition correlation',1]],
  entry:[
    'Assembled daisy-chain units available from PTV-06',
    'Chain-to-location mapping available from PTV-04',
    'Assembly condition travelers complete',
  ],
  exit:[
    'Failures localized to interconnect level and position',
    'Marginal joints identified by resistance, not only by continuity',
    'Feedback delivered before the process window freezes',
  ],
  dependsOn:['PTV-04','PTV-06'],
  dependsNote:null,
  feedsInto:['PTV-12','ASSY-07','MP-05'],
  measuredBy:[
    'Assembly yield against the cost model assumption',
    'Failures localized against detected',
    'Yield variation explained by DOE conditions',
  ],
},

'PTV-12': {
  stage:'packageTestVehicle', window:[45,52], criticalPath:true,
  purpose:[
    'Freeze the <b>assembly process window</b>, feed the findings back into package design, and declare package validation complete—the gate product wafer-out has to clear.',
    'This is the activity the whole stage exists for. It converts a large body of measurement into two things: a process window <code>ASSY</code> will run to, and a statement that the package has been validated. Product wafers must not come out before it is issued, because the alternative is learning about the package on real dies.',
  ],
  steps:[
    {n:1, text:'Result consolidation across all vehicle characterization', tat:1, lane:'main'},
    {n:2, text:'Risk retirement assessment against the coverage matrix', tat:1.5, lane:'main'},
    {n:3, text:'Package design feedback and change requests', tat:1.5, lane:'par'},
    {n:4, text:'Assembly process window definition and freeze', tat:2, lane:'main'},
    {n:5, text:'Residual risk statement for unretired items', tat:1, lane:'par'},
    {n:6, text:'Package validation complete declaration', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 2 is the honest accounting. Some risks in the matrix will not have been retired—a vehicle failed, a measurement was inconclusive—and the declaration has to say which, rather than declaring completion because the date arrived.',
  consumes:[
    'Warpage results from PTV-07',
    'CPI assessment from PTV-08',
    'Thermal characterization from PTV-09',
    'Board-level reliability from PTV-10',
    'Assembly yield learning from PTV-11',
  ],
  produces:[
    'Consolidated vehicle results',
    'Risk retirement assessment against the matrix',
    'Package design feedback and change requests',
    'Frozen assembly process window',
    'Residual risk statement',
    'Package validation complete declaration',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'PTV-D8', rel:'produces', text:'<b>Frozen assembly process window definition.</b> The window <code>ASSY</code> will build the product to, derived from evidence rather than from the OSAT\'s standard recipe.'},
    {id:'PTV-D9', rel:'produces', text:'<b>Package validation complete record—gate for product wafer-out.</b> This activity carries the stage\'s milestone and the gate.'},
  ],
  risks:[
    '<b>Completion declared because the date arrived.</b> The gate exists to be capable of holding wafer-out, and a declaration that cannot say no is not a gate.',
    '<b>Unretired risks not stated.</b> A validation record that implies full coverage when some risks remain open misleads exactly the decision it informs.',
    '<b>Feedback arriving after PKGD-11.</b> Package design changes are not available after the freeze, so vehicle findings have to land before it.',
    '<b>Process window frozen too wide.</b> A window that accommodates every observed condition is not a window; the boundaries have to exclude what produced failures.',
    '<b>Window not transferred to the OSAT as a specification.</b> A window that exists in a report and not in the assembly instructions will not be followed.',
  ],
  roles:[
    {r:'PTV lead', d:'Owns consolidation, the window and the declaration'},
    {r:'Package architect', d:'Design feedback and change requests'},
    {r:'Assembly process engineer', d:'Process window definition'},
    {r:'Reliability engineer', d:'Risk retirement assessment'},
    {r:'Program manager', d:'Gate decision against wafer-out'},
  ],
  effort:[['Validation declaration',1.25], ['Process window definition',1], ['Risk retirement assessment',1], ['Design feedback',1], ['Residual risk statement',0.75]],
  entry:[
    'Characterization complete from PTV-07 through PTV-11',
    'Coverage matrix available from PTV-01',
    'Wafer-out date known from FAB-09',
  ],
  exit:[
    'Every matrix risk marked retired or explicitly not retired',
    'Process window frozen with boundaries that exclude observed failures',
    'Window transferred to the OSAT as a specification, not a report',
  ],
  dependsOn:['PTV-01','PTV-07','PTV-08','PTV-09','PTV-10','PTV-11'],
  dependsNote:null,
  feedsInto:['ASSY-01','ASSY-07','FAB-10','MP-04'],
  measuredBy:[
    'Risks retired against the coverage matrix',
    'Weeks of margin against the wafer-out gate',
    'Process window adopted by the OSAT',
  ],
},

};
