/* RTL — RTL Design & Integration. Ten activities. Stage w20–52 (32w), 410 M/M. */
module.exports = {

'RTL-01': {
  stage:'rtl', window:[0,10], criticalPath:true,
  purpose:[
    'Complete the <b>microarchitecture specification for every block</b>—pipeline, interfaces, control, register map—to the level of detail an implementer can write code against without inventing anything.',
    '<code>ARCH-10</code> started these inside architecture; this finishes them. The distinction matters: a block whose specification is still being written while its RTL is being written produces code that documents itself, and the specification then follows the code instead of leading it.',
  ],
  steps:[
    {n:1, text:'Specification completion plan and block-owner assignment', tat:1, lane:'main'},
    {n:2, text:'Pipeline and datapath detail per block', tat:3, lane:'main'},
    {n:3, text:'Control and state machine specification', tat:2.5, lane:'par'},
    {n:4, text:'Block interface and protocol detail against the NoC', tat:2.5, lane:'main'},
    {n:5, text:'Exception, error and corner-case behavior', tat:2, lane:'par'},
    {n:6, text:'Verification hook and observability requirements with DV', tat:1.5, lane:'par'},
    {n:7, text:'Specification review and implementation entry gate', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 5 is the section most often left thin and the one verification spends the most time on. Corner-case behavior that the specification does not define is behavior the implementer chooses and the verification engineer has no basis to check.',
  consumes:[
    'Architecture specification and block chapters from ARCH-09',
    'Microarchitecture drafts from ARCH-10',
    'PPA budgets per block from ARCH-06',
    'Verification strategy from DV-01',
    'Interface definitions from ARCH-04',
  ],
  produces:[
    'Block microarchitecture specifications, complete',
    'Per-block pipeline and datapath detail',
    'Control and state machine definitions',
    'Interface and protocol detail per block',
    'Exception and corner-case behavior definitions',
    'Verification hook and observability requirements',
    'Implementation entry gate records',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'RTL-D1', rel:'feeds', text:'<b>Block and top-level RTL release.</b> The specification is what the release is checked against; without it, review has nothing to compare code to.'},
    {id:'RTL-D7', rel:'gates', text:'<b>RTL Freeze package.</b> A block whose specification was never completed cannot be declared frozen against anything.'},
  ],
  risks:[
    '<b>Specification written alongside the code.</b> The document then records what was built rather than defining it, and verification loses its independent reference.',
    '<b>Corner cases left undefined.</b> The implementer decides, verification cannot check, and the disagreement surfaces at chip-level integration.',
    '<b>Interfaces specified from one side.</b> Two blocks each documenting their own view of a shared protocol produces two consistent documents that disagree.',
    '<b>Entry gate skipped for schedule.</b> Coding against an incomplete specification is faster for two weeks and slower for two months.',
    '<b>Observability requirements added later.</b> Debug and coverage hooks designed in cost little; retrofitted they cost timing and an RTL change under control.',
  ],
  roles:[
    {r:'Block owners', d:'Author their block\'s specification'},
    {r:'RTL lead', d:'Owns the entry gate and specification quality'},
    {r:'Interconnect architect', d:'Arbitrates shared interface definitions'},
    {r:'Verification leads', d:'Observability and checkability requirements'},
    {r:'Chief architect', d:'Resolves conflicts against the architecture specification'},
  ],
  effort:[['Pipeline and datapath detail',14], ['Control and state machines',9], ['Interface detail',7], ['Exception and corner-case behavior',5], ['Reviews and entry gate',5]],
  entry:[
    'Architecture specification frozen by ARCH-09',
    'Block owners assigned and available',
    'PPA budgets accepted per block',
  ],
  exit:[
    'Every block passes an entry gate before implementation starts',
    'Corner-case behavior defined, not left to the implementer',
    'Shared interfaces agreed by both sides',
  ],
  dependsOn:['ARCH-06','ARCH-09','ARCH-10'],
  dependsNote:null,
  feedsInto:['RTL-02','RTL-04','RTL-07','DV-01','DV-03'],
  measuredBy:[
    'Blocks passing the entry gate before coding starts',
    'Specification changes raised during implementation',
    'Corner cases defined against those found in verification',
  ],
},

'RTL-02': {
  stage:'rtl', window:[4,28], criticalPath:true,
  purpose:[
    'Write the <b>synthesisable logic for every block</b>, to a coding standard that survives lint, CDC, synthesis and gate-level simulation without rework.',
    'At 180 man-months this is the largest single activity in the entire template—nearly 5% of the program\'s effort in one line. It is also the one most exposed to specification churn: every change upstream lands here, multiplied by the number of blocks that inherit it.',
  ],
  steps:[
    {n:1, text:'Coding standard, directory structure and naming conventions', tat:1.5, lane:'main'},
    {n:2, text:'Block RTL implementation, first pass', tat:9, lane:'main'},
    {n:3, text:'Block-level self-checking and assertion insertion', tat:4, lane:'par'},
    {n:4, text:'Block RTL review against specification', tat:3.5, lane:'main'},
    {n:5, text:'Parameterization and configurability implementation', tat:3, lane:'par'},
    {n:6, text:'Bug fix and refinement against block verification', tat:7, lane:'main'},
    {n:7, text:'Block-level PPA refinement against trial synthesis', tat:4, lane:'par'},
    {n:8, text:'Block freeze and release tagging', tat:3, lane:'main'},
  ],
  flowNote:'Step 6 is seven weeks of fixing rather than writing, and it is the honest half of RTL. First-pass code is written in step 2; what makes it correct is the loop against block-level verification, and shortening that loop is where schedule pressure does the most damage.',
  consumes:[
    'Block specifications from RTL-01',
    'Coding and lint standards from the methodology',
    'IP integration requirements from RTL-03',
    'Verification feedback from DV-03',
    'Trial synthesis results from RTL-08',
  ],
  produces:[
    'Coding standard and repository structure',
    'First-pass block RTL',
    'Embedded assertions and self-checking',
    'Block RTL review findings',
    'Parameterization and configurability implementation',
    'Fixed and refined block RTL',
    'Block-level PPA refinement record',
    'Block RTL source, tagged',
    'Parameterized and configurable blocks',
    'Block review records',
    'Block release tags with known issues',
  ],
  producedBy:[1,2,3,4,5,6,7,8,8,8,8],
  rel:[
    {id:'RTL-D1', rel:'produces', text:'<b>Block and top-level RTL release, tagged.</b> The block half of the deliverable; <code>RTL-04</code> assembles the top.'},
    {id:'RTL-D4', rel:'feeds', text:'<b>Lint / CDC / RDC clean reports.</b> Clean reports are a property of the code, and the coding standard set here largely determines them.'},
  ],
  risks:[
    '<b>Specification churn arriving mid-implementation.</b> Every upstream change lands here multiplied by the blocks affected, which is why <code>RTL-10</code> exists.',
    '<b>Coding standard imposed after code exists.</b> Retrofitting a standard across 180 man-months of code is a project nobody schedules and everyone half-does.',
    '<b>Assertions treated as verification\'s job.</b> Assertions written by the implementer capture intent; written by someone else they capture observed behavior.',
    '<b>Blocks declared complete without verification feedback.</b> First-pass code is not correct code, and a block frozen before its verification loop closes freezes its bugs.',
    '<b>Configurability added everywhere.</b> Parameterization nobody uses multiplies the verification space at no benefit, and the cost lands on <code>DV-03</code>.',
  ],
  roles:[
    {r:'Block designers', d:'Implement, review and refine their blocks'},
    {r:'RTL lead', d:'Coding standard, review discipline and freeze'},
    {r:'Verification engineers', d:'Feedback loop through block-level testing'},
    {r:'Synthesis liaison', d:'Trial synthesis feedback on PPA'},
    {r:'Configuration manager', d:'Release tagging and traceability'},
  ],
  effort:[['Block implementation',70], ['Bug fix and refinement',45], ['Assertions and self-checking',25], ['Block review',20], ['PPA refinement',12], ['Parameterization',8]],
  entry:[
    'Block specifications passed the RTL-01 entry gate',
    'Coding standard and build environment available',
    'Block-level verification environment starting up in DV-02',
  ],
  exit:[
    'Every block reviewed against its specification, not only linted',
    'Blocks frozen only after their verification loop has closed',
    'Releases tagged with known issues listed',
  ],
  dependsOn:['RTL-01','RTL-09'],
  dependsNote:null,
  feedsInto:['RTL-04','RTL-06','RTL-08','DV-03','SYN-02'],
  measuredBy:[
    'Blocks frozen against blocks planned',
    'Bugs found per block after freeze',
    'Specification changes absorbed during implementation',
  ],
},

'RTL-03': {
  stage:'rtl', window:[8,24], criticalPath:true,
  purpose:[
    'Bring every third-party, foundry and internal IP into the design—<b>wrappers, glue, configuration and version control</b>—and prove each one behaves as its documentation claims.',
    'IP integration fails at the boundary rather than in the block. A PHY that meets its specification and a controller that meets its specification can still disagree about reset ordering, and the disagreement is found here or it is found in the lab.',
  ],
  steps:[
    {n:1, text:'IP receipt, incoming inspection against the acceptance checklist', tat:1.5, lane:'main'},
    {n:2, text:'Integration environment and wrapper framework', tat:2, lane:'main'},
    {n:3, text:'Per-IP wrapper and glue implementation', tat:5, lane:'main'},
    {n:4, text:'Configuration, tie-off and parameter setting per IP', tat:3, lane:'par'},
    {n:5, text:'Boundary and reset sequencing verification per IP', tat:4, lane:'main'},
    {n:6, text:'AMS macro integration with behavioural models', tat:3.5, lane:'par'},
    {n:7, text:'IP version manifest and update handling', tat:2.5, lane:'par'},
    {n:8, text:'Integration report and issue escalation to vendors', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 1 is the acceptance check <code>IPR-06</code> defined, and it is the last point at which an incomplete delivery is the vendor\'s problem. Accepting a delivery without inspecting it transfers the missing views to the integration team.',
  consumes:[
    'IP deliveries against the schedule from IPR-09',
    'Acceptance checklists from IPR-06',
    'AMS macros and models from AMS-15 and AMS-16',
    'Block RTL from RTL-02',
    'Integration requirements from the architecture specification',
  ],
  produces:[
    'Incoming inspection records per delivery',
    'Integration environment and wrapper framework',
    'IP wrappers and glue logic',
    'Per-IP configuration and tie-off',
    'Boundary and reset sequencing verification results',
    'AMS macro integration with behavioural models',
    'IP version manifest',
    'Integration report and vendor issue log',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'RTL-D6', rel:'produces', text:'<b>IP integration report and version manifest.</b> This activity is the deliverable, and the manifest is what makes an IP-related bug traceable to a version.'},
    {id:'RTL-D1', rel:'feeds', text:'<b>Block and top-level RTL release.</b> Integrated IP is part of the release, and its versions are part of the tag.'},
  ],
  risks:[
    '<b>Deliveries accepted without inspection.</b> Missing views and collateral then become the integration team\'s problem rather than the vendor\'s.',
    '<b>Boundary behavior assumed from documentation.</b> Reset ordering, enable timing and calibration sequences are where IP integration actually fails.',
    '<b>Version manifest not maintained.</b> An IP bug that cannot be traced to a version cannot be reported usefully or fixed reproducibly.',
    '<b>IP updates absorbed silently.</b> A vendor drop applied without impact assessment can change behavior verification has already signed off.',
    '<b>Late IP compressing integration.</b> The integration window is fixed at its far end by <code>RTL-04</code>; a late delivery does not move it, it shortens it.',
  ],
  roles:[
    {r:'IP integration lead', d:'Owns integration, inspection and the manifest'},
    {r:'Integration engineers', d:'Wrappers, glue and configuration'},
    {r:'Verification engineers', d:'Boundary and sequencing verification'},
    {r:'AMS integration engineer', d:'Analog macro integration and co-simulation'},
    {r:'Procurement liaison', d:'Vendor escalation on delivery and quality issues'},
  ],
  effort:[['Wrapper and glue implementation',14], ['Boundary and sequencing verification',11], ['AMS macro integration',7], ['Configuration and tie-off',5], ['Incoming inspection',4], ['Version manifest and reporting',4]],
  entry:[
    'IP delivery schedule aligned by IPR-09',
    'Acceptance checklists agreed in IPR-06',
    'Integration environment available from RTL-09',
  ],
  exit:[
    'Every delivery inspected against its checklist on receipt',
    'Boundary and reset behavior verified, not assumed from documentation',
    'Version manifest complete and maintained through updates',
  ],
  dependsOn:['IPR-06','IPR-07','IPR-09','AMS-15','AMS-16'],
  dependsNote:null,
  feedsInto:['RTL-04','RTL-06','DV-03','DV-07','PD-02'],
  measuredBy:[
    'Deliveries inspected on receipt',
    'Boundary defects found here against those found at chip level',
    'IP issues traceable to a manifest version',
  ],
},

'RTL-04': {
  stage:'rtl', window:[16,28], criticalPath:true,
  purpose:[
    'Assemble the blocks and the IP into <b>one top-level design that elaborates, connects and boots</b>—the first point at which the chip exists as a single object.',
    'Chip-level integration is where every optimistic assumption made in isolation meets every other one. Connectivity, clock and reset distribution, address maps and configuration all become concrete here, and the defects found are the ones no block-level test could have seen.',
  ],
  steps:[
    {n:1, text:'Top-level hierarchy and connectivity definition', tat:1.5, lane:'main'},
    {n:2, text:'NoC and interconnect integration', tat:3, lane:'main'},
    {n:3, text:'Clock and reset distribution implementation', tat:2.5, lane:'par'},
    {n:4, text:'Address map and configuration space assembly', tat:2, lane:'par'},
    {n:5, text:'Top-level elaboration and connectivity checking', tat:2.5, lane:'main'},
    {n:6, text:'Boot and bring-up path integration', tat:2.5, lane:'par'},
    {n:7, text:'Chip-level smoke tests and first boot', tat:2.5, lane:'main'},
    {n:8, text:'Integration issue closure and top release', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 7—the first chip-level boot in simulation—is the moment the design becomes real. It is also slow, because the first boot exercises paths that no block test touched, and each failure takes a full-chip simulation to reproduce.',
  consumes:[
    'Block RTL releases from RTL-02',
    'Integrated IP from RTL-03',
    'Power and clock intent from RTL-05',
    'Register map from RTL-07',
    'Top-level architecture from ARCH-09',
  ],
  produces:[
    'Top-level hierarchy and connectivity',
    'Integrated NoC and interconnect',
    'Clock and reset distribution',
    'Assembled address map and configuration space',
    'Elaborated top level with connectivity check results',
    'Integrated boot and bring-up path',
    'Chip-level smoke test results',
    'Top-level RTL release',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'RTL-D1', rel:'produces', text:'<b>Block and top-level RTL release, tagged.</b> The top half of the deliverable—the object every downstream stage actually consumes.'},
    {id:'RTL-D7', rel:'feeds', text:'<b>RTL Freeze package.</b> Freeze is declared on the top-level release, so its state is what the package describes.'},
  ],
  risks:[
    '<b>Connectivity checked by inspection.</b> A chip this size has too many connections to review; automated connectivity checking is the only reliable method.',
    '<b>Integration started before blocks are stable.</b> Integrating moving blocks produces defects that are re-found every time a block updates.',
    '<b>Address map assembled from block documentation.</b> Generated maps agree with the code; hand-assembled maps agree with the documentation, which is a different thing.',
    '<b>First boot deferred.</b> The boot path exercises reset, clocking, configuration and the fabric together, and delaying it delays every defect that only appears in combination.',
    '<b>Clock and reset distribution treated as a wiring task.</b> It carries the crossing inventory from <code>ARCH-05</code> and the CDC obligations that follow from it.',
  ],
  roles:[
    {r:'Chip integration lead', d:'Owns the top level and its release'},
    {r:'Integration engineers', d:'Hierarchy, connectivity and fabric integration'},
    {r:'Clock and reset owner', d:'Distribution implementation'},
    {r:'Verification engineers', d:'Chip-level smoke tests and first boot'},
    {r:'Software liaison', d:'Boot path and configuration space expectations'},
  ],
  effort:[['NoC and interconnect integration',9], ['Chip-level smoke tests and boot',7], ['Connectivity checking',6], ['Clock and reset distribution',5], ['Address map assembly',4], ['Issue closure and release',4]],
  entry:[
    'Blocks stable enough to integrate from RTL-02',
    'IP integrated and boundary-verified in RTL-03',
    'Register map generated by RTL-07',
  ],
  exit:[
    'Connectivity verified automatically, not by inspection',
    'Chip boots in simulation before freeze is contemplated',
    'Top-level release tagged with its full IP manifest',
  ],
  dependsOn:['RTL-02','RTL-03','RTL-05','RTL-07'],
  dependsNote:null,
  feedsInto:['RTL-06','RTL-08','DV-04','SYN-02','DFT-06'],
  measuredBy:[
    'Connectivity defects found by checking against by simulation',
    'Weeks from first integration to first successful boot',
    'Blocks integrated against blocks released',
  ],
},

'RTL-05': {
  stage:'rtl', window:[6,16], criticalPath:false,
  purpose:[
    'Implement the <b>clock, reset and power intent</b> the architecture defined—domain boundaries, isolation, retention, crossing synchronisers—and produce a UPF file the tools accept.',
    'Power intent is where architecture becomes an obligation on every downstream tool. Synthesis inserts isolation cells from it, verification checks against it, and physical design implements it. An intent file that is wrong or incomplete propagates the same error into all three.',
  ],
  steps:[
    {n:1, text:'Domain boundary implementation against the ARCH-05 definition', tat:2, lane:'main'},
    {n:2, text:'Isolation, level shifter and retention strategy implementation', tat:2.5, lane:'main'},
    {n:3, text:'Clock domain crossing synchroniser implementation', tat:2, lane:'par'},
    {n:4, text:'Reset sequencing and synchronization implementation', tat:1.5, lane:'par'},
    {n:5, text:'UPF authoring and tool acceptance check', tat:2.5, lane:'main'},
    {n:6, text:'Power management controller RTL', tat:2, lane:'par'},
    {n:7, text:'Intent review with synthesis, verification and physical design', tat:3, lane:'main'},
  ],
  flowNote:'Step 5 includes a tool acceptance check because UPF that reads correctly to a human and fails to elaborate in synthesis is common. The file has to be exercised in the actual flow, not reviewed as a document.',
  consumes:[
    'Power and clock architecture from ARCH-05',
    'Crossing inventory from ARCH-05',
    'Block list and hierarchy from RTL-01',
    'UPF methodology from PDK-09',
    'Library low-power cell availability from PDK-03',
  ],
  produces:[
    'Implemented power domain boundaries',
    'Isolation, level shifter and retention implementation',
    'Implemented domain boundaries',
    'CDC synchroniser implementation',
    'Reset sequencing logic',
    'UPF power intent file, tool-accepted',
    'Power management controller RTL',
    'Power intent review record',
  ],
  producedBy:[1,2,3,3,4,5,6,7],
  rel:[
    {id:'RTL-D5', rel:'produces', text:'<b>UPF power intent file.</b> This activity is the deliverable, and "tool-accepted" is the standard rather than "reviewed".'},
    {id:'RTL-D4', rel:'feeds', text:'<b>Lint / CDC / RDC clean reports.</b> The synchroniser implementation is what CDC closure in <code>RTL-06</code> is checking.'},
  ],
  risks:[
    '<b>UPF written as a document.</b> Intent that has never been elaborated in synthesis is intent whose errors are found by the first person who runs the flow.',
    '<b>Crossings implemented without reference to the inventory.</b> A synchroniser strategy chosen per crossing by each designer produces inconsistency CDC will flag hundreds of times.',
    '<b>Retention strategy decided late.</b> Retention cells cost area and change the physical implementation; adding them after floorplan is expensive.',
    '<b>Reset sequencing implemented from the block view.</b> Reset order is a chip-level property, and blocks each releasing in their own order produces a boot that works in simulation and not in silicon.',
    '<b>Intent reviewed only by its author.</b> Synthesis, verification and physical design each consume it differently, and each has to confirm it works for them.',
  ],
  roles:[
    {r:'Low-power implementation lead', d:'Owns domains, intent and the UPF file'},
    {r:'Clock and reset owner', d:'Synchroniser and reset sequencing implementation'},
    {r:'Synthesis liaison', d:'Confirms the intent elaborates and infers correctly'},
    {r:'Verification liaison', d:'Confirms the intent is checkable'},
    {r:'Physical design liaison', d:'Confirms the intent is implementable'},
  ],
  effort:[['Isolation and retention implementation',5], ['Domain boundary implementation',4], ['UPF authoring and acceptance',3.5], ['CDC synchroniser implementation',2.5], ['Power management controller',2], ['Intent review',1]],
  entry:[
    'Power and clock architecture fixed by ARCH-05',
    'Crossing inventory available',
    'Low-power cells qualified in PDK-03',
  ],
  exit:[
    'UPF elaborates in synthesis, not only reviews well',
    'Every crossing on the inventory has an implemented synchroniser',
    'Intent accepted by synthesis, verification and physical design',
  ],
  dependsOn:['ARCH-05','RTL-01','PDK-03'],
  dependsNote:null,
  feedsInto:['RTL-04','RTL-06','DV-06','SYN-06','PD-03'],
  measuredBy:[
    'UPF elaboration errors at first synthesis run',
    'Crossings implemented against the inventory',
    'Intent revisions after RTL freeze',
  ],
},

'RTL-06': {
  stage:'rtl', window:[12,28], criticalPath:true,
  purpose:[
    'Drive <b>lint, clock domain crossing and reset domain crossing to closure</b>—every violation either fixed or waived with a reason someone signed.',
    'These checks find the class of defect that simulation cannot: a crossing without a synchroniser works in every simulation and fails intermittently in silicon. The discipline is in the waivers—an unexamined waiver list is where the surviving bugs live.',
  ],
  steps:[
    {n:1, text:'Lint, CDC and RDC methodology and rule set definition', tat:1.5, lane:'main'},
    {n:2, text:'Block-level lint closure', tat:3.5, lane:'main'},
    {n:3, text:'Block-level CDC closure', tat:3.5, lane:'par'},
    {n:4, text:'Chip-level CDC closure against the crossing inventory', tat:4, lane:'main'},
    {n:5, text:'RDC closure and reset domain analysis', tat:3, lane:'par'},
    {n:6, text:'Waiver review and disposition', tat:3, lane:'main'},
    {n:7, text:'Closure reporting and regression setup', tat:4, lane:'main'},
  ],
  flowNote:'Step 4 is chip-level rather than block-level because most real crossings are between blocks. Block-level CDC finds the easy ones; the crossing that fails in silicon is usually one neither block owner considered theirs.',
  consumes:[
    'Block and top RTL from RTL-02 and RTL-04',
    'Crossing inventory from ARCH-05',
    'Synchroniser implementation from RTL-05',
    'Lint and CDC tool setup from PDK-08',
    'Waiver policy from the methodology',
  ],
  produces:[
    'Lint, CDC and RDC rule sets',
    'Block-level lint closure record',
    'Block-level CDC closure record',
    'Block and chip-level closure results',
    'Crossing inventory reconciliation',
    'RDC closure and reset domain analysis',
    'Waiver list with dispositions and signatures',
    'Closure regression in the CI flow',
  ],
  producedBy:[1,2,3,4,4,5,6,7],
  rel:[
    {id:'RTL-D4', rel:'produces', text:'<b>Lint / CDC / RDC clean reports with waiver list.</b> This activity is the deliverable, and the waiver list is the part that needs review rather than filing.'},
    {id:'RTL-D7', rel:'gates', text:'<b>RTL Freeze package.</b> Freeze with open CDC violations is freezing a class of defect that will not appear until silicon.'},
  ],
  risks:[
    '<b>Waivers accumulated rather than reviewed.</b> A waiver list nobody re-reads is where the surviving crossings hide, and they are the hardest silicon bugs to diagnose.',
    '<b>CDC run only at block level.</b> The crossings that matter are usually between blocks, and neither owner runs the check that would find them.',
    '<b>Closure not regressed.</b> Clean at one release and dirty at the next, with nobody noticing until the freeze package is assembled.',
    '<b>Rule set weakened to reduce noise.</b> Turning off the rule that produces the most violations is the fastest way to a clean report and the slowest way to a working chip.',
    '<b>Crossing inventory not reconciled.</b> Crossings found by the tool but absent from <code>ARCH-05</code>\'s inventory mean the architecture and the implementation disagree.',
  ],
  roles:[
    {r:'RTL quality lead', d:'Owns lint, CDC and RDC closure'},
    {r:'CDC specialist', d:'Chip-level analysis and waiver review'},
    {r:'Block owners', d:'Block-level closure of their own violations'},
    {r:'Clock and reset owner', d:'Inventory reconciliation'},
    {r:'CAD engineer', d:'Tool setup and regression integration'},
  ],
  effort:[['Chip-level CDC closure',8], ['Block-level lint closure',6], ['Block-level CDC closure',6], ['RDC closure',4], ['Waiver review',3], ['Reporting and regression',3]],
  entry:[
    'Blocks stable enough to lint meaningfully',
    'Synchronisers implemented in RTL-05',
    'Tools set up and qualified by PDK-08',
  ],
  exit:[
    'Every violation fixed or waived with a signed reason',
    'Chip-level CDC clean, not only block-level',
    'Closure regressed in CI so it stays clean',
  ],
  dependsOn:['RTL-02','RTL-04','RTL-05','PDK-08'],
  dependsNote:null,
  feedsInto:['RTL-10','SYN-01','DV-11','SO-09'],
  measuredBy:[
    'Waivers reviewed against waivers granted',
    'Crossings found at chip level that block level missed',
    'Closure regression failures after first clean',
  ],
},

'RTL-07': {
  stage:'rtl', window:[4,12], criticalPath:false,
  purpose:[
    'Define the <b>register map—the software contract</b>—and generate the RTL, headers and documentation from one source so they cannot disagree.',
    'The register map is where hardware and firmware meet, and it is the interface most often maintained in three places. Generating the RTL, the C headers and the documentation from a single description is what makes them consistent; hand-maintaining them is what produces a driver that writes to the wrong offset.',
  ],
  steps:[
    {n:1, text:'Register description language and tooling selection', tat:1, lane:'main'},
    {n:2, text:'Address map allocation across blocks', tat:1.5, lane:'main'},
    {n:3, text:'Per-block register definition', tat:2.5, lane:'main'},
    {n:4, text:'Access policy, reset value and side-effect specification', tat:1.5, lane:'par'},
    {n:5, text:'Generation flow — RTL, headers, documentation, UVM model', tat:2, lane:'par'},
    {n:6, text:'Software review of the map', tat:1.5, lane:'par'},
    {n:7, text:'Map release and change control', tat:3, lane:'main'},
  ],
  flowNote:'Step 6 is a review by the people who will use the map rather than the people who wrote it. A register set that is natural to the hardware and awkward to drive is a set the driver will work around, and the workaround becomes the real interface.',
  consumes:[
    'Block specifications from RTL-01',
    'Address map intent from ARCH-09',
    'Software and firmware requirements',
    'Security and lifecycle access rules from ARCH-07',
    'Verification model requirements from DV-01',
  ],
  produces:[
    'Register description source',
    'Address map allocation',
    'Per-block register definitions',
    'Access policy and side-effect specification',
    'Generated RTL, headers, documentation and UVM model',
    'Software review record',
    'Released register map with change control',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'RTL-D2', rel:'produces', text:'<b>Register map / RDL and generated headers.</b> This activity is the deliverable, generated from one source rather than maintained in several.'},
    {id:'RTL-D1', rel:'feeds', text:'<b>Block and top-level RTL release.</b> Generated register RTL is part of every block, so the map\'s release cadence is tied to the RTL\'s.'},
  ],
  risks:[
    '<b>Map maintained in more than one place.</b> RTL, headers and documentation drift apart, and the driver eventually writes to an offset that moved.',
    '<b>Software reviews the map after freeze.</b> An awkward interface then gets worked around in the driver, and the workaround becomes the contract nobody documented.',
    '<b>Side effects undocumented.</b> A read that clears a status bit is a behavior firmware has to know about, and discovering it in the lab costs days per instance.',
    '<b>Security access rules omitted.</b> Registers that should be locked in production lifecycle states are locked late or not at all.',
    '<b>Reset values unspecified.</b> Registers whose reset value is whatever the implementer chose produce a boot sequence that depends on undocumented behavior.',
  ],
  roles:[
    {r:'Register map owner', d:'Owns the description source and the generation flow'},
    {r:'Block owners', d:'Define their block\'s registers and side effects'},
    {r:'Firmware lead', d:'Reviews the map from the driver\'s perspective'},
    {r:'Security architect', d:'Access rules per lifecycle state'},
    {r:'Verification liaison', d:'UVM register model requirements'},
  ],
  effort:[['Per-block register definition',3.5], ['Generation flow',2], ['Address map allocation',1.5], ['Access policy and side effects',1.5], ['Release and change control',1.5]],
  entry:[
    'Block specifications available from RTL-01',
    'Address map intent from the architecture specification',
    'RDL tooling selected and available',
  ],
  exit:[
    'RTL, headers and documentation generated from one source',
    'Map reviewed by firmware before it is frozen',
    'Side effects and reset values specified for every register',
  ],
  dependsOn:['RTL-01','ARCH-07','ARCH-09'],
  dependsNote:null,
  feedsInto:['RTL-02','RTL-04','DV-03','BU-04'],
  measuredBy:[
    'Artifacts generated against artifacts hand-maintained',
    'Register changes after software review',
    'Side effects documented against those found in bring-up',
  ],
},

'RTL-08': {
  stage:'rtl', window:[10,22], criticalPath:false,
  purpose:[
    'Run <b>trial synthesis continuously against the evolving RTL</b> and feed timing, area and power back to block owners while the code can still change cheaply.',
    'RTL that has never been synthesized is RTL whose PPA is unknown. A block that misses its area budget by 30% is a redesign if found at <code>SYN-02</code> and an afternoon if found here, and the difference is only whether anyone was running synthesis during implementation.',
  ],
  steps:[
    {n:1, text:'Trial synthesis flow and constraint bootstrap', tat:1.5, lane:'main'},
    {n:2, text:'Per-block trial synthesis and QoR baseline', tat:3, lane:'main'},
    {n:3, text:'Timing feedback to block owners', tat:2.5, lane:'par'},
    {n:4, text:'Area and budget tracking against ARCH-06', tat:2, lane:'main'},
    {n:5, text:'Power and clock gating effectiveness feedback', tat:2, lane:'par'},
    {n:6, text:'Congestion and routability early indication', tat:2, lane:'par'},
    {n:7, text:'Recurring trial synthesis cadence and reporting', tat:5.5, lane:'main'},
  ],
  flowNote:'Step 7 is the activity\'s real shape—a weekly cadence rather than a one-off study. A single trial synthesis is a snapshot; a weekly one is a feedback loop, and only the loop changes how blocks are written.',
  consumes:[
    'Block RTL from RTL-02',
    'Constraints bootstrap from SYN-01',
    'Library and PDK from PDK-13',
    'PPA budgets from ARCH-06',
    'Floorplan intent from ARCH-08',
  ],
  produces:[
    'Trial synthesis flow and constraints',
    'Per-block QoR baselines',
    'Timing feedback to block owners',
    'Budget tracking against ARCH-06',
    'Timing, area and power feedback reports',
    'Congestion and routability indications',
    'Trial synthesis cadence and reporting record',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'RTL-D1', rel:'feeds', text:'<b>Block and top-level RTL release.</b> A block released without a trial synthesis result has an unknown PPA, and the release quality reflects that.'},
    {id:'RTL-D7', rel:'feeds', text:'<b>RTL Freeze package.</b> The package states where each block sits against its budget, and this activity is where that number comes from.'},
  ],
  risks:[
    '<b>Trial synthesis run once.</b> A snapshot tells a block owner where they were; only a cadence tells them whether they are improving.',
    '<b>Feedback delivered without constraints.</b> Timing results against bootstrap constraints that do not resemble the real ones send block owners chasing paths that do not matter.',
    '<b>Area overrun tolerated because it is early.</b> Blocks rarely shrink after implementation, and an overrun accepted at trial synthesis is an overrun accepted permanently.',
    '<b>Congestion ignored.</b> Routability problems are cheaper to fix in RTL structure than in placement, and the early indication is the only chance to do so.',
    '<b>Results not tied to the budget.</b> QoR reported in absolute terms rather than against <code>ARCH-06</code> tells nobody whether the block is acceptable.',
  ],
  roles:[
    {r:'Synthesis engineer', d:'Owns the trial flow and the reporting cadence'},
    {r:'Block owners', d:'Act on the feedback in their RTL'},
    {r:'PPA lead', d:'Budget tracking and escalation on overruns'},
    {r:'Physical design liaison', d:'Congestion and routability interpretation'},
    {r:'RTL lead', d:'Enforces that feedback is acted on'},
  ],
  effort:[['Recurring trial synthesis and reporting',7], ['Per-block synthesis and baselines',4.5], ['Timing feedback',3], ['Area and budget tracking',2.5], ['Power feedback',1.5], ['Congestion indication',1.5]],
  entry:[
    'Blocks synthesisable, even if incomplete',
    'Constraint bootstrap available from SYN-01',
    'Library and environment available from PDK-13',
  ],
  exit:[
    'Every block has a current QoR result against its budget',
    'Feedback delivered on a cadence, not on request',
    'Overruns escalated rather than noted',
  ],
  dependsOn:['RTL-02','ARCH-06','PDK-13'],
  dependsNote:null,
  feedsInto:['RTL-02','SYN-02','SYN-07','PD-01'],
  measuredBy:[
    'Blocks with a current QoR result',
    'Area against budget at RTL freeze',
    'Weeks between a block change and its next QoR number',
  ],
},

'RTL-09': {
  stage:'rtl', window:[2,32], criticalPath:false,
  purpose:[
    'Run the <b>build, regression and release machinery</b> the whole stage depends on—continuous integration, nightly regressions, tagged releases and a reproducible environment.',
    'This is infrastructure, and its value shows only in its absence. Without a nightly build, a break introduced on Tuesday is found on Friday by whoever needed the design; without release tagging, a bug cannot be reproduced against the version that had it.',
  ],
  steps:[
    {n:1, text:'Build system and dependency management setup', tat:2.5, lane:'main'},
    {n:2, text:'Continuous integration and per-commit checking', tat:3, lane:'main'},
    {n:3, text:'Nightly regression definition and scheduling', tat:2.5, lane:'par'},
    {n:4, text:'Release tagging and version manifest process', tat:2, lane:'main'},
    {n:5, text:'Compute and license capacity management for regressions', tat:2, lane:'par'},
    {n:6, text:'Failure triage and notification workflow', tat:2.5, lane:'par'},
    {n:7, text:'Continuous operation and maintenance across the stage', tat:22.5, lane:'main'},
  ],
  flowNote:'Twenty-two of the thirty weeks are step 7, which is maintenance rather than construction. A CI system that is not maintained degrades into one everyone ignores, and an ignored red build is worse than no build at all.',
  consumes:[
    'RTL source from RTL-02, RTL-03 and RTL-04',
    'Verification regressions from DV-10',
    'Compute and license capacity from PDK-12',
    'Tool versions from PDK-08',
    'Configuration management policy',
  ],
  produces:[
    'Build system and dependency management',
    'Continuous integration with per-commit checks',
    'Nightly regression suite and schedule',
    'Release tagging and version manifests',
    'Compute and license capacity management record',
    'Failure triage and notification workflow',
    'Regression operation and maintenance log',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'RTL-D3', rel:'produces', text:'<b>Integration testbench and build system.</b> This activity is the deliverable, and its measure is that every release is reproducible from a tag.'},
    {id:'RTL-D1', rel:'feeds', text:'<b>Block and top-level RTL release.</b> Releases are produced and tagged by this machinery; without it a release is a directory copy.'},
  ],
  risks:[
    '<b>Red builds tolerated.</b> Once a broken build is normal, the signal is gone and every subsequent break is invisible.',
    '<b>Regression runtime exceeding the night.</b> A nightly that takes thirty hours is not nightly, and the feedback loop silently doubles.',
    '<b>Releases produced by hand.</b> An untagged release cannot be reproduced, and an IP bug found against it cannot be reported precisely.',
    '<b>Capacity not managed.</b> Regressions competing with verification for the same licences slow both, usually at the point in the schedule where both matter most.',
    '<b>Triage unowned.</b> Failures nobody is assigned to investigate accumulate until the regression result is meaningless.',
  ],
  roles:[
    {r:'Configuration and release manager', d:'Owns builds, tags and manifests'},
    {r:'CI engineer', d:'Continuous integration and regression infrastructure'},
    {r:'Verification liaison', d:'Regression content and runtime'},
    {r:'CAD infrastructure', d:'Compute and license capacity'},
    {r:'RTL lead', d:'Enforces build discipline'},
  ],
  effort:[['Continuous operation and maintenance',8], ['CI and per-commit checking',4], ['Build system setup',3], ['Nightly regression setup',2], ['Triage workflow',1.5], ['Release tagging process',1.5]],
  entry:[
    'Repository and branching model agreed',
    'Tool versions available from PDK-08',
    'Compute capacity allocated by PDK-12',
  ],
  exit:[
    'Every release reproducible from a tag',
    'Nightly regression completing within the night',
    'Failures triaged within a working day, with an owner',
  ],
  dependsOn:['PDK-08','PDK-12'],
  dependsNote:null,
  feedsInto:['RTL-02','RTL-04','DV-10','SYN-01'],
  measuredBy:[
    'Days the build stays red',
    'Nightly regression runtime',
    'Releases reproducible from their tag',
  ],
},

'RTL-10': {
  stage:'rtl', window:[2,32], criticalPath:true,
  purpose:[
    'Control what changes and when—<b>specification change requests, ECO board decisions and the freeze itself</b>—so the design converges rather than oscillates.',
    'Every stage downstream assumes RTL stops moving at some point. Change control is how that point is created: not by refusing changes, but by making each one visible, costed and decided by people who can see what it affects. The freeze is this activity\'s output, and its credibility is the whole program\'s.',
  ],
  steps:[
    {n:1, text:'Change control process and ECO board definition', tat:1.5, lane:'main'},
    {n:2, text:'Change request intake and impact assessment workflow', tat:2, lane:'main'},
    {n:3, text:'ECO board operation and decision records', tat:20, lane:'main'},
    {n:4, text:'Change tracking against blocks, verification and synthesis', tat:3, lane:'par'},
    {n:5, text:'Freeze criteria definition and readiness tracking', tat:2.5, lane:'par'},
    {n:6, text:'RTL Freeze package assembly', tat:3, lane:'main'},
    {n:7, text:'Freeze declaration and post-freeze exception policy', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 3 runs for twenty weeks and is a standing meeting rather than a task. Its discipline is impact assessment: a change that looks like an afternoon in one block can invalidate a month of verification, and the board exists so that cost is visible before the change is approved.',
  consumes:[
    'Change requests from every source — architecture, verification, synthesis, IP',
    'Verification status from DV-12',
    'Trial synthesis and PPA status from RTL-08',
    'Lint and CDC closure status from RTL-06',
    'Freeze criteria from the program plan',
  ],
  produces:[
    'Change control process and ECO board charter',
    'Change request log with impact assessments',
    'ECO board decision records',
    'Change tracking record across blocks, verification and synthesis',
    'Freeze criteria and readiness tracking',
    'RTL Freeze package and declaration',
    'Freeze declaration with its exception policy',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'RTL-D7', rel:'produces', text:'<b>RTL Freeze package.</b> This activity is the deliverable—the freeze, its criteria, its exceptions and the change history behind it.'},
    {id:'RTL-D1', rel:'gates', text:'<b>Block and top-level RTL release.</b> After freeze, a release is only produced through an approved exception.'},
  ],
  risks:[
    '<b>Freeze declared by date rather than by criteria.</b> A gate that passes because it was scheduled teaches everyone that gates mean nothing.',
    '<b>Impact assessment skipped for small changes.</b> The cost of a change is rarely in the block that changes; it is in the verification that has to be re-run.',
    '<b>Post-freeze exceptions ungoverned.</b> Changes will be needed after freeze; without a policy they happen informally and nobody knows what the design contains.',
    '<b>Board without downstream representation.</b> Verification and synthesis are the ones who pay for most changes, and a board without them approves costs it cannot see.',
    '<b>Change log not reconciled with the release.</b> A freeze package that does not match what was actually built is a package nobody can rely on.',
  ],
  roles:[
    {r:'Program manager', d:'Chairs the ECO board and owns the freeze'},
    {r:'RTL lead', d:'Impact assessment on the design side'},
    {r:'Verification lead', d:'Impact assessment on verification cost'},
    {r:'Synthesis and PD representatives', d:'Downstream cost of each change'},
    {r:'Configuration manager', d:'Change log reconciliation with releases'},
  ],
  effort:[['ECO board operation',5], ['Impact assessment workflow',2.5], ['Freeze package assembly',1.5], ['Change tracking',1.5], ['Process definition',1], ['Freeze declaration and policy',0.5]],
  entry:[
    'Process agreed and board membership named',
    'Change intake path published to every team',
    'Freeze criteria defined in the program plan',
  ],
  exit:[
    'Freeze declared against criteria, not against a date',
    'Every change carries an impact assessment before approval',
    'Post-freeze exception policy published and used',
  ],
  dependsOn:['RTL-06','RTL-08','DEF-08'],
  dependsNote:null,
  feedsInto:['SYN-09','DV-12','PD-14','TO-03'],
  measuredBy:[
    'Changes with an impact assessment before approval',
    'Freeze criteria met at declaration',
    'Post-freeze exceptions against the policy',
  ],
},

};
