/* SIPI — Chip-Package-System Co-Verification. Eleven activities. Stage w50–76 (26w), 85 M/M.
   Closes before signoff completes at w78 and the FEOL mask release at w80. */
module.exports = {

'SIPI-01': {
  stage:'chipPackageCoVerification', window:[0,7], criticalPath:true,
  purpose:[
    'Get a <b>chip power model</b> that represents the die\'s current demand honestly—per domain, per mode, under the switching the product actually produces.',
    'Everything in this stage depends on this model. A CPM extracted under averaged activity understates the transient the package must supply, and every downstream conclusion inherits that error without any indication that it did.',
  ],
  steps:[
    {n:1, text:'Model requirement definition with physical design', tat:1, lane:'main'},
    {n:2, text:'Switching scenario selection from real workloads', tat:1.5, lane:'main'},
    {n:3, text:'Domain and mode decomposition', tat:1.5, lane:'par'},
    {n:4, text:'CPM extraction and assembly', tat:2, lane:'main'},
    {n:5, text:'Model validation against die-level IR analysis', tat:1.5, lane:'par'},
    {n:6, text:'Model release and version control', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 2 decides everything the stage can conclude. The worst realistic transient—a workload burst arriving after an idle period—is what the package has to absorb, and a model built on steady-state activity cannot represent it.',
  consumes:[
    'Placed and routed database from PD-05 and PD-06',
    'Chip power model extraction from PD-11',
    'Switching activity from DV-04 and SYN-06',
    'Power domain definition from ARCH-05',
    'Model format requirements from the analysis tools',
  ],
  produces:[
    'Model requirements and format definition',
    'Switching scenario selection',
    'Domain and mode decomposition',
    'Assembled chip power model',
    'Validation against die-level IR',
    'Extracted chip power model',
    'Versioned model release',
  ],
  producedBy:[1,2,3,4,5,6,6],
  rel:[
    {id:'SIPI-D1', rel:'produces', text:'<b>Chip power model (CPM/CPS) release per domain and mode.</b> This activity is the deliverable, and everything else in the stage consumes it.'},
    {id:'SIPI-D3', rel:'feeds', text:'<b>PDN impedance and dynamic IR co-simulation report.</b> The model is the die-side input to every co-simulation.'},
  ],
  risks:[
    '<b>Model built on averaged activity.</b> The transient is what the package must supply, and averaging removes exactly the event of interest.',
    '<b>Single model for all modes.</b> DVFS points and workloads draw very differently, and one model represents none of them well.',
    '<b>Not validated against die-level IR.</b> A CPM that disagrees with the die\'s own analysis is wrong somewhere, and nobody knows where.',
    '<b>Delivered late.</b> The stage cannot start without it, and the stage gates mask release.',
    '<b>Version drift.</b> Analysis run against a stale model produces conclusions about a die that has since changed.',
  ],
  roles:[
    {r:'Power modeling engineer', d:'Owns extraction and validation'},
    {r:'Physical design liaison', d:'Database and die-level IR correlation'},
    {r:'Verification liaison', d:'Realistic switching scenarios'},
    {r:'SI/PI lead', d:'Model requirements for co-analysis'},
    {r:'Configuration manager', d:'Model versioning'},
  ],
  effort:[['CPM extraction',2.5], ['Model validation',1.5], ['Scenario selection',1.5], ['Requirement definition',1.5], ['Release and version control',1]],
  entry:[
    'Placed database available from PD-05',
    'Switching activity available from DV-04',
    'Model format requirements agreed',
  ],
  exit:[
    'Model built on the worst realistic transient, not an average',
    'Separate models per domain and mode',
    'Validated against die-level IR before release',
  ],
  dependsOn:['PD-05','PD-11','DV-04','ARCH-05'],
  dependsNote:null,
  feedsInto:['SIPI-03','SIPI-04','SIPI-09','PD-11'],
  measuredBy:[
    'Modes modelled against modes the product uses',
    'Validation agreement against die-level IR',
    'Model delivery against the stage start',
  ],
},

'SIPI-02': {
  stage:'chipPackageCoVerification', window:[2,10], criticalPath:true,
  purpose:[
    'Extract <b>electrical models of the package and the board</b>—3D field solution, S-parameters, RLC networks—so the system can be analyzed as one circuit rather than three assumptions.',
    'Each of the three parties has been designing against a model of the other two. Extraction replaces those assumptions with a solved answer: what the interposer, substrate and board actually do electrically, at the frequencies the design cares about.',
  ],
  steps:[
    {n:1, text:'Extraction scope and frequency range definition', tat:1.5, lane:'main'},
    {n:2, text:'Interposer model extraction', tat:2, lane:'main'},
    {n:3, text:'Substrate model extraction', tat:2, lane:'par'},
    {n:4, text:'Board and socket model extraction', tat:1.5, lane:'par'},
    {n:5, text:'PDN network model assembly', tat:2, lane:'main'},
    {n:6, text:'Model validation and correlation', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 1\'s frequency range decides the extraction cost and its usefulness. PDN analysis needs DC to the switching harmonics; channel analysis needs far higher. Extracting once for both is efficient and extracting for the wrong range wastes the effort entirely.',
  consumes:[
    'Interposer database from PKGD-03',
    'Substrate database from PKGD-04',
    'Board design from EVB-03',
    'Bump and ball assignment from PKGD-02 and PD-04',
    '3D field solver capability',
  ],
  produces:[
    'Extraction scope and frequency definition',
    'Interposer electrical model',
    'Substrate electrical model',
    'Board and socket models',
    'Assembled PDN network model',
    'Model validation results',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SIPI-D2', rel:'produces', text:'<b>Extracted package and board electrical models.</b> This activity is the deliverable, and it is what turns three design intents into one analysable circuit.'},
    {id:'SIPI-D5', rel:'feeds', text:'<b>Channel compliance report per interface.</b> Channel simulation runs on these models rather than on idealized transmission lines.'},
  ],
  risks:[
    '<b>Frequency range too narrow.</b> A model extracted for PDN analysis cannot support channel simulation, and re-extraction is expensive.',
    '<b>Extraction on an unfinished design.</b> Package routing changes invalidate the model, and re-extraction is measured in weeks.',
    '<b>Board model omitted.</b> The board is part of the PDN and part of the channel, and excluding it makes the analysis die-and-package only.',
    '<b>Models not validated.</b> A 3D extraction has convergence and meshing choices, and an unvalidated result can be confidently wrong.',
    '<b>Socket and connector effects ignored.</b> The bring-up platform includes them, and channel margin measured at bring-up will reflect them.',
  ],
  roles:[
    {r:'SI/PI extraction engineer', d:'Owns extraction and model validation'},
    {r:'Package designer', d:'Interposer and substrate geometry'},
    {r:'Board designer', d:'Board, socket and connector models'},
    {r:'SI lead', d:'Frequency range and scope definition'},
    {r:'CAD infrastructure', d:'Field solver capacity'},
  ],
  effort:[['Interposer extraction',2.5], ['Substrate extraction',2], ['PDN network assembly',2], ['Model validation',1.5], ['Board and socket models',1], ['Scope definition',1]],
  entry:[
    'Interposer and substrate designs stable from PKGD-03 and PKGD-04',
    'Board design available from EVB-03',
    'Field solver capacity available',
  ],
  exit:[
    'Frequency range covers both PDN and channel needs',
    'Board and socket included, not only die and package',
    'Models validated rather than assumed correct',
  ],
  dependsOn:['PKGD-02','PKGD-03','PKGD-04','PD-04','EVB-03'],
  dependsNote:null,
  feedsInto:['SIPI-03','SIPI-04','SIPI-06','SIPI-07'],
  measuredBy:[
    'Frequency coverage against analysis needs',
    'Model validation error',
    'Re-extractions required after design change',
  ],
},

'SIPI-03': {
  stage:'chipPackageCoVerification', window:[8,17], criticalPath:true,
  purpose:[
    'Simulate the <b>die, package and board as one power delivery network</b> and check its impedance against target across the frequency range that matters.',
    'The three levels each cover a different band: on-die decap handles the highest frequencies, package decoupling the middle, board bulk capacitance the lowest. Analyzed separately each looks adequate; analyzed together the gaps between them appear, and those gaps are where the supply actually sags.',
  ],
  steps:[
    {n:1, text:'Impedance target derivation per domain', tat:1.5, lane:'main'},
    {n:2, text:'Combined die-package-board PDN assembly', tat:2, lane:'main'},
    {n:3, text:'DC resistance and static drop analysis', tat:1.5, lane:'par'},
    {n:4, text:'AC impedance analysis across frequency', tat:2.5, lane:'main'},
    {n:5, text:'Anti-resonance identification and analysis', tat:1.5, lane:'par'},
    {n:6, text:'PDN findings and improvement recommendations', tat:3, lane:'main'},
  ],
  flowNote:'Step 5 finds what separate analyses cannot. Anti-resonances form between the package\'s inductance and the die\'s capacitance, at frequencies neither level would identify alone, and they are where impedance peaks far above target.',
  consumes:[
    'Chip power model from SIPI-01',
    'Package and board models from SIPI-02',
    'Die PDN from PD-03',
    'Package PDN design from PKGD-06',
    'Board power design from EVB-05',
  ],
  produces:[
    'Impedance targets per domain',
    'Combined PDN model',
    'DC resistance and static drop results',
    'AC impedance across frequency',
    'Anti-resonance analysis',
    'PDN findings and recommendations',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SIPI-D3', rel:'produces', text:'<b>PDN impedance and dynamic IR co-simulation report.</b> The impedance half of the deliverable; <code>SIPI-04</code> supplies the dynamic IR half.'},
    {id:'SIPI-D4', rel:'feeds', text:'<b>Decap budget and placement specification.</b> The impedance profile is what the decap budget is designed to flatten.'},
  ],
  risks:[
    '<b>Levels analyzed separately.</b> Each looks adequate in isolation and the transitions between them are where the impedance peaks.',
    '<b>Anti-resonances missed.</b> They occur at frequencies no single level would examine and can exceed target by a large factor.',
    '<b>Impedance target derived from a rule of thumb.</b> The target follows from the current step and the allowable ripple, and a generic value is either wasteful or inadequate.',
    '<b>DC analysis only.</b> Static drop is the easy half; the frequency-dependent behavior is where the problems are.',
    '<b>Findings without recommendations.</b> An impedance plot that exceeds target tells the team there is a problem, not which level to fix.',
  ],
  roles:[
    {r:'Power integrity engineer', d:'Owns PDN co-simulation and findings'},
    {r:'Die power delivery engineer', d:'Die-side PDN and on-chip decap'},
    {r:'Package power engineer', d:'Package PDN and decoupling'},
    {r:'Board designer', d:'Board PDN and bulk capacitance'},
    {r:'SI/PI lead', d:'Target derivation and recommendation priority'},
  ],
  effort:[['AC impedance analysis',3], ['Findings and recommendations',2.5], ['PDN assembly',2], ['Anti-resonance analysis',2], ['DC analysis',1.5], ['Target derivation',1]],
  entry:[
    'Chip power model released by SIPI-01',
    'Package and board models extracted in SIPI-02',
    'Die PDN available from PD-03',
  ],
  exit:[
    'Impedance analyzed across the full frequency range as one network',
    'Anti-resonances identified and addressed',
    'Findings carry recommendations naming which level to change',
  ],
  dependsOn:['SIPI-01','SIPI-02','PD-03','PKGD-06'],
  dependsNote:null,
  feedsInto:['SIPI-04','SIPI-05','PKGD-06','SO-06'],
  measuredBy:[
    'Impedance against target across frequency',
    'Anti-resonance peaks identified',
    'Recommendations adopted by the responsible level',
  ],
},

'SIPI-04': {
  stage:'chipPackageCoVerification', window:[12,20], criticalPath:true,
  purpose:[
    'Analyze <b>dynamic voltage droop with the package\'s inductance included</b>, under the switching profiles the product actually produces—the number the die-only analysis is optimistic about.',
    'Die-only dynamic IR excludes the package\'s series inductance, which is the dominant impedance at the frequencies a workload burst excites. The difference between the two numbers is real margin, and it is the reason this stage exists rather than trusting <code>SO-04</code>.',
  ],
  steps:[
    {n:1, text:'Transient scenario selection from the workload profiles', tat:1.5, lane:'main'},
    {n:2, text:'Combined transient simulation with package inductance', tat:2.5, lane:'main'},
    {n:3, text:'Droop magnitude and duration analysis per domain', tat:2, lane:'main'},
    {n:4, text:'Comparison against die-only IR results', tat:1.5, lane:'par'},
    {n:5, text:'Worst-case scenario exploration', tat:1.5, lane:'par'},
    {n:6, text:'Dynamic IR findings and margin assessment', tat:2, lane:'main'},
  ],
  flowNote:'Step 4 is the comparison the program most needs. Where die-only analysis says 4.1% and the co-analysis says 5.0% against a 5% budget, the design has no margin—and the two numbers have to be reconciled before <code>SO-04</code> signs off on the optimistic one.',
  consumes:[
    'Chip power model from SIPI-01',
    'Combined PDN model from SIPI-03',
    'Die-only IR results from PD-03 and SO-04',
    'Workload transient profiles from DV-04',
    'Decap configuration from SIPI-05',
  ],
  produces:[
    'Transient scenario selection',
    'Combined transient simulation results',
    'Droop magnitude and duration per domain',
    'Die-only comparison',
    'Worst-case scenario findings',
    'Dynamic IR margin assessment',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SIPI-D3', rel:'produces', text:'<b>PDN impedance and dynamic IR co-simulation report.</b> The dynamic IR half of the deliverable, and the number signoff should be using.'},
    {id:'SIPI-D7', rel:'feeds', text:'<b>Power-aware STA correlation report.</b> Droop is what gets back-annotated into timing in <code>SIPI-09</code>.'},
  ],
  risks:[
    '<b>Package inductance excluded.</b> It dominates at the frequencies a burst excites, and excluding it produces a comfortable and wrong answer.',
    '<b>Transient scenario too gentle.</b> The worst case is a burst after idle, and a scenario built from steady-state activity never reaches it.',
    '<b>Droop duration ignored.</b> A deep short droop and a shallow long one have different timing consequences, and only the magnitude is usually reported.',
    '<b>Die-only comparison not made.</b> Without it nobody knows whether <code>SO-04</code>\'s number is optimistic, and the two signoffs disagree silently.',
    '<b>Findings arriving after timing signoff.</b> Droop consumes timing margin, and a late finding invalidates closure.',
  ],
  roles:[
    {r:'Power integrity engineer', d:'Owns dynamic analysis and margin assessment'},
    {r:'Die power delivery engineer', d:'Die-only comparison and reconciliation'},
    {r:'Verification liaison', d:'Transient scenarios from real workloads'},
    {r:'Timing engineer', d:'Timing consequence of the droop'},
    {r:'Package power engineer', d:'Package-side mitigation options'},
  ],
  effort:[['Transient simulation',3], ['Droop analysis',2], ['Findings and margin assessment',2], ['Die-only comparison',1.5], ['Scenario selection and exploration',1.5]],
  entry:[
    'Chip power model and PDN model available',
    'Die-only IR results available from PD-03',
    'Workload transients available from DV-04',
  ],
  exit:[
    'Package inductance included in every result',
    'Die-only and co-analysis numbers reconciled',
    'Findings delivered before timing signoff closes',
  ],
  dependsOn:['SIPI-01','SIPI-02','SIPI-03','PD-10'],
  dependsNote:null,
  feedsInto:['SIPI-05','SIPI-09','SO-04','SO-06'],
  measuredBy:[
    'Droop against budget with package inductance',
    'Gap between die-only and co-analysis results',
    'Timing margin consumed by droop',
  ],
},

'SIPI-05': {
  stage:'chipPackageCoVerification', window:[14,21], criticalPath:false,
  purpose:[
    'Allocate the <b>decoupling budget across die, package and board</b>—how much capacitance, of what type, mounted where—so the three levels cover the frequency range between them rather than overlapping.',
    'Decoupling is a system-level allocation that is usually made three times independently. On-die capacitance is expensive in area, package capacitors are limited by mounting positions, and board bulk is cheap and slow. Optimizing them together is what covers the band; optimizing them separately leaves the middle uncovered.',
  ],
  steps:[
    {n:1, text:'Frequency band allocation across the three levels', tat:1.5, lane:'main'},
    {n:2, text:'On-die decap requirement and area cost', tat:1.5, lane:'main'},
    {n:3, text:'Package capacitor selection and mounting position', tat:1.5, lane:'par'},
    {n:4, text:'Board bulk capacitance requirement', tat:1, lane:'par'},
    {n:5, text:'Combined impedance verification with the allocation', tat:1.5, lane:'main'},
    {n:6, text:'Decap specification and handoff to each level', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 2 carries a real cost. On-die decoupling consumes die area that could have been logic, and the trade between area and package capacitors is a system decision rather than a physical design one.',
  consumes:[
    'PDN impedance results from SIPI-03',
    'Dynamic droop results from SIPI-04',
    'On-die decap capability and area cost from PD-03',
    'Package mounting positions from PKGD-06',
    'Board capacitance options from EVB-05',
  ],
  produces:[
    'Frequency band allocation',
    'On-die decap requirement with area cost',
    'Package capacitor selection and placement',
    'Board bulk capacitance requirement',
    'Combined impedance verification',
    'Decap specification per level',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SIPI-D4', rel:'produces', text:'<b>Decap budget and placement specification across die, package and board.</b> This activity is the deliverable, and it is the only place the three levels are allocated together.'},
    {id:'SIPI-D3', rel:'feeds', text:'<b>PDN impedance and dynamic IR co-simulation report.</b> The allocation is verified against the impedance target it was designed to meet.'},
  ],
  risks:[
    '<b>Each level decoupled independently.</b> The bands overlap in places and leave gaps in others, and the gaps are where the impedance peaks.',
    '<b>Package capacitors placed where there is room.</b> Mounting position determines loop inductance, and a capacitor far from the current draw contributes little.',
    '<b>On-die decap area not costed.</b> It is die area, and treating it as free produces a design that traded logic for decoupling without anyone deciding to.',
    '<b>Allocation not verified.</b> A budget that has not been re-simulated against the impedance target is a proposal rather than a solution.',
    '<b>Specification not handed to each level.</b> A system allocation that stays in a report is not implemented by anyone.',
  ],
  roles:[
    {r:'Power integrity engineer', d:'Owns the allocation and verification'},
    {r:'Die power delivery engineer', d:'On-die decap and area cost'},
    {r:'Package power engineer', d:'Capacitor selection and mounting'},
    {r:'Board designer', d:'Bulk capacitance and board placement'},
    {r:'Program manager', d:'Arbitrates the area-versus-cost trade'},
  ],
  effort:[['Decap specification and handoff',1.5], ['Band allocation',1.25], ['On-die requirement',1.25], ['Package capacitor selection',1.25], ['Combined verification',1], ['Board requirement',0.75]],
  entry:[
    'Impedance results available from SIPI-03',
    'Droop results available from SIPI-04',
    'Mounting and area constraints known from each level',
  ],
  exit:[
    'Bands allocated so the three levels cover the range without gaps',
    'Package capacitors placed for loop inductance',
    'Allocation verified against the impedance target before handoff',
  ],
  dependsOn:['SIPI-03','SIPI-04','PKGD-06','PD-03'],
  dependsNote:null,
  feedsInto:['PKGD-06','PD-03','EVB-05','SIPI-11'],
  measuredBy:[
    'Impedance gaps between levels',
    'On-die decap area against the budget',
    'Specification adopted by each level',
  ],
},

'SIPI-06': {
  stage:'chipPackageCoVerification', window:[15,20], criticalPath:false,
  purpose:[
    'Analyze <b>simultaneous switching noise at the IO ring</b>—the supply disturbance many outputs switching together inject into their own reference.',
    'SSN is a local problem with system consequences. When a wide interface switches together, the current through the shared return path moves the reference the receivers are measuring against, and the resulting noise appears as jitter and reduced eye margin on the very interface that caused it.',
  ],
  steps:[
    {n:1, text:'SSN analysis scope — which interfaces switch together', tat:1, lane:'main'},
    {n:2, text:'IO ring power and ground network modeling', tat:1.5, lane:'main'},
    {n:3, text:'Simultaneous switching simulation per interface', tat:1.5, lane:'par'},
    {n:4, text:'Ground bounce and reference shift analysis', tat:1.5, lane:'main'},
    {n:5, text:'Mitigation assessment — bump assignment, decoupling', tat:1, lane:'par'},
    {n:6, text:'SSN findings and interface impact', tat:1, lane:'main'},
  ],
  flowNote:'Step 5 usually points back at the bump map. The most effective SSN mitigation is more or better-placed power and ground bumps for that interface, which is a <code>PKGD-02</code> decision—and one that has to be made before the map freezes.',
  consumes:[
    'Package and board models from SIPI-02',
    'IO library characteristics from PDK-07',
    'Bump and ball assignment from PKGD-02',
    'Interface switching patterns from ARCH-04',
    'On-die IO power distribution from PD-03',
  ],
  produces:[
    'SSN analysis scope',
    'IO ring power and ground models',
    'Simultaneous switching simulation results',
    'Ground bounce and reference shift analysis',
    'Mitigation assessment',
    'SSN findings per interface',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SIPI-D5', rel:'feeds', text:'<b>Channel compliance report per interface.</b> SSN degrades the eye of the interface that causes it, so it belongs in the same compliance assessment.'},
    {id:'SIPI-D3', rel:'feeds', text:'<b>PDN impedance and dynamic IR co-simulation report.</b> SSN is a local PDN problem and is reported alongside the global one.'},
  ],
  risks:[
    '<b>SSN analyzed per pin rather than per interface.</b> The problem is simultaneity, and a single-pin analysis cannot see it.',
    '<b>Reference shift not included in the eye budget.</b> Ground bounce moves the receiver\'s threshold, and excluding it overstates the margin.',
    '<b>Mitigation identified after bump map freeze.</b> The most effective remedy is bump assignment, and it is unavailable after <code>PKGD-02</code> closes.',
    '<b>Worst-case switching pattern not simulated.</b> All outputs switching the same direction simultaneously is the worst case and is rarely the default pattern.',
    '<b>IO ring modelled as ideal.</b> The ring\'s own power distribution is what carries the return current, and idealizing it removes the effect being analyzed.',
  ],
  roles:[
    {r:'SI/PI engineer', d:'Owns SSN analysis and findings'},
    {r:'IO library engineer', d:'IO driver characteristics and reference behavior'},
    {r:'Package designer', d:'Bump assignment mitigation'},
    {r:'Die power engineer', d:'IO ring power distribution'},
    {r:'Interface architect', d:'Switching patterns per interface'},
  ],
  effort:[['IO ring modeling',1.25], ['Switching simulation',1], ['Ground bounce analysis',1], ['Mitigation assessment',1], ['Findings',0.75]],
  entry:[
    'Package models available from SIPI-02',
    'IO characteristics available from PDK-07',
    'Bump assignment available from PKGD-02',
  ],
  exit:[
    'Worst-case simultaneous switching simulated per interface',
    'Reference shift included in the interface eye budget',
    'Mitigations identified before the bump map freezes',
  ],
  dependsOn:['SIPI-02','PKGD-02','PDK-07','PD-03'],
  dependsNote:null,
  feedsInto:['SIPI-08','SIPI-11','SO-05'],
  measuredBy:[
    'Ground bounce against the reference budget',
    'Eye margin consumed by SSN',
    'Mitigations available before bump map freeze',
  ],
},

'SIPI-07': {
  stage:'chipPackageCoVerification', window:[8,17], criticalPath:true,
  purpose:[
    'Simulate the <b>high-speed channels end to end with extracted package models</b>—insertion loss, crosstalk, return path, reflections—rather than against the idealized channel the PHY was designed to.',
    'Every PHY closes its margin against an assumed channel. This activity produces the real one: interposer, substrate, board, socket, connectors and all their discontinuities. Where the real channel is worse than assumed, the margin the PHY reported never existed.',
  ],
  steps:[
    {n:1, text:'Channel topology definition per interface', tat:1.5, lane:'main'},
    {n:2, text:'End-to-end channel assembly from extracted models', tat:2, lane:'main'},
    {n:3, text:'Insertion loss and return loss analysis', tat:2, lane:'main'},
    {n:4, text:'Crosstalk analysis — near and far end', tat:2, lane:'par'},
    {n:5, text:'Return path and discontinuity analysis', tat:1.5, lane:'par'},
    {n:6, text:'Channel characterization against the PHY assumption', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 6 is the reconciliation that matters. The PHY in <code>AMS-03</code> closed against a channel budget; this activity says what the channel actually is, and any gap between them is margin the interface does not have.',
  consumes:[
    'Package and board models from SIPI-02',
    'Channel budgets from AMS-03 and ARCH-04',
    'Package SI routing from PKGD-05',
    'Interface specifications and compliance masks',
    'PHY equalization capability from AMS-03',
  ],
  produces:[
    'Channel topology per interface',
    'End-to-end channel models',
    'Insertion and return loss results',
    'Crosstalk analysis results',
    'Return path and discontinuity findings',
    'Channel characterization against PHY assumptions',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SIPI-D5', rel:'produces', text:'<b>Channel compliance report per interface, with margins.</b> This activity is the deliverable, and the margin is stated against the real channel.'},
    {id:'SIPI-D2', rel:'feeds', text:'<b>Extracted package and board electrical models.</b> Channel simulation is the primary consumer of the extraction.'},
  ],
  risks:[
    '<b>Channel simulated on nominal models only.</b> Manufacturing variation moves impedance and loss, and the compliance margin has to survive it.',
    '<b>PHY assumption not reconciled.</b> The PHY closed against a budget; if the real channel is worse, the interface has no margin and nobody has noticed.',
    '<b>Crosstalk analyzed only at the near end.</b> Far-end crosstalk on a long dense channel can dominate, and it behaves differently.',
    '<b>Socket and connector excluded.</b> The bring-up platform includes them, and margin measured at bring-up will reflect them.',
    '<b>Findings after the package design freeze.</b> Channel improvements are routing changes, and they are unavailable after <code>PKGD-11</code>.',
  ],
  roles:[
    {r:'SI engineer', d:'Owns channel simulation and characterization'},
    {r:'PHY designer', d:'Equalization capability and channel assumptions'},
    {r:'Package designer', d:'Routing changes from the findings'},
    {r:'Board designer', d:'Board-side channel contribution'},
    {r:'Interface architect', d:'Compliance requirements per interface'},
  ],
  effort:[['Channel characterization',3], ['Insertion and return loss',2], ['Channel assembly',2], ['Crosstalk analysis',2], ['Return path analysis',1], ['Topology definition',1]],
  entry:[
    'Package and board models extracted in SIPI-02',
    'Channel budgets available from AMS-03',
    'Package SI routing complete in PKGD-05',
  ],
  exit:[
    'Channels simulated end to end including socket and connectors',
    'Real channel reconciled against the PHY\'s assumed budget',
    'Findings delivered before the package design freeze',
  ],
  dependsOn:['SIPI-02','PKGD-05','ARCH-04','AMS-03'],
  dependsNote:null,
  feedsInto:['SIPI-08','PKGD-05','AMS-03','SO-06'],
  measuredBy:[
    'Channel loss against the PHY\'s assumed budget',
    'Crosstalk against the interface allowance',
    'Discontinuities identified and addressed',
  ],
},

'SIPI-08': {
  stage:'chipPackageCoVerification', window:[15,23], criticalPath:true,
  purpose:[
    'Close the <b>eye, jitter and BER budget per interface</b>—combining channel loss, crosstalk, SSN, PHY equalization and jitter into one number that either meets the compliance mask or does not.',
    'This is where all the electrical work resolves into a pass or a fail. Every contribution—the channel from <code>SIPI-07</code>, the noise from <code>SIPI-06</code>, the PLL jitter from <code>AMS-02</code> and the PHY\'s own equalization—lands in a single budget, and the interface either has margin or it is shipping on hope.',
  ],
  steps:[
    {n:1, text:'Budget structure and contribution allocation per interface', tat:1.5, lane:'main'},
    {n:2, text:'Jitter budget assembly — random, deterministic, correlated', tat:2, lane:'main'},
    {n:3, text:'Statistical eye analysis with equalization', tat:2, lane:'par'},
    {n:4, text:'BER estimation and margin against the mask', tat:2, lane:'main'},
    {n:5, text:'Sensitivity to channel and process variation', tat:1.5, lane:'par'},
    {n:6, text:'Budget closure and interface signoff', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 2 is where interfaces are usually lost. Jitter contributions from the PLL, the PHY, the channel and the SSN do not add linearly, and a budget that sums them naively either over-designs or, more often, over-promises.',
  consumes:[
    'Channel characterization from SIPI-07',
    'SSN findings from SIPI-06',
    'PLL jitter from AMS-02',
    'PHY equalization and BER capability from AMS-03',
    'Interface compliance masks',
  ],
  produces:[
    'Budget structure and contribution allocation',
    'Assembled jitter budget',
    'Statistical eye analysis results',
    'BER estimation and mask margin',
    'Variation sensitivity analysis',
    'Assembled jitter budget per interface',
    'Interface budget closure records',
  ],
  producedBy:[1,2,3,4,5,6,6],
  rel:[
    {id:'SIPI-D6', rel:'produces', text:'<b>Eye, jitter and BER budget closure record.</b> This activity is the deliverable—the statement that each interface will work.'},
    {id:'SIPI-D5', rel:'feeds', text:'<b>Channel compliance report per interface.</b> Compliance is a budget conclusion rather than a channel property alone.'},
  ],
  risks:[
    '<b>Jitter contributions summed naively.</b> Random and deterministic components combine differently, and getting it wrong produces a budget that is confidently wrong.',
    '<b>Equalization assumed at its maximum.</b> A PHY closing only with full equalization has no adaptation range left for a worse-than-nominal channel.',
    '<b>Variation sensitivity ignored.</b> The budget has to hold across manufacturing spread, not only at nominal.',
    '<b>SSN excluded from the budget.</b> It is a real contribution and it degrades the interface that generates it.',
    '<b>Interface failing the mask with no route to fix.</b> Late findings leave only channel changes, PHY changes or a rate reduction, and all three are expensive.',
  ],
  roles:[
    {r:'SI engineer', d:'Owns the budget and its closure'},
    {r:'PHY designer', d:'Equalization, jitter and BER capability'},
    {r:'Interface architect', d:'Compliance mask and rate decisions'},
    {r:'Clocking architect', d:'PLL jitter contribution'},
    {r:'SI/PI lead', d:'Signoff on interface closure'},
  ],
  effort:[['Budget closure and signoff',2], ['Jitter budget assembly',2], ['BER estimation',1.75], ['Statistical eye analysis',1.75], ['Variation sensitivity',1], ['Budget structure',0.5]],
  entry:[
    'Channel characterization available from SIPI-07',
    'SSN findings available from SIPI-06',
    'PHY and PLL contributions available from AMS-02 and AMS-03',
  ],
  exit:[
    'Every interface closed against its compliance mask with stated margin',
    'Jitter combined correctly rather than summed',
    'Budget holds across variation, not only at nominal',
  ],
  dependsOn:['SIPI-06','SIPI-07','AMS-02','AMS-03'],
  dependsNote:null,
  feedsInto:['SIPI-11','SO-06','BU-05','MP-11'],
  measuredBy:[
    'Eye margin against the compliance mask',
    'Equalization range remaining at closure',
    'Budget margin under variation',
  ],
},

'SIPI-09': {
  stage:'chipPackageCoVerification', window:[18,23], criticalPath:false,
  purpose:[
    'Back-annotate the <b>voltage droop into static timing analysis</b>—because a design signed off at nominal voltage was signed off at a voltage the die does not see.',
    'Timing and power are analyzed by different teams with different tools, and the connection between them is usually a margin someone assumed. This activity replaces the assumption: the droop map from <code>SIPI-04</code> applied to the timing analysis, so that closure reflects the supply the logic actually has.',
  ],
  steps:[
    {n:1, text:'Droop map generation per region and mode', tat:1, lane:'main'},
    {n:2, text:'Voltage-aware timing analysis setup', tat:1.5, lane:'main'},
    {n:3, text:'Timing re-analysis with back-annotated droop', tat:1.5, lane:'par'},
    {n:4, text:'Margin impact assessment per timing path group', tat:1.5, lane:'main'},
    {n:5, text:'Reconciliation with the SO-02 signoff margin', tat:1.5, lane:'par'},
    {n:6, text:'Power-aware timing findings and recommendations', tat:1, lane:'main'},
  ],
  flowNote:'Step 5 is the reconciliation. If timing signoff already carries a flat voltage margin and this analysis shows the droop is worse in some regions and better in others, the flat margin was both too generous and insufficient—and the recommendation is regional rather than global.',
  consumes:[
    'Dynamic droop results from SIPI-04',
    'Timing analysis from PD-09 and SO-02',
    'Voltage-aware timing tool capability',
    'Region and instance mapping from PD-02',
    'Operating point definitions from ARCH-05',
  ],
  produces:[
    'Droop map per region and mode',
    'Voltage-aware timing setup',
    'Re-analyzed timing with droop',
    'Margin impact per path group',
    'Reconciliation with signoff margin',
    'Power-aware timing recommendations',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SIPI-D7', rel:'produces', text:'<b>Power-aware STA correlation report.</b> This activity is the deliverable, and it connects two signoffs that otherwise run independently.'},
    {id:'SIPI-D3', rel:'feeds', text:'<b>PDN impedance and dynamic IR co-simulation report.</b> The timing consequence is what makes the IR number actionable.'},
  ],
  risks:[
    '<b>Flat voltage margin used instead.</b> Droop is regional, and a flat margin is simultaneously wasteful where droop is low and inadequate where it is high.',
    '<b>Analysis run after timing closure.</b> Findings then require reopening closure, which is expensive at this point in the schedule.',
    '<b>Droop map too coarse.</b> Region granularity determines whether the analysis can distinguish a hot spot from an average.',
    '<b>Reconciliation skipped.</b> Two signoffs with different voltage assumptions produce a design that satisfies neither cleanly.',
    '<b>Recommendations global rather than regional.</b> The remedy is usually local—more decoupling or a PDN change in one region—and a global response over-corrects.',
  ],
  roles:[
    {r:'Power integrity engineer', d:'Droop map generation'},
    {r:'STA engineer', d:'Voltage-aware timing analysis'},
    {r:'Signoff methodology engineer', d:'Reconciliation with signoff margin'},
    {r:'Physical design liaison', d:'Regional remedies'},
    {r:'SI/PI lead', d:'Findings and recommendation priority'},
  ],
  effort:[['Timing re-analysis',1.25], ['Margin impact assessment',1], ['Droop map generation',1], ['Reconciliation',1], ['Findings',0.75]],
  entry:[
    'Droop results available from SIPI-04',
    'Timing analysis available from PD-09',
    'Voltage-aware timing capability available',
  ],
  exit:[
    'Droop applied regionally rather than as a flat margin',
    'Reconciled with the SO-02 signoff assumption',
    'Recommendations targeted at the regions that need them',
  ],
  dependsOn:['SIPI-04','PD-09','SO-02'],
  dependsNote:null,
  feedsInto:['SIPI-11','SO-02','SO-06'],
  measuredBy:[
    'Timing margin change from droop back-annotation',
    'Regional variation in droop impact',
    'Agreement with the signoff voltage assumption',
  ],
},

'SIPI-10': {
  stage:'chipPackageCoVerification', window:[18,23], criticalPath:false,
  purpose:[
    'Couple the <b>electrical and thermal analyses</b>—because leakage rises with temperature, temperature rises with power, and the two feed each other until they settle somewhere the isolated analyses did not predict.',
    'Electro-thermal coupling matters at this power density. A hotspot raises local leakage, which raises local power, which raises the hotspot. Analyzing power at a fixed temperature and temperature at a fixed power finds an equilibrium that is optimistic in exactly the region that matters.',
  ],
  steps:[
    {n:1, text:'Coupling methodology and iteration scheme', tat:1, lane:'main'},
    {n:2, text:'Thermal model integration with the package model', tat:1.5, lane:'main'},
    {n:3, text:'Leakage-temperature feedback modeling', tat:1, lane:'par'},
    {n:4, text:'Coupled electro-thermal iteration to convergence', tat:1.5, lane:'main'},
    {n:5, text:'Hotspot and gradient assessment', tat:1, lane:'par'},
    {n:6, text:'Findings against the isolated analyses', tat:1, lane:'main'},
  ],
  flowNote:'Step 4 iterates to convergence, and whether it converges is itself information. A design where the leakage-temperature loop does not settle is a design with a thermal runaway risk, which is a different and more serious finding than a high temperature.',
  consumes:[
    'Package thermal model from PKGD-07',
    'Thermal characterization from PTV-09',
    'Chip power model from SIPI-01',
    'Leakage characterization from PDK-03',
    'Power map from PD-03',
  ],
  produces:[
    'Coupling methodology and iteration scheme',
    'Integrated electro-thermal model',
    'Leakage-temperature feedback model',
    'Coupled analysis results',
    'Hotspot and gradient assessment',
    'Comparison against isolated analyses',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SIPI-D3', rel:'feeds', text:'<b>PDN impedance and dynamic IR co-simulation report.</b> Temperature affects both resistance and leakage, and the coupled result is the honest one.'},
    {id:'SIPI-D7', rel:'feeds', text:'<b>Power-aware STA correlation report.</b> Temperature affects timing as well as voltage, and both belong in the same correlation.'},
  ],
  risks:[
    '<b>Analyses run at fixed temperature and fixed power.</b> The equilibrium the coupled analysis finds is worse, and it is the one that occurs.',
    '<b>Leakage-temperature model too coarse.</b> The feedback is exponential, and a linear approximation understates the hotspot.',
    '<b>Non-convergence dismissed as a numerical issue.</b> It can indicate a real thermal runaway risk and deserves investigation rather than a damping factor.',
    '<b>Package thermal model unvalidated.</b> If <code>PTV-09</code> has not correlated it, the coupled analysis inherits an unknown error.',
    '<b>Gradient ignored in favor of peak temperature.</b> Gradients drive mechanical stress and timing variation across the die, and the peak alone does not capture them.',
  ],
  roles:[
    {r:'Thermal engineer', d:'Thermal model and coupling'},
    {r:'Power integrity engineer', d:'Electrical side of the coupled analysis'},
    {r:'Device engineer', d:'Leakage-temperature characterization'},
    {r:'Package thermal liaison', d:'Package model and validation status'},
    {r:'SI/PI lead', d:'Findings against the isolated analyses'},
  ],
  effort:[['Coupled iteration',1.25], ['Thermal model integration',1], ['Leakage feedback modeling',1], ['Hotspot assessment',1], ['Findings and comparison',0.75]],
  entry:[
    'Package thermal model available from PKGD-07',
    'Thermal characterization available from PTV-09',
    'Chip power model available from SIPI-01',
  ],
  exit:[
    'Coupled analysis converged, or non-convergence investigated',
    'Compared against the isolated analyses to quantify the difference',
    'Gradients assessed alongside peak temperature',
  ],
  dependsOn:['SIPI-01','PKGD-07','PTV-09','PD-03'],
  dependsNote:null,
  feedsInto:['SIPI-11','SO-06','MP-02'],
  measuredBy:[
    'Temperature difference between coupled and isolated analysis',
    'Convergence of the coupled iteration',
    'Gradient magnitude across the die',
  ],
},

'SIPI-11': {
  stage:'chipPackageCoVerification', window:[22,26], criticalPath:true,
  purpose:[
    'Hold the <b>co-verification signoff</b>—every result reviewed against named exit criteria, dispositioned, and signed—because mask release depends on it.',
    'This is the gate the stage exists to reach. Without a signoff with criteria, co-verification is a collection of analyses that each conclude something and together conclude nothing. The disposition here is what <code>SO-06</code> reviews and what makes the MTO gate at week 78 meaningful.',
  ],
  steps:[
    {n:1, text:'Exit criteria confirmation across all analyses', tat:0.75, lane:'main'},
    {n:2, text:'Result consolidation and margin summary', tat:1, lane:'main'},
    {n:3, text:'Open item disposition with die, package and board owners', tat:1, lane:'par'},
    {n:4, text:'Signoff review with design and package teams', tat:1.25, lane:'main'},
    {n:5, text:'Residual risk statement', tat:0.75, lane:'par'},
    {n:6, text:'Co-verification signoff declaration', tat:1, lane:'main'},
  ],
  flowNote:'Step 3 is a three-party disposition. Every open item belongs to the die, the package or the board, and closing it requires the owner in the room—which is why co-verification signoff is a joint review rather than a report circulated for comment.',
  consumes:[
    'Results from SIPI-03 through SIPI-10',
    'Exit criteria defined at stage start',
    'Package design freeze schedule from PKGD-11',
    'Signoff schedule from SO-06',
    'Program risk register',
  ],
  produces:[
    'Confirmed exit criteria',
    'Consolidated results and margin summary',
    'Open item dispositions with owners',
    'Signoff review record with design and package',
    'Residual risk statement',
    'Signoff review record',
    'Co-verification signoff declaration',
  ],
  producedBy:[1,2,3,4,5,6,6],
  rel:[
    {id:'SIPI-D8', rel:'produces', text:'<b>Chip-package-system co-verification signoff—tapeout gate.</b> This activity is the deliverable, and it carries the stage\'s milestone.'},
    {id:'SIPI-D6', rel:'gates', text:'<b>Eye, jitter and BER budget closure record.</b> An interface that has not closed its budget is an open item at this gate.'},
  ],
  risks:[
    '<b>Signoff without exit criteria.</b> The analyses each conclude something and together conclude nothing that can be signed.',
    '<b>Open items dispositioned without their owners.</b> An item closed by the analysis team rather than by the die, package or board owner has not actually been closed.',
    '<b>Signoff after the package design freeze.</b> Findings then have nowhere to go, and the freeze was taken without them.',
    '<b>Residual risk not stated.</b> Some margin will be thin; saying which and how thin is what lets the tapeout decision be informed.',
    '<b>Declared to meet the date.</b> The gate exists to be able to hold mask release, and one that cannot is not a gate.',
  ],
  roles:[
    {r:'SI/PI lead', d:'Chairs the signoff and owns the declaration'},
    {r:'Die power and timing owners', d:'Die-side dispositions'},
    {r:'Package architect', d:'Package-side dispositions'},
    {r:'Board designer', d:'Board-side dispositions'},
    {r:'Signoff lead', d:'Carries the result into SO-06 and the freeze'},
  ],
  effort:[['Signoff review',1], ['Result consolidation',0.75], ['Open item disposition',0.5], ['Declaration',0.5], ['Residual risk statement',0.25]],
  entry:[
    'Analyses complete from SIPI-03 through SIPI-10',
    'Exit criteria defined and agreed',
    'Die, package and board owners available to disposition',
  ],
  exit:[
    'Every analysis assessed against a named exit criterion',
    'Open items dispositioned by their owners, not by the analysis team',
    'Signoff complete before the package design freeze and the MTO gate',
  ],
  dependsOn:['SIPI-03','SIPI-04','SIPI-05','SIPI-06','SIPI-08','SIPI-09','SIPI-10'],
  dependsNote:null,
  feedsInto:['SO-06','PKGD-11','TO-04','BU-05'],
  measuredBy:[
    'Analyses assessed against exit criteria',
    'Open items closed by their owners',
    'Signoff date against the package freeze and MTO gate',
  ],
},

};
