/* One output for every step that had none. Keyed by activity, then step number. */
module.exports = {
'DEF-01':{1:"Stakeholder map and interview schedule",3:"Market and analyst input with segment sizing",6:"Requirement-to-KPI traceability tags"},
'DEF-02':{1:"Use-case shortlist with deployment weights",2:"Captured workload traces per use case"},
'DEF-03':{5:"PPA sensitivity table per candidate node",7:"Target review record with architecture and physical design"},
'DEF-04':{1:"Die area estimate with its tolerance",3:"Defect density and yield curve per node",4:"Package and substrate cost breakdown",5:"Test cost model with its test-time assumption"},
'DEF-05':{3:"Host interface sizing — generation and lane count"},
'DEF-06':{2:"Collected competitor benchmarks and datasheets",6:"Product and sales review record"},
'DEF-07':{1:"Agreed candidate node shortlist",4:"Cost model results per node"},
'DEF-08':{1:"Selected profile with a dated kickoff",7:"Schedule commitment record"},
'DEF-09':{5:"Executive review pack"},
'ARCH-01':{1:"Model scope and fidelity decision record",2:"Baseline performance model",3:"Workload suite integrated into the model",6:"Interconnect and NoC topology study results",8:"Bottleneck and roofline analysis"},
'ARCH-02':{2:"Reticle limit and die size feasibility finding",5:"Die-to-die interface implication study",7:"Known-good-die and test implication assessment"},
'ARCH-03':{2:"SRAM capacity sizing with reuse-distance evidence",6:"Prefetch and data-movement engine requirement",8:"Memory hierarchy specification chapter"},
'ARCH-04':{1:"Consolidated interface requirement list",2:"Standard revision and ratification status record",3:"Host interface selection with generation and profile",4:"HBM generation selection and controller requirement"},
'ARCH-05':{6:"Power management controller requirement",8:"Review record from physical design and verification"},
'ARCH-06':{2:"Per-block area allocation",3:"Per-block and per-domain power allocation"},
'ARCH-07':{7:"Security architecture note and review record"},
'ARCH-08':{5:"Power delivery bump budget",7:"Published block diagram and bump budget"},
'ARCH-09':{1:"Specification structure with section owners",5:"Internal technical review findings, two rounds",8:"Architecture Freeze gate decision"},
'ARCH-10':{2:"Block owner assignment and kickoff record",3:"Per-block pipeline and datapath definition",7:"First-round microarchitecture review findings"},
'TECH-01':{3:"Foundry information request responses",4:"Previous-program experience review"},
'TECH-02':{3:"Backside power delivery evaluation",6:"Priced option adders"},
'TECH-03':{3:"Ring oscillator and critical-path frequency study",7:"Node comparison against the PPA targets"},
'TECH-04':{1:"Volume and wafer-start forecast",2:"Wafer price quotations per foundry"},
'TECH-06':{5:"Agreed liability, indemnity and yield-responsibility terms",7:"Redline history with resolved positions"},
'TECH-07':{1:"Node maturity and risk-production timing assessment"},
'TECH-09':{6:"Preliminary OSAT capacity indication"},
'PDK-01':{1:"Release calendar and version tracking framework",2:"0.1-to-0.5 delta impact analysis",6:"Production PDK adoption and freeze decision"},
'PDK-02':{4:"Density and spacing rule impact on the floorplan"},
'PDK-03':{5:"Physical view and abstract consistency findings",6:"Re-characterization results where foundry data was thin"},
'PDK-04':{2:"Compiler license and access setup record",6:"Compiler view completeness findings"},
'PDK-05':{1:"Per-block memory budget extract"},
'PDK-06':{1:"Shortfall review against the block budgets",2:"Defined options — pushed rules, custom array, architecture change"},
'PDK-07':{1:"Consolidated IO requirement list"},
'PDK-08':{3:"Synthesis and place-and-route version qualification results",4:"STA and signoff tool qualification results",8:"Published tool matrix"},
'PDK-09':{1:"Ingested foundry reference flow",2:"Gap analysis against internal methodology",3:"Adapted synthesis and place-and-route flow"},
'PDK-10':{6:"Deck version tracking log"},
'PDK-11':{2:"Proposed PVT corner set"},
'PDK-12':{6:"Published capacity plan and review record"},
'PDK-13':{1:"Environment scope definition",4:"Reference block regression results"},
'IPR-01':{1:"Requirement-to-IP decomposition",2:"Block-level IP list",3:"Interface and protocol IP list"},
'IPR-03':{4:"Cost and schedule comparison per line",5:"Foundry-specific versus portable IP assessment"},
'IPR-04':{2:"RFI responses per vendor",5:"Support model and escalation path assessment"},
'IPR-05':{2:"Collected silicon evidence per block",7:"IP readiness report with its gap list"},
'IPR-06':{4:"Documentation, errata and integration guide requirements",7:"Published checklist with procurement handoff"},
'IPR-07':{2:"Agreed licence model per block",4:"Deliverable checklist as a contractual schedule",6:"Agreed liability, indemnity and warranty terms",7:"Redline history with resolved positions"},
'IPR-08':{1:"Unproven block list"},
'IPR-09':{2:"Committed delivery dates per block and deliverable"},
'AMS-01':{3:"Per-block AMS specifications",5:"PSRR and supply sensitivity requirements"},
'AMS-02':{1:"PLL architecture selection record",2:"Loop dynamics and phase noise budget",3:"VCO design with its tuning range",6:"Lock detection, calibration and startup sequencing design",7:"PLL layout with matching and shielding",9:"Clock distribution interface definition"},
'AMS-03':{3:"Equalization and link training architecture",5:"Clock recovery and per-lane timing design",6:"HBM PHY integration and training sequence",7:"SerDes layout with lane pitch closure"},
'AMS-04':{5:"Startup, sequencing and brown-out behavior definition",6:"Regulator layout with supply isolation",7:"Post-layout stability and PSRR results across PVT"},
'AMS-05':{1:"Confirmed custom array scope",6:"Peripheral circuit architecture"},
'AMS-06':{3:"Wordline boost circuit design",5:"VDD collapse and read-assist timing design"},
'AMS-07':{3:"Peripheral and assist circuit layout",6:"DRC closure record with pushed-rule waivers",8:"Frozen layout with extraction handoff"},
'AMS-08':{4:"Sense amplifier offset distribution analysis"},
'AMS-09':{1:"Redundancy scheme selection record",3:"Repair interface definition"},
'AMS-10':{1:"View requirement definition against the tool matrix"},
'AMS-11':{4:"Pre-layout corner simulation results"},
'AMS-12':{5:"Fill and density compliance record",6:"Per-macro DRC closure"},
'AMS-13':{3:"Post-layout PVT corner closure results"},
'AMS-14':{6:"Latch-up and guard structure review findings"},
'AMS-15':{1:"Confirmed view requirement list",7:"Trial placement integration verification results"},
'AMS-16':{5:"Integration support record for RTL and physical design"},
'TC-01':{5:"Shuttle die cost and area budget"},
'TC-02':{1:"IP-under-test integration plan",5:"Assembled test structure library",7:"Pad ring and ESD design for the shuttle"},
'TC-03':{2:"Foundry or broker engagement with pricing"},
'TC-04':{2:"Placed and routed shuttle database",4:"Timing closure results on access and control paths",5:"Fill, seal ring and frame compliance record",7:"LVS closure record"},
'TC-05':{2:"Fabricated shuttle mask set",4:"Processed wafers"},
'TC-06':{4:"Fabricated and assembled test boards"},
'TC-07':{1:"Incoming inspection and functionality results",5:"Corner correlation setup"},
'TC-08':{5:"Production design change requests"},
'RTL-01':{2:"Per-block pipeline and datapath detail",6:"Verification hook and observability requirements"},
'RTL-02':{1:"Coding standard and repository structure",2:"First-pass block RTL",4:"Block RTL review findings",5:"Parameterization and configurability implementation",6:"Fixed and refined block RTL",7:"Block-level PPA refinement record"},
'RTL-03':{2:"Integration environment and wrapper framework",6:"AMS macro integration with behavioural models"},
'RTL-04':{5:"Elaborated top level with connectivity check results",6:"Integrated boot and bring-up path"},
'RTL-05':{1:"Implemented power domain boundaries",7:"Power intent review record"},
'RTL-06':{2:"Block-level lint closure record",3:"Block-level CDC closure record",5:"RDC closure and reset domain analysis"},
'RTL-07':{3:"Per-block register definitions",7:"Released register map with change control"},
'RTL-08':{3:"Timing feedback to block owners",7:"Trial synthesis cadence and reporting record"},
'RTL-09':{5:"Compute and license capacity management record",7:"Regression operation and maintenance log"},
'RTL-10':{4:"Change tracking record across blocks, verification and synthesis",7:"Freeze declaration with its exception policy"},
'DV-02':{7:"Environment bring-up results on the first block"},
'DV-03':{2:"Directed test suite for specified behavior",4:"Bound assertion set",7:"Bug reports and debug log with block owners"},
'DV-04':{6:"System-level error injection and recovery results",7:"Realistic workload scenarios in the testbench"},
'DV-05':{6:"Assumption review and over-constraint findings"},
'DV-06':{6:"Power-aware regression integration"},
'DV-07':{6:"Analog fault and degraded-mode results"},
'DV-08':{6:"Performance and throughput tuning record",8:"Platform handover package to firmware and validation"},
'DV-09':{4:"Latency and queueing analysis"},
'DV-10':{6:"Regression stability and flake elimination record",7:"Published coverage dashboard"},
'DV-11':{1:"Gate-level environment with the netlist brought up",7:"Failure debug and closure record"},
'DV-12':{3:"Triage and disposition log"},
'DFT-03':{6:"Repair interface agreement with the memory designers",8:"Verified MBIST architecture specification"},
'DFT-04':{6:"Access network verification results and description files"},
'DFT-05':{6:"At-speed clocking verification results"},
'DFT-06':{6:"Scan chain integrity verification results"},
'DFT-07':{2:"Stuck-at pattern set with coverage analysis",3:"Transition and at-speed pattern set"},
'DFT-08':{3:"Timing-annotated pattern simulation results"},
'DFT-10':{6:"Lifecycle state encoding agreed with the security architecture"},
'SYN-03':{1:"N0 scope definition — representative versus stubbed"},
'SYN-04':{3:"Macro and blockage aware placement"},
'SYN-05':{1:"RTL drop intake and delta review",2:"Block-level synthesis closure"},
'SYN-06':{5:"Activity-driven optimization results"},
'SYN-08':{1:"RTL and ECO intake record since N1"},
'SYN-09':{1:"RTL freeze confirmation"},
'SYN-10':{2:"Per-drop block-level equivalence results",3:"Black-box and constraint handling record",8:"Equivalence checking log across the drop sequence"},
'SYN-11':{2:"Per-drop timing, area and power report",6:"Reporting log across the stage"},
'SYN-12':{2:"Per-drop handoff package"},
'PD-04':{1:"Ingested bump map",5:"Signal escape plan with the substrate"},
'PD-05':{1:"N1 intake and turn setup",2:"Placed and optimized N1 database",5:"First-round timing analysis and ECOs",6:"First full route"},
'PD-06':{1:"N2 intake and delta assessment",2:"Placement with congestion mitigation",5:"Timing convergence and ECO record",6:"Converged route"},
'PD-07':{1:"Clock architecture implementation plan",6:"Cross-domain and useful skew handling",8:"Clock tree refinement record across turns"},
'PD-08':{2:"Global routing and congestion assessment",8:"Routing record across turns"},
'PD-09':{2:"Setup timing closure results",8:"Closure record across turns"},
'PD-10':{1:"SI setup and crosstalk analysis",2:"Crosstalk fixes — spacing, shielding, sizing"},
'PD-12':{2:"Reordered scan chains"},
'PD-13':{1:"FFN intake and delta assessment",2:"Placement on the final netlist",4:"Final clock tree",9:"Closure report with remaining-violation disposition"},
'PD-16':{2:"Block-level closure results",6:"Assembled top level"},
'SO-02':{2:"Setup timing analysis across corners and modes"},
'SO-03':{2:"Full-chip DRC results with triaged violations"},
'SO-05':{5:"Power integrity signoff reconciliation"},
'SO-10':{1:"Classified waiver intake across signoff domains"},
'TO-01':{3:"Merged macro and hard IP GDS"},
'TO-02':{2:"Full-chip DRC re-run results"},
'TO-08':{5:"Per-fix equivalence and consistency results"},
'FAB-01':{3:"Pellicle and handling preparation record"},
'FAB-03':{4:"BEOL mask inspection and qualification results",5:"BEOL masks released to the line"},
'FAB-04':{1:"Lot release and front-end entry confirmation",2:"Wafers through transistor formation",4:"Wafers through contact and local interconnect"},
'FAB-05':{1:"Back-end entry and mask availability confirmation",2:"Wafers through metallization and via formation",4:"Wafers through top metal and passivation"},
'FAB-06':{4:"Reviewed and classified defect inspection results",6:"Inline monitoring log across the lot"},
'FAB-09':{6:"Yield tracking log across the run"},
'PKGD-01':{2:"Defined package architecture options"},
'PKGD-02':{5:"Die-side placement iteration record"},
'PKGD-03':{6:"Interposer DRC and manufacturability results"},
'PKGD-04':{6:"Package DRC results against supplier rules"},
'PKGD-07':{7:"Thermal and mechanical design recommendations"},
'PTV-01':{1:"Risk intake from package design and previous programs"},
'PTV-05':{1:"Vehicle build plan with quantities"},
'PTV-06':{2:"Bonded vehicles across conditions",3:"Underfilled and cured vehicles",4:"Molded and lidded vehicles"},
'SIPI-01':{4:"Assembled chip power model"},
'SIPI-08':{2:"Assembled jitter budget"},
'SIPI-11':{4:"Signoff review record with design and package"},
'ASSY-01':{1:"Wafers received with sort setup complete"},
'ASSY-02':{1:"Delivered HBM stacks"},
'ASSY-04':{2:"Dispensed and flowed underfill"},
'ASSY-09':{4:"Units built to allocation"},
'EVB-01':{2:"Platform topology options with trade-offs"},
'EVB-04':{2:"Fabricated bare boards"},
'TEST-01':{8:"Reviewed and released test plan"},
'TEST-03':{8:"Probe card released to sort"},
'TEST-04':{2:"Load board design with SI results",4:"Fabricated and assembled load board"},
'TEST-06':{8:"Debugged final test program"},
'TEST-09':{7:"Tester resource cost per unit"},
'BU-05':{1:"Interface bring-up order and plan"},
'MP-01':{6:"Reviewed and released qualification plan"},
'MP-07':{2:"Converted multi-site load board and probe card"},
'MP-12':{5:"Localized and formatted documentation outputs"},
};
