/* SYN — Logic Synthesis & Netlist Drops. Twelve activities. Stage w42–66 (24w), 136 M/M. */
module.exports = {

'SYN-01': {
  stage:'synthesis', window:[0,8], criticalPath:true,
  purpose:[
    'Write the <b>constraints the whole implementation is optimized and signed off against</b>—clocks, generated clocks, IO timing, exceptions, test modes—and validate them rather than assume them.',
    'Constraints are the specification synthesis and physical design actually read. A missing clock definition produces a design optimized for a path nobody cares about; a wrong false path produces one that closes in the tool and fails in silicon. Every hour spent validating them here saves days at <code>PD-09</code>.',
  ],
  steps:[
    {n:1, text:'Mode and corner enumeration against the operating conditions', tat:1.5, lane:'main'},
    {n:2, text:'Clock and generated clock definition across the design', tat:2, lane:'main'},
    {n:3, text:'Exception, false path and multicycle specification', tat:1.5, lane:'par'},
    {n:4, text:'IO and interface timing constraints', tat:2, lane:'main'},
    {n:5, text:'Test mode and scan constraints', tat:1.5, lane:'par'},
    {n:6, text:'Constraint validation and quality checking', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 6 is not review, it is tooling. Constraint quality checkers find unconstrained paths, conflicting exceptions and clocks that reach nothing, and they find them in minutes—which is why every drop should be re-checked rather than checked once.',
  consumes:[
    'Clock architecture and DVFS points from ARCH-05',
    'Interface timing requirements from ARCH-04',
    'Corner and mode definition from PDK-11',
    'DFT test modes from DFT-01',
    'RTL hierarchy from RTL-04',
  ],
  produces:[
    'Mode and corner enumeration',
    'Clock and generated clock definitions',
    'Exception and multicycle specification',
    'IO and interface constraints',
    'Test mode constraints',
    'Constraint validation reports',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SYN-D4', rel:'produces', text:'<b>Validated SDC constraint set per mode and corner.</b> This activity is the deliverable, and "validated" is what distinguishes it from a file of assertions.'},
    {id:'SYN-D5', rel:'feeds', text:'<b>Synthesis QoR report per drop.</b> QoR is only meaningful against constraints; an unconstrained path reports as passing.'},
  ],
  risks:[
    '<b>Unconstrained paths reported as clean.</b> A path with no constraint is a path the tool ignores, and it appears in the report as no violation at all.',
    '<b>Exceptions written to close timing.</b> A false path added because the path would not close is a silicon failure being converted into a green report.',
    '<b>Constraints diverging between synthesis and signoff.</b> Two constraint sets means optimizing against one and being judged against the other.',
    '<b>Test mode constraints written late.</b> Scan shift and at-speed modes have their own timing, and a design closed only in functional mode fails at ATE.',
    '<b>IO constraints assumed from the interface specification.</b> Actual budgets come from the package and channel analysis in <code>SIPI-07</code>, not from the protocol document.',
  ],
  roles:[
    {r:'Constraints lead', d:'Owns the SDC set and its validation'},
    {r:'Timing engineers', d:'Clock definitions and exception specification'},
    {r:'DFT engineer', d:'Test mode constraints'},
    {r:'Physical design liaison', d:'Confirms constraints are implementable'},
    {r:'Signoff methodology engineer', d:'Constraint consistency between synthesis and signoff'},
  ],
  effort:[['Clock and generated clock definitions',5], ['Constraint validation',4.5], ['IO and interface constraints',3.5], ['Exception specification',3], ['Test mode constraints',2]],
  entry:[
    'Clock architecture fixed by ARCH-05',
    'Corner and mode definition available from PDK-11',
    'RTL hierarchy stable enough to constrain',
  ],
  exit:[
    'No unconstrained paths in the design',
    'Every exception justified by a design reason, not by a violation',
    'One constraint set used by both synthesis and signoff',
  ],
  dependsOn:['ARCH-05','PDK-11','DFT-01','RTL-04'],
  dependsNote:null,
  feedsInto:['SYN-02','SYN-03','SYN-11','PD-01','SO-02'],
  measuredBy:[
    'Unconstrained paths at each drop',
    'Exceptions with a documented design reason',
    'Constraint differences between synthesis and signoff',
  ],
},

'SYN-02': {
  stage:'synthesis', window:[2,10], criticalPath:true,
  purpose:[
    'Map the RTL onto the qualified library and <b>optimize it for the PPA budget</b>—Vt mix, multi-bit banking, useful skew, datapath structure.',
    'Technology mapping is where architecture becomes gates and where most of the achievable PPA is decided. The same RTL mapped two ways can differ by 20% in area and a hundred millivolts in achievable frequency, and the difference is entirely in how this activity is configured.',
  ],
  steps:[
    {n:1, text:'Library and mapping strategy selection', tat:1.5, lane:'main'},
    {n:2, text:'Baseline mapping and optimization', tat:2.5, lane:'main'},
    {n:3, text:'Datapath and arithmetic optimization', tat:1.5, lane:'par'},
    {n:4, text:'Multi-bit banking and useful skew configuration', tat:2, lane:'main'},
    {n:5, text:'Area recovery on non-critical paths', tat:1.5, lane:'par'},
    {n:6, text:'QoR analysis and optimization iteration', tat:2, lane:'main'},
  ],
  flowNote:'Step 5 is where area is won without cost. Most of a design is not on the critical path, and recovering area and leakage there is free performance-wise—but it only happens if someone configures the flow to do it rather than optimizing everything for speed.',
  consumes:[
    'Qualified libraries from PDK-03',
    'Constraints from SYN-01',
    'RTL from RTL-02 and RTL-04',
    'PPA budgets from ARCH-06',
    'Flow and methodology from PDK-09',
  ],
  produces:[
    'Mapping strategy and library configuration',
    'Baseline mapped netlist',
    'Datapath optimization results',
    'Multi-bit and useful skew configuration',
    'Area recovery results',
    'QoR analysis per iteration',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SYN-D5', rel:'feeds', text:'<b>Synthesis QoR report per drop.</b> This activity produces the QoR the report describes, drop after drop.'},
    {id:'SYN-D2', rel:'feeds', text:'<b>N1 and N2 netlist drops.</b> Each drop is this activity\'s output at a point in time, with whatever optimization was enabled.'},
  ],
  risks:[
    '<b>Everything optimized for speed.</b> Area and leakage on non-critical paths are given away for performance nobody asked for, and the die grows.',
    '<b>Multi-bit banking configured late.</b> Clock power depends heavily on it, and adding it after closure means re-timing the design.',
    '<b>Useful skew used to hide a timing problem.</b> It buys real margin and also makes the clock tree harder to build; using it to rescue a path that should be restructured moves the problem to <code>PD-07</code>.',
    '<b>Library subset used without knowing it.</b> Synthesis using only part of the Vt menu produces avoidable leakage, and nobody notices because the design closes.',
    '<b>QoR compared drop to drop without normalizing.</b> A netlist with more RTL in it is not directly comparable to the last one, and the trend becomes noise.',
  ],
  roles:[
    {r:'Synthesis lead', d:'Owns mapping strategy and QoR'},
    {r:'Synthesis engineers', d:'Flow configuration and optimization'},
    {r:'Library engineer', d:'Vt menu and special cell usage'},
    {r:'Block owners', d:'RTL restructuring where synthesis cannot close'},
    {r:'PPA lead', d:'QoR against the ARCH-06 budgets'},
  ],
  effort:[['Baseline mapping and optimization',5], ['QoR analysis and iteration',4], ['Multi-bit and useful skew',3], ['Datapath optimization',2], ['Area recovery',2]],
  entry:[
    'Libraries qualified and frozen by PDK-03',
    'Constraints available from SYN-01',
    'Flow available from PDK-09',
  ],
  exit:[
    'Area recovered on non-critical paths, not only speed optimized',
    'Vt menu used across its range, not defaulted',
    'QoR reported normalized so drops are comparable',
  ],
  dependsOn:['SYN-01','PDK-03','PDK-09','RTL-02'],
  dependsNote:null,
  feedsInto:['SYN-04','SYN-05','SYN-06','SYN-11','PD-05'],
  measuredBy:[
    'Area and leakage against the ARCH-06 budget',
    'Clock power against the multi-bit projection',
    'QoR trend across drops',
  ],
},

'SYN-03': {
  stage:'synthesis', window:[3,7], criticalPath:true,
  purpose:[
    'Release the <b>N0 flow-flush netlist</b>—functionally incomplete, structurally representative—so physical design can build and debug its flow against a real database months before the design is ready.',
    'N0 exists to be wrong in the right way. It has the right hierarchy, the right macros and roughly the right size, and it does not need to work. Its entire purpose is to let <code>PD-01</code> find its flow problems on a throwaway netlist rather than on the one the schedule depends on.',
  ],
  steps:[
    {n:1, text:'N0 scope definition — what must be representative, what may be stubbed', tat:1, lane:'main'},
    {n:2, text:'Black-box and stub strategy for incomplete blocks', tat:1, lane:'main'},
    {n:3, text:'Constraint bootstrap for N0', tat:1, lane:'par'},
    {n:4, text:'Elaboration and structural sanity checking', tat:1, lane:'main'},
    {n:5, text:'Release and physical design handover', tat:1, lane:'main'},
  ],
  flowNote:'Step 1 is the whole activity. N0 has to be representative in the dimensions PD\'s flow cares about—hierarchy, macro count, instance count, pin count—and can be arbitrarily wrong in everything else. Getting that distinction right is what makes it cheap.',
  consumes:[
    'RTL in whatever state exists from RTL-02',
    'Macro list and abstracts from AMS-15',
    'Constraints from SYN-01',
    'Flow setup requirements from PD-01',
    'Hierarchy from ARCH-02',
  ],
  produces:[
    'N0 scope definition — representative versus stubbed',
    'N0 scope definition and stub strategy',
    'Black-boxed and stubbed netlist',
    'Bootstrap constraint set',
    'Structural sanity check results',
    'Released N0 netlist with a stated limitation list',
  ],
  producedBy:[1,2,2,3,4,5],
  rel:[
    {id:'SYN-D1', rel:'produces', text:'<b>N0 flow-flush netlist for PD flow setup.</b> This activity is the deliverable, and its value is entirely in arriving early rather than in being correct.'},
    {id:'SYN-D8', rel:'feeds', text:'<b>Physical design handoff package per drop.</b> N0 is the first handoff, and it sets the format every later one follows.'},
  ],
  risks:[
    '<b>N0 delayed until it is good.</b> The point is to be early; a correct N0 delivered late has become N1 and left PD\'s flow undebugged.',
    '<b>Not representative in the dimensions that matter.</b> A netlist with a tenth of the instances exercises none of the runtime and capacity problems PD needs to find.',
    '<b>Limitations not stated.</b> Physical design chasing timing on a stubbed netlist wastes a week before someone explains it was never going to close.',
    '<b>Stub strategy that changes the hierarchy.</b> A hierarchy that differs from the real one means the flow is set up for a structure that will not arrive.',
    '<b>Treated as a milestone rather than a tool.</b> N0 is scaffolding; celebrating it as progress distracts from the fact that no real design has been synthesized.',
  ],
  roles:[
    {r:'Synthesis lead', d:'Owns N0 scope and release'},
    {r:'Physical design lead', d:'States what must be representative'},
    {r:'Integration engineer', d:'Stub and black-box implementation'},
    {r:'Constraints engineer', d:'Bootstrap constraint set'},
    {r:'Configuration manager', d:'Release tagging and limitation list'},
  ],
  effort:[['Scope definition and stubs',2], ['Elaboration and structural checks',1.5], ['Release and handover',1.5], ['Bootstrap constraints',1]],
  entry:[
    'Enough RTL exists to elaborate a representative hierarchy',
    'Macro abstracts available from AMS-15',
    'PD flow setup ready to receive a netlist',
  ],
  exit:[
    'Representative in hierarchy, instance count and macro content',
    'Limitations stated explicitly with the release',
    'Delivered on the date PD\'s flow setup needs it, not when it is good',
  ],
  dependsOn:['SYN-01','SYN-02','AMS-15','RTL-02'],
  dependsNote:null,
  feedsInto:['PD-01','PD-02','SYN-12'],
  measuredBy:[
    'Days from PD flow setup start to N0 availability',
    'Representativeness against the dimensions PD named',
    'Flow problems found on N0 against on N1',
  ],
},

'SYN-04': {
  stage:'synthesis', window:[6,13], criticalPath:false,
  purpose:[
    'Synthesize <b>with the floorplan in the loop</b>—physical-aware mapping, congestion feedback, placement-driven restructuring—so the netlist that reaches physical design is already routable.',
    'Logic synthesis without physical information optimizes for a wire model that does not exist. On a large die the difference between estimated and actual wire delay is large enough to invalidate the optimization, and the correction happens either here or as weeks of congestion work at <code>PD-06</code>.',
  ],
  steps:[
    {n:1, text:'Physical-aware flow setup with the floorplan', tat:1.5, lane:'main'},
    {n:2, text:'Floorplan-aware mapping and optimization', tat:2, lane:'main'},
    {n:3, text:'Macro and blockage awareness in placement', tat:1.5, lane:'par'},
    {n:4, text:'Congestion feedback loop with physical design', tat:2, lane:'main'},
    {n:5, text:'Placement-driven logic restructuring', tat:1.5, lane:'par'},
    {n:6, text:'QoR comparison against non-physical synthesis', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 6 answers whether the added runtime is worth it. Physical-aware synthesis is slower; comparing its QoR against the wire-load-model result is what justifies the cost, and occasionally shows the floorplan is the problem rather than the logic.',
  consumes:[
    'Floorplan from PD-02',
    'Mapped netlist from SYN-02',
    'Congestion analysis from PD-06',
    'Macro placement and blockages from PD-02',
    'Constraints from SYN-01',
  ],
  produces:[
    'Physical-aware synthesis flow',
    'Floorplan-aware mapped netlist',
    'Macro and blockage aware placement',
    'Congestion feedback findings',
    'Restructured logic in congested regions',
    'QoR comparison against non-physical synthesis',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SYN-D5', rel:'feeds', text:'<b>Synthesis QoR report per drop.</b> Physical-aware results are the ones that predict what physical design will actually achieve.'},
    {id:'SYN-D8', rel:'feeds', text:'<b>Physical design handoff package per drop.</b> A netlist synthesized against the floorplan is a materially better handoff than one synthesized against a wire model.'},
  ],
  risks:[
    '<b>Floorplan too immature to synthesize against.</b> Physical-aware synthesis against a floorplan that then changes produces optimization for a layout that never exists.',
    '<b>Congestion feedback one-directional.</b> Synthesis restructures and physical design re-places; without both, each optimizes against the other\'s stale result.',
    '<b>Runtime cost not justified.</b> Physical-aware flows are slow, and without the QoR comparison nobody knows whether the extra hours bought anything.',
    '<b>Restructuring breaking hierarchy.</b> Aggressive cross-boundary optimization improves QoR and makes the netlist harder to close hierarchically and harder to equivalence-check.',
    '<b>Blockages not modelled.</b> Macros and their keep-out regions dominate placement on this die, and synthesis blind to them produces logic that cannot be placed where it assumed.',
  ],
  roles:[
    {r:'Synthesis engineers', d:'Physical-aware flow and restructuring'},
    {r:'Physical design engineers', d:'Floorplan, congestion analysis and feedback'},
    {r:'Synthesis lead', d:'QoR comparison and flow decisions'},
    {r:'Floorplan owner', d:'Macro placement and blockage data'},
    {r:'CAD engineer', d:'Runtime and capacity for physical-aware runs'},
  ],
  effort:[['Congestion feedback loop',4], ['Floorplan-aware mapping',3.5], ['Flow setup',2.5], ['Logic restructuring',2], ['QoR comparison',2]],
  entry:[
    'Floorplan available and stable from PD-02',
    'Mapped netlist available from SYN-02',
    'Congestion analysis capability in PD-06',
  ],
  exit:[
    'Netlist synthesized against a floorplan PD is actually using',
    'Congestion feedback flowing in both directions',
    'Runtime cost justified by a measured QoR improvement',
  ],
  dependsOn:['SYN-02','PD-02'],
  dependsNote:null,
  feedsInto:['SYN-05','SYN-08','PD-05','PD-06'],
  measuredBy:[
    'QoR improvement against non-physical synthesis',
    'Congestion at PD-05 against prediction',
    'Runtime cost per drop',
  ],
},

'SYN-05': {
  stage:'synthesis', window:[8,13], criticalPath:true,
  purpose:[
    'Release the <b>N1 drop—the first netlist meant to be closed</b>—against PD\'s feedback from its flow setup, and establish the QoR baseline every later drop is measured against.',
    'N0 proved the flow ran. N1 is where the design\'s actual QoR first becomes visible: real timing, real area, real congestion. The number it establishes is the one <code>PD-05</code> will work from and the one everyone will argue about for the next three months.',
  ],
  steps:[
    {n:1, text:'RTL drop intake and delta review against N0', tat:1, lane:'main'},
    {n:2, text:'Synthesis run and block-level closure', tat:1.5, lane:'main'},
    {n:3, text:'Physical design feedback incorporation', tat:1, lane:'par'},
    {n:4, text:'QoR delta analysis against the N0 baseline', tat:1.5, lane:'main'},
    {n:5, text:'Issue list for the next drop', tat:1, lane:'par'},
    {n:6, text:'Release and handoff to physical design', tat:1, lane:'main'},
  ],
  flowNote:'Step 5 is what makes the drop cadence a process rather than a sequence of releases. Each drop should hand forward a named list of what it could not fix and why, so the next one starts from a position rather than from scratch.',
  consumes:[
    'RTL release from RTL-02',
    'Physical-aware results from SYN-04',
    'PD flow setup feedback from PD-01',
    'Constraints from SYN-01',
    'PPA budgets from ARCH-06',
  ],
  produces:[
    'RTL drop intake and delta review',
    'Block-level synthesis closure',
    'Physical design feedback incorporation record',
    'QoR delta analysis against N0',
    'Issue list carried to N2',
    'N1 netlist',
    'Handoff package for PD turn 1',
  ],
  producedBy:[1,2,3,4,5,6,6],
  rel:[
    {id:'SYN-D2', rel:'produces', text:'<b>N1 and N2 netlist drops with QoR delta reports.</b> The first of the two quality drops, with the baseline it establishes.'},
    {id:'SYN-D5', rel:'feeds', text:'<b>Synthesis QoR report per drop.</b> N1 sets the baseline the QoR trend is measured from.'},
  ],
  risks:[
    '<b>N1 released before RTL is worth synthesizing.</b> A drop taken from unstable RTL produces a baseline that means nothing and a PD turn that chases moving targets.',
    '<b>QoR delta not analyzed.</b> Knowing the numbers without knowing what changed them leaves the next drop guessing about what to fix.',
    '<b>Issue list not carried forward.</b> N2 then rediscovers the same problems, and the drop cadence loses its cumulative benefit.',
    '<b>PD feedback arriving after the drop.</b> Feedback from flow setup has to reach synthesis before N1 is run, not after it is released.',
    '<b>Baseline set on a partial design.</b> A QoR baseline missing significant blocks flatters the trend and hides the growth that follows.',
  ],
  roles:[
    {r:'Synthesis lead', d:'Owns the drop, its QoR and its issue list'},
    {r:'Synthesis engineers', d:'Run, closure and delta analysis'},
    {r:'Physical design lead', d:'Feedback into the drop and acceptance out of it'},
    {r:'RTL lead', d:'Confirms RTL readiness for the drop'},
    {r:'PPA lead', d:'Baseline against the ARCH-06 budgets'},
  ],
  effort:[['Synthesis run and closure',4], ['QoR delta analysis',3], ['Feedback incorporation',2.5], ['Intake and release',2.5]],
  entry:[
    'RTL stable enough that a drop is meaningful',
    'PD flow setup complete and feedback available from PD-01',
    'Constraints validated in SYN-01',
  ],
  exit:[
    'QoR baseline established against a substantially complete design',
    'Delta against N0 explained, not only reported',
    'Issue list handed forward to N2',
  ],
  dependsOn:['SYN-01','SYN-02','SYN-04','PD-01','RTL-02'],
  dependsNote:null,
  feedsInto:['SYN-08','SYN-11','SYN-12','PD-05'],
  measuredBy:[
    'QoR at N1 against the ARCH-06 budget',
    'Design completeness at the baseline',
    'Issues carried forward against issues found',
  ],
},

'SYN-06': {
  stage:'synthesis', window:[9,16], criticalPath:false,
  purpose:[
    'Reduce power where it is actually spent—<b>clock gating, operand isolation, Vt mix</b>—driven by real switching activity rather than by defaults.',
    'Power optimization without activity data is guesswork. Clock gating inserted everywhere costs area and saves little; inserted where the data says the logic is idle it saves a meaningful fraction of dynamic power. The activity data comes from verification, which makes this a cross-stage dependency more than a synthesis setting.',
  ],
  steps:[
    {n:1, text:'Power analysis baseline and hot-spot identification', tat:1.5, lane:'main'},
    {n:2, text:'Clock gating insertion and efficiency analysis', tat:2, lane:'main'},
    {n:3, text:'Vt mix optimization for leakage', tat:1.5, lane:'par'},
    {n:4, text:'Operand isolation and datapath gating', tat:2, lane:'main'},
    {n:5, text:'Activity-driven optimization with real switching data', tat:1.5, lane:'par'},
    {n:6, text:'Power QoR and comparison against the budget', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 5 is what separates power optimization from power decoration. Switching activity from the <code>DV-04</code> workload simulations tells the tool which logic is actually idle; without it, gating is inserted by structural heuristic and saves a fraction of what it could.',
  consumes:[
    'Switching activity from DV-04 workload simulations',
    'Power budgets from ARCH-06',
    'Mapped netlist from SYN-02',
    'Library Vt menu from PDK-03',
    'Clock architecture from ARCH-05',
  ],
  produces:[
    'Power analysis baseline and hot spots',
    'Clock gating insertion and efficiency report',
    'Vt mix optimization results',
    'Operand isolation implementation',
    'Activity-driven optimization results',
    'Power QoR against budget',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SYN-D5', rel:'feeds', text:'<b>Synthesis QoR report per drop.</b> Power is one of the three QoR axes, and the only one that needs external activity data to measure honestly.'},
    {id:'SYN-D7', rel:'feeds', text:'<b>Power intent implementation report.</b> Dynamic power optimization sits alongside the UPF implementation from <code>SYN-07</code> in the same report.'},
  ],
  risks:[
    '<b>Optimization driven by default activity.</b> Uniform switching assumptions produce gating where it saves nothing and none where it would.',
    '<b>Clock gating efficiency unmeasured.</b> Gates inserted without measuring how often they actually gate cost area and leakage for no benefit.',
    '<b>Vt mix skewed to low-Vt for timing.</b> Leakage grows non-linearly, and a design closed on low-Vt everywhere blows its static power budget.',
    '<b>Power measured at the wrong operating point.</b> The number that matters is at the DVFS point the product runs at, not at nominal.',
    '<b>Optimization deferred to the final turn.</b> Power changes timing; a design closed on timing and then power-optimized has to be re-closed.',
  ],
  roles:[
    {r:'Power optimization engineer', d:'Owns dynamic and leakage optimization'},
    {r:'Synthesis engineers', d:'Flow configuration and insertion'},
    {r:'Verification liaison', d:'Switching activity from real workloads'},
    {r:'PPA lead', d:'Power against the ARCH-06 budget'},
    {r:'Library engineer', d:'Vt menu usage and leakage characterization'},
  ],
  effort:[['Clock gating',3.5], ['Vt mix optimization',2.5], ['Operand isolation',2.5], ['Power analysis',2], ['QoR comparison',1.5]],
  entry:[
    'Switching activity available from DV-04',
    'Power budgets published by ARCH-06',
    'Mapped netlist available from SYN-02',
  ],
  exit:[
    'Optimization driven by real activity data, not defaults',
    'Clock gating efficiency measured, not assumed',
    'Power reported at the operating point the product uses',
  ],
  dependsOn:['SYN-02','ARCH-06','DV-04','PDK-03'],
  dependsNote:null,
  feedsInto:['SYN-08','SYN-11','PD-09','SO-04'],
  measuredBy:[
    'Dynamic power against budget',
    'Clock gating efficiency',
    'Leakage against the Vt mix projection',
  ],
},

'SYN-07': {
  stage:'synthesis', window:[10,15], criticalPath:false,
  purpose:[
    'Implement the <b>power intent in the netlist</b>—isolation cells, level shifters, retention flops, always-on paths—from the UPF, and prove the netlist and the intent still agree.',
    'UPF describes what should happen; synthesis is where it becomes cells. An isolation cell missing at a domain boundary is a design that corrupts data on power-down, and it is invisible in any functional check that does not model power. The consistency check between netlist and intent is the only reliable detector.',
  ],
  steps:[
    {n:1, text:'UPF ingestion and elaboration in the synthesis flow', tat:1, lane:'main'},
    {n:2, text:'Isolation and level shifter inference and insertion', tat:1.5, lane:'main'},
    {n:3, text:'Always-on and feed-through path handling', tat:1, lane:'par'},
    {n:4, text:'Retention cell insertion and control', tat:1.5, lane:'main'},
    {n:5, text:'UPF and netlist consistency checking', tat:1, lane:'par'},
    {n:6, text:'Power intent implementation report', tat:1, lane:'main'},
  ],
  flowNote:'Step 5 runs in parallel and is the one that must not be skipped. The netlist and the UPF are two descriptions of the same intent, and any divergence between them propagates into physical design and verification as a defect nobody can attribute.',
  consumes:[
    'UPF from RTL-05',
    'Low-power cells from PDK-03',
    'Power domain definition from ARCH-05',
    'Mapped netlist from SYN-02',
    'Low-power flow from PDK-09',
  ],
  produces:[
    'Elaborated UPF in the synthesis flow',
    'Inserted isolation and level shifter cells',
    'Always-on path implementation',
    'Retention cell insertion and control logic',
    'UPF-netlist consistency results',
    'Power intent implementation report',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SYN-D7', rel:'produces', text:'<b>Power intent implementation report.</b> This activity is the deliverable—what was inferred, what was inserted, and where intent and netlist agree.'},
    {id:'SYN-D6', rel:'feeds', text:'<b>Formal equivalence clean report per drop.</b> Low-power cells complicate equivalence checking, and the two activities have to agree on how they are handled.'},
  ],
  risks:[
    '<b>Isolation inferred but not verified.</b> A missing cell at one boundary corrupts state on power-down and appears in no functional test.',
    '<b>Retention cells inserted without physical planning.</b> They have a different footprint and power connectivity, and adding them late disturbs the floorplan.',
    '<b>Always-on paths not identified.</b> Logic that must survive a domain shutting down and is not marked always-on is powered down with it.',
    '<b>UPF and netlist diverging.</b> Two descriptions of the same intent, and downstream tools reading different ones.',
    '<b>Level shifters omitted between voltage domains.</b> The design functions in simulation and fails at the voltage extremes in silicon.',
  ],
  roles:[
    {r:'Low-power synthesis engineer', d:'Owns intent implementation in the netlist'},
    {r:'Low-power implementation lead', d:'UPF correctness and intent alignment'},
    {r:'Physical design liaison', d:'Retention and always-on physical implications'},
    {r:'Verification liaison', d:'Confirms the implementation is verifiable'},
    {r:'Library engineer', d:'Low-power cell availability and characterization'},
  ],
  effort:[['Isolation and level shifter insertion',2.5], ['Retention cell insertion',2], ['UPF elaboration',1.5], ['Consistency checking',1], ['Implementation report',1]],
  entry:[
    'UPF available and tool-accepted from RTL-05',
    'Low-power cells qualified in PDK-03',
    'Low-power flow available from PDK-09',
  ],
  exit:[
    'Every domain boundary has verified isolation',
    'UPF and netlist consistent, checked rather than assumed',
    'Retention and always-on requirements handed to physical design',
  ],
  dependsOn:['RTL-05','SYN-02','PDK-03','PDK-09'],
  dependsNote:null,
  feedsInto:['SYN-10','DV-06','PD-03','SO-09'],
  measuredBy:[
    'Domain boundaries with verified isolation',
    'UPF-netlist consistency violations',
    'Low-power cells inserted against intent',
  ],
},

'SYN-08': {
  stage:'synthesis', window:[14,19], criticalPath:true,
  purpose:[
    'Release the <b>N2 drop with everything enabled</b>—full optimization, power, low-power intent, physical awareness—and state honestly how much closure risk remains.',
    'N2 is the last drop before the FFN and the last chance to change anything structurally. Its QoR is the best prediction available of what the final turn will achieve, and the closure risk statement it carries is what tells the program whether the tapeout date is credible.',
  ],
  steps:[
    {n:1, text:'RTL and ECO intake since N1', tat:1, lane:'main'},
    {n:2, text:'Full synthesis with all optimizations enabled', tat:1.5, lane:'main'},
    {n:3, text:'Late RTL change impact assessment', tat:1, lane:'par'},
    {n:4, text:'Congestion and timing convergence check', tat:1.5, lane:'main'},
    {n:5, text:'Physical design turn-1 feedback incorporation', tat:1, lane:'par'},
    {n:6, text:'Release with a closure risk statement', tat:1, lane:'main'},
  ],
  flowNote:'Step 6 is the honest part. A drop released with "timing is converging" tells nobody anything; one released with "forty paths in two blocks remain, all in the compute cluster, requiring a restructure or a frequency concession" gives the program a decision.',
  consumes:[
    'RTL updates and ECOs since N1',
    'Turn 1 results and feedback from PD-05',
    'Power optimization from SYN-06',
    'Low-power implementation from SYN-07',
    'Physical-aware results from SYN-04',
  ],
  produces:[
    'RTL and ECO intake record since N1',
    'N2 netlist with full optimization',
    'Late change impact assessment',
    'Congestion and timing convergence analysis',
    'Turn-1 feedback incorporation record',
    'Closure risk statement',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SYN-D2', rel:'produces', text:'<b>N1 and N2 netlist drops with QoR delta reports.</b> The second quality drop, and the last structurally changeable one.'},
    {id:'SYN-D5', rel:'feeds', text:'<b>Synthesis QoR report per drop.</b> The N2 QoR is the best available prediction of what the final turn will reach.'},
  ],
  risks:[
    '<b>Closure risk understated.</b> An optimistic risk statement at N2 removes the program\'s last opportunity to take a frequency or feature concession while it is still cheap.',
    '<b>Late RTL changes absorbed without assessment.</b> A functional change arriving between N1 and N2 can invalidate the turn-1 closure work entirely.',
    '<b>All optimizations enabled for the first time at N2.</b> Enabling power, low-power and physical awareness together for the first time produces a QoR nobody can attribute.',
    '<b>Turn-1 feedback not incorporated.</b> N2 then repeats N1\'s physical problems, and turn 2 spends its time on the same issues.',
    '<b>Treated as the final netlist.</b> N2 is not the FFN, and freezing behavior around it removes the RTL freeze discipline that <code>SYN-09</code> depends on.',
  ],
  roles:[
    {r:'Synthesis lead', d:'Owns the drop and the closure risk statement'},
    {r:'Synthesis engineers', d:'Full-optimization run and convergence analysis'},
    {r:'Physical design lead', d:'Turn-1 feedback and turn-2 acceptance'},
    {r:'RTL lead', d:'Late change control and impact'},
    {r:'Program manager', d:'Consumes the risk statement for schedule decisions'},
  ],
  effort:[['Full synthesis run',4], ['Convergence check',3], ['Change impact assessment',2.5], ['Release and risk statement',2.5]],
  entry:[
    'Turn 1 complete with feedback from PD-05',
    'Power and low-power optimization available from SYN-06 and SYN-07',
    'RTL changes since N1 controlled through RTL-10',
  ],
  exit:[
    'Closure risk stated specifically, with paths, blocks and options',
    'Turn-1 feedback incorporated rather than deferred',
    'Late changes assessed before inclusion',
  ],
  dependsOn:['SYN-04','SYN-05','SYN-06','SYN-07','PD-05'],
  dependsNote:null,
  feedsInto:['SYN-09','SYN-11','PD-06','SO-01'],
  measuredBy:[
    'Closure risk at N2 against outcome at the final turn',
    'Late changes assessed against absorbed',
    'QoR delta from N1',
  ],
},

'SYN-09': {
  stage:'synthesis', window:[19,23], criticalPath:true,
  purpose:[
    'Release the <b>FFN—the final full netlist</b>—against frozen RTL, with constraints frozen and equivalence proved, and declare that nothing functional changes after it.',
    'The FFN is a commitment more than a deliverable. Everything after it is physical: <code>PD-13</code> closes on this netlist and <code>SO-02</code> signs off on what PD produces. A functional change after the FFN restarts both, which is why the freeze around it has to be real.',
  ],
  steps:[
    {n:1, text:'RTL freeze confirmation and final intake', tat:0.75, lane:'main'},
    {n:2, text:'Final synthesis run', tat:1.25, lane:'main'},
    {n:3, text:'Final constraint freeze', tat:1, lane:'par'},
    {n:4, text:'Final equivalence and UPF consistency verification', tat:1, lane:'main'},
    {n:5, text:'Handoff package assembly', tat:0.75, lane:'par'},
    {n:6, text:'FFN release and functional freeze declaration', tat:1, lane:'main'},
  ],
  flowNote:'Step 1 is a confirmation rather than a formality. If <code>RTL-10</code> has not actually declared freeze, the FFN is a snapshot of a moving design, and the final turn in <code>PD-13</code> will be closing against something that changes underneath it.',
  consumes:[
    'Frozen RTL from RTL-10',
    'Constraints from SYN-01',
    'Optimization configuration from SYN-06 and SYN-07',
    'N2 results and closure risk from SYN-08',
    'Equivalence methodology from SYN-10',
  ],
  produces:[
    'RTL freeze confirmation',
    'Final synthesis run and netlist',
    'Frozen constraint set',
    'Final equivalence and UPF consistency results',
    'Handoff package for the final turn',
    'FFN release with functional freeze declaration',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SYN-D3', rel:'produces', text:'<b>FFN—final full netlist, release-tagged.</b> This activity is the deliverable, and the milestone the stage ends on.'},
    {id:'SYN-D4', rel:'gates', text:'<b>Validated SDC constraint set.</b> Constraints freeze with the FFN—closing against moving constraints is closing against nothing.'},
    {id:'SYN-D8', rel:'feeds', text:'<b>Physical design handoff package per drop.</b> The final handoff, and the one <code>PD-13</code> closes against.'},
  ],
  risks:[
    '<b>FFN released against RTL that is not actually frozen.</b> The final turn then closes against a moving netlist, and every change restarts it.',
    '<b>Constraints still changing after the FFN.</b> A design closed against one constraint set and signed off against another has not been signed off.',
    '<b>Equivalence not proved on the final netlist.</b> The last synthesis run is the one most likely to contain a transformation error, and the least likely to be checked under schedule pressure.',
    '<b>Functional freeze declared and not enforced.</b> Post-FFN functional ECOs are sometimes unavoidable and must be exceptional, visible and costed.',
    '<b>Handoff package incomplete.</b> The final turn needs constraints, UPF, DFT collateral and abstracts together; a missing item stops closure at its start.',
  ],
  roles:[
    {r:'Synthesis lead', d:'Owns the FFN and the freeze declaration'},
    {r:'Constraints lead', d:'Constraint freeze'},
    {r:'Equivalence engineer', d:'Final LEC and consistency'},
    {r:'RTL lead', d:'Confirms RTL freeze is real'},
    {r:'Physical design lead', d:'Accepts the handoff for the final turn'},
  ],
  effort:[['Final synthesis run',3.5], ['Equivalence and consistency',2.5], ['Release and freeze declaration',2], ['Constraint freeze',1], ['Handoff package',1]],
  entry:[
    'RTL freeze declared by RTL-10',
    'N2 closure risk understood from SYN-08',
    'Equivalence methodology proven across earlier drops',
  ],
  exit:[
    'Equivalence proved on the actual FFN, not on a proxy',
    'Constraints frozen with the netlist',
    'Functional freeze declared and its exception process published',
  ],
  dependsOn:['SYN-08','SYN-10','RTL-10'],
  dependsNote:null,
  feedsInto:['PD-13','SO-02','SO-09','TO-01'],
  measuredBy:[
    'Functional changes after the FFN',
    'Equivalence result on the final netlist',
    'Handoff completeness at the final turn\'s start',
  ],
},

'SYN-10': {
  stage:'synthesis', window:[4,24], criticalPath:false,
  purpose:[
    'Prove that <b>every netlist still means what the RTL meant</b>—formal equivalence per drop, including through DFT insertion, clock gating and low-power transformations.',
    'Synthesis rewrites the design, and the tools that do it are not infallible. Equivalence checking is the only evidence that the netlist implements the RTL that verification actually verified; without it, a transformation error is discovered in silicon as behavior nobody can trace to a bug.',
  ],
  steps:[
    {n:1, text:'Equivalence methodology and tool setup', tat:1.5, lane:'main'},
    {n:2, text:'Block-level equivalence per drop', tat:2, lane:'main'},
    {n:3, text:'Black-box and constraint handling for incomplete drops', tat:2, lane:'par'},
    {n:4, text:'Chip-level equivalence per drop', tat:3, lane:'main'},
    {n:5, text:'DFT and clock gating equivalence handling', tat:2, lane:'par'},
    {n:6, text:'Non-equivalence debug and resolution', tat:2.5, lane:'main'},
    {n:7, text:'Per-drop equivalence reporting', tat:2, lane:'par'},
    {n:8, text:'Continuous checking across the drop sequence', tat:11, lane:'main'},
  ],
  flowNote:'Step 5 is where most of the difficulty lives. Scan insertion and clock gating change the netlist in ways that are correct and not structurally equivalent, and setting up the checker to accept those and reject everything else is the skilled part of the activity.',
  consumes:[
    'RTL from RTL-02 and RTL-04',
    'Netlists from every synthesis drop',
    'Scan-inserted netlist from DFT-06',
    'UPF and low-power implementation from SYN-07',
    'Equivalence tools from PDK-08',
  ],
  produces:[
    'Equivalence methodology and setup',
    'Per-drop block-level equivalence results',
    'Black-box and constraint handling record',
    'Block and chip-level equivalence results per drop',
    'DFT and clock gating handling configuration',
    'Non-equivalence debug records',
    'Per-drop equivalence reports',
    'Equivalence checking log across the drop sequence',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'SYN-D6', rel:'produces', text:'<b>Formal equivalence clean report per drop.</b> This activity is the deliverable, and "per drop" is what makes it a control rather than a final check.'},
    {id:'SYN-D3', rel:'gates', text:'<b>FFN—final full netlist.</b> An FFN that has not been proved equivalent is a netlist nobody can claim was verified.'},
  ],
  risks:[
    '<b>Equivalence run only on the final netlist.</b> A transformation error introduced at N1 is then found at the FFN, when the debug competes with tapeout.',
    '<b>Non-equivalences waived to make progress.</b> Each waiver is a place where the netlist may not implement the verified RTL, and they accumulate quietly.',
    '<b>DFT transformations not modelled.</b> The checker reports thousands of differences and everyone stops reading the report.',
    '<b>Black-box handling too permissive.</b> Boxing out a block to get a clean result excludes exactly the logic that was not checked.',
    '<b>Debug capacity underestimated.</b> A single real non-equivalence on a design this size can take a week to localize, and there is rarely a week available.',
  ],
  roles:[
    {r:'Equivalence engineer', d:'Owns methodology, runs and debug'},
    {r:'Synthesis engineers', d:'Transformation explanations and fixes'},
    {r:'DFT engineer', d:'Scan transformation handling'},
    {r:'Low-power engineer', d:'UPF-related transformation handling'},
    {r:'Synthesis lead', d:'Waiver decisions and reporting'},
  ],
  effort:[['Continuous checking',4], ['Non-equivalence debug',3], ['Chip-level equivalence',2], ['Methodology and setup',1.5], ['DFT and low-power handling',1.5]],
  entry:[
    'RTL and first netlists available',
    'Equivalence tools qualified by PDK-08',
    'DFT insertion methodology known from DFT-06',
  ],
  exit:[
    'Every drop checked, not only the final one',
    'Non-equivalences resolved rather than waived',
    'Chip-level equivalence clean on the FFN',
  ],
  dependsOn:['SYN-02','SYN-07','DFT-06','PDK-08'],
  dependsNote:null,
  feedsInto:['SYN-09','SO-09','TO-02'],
  measuredBy:[
    'Drops with a clean equivalence result',
    'Non-equivalences waived against resolved',
    'Debug time per non-equivalence',
  ],
},

'SYN-11': {
  stage:'synthesis', window:[2,24], criticalPath:false,
  purpose:[
    'Report <b>timing, area and power against the budget after every drop</b>, and escalate when a block is diverging rather than when it has already blown its allocation.',
    'QoR reported in absolute terms tells nobody anything. Reported against the <code>ARCH-06</code> allocation and trended across drops, it says which blocks are converging, which are not, and how much of the gap is still recoverable—which is the only version a program manager can act on.',
  ],
  steps:[
    {n:1, text:'Reporting framework and budget ingestion', tat:1.5, lane:'main'},
    {n:2, text:'Per-drop timing report and analysis', tat:2, lane:'main'},
    {n:3, text:'Budget comparison and escalation rules', tat:2, lane:'par'},
    {n:4, text:'Per-drop area and power report', tat:2, lane:'main'},
    {n:5, text:'Trend analysis across the drop sequence', tat:2, lane:'par'},
    {n:6, text:'Continuous reporting across the stage', tat:16.5, lane:'main'},
  ],
  flowNote:'Step 5 is the part that predicts. A block 10% over budget and improving is a different problem from one 5% over and flat, and only a trend across drops distinguishes them.',
  consumes:[
    'Synthesis results from every drop',
    'PPA budgets from ARCH-06',
    'Constraints from SYN-01',
    'Power results from SYN-06',
    'Physical-aware results from SYN-04',
  ],
  produces:[
    'Reporting framework with budget ingestion',
    'Per-drop timing, area and power report',
    'Budget comparison per block',
    'Escalation records',
    'Per-drop timing, area and power reports',
    'Trend analysis across drops',
    'Reporting log across the stage',
  ],
  producedBy:[1,2,3,3,4,5,6],
  rel:[
    {id:'SYN-D5', rel:'produces', text:'<b>Synthesis QoR report per drop against PPA targets.</b> This activity is the deliverable, and "against targets" is what makes it usable.'},
    {id:'SYN-D2', rel:'feeds', text:'<b>N1 and N2 netlist drops with QoR delta reports.</b> The delta report accompanying each drop comes from here.'},
  ],
  risks:[
    '<b>QoR reported in absolute terms.</b> Numbers with no budget reference cannot be acted on, and everyone forms their own opinion of whether they are acceptable.',
    '<b>No escalation rule.</b> Divergence noticed and not escalated becomes a surprise at the final turn, when there is nothing left to do about it.',
    '<b>Reports not normalized across drops.</b> More RTL in a later drop makes the trend meaningless unless the comparison accounts for it.',
    '<b>Power reported at nominal only.</b> The number that matters is at the product\'s operating point, and reporting at nominal understates it consistently.',
    '<b>Reporting stopping between drops.</b> The interesting question is whether a block is improving, and that needs data between releases as well as at them.',
  ],
  roles:[
    {r:'PPA reporting engineer', d:'Owns the framework and the reports'},
    {r:'Synthesis engineers', d:'Data generation per drop'},
    {r:'PPA lead', d:'Budget comparison and escalation decisions'},
    {r:'Block owners', d:'Act on their block\'s divergence'},
    {r:'Program manager', d:'Consumes trends for schedule decisions'},
  ],
  effort:[['Continuous reporting',4], ['Per-drop reports',2.5], ['Budget comparison',2], ['Trend analysis',1.5]],
  entry:[
    'PPA budgets available from ARCH-06',
    'First synthesis results available',
    'Reporting framework agreed with the PPA lead',
  ],
  exit:[
    'Every report references the budget, not only the absolute number',
    'Divergence escalated on a rule, not on judgment',
    'Trends normalized so drops are comparable',
  ],
  dependsOn:['SYN-01','SYN-02','ARCH-06','PDK-12'],
  dependsNote:null,
  feedsInto:['SYN-05','SYN-08','PD-09','ARCH-06'],
  measuredBy:[
    'Blocks reported against budget',
    'Escalations raised before the final turn',
    'Trend accuracy in predicting final-turn QoR',
  ],
},

'SYN-12': {
  stage:'synthesis', window:[2,24], criticalPath:false,
  purpose:[
    'Hand each netlist to physical design as a <b>complete, accepted package</b>—netlist, constraints, UPF, DFT collateral, abstracts—and review the QoR delta together rather than throwing results over a wall.',
    'The handoff is where two teams either share a picture of the design or maintain two. Six man-months across the stage buys a structured package and a joint review per drop, and it prevents the pattern where physical design spends a week discovering what synthesis already knew.',
  ],
  steps:[
    {n:1, text:'Handoff package definition — contents and format', tat:1, lane:'main'},
    {n:2, text:'Per-drop package assembly', tat:1.5, lane:'main'},
    {n:3, text:'Acceptance criteria agreed with physical design', tat:1.5, lane:'par'},
    {n:4, text:'QoR delta review with physical design per drop', tat:1.5, lane:'main'},
    {n:5, text:'Issue tracking between drops', tat:1.5, lane:'par'},
    {n:6, text:'Continuous handoff across the drop sequence', tat:18, lane:'main'},
  ],
  flowNote:'Step 3 is what makes a handoff a transaction rather than a delivery. Acceptance criteria mean physical design can reject a package that is incomplete, and rejection at handoff is far cheaper than discovering the gap three days into a turn.',
  consumes:[
    'Netlists from every drop',
    'Constraints from SYN-01',
    'UPF and low-power implementation from SYN-07',
    'DFT collateral from DFT-06',
    'QoR reports from SYN-11',
  ],
  produces:[
    'Handoff package definition and format',
    'Per-drop handoff package',
    'Acceptance criteria agreed with PD',
    'QoR delta review records',
    'Issue tracking between drops',
    'Assembled packages per drop',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'SYN-D8', rel:'produces', text:'<b>Physical design handoff package per drop.</b> This activity is the deliverable, and acceptance rather than delivery is its standard.'},
    {id:'SYN-D2', rel:'feeds', text:'<b>N1 and N2 netlist drops with QoR delta reports.</b> The delta review is where the drop is actually transferred.'},
  ],
  risks:[
    '<b>Packages delivered without acceptance.</b> Physical design discovers the gap mid-turn, and the turn absorbs the delay.',
    '<b>QoR reviewed asynchronously.</b> A report read separately produces two interpretations, and the disagreement surfaces at the next escalation.',
    '<b>Issues not tracked between drops.</b> Each handoff then starts fresh, and the same problems are raised at every drop.',
    '<b>Package contents changing between drops.</b> Physical design automates against the format, and an inconsistent package breaks their flow.',
    '<b>Handoff treated as a synthesis milestone.</b> It is a shared event; a handoff that PD has not accepted has not happened.',
  ],
  roles:[
    {r:'Synthesis lead', d:'Owns the handoff and the delta review'},
    {r:'Physical design lead', d:'Acceptance and feedback'},
    {r:'Configuration manager', d:'Package assembly and version control'},
    {r:'DFT engineer', d:'DFT collateral in the package'},
    {r:'PPA lead', d:'Joint QoR interpretation'},
  ],
  effort:[['Continuous handoff',2.5], ['QoR delta review',1.5], ['Package assembly',1], ['Acceptance criteria',1]],
  entry:[
    'First netlist drop ready in SYN-03',
    'Acceptance criteria negotiable with physical design',
    'Package format agreed',
  ],
  exit:[
    'Every package accepted rather than merely delivered',
    'QoR reviewed jointly per drop',
    'Issues tracked across drops rather than re-raised',
  ],
  dependsOn:['SYN-03','SYN-05','SYN-11'],
  dependsNote:null,
  feedsInto:['PD-01','PD-05','PD-06','PD-13'],
  measuredBy:[
    'Packages accepted at first presentation',
    'Issues carried between drops against re-raised',
    'Days lost to incomplete handoffs',
  ],
},

};
