/* TC — Test Chip / MPW Shuttle. Eight activities. Stage w22–62 (40w), 83 M/M. */
module.exports = {

'TC-01': {
  stage:'testChip', window:[0,5], criticalPath:true,
  purpose:[
    'Decide what the test chip is <b>for</b>—which specific risks it retires—and select the structures that will actually answer those questions rather than the ones that are easy to include.',
    'A test chip with no objective becomes a collection of everything anyone wanted to try, and it answers nothing in time to matter. The discipline is subtractive: name the two or three uncertainties that would change a production decision, and carry only what measures them.',
  ],
  steps:[
    {n:1, text:'Objective definition — which production decisions this chip informs', tat:1, lane:'main'},
    {n:2, text:'Risk item selection and prioritization', tat:1.5, lane:'main'},
    {n:3, text:'Schedule feasibility — does the answer arrive before the decision', tat:1, lane:'par'},
    {n:4, text:'Structure selection per risk item', tat:1, lane:'main'},
    {n:5, text:'Cost and area budget for the shuttle die', tat:0.75, lane:'par'},
    {n:6, text:'Specification and risk coverage matrix', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 3 can cancel the activity, and should be allowed to. A test chip whose results land after the production design has committed is an expense with no decision attached, and finding that out in week three is far better than in week forty.',
  consumes:[
    'Node risk assessment from TECH-07',
    'IP readiness gaps from IPR-05',
    'Custom memory decision from PDK-06',
    'AMS block risk list from AMS-01',
    'Production design schedule from DEF-08',
  ],
  produces:[
    'Test chip objective statement',
    'Prioritized risk item list',
    'Schedule feasibility finding',
    'Structure selection per risk',
    'Shuttle die cost and area budget',
    'Test chip specification and risk coverage matrix',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'TC-D1', rel:'produces', text:'<b>Test chip specification and risk coverage matrix.</b> This activity is the deliverable, and the matrix is what every later result is reported against.'},
    {id:'TC-D5', rel:'feeds', text:'<b>Design guidance and margin decisions.</b> The guidance can only address risks this activity chose to carry—everything else stays unmeasured.'},
  ],
  risks:[
    '<b>Scope grows until the shuttle is missed.</b> Every team has something worth measuring, and a chip that carries all of them misses the slot that made it useful.',
    '<b>Results arrive after the decision.</b> A test chip is only worth its cost if the answer lands while the production design can still act on it.',
    '<b>Structures chosen for measurability rather than for risk.</b> Ring oscillators are easy and tell you about the node; the risk is usually in a specific circuit nobody has built before.',
    '<b>No decision rule attached to a result.</b> Measuring something without agreeing in advance what each outcome would change produces data and no decisions.',
    '<b>Area budget set after structure selection.</b> Shuttle die area is expensive and fixed; selecting first and budgeting second guarantees a painful subtraction later.',
  ],
  roles:[
    {r:'Test chip lead', d:'Owns the objective, the scope and the coverage matrix'},
    {r:'Chief architect', d:'Confirms which risks would change a production decision'},
    {r:'AMS lead', d:'Analog risk items and the structures that measure them'},
    {r:'Program manager', d:'Schedule feasibility against the production decision dates'},
    {r:'Device and technology engineer', d:'PCM and process monitor structure selection'},
  ],
  effort:[['Risk item selection',1.25], ['Structure selection',1], ['Specification and coverage matrix',1], ['Objective definition',0.75]],
  entry:[
    'Node risk assessment available from TECH-07',
    'IP and memory gaps known from IPR-05 and PDK-06',
    'Production design schedule dated by DEF-08',
  ],
  exit:[
    'Every carried structure traces to a named risk and a decision rule',
    'Schedule feasibility confirmed against the decision dates',
    'Area and cost budget fixed before structures are finalized',
  ],
  dependsOn:['TECH-07','IPR-05','PDK-06','AMS-01'],
  dependsNote:null,
  feedsInto:['TC-02','TC-03','TC-04','TC-07'],
  measuredBy:[
    'Structures traceable to a risk item',
    'Risks covered against risks identified',
    'Shuttle die area against budget',
  ],
},

'TC-02': {
  stage:'testChip', window:[2,14], criticalPath:true,
  purpose:[
    'Design and integrate the vehicle itself—<b>the IP under test, its access wrappers, the process monitors and the measurement structures</b>—as a small chip that has to work first time.',
    'A test chip gets one shuttle. There is no bring-up iteration and no respin, so the access paths, the monitors and the pad ring have to be right on submission. That makes it a small design with an unusually high verification burden relative to its size.',
  ],
  steps:[
    {n:1, text:'IP-under-test integration plan', tat:1, lane:'main'},
    {n:2, text:'Device-under-test wrapper and access path design', tat:3, lane:'main'},
    {n:3, text:'Ring oscillator and process monitor array', tat:2, lane:'par'},
    {n:4, text:'Measurement and PCM structure design', tat:3, lane:'main'},
    {n:5, text:'Test structure library assembly', tat:2, lane:'par'},
    {n:6, text:'Top-level integration and pad assignment', tat:2.5, lane:'main'},
    {n:7, text:'Pad ring and ESD for the shuttle die', tat:1.5, lane:'par'},
    {n:8, text:'Verification of access paths and measurement modes', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 8 gets two and a half weeks for a chip that is mostly structures, because an access path that does not work makes the structure behind it unmeasurable. Every mode has to be exercised in simulation, since there is no second chance in silicon.',
  consumes:[
    'Test chip specification and coverage matrix from TC-01',
    'IP-under-test deliverables from AMS and IPR',
    'Process monitor structure definitions from the foundry',
    'Shuttle die area and pad count limits from TC-03',
    'PDK and libraries from PDK-13',
  ],
  produces:[
    'IP-under-test integration plan',
    'IP-under-test integration with access wrappers',
    'Ring oscillator and process monitor arrays',
    'Measurement and PCM structures',
    'Assembled test structure library',
    'Top-level netlist with pad assignment',
    'Pad ring and ESD design for the shuttle',
    'Access path and measurement mode verification results',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TC-D2', rel:'feeds', text:'<b>Test chip GDS and shuttle submission record.</b> The design half—<code>TC-04</code> turns it into a submittable database.'},
    {id:'TC-D1', rel:'feeds', text:'<b>Test chip specification and risk coverage matrix.</b> Where a structure cannot be built as specified, the matrix is what gets updated.'},
  ],
  risks:[
    '<b>Access paths unverified.</b> A structure that cannot be reached is a structure that was not measured, and the failure is only discovered in the lab.',
    '<b>Pad count exceeded.</b> Shuttle die have few pads; a measurement scheme needing more forces multiplexing that has to be designed and verified.',
    '<b>IP under test modified for the vehicle.</b> A block wrapped or altered to fit the test chip is no longer the block the production design will use.',
    '<b>Monitors placed without regard to position.</b> Process variation across the die is part of what is being measured, and monitors clustered in one corner cannot see it.',
    '<b>No redundancy in critical structures.</b> A single instance of the structure that matters most means one defect loses the answer entirely.',
  ],
  roles:[
    {r:'Test chip design lead', d:'Owns the integration and the access architecture'},
    {r:'Analog designers', d:'IP-under-test wrappers and measurement paths'},
    {r:'Device engineer', d:'Process monitor and PCM structure design'},
    {r:'Verification engineer', d:'Access path and measurement mode verification'},
    {r:'Layout lead', d:'Pad ring, area and structure placement'},
  ],
  effort:[['DUT wrappers and access paths',4.5], ['Measurement and PCM structures',4], ['Top-level integration',3.5], ['Verification',3], ['Ring oscillator arrays',2], ['Pad ring and ESD',1]],
  entry:[
    'Specification and coverage matrix from TC-01',
    'IP-under-test available in a form that can be instantiated',
    'Shuttle die area and pad limits known',
  ],
  exit:[
    'Every structure reachable through a verified access path',
    'Monitors distributed to see across-die variation',
    'Pad budget met without unverified multiplexing',
  ],
  dependsOn:['TC-01','TC-03','PDK-13'],
  dependsNote:null,
  feedsInto:['TC-04','TC-06','TC-07'],
  measuredBy:[
    'Structures with a verified access path',
    'Measurement modes exercised in simulation',
    'Pad count against the shuttle limit',
  ],
},

'TC-03': {
  stage:'testChip', window:[5,9], criticalPath:false,
  purpose:[
    'Book the shuttle slot and <b>work backwards from its submission date</b>—because the shuttle calendar is fixed, and missing a slot costs a quarter rather than a week.',
    'One man-month across four weeks: almost all of this is scheduling and paperwork. Its importance is out of proportion to its effort, because the submission date it fixes is what every other test chip activity is planned against.',
  ],
  steps:[
    {n:1, text:'Shuttle calendar review and slot options', tat:1, lane:'main'},
    {n:2, text:'Foundry or broker engagement and pricing', tat:0.75, lane:'par'},
    {n:3, text:'Slot booking against the production decision dates', tat:1, lane:'main'},
    {n:4, text:'Data format and submission requirement collection', tat:0.75, lane:'par'},
    {n:5, text:'Submission schedule and checklist working backwards from the slot', tat:2, lane:'main'},
  ],
  flowNote:'Step 5 is the useful output. A shuttle slot is a date on which a compliant database must exist; scheduling backwards from it is what tells <code>TC-04</code> when physical verification actually has to finish.',
  consumes:[
    'Test chip objective and schedule feasibility from TC-01',
    'Shuttle calendars from the foundry or broker',
    'Capacity and pricing terms from TECH-05',
    'Production decision dates from DEF-08',
    'Submission format requirements',
  ],
  produces:[
    'Shuttle slot options and pricing',
    'Foundry or broker engagement with pricing',
    'Booked slot with confirmation',
    'Data format and submission requirements',
    'Backward-planned submission schedule',
    'Submission checklist',
  ],
  producedBy:[1,2,3,4,5,5],
  rel:[
    {id:'TC-D2', rel:'feeds', text:'<b>Test chip GDS and shuttle submission record.</b> The booking and its requirements are half the submission record; the database is the other half.'},
  ],
  risks:[
    '<b>Slot booked without checking the production decision date.</b> An available slot that returns silicon too late buys nothing.',
    '<b>Submission requirements collected late.</b> Shuttle submissions have their own format and layer rules, and discovering them near the date forces rushed rework.',
    '<b>Backward schedule not enforced.</b> A submission date that is not translated into a physical verification deadline gets missed by exactly the amount by which signoff runs long.',
    '<b>No contingency slot identified.</b> A missed shuttle costs a quarter, and knowing the next available date in advance changes how the schedule is managed.',
    '<b>Cost approved after booking.</b> Shuttle die area is charged by area and layer count; booking before the budget is agreed produces an invoice nobody planned.',
  ],
  roles:[
    {r:'Program manager', d:'Owns the slot booking and the backward schedule'},
    {r:'Foundry relationship manager', d:'Shuttle engagement and confirmation'},
    {r:'Test chip lead', d:'Confirms the slot serves the objective'},
    {r:'Procurement', d:'Pricing and purchase authorization'},
    {r:'Physical design lead', d:'Confirms the backward schedule is achievable'},
  ],
  effort:[['Slot booking',0.4], ['Calendar review',0.3], ['Submission schedule',0.3]],
  entry:[
    'Objective and schedule feasibility confirmed by TC-01',
    'Shuttle calendars available',
    'Budget authority for the shuttle cost',
  ],
  exit:[
    'Slot confirmed in writing with a submission date',
    'Submission requirements collected and understood',
    'Backward schedule agreed with physical design',
  ],
  dependsOn:['TC-01','TECH-05','TECH-06'],
  dependsNote:null,
  feedsInto:['TC-02','TC-04','TC-05'],
  measuredBy:[
    'Weeks between slot booking and submission',
    'Submission date against the production decision date',
    'Contingency slot identified',
  ],
},

'TC-04': {
  stage:'testChip', window:[12,24], criticalPath:true,
  purpose:[
    'Implement the test chip physically and <b>sign it off to shuttle submission standard</b>—the same DRC, LVS and antenna closure a production die needs, on a fraction of the schedule.',
    'The vehicle is small and the standard is not reduced. A shuttle rejects a non-compliant database, and the rejection costs the slot. What compresses the schedule is that timing closure is easy here; what does not compress is physical verification, which has to be as clean as production.',
  ],
  steps:[
    {n:1, text:'Floorplan and structure placement', tat:1.5, lane:'main'},
    {n:2, text:'Place and route', tat:2.5, lane:'main'},
    {n:3, text:'Power delivery network for measurement accuracy', tat:2, lane:'par'},
    {n:4, text:'Timing closure on access and control paths', tat:2.5, lane:'main'},
    {n:5, text:'Fill, seal ring and shuttle frame compliance', tat:1.5, lane:'par'},
    {n:6, text:'Physical verification — DRC, antenna, density', tat:3, lane:'main'},
    {n:7, text:'LVS closure', tat:1.5, lane:'par'},
    {n:8, text:'GDS assembly and shuttle submission', tat:2.5, lane:'main'},
  ],
  flowNote:'Step 3 exists because a test chip measures small signals. A power delivery network adequate for function but noisy in the measurement bands turns a characterization result into an argument about the vehicle rather than the device.',
  consumes:[
    'Test chip netlist and structures from TC-02',
    'Submission requirements and date from TC-03',
    'PDK, libraries and decks from PDK-13',
    'Shuttle frame and seal ring rules from the foundry',
    'Measurement accuracy requirements from TC-01',
  ],
  produces:[
    'Floorplan and routed database',
    'Placed and routed shuttle database',
    'Measurement-grade power delivery network',
    'Timing closure results on access and control paths',
    'Fill, seal ring and frame compliance record',
    'Physical verification clean reports',
    'LVS closure record',
    'Shuttle frame compliant GDS',
    'Submission package and record',
  ],
  producedBy:[1,2,3,4,5,6,7,8,8],
  rel:[
    {id:'TC-D2', rel:'produces', text:'<b>Test chip GDS and shuttle submission record.</b> This activity is the deliverable, and the submission record is what proves the slot was met.'},
    {id:'TC-D3', rel:'feeds', text:'<b>Test chip silicon and characterization report.</b> Measurement quality is determined here—a noisy vehicle produces uncertain results.'},
  ],
  risks:[
    '<b>Submission rejected on frame or format compliance.</b> Shuttle frames have their own rules, and a rejection costs the slot rather than a re-run.',
    '<b>PDN adequate for function and inadequate for measurement.</b> The results then carry vehicle noise that cannot be separated from device behavior.',
    '<b>Physical verification compressed because the chip is small.</b> Size does not reduce the standard, and a DRC violation is as fatal here as on a production die.',
    '<b>Structures placed without regard to the measurement plan.</b> Placement affects what across-die variation can be seen, and it is decided here rather than in the lab.',
    '<b>No margin against the submission date.</b> Everything before this activity can slip and this one cannot, so its schedule needs the buffer.',
  ],
  roles:[
    {r:'Test chip physical lead', d:'Owns implementation and submission'},
    {r:'Physical design engineers', d:'Place, route and closure'},
    {r:'Physical verification engineer', d:'DRC, LVS, antenna and frame compliance'},
    {r:'Analog layout engineer', d:'Measurement-grade PDN and shielding'},
    {r:'Program manager', d:'Submission date enforcement'},
  ],
  effort:[['Place and route',5], ['Physical verification',4.5], ['Timing closure',4], ['GDS assembly and submission',2.5], ['Power delivery network',2.5], ['Fill and seal ring',1.5]],
  entry:[
    'Netlist and structures complete from TC-02',
    'Submission date and format requirements from TC-03',
    'Golden environment available from PDK-13',
  ],
  exit:[
    'Database clean against production physical verification standards',
    'Shuttle frame and format compliance confirmed before submission',
    'Submission made on the booked date',
  ],
  dependsOn:['TC-02','TC-03','PDK-13'],
  dependsNote:null,
  feedsInto:['TC-05','TC-07'],
  measuredBy:[
    'Submission accepted at first attempt',
    'Days of margin against the submission date',
    'Measurement-band noise on the PDN',
  ],
},

'TC-05': {
  stage:'testChip', window:[22,38], criticalPath:true,
  purpose:[
    'Wait, visibly—<b>mask, fabricate, dice and deliver</b>—while keeping the program informed about a schedule it has almost no ability to influence.',
    'Sixteen weeks and four man-months. The work here is tracking and logistics rather than engineering, and the value is that the rest of the program knows what date to plan against. A shuttle lot moves for reasons that have nothing to do with this program, and being told late is the avoidable part.',
  ],
  steps:[
    {n:1, text:'Data submission and acceptance confirmation', tat:1, lane:'main'},
    {n:2, text:'Shuttle mask fabrication', tat:4, lane:'main'},
    {n:3, text:'WIP tracking and schedule communication', tat:2, lane:'par'},
    {n:4, text:'Wafer processing', tat:8, lane:'main'},
    {n:5, text:'E-test and PCM data review as it becomes available', tat:1.5, lane:'par'},
    {n:6, text:'Dicing, packaging and delivery', tat:3, lane:'main'},
  ],
  flowNote:'Step 5 matters more than its 1.5 weeks suggest. PCM and e-test data arrives before packaged parts do, and it answers some of the process questions the chip was built for weeks earlier than the lab can.',
  consumes:[
    'Submitted GDS from TC-04',
    'Shuttle slot confirmation from TC-03',
    'Foundry WIP reporting',
    'Packaging requirements from TC-06',
    'Delivery logistics arrangements',
  ],
  produces:[
    'Submission acceptance confirmation',
    'Fabricated shuttle mask set',
    'WIP status reporting against the program schedule',
    'Processed wafers',
    'E-test and PCM data',
    'Packaged test chip parts',
    'Delivery record',
  ],
  producedBy:[1,2,3,4,5,6,6],
  rel:[
    {id:'TC-D3', rel:'feeds', text:'<b>Test chip silicon and characterization report.</b> The silicon itself, plus the PCM data that arrives with it.'},
  ],
  risks:[
    '<b>Shuttle lot slips and the program hears late.</b> The slip cannot be prevented; the surprise can, and the surprise is what damages downstream plans.',
    '<b>Packaging not arranged in advance.</b> Diced die with no package and no socket cannot be measured, and arranging it after delivery adds weeks.',
    '<b>PCM data ignored until parts arrive.</b> Some process questions are answered by e-test alone, weeks earlier and at no additional cost.',
    '<b>Insufficient parts requested.</b> Shuttle quantities are small; a characterization plan needing more parts than were ordered cannot be run.',
    '<b>Logistics and customs not planned.</b> Cross-border shipment of engineering samples carries paperwork that stops parts at a border for weeks.',
  ],
  roles:[
    {r:'Program manager', d:'WIP tracking and schedule communication'},
    {r:'Foundry relationship manager', d:'Lot status and escalation'},
    {r:'Operations planner', d:'Packaging, logistics and delivery'},
    {r:'Device engineer', d:'E-test and PCM data review'},
    {r:'Test chip lead', d:'Confirms part quantities against the characterization plan'},
  ],
  effort:[['WIP tracking and communication',1.5], ['PCM and e-test review',1], ['Submission and acceptance',0.75], ['Logistics and delivery',0.75]],
  entry:[
    'GDS submitted and accepted by the shuttle',
    'Packaging and socket requirements defined by TC-06',
    'Delivery logistics arranged',
  ],
  exit:[
    'Parts delivered in the quantity the characterization plan needs',
    'PCM and e-test data reviewed before parts arrive',
    'Schedule communicated at every status change, not only at delivery',
  ],
  dependsOn:['TC-03','TC-04'],
  dependsNote:null,
  feedsInto:['TC-07'],
  measuredBy:[
    'Delivery date against the forecast at submission',
    'Parts delivered against parts planned',
    'Days between a lot status change and the program hearing about it',
  ],
},

'TC-06': {
  stage:'testChip', window:[24,33], criticalPath:false,
  purpose:[
    'Have the <b>board, sockets, instruments and automation ready before the parts arrive</b>, so that characterization starts on the day of delivery rather than six weeks later.',
    'This is the small-scale version of the same mistake the production program makes with EVB. Parts arriving into a lab with no board is a delay that consumes the schedule advantage the test chip was supposed to buy, and it is entirely avoidable by starting during fabrication.',
  ],
  steps:[
    {n:1, text:'Measurement requirement definition from the coverage matrix', tat:1, lane:'main'},
    {n:2, text:'Board design — supplies, bias, measurement paths', tat:2.5, lane:'main'},
    {n:3, text:'Socket or probe card selection and lead time', tat:1.5, lane:'par'},
    {n:4, text:'Board fabrication and assembly', tat:2.5, lane:'main'},
    {n:5, text:'Measurement automation and data capture scripting', tat:1.5, lane:'par'},
    {n:6, text:'Board bring-up and instrument setup', tat:3, lane:'main'},
  ],
  flowNote:'Step 3 has a lead time that can exceed the whole activity. Sockets for an unusual package are made to order, and a socket ordered when the parts ship arrives after they do.',
  consumes:[
    'Coverage matrix and measurement plan from TC-01',
    'Pad assignment and access modes from TC-02',
    'Package and die dimensions from TC-05',
    'Lab instrument availability',
    'Measurement accuracy requirements',
  ],
  produces:[
    'Measurement requirement specification',
    'Test chip board design and assembled boards',
    'Socket or probe card',
    'Fabricated and assembled test boards',
    'Measurement automation and capture scripts',
    'Bring-up record and instrument setup',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'TC-D3', rel:'feeds', text:'<b>Test chip silicon and characterization report.</b> The measurement quality the report can claim is bounded by the board and the automation built here.'},
  ],
  risks:[
    '<b>Board started when parts ship.</b> The lab then waits, and the schedule advantage the test chip existed to buy is spent waiting for a PCB.',
    '<b>Socket lead time discovered late.</b> Custom sockets are made to order and can take longer than the board itself.',
    '<b>Measurement automation deferred.</b> Manual measurement of a full characterization matrix is slow enough to consume the window and inconsistent enough to weaken the data.',
    '<b>Board noise floor above the signal of interest.</b> A board adequate for function cannot measure a low-jitter clock or a small offset, and the limitation is found with the parts in hand.',
    '<b>Instruments not reserved.</b> A shared high-end instrument booked by another program stops characterization as effectively as a missing board.',
  ],
  roles:[
    {r:'Characterization engineer', d:'Owns the measurement setup and automation'},
    {r:'Board designer', d:'Test chip board design and bring-up'},
    {r:'Lab manager', d:'Instrument reservation and socket procurement'},
    {r:'Test chip lead', d:'Confirms the setup covers the matrix'},
    {r:'Analog designer', d:'Measurement path accuracy requirements'},
  ],
  effort:[['Board design',2.5], ['Bring-up and instrument setup',2], ['Measurement automation',1.5], ['Board fabrication',1], ['Socket procurement',1]],
  entry:[
    'Coverage matrix and measurement plan available from TC-01',
    'Pad assignment fixed by TC-02',
    'Package format known from TC-05',
  ],
  exit:[
    'Board bring-up complete before parts are delivered',
    'Sockets in hand, not on order',
    'Automation able to run the matrix without manual steps',
  ],
  dependsOn:['TC-01','TC-02'],
  dependsNote:null,
  feedsInto:['TC-07','EVB-01'],
  measuredBy:[
    'Days between part delivery and first measurement',
    'Board noise floor against the smallest signal of interest',
    'Matrix points automated against total',
  ],
},

'TC-07': {
  stage:'testChip', window:[28,40], criticalPath:true,
  purpose:[
    'Measure the silicon and <b>correlate it against the models the production design is being built on</b>—which is the only reason the chip exists.',
    'Characterization without correlation produces a data set. Correlation produces a statement of the form "the model is optimistic by 8% on this parameter at this corner", and that statement is what <code>TC-08</code> converts into margin decisions the production design can act on.',
  ],
  steps:[
    {n:1, text:'Incoming inspection and basic functionality check', tat:1.5, lane:'main'},
    {n:2, text:'IP-under-test characterization across the matrix', tat:3, lane:'main'},
    {n:3, text:'Ring oscillator frequency and leakage measurement', tat:2.5, lane:'par'},
    {n:4, text:'PCM and device parameter extraction', tat:3, lane:'main'},
    {n:5, text:'Corner correlation setup against simulation', tat:2, lane:'par'},
    {n:6, text:'Across-wafer and lot-to-lot variability analysis', tat:2, lane:'main'},
    {n:7, text:'Failure analysis on outliers', tat:1.5, lane:'par'},
    {n:8, text:'Correlation results assembly', tat:2.5, lane:'main'},
  ],
  flowNote:'This window overlaps the tail of fabrication because the stage as templated does not allow a clean sequence—PCM and e-test data are worked first, and device characterization follows once packaged parts arrive. It is worth noting that the stage\'s forty weeks are tight for its own chain.',
  consumes:[
    'Packaged parts and PCM data from TC-05',
    'Measurement setup from TC-06',
    'Coverage matrix from TC-01',
    'Simulation results the models predicted',
    'Foundry PCM reference data',
  ],
  produces:[
    'Incoming inspection and functionality results',
    'Functional and characterization results per structure',
    'Ring oscillator and leakage measurements',
    'Extracted device parameters',
    'Corner correlation setup',
    'Variability analysis across wafer and lot',
    'Failure analysis findings',
    'Silicon-to-model correlation results',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TC-D3', rel:'produces', text:'<b>Test chip silicon and characterization report.</b> The measurement half of the deliverable.'},
    {id:'TC-D4', rel:'produces', text:'<b>Silicon-to-model correlation report.</b> The half that makes the measurements actionable—a delta against what was predicted, per parameter and corner.'},
  ],
  risks:[
    '<b>Characterization without correlation.</b> A data set with no comparison to prediction cannot change a design decision, and changing decisions was the point.',
    '<b>Sample size too small for variability.</b> Across-wafer and lot-to-lot variation is often the question, and a handful of parts cannot answer it.',
    '<b>Measurement uncertainty larger than the effect.</b> A correlation claim that sits inside the measurement error is not a finding.',
    '<b>Outliers discarded.</b> The parts that behave unexpectedly are usually the informative ones, and discarding them removes the tail the yield model depends on.',
    '<b>Results delivered too late for TC-08.</b> Correlation completed after the production design has committed is a report nobody can act on.',
  ],
  roles:[
    {r:'Characterization engineer', d:'Owns the measurements and the data quality'},
    {r:'Device engineer', d:'PCM extraction and process parameter analysis'},
    {r:'Analog designers', d:'IP-under-test interpretation against simulation'},
    {r:'Modeling engineer', d:'Correlation setup and delta analysis'},
    {r:'Failure analysis engineer', d:'Outlier investigation'},
  ],
  effort:[['IP-under-test characterization',6], ['PCM and device extraction',4], ['Ring oscillator measurement',3], ['Variability analysis',3], ['Correlation assembly',2], ['Failure analysis',2]],
  entry:[
    'Parts delivered from TC-05',
    'Measurement setup ready from TC-06',
    'Simulation predictions available for comparison',
  ],
  exit:[
    'Every measured parameter compared against its prediction',
    'Measurement uncertainty stated alongside each correlation claim',
    'Results delivered with time for TC-08 to act',
  ],
  dependsOn:['TC-01','TC-02','TC-04','TC-05','TC-06'],
  dependsNote:null,
  feedsInto:['TC-08','AMS-13','PDK-03','SO-10'],
  measuredBy:[
    'Parameters correlated against parameters measured',
    'Measurement uncertainty against effect size',
    'Parts characterized against the sample size the plan required',
  ],
},

'TC-08': {
  stage:'testChip', window:[34,40], criticalPath:true,
  purpose:[
    'Convert correlation findings into <b>changes the production design actually makes</b>—corrected models, revised margins, methodology updates—and track that they were adopted.',
    'This is where a test chip earns or wastes its cost. A correlation report that circulates and changes nothing has bought an expensive confirmation of what everyone assumed. The output has to be specific: this model corrected by this factor, this margin increased by this amount, owned by this person, adopted by this date.',
  ],
  steps:[
    {n:1, text:'Correlation gap analysis — where model and silicon disagree', tat:1, lane:'main'},
    {n:2, text:'Model correction and re-characterization requests', tat:1.5, lane:'main'},
    {n:3, text:'Design rule and methodology update proposals', tat:1, lane:'par'},
    {n:4, text:'Margin decisions for the production design', tat:1.5, lane:'main'},
    {n:5, text:'Production design change requests', tat:1, lane:'par'},
    {n:6, text:'Guidance publication and adoption tracking', tat:2, lane:'main'},
  ],
  flowNote:'Step 6 is the one that distinguishes a useful test chip from an expensive one. Publishing guidance is easy; tracking that physical design actually changed its margin and that the model was actually re-characterized is what turns the finding into a change.',
  consumes:[
    'Correlation results from TC-07',
    'Production design status and open margins',
    'Model and library data from PDK-03',
    'AMS post-layout results from AMS-13',
    'Production design change control process from RTL-10',
  ],
  produces:[
    'Correlation gap analysis',
    'Model correction requests and re-characterization scope',
    'Methodology and rule update proposals',
    'Margin decisions for the production design',
    'Production design change requests',
    'Adoption tracking record',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'TC-D5', rel:'produces', text:'<b>Design guidance and margin decisions for the production chip.</b> This activity is the deliverable, and adoption tracking is what makes it more than a report.'},
    {id:'TC-D4', rel:'feeds', text:'<b>Silicon-to-model correlation report.</b> The gap analysis is published with the correlation, so the finding and its consequence stay together.'},
  ],
  risks:[
    '<b>Guidance published and not adopted.</b> The most common way a test chip wastes its cost: everyone reads the report and nobody changes a margin.',
    '<b>Findings arrive after the design has committed.</b> A margin decision for a block that has already closed is a decision that cannot be taken.',
    '<b>Model corrections requested but not scheduled.</b> Re-characterization is work; a correction with no owner and no date does not happen.',
    '<b>Only bad news acted on.</b> Where silicon is better than the model, the margin released is real and usually left on the table.',
    '<b>Guidance stated as observation.</b> "Leakage is higher than modelled" is not actionable; "increase the leakage budget for the compute cluster by 12%" is.',
  ],
  roles:[
    {r:'Test chip lead', d:'Owns the guidance and its adoption tracking'},
    {r:'Modeling and library engineers', d:'Model corrections and re-characterization'},
    {r:'PPA lead', d:'Margin decisions against the production budgets'},
    {r:'Physical design lead', d:'Adopts margin changes into closure'},
    {r:'Program manager', d:'Change requests through the ECO board'},
  ],
  effort:[['Model correction',2.5], ['Margin decisions',2], ['Gap analysis',1.5], ['Guidance and adoption tracking',1], ['Change requests',1]],
  entry:[
    'Correlation results available from TC-07',
    'Production design status known well enough to act on',
    'Change control process available from RTL-10',
  ],
  exit:[
    'Every finding converted into a specific, owned action',
    'Margin released where silicon beat the model, not only tightened where it did not',
    'Adoption tracked to completion, not just published',
  ],
  dependsOn:['TC-07'],
  dependsNote:null,
  feedsInto:['PDK-03','AMS-13','PD-09','SO-10','DEF-04'],
  measuredBy:[
    'Findings converted into owned actions',
    'Actions adopted against actions raised',
    'Margin released where silicon outperformed the model',
  ],
},

};
