/* TECH — Technology & Foundry Selection. Nine activities. Stage w0–14 (14w), 26 M/M.
   Low effort, long elapsed time: most of the calendar here belongs to the foundry. */
module.exports = {

'TECH-01': {
  stage:'technology', window:[0,5], criticalPath:true,
  purpose:[
    'Narrow the field of foundries and nodes to a short-list the program can actually evaluate, and <b>record why the others were dropped</b>.',
    'Every other decision in this stage is conditional on this one, and so is most of the enablement band: IP availability, PDK maturity, library qualification and capacity all become node-specific the moment the short-list closes. The screen has to be quick and it has to be written down—a selection nobody can reconstruct is one that gets reopened at every setback.',
  ],
  steps:[
    {n:1, text:'Long-list construction — foundries, nodes and their availability windows', tat:0.75, lane:'main'},
    {n:2, text:'Screening criteria weighted against the product requirements', tat:0.5, lane:'main'},
    {n:3, text:'Foundry engagement and formal information requests', tat:1.5, lane:'main'},
    {n:4, text:'Previous-program experience and relationship review', tat:0.5, lane:'par'},
    {n:5, text:'Geopolitical, export-control and supply-continuity screen', tat:0.75, lane:'par'},
    {n:6, text:'Short-list down to two or three candidates', tat:1, lane:'main'},
    {n:7, text:'Selection recommendation and decision record', tat:1.25, lane:'main'},
  ],
  flowNote:'Step 3 is the pacing item and almost none of it is our work—information requests sit with the foundry\'s technical marketing team, and the response time is theirs. Starting the engagement in week one is the only lever the program has over it.',
  consumes:[
    'Product requirements and PPA targets from DEF-01 and DEF-03',
    'Volume forecast and cost ceiling from the business case',
    'Foundry public roadmaps and node cadence',
    'Previous-program experience with each foundry',
    'Export control and supply-continuity guidance',
  ],
  produces:[
    'Foundry and node long-list with availability windows',
    'Weighted screening criteria',
    'Foundry information request responses',
    'Previous-program experience review',
    'Screening record — what was dropped and why',
    'Short-list of two or three candidates',
    'Selection recommendation and decision record',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'TECH-D1', rel:'produces', text:'<b>Technology selection report and decision record.</b> This activity owns the deliverable; <code>TECH-03</code> supplies the technical evidence it rests on.'},
    {id:'TECH-D6', rel:'feeds', text:'<b>Node risk assessment.</b> The supply-continuity and geopolitical screen is one of the risk assessment\'s inputs, and it is gathered here.'},
  ],
  risks:[
    '<b>Short-list of one.</b> A screen that arrives at a single candidate has no negotiating position on price, capacity or terms, and the foundry knows it.',
    '<b>Selection driven by relationship.</b> The foundry the last program used is a legitimate input and a poor criterion; making it the criterion means the screen was theatre.',
    '<b>Availability window not checked.</b> A node that is right for the product but reaches risk production after the tapeout date is not a candidate, however good the numbers are.',
    '<b>Export control screened late.</b> A candidate that fails compliance after technical evaluation has consumed weeks of the stage for nothing.',
    '<b>Criteria written after the data arrives.</b> Weighting the screen once the responses are in produces the answer somebody already wanted.',
  ],
  roles:[
    {r:'Technology strategist', d:'Owns the screen, the short-list and the recommendation'},
    {r:'Foundry relationship manager', d:'Engagement and information requests'},
    {r:'Program manager', d:'Availability windows against the program schedule'},
    {r:'Compliance liaison', d:'Export control and supply-continuity screen'},
    {r:'Chief architect', d:'Confirms the criteria reflect what the product needs'},
  ],
  effort:[['Foundry engagement',1.25], ['Screening criteria and long-list',0.75], ['Short-listing',0.75], ['Continuity and compliance screen',0.5], ['Decision record',0.75]],
  entry:[
    'Product requirements and PPA targets available at draft quality',
    'Volume forecast good enough to discuss with a foundry',
    'Legal cover in place for preliminary discussion',
  ],
  exit:[
    'Short-list of at least two candidates, with the dropped options recorded',
    'Criteria weighted before the responses were read',
    'Recommendation carries availability windows, not only technical fit',
  ],
  dependsOn:['DEF-01'],
  dependsNote:null,
  feedsInto:['TECH-02','TECH-03','TECH-06','TECH-07','DEF-07','IPR-05','PDK-01'],
  measuredBy:[
    'Candidates carried to short-list against those screened',
    'Weeks from first engagement to short-list',
    'Selection reopened after the decision record',
  ],
},

'TECH-02': {
  stage:'technology', window:[4,9], criticalPath:true,
  purpose:[
    'Choose the <b>flavor of the node</b>, not just the node—performance or density library, the multi-Vt menu, the metal stack, backside power delivery, and any analog or high-voltage adders the product needs.',
    'A node name is not a specification. Two programs on the same node with different flavor sheets get different density, different leakage and different routing resource, and the difference is larger than most architectural decisions. This sheet is also what the foundry prices against, so it has to close before <code>TECH-04</code> can finish.',
  ],
  steps:[
    {n:1, text:'Process flavor options against the PPA targets — HPC, HD, or mixed', tat:1, lane:'main'},
    {n:2, text:'Multi-Vt menu selection and its leakage implication', tat:1, lane:'main'},
    {n:3, text:'Backside power delivery evaluation, where the node offers it', tat:0.75, lane:'par'},
    {n:4, text:'RF, high-voltage and analog adder requirements', tat:0.5, lane:'par'},
    {n:5, text:'Metal stack selection and routing resource implication', tat:1, lane:'main'},
    {n:6, text:'Option cost adders priced with TECH-04', tat:0.5, lane:'par'},
    {n:7, text:'Flavor sheet agreement with the foundry', tat:2, lane:'main'},
  ],
  flowNote:'Two of the five weeks sit in step 7, which is signature time rather than engineering time. The sheet is a contractual artifact: once agreed it governs what the PDK contains and what the wafer costs, and changing it later reopens both.',
  consumes:[
    'Short-list from TECH-01',
    'PPA targets from DEF-03',
    'DTCO findings as they emerge from TECH-03',
    'Reticle and die size direction from ARCH-02',
    'Analog and PHY requirements from ARCH-04',
  ],
  produces:[
    'Flavor option comparison against the PPA targets',
    'Multi-Vt menu selection with leakage projection',
    'Backside power delivery evaluation',
    'Analog, RF and high-voltage adder list',
    'Metal stack selection and routing resource note',
    'Priced option adders',
    'Process option / flavor sheet agreed with the foundry',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'TECH-D2', rel:'produces', text:'<b>Process option / flavor sheet agreed with foundry.</b> This activity is the deliverable, and it is contractual rather than advisory.'},
    {id:'TECH-D3', rel:'feeds', text:'<b>Wafer, mask and NRE cost sheet.</b> Every option on the sheet carries a price adder, so the flavor decides a meaningful part of the wafer cost.'},
    {id:'TECH-D1', rel:'feeds', text:'<b>Technology selection report.</b> The selection is only complete when the flavor is named—a node without a flavor sheet is not a selection anyone can build on.'},
  ],
  risks:[
    '<b>Flavor chosen for density alone.</b> A high-density library that cannot reach the frequency target trades an area saving for a performance failure, and the trade is discovered at trial synthesis.',
    '<b>Metal stack chosen without a congestion study.</b> Too few routing layers is the defect that surfaces at <code>PD-06</code>, when the only remaining fix is a floorplan change.',
    '<b>Multi-Vt menu wider than the flow supports.</b> Every extra Vt is a library to characterize, qualify and maintain; menus are chosen for leakage and paid for in methodology.',
    '<b>Backside power taken for the roadmap.</b> A first-generation backside PDN buys power integrity and costs schedule risk, and the trade belongs to this product rather than the next one.',
    '<b>Adders discovered after the sheet is agreed.</b> An analog or high-voltage requirement that arrives late is a sheet amendment, a price change and a PDK delta at once.',
  ],
  roles:[
    {r:'Technology strategist', d:'Owns the flavor sheet and its agreement'},
    {r:'Library and CAD lead', d:'Multi-Vt menu and library implications'},
    {r:'Physical design liaison', d:'Metal stack and routing resource'},
    {r:'Analog lead', d:'RF, high-voltage and analog adder requirements'},
    {r:'Foundry technical account manager', d:'Availability of each option on the node'},
  ],
  effort:[['Flavor and Vt studies',1.5], ['Metal stack selection',0.75], ['Backside PDN and adder evaluation',0.75], ['Sheet agreement',1]],
  entry:[
    'Short-list closed by TECH-01',
    'PPA targets published by DEF-03',
    'Early DTCO results available from TECH-03',
  ],
  exit:[
    'Flavor sheet agreed and signed, not merely discussed',
    'Metal stack backed by a congestion study rather than by precedent',
    'Every analog and adder requirement captured before agreement',
  ],
  dependsOn:['TECH-01','DEF-03'],
  dependsNote:null,
  feedsInto:['TECH-04','PDK-02','PDK-03','PDK-04','SYN-02','PD-06'],
  measuredBy:[
    'Options on the sheet against those the design actually uses',
    'Sheet amendments raised after agreement',
    'Routing layers against the congestion study\'s recommendation',
  ],
},

'TECH-03': {
  stage:'technology', window:[3,10], criticalPath:true,
  purpose:[
    'Measure the candidate nodes against <b>this product\'s targets</b> rather than against the foundry\'s brochure—density, achievable frequency, leakage, SRAM Vmin and routing resource, on circuits that resemble the design.',
    'This is the technical evidence the selection stands on. Published node comparisons are made on somebody else\'s circuits at somebody else\'s operating point; a DTCO study run on representative structures is the only way to know whether the PPA targets survive the node, and it is what <code>DEF-07</code> tests feasibility against.',
  ],
  steps:[
    {n:1, text:'Benchmark circuit set definition, representative of the design', tat:0.75, lane:'main'},
    {n:2, text:'Standard cell density and area scaling study', tat:1.5, lane:'main'},
    {n:3, text:'Ring oscillator and critical-path frequency study', tat:1.5, lane:'main'},
    {n:4, text:'Leakage and dynamic power characterization across the Vt menu', tat:1.25, lane:'par'},
    {n:5, text:'SRAM bitcell density and Vmin study', tat:1.25, lane:'par'},
    {n:6, text:'Routing congestion proxy study on the candidate metal stacks', tat:1, lane:'par'},
    {n:7, text:'Node comparison against the DEF-03 targets', tat:1.5, lane:'main'},
    {n:8, text:'DTCO findings and recommendation', tat:1.75, lane:'main'},
  ],
  flowNote:'Three of the eight steps run in parallel because they use different data and different people—power characterization, SRAM and congestion are separable studies. What cannot be parallelized is step 7: comparison needs all three to have landed.',
  consumes:[
    'Short-list from TECH-01',
    'PPA targets from DEF-03',
    'Foundry-supplied preliminary libraries and models',
    'Previous-generation design as a benchmark reference',
    'Memory compiler capability indications',
  ],
  produces:[
    'Benchmark circuit set and its rationale',
    'Density and area scaling results per node',
    'Ring oscillator and critical-path frequency study',
    'Frequency and leakage characterization per Vt',
    'SRAM density and Vmin findings',
    'Routing congestion proxy results',
    'Node comparison against the PPA targets',
    'DTCO findings and node recommendation',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TECH-D1', rel:'feeds', text:'<b>Technology selection report and decision record.</b> The evidence half of the report—<code>TECH-01</code> records the decision, this activity is why the decision is defensible.'},
    {id:'TECH-D6', rel:'feeds', text:'<b>Node risk assessment.</b> Where a target is only just met, this study is what says so, and that margin is a node risk.'},
    {id:'TECH-D2', rel:'feeds', text:'<b>Process option / flavor sheet.</b> The Vt menu and metal stack on the sheet are chosen from these results.'},
  ],
  risks:[
    '<b>Benchmark circuits unrepresentative.</b> A study run on ring oscillators alone measures the node and not the design; the answer is precise and irrelevant.',
    '<b>Preliminary libraries treated as final.</b> Early PDK models move, sometimes by more than the difference between the candidates, and a comparison made on 0.5 data can invert.',
    '<b>SRAM left out.</b> On an accelerator the array is a large fraction of the die; a node comparison without a bitcell and Vmin study has skipped the dominant area and the dominant Vmin constraint.',
    '<b>Congestion never modelled.</b> Density that cannot be routed is not density, and the routing resource question is decided by the metal stack chosen in <code>TECH-02</code>.',
    '<b>Results reported without margin.</b> A target met exactly in a DTCO study will not be met in implementation, and reporting the number without the margin invites the wrong conclusion.',
  ],
  roles:[
    {r:'DTCO lead', d:'Owns the study, its circuits and its findings'},
    {r:'Library characterization engineer', d:'Density, frequency and leakage measurement'},
    {r:'Memory design liaison', d:'SRAM bitcell density and Vmin study'},
    {r:'Physical design liaison', d:'Congestion proxy and routing resource'},
    {r:'Foundry technical contact', d:'Preliminary models, decks and interpretation'},
  ],
  effort:[['Density and frequency studies',2], ['Leakage and SRAM characterization',1.5], ['Node comparison',1], ['Congestion proxy study',0.75], ['Findings and recommendation',0.75]],
  entry:[
    'Short-list available from TECH-01',
    'Preliminary libraries released under NDA',
    'PPA targets published by DEF-03',
  ],
  exit:[
    'Every target has a measured result per candidate node',
    'Findings state margin, not only pass or fail',
    'Benchmark set documented well enough to re-run on a later PDK',
  ],
  dependsOn:['TECH-01','DEF-03'],
  dependsNote:null,
  feedsInto:['TECH-02','TECH-07','DEF-03','DEF-07','PDK-03','ARCH-01'],
  measuredBy:[
    'Targets measured against targets asserted',
    'Margin reported on each met target',
    'Findings later contradicted by trial synthesis',
  ],
},

'TECH-04': {
  stage:'technology', window:[5,11], criticalPath:false,
  purpose:[
    'Put a <b>price on the technology</b>—wafers at the forecast volume, the mask set, the NRE, the MPW shuttle, and every adder the flavor sheet carries—and hand it to the cost model as quotations rather than estimates.',
    'The cost model in <code>DEF-04</code> is only as good as this activity. A model built on published estimates produces a margin nobody can defend at the funding gate; a model built on quotations produces one that survives the first conversation with finance.',
  ],
  steps:[
    {n:1, text:'Volume and wafer-start forecast from the business case', tat:0.5, lane:'main'},
    {n:2, text:'Wafer price request and negotiation', tat:2, lane:'main'},
    {n:3, text:'Mask set and NRE quotation per node and flavor', tat:1.5, lane:'par'},
    {n:4, text:'MPW shuttle pricing and slot cost', tat:0.5, lane:'par'},
    {n:5, text:'Option adder pricing against the TECH-02 sheet', tat:0.5, lane:'par'},
    {n:6, text:'Volume tier and price-break structure', tat:2.5, lane:'main'},
    {n:7, text:'Cost sheet publication into the DEF-04 model', tat:1, lane:'main'},
  ],
  flowNote:'The tier structure in step 6 is worth more than the headline price. A wafer price that only applies above a volume the product will not reach in its first year is a price the cost model should not be using.',
  consumes:[
    'Short-list and flavor sheet from TECH-01 and TECH-02',
    'Volume forecast and ramp profile from the business case',
    'Die size estimate from DEF-04',
    'Mask layer count implied by the metal stack',
    'MPW shuttle calendar from the foundry',
  ],
  produces:[
    'Volume and wafer-start forecast',
    'Wafer price quotations per foundry',
    'Mask set and NRE quotation per candidate',
    'MPW shuttle pricing and slot cost',
    'Option adder pricing',
    'Wafer price quotation with tier structure',
    'Cost sheet published into the DEF-04 model',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'TECH-D3', rel:'produces', text:'<b>Wafer, mask and NRE cost sheet.</b> This activity is the deliverable, and its value is that the numbers are quoted rather than estimated.'},
    {id:'TECH-D1', rel:'feeds', text:'<b>Technology selection report.</b> Cost is a selection criterion; a node that wins on PPA and loses on price is a decision, not a formality.'},
  ],
  risks:[
    '<b>Price quoted at a volume the product will not reach.</b> Tier structures are where the real cost lives, and a headline price at ten times the forecast volume is a number the model should reject.',
    '<b>Mask cost estimated from layer count alone.</b> EUV layers dominate mask cost, and the count of them depends on the flavor sheet rather than on the total layer count.',
    '<b>Adders priced after the sheet is agreed.</b> Once <code>TECH-02</code> closes, the adders are committed; pricing them afterwards removes the option of dropping one.',
    '<b>Currency and term exposure ignored.</b> A quotation with no validity period or currency term is not a quotation the cost model can carry to a funding gate.',
    '<b>Second-source pricing never requested.</b> Without a comparison the negotiation has no floor, and the first price is the last price.',
  ],
  roles:[
    {r:'Procurement lead', d:'Owns the negotiation and the quotations'},
    {r:'Product cost analyst', d:'Feeds the sheet into the DEF-04 model'},
    {r:'Technology strategist', d:'Confirms what each adder buys technically'},
    {r:'Finance partner', d:'Currency, validity and term treatment'},
    {r:'Program manager', d:'Volume and ramp profile assumptions'},
  ],
  effort:[['Price negotiation',1.25], ['Mask, NRE and shuttle quotations',0.75], ['Tier structure',0.5], ['Publication into the cost model',0.5]],
  entry:[
    'Short-list closed and flavor options known',
    'Volume forecast agreed with sales and finance',
    'Die size estimate available from DEF-04',
  ],
  exit:[
    'Every cost line quoted, with a validity period and currency term',
    'Tier structure reflects the actual ramp, not a notional volume',
    'Cost sheet loaded into the DEF-04 model, not summarized into it',
  ],
  dependsOn:['TECH-01','TECH-02','DEF-04'],
  dependsNote:null,
  feedsInto:['DEF-04','DEF-07','DEF-09','TC-03','MP-10'],
  measuredBy:[
    'Cost lines backed by a quotation rather than an estimate',
    'Quoted price against the tier the program will actually reach',
    'Cost sheet revisions after the funding gate',
  ],
},

'TECH-05': {
  stage:'technology', window:[8,13], criticalPath:false,
  purpose:[
    'Convert the program\'s schedule into <b>reserved fab capacity</b>—a wafer-start profile, a tapeout slot, hot-lot terms and an engineering-lot allocation—and get it committed in writing.',
    'Capacity is not bought at tapeout; it is reserved a year before, against a date that will move. The commitment matters most in its escalation path: when the schedule slips or the market tightens, what the program has is whatever was written down, and a verbal understanding is worth exactly nothing at that moment.',
  ],
  steps:[
    {n:1, text:'Wafer-start profile derived from the program schedule', tat:0.5, lane:'main'},
    {n:2, text:'Capacity request and allocation discussion', tat:1.5, lane:'main'},
    {n:3, text:'Tapeout slot reservation against the DEF-08 date', tat:1, lane:'main'},
    {n:4, text:'Hot-lot policy and priority terms', tat:1, lane:'par'},
    {n:5, text:'Engineering-lot and risk-wafer allocation', tat:0.75, lane:'par'},
    {n:6, text:'Capacity commitment letter and escalation path', tat:2, lane:'main'},
  ],
  flowNote:'Steps 4 and 5 look like details and behave like insurance. Hot-lot priority is what turns an 18-week fab cycle into an 11-week one at <code>FAB-04</code>, and it is only available to programs that negotiated it before they needed it.',
  consumes:[
    'Program schedule and tapeout date from DEF-08',
    'Wafer volume forecast and ramp profile',
    'Foundry capacity availability at the node',
    'Hot-lot policy terms offered by the foundry',
    'Engineering and risk-lot requirements from the test plan',
  ],
  produces:[
    'Wafer-start profile against the program schedule',
    'Capacity allocation agreement',
    'Tapeout slot reservation',
    'Hot-lot policy and priority terms',
    'Engineering and risk-lot allocation',
    'Capacity commitment letter with an escalation path',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'TECH-D5', rel:'produces', text:'<b>Capacity and tapeout slot commitment.</b> This activity is the deliverable, and it is worth only as much as the escalation path written into it.'},
    {id:'TECH-D3', rel:'informs', text:'<b>Wafer, mask and NRE cost sheet.</b> Committed volume is what the price tier is granted against, so the two documents have to agree.'},
  ],
  risks:[
    '<b>Slot reserved against a date that has not been committed.</b> A tapeout slot booked against an optimistic schedule is a slot that will be missed and re-queued behind whoever is ready.',
    '<b>Hot-lot terms left informal.</b> Priority granted by relationship evaporates when a larger customer needs the same capacity in the same week.',
    '<b>No escalation path.</b> A commitment with no named escalation contact is a commitment enforced by goodwill, which is not a mechanism.',
    '<b>Engineering lots forgotten.</b> Test-program development and characterization need silicon before the production ramp, and those wafers have to be allocated separately.',
    '<b>Capacity sized to the base case only.</b> An upside scenario the fab cannot supply is a revenue forecast the program cannot deliver on.',
  ],
  roles:[
    {r:'Foundry relationship manager', d:'Owns the capacity negotiation and the commitment'},
    {r:'Program manager', d:'Wafer-start profile and tapeout date'},
    {r:'Operations planner', d:'Ramp profile and engineering-lot needs'},
    {r:'Procurement lead', d:'Contractual terms and escalation path'},
    {r:'Product engineering liaison', d:'Risk-wafer and characterization requirements'},
  ],
  effort:[['Capacity allocation discussion',0.75], ['Tapeout slot reservation',0.5], ['Hot-lot and engineering-lot terms',0.5], ['Commitment letter',0.25]],
  entry:[
    'Program schedule dated by DEF-08',
    'Volume and ramp forecast agreed',
    'Design agreement executed or in final redline',
  ],
  exit:[
    'Capacity committed in writing, with an escalation contact named',
    'Hot-lot terms explicit rather than understood',
    'Engineering and risk lots allocated separately from production',
  ],
  dependsOn:['TECH-01','TECH-06','DEF-08'],
  dependsNote:null,
  feedsInto:['TO-07','FAB-02','FAB-09','TC-03','MP-10'],
  measuredBy:[
    'Capacity committed against capacity requested',
    'Weeks of hot-lot priority secured',
    'Slot date against the DEF-08 tapeout date',
  ],
},

'TECH-06': {
  stage:'technology', window:[2,10], criticalPath:true,
  purpose:[
    'Put the <b>legal frame</b> in place that everything technical depends on—NDA, design agreement, PDK and library licensing, the foundry IP frame, and liability terms—and execute it.',
    'This is the longest activity in the stage at eight weeks and one of the smallest at 2 M/M, which is exactly the shape it should have: the elapsed time belongs to two legal departments and almost none of the work belongs to the program. It is on the critical path anyway, because production PDK access, memory compilers and foundry IP all sit behind the design agreement.',
  ],
  steps:[
    {n:1, text:'NDA execution, to open technical discussion', tat:1, lane:'main'},
    {n:2, text:'Design agreement scope definition', tat:1, lane:'main'},
    {n:3, text:'PDK and library licensing terms', tat:1.5, lane:'par'},
    {n:4, text:'Foundry IP licensing frame — memory compilers, IO, PHY', tat:2.5, lane:'main'},
    {n:5, text:'Liability, indemnity and yield-responsibility terms', tat:1.5, lane:'par'},
    {n:6, text:'Export control and compliance review', tat:1, lane:'par'},
    {n:7, text:'Legal negotiation and redline cycles', tat:2.5, lane:'main'},
    {n:8, text:'Execution and distribution to the teams that need it', tat:1, lane:'main'},
  ],
  flowNote:'Step 1 is deliberately first and deliberately short. Nothing technical can be discussed before the NDA executes, so every week it takes is a week subtracted from <code>TECH-03</code>—which is why the NDA is chased separately from the agreement it precedes.',
  consumes:[
    'Short-list from TECH-01',
    'Corporate legal templates and negotiation positions',
    'Foundry standard agreement terms',
    'Export control and compliance guidance',
    'IP requirements from ARCH-04 and IPR-01',
  ],
  produces:[
    'Executed NDA',
    'Design agreement, scoped and executed',
    'PDK and library license terms',
    'Foundry IP licensing frame',
    'Agreed liability, indemnity and yield-responsibility terms',
    'Compliance and export-control record',
    'Redline history with resolved positions',
    'Distribution record — who is covered to access what',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TECH-D4', rel:'produces', text:'<b>Executed foundry design agreement (DA) and NDA.</b> This activity is the deliverable, and until it executes the enablement band cannot legally start.'},
    {id:'TECH-D5', rel:'feeds', text:'<b>Capacity and tapeout slot commitment.</b> Capacity is committed under the design agreement; the commitment has no standing without it.'},
  ],
  risks:[
    '<b>NDA treated as a formality and queued behind the agreement.</b> Technical evaluation is blocked until it executes, and every week lost here is taken out of the DTCO study.',
    '<b>Foundry IP frame left out of scope.</b> Memory compilers and IO libraries are licensed separately from the PDK; discovering that at <code>PDK-04</code> stops library qualification.',
    '<b>Distribution not tracked.</b> An executed agreement nobody circulated leaves engineers unable to download the PDK they are waiting for, and the delay looks technical.',
    '<b>Yield responsibility left ambiguous.</b> Who owns a process excursion is a term, not a conversation to have after it happens.',
    '<b>Redline cycles unbudgeted.</b> Two legal departments will take longer than either forecasts, and the program\'s plan should assume the longer number.',
  ],
  roles:[
    {r:'Legal counsel', d:'Owns the agreements and the negotiation'},
    {r:'Foundry relationship manager', d:'Drives the redline cycles to closure'},
    {r:'Procurement lead', d:'Commercial terms and licensing scope'},
    {r:'CAD and methodology lead', d:'States what PDK and library access is needed'},
    {r:'Compliance officer', d:'Export control and regulatory review'},
  ],
  effort:[['Negotiation support',0.75], ['IP and licensing frame',0.5], ['Terms review',0.5], ['Execution and distribution',0.25]],
  entry:[
    'Short-list narrow enough to engage legally',
    'Corporate legal position and templates available',
    'Compliance guidance for the candidate foundries',
  ],
  exit:[
    'NDA and design agreement executed, not merely agreed',
    'PDK, library and foundry IP access all covered by scope',
    'Access distributed to the teams that need it, and tracked',
  ],
  dependsOn:['TECH-01'],
  dependsNote:null,
  feedsInto:['TECH-05','PDK-01','PDK-04','IPR-07','TC-03'],
  measuredBy:[
    'Weeks from engagement to executed NDA',
    'Access requests blocked on missing scope',
    'Redline cycles against those forecast',
  ],
},

'TECH-07': {
  stage:'technology', window:[1,5], criticalPath:false,
  purpose:[
    'Establish where each candidate node <b>actually is on its maturity curve</b>—risk production timing, defect density trend, yield learning rate, capacity ramp—and turn that into a risk assessment the program plans against.',
    'A node chosen at the right time is a node in volume production when the program taped out. A node chosen too early gives the program the foundry\'s learning curve as a yield problem, and the schedule to absorb it was never in the plan.',
  ],
  steps:[
    {n:1, text:'Node maturity and risk-production timing review', tat:1, lane:'main'},
    {n:2, text:'Defect density trend and yield learning curve request', tat:1, lane:'main'},
    {n:3, text:'Foundry roadmap alignment against the program schedule', tat:1, lane:'par'},
    {n:4, text:'Capacity ramp profile at the node', tat:0.75, lane:'par'},
    {n:5, text:'Node risk assessment and mitigation options', tat:2, lane:'main'},
  ],
  flowNote:'Step 2 asks for data the foundry treats as sensitive, and how much of it arrives is itself a signal. A foundry that will not share a defect density trend under NDA is telling the program something about the trend.',
  consumes:[
    'Short-list from TECH-01',
    'Foundry roadmap and node cadence under NDA',
    'Defect density and yield learning data where available',
    'Program schedule and tapeout date from DEF-08',
    'DTCO findings as they emerge from TECH-03',
  ],
  produces:[
    'Node maturity and risk-production timing assessment',
    'Defect density trend and yield learning curve',
    'Roadmap alignment note against the program schedule',
    'Capacity ramp profile',
    'Node maturity assessment per candidate',
    'Node risk assessment with mitigation options',
  ],
  producedBy:[1,2,3,4,5,5],
  rel:[
    {id:'TECH-D6', rel:'produces', text:'<b>Node risk assessment—maturity, defect density, yield learning curve.</b> This activity is the deliverable, and it is what the yield assumption in the cost model should be built on.'},
    {id:'TECH-D1', rel:'feeds', text:'<b>Technology selection report.</b> Maturity is a selection criterion in its own right, separate from the PPA the node can deliver.'},
  ],
  risks:[
    '<b>Marketing defect density used as a planning number.</b> The published curve is a target; the yield the program gets is the curve at its own tapeout date, which is a different point.',
    '<b>Risk production date taken as the availability date.</b> Risk production is when the node exists, not when it is ready for a large die at volume, and the gap can be two quarters.',
    '<b>Roadmap alignment checked once.</b> Foundry roadmaps move; an alignment done at selection and never revisited is a stale assumption by tapeout.',
    '<b>No mitigation options developed.</b> Identifying a maturity risk without a mitigation—a later slot, a shuttle, a conservative design rule set—leaves the program with a finding and no action.',
    '<b>Large-die yield inferred from small-die data.</b> Defect density scales against area brutally, and a curve measured on small test die flatters a 600 mm² part.',
  ],
  roles:[
    {r:'Technology strategist', d:'Owns the maturity and risk assessment'},
    {r:'Yield engineer', d:'Defect density interpretation and area scaling'},
    {r:'Foundry technical contact', d:'Roadmap, ramp and learning-curve data'},
    {r:'Program manager', d:'Alignment against the program schedule'},
    {r:'Product cost analyst', d:'Turns the yield curve into a cost assumption'},
  ],
  effort:[['Maturity and roadmap review',0.5], ['Defect density and yield data',0.5], ['Risk assessment and mitigations',0.5]],
  entry:[
    'Short-list available from TECH-01',
    'NDA executed far enough to receive roadmap data',
    'Program tapeout date estimated by DEF-08',
  ],
  exit:[
    'Yield curve stated at the program\'s own tapeout date, not in general',
    'Every maturity risk carries at least one mitigation option',
    'Assessment handed to DEF-04 as the model\'s yield input',
  ],
  dependsOn:['TECH-01'],
  dependsNote:null,
  feedsInto:['TECH-08','DEF-04','DEF-07','TC-01','FAB-06','MP-05'],
  measuredBy:[
    'Risks identified with a mitigation against those without',
    'Yield assumption against the cost model\'s requirement',
    'Roadmap revisions after selection',
  ],
},

'TECH-08': {
  stage:'technology', window:[9,13], criticalPath:false,
  purpose:[
    'Decide, deliberately, <b>whether the program accepts single-source risk</b>—and if it does not, what dual-sourcing or migration readiness would cost in area, schedule and IP.',
    'Most leading-edge programs end up single-source, and that is a defensible answer. What is not defensible is arriving there by default. This activity prices the alternative so that the acceptance is a decision with a number attached rather than a shrug.',
  ],
  steps:[
    {n:1, text:'Second-source viability screen at the selected node class', tat:1, lane:'main'},
    {n:2, text:'Migration cost and schedule estimate', tat:1.25, lane:'main'},
    {n:3, text:'IP portability assessment across foundries', tat:0.75, lane:'par'},
    {n:4, text:'Design rule and library delta analysis', tat:0.75, lane:'par'},
    {n:5, text:'Strategy recommendation — dual-source, migration-ready, or single-source accepted', tat:1.75, lane:'main'},
  ],
  flowNote:'Migration readiness is a design-time choice, not a later option: it constrains which IP can be used and how aggressively design rules can be pushed. Deciding after RTL starts means the decision has already been made by everyone who chose an IP.',
  consumes:[
    'Selected node and flavor from TECH-01 and TECH-02',
    'IP bill of materials direction from IPR-01',
    'Design rule sets for alternative foundries',
    'Migration experience from previous programs',
    'Supply-continuity findings from TECH-01',
  ],
  produces:[
    'Second-source viability finding',
    'Migration cost and schedule estimate',
    'IP portability assessment',
    'Design rule and library delta analysis',
    'Sourcing strategy recommendation and decision record',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'TECH-D1', rel:'feeds', text:'<b>Technology selection report and decision record.</b> Single-source acceptance belongs in the selection record, priced, rather than being implied by its absence.'},
    {id:'TECH-D6', rel:'feeds', text:'<b>Node risk assessment.</b> Supply concentration is a node risk, and its mitigation is either a second source or an accepted exposure.'},
  ],
  risks:[
    '<b>Single-source accepted by default.</b> A decision nobody made is a decision nobody owns, and it surfaces during a supply disruption as a surprise.',
    '<b>Migration cost estimated without IP portability.</b> Foundry-specific memory compilers, IO and PHY are the expensive part of a migration, and they are usually the part left out of the estimate.',
    '<b>Migration readiness assumed to be free.</b> Designing to the intersection of two rule sets costs density and frequency on the node actually used.',
    '<b>Decision taken after IP selection.</b> Once <code>IPR-03</code> has committed to foundry-specific IP, migration readiness is no longer available at the price this study quotes.',
    '<b>Second source screened on capability alone.</b> Capability without allocated capacity is not a second source; it is a phone number.',
  ],
  roles:[
    {r:'Technology strategist', d:'Owns the sourcing recommendation'},
    {r:'IP strategist', d:'Portability of the IP bill of materials'},
    {r:'Physical design liaison', d:'Design rule and library delta impact'},
    {r:'Procurement lead', d:'Capacity and commercial viability of an alternative'},
    {r:'Program manager', d:'Carries the accepted exposure into the risk register'},
  ],
  effort:[['Migration cost and schedule estimate',0.5], ['Second-source viability screen',0.5], ['IP portability and rule delta',0.25], ['Strategy recommendation',0.25]],
  entry:[
    'Node and flavor selected',
    'IP bill of materials direction available from IPR-01',
    'Design rule sets accessible for at least one alternative',
  ],
  exit:[
    'Migration cost estimated with IP portability included',
    'Recommendation recorded, including the option of accepting single source',
    'Accepted exposure entered on the program risk register with an owner',
  ],
  dependsOn:['TECH-01','TECH-02','TECH-07'],
  dependsNote:null,
  feedsInto:['IPR-03','IPR-10','DEF-09'],
  measuredBy:[
    'Migration cost estimated against the exposure accepted',
    'IP blocks assessed for portability',
    'Whether the sourcing decision is recorded or implied',
  ],
},

'TECH-09': {
  stage:'technology', window:[9,14], criticalPath:false,
  purpose:[
    'Open the <b>backend supply chain</b> early—OSAT capability and capacity, substrate and interposer suppliers, the foundry-to-OSAT logistics model, and who owns known-good die—so package design starts against real constraints.',
    'On a 2.5D part the backend is not a downstream detail; it is a second supply chain with its own lead times, its own capacity constraints and its own qualification. Advanced packaging capacity in particular is allocated far ahead, and a program that starts asking at <code>PKGD-10</code> is asking late.',
  ],
  steps:[
    {n:1, text:'OSAT long-list against the package architecture assumption', tat:0.75, lane:'main'},
    {n:2, text:'Advanced packaging capability and capacity screen', tat:1.5, lane:'main'},
    {n:3, text:'Foundry-to-OSAT logistics and interface model', tat:1, lane:'par'},
    {n:4, text:'Substrate and interposer supplier landscape', tat:1, lane:'par'},
    {n:5, text:'Known-good-die handoff responsibility model', tat:0.75, lane:'par'},
    {n:6, text:'Preliminary capacity indication and engagement', tat:1.5, lane:'main'},
    {n:7, text:'Backend supply chain finding and handoff to package design', tat:1.25, lane:'main'},
  ],
  flowNote:'Step 5 decides an argument before it happens. When a packaged unit fails, whether the die or the assembly is responsible is a contractual question, and settling it while nobody has lost money is far easier than settling it afterwards.',
  consumes:[
    'Package architecture assumption from the requirement register',
    'Selected foundry and node from TECH-01',
    'Volume and ramp profile from the business case',
    'OSAT and substrate supplier capability data',
    'Interposer technology options from the foundry',
  ],
  produces:[
    'OSAT long-list with capability assessment',
    'Advanced packaging capacity indication',
    'Foundry-to-OSAT logistics model',
    'Substrate and interposer supplier landscape',
    'Known-good-die responsibility model',
    'Preliminary OSAT capacity indication',
    'Backend supply chain findings for package design',
  ],
  producedBy:[1,2,3,4,5,6,7],
  rel:[
    {id:'TECH-D5', rel:'feeds', text:'<b>Capacity and tapeout slot commitment.</b> Front-end capacity without matching backend capacity delivers wafers that cannot be assembled.'},
    {id:'TECH-D3', rel:'informs', text:'<b>Wafer, mask and NRE cost sheet.</b> Interposer and assembly pricing is the backend half of the technology cost, and the cost model needs both.'},
    {id:'TECH-D1', rel:'feeds', text:'<b>Technology selection report.</b> On a 2.5D part the choice of foundry constrains the interposer options, so backend capability belongs in the selection record.'},
  ],
  risks:[
    '<b>Advanced packaging capacity assumed available.</b> CoWoS-class capacity is allocated quarters ahead and to a small number of customers; assuming access is the single most common backend planning error.',
    '<b>OSAT chosen after package design starts.</b> Assembly process capability constrains the package design; choosing the OSAT afterwards means redesigning to fit.',
    '<b>Known-good-die responsibility left open.</b> The first failed assembly lot is the wrong moment to discover that nobody agreed who owns the die.',
    '<b>Substrate lead time discovered rather than planned.</b> Twenty-week substrate lead times set the order date, and the order date is derived from a wafer-out date nobody has committed yet.',
    '<b>Logistics model ignored.</b> Wafers crossing borders between fab, sort and assembly carry customs, export control and transit time that the schedule rarely shows.',
  ],
  roles:[
    {r:'Backend supply chain lead', d:'Owns the OSAT and substrate engagement'},
    {r:'Package architect', d:'States the capability the package will need'},
    {r:'Procurement lead', d:'Capacity indication and commercial engagement'},
    {r:'Quality liaison', d:'Known-good-die responsibility and failure ownership'},
    {r:'Operations planner', d:'Logistics, transit and customs model'},
  ],
  effort:[['Capability and capacity screen',0.75], ['OSAT and supplier engagement',0.5], ['Logistics and supplier landscape',0.5], ['Handoff to package design',0.25]],
  entry:[
    'Package architecture assumption stated in the requirement register',
    'Foundry selected, so interposer options are known',
    'Volume and ramp profile available',
  ],
  exit:[
    'Advanced packaging capacity indicated, not assumed',
    'Known-good-die responsibility model agreed in principle',
    'Findings handed to PKGD before package architecture is chosen',
  ],
  dependsOn:['TECH-01','DEF-01'],
  dependsNote:null,
  feedsInto:['PKGD-01','PKGD-09','PKGD-10','PTV-01','ASSY-01'],
  measuredBy:[
    'Advanced packaging capacity indicated against the ramp requirement',
    'Weeks between backend engagement and package architecture selection',
    'Substrate lead time against the wafer-out date',
  ],
},

};
