/* TEST — Test Development. Eleven activities. Stage w54–96 (42w), 174 M/M. */
module.exports = {

'TEST-01': {
  stage:'testDevelopment', window:[0,8], criticalPath:true,
  purpose:[
    'Decide <b>what will be tested, where, and to what defect level</b>—the plan every other activity in the stage implements.',
    'Test is where quality is bought and where cost per unit is set, and the two trade directly. The plan is the document where that trade is made explicitly: a DPPM target implies coverage, coverage implies content, content implies test time, and test time is money on every unit ever shipped.',
  ],
  steps:[
    {n:1, text:'Coverage requirement from the specification and DFT', tat:1, lane:'main'},
    {n:2, text:'Test flow architecture — sort, final, characterization', tat:2, lane:'main'},
    {n:3, text:'Tester resource estimation', tat:1.5, lane:'par'},
    {n:4, text:'Coverage matrix construction', tat:2, lane:'main'},
    {n:5, text:'DPPM target derivation from the coverage', tat:1.5, lane:'par'},
    {n:6, text:'Test insertion and binning strategy', tat:1.5, lane:'main'},
    {n:7, text:'Burn-in and screening decision', tat:1, lane:'par'},
    {n:8, text:'Plan review and release', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 5 is the one that closes the loop. Coverage without a DPPM target is an engineering preference; a DPPM target derived from the coverage is a commitment the customer can be given.',
  consumes:[
    'Product specification and quality target from DEF-04',
    'DFT coverage from DFT-03 and DFT-05',
    'Package pin map from PKGD-04',
    'Quality and reliability requirement from MP-01',
    'Cost target from DEF-06',
  ],
  produces:[
    'Coverage requirement',
    'Test flow architecture across insertions',
    'Tester resource estimate',
    'Test coverage matrix',
    'DPPM target derivation',
    'Test insertion and binning strategy',
    'Reviewed test plan',
    'Burn-in and screening decision',
    'Reviewed and released test plan',
  ],
  producedBy:[1,2,3,4,5,6,6,7,8],
  rel:[
    {id:'TEST-D1', rel:'produces', text:'<b>Test plan and test coverage matrix.</b> This activity is the deliverable, and every other TEST activity implements part of it.'},
    {id:'TEST-D6', rel:'informs', text:'<b>Test time and test cost model.</b> The flow architecture and insertion strategy set the cost model\'s structure.'},
  ],
  risks:[
    '<b>Coverage chosen without a DPPM target.</b> There is then no way to say whether the test is sufficient, only whether it is thorough.',
    '<b>Test time not budgeted at plan time.</b> Content accumulates and the cost per unit is discovered at production readiness when it is expensive to change.',
    '<b>Burn-in decided late.</b> It is a capital and cycle-time commitment, and reversing it after qualification planning is expensive.',
    '<b>Sort and final coverage overlapping without intent.</b> Testing the same thing twice costs money on every unit and often happens by accretion.',
    '<b>DFT coverage assumed rather than measured.</b> The plan then promises a DPPM the actual pattern set cannot deliver.',
  ],
  roles:[
    {r:'Test architect', d:'Owns the plan and the coverage matrix'},
    {r:'DFT engineer', d:'Structural coverage and pattern capability'},
    {r:'Quality engineer', d:'DPPM target and screening strategy'},
    {r:'Product engineering', d:'Binning and grading strategy'},
    {r:'Cost analyst', d:'Test cost against the product cost target'},
  ],
  effort:[['Coverage matrix',3], ['Test flow architecture',2.5], ['Binning strategy',2], ['DPPM derivation',1.75], ['Review and release',1.5], ['Resource estimation',1.25]],
  entry:[
    'DFT coverage results available from DFT-03 and DFT-05',
    'Quality target defined',
    'Package pin map from PKGD-04',
  ],
  exit:[
    'DPPM target derived from actual coverage, not asserted',
    'Test time budgeted before content is written',
    'Sort and final coverage split deliberately',
  ],
  dependsOn:['DEF-04','DEF-06','DFT-03','DFT-05','PKGD-04'],
  dependsNote:null,
  feedsInto:['TEST-02','TEST-05','TEST-06','TEST-07','TEST-09'],
  measuredBy:[
    'Coverage against the DPPM target',
    'Test time estimate against the cost target',
    'Overlap between sort and final content',
  ],
},

'TEST-02': {
  stage:'testDevelopment', window:[4,10], criticalPath:false,
  purpose:[
    'Choose the <b>ATE platform</b> and book the tester time—a capital and capacity decision that has to be made long before there is anything to test.',
    'Tester capacity is a shared, scheduled resource. Program development time, characterization time and production capacity are all booked against the same pool, and a program that has not committed its slots competes with programs that have.',
  ],
  steps:[
    {n:1, text:'Tester requirement from the test plan', tat:1, lane:'main'},
    {n:2, text:'ATE platform evaluation against the requirement', tat:1.5, lane:'main'},
    {n:3, text:'Instrument option and pin-count analysis', tat:1, lane:'par'},
    {n:4, text:'Platform selection and configuration', tat:1.5, lane:'main'},
    {n:5, text:'Cost per tested unit model', tat:1, lane:'par'},
    {n:6, text:'Tester time booking and capacity commitment', tat:2, lane:'main'},
  ],
  flowNote:'Step 6 is why this runs early. Development, characterization and production all draw on the same testers, and slots that are not booked are taken.',
  consumes:[
    'Test plan and flow architecture from TEST-01',
    'Pin count and interface rates from PKGD-04',
    'Available ATE platforms and their capability',
    'Test capacity and capital budget',
    'Production volume forecast from DEF-05',
  ],
  produces:[
    'Tester requirement specification',
    'ATE platform evaluation',
    'Instrument option and pin-count analysis',
    'Platform selection and configuration',
    'Cost per tested unit model',
    'Tester time bookings across development, characterization and production',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'TEST-D6', rel:'feeds', text:'<b>Test time and test cost model.</b> The platform\'s cost per hour is the model\'s rate.'},
    {id:'TEST-D3', rel:'informs', text:'<b>Wafer sort and final test programs.</b> Programs are written for a specific platform and its instrument set.'},
  ],
  risks:[
    '<b>Tester time not booked ahead.</b> Capacity is shared, and a program without commitments waits behind programs with them.',
    '<b>Instrument options short of the interface rate.</b> High-speed content cannot be run, and the shortfall is discovered when the program is written.',
    '<b>Pin count insufficient for parallel sites.</b> Multi-site conversion later becomes impossible, and test cost stays where it started.',
    '<b>Platform chosen on capital cost alone.</b> Cost per tested unit depends on throughput as much as on the tester\'s price.',
    '<b>Development capacity not separated from production.</b> Program debug then competes with the ramp it is meant to enable.',
  ],
  roles:[
    {r:'Test engineering manager', d:'Owns platform selection and booking'},
    {r:'Test architect', d:'Requirement derivation from the plan'},
    {r:'Operations planner', d:'Capacity commitment and scheduling'},
    {r:'Cost analyst', d:'Cost per tested unit'},
    {r:'ATE vendor liaison', d:'Configuration and instrument options'},
  ],
  effort:[['Platform evaluation',1.25], ['Tester time booking',1], ['Selection and configuration',0.75], ['Pin-count analysis',0.5], ['Cost model',0.5]],
  entry:[
    'Test plan available from TEST-01',
    'Pin count and interface rates known',
    'Capital budget and capacity forecast available',
  ],
  exit:[
    'Development, characterization and production slots all booked',
    'Instrument set covering the highest interface rate',
    'Pin count supporting the planned multi-site conversion',
  ],
  dependsOn:['TEST-01','PKGD-04','DEF-05'],
  dependsNote:null,
  feedsInto:['TEST-05','TEST-06','TEST-08','MP-07'],
  measuredBy:[
    'Tester slots committed against the plan',
    'Instrument capability against interface rates',
    'Cost per tested unit against target',
  ],
},

'TEST-03': {
  stage:'testDevelopment', window:[10,30], criticalPath:true,
  purpose:[
    'Design, fabricate and qualify the <b>probe card</b>—the physical interface between the tester and the wafer, and the longest lead time in the stage.',
    'Nothing can be sorted without it, and sort gates assembly. Twenty weeks of design and fabrication sit in front of the first wafer, which means the card has to be committed against a bump map that is frozen far earlier than most people expect.',
  ],
  steps:[
    {n:1, text:'Probe card requirement and bump map extraction', tat:2, lane:'main'},
    {n:2, text:'Probe card design', tat:3, lane:'main'},
    {n:3, text:'Contact resistance and planarity analysis', tat:3, lane:'par'},
    {n:4, text:'Probe card fabrication', tat:8, lane:'main'},
    {n:5, text:'Touchdown life and cleaning strategy', tat:3, lane:'par'},
    {n:6, text:'Qualification on the tester', tat:4, lane:'main'},
    {n:7, text:'Spare card and repair plan', tat:2.5, lane:'par'},
    {n:8, text:'Release to wafer sort', tat:3, lane:'main'},
  ],
  flowNote:'Step 4\'s eight weeks are pure vendor lead time and cannot be compressed. Step 1\'s bump map therefore has to be frozen roughly five months before sort, which is well before most people believe the design is stable.',
  consumes:[
    'Bump map from PD-15 and PKGD-03',
    'Test plan and sort content from TEST-01',
    'ATE platform and interface from TEST-02',
    'Wafer sort touchdown plan',
    'Probe card vendor capability',
  ],
  produces:[
    'Probe card requirement and bump map',
    'Probe card design',
    'Contact resistance and planarity analysis',
    'Fabricated probe card',
    'Touchdown life and cleaning strategy',
    'Tester qualification results',
    'Spare card and repair plan',
    'Probe card released to sort',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TEST-D2', rel:'produces', text:'<b>Qualified probe card and load board.</b> The probe card half of the deliverable.'},
    {id:'TEST-D3', rel:'gates', text:'<b>Wafer sort and final test programs.</b> A sort program cannot be debugged on silicon without a qualified card.'},
  ],
  risks:[
    '<b>Bump map changing after card release.</b> Eight weeks of fabrication are lost, and sort—and therefore assembly—moves by that much.',
    '<b>Contact resistance out of specification.</b> Marginal contact produces failures that look like silicon defects and corrupts the whole sort yield.',
    '<b>Planarity insufficient across the touchdown area.</b> Some probes contact and some do not, and the pattern is subtle enough to be missed.',
    '<b>No spare card.</b> A damaged card with a ten-week replacement stops sort entirely, and cards are damaged routinely.',
    '<b>Touchdown life below the wafer volume.</b> Card degradation then appears as a yield trend that gets chased as a process problem.',
  ],
  roles:[
    {r:'Probe engineer', d:'Owns the card and its qualification'},
    {r:'Test engineer', d:'Requirement and tester interface'},
    {r:'Physical design', d:'Bump map freeze and change control'},
    {r:'Probe card vendor', d:'Design and fabrication'},
    {r:'Operations planner', d:'Spare strategy and lead time'},
  ],
  effort:[['Probe card design',4], ['Qualification',3.5], ['Requirement and bump map',2.5], ['Contact analysis',2.5], ['Touchdown strategy',2], ['Spare plan',1.5]],
  entry:[
    'Bump map frozen from PD-15 and PKGD-03',
    'ATE platform selected in TEST-02',
    'Vendor capacity booked against the lead time',
  ],
  exit:[
    'Card qualified on the tester before wafers arrive',
    'Contact resistance and planarity inside specification',
    'Spare card available against the sort volume',
  ],
  dependsOn:['TEST-01','TEST-02','PD-15','PKGD-03'],
  dependsNote:null,
  feedsInto:['TEST-05','ASSY-01','FAB-08'],
  measuredBy:[
    'Card readiness against wafer arrival',
    'Contact resistance and planarity at qualification',
    'Touchdown life against planned wafer volume',
  ],
},

'TEST-04': {
  stage:'testDevelopment', window:[12,29], criticalPath:false,
  purpose:[
    'Design, build and bring up the <b>load board and socket</b>—the package-level equivalent of the probe card, and what every final-test and characterization measurement passes through.',
    'The load board carries the tester\'s signals to the package at full rate and delivers its power at full current. It is a high-speed board design in its own right, and its own contribution to a measurement has to be small enough that what is measured is the silicon.',
  ],
  steps:[
    {n:1, text:'Load board requirement and socket selection', tat:2, lane:'main'},
    {n:2, text:'Load board design with signal integrity', tat:3.5, lane:'main'},
    {n:3, text:'Socket contact and insertion life analysis', tat:2.5, lane:'par'},
    {n:4, text:'Fabrication and assembly', tat:5, lane:'main'},
    {n:5, text:'Power delivery design on the load board', tat:2.5, lane:'par'},
    {n:6, text:'Bring-up on the tester', tat:3.5, lane:'main'},
    {n:7, text:'Correlation fixture design', tat:2, lane:'par'},
    {n:8, text:'Release to final test', tat:3, lane:'main'},
  ],
  flowNote:'Step 5 is routinely underestimated. A high-power part draws current through the socket, and a load board whose power delivery droops produces failures at speed that are indistinguishable from silicon marginality.',
  consumes:[
    'Package pin map and ball map from PKGD-04',
    'Test plan and final content from TEST-01',
    'ATE platform interface from TEST-02',
    'Power envelope from ARCH-08',
    'Socket vendor capability',
  ],
  produces:[
    'Load board requirement and socket selection',
    'Load board design with SI results',
    'Socket contact and life analysis',
    'Fabricated and assembled load board',
    'Load board design',
    'Load board power delivery design',
    'Tester bring-up results',
    'Correlation fixture',
    'Load board released to final test',
  ],
  producedBy:[1,2,3,4,5,5,6,7,8],
  rel:[
    {id:'TEST-D2', rel:'produces', text:'<b>Qualified probe card and load board.</b> The load board half of the deliverable.'},
    {id:'TEST-D3', rel:'gates', text:'<b>Wafer sort and final test programs.</b> The final test program is debugged on this hardware.'},
  ],
  risks:[
    '<b>Load board power delivery droop.</b> It produces at-speed failures that look exactly like silicon marginality and consume weeks of debug.',
    '<b>Socket insertion life below the test volume.</b> Contact degrades, yield trends downward, and the cause is looked for in the process.',
    '<b>Board channel loss consuming the measurement margin.</b> The interface test then fails on the board rather than on the part.',
    '<b>Socket selected before the package is dimensioned.</b> A socket that does not fit the finished package is discovered very late.',
    '<b>No correlation fixture.</b> ATE and bench results then cannot be reconciled, and both are distrusted.',
  ],
  roles:[
    {r:'Test hardware engineer', d:'Owns the load board'},
    {r:'SI/PI engineer', d:'Channel and power delivery on the board'},
    {r:'Test engineer', d:'Tester interface and bring-up'},
    {r:'Package engineer', d:'Socket and package dimensional fit'},
    {r:'Socket vendor', d:'Contact design and insertion life'},
  ],
  effort:[['Load board design',4], ['Tester bring-up',3], ['Fabrication and assembly',2.5], ['Power delivery design',2.5], ['Socket analysis',2], ['Release',2]],
  entry:[
    'Package pin and ball map from PKGD-04',
    'ATE platform selected in TEST-02',
    'Power envelope known from ARCH-08',
  ],
  exit:[
    'Power delivery adequate at maximum test current',
    'Socket insertion life above the planned test volume',
    'Board channel contribution small against the measurement margin',
  ],
  dependsOn:['TEST-01','TEST-02','PKGD-04','ARCH-08'],
  dependsNote:null,
  feedsInto:['TEST-06','TEST-07','TEST-10'],
  measuredBy:[
    'Power droop at maximum test current',
    'Socket life against test volume',
    'Board channel loss against measurement margin',
  ],
},

'TEST-05': {
  stage:'testDevelopment', window:[16,32], criticalPath:true,
  purpose:[
    'Write the <b>wafer sort test program</b>—the screen that decides which die are worth assembling into a package.',
    'On a 2.5D part, sort is the most economically consequential test in the flow. Everything it lets through carries an interposer, two HBM stacks and an assembly with it, so its coverage is measured against package cost rather than against die cost.',
  ],
  steps:[
    {n:1, text:'Sort flow and test list definition', tat:2, lane:'main'},
    {n:2, text:'DC and continuity test development', tat:3.5, lane:'main'},
    {n:3, text:'Parametric and process monitor test development', tat:2.5, lane:'par'},
    {n:4, text:'Scan and structural test integration', tat:3.5, lane:'main'},
    {n:5, text:'Binning and wafer map output', tat:2.5, lane:'par'},
    {n:6, text:'Functional and memory BIST content', tat:3.5, lane:'main'},
    {n:7, text:'Test limits and guard-band setting', tat:2.5, lane:'par'},
    {n:8, text:'Program integration and debug on the tester', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 7 is where the program\'s economics are set. Limits too tight throw away good die; too loose and packages are built on bad ones. The guard bands should come from measurement uncertainty and package cost, not from convention.',
  consumes:[
    'Test plan and coverage matrix from TEST-01',
    'ATE patterns from TEST-08',
    'Probe card from TEST-03',
    'Memory BIST from DFT-06',
    'Scan architecture from DFT-03',
  ],
  produces:[
    'Sort flow and test list',
    'DC and continuity tests',
    'Parametric and monitor tests',
    'Integrated scan and structural content',
    'Binning and wafer map output',
    'Functional and BIST content',
    'Test limits and guard bands',
    'Debugged sort program',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TEST-D3', rel:'produces', text:'<b>Wafer sort and final test programs, release-tagged.</b> The sort half of the deliverable.'},
    {id:'TEST-D1', rel:'feeds', text:'<b>Test plan and test coverage matrix.</b> What the program actually achieves updates what the plan claimed.'},
  ],
  risks:[
    '<b>Guard bands set by convention.</b> On a part where an escape costs an assembled package, the limits should be derived from that cost.',
    '<b>Coverage below what the package economics need.</b> Assembly yield then absorbs the difference, at many times the price.',
    '<b>Program debugged only in simulation.</b> Tester behavior differs from the model, and the difference is found on the first wafer.',
    '<b>Wafer map output not matching the assembly requirement.</b> KGD selection depends on the map format, and a mismatch stops assembly.',
    '<b>Test time growing without check.</b> Sort time multiplies across every wafer ever run, and content accretes silently.',
  ],
  roles:[
    {r:'Test engineer', d:'Owns the sort program'},
    {r:'DFT engineer', d:'Scan and BIST content integration'},
    {r:'Product engineering', d:'Limits, guard bands and binning'},
    {r:'Yield engineer', d:'Parametric monitors and map output'},
    {r:'Assembly liaison', d:'Wafer map format and KGD criteria'},
  ],
  effort:[['Scan and structural integration',6.5], ['Functional and BIST',6], ['DC and continuity',5.5], ['Integration and debug',5], ['Parametric development',4], ['Binning and limits',3]],
  entry:[
    'Test plan from TEST-01',
    'ATE patterns available from TEST-08',
    'Probe card qualified in TEST-03',
  ],
  exit:[
    'Guard bands derived from package cost and measurement uncertainty',
    'Coverage sufficient for the assembly economics',
    'Wafer map format agreed with assembly',
  ],
  dependsOn:['TEST-01','TEST-03','TEST-08','DFT-03','DFT-06'],
  dependsNote:null,
  feedsInto:['ASSY-01','FAB-08','MP-06','TEST-09'],
  measuredBy:[
    'Sort coverage against the DPPM target',
    'Sort test time against budget',
    'Assembly failures attributable to sort escapes',
  ],
},

'TEST-06': {
  stage:'testDevelopment', window:[20,36], criticalPath:false,
  purpose:[
    'Write the <b>final test program</b> that runs on the assembled package—at speed, at temperature, across every interface the product ships with.',
    'Final test is the last screen before a customer sees the part. It exercises what sort could not: the assembled interfaces, the HBM stacks, the full power envelope, and the at-speed behavior of a part that is now mechanically complete.',
  ],
  steps:[
    {n:1, text:'Final test flow definition', tat:2, lane:'main'},
    {n:2, text:'Package-level DC and continuity content', tat:3.5, lane:'main'},
    {n:3, text:'Power and thermal test content', tat:2.5, lane:'par'},
    {n:4, text:'At-speed functional content', tat:3.5, lane:'main'},
    {n:5, text:'Binning and grading content', tat:2.5, lane:'par'},
    {n:6, text:'Interface and HBM test content', tat:3.5, lane:'main'},
    {n:7, text:'Final test limits and guard bands', tat:2.5, lane:'par'},
    {n:8, text:'Program integration and debug', tat:3.5, lane:'main'},
  ],
  flowNote:'Step 6 is where the 2.5D part differs most from a monolithic one. The HBM interfaces exist only after assembly, they cannot be tested at sort, and they are the most likely thing to be wrong about an assembled unit.',
  consumes:[
    'Test plan from TEST-01',
    'Load board from TEST-04',
    'ATE patterns from TEST-08',
    'HBM interface specification from ARCH-03',
    'Binning strategy from TEST-01',
  ],
  produces:[
    'Final test flow',
    'Package-level DC and continuity content',
    'Power and thermal test content',
    'At-speed functional content',
    'Binning and grading content',
    'Interface and HBM test content',
    'Final test limits and guard bands',
    'Debugged final test program',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TEST-D3', rel:'produces', text:'<b>Wafer sort and final test programs, release-tagged.</b> The final-test half of the deliverable.'},
    {id:'TEST-D6', rel:'feeds', text:'<b>Test time and test cost model.</b> Final test time is the larger half of the per-unit test cost.'},
  ],
  risks:[
    '<b>HBM interface content insufficient.</b> The interfaces only exist after assembly, and a marginal one shipped is a field failure.',
    '<b>At-speed content not run at temperature.</b> Timing marginality appears at the hot corner, and testing only at room temperature misses it.',
    '<b>Binning content added late.</b> Grading is how the product line is built, and retrofitting it changes the flow and its cost.',
    '<b>Test time not tracked against the cost model.</b> Final test dominates per-unit test cost and grows quietly.',
    '<b>Program debugged without real assembled units.</b> The first units are precious, and the program has to be ready when they exist.',
  ],
  roles:[
    {r:'Test engineer', d:'Owns the final test program'},
    {r:'Product engineering', d:'Binning, grading and limits'},
    {r:'Interface engineer', d:'HBM and high-speed content'},
    {r:'Thermal engineer', d:'Temperature-dependent content'},
    {r:'Yield engineer', d:'Failure classification from final test'},
  ],
  effort:[['At-speed functional',6], ['Interface and HBM content',6], ['DC and continuity',5], ['Integration and debug',4.5], ['Power and thermal',3.5], ['Binning and limits',3]],
  entry:[
    'Test plan from TEST-01',
    'Load board released from TEST-04',
    'ATE patterns available from TEST-08',
  ],
  exit:[
    'HBM interfaces exercised at their operating rate',
    'At-speed content run across the temperature range',
    'Test time inside the cost model\'s allowance',
  ],
  dependsOn:['TEST-01','TEST-04','TEST-08','ARCH-03'],
  dependsNote:null,
  feedsInto:['MP-06','TEST-09','TEST-10','BU-05'],
  measuredBy:[
    'Final test coverage against the DPPM target',
    'Final test time against the cost model',
    'Escapes found at system level',
  ],
},

'TEST-07': {
  stage:'testDevelopment', window:[24,36], criticalPath:false,
  purpose:[
    'Build the <b>characterization content</b>—shmoos, corners, parametric sweeps, datasheet parameter measurement—that turns silicon into a specified product.',
    'Production test asks whether a part passes. Characterization asks what the part actually does, across voltage, frequency and temperature, over a statistically meaningful sample. Every number in the datasheet comes from here, and so do the guard bands production test uses.',
  ],
  steps:[
    {n:1, text:'Characterization requirement from qualification and marketing', tat:1.5, lane:'main'},
    {n:2, text:'Shmoo and corner content', tat:2.5, lane:'main'},
    {n:3, text:'Temperature and voltage sweep automation', tat:2, lane:'par'},
    {n:4, text:'Parametric characterization content', tat:2.5, lane:'main'},
    {n:5, text:'Statistical sample plan', tat:2, lane:'par'},
    {n:6, text:'Datasheet parameter test content', tat:2.5, lane:'main'},
    {n:7, text:'Data analysis and reporting pipeline', tat:1.5, lane:'par'},
    {n:8, text:'Content integration and correlation setup', tat:3, lane:'main'},
  ],
  flowNote:'Step 5 decides whether the results mean anything. A datasheet number from three units is an anecdote; the sample size follows from the distribution being characterized and the confidence the specification claims.',
  consumes:[
    'Datasheet parameter list from DEF-04',
    'Qualification requirements from MP-01',
    'Test plan from TEST-01',
    'Load board and correlation fixture from TEST-04',
    'Lab instrumentation from EVB-09',
  ],
  produces:[
    'Characterization requirement',
    'Shmoo and corner content',
    'Sweep automation',
    'Parametric characterization content',
    'Statistical sample plan',
    'Datasheet parameter content',
    'Data analysis and reporting pipeline',
    'Integrated characterization suite',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TEST-D4', rel:'produces', text:'<b>Characterization test suite.</b> This activity is the deliverable, and every datasheet number traces to it.'},
    {id:'TEST-D6', rel:'informs', text:'<b>Test time and test cost model.</b> Characterization guard bands set how much production test time is spent on margin.'},
  ],
  risks:[
    '<b>Sample size too small for the claim.</b> A datasheet parameter from a handful of units is a number without confidence behind it.',
    '<b>Corners not spanning the qualification range.</b> Qualification then stresses conditions characterization never measured.',
    '<b>Sweeps not automated.</b> Manual shmoo consumes engineer-weeks per corner, and the corners get quietly reduced.',
    '<b>Datasheet parameters not traceable to a measurement.</b> A customer question about a number then has no answer.',
    '<b>Analysis pipeline built after the data.</b> Data is collected in a format nobody can analyze, and the campaign is re-run.',
  ],
  roles:[
    {r:'Characterization engineer', d:'Owns the suite'},
    {r:'Product engineering', d:'Datasheet parameters and guard bands'},
    {r:'Statistician or yield engineer', d:'Sample plan and confidence'},
    {r:'Automation engineer', d:'Sweep automation and data pipeline'},
    {r:'Quality engineer', d:'Alignment with qualification conditions'},
  ],
  effort:[['Shmoo and corner content',4.5], ['Datasheet parameters',4], ['Parametric content',3.5], ['Integration and correlation',3], ['Sweep automation',2.5], ['Sample plan and reporting',2.5]],
  entry:[
    'Datasheet parameter list from DEF-04',
    'Qualification conditions from MP-01',
    'Correlation fixture from TEST-04',
  ],
  exit:[
    'Sample size supporting the datasheet\'s confidence claim',
    'Corners spanning the qualification range',
    'Every datasheet number traceable to a measurement',
  ],
  dependsOn:['TEST-01','TEST-04','DEF-04','MP-01','EVB-09'],
  dependsNote:null,
  feedsInto:['BU-07','BU-08','MP-08','MP-12','EVB-01'],
  measuredBy:[
    'Sample size against the confidence claim',
    'Corner coverage against qualification range',
    'Datasheet parameters with traceable measurements',
  ],
},

'TEST-08': {
  stage:'testDevelopment', window:[22,32], criticalPath:true,
  purpose:[
    'Port the <b>DFT patterns to the tester\'s format</b> and debug them there—the step between a pattern that simulates and a pattern that runs.',
    'ATPG produces patterns against an idealized model. The tester has finite memory, real timing resolution, protocol constraints and a specific pin electronics behavior. Every one of those turns a pattern that passes in simulation into one that fails on hardware, and finding out which is the work.',
  ],
  steps:[
    {n:1, text:'ATPG pattern handoff from DFT', tat:1.5, lane:'main'},
    {n:2, text:'Pattern translation to the tester format', tat:2, lane:'main'},
    {n:3, text:'Pattern volume and memory-depth reduction', tat:1.5, lane:'par'},
    {n:4, text:'Timing and protocol mapping', tat:2.5, lane:'main'},
    {n:5, text:'Compression and streaming setup', tat:1.5, lane:'par'},
    {n:6, text:'Pattern simulation against the tester model', tat:2, lane:'main'},
    {n:7, text:'Pattern regression and version control', tat:1.5, lane:'par'},
    {n:8, text:'Pattern debug on silicon or emulation', tat:2, lane:'main'},
  ],
  flowNote:'Step 3 is a hard constraint, not an optimization. Tester pattern memory is finite, and a pattern set that exceeds it simply cannot be loaded—which is discovered at translation, not at ATPG.',
  consumes:[
    'ATPG patterns from DFT-03',
    'Compression architecture from DFT-04',
    'ATE platform and memory depth from TEST-02',
    'Timing constraints from SO-03',
    'Tester timing model',
  ],
  produces:[
    'Pattern handoff record',
    'Translated tester-format patterns',
    'Volume and memory reduction',
    'Timing and protocol mapping',
    'Compression and streaming setup',
    'Tester-model simulation results',
    'Pattern regression under version control',
    'Debugged ATE-ready pattern set',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TEST-D5', rel:'produces', text:'<b>ATE-ready pattern set with debug log.</b> This activity is the deliverable.'},
    {id:'TEST-D3', rel:'feeds', text:'<b>Wafer sort and final test programs.</b> Both programs run these patterns as their structural content.'},
  ],
  risks:[
    '<b>Pattern volume exceeding tester memory.</b> The set cannot be loaded at all, and reduction after ATPG loses coverage.',
    '<b>Timing not mappable to the tester\'s resolution.</b> At-speed patterns then run at the wrong speed, silently.',
    '<b>Patterns not simulated against the tester model.</b> Failures are then debugged on silicon at tester rates rather than in simulation.',
    '<b>Pattern set not versioned.</b> A yield excursion cannot be correlated to a pattern change nobody recorded.',
    '<b>Debug deferred until first silicon.</b> Pattern problems and silicon problems then arrive together and cannot be separated.',
  ],
  roles:[
    {r:'Test engineer', d:'Owns pattern porting and debug'},
    {r:'DFT engineer', d:'ATPG handoff and coverage preservation'},
    {r:'ATE applications engineer', d:'Tester format, timing and memory'},
    {r:'CAD engineer', d:'Translation flow and regression'},
    {r:'Product engineering', d:'Coverage after reduction'},
  ],
  effort:[['Timing and protocol mapping',4], ['Pattern debug',3.5], ['Translation',3], ['Tester-model simulation',2.5], ['Volume reduction',1.5], ['Regression and version control',1.5]],
  entry:[
    'ATPG patterns released from DFT-03',
    'ATE platform and memory depth known from TEST-02',
    'Tester timing model available',
  ],
  exit:[
    'Pattern set fitting tester memory without coverage loss',
    'Timing mapped within the tester\'s resolution',
    'Patterns simulated against the tester model before silicon',
  ],
  dependsOn:['DFT-03','DFT-04','TEST-02','SO-03'],
  dependsNote:null,
  feedsInto:['TEST-05','TEST-06','MP-06'],
  measuredBy:[
    'Coverage retained after volume reduction',
    'Patterns passing tester-model simulation',
    'Pattern failures found on silicon that simulation missed',
  ],
},

'TEST-09': {
  stage:'testDevelopment', window:[8,17], criticalPath:false,
  purpose:[
    'Reduce <b>test time and test cost per unit</b>—an activity that starts early, because content is far cheaper to not write than to remove.',
    'Test time is paid on every unit for the product\'s whole life. A second saved at final test on a million units is real money, and the savings available at plan time are much larger than the ones available after the program is written and qualified.',
  ],
  steps:[
    {n:1, text:'Test time baseline measurement', tat:1.5, lane:'main'},
    {n:2, text:'Test time contributor analysis', tat:2, lane:'main'},
    {n:3, text:'Redundant coverage identification', tat:1.5, lane:'par'},
    {n:4, text:'Content reduction and reordering', tat:2, lane:'main'},
    {n:5, text:'Adaptive and skip-on-fail strategy', tat:1.5, lane:'par'},
    {n:6, text:'Parallelism and multi-site assessment', tat:1.75, lane:'main'},
    {n:7, text:'Tester resource cost per unit', tat:1.25, lane:'par'},
    {n:8, text:'Cost model update and release', tat:1.75, lane:'main'},
  ],
  flowNote:'Step 4\'s reordering is often the largest single win and costs nothing. Running the tests that fail most first means failing parts leave the tester early, and the average test time drops without any coverage change.',
  consumes:[
    'Test plan and flow from TEST-01',
    'Sort content from TEST-05',
    'Final content from TEST-06',
    'Tester cost per hour from TEST-02',
    'Expected yield and failure distribution',
  ],
  produces:[
    'Test time baseline',
    'Contributor analysis by test block',
    'Redundant coverage findings',
    'Content reduction and reordering',
    'Adaptive and skip-on-fail strategy',
    'Parallelism and multi-site assessment',
    'Tester resource cost per unit',
    'Cost per unit model',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TEST-D6', rel:'produces', text:'<b>Test time and test cost model.</b> This activity is the deliverable.'},
    {id:'TEST-D1', rel:'informs', text:'<b>Test plan and test coverage matrix.</b> Reduction decisions change what the plan promises, and the matrix has to follow.'},
  ],
  risks:[
    '<b>Optimization started after qualification.</b> Any content change then requires re-qualification, which is why this starts early.',
    '<b>Coverage traded away silently.</b> Time reduction that loses coverage has to be an explicit decision against the DPPM target.',
    '<b>Reordering not done.</b> It is free and it is the largest single lever, and it is routinely overlooked.',
    '<b>Multi-site assumed without pin count.</b> The tester configuration from <code>TEST-02</code> has to support it, and retrofitting it does not work.',
    '<b>Cost model without a yield assumption.</b> Cost per good unit depends on yield, and a model without it understates the cost.',
  ],
  roles:[
    {r:'Test engineer', d:'Owns time and cost optimization'},
    {r:'Product engineering', d:'Coverage trade decisions'},
    {r:'Cost analyst', d:'Cost per unit model'},
    {r:'Yield engineer', d:'Failure distribution for reordering'},
    {r:'Operations planner', d:'Multi-site and capacity implications'},
  ],
  effort:[['Contributor analysis',3], ['Content reduction',2.5], ['Parallelism assessment',2], ['Cost model',1.75], ['Redundancy identification',1.5], ['Adaptive strategy',1.25]],
  entry:[
    'Test plan and flow available from TEST-01',
    'Content estimates or early programs available',
    'Tester cost per hour known',
  ],
  exit:[
    'Optimization done before qualification freezes the content',
    'Coverage trades made explicitly against the DPPM target',
    'Cost model including a yield assumption',
  ],
  dependsOn:['TEST-01','TEST-02','TEST-05','TEST-06'],
  dependsNote:null,
  feedsInto:['MP-07','MP-06','DEF-06'],
  measuredBy:[
    'Test time against the plan\'s budget',
    'Cost per good unit against target',
    'Coverage retained after reduction',
  ],
},

'TEST-10': {
  stage:'testDevelopment', window:[32,40], criticalPath:false,
  purpose:[
    'Correlate <b>ATE, bench and system results</b> so that a part passing on the tester behaves the same way in a customer\'s system.',
    'Three measurement environments produce three numbers for the same parameter, and they never agree exactly. What matters is whether the disagreement is understood: an unexplained gap between tester and system is either an escape path or an over-screen, and both are expensive.',
  ],
  steps:[
    {n:1, text:'Correlation plan and unit selection', tat:1, lane:'main'},
    {n:2, text:'ATE-to-bench correlation', tat:2, lane:'main'},
    {n:3, text:'Measurement uncertainty budget', tat:1.5, lane:'par'},
    {n:4, text:'ATE-to-system correlation', tat:2, lane:'main'},
    {n:5, text:'Golden unit designation and retention', tat:1.5, lane:'par'},
    {n:6, text:'Discrepancy analysis and root cause', tat:1.5, lane:'main'},
    {n:7, text:'Correlation regression setup', tat:1, lane:'par'},
    {n:8, text:'Guard-band adjustment and release', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 5 is what makes correlation repeatable. A retained set of golden units re-measured after any change is how tester drift, load board degradation and program regressions are caught before they become yield excursions.',
  consumes:[
    'Final test results from TEST-06',
    'Bench measurements from BU-08',
    'System-level results from BU-05',
    'Measurement uncertainty from TEST-07',
    'Load board and correlation fixture from TEST-04',
  ],
  produces:[
    'Correlation plan and unit selection',
    'ATE-to-bench correlation results',
    'Measurement uncertainty budget',
    'ATE-to-system correlation results',
    'Designated golden units',
    'Discrepancy analysis and root causes',
    'Correlation regression',
    'Adjusted guard bands',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TEST-D4', rel:'feeds', text:'<b>Characterization test suite.</b> Correlation validates that characterization numbers hold outside the tester.'},
    {id:'TEST-D3', rel:'feeds', text:'<b>Wafer sort and final test programs.</b> Guard-band adjustments from correlation go back into the programs.'},
  ],
  risks:[
    '<b>Discrepancy accepted without root cause.</b> The gap is either an escape or an over-screen, and \'they just differ\' resolves neither.',
    '<b>Correlation on too few units.</b> Two units that agree prove very little about the population.',
    '<b>No golden units retained.</b> Drift in the tester, the load board or the program then has nothing to be measured against.',
    '<b>System correlation skipped.</b> ATE-to-bench is the easy half; ATE-to-system is the one the customer experiences.',
    '<b>Guard bands not updated.</b> The correlation produced the information and nothing acted on it.',
  ],
  roles:[
    {r:'Product engineering', d:'Owns correlation and guard bands'},
    {r:'Test engineer', d:'ATE-side measurement and regression'},
    {r:'Characterization engineer', d:'Bench measurement and uncertainty'},
    {r:'Validation engineer', d:'System-level measurement'},
    {r:'Quality engineer', d:'Escape and over-screen implications'},
  ],
  effort:[['ATE-to-bench correlation',2.5], ['ATE-to-system correlation',2.25], ['Discrepancy analysis',2], ['Uncertainty budget',1.5], ['Guard-band adjustment',1.25], ['Golden unit retention',0.5]],
  entry:[
    'Final test program running from TEST-06',
    'Bench and system results available from bring-up',
    'Correlation fixture available from TEST-04',
  ],
  exit:[
    'Every material discrepancy root-caused, not accepted',
    'Golden units retained and re-measurable',
    'Guard bands updated from what correlation found',
  ],
  dependsOn:['TEST-04','TEST-06','TEST-07','BU-05','BU-08'],
  dependsNote:null,
  feedsInto:['MP-06','MP-08','MP-12'],
  measuredBy:[
    'Discrepancies root-caused against found',
    'Correlation sample size',
    'Guard-band changes traced to correlation findings',
  ],
},

'TEST-11': {
  stage:'testDevelopment', window:[26,34], criticalPath:false,
  purpose:[
    'Build the <b>test data infrastructure</b>—STDF collection, parsing, a yield database and the analysis on top of it—so that test results become information rather than files.',
    'Every yield decision the program makes for the rest of its life is made from this data. Without a pipeline, the data exists as per-lot files nobody can query, and questions that should take an hour take a week or go unasked.',
  ],
  steps:[
    {n:1, text:'Data requirement from yield, quality and characterization', tat:1, lane:'main'},
    {n:2, text:'STDF collection and parsing pipeline', tat:2, lane:'main'},
    {n:3, text:'Traceability keys — lot, wafer, unit, assembly', tat:1.5, lane:'par'},
    {n:4, text:'Yield database and schema', tat:2, lane:'main'},
    {n:5, text:'Retention and archival policy', tat:1.5, lane:'par'},
    {n:6, text:'Analysis and dashboard layer', tat:1.5, lane:'main'},
    {n:7, text:'Alerting on yield excursions', tat:1, lane:'par'},
    {n:8, text:'Deployment and access provisioning', tat:1.5, lane:'main'},
  ],
  flowNote:'Step 3 is the piece that is hardest to add later. A unit\'s test result is only useful if it can be joined to its wafer position, its assembly lot and its bring-up history, and those keys have to be carried from the beginning.',
  consumes:[
    'Sort and final test output formats from TEST-05 and TEST-06',
    'Yield analysis requirements from MP-05',
    'Characterization data needs from TEST-07',
    'Traceability scheme from ASSY-01 and ASSY-09',
    'Data infrastructure and storage',
  ],
  produces:[
    'Data requirements',
    'STDF collection and parsing pipeline',
    'Traceability key scheme',
    'Yield database and schema',
    'Retention and archival policy',
    'Analysis and dashboard layer',
    'Excursion alerting',
    'Deployed and accessible infrastructure',
  ],
  producedBy:[1,2,3,4,5,6,7,8],
  rel:[
    {id:'TEST-D7', rel:'produces', text:'<b>Test data infrastructure and yield database.</b> This activity is the deliverable.'},
    {id:'TEST-D1', rel:'informs', text:'<b>Test plan and test coverage matrix.</b> What the data shows about actual failure modes updates the plan\'s assumptions.'},
  ],
  risks:[
    '<b>Traceability keys added retroactively.</b> Historical data then cannot be joined, and the most valuable early lots become unanalysable.',
    '<b>Pipeline built after the first lots run.</b> The first silicon\'s data is the most informative the program will ever have, and it is the data most often lost.',
    '<b>Retention policy absent.</b> Field returns arrive years later, and the test record for that unit has to still exist.',
    '<b>Dashboards without an alerting layer.</b> A yield excursion is noticed at the weekly review rather than the same day.',
    '<b>Schema not covering characterization.</b> Characterization data has a different shape, and a sort-only schema forces it into a separate silo.',
  ],
  roles:[
    {r:'Test data engineer', d:'Owns the pipeline and database'},
    {r:'Yield engineer', d:'Analysis requirements and excursion definitions'},
    {r:'Quality engineer', d:'Retention policy and traceability'},
    {r:'Test engineer', d:'Output formats and collection'},
    {r:'IT infrastructure', d:'Storage, access and deployment'},
  ],
  effort:[['Collection pipeline',2.5], ['Yield database',2.25], ['Dashboard layer',2], ['Traceability keys',1.5], ['Deployment',1], ['Retention policy',0.75]],
  entry:[
    'Test output formats known from TEST-05 and TEST-06',
    'Yield analysis requirements from MP-05',
    'Traceability scheme agreed with assembly',
  ],
  exit:[
    'Traceability keys carried from the first lot',
    'Pipeline running before first silicon data arrives',
    'Retention policy covering the field-return horizon',
  ],
  dependsOn:['TEST-05','TEST-06','TEST-07','ASSY-09'],
  dependsNote:null,
  feedsInto:['MP-05','MP-09','FAB-09'],
  measuredBy:[
    'First-silicon data captured against produced',
    'Traceability join completeness',
    'Time from excursion to alert',
  ],
},

};
