/* TO — Tapeout & Mask Release (MTO). Eleven activities. Stage w78–86 (8w), 47 M/M.
   FEOL MTO at stage w2, BEOL MTO at stage w6. */
module.exports = {

'TO-01': {
  stage:'tapeout', window:[0,2], criticalPath:true,
  purpose:[
    'Assemble the <b>final GDSII or OASIS database</b> from the closed design—every block, every macro, every layer—and verify that the layer map the foundry will read matches the one the design was built with.',
    'This is a mechanical activity with no tolerance for error. A layer misassigned in the stream-out produces masks that are wrong in a way no verification would have caught, because the design was correct and the translation was not.',
  ],
  steps:[
    {n:1, text:'Closure database intake and provenance check', tat:0.5, lane:'main'},
    {n:2, text:'GDSII / OASIS stream out from the closed database', tat:0.75, lane:'main'},
    {n:3, text:'Macro and hard IP GDS merge', tat:0.5, lane:'par'},
    {n:4, text:'Layer map verification against the foundry definition', tat:0.75, lane:'main'},
  ],
  flowNote:'Step 4 is checked against the foundry\'s layer map rather than the internal one. The two are usually identical and occasionally are not, and the difference is only visible at the mask shop—by which point the masks exist.',
  consumes:[
    'Frozen signoff database from PD-13 and PD-16',
    'Hard macro GDS from AMS-15',
    'Foundry layer map and stream-out rules',
    'Chip finishing from PD-15',
    'Signoff clean status from SO-03',
  ],
  produces:[
    'Database checksum and provenance record',
    'Streamed GDSII / OASIS database',
    'Merged macro and hard IP GDS',
    'Merged macro and IP layers',
    'Layer map verification record',
  ],
  producedBy:[1,2,3,4,4],
  rel:[
    {id:'TO-D1', rel:'produces', text:'<b>Released GDSII / OASIS database with checksum record.</b> This activity is the deliverable, and the checksum is what makes every later reference unambiguous.'},
    {id:'TO-D2', rel:'feeds', text:'<b>Tapeout checklist with signoff matrix.</b> Database assembly and layer verification are checklist entries in their own right.'},
  ],
  risks:[
    '<b>Layer map mismatch.</b> A misassigned layer produces masks that are wrong in a way no design verification would have found.',
    '<b>Macro GDS from the wrong version.</b> An abstract that matched and a layout that did not is discovered at LVS, or worse, not at all.',
    '<b>Stream-out from an unfrozen database.</b> The design has to stop moving before it is streamed, or the streamed version is not the signed-off one.',
    '<b>No checksum.</b> Without one, the question "is this the database we signed off" has no answer.',
    '<b>Assembly compressed to hours.</b> Stream-out on a die this size takes real time, and rushing it is how a merge error is missed.',
  ],
  roles:[
    {r:'Tapeout engineer', d:'Owns assembly, stream-out and provenance'},
    {r:'Physical design lead', d:'Confirms the database is the frozen one'},
    {r:'Macro owners', d:'GDS versions for hard IP'},
    {r:'CAD engineer', d:'Stream-out flow and layer map configuration'},
    {r:'Foundry liaison', d:'Layer map and format requirements'},
  ],
  effort:[['Stream-out',2.5], ['Layer map verification',1.5], ['Macro merge',1], ['Intake and provenance',1]],
  entry:[
    'Signoff database frozen by PD-13',
    'Physical verification clean from SO-03',
    'Foundry layer map and format confirmed',
  ],
  exit:[
    'Layer map verified against the foundry\'s definition, not the internal one',
    'Every macro GDS traced to its released version',
    'Database checksummed and recorded',
  ],
  dependsOn:['PD-13','PD-15','PD-16','SO-03','AMS-15'],
  dependsNote:null,
  feedsInto:['TO-02','TO-03','TO-06','TO-08'],
  measuredBy:[
    'Layer map discrepancies found',
    'Macro versions traced to release',
    'Stream-out reruns required',
  ],
},

'TO-02': {
  stage:'tapeout', window:[0,2], criticalPath:true,
  purpose:[
    'Re-run <b>full-chip physical verification on the released database</b>—not on the one signoff checked, but on the exact bytes going to the mask shop.',
    'Between the signoff run and the released database sit stream-out, macro merge and possibly a late fix. Each is a chance to introduce something. This re-run is short, expensive in compute and non-negotiable: it is the only check that the thing being released is the thing that was verified.',
  ],
  steps:[
    {n:1, text:'Verification setup on the released database', tat:0.5, lane:'main'},
    {n:2, text:'Full-chip DRC re-run', tat:0.75, lane:'main'},
    {n:3, text:'Density and fill re-check', tat:0.5, lane:'par'},
    {n:4, text:'LVS and antenna re-run', tat:0.75, lane:'main'},
    {n:5, text:'Checksum confirmation against the released database', tat:0.5, lane:'par'},
  ],
  flowNote:'Step 5 sounds pedantic and prevents the worst class of error. Verifying one database and releasing another has happened on real programs, and the only defense is confirming the checksum of what was verified against the checksum of what was sent.',
  consumes:[
    'Released database from TO-01',
    'Verification decks from PDK-10',
    'Signoff results from SO-03',
    'Waiver list from SO-10',
    'Compute capacity for full-chip runs',
  ],
  produces:[
    'Verification results on the released database',
    'Full-chip DRC re-run results',
    'Density and fill confirmation',
    'LVS and antenna re-run results',
    'Checksum confirmation record',
  ],
  producedBy:[1,2,3,4,5],
  rel:[
    {id:'TO-D1', rel:'feeds', text:'<b>Released GDSII / OASIS database with checksum record.</b> The release is only complete when the released bytes have been verified.'},
    {id:'TO-D2', rel:'feeds', text:'<b>Tapeout checklist with signoff matrix.</b> Verification on the released database is one of the checklist\'s non-waivable entries.'},
  ],
  risks:[
    '<b>Skipped because signoff was clean.</b> Signoff checked a different database, and the difference between them is exactly what this run exists to catch.',
    '<b>Run on the signoff database rather than the released one.</b> That repeats the earlier check and proves nothing new.',
    '<b>Compute capacity unavailable.</b> A full-chip run takes days and needs to be scheduled, not requested.',
    '<b>New violations discovered with no time to fix.</b> Which is why <code>SO-03</code> has to close cleanly rather than nearly.',
    '<b>Checksums not compared.</b> Verifying one file and releasing another is a documented failure mode with a trivial defense.',
  ],
  roles:[
    {r:'Physical verification engineer', d:'Owns the re-run and its results'},
    {r:'Tapeout engineer', d:'Database provenance and checksums'},
    {r:'CAD infrastructure', d:'Compute capacity for full-chip runs'},
    {r:'Signoff lead', d:'Disposition of anything newly found'},
    {r:'Foundry liaison', d:'Deck versions matching the submission'},
  ],
  effort:[['DRC re-run',3], ['LVS and antenna re-run',2.5], ['Setup',1], ['Density re-check',1], ['Checksum confirmation',0.5]],
  entry:[
    'Database released by TO-01',
    'Decks versioned and matching the submission',
    'Compute capacity scheduled',
  ],
  exit:[
    'Verification run on the exact released database',
    'Checksums confirmed identical between verified and released',
    'No violations outstanding that were not already waived',
  ],
  dependsOn:['TO-01','SO-03','SO-09','PDK-10'],
  dependsNote:null,
  feedsInto:['TO-03','TO-05','TO-06'],
  measuredBy:[
    'New violations found on the released database',
    'Checksum agreement',
    'Run completion before the Go / No-Go',
  ],
},

'TO-03': {
  stage:'tapeout', window:[0,3], criticalPath:true,
  purpose:[
    'Walk the <b>tapeout checklist</b>—every domain, every entry, evidence attached, owner signed—so the Go / No-Go decision is taken on facts rather than on confidence.',
    'The checklist is the program\'s collected memory of what has to be true before masks are cut. Its value is entirely in the evidence: an entry ticked because the owner believes it is true is worth nothing, and the difference between a checklist and a ritual is whether anyone reads the attachments.',
  ],
  steps:[
    {n:1, text:'Checklist assembly per domain', tat:0.75, lane:'main'},
    {n:2, text:'Evidence collection per item', tat:1, lane:'main'},
    {n:3, text:'Gap chasing and escalation', tat:0.75, lane:'par'},
    {n:4, text:'Owner signoff collection', tat:1.25, lane:'main'},
  ],
  flowNote:'Step 3 runs in parallel because it is where the time goes. Chasing an owner who has not signed, or an entry whose evidence does not exist, is the real work—the checklist itself takes an afternoon.',
  consumes:[
    'Signoff results from SO-02 through SO-11',
    'DFT signoff from DFT-08',
    'DV closure from DV-12',
    'Verification results from TO-02',
    'Waiver dispositions from SO-10',
  ],
  produces:[
    'Assembled tapeout checklist',
    'Evidence attached per item',
    'Gap and escalation log',
    'Owner signoff matrix',
  ],
  producedBy:[1,2,3,4],
  rel:[
    {id:'TO-D2', rel:'produces', text:'<b>Tapeout checklist with signoff matrix.</b> This activity is the deliverable, and the signoff matrix is what makes accountability explicit.'},
    {id:'TO-D4', rel:'gates', text:'<b>Go / No-Go decision minutes.</b> The decision reads the checklist; entries without evidence are decisions being taken blind.'},
  ],
  risks:[
    '<b>Entries ticked without evidence.</b> A checklist of assertions is a ritual, and it produces confidence rather than information.',
    '<b>Signoff by proxy.</b> An entry signed by someone other than the accountable owner has moved the signature without moving the accountability.',
    '<b>Checklist assembled at tapeout.</b> It should be maintained across the program; assembling it in the last week means discovering gaps with no time to close them.',
    '<b>Domains missing from the checklist.</b> Test, package and reliability entries are easy to omit from a design-centred checklist and expensive to miss.',
    '<b>Gaps escalated too late.</b> An unsigned entry three days before the Go / No-Go is a decision the meeting cannot take.',
  ],
  roles:[
    {r:'Program manager', d:'Owns the checklist and the signoff matrix'},
    {r:'Domain owners', d:'Sign their own entries with evidence'},
    {r:'Signoff lead', d:'Design-side evidence'},
    {r:'DFT and test leads', d:'Test-side entries'},
    {r:'Package lead', d:'Package and assembly entries'},
  ],
  effort:[['Evidence collection',2], ['Signoff collection',1.5], ['Checklist assembly',1], ['Gap escalation',0.5]],
  entry:[
    'Signoff activities producing evidence',
    'Checklist template maintained across the program',
    'Domain owners identified',
  ],
  exit:[
    'Every entry carries evidence, not an assertion',
    'Signatures from accountable owners, not proxies',
    'Gaps escalated with time to close them',
  ],
  dependsOn:['TO-01','TO-02','SO-10','DFT-08','DV-12'],
  dependsNote:null,
  feedsInto:['TO-04','TO-05'],
  measuredBy:[
    'Entries with attached evidence',
    'Signatures from accountable owners',
    'Gaps open at the Go / No-Go',
  ],
},

'TO-04': {
  stage:'tapeout', window:[1,3], criticalPath:false,
  purpose:[
    'Take every open issue the program is carrying—<b>bugs, waivers, unclosed items</b>—and turn it into an accepted risk with a name against it.',
    'No large program tapes out with nothing open. The question is whether what remains was assessed and accepted, or simply ran out of time. This activity converts a list of loose ends into a set of decisions, each with an owner, a consequence and a mitigation.',
  ],
  steps:[
    {n:1, text:'Open item consolidation across design, verification and test', tat:0.5, lane:'main'},
    {n:2, text:'Risk classification and consequence assessment', tat:0.75, lane:'main'},
    {n:3, text:'Mitigation options per item', tat:0.5, lane:'par'},
    {n:4, text:'Risk acceptance and owner assignment', tat:0.75, lane:'main'},
  ],
  flowNote:'Step 3 is what gives the Go / No-Go meeting something to decide. An item with a mitigation—a test screen, a software workaround, a bin split—is a different decision from one without, and identifying which is which is this activity\'s contribution.',
  consumes:[
    'Open bug list and risk statement from DV-12',
    'Waiver register from SO-10',
    'Test coverage gaps from DFT-07',
    'Package and assembly open items from PKGD-11',
    'Program risk register',
  ],
  produces:[
    'Consolidated open item list',
    'Risk classification with consequences',
    'Mitigation options per item',
    'Risk acceptance record with named owners',
  ],
  producedBy:[1,2,3,4],
  rel:[
    {id:'TO-D3', rel:'produces', text:'<b>Open issue and risk acceptance record.</b> This activity is the deliverable, and named ownership is what distinguishes acceptance from omission.'},
    {id:'TO-D4', rel:'feeds', text:'<b>Go / No-Go decision minutes.</b> The decision is largely a decision about this list.'},
  ],
  risks:[
    '<b>Items carried without assessment.</b> An open issue nobody classified is a risk being accepted without anyone accepting it.',
    '<b>Risk stated qualitatively.</b> "Low risk" gives the decision room nothing; a failure mode, a probability and an affected population gives it a decision.',
    '<b>Mitigations not identified.</b> Many silicon risks can be screened at test or worked around in software, and the option is worth knowing before the gate.',
    '<b>Test and package items excluded.</b> Risk consolidation that covers only design misses the categories that most often cause a late problem.',
    '<b>Acceptance without an owner.</b> An accepted risk with no name against it has nobody watching for it at bring-up.',
  ],
  roles:[
    {r:'Program manager', d:'Owns consolidation and the acceptance record'},
    {r:'Verification lead', d:'Bug risk and consequence'},
    {r:'Signoff lead', d:'Waiver risk'},
    {r:'Product engineering', d:'Screening and mitigation options at test'},
    {r:'Chief architect', d:'Product impact of each accepted risk'},
  ],
  effort:[['Risk classification',1.25], ['Acceptance and ownership',0.75], ['Consolidation',0.5], ['Mitigation options',0.5]],
  entry:[
    'Bug and waiver lists available from DV-12 and SO-10',
    'Test and package open items collected',
    'Risk classification scheme agreed',
  ],
  exit:[
    'Every open item classified with a stated consequence',
    'Mitigation options identified where they exist',
    'Each accepted risk has a named owner',
  ],
  dependsOn:['DV-12','SO-10','DFT-07'],
  dependsNote:null,
  feedsInto:['TO-05','BU-10','MP-09'],
  measuredBy:[
    'Items with a quantified consequence',
    'Accepted risks with a named owner',
    'Mitigations identified against items carried',
  ],
},

'TO-05': {
  stage:'tapeout', window:[1.5,2], criticalPath:true,
  purpose:[
    'Hold the <b>Go / No-Go decision</b>—the moment the program commits several million dollars of masks and a quarter of schedule to the design as it stands.',
    'Half a week of activity and one man-month, preceded by three weeks of preparation. That ratio is correct: a gate argued in the room rather than before it is a gate whose outcome depends on who attended. The meeting exists to take a decision, record its conditions and name who owns them.',
  ],
  steps:[
    {n:1, text:'Decision pack presentation — checklist, risks, readiness', tat:0.2, lane:'main'},
    {n:2, text:'Decision, conditions and dissent capture', tat:0.2, lane:'main'},
    {n:3, text:'Minutes, distribution and condition assignment', tat:0.1, lane:'main'},
  ],
  flowNote:'Step 2 captures dissent deliberately. The objection nobody minuted is the one that resurfaces at first silicon with nothing to point at, and recording it costs a line.',
  consumes:[
    'Tapeout checklist from TO-03',
    'Risk acceptance record from TO-04',
    'Verification results from TO-02',
    'Foundry readiness from TECH-05',
    'Program schedule position from DEF-08',
  ],
  produces:[
    'Decision pack',
    'Go / No-Go decision with conditions',
    'Dissent record',
    'Minutes and condition assignments',
  ],
  producedBy:[1,2,2,3],
  rel:[
    {id:'TO-D4', rel:'produces', text:'<b>Go / No-Go decision minutes.</b> This activity is the deliverable, and the conditions attached are as important as the decision itself.'},
    {id:'TO-D5', rel:'gates', text:'<b>FEOL MTO release package.</b> Mask data is not released before this decision, whatever the schedule pressure.'},
  ],
  risks:[
    '<b>Decision taken because the date arrived.</b> A gate that cannot say no is not a gate, and the organization learns that quickly.',
    '<b>Conditions accepted verbally.</b> A Go granted "subject to" something unrecorded is an unconditional Go.',
    '<b>Wrong people in the room.</b> The decision needs someone who can say no and someone who owns the consequence, and both have to attend.',
    '<b>Dissent unrecorded.</b> It is the cheapest insurance available and it is routinely omitted.',
    '<b>Material presented for the first time in the room.</b> A pack circulated on the day produces a decision based on whoever speaks most confidently.',
  ],
  roles:[
    {r:'Executive sponsor', d:'Chairs the decision and owns the outcome'},
    {r:'Program manager', d:'Presents the pack and records the minutes'},
    {r:'Chief architect', d:'Design readiness and product risk'},
    {r:'Signoff lead', d:'Signoff status and residual risk'},
    {r:'Product engineering', d:'Manufacturability and screening options'},
  ],
  effort:[['Decision pack presentation',0.4], ['Decision and conditions',0.4], ['Minutes and distribution',0.2]],
  entry:[
    'Checklist complete with signatures from TO-03',
    'Risk acceptance record available from TO-04',
    'Decision pack circulated in advance',
  ],
  exit:[
    'Decision recorded with conditions and their owners',
    'Dissent captured in the minutes',
    'Conditions assigned before mask data is released',
  ],
  dependsOn:['TO-02','TO-03','TO-04'],
  dependsNote:null,
  feedsInto:['TO-06','TO-08','MP-09'],
  measuredBy:[
    'Conditions attached and assigned',
    'Dissent recorded',
    'Days between pack circulation and decision',
  ],
},

'TO-06': {
  stage:'tapeout', window:[2,3.5], criticalPath:true,
  purpose:[
    'Prepare and release the <b>front-end layer data</b> to the mask shop—the first of the two mask tapeouts, and the one that starts the fab clock.',
    'FEOL goes first because it is the longest lead item and the least likely to change. Releasing it now starts mask writing while the back-end layers are still absorbing late fixes, which is the entire reason the two releases are separated.',
  ],
  steps:[
    {n:1, text:'FEOL layer selection and data preparation', tat:0.5, lane:'main'},
    {n:2, text:'Mask data preparation handoff — fracture, OPC scope', tat:0.5, lane:'main'},
    {n:3, text:'Submission to the foundry and acceptance confirmation', tat:0.5, lane:'main'},
  ],
  flowNote:'Step 1\'s layer selection has to be exact. A layer released with FEOL that later needs a fix cannot be fixed in the BEOL window, and a layer held back that the mask shop needed delays the whole set.',
  consumes:[
    'Released database from TO-01',
    'Go / No-Go decision from TO-05',
    'Foundry submission format and MDP requirements',
    'Layer split definition from TECH-02',
    'Mask order and slot from TECH-05',
  ],
  produces:[
    'FEOL layer data set',
    'Mask data preparation handoff package',
    'Submission record and foundry acceptance',
  ],
  producedBy:[1,2,3],
  rel:[
    {id:'TO-D5', rel:'produces', text:'<b>FEOL MTO release package and mask order confirmation.</b> This activity is the deliverable, and it is what starts the mask and fab clock.'},
    {id:'TO-D1', rel:'feeds', text:'<b>Released GDSII / OASIS database.</b> The FEOL release is a subset of it, and the two must be traceable to the same checksum.'},
  ],
  risks:[
    '<b>Layer split wrong.</b> A layer released as FEOL that later needs a fix cannot use the BEOL window, and the fix costs a new mask.',
    '<b>Released before the Go / No-Go.</b> Schedule pressure makes this tempting and it removes the gate\'s authority entirely.',
    '<b>MDP requirements misunderstood.</b> Fracture and OPC expectations differ per foundry, and a non-compliant submission is rejected.',
    '<b>Submission not acknowledged.</b> A release nobody confirmed received is a release that may not have started the clock.',
    '<b>Traceability lost between database and submission.</b> The submitted layers have to be provably from the checksummed database.',
  ],
  roles:[
    {r:'Tapeout engineer', d:'Owns layer preparation and submission'},
    {r:'Foundry liaison', d:'Submission, acceptance and MDP interface'},
    {r:'Physical verification engineer', d:'Layer content confirmation'},
    {r:'Program manager', d:'Gate compliance before release'},
    {r:'Procurement', d:'Mask order alignment'},
  ],
  effort:[['Data preparation',1.5], ['MDP handoff',1], ['Submission and acceptance',0.5]],
  entry:[
    'Go / No-Go decision taken in TO-05',
    'Database verified in TO-02',
    'Mask slot confirmed by TECH-05',
  ],
  exit:[
    'Layer split matches the FEOL/BEOL plan exactly',
    'Submission acknowledged by the foundry in writing',
    'Released layers traceable to the database checksum',
  ],
  dependsOn:['TO-01','TO-05','TECH-05'],
  dependsNote:null,
  feedsInto:['TO-07','FAB-01','TO-08'],
  measuredBy:[
    'Submission accepted at first attempt',
    'Release date against the plan',
    'Layer split errors found after release',
  ],
},

'TO-07': {
  stage:'tapeout', window:[3,4], criticalPath:false,
  purpose:[
    'Confirm the <b>FEOL mask order</b> and get a mask shop schedule the program can plan wafer start against.',
    'One man-month of administration that fixes a date the whole downstream schedule hangs on. Mask writing takes weeks, and knowing when the FEOL set will be ready is what tells <code>FAB-02</code> when wafers can start.',
  ],
  steps:[
    {n:1, text:'Mask order confirmation and purchase authorization', tat:0.4, lane:'main'},
    {n:2, text:'Mask shop schedule confirmation', tat:0.3, lane:'main'},
    {n:3, text:'Delivery date communication to the program', tat:0.3, lane:'main'},
  ],
  flowNote:'Step 3 sounds trivial and is where schedules break. A mask completion date known only to the person who confirmed it is a date the rest of the program plans without.',
  consumes:[
    'FEOL submission record from TO-06',
    'Mask cost sheet from TECH-04',
    'Capacity and slot commitment from TECH-05',
    'Purchase authorization',
    'Mask shop schedule',
  ],
  produces:[
    'Confirmed mask order',
    'Mask shop schedule with completion date',
    'Delivery date communication to the program',
  ],
  producedBy:[1,2,3],
  rel:[
    {id:'TO-D5', rel:'feeds', text:'<b>FEOL MTO release package and mask order confirmation.</b> The order confirmation half of the release record.'},
    {id:'TO-D8', rel:'feeds', text:'<b>Full mask set completion record.</b> FEOL completion is the first half of the set.'},
  ],
  risks:[
    '<b>Order placed without confirmed pricing.</b> Mask cost is a large line item and an unconfirmed order produces an invoice nobody budgeted.',
    '<b>Mask shop schedule assumed.</b> Mask writing capacity is shared, and the completion date is the shop\'s to give rather than the program\'s to assume.',
    '<b>Completion date not communicated.</b> Wafer start planning depends on it, and a date held by one person is a date the program does not have.',
    '<b>No escalation path.</b> Mask shop delays happen, and knowing who to call is worth arranging before it is needed.',
    '<b>Order and submission mismatched.</b> The order has to name the exact layer set that was submitted.',
  ],
  roles:[
    {r:'Procurement', d:'Order confirmation and authorization'},
    {r:'Foundry liaison', d:'Mask shop schedule and escalation'},
    {r:'Program manager', d:'Communicates the date into the schedule'},
    {r:'Tapeout engineer', d:'Order and submission consistency'},
    {r:'Finance partner', d:'Cost against the mask budget'},
  ],
  effort:[['Order confirmation',0.5], ['Schedule confirmation',0.3], ['Communication',0.2]],
  entry:[
    'FEOL data submitted and accepted in TO-06',
    'Mask pricing confirmed in TECH-04',
    'Purchase authority available',
  ],
  exit:[
    'Order confirmed against the exact submitted layer set',
    'Mask completion date received and communicated',
    'Escalation contact identified',
  ],
  dependsOn:['TO-06','TECH-04','TECH-05'],
  dependsNote:null,
  feedsInto:['FAB-01','FAB-02','TO-11'],
  measuredBy:[
    'Days from submission to order confirmation',
    'Mask completion date against plan',
    'Cost against the mask budget',
  ],
},

'TO-08': {
  stage:'tapeout', window:[2,6], criticalPath:true,
  purpose:[
    'Use the <b>four weeks between the two mask releases</b> to make metal-layer fixes—the last window in which a design change is possible without a new front-end mask set.',
    'This window is the reason the releases are split. FEOL masks are being cut and cannot change; BEOL is still open, and any fix implementable in metal can still be made. It is a genuine and finite opportunity, and it closes on a date.',
  ],
  steps:[
    {n:1, text:'Fix window scope and admission rules', tat:0.5, lane:'main'},
    {n:2, text:'Metal-layer ECO implementation', tat:1.5, lane:'main'},
    {n:3, text:'Fix prioritization and risk assessment', tat:1, lane:'par'},
    {n:4, text:'ECO verification per fix', tat:1, lane:'main'},
    {n:5, text:'Equivalence and consistency check per fix', tat:1, lane:'par'},
    {n:6, text:'Window close and BEOL database freeze', tat:1, lane:'main'},
  ],
  flowNote:'Step 1 has to be strict. Every late fix carries risk, and a window with no admission rules fills with changes that individually look safe and collectively make the BEOL database something nobody has verified as a whole.',
  consumes:[
    'Released database from TO-01',
    'Late findings from bring-up preparation, verification and signoff',
    'Spare cell and metal-only strategy from PD-14',
    'Go / No-Go conditions from TO-05',
    'Equivalence methodology from SO-09',
  ],
  produces:[
    'Fix window scope and admission rules',
    'Implemented metal-layer ECOs',
    'Fix prioritization and risk record',
    'Per-fix verification results',
    'Per-fix equivalence and consistency results',
    'Frozen BEOL database',
  ],
  producedBy:[1,2,3,4,5,6],
  rel:[
    {id:'TO-D6', rel:'produces', text:'<b>BEOL ECO log covering the fix window.</b> This activity is the deliverable, and the log is what makes the BEOL database traceable.'},
    {id:'TO-D7', rel:'feeds', text:'<b>BEOL MTO release package.</b> The database released to BEOL is the FEOL database plus this window\'s fixes.'},
  ],
  risks:[
    '<b>Window used as general contingency.</b> Fixes admitted without rules accumulate into a database that differs from the verified one in ways nobody assessed as a whole.',
    '<b>Fix requiring base layers.</b> If <code>PD-14</code>\'s spare cell strategy was not put in place, the fix cannot be made in metal and the window is useless.',
    '<b>Verification per fix but not in combination.</b> Individually correct changes can interact, and the combined database needs a check of its own.',
    '<b>Window extended.</b> BEOL mask release has a date; extending the window pushes the whole mask set and with it wafer start.',
    '<b>Equivalence skipped for speed.</b> A metal ECO can change function, and the only detector is an equivalence run.',
  ],
  roles:[
    {r:'Physical design lead', d:'Owns implementation and the window'},
    {r:'Program manager', d:'Admission rules and prioritization'},
    {r:'Verification lead', d:'Per-fix and combined verification'},
    {r:'Equivalence engineer', d:'Equivalence per fix and at window close'},
    {r:'Signoff lead', d:'Re-verification scope for changed layers'},
  ],
  effort:[['ECO implementation',4], ['ECO verification',2.5], ['Prioritization and risk',1.5], ['Equivalence checks',1.5], ['Window close',0.5]],
  entry:[
    'FEOL released in TO-06',
    'Admission rules agreed before the window opens',
    'Spare cell capacity available from PD-14',
  ],
  exit:[
    'Every fix implementable in metal, none requiring base layers',
    'Combined database verified, not only individual fixes',
    'Window closed on its date, not extended',
  ],
  dependsOn:['TO-01','TO-05','TO-06','PD-14'],
  dependsNote:null,
  feedsInto:['TO-09','TO-10','BU-11'],
  measuredBy:[
    'Fixes admitted against fixes requested',
    'Fixes implementable in metal',
    'Window closed on the planned date',
  ],
},

'TO-09': {
  stage:'tapeout', window:[3.5,6], criticalPath:true,
  purpose:[
    'Re-verify the <b>metal stack after the fix window</b>—DRC, LVS, antenna, density on the changed layers—before the back-end data is released.',
    'The BEOL database is not the one that was signed off. It carries the fix window\'s changes, and every one of them touched routing. This re-verification is what makes the BEOL release as trustworthy as the FEOL one, and it has to fit inside the window\'s tail.',
  ],
  steps:[
    {n:1, text:'Re-verification scope on the changed layers', tat:0.5, lane:'main'},
    {n:2, text:'DRC and antenna verification on the metal stack', tat:1, lane:'main'},
    {n:3, text:'Timing impact confirmation for the applied fixes', tat:0.75, lane:'par'},
    {n:4, text:'LVS and density re-check', tat:1, lane:'main'},
  ],
  flowNote:'Step 1 decides between a targeted re-run and a full one. Targeted is faster and risks missing an interaction; full is safe and may not fit the window. The scope decision has to be made on what the fixes actually touched.',
  consumes:[
    'Frozen BEOL database from TO-08',
    'ECO log from TO-08',
    'Verification decks from PDK-10',
    'Timing analysis capability from SO-02',
    'Signoff baseline from SO-03',
  ],
  produces:[
    'Re-verification scope decision',
    'DRC and antenna results on the metal stack',
    'Timing impact confirmation',
    'LVS and density re-check results',
  ],
  producedBy:[1,2,3,4],
  rel:[
    {id:'TO-D7', rel:'feeds', text:'<b>BEOL MTO release package.</b> The release is only defensible if the changed layers were re-verified.'},
    {id:'TO-D6', rel:'feeds', text:'<b>BEOL ECO log.</b> The log and the re-verification results are read together—what changed, and what was checked afterwards.'},
  ],
  risks:[
    '<b>Scope too narrow.</b> A targeted re-run that misses an interaction between two fixes releases a violation into the mask set.',
    '<b>Timing not re-confirmed.</b> Metal ECOs change delay, and a fix that breaks timing has replaced one problem with another.',
    '<b>Re-verification not fitting the window.</b> Full-chip runs take days, and a window planned without them cannot accommodate them.',
    '<b>LVS skipped because the change was metal-only.</b> Metal changes connectivity, which is exactly what LVS checks.',
    '<b>Results arriving after the release.</b> Verifying after submission is verifying something already committed to masks.',
  ],
  roles:[
    {r:'Physical verification engineer', d:'Owns the re-verification'},
    {r:'Physical design lead', d:'Scope decision based on what changed'},
    {r:'Timing engineer', d:'Timing impact of the applied fixes'},
    {r:'Tapeout engineer', d:'Release gating on the results'},
    {r:'Signoff lead', d:'Disposition of anything newly found'},
  ],
  effort:[['DRC and antenna verification',2.5], ['LVS and density re-check',2], ['Scope definition',0.75], ['Timing confirmation',0.75]],
  entry:[
    'BEOL database frozen by TO-08',
    'ECO log complete',
    'Verification decks and capacity available',
  ],
  exit:[
    'Scope justified against what the fixes touched',
    'Timing re-confirmed for every applied fix',
    'Results complete before BEOL data is released',
  ],
  dependsOn:['TO-08','PDK-10','SO-02'],
  dependsNote:null,
  feedsInto:['TO-10'],
  measuredBy:[
    'Violations found after the fix window',
    'Timing changes introduced by fixes',
    'Re-verification completion before release',
  ],
},

'TO-10': {
  stage:'tapeout', window:[6,7.5], criticalPath:true,
  purpose:[
    'Prepare and release the <b>back-end layer data</b>—the second mask tapeout, and the moment the design is fully committed to silicon.',
    'BEOL release is the real tapeout. After it nothing about the design can change without a new mask set, and the milestone the program has been working toward for eighty weeks is this submission being accepted.',
  ],
  steps:[
    {n:1, text:'BEOL layer data preparation from the re-verified database', tat:0.5, lane:'main'},
    {n:2, text:'Mask data preparation handoff', tat:0.5, lane:'main'},
    {n:3, text:'Submission to the foundry and acceptance confirmation', tat:0.5, lane:'main'},
  ],
  flowNote:'The layer set here has to be exactly the complement of what <code>TO-06</code> released. A layer released twice or not at all produces a mask set that is either wrong or incomplete, and the mask shop will not necessarily notice.',
  consumes:[
    'Re-verified BEOL database from TO-09',
    'FEOL layer split from TO-06',
    'Foundry submission requirements',
    'Mask order framework from TO-07',
    'ECO log from TO-08',
  ],
  produces:[
    'BEOL layer data set',
    'Mask data preparation handoff package',
    'Submission record and foundry acceptance',
  ],
  producedBy:[1,2,3],
  rel:[
    {id:'TO-D7', rel:'produces', text:'<b>BEOL MTO release package and mask order confirmation.</b> This activity is the deliverable, and the milestone the stage carries—Tapeout.'},
    {id:'TO-D6', rel:'feeds', text:'<b>BEOL ECO log.</b> The released database is the FEOL one plus the logged fixes, and the two travel together.'},
  ],
  risks:[
    '<b>Layer set not complementary to FEOL.</b> A layer released twice or omitted produces an incomplete or contradictory mask set.',
    '<b>Released before re-verification completes.</b> The fix window\'s changes are then committed unchecked.',
    '<b>Submission rejected on format.</b> BEOL layers have their own OPC and fracture requirements, and a rejection costs days against a running FEOL clock.',
    '<b>No acceptance confirmation.</b> An unconfirmed release may not have started the second mask clock.',
    '<b>Traceability broken.</b> The BEOL database differs from the checksummed original, and the difference has to be exactly the ECO log.',
  ],
  roles:[
    {r:'Tapeout engineer', d:'Owns preparation and submission'},
    {r:'Foundry liaison', d:'Submission, acceptance and MDP interface'},
    {r:'Physical verification engineer', d:'Confirms re-verification complete'},
    {r:'Program manager', d:'Milestone confirmation and communication'},
    {r:'Configuration manager', d:'Database traceability and ECO log'},
  ],
  effort:[['Data preparation',1.5], ['MDP handoff',1], ['Submission and acceptance',0.5]],
  entry:[
    'BEOL re-verification complete in TO-09',
    'FEOL layer split known from TO-06',
    'Foundry submission requirements confirmed',
  ],
  exit:[
    'Layer set exactly complementary to the FEOL release',
    'Submission acknowledged in writing',
    'Database difference from the original traced to the ECO log',
  ],
  dependsOn:['TO-08','TO-09','TO-06'],
  dependsNote:null,
  feedsInto:['TO-11','FAB-03'],
  measuredBy:[
    'Submission accepted at first attempt',
    'Layer set completeness against the split',
    'Release date against plan',
  ],
},

'TO-11': {
  stage:'tapeout', window:[7,8], criticalPath:false,
  purpose:[
    'Confirm the <b>BEOL order and track the mask set to completion</b>, so that <code>FAB-05</code> knows when back-end layers will be available and the line does not stall mid-lot.',
    'The BEOL masks are needed several weeks into wafer processing, not at wafer start. Tracking them to completion is what confirms that the parallel schedule the FEOL/BEOL split assumed actually holds.',
  ],
  steps:[
    {n:1, text:'BEOL mask order confirmation', tat:0.4, lane:'main'},
    {n:2, text:'Full mask set completion tracking', tat:0.3, lane:'main'},
    {n:3, text:'Mask availability communication to fabrication', tat:0.3, lane:'main'},
  ],
  flowNote:'Step 2 tracks the whole set rather than the second half. A mask set is only usable when every layer is complete, and the last layer to finish is the one that decides.',
  consumes:[
    'BEOL submission record from TO-10',
    'Mask order framework from TO-07',
    'Mask shop schedules',
    'Wafer processing plan from FAB-04',
    'Cost sheet from TECH-04',
  ],
  produces:[
    'Confirmed BEOL mask order',
    'Full mask set completion tracking',
    'Mask availability communication to fabrication',
  ],
  producedBy:[1,2,3],
  rel:[
    {id:'TO-D8', rel:'produces', text:'<b>Full mask set completion record.</b> This activity is the deliverable, and it is what confirms the split schedule held.'},
    {id:'TO-D7', rel:'feeds', text:'<b>BEOL MTO release package and mask order confirmation.</b> The order half of the BEOL release record.'},
  ],
  risks:[
    '<b>BEOL masks late against the wafer schedule.</b> Wafers reach the metallization steps and stop, which is worse than starting late.',
    '<b>Completion tracked per layer rather than per set.</b> The set is usable when the last layer is done, and per-layer optimism hides that.',
    '<b>Availability not communicated to fabrication.</b> The line plans against the date, and a date nobody passed on is a date the line does not have.',
    '<b>Order mismatched to submission.</b> The order has to name exactly the layers submitted, and BEOL sets are large.',
    '<b>No contingency for a mask defect.</b> Masks fail inspection sometimes, and a remake takes weeks.',
  ],
  roles:[
    {r:'Procurement', d:'Order confirmation'},
    {r:'Foundry liaison', d:'Mask shop tracking and escalation'},
    {r:'Program manager', d:'Communicates availability into the fab plan'},
    {r:'Tapeout engineer', d:'Order and submission consistency'},
    {r:'Operations planner', d:'Wafer schedule alignment'},
  ],
  effort:[['Order confirmation',0.4], ['Set completion tracking',0.4], ['Communication',0.2]],
  entry:[
    'BEOL data submitted and accepted in TO-10',
    'Mask order framework established in TO-07',
    'Wafer processing plan available from FAB-04',
  ],
  exit:[
    'Order confirmed against the submitted layer set',
    'Set completion tracked to the last layer',
    'Availability communicated to fabrication against the line schedule',
  ],
  dependsOn:['TO-07','TO-10'],
  dependsNote:null,
  feedsInto:['FAB-03','FAB-05','FAB-09'],
  measuredBy:[
    'Mask set completion against the wafer schedule',
    'Layers remaining at each status check',
    'Mask remakes required',
  ],
},

};
