/**
 * /data/deliverableTemplates.ts — the sign-off workbooks a key deliverable's
 * handover can be started from.
 *
 * A gate — a freeze, a closure, a signoff — is confirmed item by item: every
 * item carries a result, its evidence and a status, and the stage lead or the
 * TPM confirms each on that evidence. These deliverables are confirmed in the
 * app (the Checklist beside the Handover heading); the sign-off page also
 * offers an Excel workbook of the same items, generated by
 * tools/deliverable-templates/build.ts from the write-up of the activity that
 * produces each one, and served from public/templates.
 *
 * Keyed by deliverable reference, which is how the handover knows its row.
 * Client-safe: a list of paths.
 */
export interface DeliverableTemplate {
  /** Where the file is served. */
  href: string;
  /** What the download is called. */
  filename: string;
}

const xlsx = (ref: string, slug: string): DeliverableTemplate => ({
  href: `/templates/${ref}-${slug}.xlsx`,
  filename: `${ref}-${slug}-template.xlsx`,
});

export const DELIVERABLE_TEMPLATES: Record<string, DeliverableTemplate> = {
  'ERTL-D7': xlsx('ERTL-D7', 'rtl-freeze-package'),
  'EDV-D7': xlsx('EDV-D7', 'dv-closure-signoff'),
  'MRAM-D7': xlsx('MRAM-D7', 'emram-integration-signoff'),
  'PMU-D7': xlsx('PMU-D7', 'pmu-always-on-signoff'),
  'FPV-D6': xlsx('FPV-D6', 'fpga-verification-signoff'),
  'EDFT-D7': xlsx('EDFT-D7', 'dft-signoff-entry'),
  'EPD-D8': xlsx('EPD-D8', 'signoff-ready-database-handoff'),
  'ESO-D7': xlsx('ESO-D7', 'signoff-summary-design-freeze'),
};

export const templateFor = (ref: string | null | undefined): DeliverableTemplate | undefined =>
  ref ? DELIVERABLE_TEMPLATES[ref] : undefined;

/**
 * The gates that can be confirmed in the app — every one with a workbook.
 * ESO-D7 was tried first; the others followed it.
 */
const IN_APP = new Set(Object.keys(DELIVERABLE_TEMPLATES));

export const signoffInApp = (ref: string | null | undefined): boolean => !!ref && IN_APP.has(ref);
